{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "SFMOHD API",
    "description" : "The first version of the SFMO Housing API is an exciting step in providing information to listings to apply.  We want to make it easy for you, to build apps and have open access to city Listing data to apply for affordable housing\nThere are two ways to connect to the api-\nThe listing data is public domain and can be accessed at <publicsite>/salesforce.com/apexrest\nYou can connect your listing information to this\nTo connect a full fledge application to the city data in or[...]",
    "version" : "2.0.0"
  },
  "servers" : [ {
    "url" : "https://salesforce.com/services/apexrest"
  } ],
  "security" : [ {
    "restrictedAccess" : [ "Listing", "ListingDetails", "LotteryMember", "UnitSummary", "ShortForm", "Person", "ami" ]
  }, {
    "public" : [ ]
  } ],
  "paths" : {
    "/Listing/*" : {
      "get" : {
        "tags" : [ "Listing" ],
        "description" : "API used to return the list of Listings that match criteria"
      }
    },
    "/Listing/LotteryResult/Summary/{listingID}" : {
      "get" : {
        "tags" : [ "Listing" ],
        "description" : "API used to return the Lottery results",
        "deprecated" : true
      }
    },
    "/Listing/LotteryResult/Bucket/{listingID}" : {
      "get" : {
        "tags" : [ "Listing" ],
        "description" : "This returns the bucket of lottery results, application results are empty the bucket of results is a list of applicaition results by preference - we may need to add additional filter parameters to define result set size - default is to return top 100",
        "deprecated" : true
      }
    },
    "/Listing/LotteryResult/{listingID}/{lotteryNumber}" : {
      "get" : {
        "tags" : [ "Listing" ],
        "description" : "This returns the Listing result - with 1 applicationResult inside this is the Application with the appropriate lottery number.  If no lotteryNumber fits, applicationsResult will be empty.  If listingID\n is incorrect it will error."
      }
    },
    "/Listing/LotteryResult/{listingID}" : {
      "get" : {
        "tags" : [ "Listing" ],
        "description" : "This returns the Listing result - with applicationResults for the listing.  If listingId doesn't  fit, applicationsResult will be empty.  If listingId isIncorrect it will error."
      }
    },
    "/ListingDetails/*" : {
      "get" : {
        "tags" : [ "Listing" ],
        "description" : "This returns the Listing information and its summary information."
      }
    },
    "/ListingDetails/Criteria/" : {
      "get" : {
        "tags" : [ "Listing" ],
        "description" : "This queries the Listing information and its summary information.",
        "deprecated" : true
      }
    },
    "/Listing/EligibilityCheck/{listingid}" : {
      "get" : {
        "tags" : [ "Listing" ],
        "description" : "API used to return the eligibility info for a given listing that matches criteria"
      }
    },
    "/Listing/Units/{listingid}" : {
      "get" : {
        "tags" : [ "Listing" ],
        "description" : "returns Units for listing based on Listing ID."
      }
    },
    "/Listing/Units/" : {
      "get" : {
        "tags" : [ "Listing" ],
        "description" : "returns Units for listing based on Listing ID",
        "deprecated" : true
      }
    },
    "/LotteryPreference/{id}'" : {
      "get" : {
        "tags" : [ "Listing" ],
        "description" : "returns lottery Preference by ID",
        "deprecated" : true
      }
    },
    "/LotteryPreference/" : {
      "get" : {
        "tags" : [ "Listing" ],
        "description" : "returns lottery preferences by ID.  If not id is provided it returns all lottery preferences",
        "deprecated" : true
      }
    },
    "/Listing/UnitSummary/{listingid}" : {
      "get" : {
        "tags" : [ "Listing" ],
        "description" : "API used to return the list of Units summary for a given listing"
      }
    },
    "/Listing/UnitStats/{listingid}" : {
      "get" : {
        "tags" : [ "Listing" ],
        "description" : "returns unitType and totalUnits of Listing. Also returns the Minimum Occupancy, Maximum Occupancy, Minimum Square Foot and Maximum Square Foot from the Units"
      }
    },
    "/Listing/Preferences/{listingID}" : {
      "get" : {
        "tags" : [ "Listing" ],
        "description" : "API used to return the list of Listing Preferences"
      }
    },
    "/LotteryMember/*" : {
      "get" : {
        "tags" : [ "Listing" ],
        "description" : "returns lottery Members for listing - either id or ids is required",
        "security" : [ {
          "restrictedAccess" : [ "LotteryMember", "Listing" ]
        } ]
      }
    },
    "/ami/*" : {
      "get" : {
        "tags" : [ "AMI" ],
        "description" : "Returns the ami table value based on 2 passed in parameters"
      }
    },
    "/ami/calc/" : {
      "get" : {
        "tags" : [ "AMI" ],
        "description" : "Calculates the percentage ami based off household and amount and returns ami",
        "deprecated" : true
      }
    },
    "/ami/charts/" : {
      "get" : {
        "tags" : [ "AMI" ],
        "description" : "returns the list of application charts type and years for those chart types",
        "deprecated" : true
      }
    },
    "/Person/{contactid}" : {
      "get" : {
        "tags" : [ "Person" ],
        "description" : "This returns a Perons account data.  This is their contact information"
      }
    },
    "/Person/" : {
      "post" : {
        "tags" : [ "Person" ],
        "description" : "Check for valid person contactId Id and update",
        "security" : [ {
          "restrictedAccess" : [ "Person" ]
        } ]
      }
    },
    "/agents/" : {
      "get" : {
        "tags" : [ "Agents" ],
        "description" : "deletes specified Rental Assistance"
      }
    },
    "/RentalAssistance/{rentalAssistanceId}" : {
      "delete" : {
        "tags" : [ "Rental Assistance" ],
        "description" : "deletes specified Rental Assistance"
      }
    },
    "/shortForm/list/{ContactID}" : {
      "get" : {
        "tags" : [ "Shortform Application" ],
        "description" : "This returns shortform type data (applications related to the contact) based on request criteria.",
        "security" : [ {
          "restrictedAccess" : [ "ShortForm" ]
        } ]
      }
    },
    "/shortForm/{shortFormId}" : {
      "get" : {
        "tags" : [ "Shortform Application" ],
        "description" : "ShortForm type data based on request criteria.",
        "security" : [ {
          "restrictedAccess" : [ "ShortForm" ]
        } ]
      }
    },
    "/LeasingAgentPortal/shortForm/{shortFormId}" : {
      "get" : {
        "tags" : [ "Shortform Application - Leasing Agent Portal" ],
        "description" : "ShortForm type data based on request criteria.",
        "security" : [ {
          "restrictedAccess" : [ "ShortForm" ]
        } ]
      }
    },
    "/LeasingAgentPortal/shortForm/Archive/{snapshotId}" : {
      "get" : {
        "tags" : [ "Shortform Application - Leasing Agent Portal" ],
        "description" : "ShortForm type data based on request criteria.",
        "security" : [ {
          "restrictedAccess" : [ "ShortForm" ]
        } ]
      }
    },
    "/shortForm/" : {
      "post" : {
        "tags" : [ "Shortform Application" ],
        "description" : "get Application and its Application Members by passing the application id",
        "security" : [ {
          "restrictedAccess" : [ "ShortForm" ]
        } ]
      }
    },
    "/LeasingAgentPortal/shortForm/" : {
      "post" : {
        "tags" : [ "Shortform Application - Leasing Agent Portal" ],
        "description" : "get Application and its Application Members by passing the application id",
        "security" : [ {
          "restrictedAccess" : [ "ShortForm" ]
        } ]
      },
      "put" : {
        "tags" : [ "Shortform Application - Leasing Agent Portal" ],
        "description" : "get Application and its Application Members by passing the application id",
        "security" : [ {
          "restrictedAccess" : [ "ShortForm" ]
        } ]
      }
    },
    "/shortForm/delete/{shortformid}" : {
      "delete" : {
        "tags" : [ "Shortform Application" ],
        "description" : "deletes specified application",
        "security" : [ {
          "restrictedAccess" : [ "ShortForm" ]
        } ]
      }
    },
    "/shortForm/delete/" : {
      "post" : {
        "tags" : [ "Shortform Application" ],
        "description" : "deletes specified application",
        "security" : [ {
          "restrictedAccess" : [ "ShortForm" ]
        } ]
      }
    },
    "/shortForm/Attachment/" : {
      "post" : {
        "tags" : [ "Shortform Application" ],
        "description" : "upload attachment to shortform.",
        "security" : [ {
          "restrictedAccess" : [ "ShortForm" ]
        } ]
      }
    },
    "/shortForm/Attachment/{FileId}" : {
      "get" : {
        "tags" : [ "Shortform Application" ],
        "description" : "upload attachment to shortform.",
        "security" : [ {
          "restrictedAccess" : [ "ShortForm" ]
        } ]
      }
    },
    "/shortForm/contact/delete" : {
      "post" : {
        "tags" : [ "Shortform Application" ],
        "description" : "deletes specified contact from household  - use \"delete\" instead",
        "security" : [ {
          "restrictedAccess" : [ "ShortForm" ]
        } ]
      }
    },
    "/shortForm/File/*" : {
      "post" : {
        "tags" : [ "Shortform Application" ],
        "description" : "API used to upload a file into salesforce to an Application",
        "security" : [ {
          "restrictedAccess" : [ "ShortForm" ]
        } ]
      }
    },
    "/shortForm/File/{attachmentId}" : {
      "get" : {
        "tags" : [ "Shortform Application" ],
        "description" : "upload attachment to shortform.",
        "security" : [ {
          "restrictedAccess" : [ "ShortForm" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "restrictedAccess" : {
        "type" : "oauth2",
        "flows" : {
          "password" : {
            "tokenUrl" : "https://test.salesforce.com/services/oauth2/token",
            "scopes" : {
              "Listing" : "Information of a particular listing, including qualifications, to apply for listing as well as details on the listing itself - this is available via public and pwd based oauth\n",
              "ListingDetails" : "Listing information coupled with detailed information on unit summary data, and if a criteria was passed in the request, it will show the \"match\" on the citeria\n",
              "UnitSummary" : "summary information on particular unit types for a listing",
              "ShortForm" : "the shortform application for a particular person for a particular listing this includes contact/household information for a person",
              "LotteryMember" : "current lottery memebers for a given listing",
              "Person" : "primary applicant/person who will have applications connected to them.",
              "ami" : "ami calculation"
            }
          }
        }
      },
      "public" : {
        "type" : "apiKey",
        "name" : "access_token",
        "in" : "query"
      }
    }
  }
}