openapi: 3.0.0
servers:
  - description: Тестовый сервер
    url: https://galeev.dev.b24.medianation.ru/local/tools/api/bp
  - description: Корп портал
    url: https://b24.medianation.ru/local/tools/api/bp
info:
  description: "API для взаимодействия с бизнес-процессами в b24.medianation.ru"
  version: "1.1.2"
  title: Bitrix 24 API - Взаимодействия с БП
  contact:
    email: f1gure09x@gmail.com
tags:
  - name: БП Счета
    description: API для бизнес-процессов со счетами
  - name: БП Акты выполненных работ
    description: API для бизнес-процессов с актами выполненных работ
paths:
  /addInvoice/:
    post:
      tags:
        - БП Счета
      summary: Отправка данных об оплате счета
      operationId: addInvoiceId
      description: Отправка данных об оплате счета в бизнес-процесс. Соотвествие счета подбирается по номеру и указанному ИНН
      responses:
        '200':
          description: 'ОК'
        '206':
          description: 'Ошибка, не удалось передать оплату для одного или нескольких счетов: [{id}, ..]'
        '400':
          description: 'Ошибка, проверьте отправляемые данные'
        '401':
          description: 'Ошибка, не удалось передать оплату'
        '403':
          description: 'Ошибка, нет доступа'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addInvoice'
        description: Входные параметры
      security:
        - BasicAuth: []
  /act/confirmStatement/:
    post:
      tags:
        - БП Акты выполненных работ
      summary: Подтверждения получения акта
      operationId: actConfirmStatementId
      description: Отправка данных о полученных актах в бизнес-процесс. Соответствие акта по ИНН и номеру акта
      responses:
        '200':
          description: 'ОК'
        '206':
          description: 'Ошибка, не удалось передать информацию для одного или нескольких актов: [{id}, ..]'
        '400':
          description: 'Ошибка, проверьте отправляемые данные'
        '401':
          description: 'Ошибка, не удалось передать информацию об акте'
        '403':
          description: 'Ошибка, нет доступа'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/actConfirmStatement'
        description: Входные параметры
      security:
        - BasicAuth: []
  /act/addStatement/:
    post:
      tags:
        - БП Акты выполненных работ
      summary: Добавление акта
      operationId: actAddStatementId
      description: Создание акта и бизнес-процесса
      responses:
        '200':
          description: 'ОК'
        '400':
          description: 'Ошибка, проверьте отправляемые данные'
        '401':
          description: 'Ошибка, не удалось передать информацию об акте'
        '403':
          description: 'Ошибка, нет доступа'
        '405':
          description: 'Ошибка, не найдена компания в CRM с ИНН: {ИНН}'
        '406':
          description: 'Ошибка, в CRM существует несколько компаний с таким ИНН: [{company_id}, ..]'
        '407':
          description: 'Ошибка, акт с номером {номер} за {год} год для {ИНН} уже существует!'
        '408':
          description: 'Ошибка, {описание ошибки связанной с трудометром}'
        '500':
          description: 'Внутренняя ошибка'
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/actAddStatement'
        description: Входные параметры
      security:
        - BasicAuth: []
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    addInvoice:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ManufInvoice'
    actConfirmStatement:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ManufActConfirmStatement'
    actAddStatement:
      required:
        - number
        - inn
        - sum
        - year
        - statement
      properties:
        number:
          type: string
          format: string
          example: "9991"
        inn:
          type: string
          format: inn
          example: '77103118782'
        sum:
          type: number
          format: float
          example: 5000.00
        year:
          type: number
          format: int
          example: 2019
        statement:
          type: string
          format: binary
        invoice:
          type: string
          format: binary
      type: object
    ManufInvoice:
      required:
        - number
        - inn
        - sum
        - date_invoice
        - date_pay
      properties:
        number:
          type: string
          format: string
          example: "24"
        inn:
          type: string
          format: inn
          example: '7777777777'
        sum:
          type: number
          format: float
          example: 50000.00
        date_invoice:
          type: string
          format: date
          example: '2016-08-26'
        date_pay:
          type: string
          format: date
          example: '2016-08-29'
      type: object
    ManufActConfirmStatement:
      required:
        - number
        - inn
      properties:
        number:
          type: string
          format: string
          example: "24"
        inn:
          type: string
          format: inn
          example: '7777777777'
      type: object
