openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Sales API'
  description: |
      Ths is the second step in our Basic Integration. It allows you to tell us the result of the offering you received from the Quote API. I.E. Did the customer take up the or decline the offer?

      We only require you to inform us of the customer's decision if the customer goes on to purchase the products for which the offering was made. I.E. You only need to call this service when the customer completes the checkout process on your site.

      Both positive and negative responses are required to allow us to identify, report and optimise conversion.
  contact:
    email: technology@bookingprotect.com
servers:
  - url: 'https://sales.insure-hub.net'
    description: Production
  - url: 'https://sales.uat.insure-hub.net'
    description: UAT
tags:
  - name: sales
    description: 'Report the outcome of an offering'
paths:
  /sales:
    post:
      tags:
        - sales
      summary: Report the outcome of an offering
      operationId: reportSales
      description: Report the outcome of an offering
      parameters: 
        - in: header
          name: X-InsuranceHub-VendorId
          schema:
            type: string
            format: uuid
          required: true
          example: 0aa8b695-67dd-4629-9f1e-233d0445d357
          description: 'Your unique vendor identifier - as displayed in your Account page.'
        - in: header
          name: X-InsuranceHub-AuthToken
          schema:
            type: string
          required: true
          description: |
            The authentication token value is generated by concatenating your vendor identifier (for example 59b9f7da07bde3119956002186eb0899) with current ***UTC date*** in the format ddMMyyyy (for example, the 5th October 2018 would be 05102018).

            An HMAC digest is then generated from the resulting string using the SHA1 hash function and your API Key as the HMAC key. Finally, this value is then base64 encoded.

            Requests with invalid or missing authentication headers will receive a status 401 Unauthorized
      responses:
        '200':
          description: 'OK - OfferingResult recorded successfully'
        '400':
          description: 'Bad Request - The data in the request is either invalid or incomplete'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '401':
          description: 'Unauthorized - Invalid authentication headers. Check the header X-InsuranceHub-VendorId is not missing and has the correct value. Check the header X-InsuranceHub-AuthToken is not missing. Ensure you are using UTC date and that the output of the HMAC SHA1 digest is base64 encoded'
        '403':
          description: 'Forbidden - You can not read, create or update data for the specified vendor'
        '409':
          description: 'Conflict - An OfferingResult has already been received for the specified offeringId.'
        '500':
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/offeringResult'
        description: 'result of offering'
        
components:
  schemas:
    offeringResult:
      required:
        - vendorId
        - offeringId
        - vendorSaleReference
        - customerSurname
        - customerForename
        - sales
      properties:
        vendorId:
          type: string
          format: uuid
          example: 0aa8b695-67dd-4629-9f1e-233d0445d357
          description: 'Your unique vendor identifier.'
        offeringId:
          type: string
          format: uuid
          example: fa4ecb5d-f0a6-45e6-89ef-d425d6b064f6
          description: 'The unique identifier of the Offering received from the Quote API'
        vendorSaleReference:
          type: string
          example: abc123xyz
          description: |
            Your sales reference. This is usually the order/invoice number. We must be able to correlate this reference with the customer's proof of purchase in the event the customer makes an application for refund.

            Not required when sold is false for all ProductOfferingResults.
        customerSurname:
          type: string
          example: Wayne
          description: |
            The customer's surname.

            Not required when sold is false for all ProductOfferingResults.
        customerForename:
          type: string
          example: Bruce
          description: |
            The customer's forename.

            Not required when sold is false for all ProductOfferingResults.
        sales:
          type: array
          items:
            $ref: '#/components/schemas/productOfferingResult'
          description: 'Array of ProductOfferingResults that relate to the individual ProductOfferings returned in the Offering from the Quote API'
    productOfferingResult:
      properties:
        productOfferingId:
          type: string
          format: uuid
          example: 
          description: 'The unique identifier of the ProductOffering to which it relates.'
        sold:
          type: boolean
          description: 'Did the customer choose to purchase the protection?'
    error:
      properties:
        message:
          type: string
          example: Invalid Request
          description: 'Short description of the error.'
        validationMessages:
          type: array
          items:
            type: string
            example: 'Product missing completionDate'
          description: 'Array of validation messages.'
