openapi: 3.0.1

servers:
  - description: "Develop environment"
    url: "https://justeat-api.yolo-insurance.com/{basePath}"
    variables:
      basePath:
        default: "sys"

info:
  description: |-
    API per il progetto P30 JustEat. Per info https://gitlab.com/yolo-insurance/issue-tracker/business-wiki/-/wikis/Just-Eat.

    Develop API key: **VHXtcR1PYB4tpqK2s0gxo7lPMHgeD7Cx8p7DQDzg**
  version: "1.0.0"
  title: "Yolo - P30 JustEat"
  contact:
    email: "contacts@yolo-insurance.com"
    name: "Yolo"

paths:
  /users:
    post:
      summary: "User registration"
      operationId: "userRegistration"
      description: "Register a new user"
      parameters:
        - name: "Content-Type"
          in: "header"
          required: true
          schema:
            type: "string"
      requestBody:
        description: "Register a user"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        400:
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        401:
          description: "Invalid API key"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        201:
          description: "User registered"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      security:
        - api_key: []
  /shifts:
    post:
      summary: "Courier shift start"
      operationId: "startShift"
      description: "Start current courier shift"
      parameters:
        - name: "Content-Type"
          in: "header"
          required: true
          schema:
            type: "string"
      requestBody:
        description: "Start a shift"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ShiftStart"
        required: true
      responses:
        400:
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        401:
          description: "Invalid API key"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        201:
          description: "Shift started"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ShiftStarted"
      security:
        - api_key: []
  /shifts/{id}:
    put:
      summary: "Courier shift end"
      operationId: "endShift"
      description: "End current courier shift"
      parameters:
        - name: "Content-Type"
          in: "header"
          required: true
          schema:
            type: "string"
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      requestBody:
        description: "End the shift"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ShiftEnd"
        required: true
      responses:
        400:
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        401:
          description: "Invalid API key"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        201:
          description: "Shift ended"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ShiftEnded"
      security:
        - api_key: []

components:
  schemas:
    User:
      required:
        - "birth_date"
        - "email"
        - "firstname"
        - "lastname"
        - "phone"
      type: "object"
      properties:
        firstname:
          minLength: 1
          type: "string"
        lastname:
          minLength: 1
          type: "string"
        email:
          type: "string"
          format: "email"
        phone:
          minLength: 1
          type: "string"
        birth_date:
          pattern: "^\\d{4}-\\d{2}-\\d{2}$"
          type: "string"
    Error:
      required:
        - "error"
        - "message"
        - "status"
      type: "object"
      properties:
        status:
          type: "string"
        error:
          type: "string"
        message:
          type: "string"
        detail:
          type: "string"
    ShiftStart:
      required:
        - "startTime"
        - "user"
      type: "object"
      properties:
        user:
          required:
            - "customerNumber"
          type: "object"
          properties:
            customerNumber:
              minLength: 1
              type: "string"
              description: "Matched customer number provided by sign up service"
              example: "IT15K"
        startTime:
          type: "string"
          format: "date-time"
          description: "Courier shift’s start time"
          example: "2018-12-15T14:00:00+00:00"
    ShiftStarted:
      required:
        - "id"
        - "startTime"
        - "user"
      type: "object"
      properties:
        id:
          pattern: "^\\d+$"
          type: "string"
        user:
          required:
            - "customerNumber"
          type: "object"
          properties:
            customerNumber:
              minLength: 1
              type: "string"
              description: "Customer number"
              example: "IT15K"
        startTime:
          type: "string"
          format: "date-time"
          description: "Courier shift’s started time"
          example: "2018-12-15T14:00:00+00:00"
    ShiftEnd:
      required:
      - "endTime"
      type: "object"
      properties:
        endTime:
          type: "string"
          format: "date-time"
          description: "Courier shift’s end time"
          example: "2018-12-15T14:00:00+00:00"
    ShiftEnded:
      required:
        - "endTime"
      type: "object"
      properties:
        endTime:
          type: "string"
          format: "date-time"
          description: "Courier shift’s ended time"
          example: "2018-12-15T14:00:00+00:00"
  securitySchemes:
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"
