openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: DutyCalls API
    url: https://dutycalls.me/api
  - description: DutyCalls test environment API
    url: https://playground.dutycalls.me/api
info:
  version: "1.1.0"
  title: 'DutyCalls API'
  description: |
    This is the DutyCalls REST API. You can find
    out more about DutyCalls at
    [dutycalls.me](http://dutycalls.me).
security:
  - basicAuth: []
tags:
  - name: notification
    description: Everything about notifications
paths:
  /notification:
    post:
      tags:
        - notification
      summary: Post a new notification to DutyCalls
      operationId: postNotification
      parameters:
        - name: channel
          in: query
          description: Channel to send the notification to
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
        description: |
          Posted notification object

          Note: If you have configured your own format within DutyCalls, you will have to use this.
        required: true
      responses:
        '201':
          description: The request was successful and a new resource was created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  notifications:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        channel:
                          type: string
        '400':
          description: The user provided wrong arguments or invalid syntax.
        '401':
          description: Caller did not supply credentials or did not provide the correct credentials.
        '429':
          description: The request has been sent multiple times, where this is not allowed.
    put:
      tags:
        - notification
      summary: Update a notification within DutyCalls
      operationId: putNotification
      parameters:
        - name: id
          in: query
          description: ID of notification that needs to be updated
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationUpdate'
        description: |
          Notification update object
        required: true
      responses:
        '204':
          description: The request was successful.
        '400':
          description: The user provided wrong arguments or invalid syntax.
        '401':
          description: Caller did not supply credentials or did not provide the correct credentials.
        '429':
          description: The request has been sent multiple times, where this is not allowed.
  
components:
  securitySchemes:
      basicAuth:     # <-- arbitrary name for the security scheme
        type: http
        scheme: basic

  schemas:
    Notification:
      required:
        - title
        - body
        - dateTime
      type: object
      properties:
        title:
          type: string
        body:
          type: string
        dateTime:
          type: integer
        severity:
          type: string
        sender:
          type: string
        link:
          type: string
      example:
        title: "This is the title of the notification"
        body: "This is the body of the notification"
        dateTime: 1565772510
        severity: "medium"
    NotificationUpdate:
      required:
        - status
      type: object
      properties:
        status:
          type: string
        comment:
          type: string
      example:
        status: "closed"
        comment: "This notification has been closed"
