openapi: 3.0.0
info:
  title: Zima API
  description: Zima Package Platform API Document
  termsOfService: ''
  contact:
    name: API Support
    url: 'https://air.unicore.studio'
    email: zqy0224@live.com
  version: 1.0.0
paths:
  '/list/{name}':
    get:
      tags:
        - package
      summary: 获取关于该包的所有版本信息
      description: 返回一个数组, 其中包含了所有包名相同的包信息
      operationId: list
      parameters:
        - name: name
          in: path
          required: true
          description: 包名
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Package'
        '404':
          description: 包名不存在
  '/info/{name}':
    get:
      tags:
        - package
      summary: 获取关于某个包的信息(最新版本)
      description: 返回一个json对象, 包含包信息
      operationId: info
      parameters:
        - name: name
          in: path
          required: true
          description: 包名
          schema:
            type: string
      responses:
        '200': 
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Package'
        '404':
          description: 包名不存在
  '/info/{name}/{version}':
    get:
      tags:
        - package
      summary: 获取关于某个包的信息(指定版本)
      description: 返回一个json对象, 包含包信息
      operationId: infoByVersion
      parameters:
        - name: name
          in: path
          required: true
          description: 包名
          schema:
            type: string
        - name: version
          in: path
          required: true
          description: 版本
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Package'
        '404':
          description: 特定包不存在
  '/publish':
    post:
      tags:
        - package
      summary: 上传一个新的包或已有包的新版本
      description: 返回新上传的包信息
      operationId: publish
      parameters:
        - name: key
          in: query
          required: true
          description: 密钥
          schema:
            type: string
      requestBody:
        content: 
          application/x-zip-compressed: 
            schema: 
              type: string
              format: binary
              example: 包文件的字节流
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Package'
        '400':
          description: 包信息存在无效属性
        '401':
          description: 密钥无效
  '/fetch/{name}':
    get:
      tags:
        - package
      summary: 下载包(最新版本)
      description: 返回字节流
      operationId: fetch
      parameters:
        - name: name
          in: path
          required: true
          description: 包名
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content: 
            application/x-zip-compressed: 
              schema: 
                type: string
                format: binary
                example: 包文件的字节流
  '/fetch/{name}/{version}':
    get:
      tags:
        - package
      summary: 下载包(指定版本)
      description: 返回字节流
      operationId: fetchByVersion
      parameters:
        - name: name
          in: path
          required: true
          description: 包名
          schema:
            type: string
        - name: version
          in: path
          required: true
          description: 版本
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content: 
            application/x-zip-compressed: 
              schema: 
                type: string
                format: binary
                example: 包文件的字节流
  '/validate':
    get:
      tags:
        - key
      summary: 验证密钥可用性
      description: 作为密钥服务器时可用, 验证密钥是否存在于本地TrustedKeys配置中
      operationId: validateKey
      parameters:
        - name: key
          in: query
          required: true
          description: 密钥
          schema:
            type: string
      responses:
        '200':
          description: 可用
        '404': 
          description: 不可用
components:
  schemas:
    Package:
      description: 包
      type: object
      required:
        - name
        - version
        - uploadDate
        - dependencies
      properties:
        name:
          type: string
          description: 包名
          example: Simple.Shell
        version: 
          type: string
          description: 版本
          example: 2020.2.3
        uploadDate: 
          type: string
          description: 上传日期
          example: 2020.1.1
        dependencies: 
          type: array
          items: 
            type: string
            description: 用逗号隔开的包签名(包名与版本, 冒号隔开)数组
            example: 'Simple.Core:1910.4.1'
tags:
  - name: package
    description: 包管理
  - name: key
    description: 密钥验证
