openapi: 3.0.0
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Codewaves/Albums/1.0.0
info:
  description: Albums API
  version: "1.0.0"
  title: Simple Album API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: top albums
    description: Top albums
paths:
  /search:
    get:
      tags:
        - top albums
      summary: searches artists
      operationId: searchArtists
      description: |
        By passing in the search term, you can search for
        iTunes artists.
      parameters:
        - in: query
          name: term
          description: term to search for
          required: true
          schema:
            type: string
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Artist'
        '400':
          description: bad input parameter
  /favorite:
    post:
      tags:
        - top albums
      summary: set user's favorite artist
      operationId: favoriteArtist
      description: By passing artist id you can store it in the user's profile
      parameters:
        - in: query
          name: user
          description: user id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: id accepted
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FavoriteArtist'
        description: Artist id to set
  /top:
    get:
      tags:
        - top albums
      summary: return user artist's top albums
      operationId: topAlbums
      description: |
        By passing in the user id, you can view his favorite artist's top 
        iTunes albums.
      parameters:
        - in: query
          name: user
          description: user id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: user artist's top albums
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Album'
        '400':
          description: bad input parameter
        '404':
          description: user not found
components:
  schemas:
    Artist:
      type: object
      required:
        - artistId
        - artistName
      properties:
        artistId:
          type: integer
          example: 1
        artistName:
          type: string
          example: ABBA
    FavoriteArtist:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          example: 1234
    Album:
      type: object
      required: 
        - "collectionId"
        - "collectionName"
        - "artistName"
        - "collectionCensoredName"
        - "artistViewUrl"
        - "collectionViewUrl"
        - "artworkUrl60"
        - "artworkUrl100"
        - "collectionPrice"
        - "collectionExplicitness"
        - "trackCount"
        - "copyright"
        - "country"
        - "currency"
        - "releaseDate"
        - "primaryGenreName"
      properties: 
        collectionId: 
          type: integer
          example: 597547053
        collectionName: 
          type: string
          example: "Tito - Single"
        artistName: 
          type: string
          example: "Term"
        collectionCensoredName: 
          type: string
          example: "Tito - Single"
        artistViewUrl: 
          type: string
          example: "https://music.apple.com/us/artist/term/253458150?uo=4"
        collectionViewUrl: 
          type: string
          example: "https://music.apple.com/us/album/tito-single/597547053?uo=4"
        artworkUrl60: 
          type: string
          example: "https://is3-ssl.mzstatic.com/image/thumb/Music/v4/6b/6d/b7/6b6db7a0-2246-71ab-ff2d-feb4459cd719/source/60x60bb.jpg"
        artworkUrl100: 
          type: string
          example: "https://is3-ssl.mzstatic.com/image/thumb/Music/v4/6b/6d/b7/6b6db7a0-2246-71ab-ff2d-feb4459cd719/source/100x100bb.jpg"
        collectionPrice: 
          type: number
          example: 2.97
        collectionExplicitness: 
          type: string
          example: "notExplicit"
        trackCount: 
          type: integer
          example: 3
        copyright: 
          type: string
          example: "℗ 2013 White Mouse Records"
        country: 
          type: string
          example: "USA"
        currency: 
          type: string
          example: "USD"
        releaseDate: 
          type: string
          example: "2013-01-28T08:00:00Z"
        primaryGenreName: 
          type: string
          example: "Electronic"
