openapi: 3.0.1
info:
  title: EXPENSE_API
  version: v03
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/spanders89/expense-api/v03
paths:
  /expense:
    post:
      operationId: postExpense
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postExpense-request-wrapper'
        required: false
      responses:
        '204':
          description: No content defined for this response
          content: {}
      security:
        - oauth2Authentication: []
  '/expense/{id}':
    get:
      operationId: getExpense
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: A sample description of the Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getExpense-response-wrapper'
      security:
        - oauth2Authentication: []
components:
  schemas:
    postExpense-request-wrapper:
      required:
        - ExpenseHeader
      type: object
      properties:
        ExpenseHeader:
          type: object
          properties:
            employeeName:
              type: string
            totalAmount:
              type: number
            travelDate:
              type: string
            destination:
              type: string
            expenseDetailCollection:
              type: object
              properties:
                ExpenseDetail:
                  minItems: 1
                  type: array
                  items:
                    required:
                      - amount
                      - expenseType
                      - notes
                    type: object
                    properties:
                      expenseType:
                        type: string
                      amount:
                        type: number
                      notes:
                        type: string
            id:
              type: string
            justification:
              type: string
            purposeOfVisit:
              type: string
    getExpense-response-wrapper:
      required:
        - ExpenseHeader
      type: object
      properties:
        ExpenseHeader:
          type: object
          properties:
            employeeName:
              type: string
            totalAmount:
              type: number
            travelDate:
              type: string
            destination:
              type: string
            expenseDetailCollection:
              type: object
              properties:
                ExpenseDetail:
                  minItems: 1
                  type: array
                  items:
                    required:
                      - amount
                      - expenseType
                      - lineid
                      - notes
                    type: object
                    properties:
                      expenseType:
                        type: string
                      amount:
                        type: number
                      notes:
                        type: string
                      lineid:
                        type: number
            id:
              type: string
            justification:
              type: string
            purposeOfVisit:
              type: string
    APIInvocationError:
      required:
        - detail
        - errorCode
        - errorDetails
        - title
        - type
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        errorCode:
          type: string
        errorDetails:
          minItems: 1
          type: array
          items:
            required:
              - errorCode
              - errorPath
              - instance
              - title
              - type
            type: object
            properties:
              instance:
                type: string
              errorCode:
                type: string
              type:
                type: string
              title:
                type: string
              errorPath:
                type: string
  securitySchemes:
    oauth2Authentication:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: >-
            https://idcs-fbacd7d8be4549798160358e52f788dc.identity.oraclecloud.com:443/oauth2/v1/authorize
          tokenUrl: >-
            https://idcs-fbacd7d8be4549798160358e52f788dc.identity.oraclecloud.com:443/oauth2/v1/token
          scopes:
            'https://psoicdemo-orasenatdpublicsector05.integration.ocp.oraclecloud.com:443urn:opc:resource:consumer::all': all
