openapi: 3.0.0
servers:
  - url: 'https://dev.foyatech.com/channel'
  - url: 'https://uat.foyatech.com/channel'
info:
  description: |
    # Resource:
    - ChargingTransaction 充電交易

    ## 更新日期
    - 2019/11/26 status code 異動
    - 2019/11/27 時間日期調整為UTC時間
    - 2019/12/12 啟動充電交易api 增加通路編號欄位
  version: 1.0.0
  title: Channel API
tags:
  - name: ChargingTransaction
    description: 充電交易
paths:
  /api/ChargingTransaction/:
    post:
      tags:
        - ChargingTransaction
      summary: 啟動充電交易
      description: ''
      requestBody:
        content:
          text/plain:
            schema:
              $ref: '#/components/schemas/ChargingTransactionRequest'
      responses:
        '200':
          description: 用戶端要求作業作成功。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargingTransactionResponse'
        '401':
          $ref: '#/components/responses/401'
        '460':
          $ref: '#/components/responses/460'
        '461':
          $ref: '#/components/responses/461'
        '462':
          $ref: '#/components/responses/462'
        '470':
          $ref: '#/components/responses/470'
        '471':
          $ref: '#/components/responses/471'
        '550':
          $ref: '#/components/responses/550'
  '/api/ChargingTransaction/{ChannelTransId}':
    get:
      tags:
        - ChargingTransaction
      summary: 查詢 充電交易結果
      description: ''
      parameters:
        - in: path
          name: ChannelTransId
          description: 充電訂單編號
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargingTransactionResultResponse'
        '401':
          $ref: '#/components/responses/401'
        '460':
          $ref: '#/components/responses/460'
        '461':
          $ref: '#/components/responses/461'
        '462':
          $ref: '#/components/responses/462'
        '550':
          $ref: '#/components/responses/550'
components:
  responses:
    '401':
      description: 未登入或無權限。
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusCode'
    '460':
      description: '{0}資料不存在。'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusCode'
    '461':
      description: '{0}欄位為必填。'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusCode'
    '462':
      description: '{0}欄位格式錯誤。'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusCode'
    '470':
      description: 充電樁尚未準備就緒。
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusCode'
    '471':
      description: QRCode過期。
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusCode'
    '550':
      description: 內部錯誤。
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusCode'
  schemas:
    ChargingTransactionRequest:
      type: object
      required:
        - CpId
        - ConnectorId
        - ChannelId
      properties:
        CpId:
          type: string
          maxLength: 20
          description: 充電樁編號
          example: CP1549
        ConnectorId:
          type: string
          maxLength: 20
          description: 充電槍代碼
          example: '1'
        CheckNo:
          type: string
          maxLength: 15
          description: 驗證碼
          example: N8pS4ieeQA
        ChannelId:
          type: string
          maxLength: 20
          description: 通路編號
          example: M2019081617351640676
    ChargingTransactionResponse:
      type: object
      properties:
        ChannelTransId:
          type: string
          description: 充電訂單編號
          example: CT191126110727479637
    ChargingTransactionResultResponse:
      type: object
      properties:
        ChannelTransId:
          type: string
          description: 充電訂單編號
          example: CT191126110727479637
        TransStatus:
          type: string
          description: |
            充電交易狀態

            規格說明：
            - Initial: 交易初始中
            - Charging: 交易進行中
            - Finish: 交易完成
          example: Initial
        TransDate:
          type: string
          description: 交易日期(UTC時間)
          format: 'yyyy-MM-dd''T''HH:mm:ss''Z'''
          example: '2019-11-18T19:31:45Z'
    StatusCode:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: errorcode
        message:
          type: string
          description: 錯誤訊息
