openapi: 3.0.1
info:
  title: Foxngame API
  description: Foxngame Order API
  version: '1.0'
servers:
  - url: https://api.foxngame.com
paths:
  '/orders/{orderId}':
    get:
      security:
        - basicAuth: [ ]
      description: Sonuç olarak sipariş detay bilgileri ve epin kodları döner.
      operationId: get-order-detail
      parameters:
        - name: orderId
          in: path
          description: Sipariş numarası
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Sipariş detay bilgileri
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDetailResult'
              example:
                orderId: 117215
                status: complete
                unitPrice: 0.95
                totalPrice: 0.95
                remainingQuantity: 0
                orderQuantity: 1
                epins:
                  - EPIN 1
                  - EPIN 2
                  - EPIN 3
                  - EPIN 4
                  - EPIN 5
        '401':
          description: Not authenticated
      summary: Sipariş detay
  /orders:
    post:
      security:
      - basicAuth: [ ]
      description: Yeni sipariş oluşturur. Sonuç olarak sipariş detay bilgileri ve epin kodları döner.
      operationId: post-create-order
      requestBody:
        description: Sipariş bilgileri
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
            example:
              ProductId: 3881
              CategoryId: 2151
              Quantity: 1
      responses:
        '200':
          description: Sipariş detay bilgileri
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDetailResult'
              example:
                orderId: 117215
                status: complete
                unitPrice: 0.95
                totalPrice: 0.95
                remainingQuantity: 0
                orderQuantity: 1
                epins:
                  - EPIN 1
                  - EPIN 2
                  - EPIN 3
                  - EPIN 4
                  - EPIN 5
        '401':
          description: Not authenticated
      summary: Yeni sipariş
components:
  schemas:
    CreateOrderRequest:
      type: object
      properties:
        ProductId:
          type: integer
        CategoryId:
          type: integer
        Quantity:
          type: integer
      description: Yeni sipariş isteği
    OrderDetailResult:
      type: object
      properties:
        orderId:
          type: integer
        status:
          type: string
          enum: [pending, processing, complete, partialcomplete, cancelled]
          description: >
            Sipariş Durumu:
             * `pending` - Bekliyor
             * `processing` - Tedarik Aşamasında
             * `complete` - Teslim Edildi
             * `partialcomplete` - Kısmen Teslim Edildi
             * `cancelled` - İptal Edildi
        unitPrice:
          type: number
        totalPrice:
          type: number
        remainingQuantity:
          type: integer
        orderQuantity:
          type: integer
        epins:
          type: array
          items:
            type: string
      description: Sipariş detay bilgileri
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
