openapi: 3.0.0
info:
  title: The Autolocator API
  description: Endpoints for the autolocator site
  version: 1.0.4
paths:
  /:
    post:
      summary: Returns the list of cars concatenating autotemptest and facebook marketplace results.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                facebookUsername:
                  type: string
                  example: fbuser@iugo.com.uy
                facebookPassword:
                  type: string
                  example: "TGGsafsdg123D2"
      parameters:
        - in: query
          name: make
          schema:
            type: string
          description: Brand of the cars
          example: nissan
          required: true
        - in: query
          name: model
          schema:
            type: string
          description: Model of the cars
          example: versa
          required: true
        - in: query
          name: zip
          schema:
            type: string
          description: Zipcode used in autotemptest to filter cars list
          example: 92373
          required: true
        - in: query
          name: radius
          schema:
            type: integer
          description: Radius to search cars
          example: 50
          required: true
        - in: query
          name: city
          schema:
            type: string
          description: City used in facebook marketplace to filter cars list. Required if facebook credentials are send.
          example: Redlands
          required: false
        - in: query
          name: state
          schema:
            type: string
          description: State used in facebook marketplace to filter cars list. Required if facebook credentials are send.
          example: California
          required: false
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    description: The list of cars.
                    items:
                      type: object
                      properties:
                        site:
                          type: string
                          description: Key indicating the origin of the item
                          example: "Autotempest:cv"
                        image:
                          type: string
                          description: URL to the image of the car
                          example: "https://cdnblob.carvana.io/2000417529/post-large/third-party/2000417529-hero-normalized.jpg"
                        link:
                          type: string
                          description: URL to the details of the car
                          example: "https://www.carvana.com/search/2000417529"
                        name:
                          type: string
                          description: Title of the item
                          example: "2018 Nissan Versa SV Sedan 4D"
                        price:
                          type: string
                          description: Price of the item
                          example: "$11,400"
                        details:
                          type: string
                          description: Long description of the item (only for autotemptest items)
                          example: "CARVANA CERTIFIED INCLUDES: 150-POINT INSPECTION -- We put each vehicle through a 150-point inspection so that you can be 100% confident in the quality and safety of your vehicle. This inspection includes everything from tread depth of tires to thickness of brake pads to exterior paint quality to Bluetooth compatibility."
                  info:
                    type: object
                    description: General information of the result
                    properties:
                      price:
                        type: object
                        properties:
                          min:
                            type: integer
                            description: Min price of the list
                            example: 1300
                          max:
                            type: integer
                            description: Max price of the list
                            example: 1950
                          avg:
                            type: integer
                            description: Average price of the list
                            example: 1610
                      items:
                        type: object
                        properties:
                          totalQty:
                            type: integer
                            description: Quantity of results returned
                            example: 180
                          autotemptest:
                            type: object
                            description: Information about autotemptest results
                            properties:
                              qty:
                                type: integer
                                example: 100
                                description: Items from autotemptest
                              url:
                                type: string
                                example: https://www.autotempest.com/results?make=nissan&model=versa&zip=92373&radius=300
                                description: Url used for the search in autotemptest
                          facebookMarketplace:
                            type: object
                            description: Information about facebook marketplace results
                            properties:
                              qty:
                                type: integer
                                example: 100
                                description: Items from facebook marketplace
                              url:
                                type: string
                                example: https://facebook.com/marketplace/category/vehicles?vehicleMake=nissan&vehicleModel=versa&sort=BEST_MATCH
                                description: Url used for the search in facebook marketplace
        422:
          description: An error with parameters occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: string
                          description: value received for the param with the error
                        msg:
                          type: string
                          description: message of the error
                        param:
                          type: string
                          description: the name of the param with the error
                        location:
                          type: string
                          description: the location of the param with the error
        500:
          description: An error has occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message explaining the error
                  debug:
                    type: object
                    description: The exception thrown
  /kbb:
    post:
      summary: Returns the kbb values for a VIN.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: kbbuser@iugo.com.uy
                password:
                  type: string
                  example: "TGGsafsdg123D2"
      parameters:
        - in: query
          name: vin
          schema:
            type: string
          description: VIN of the cars
          example: 3TMLU4EN9BM070190
          required: true
        - in: query
          name: mileage
          schema:
            type: string
          description: Mileage of the cars
          example: 37341
          required: true
        - in: query
          name: transmission
          schema:
            type: string
          description: Transmission of the car
          example: Automatic
          required: true
        - in: query
          name: driveTrain
          schema:
            type: integer
          description: Drive train of the car
          example: 2W
          required: true
        - in: query
          name: equipments
          schema:
            type: string
          description: List of ids for equipments selected separated by comma
          example: 5424975,4303346,4303380
          required: false
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  values:
                    type: object
                    description: The kbb values
                    properties:
                      WholesaleBaseValue:
                        type: string
                        example: "$18,143"
                      RetailBaseValue:
                        type: string
                        example: "$20,188"
                      WholesaleMileageValue:
                        type: string
                        example: "$6,946"
                      RetailMileageValue:
                        type: string
                        example: "$6,946"
                      WholesaleBlueBookValue:
                        type: string
                        example: "$25,089"
                      RetailBlueBookValue:
                        type: string
                        example: "$27,134"
                  equipments:
                    type: array
                    description: Array of equipments with a boolean indicating if it's selected or not
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: id of the equipment
                        name:
                          type: string
                          description: name of the equipment
                        checked:
                          type: boolean
                          description: it indicates if it's selected or not
        401:
          description: Something went wrong logging in karpower
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message explaining the error
        422:
          description: An error with parameters occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: string
                          description: value received for the param with the error
                        msg:
                          type: string
                          description: message of the error
                        param:
                          type: string
                          description: the name of the param with the error
                        location:
                          type: string
                          description: the location of the param with the error
        500:
          description: An error has occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message explaining the error
                  debug:
                    type: object
                    description: The exception thrown
  /statistics:
    get:
      summary: Returns the statistics about cars sold by by year, make and model.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: Array of year, make and model sold by dealers
                items:
                  type: object
                  properties:
                    year:
                      type: string
                      description: year of the car
                    make:
                      type: string
                      description: make of the car
                    model:
                      type: string
                      description: model of the car
                    dealers:
                      type: array
                      description: dealers that sold this car
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            description: name of the dealer
                          country:
                            type: string
                            description: country of the dealer
                          totalNew:
                            type: integer
                            description: totay quantity of new card sold by the dealer
                          totalUsed:
                            type: integer
                            description: totay quantity of used card sold by the dealer
                    totalNew:
                      type: integer
                      description: totay quantity of new card sold
                    totalUsed:
                      type: integer
                      description: totay quantity of used card sold
        500:
          description: An error has occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message explaining the error
                  debug:
                    type: object
                    description: The exception thrown
