openapi: 3.0.0
servers:
  - description: API Efact - Safebill
    url: 'https://virtserver.swaggerhub.com/Arturor72/api-efact/1.0.0'
info:
  description: >
    API allows you to create users, show accounts, and create operations for
    exchange money.
  version: "1.0.0-oas3"
  title: "Api efact"
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: abadillo@imaginaticsperu.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: auth
    description: Authenticate an user
    externalDocs:
      description: Find out more about exchange-operation
      url: 'http://papeat.com.pe/oauth/token'
  - name: empresa
    description: Everything about users
    externalDocs:
      description: Find out more
      url: 'http://papeat.com.pe/api/v1/empresa/certificate'
  - name: invoice
    description: Operations about accounts
    externalDocs:
      description: Find out more about our accounts
      url: 'http://papeat.com.pe/api/v1/invoice/send/{}'
paths:
  /oauth/token:
    summary: Recurso para obtener un token implicito
    post:
      tags:
        - auth
      summary: autenticar cliente 
      description: Autenticar cliente
      operationId: authClient
      requestBody:
        content:
          application/form-data:
            schema:
              $ref: '#/components/schemas/ClientObject'
        description: Required information to auth
        required: true
      responses:
        '200':
          description: operacion exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObject'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedObjetc'
        '403':
          description: Forbidden
        4XX:
          description: Client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        5XX:
          description: Server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
  /empresa/certificate:
    post:
      tags:
        - empresa
      summary: Crear una empresa
      description: Operacion que permite crear una empresa con su certificado
      operationId: crearEmpresa
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmpresaObject'
          multipart/form-data:
            schema:
              type: object
              properties:
                cert:
                  type: string
                  format: binary
                key:
                  type: string
                  format: binary
                empresa:
                  $ref: '#/components/schemas/EmpresaObject'
        required: true
      responses:
        '201':
          description: Resource created
          headers:
            Valid-Schedule:
              schema:
                type: boolean
              description: If the schedule is valid.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uri
                    description: User created URI
                    example: /users/user/1.
        4XX:
          description: Client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        5XX:
          description: Server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
  /invoice:
    post:
      tags:
        - invoice
      summary: Guardar invoice
      description: Guardar invoice cuando ya la empresa esta registrada
      operationId: saveInvoice
      requestBody:
        description: Invoice
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceObject'
      responses:
        '201':
          description: Resource created
          headers:
            Valid-Schedule:
              schema:
                type: boolean
              description: If the schedule is valid.
          content:
            application/json:
              schema:
                type: object
                properties:
                  resource:
                    type: string
                    format: uri
                    description: Account created URI
        4XX:
          description: Client error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        5XX:
          description: Server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  schemas:
    ClientObject:
      type: object
      properties:
        grant_type:
          type: string
          example: 'client_credentials'
        client_id:
          type: string
          example: 1
        client_secret:
          type: string
          example: 'MeSYNUYyUFk8id1rDJMTieB'
    TokenObject:
      type: object
      properties:
        token_type:
          type: string
          example: 'Bearer'
        expires_in:
          type: integer
          format: int64
          example: 123456
        access_token:
          type: string
          example: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSU'
    UnauthenticatedObjetc:
      type: object
      properties:
        message:
          type: string
          example: 'Unauthenticated'
    EmpresaObject:
      type: object
      properties:
        ruc:
          type: string
          example: 14002357
        razonSocial:
          type: string
          example: 154655
        nombreComercial:
          type: string
          example: 998765656
        userSunat:
          type: string
          example: 998765656
        passwordSunat:
          type: string
          example: 998765656
        direccion:
          $ref: '#/components/schemas/DireccionObject'
    DireccionObject:
      type: object
      properties:
        ubigeo:
          type: string
          example: '010101'
        departamento:
          type: string
          example: 'Lima'
        provincia:
          type: string
          example: 'Lima'
        distrito:
          type: string
          example: 'Independencia'
        urbanizacion:
          type: string
          example: 'Los nisperos'
        direccion:
          type: string
          example: 'Psje Dimitrov Mz K Lt 7'
    InvoiceObject:
      type: object
      properties:
        versionUBL:
          type: string
          example: '2.1'
          description: version UBL, debe ser 2.1
        tipoOperacion:
          type: string
          example: '0101'
          description: Tipo de operacion (catalogo 51)
        tipoDocumento:
          type: string
          example: '01'
          description: Tipo de documento (factura 01, boleta 03)
        serie:
          type: string
          example: 'F001'
          description: Serie ya validada en el backend
        correlativo:
          type: integer
          example: 120
          description: Numero correlativo del comprobante generado por la app backend
        fechaEmision:
          type: string
          format: date
          example: "2020-01-14"
          description: Fecha de emision del comprobante ya validado
        tipoMoneda:
          type: string
          example: "PEN"
          description: Puede ser PEN o USD
        totalOGravadas:
          type: number
          format: double
          example: 120.5
          description: Total de operaciones afectadas por igv
        totalOExoneradas:
          type: number
          format: double
          example: 50.5
          description: Total de operaciones que son exoneradas de igv
        totalOInafectas:
          type: number
          format: double
          example: 0
          description: Total de operaciones que son inafectas a igv
        totalIcbper:
          type: number
          format: double
          example: 0
          description: Total de impuestos ICBPER (Bolsa)
        totalImpuestos:
          type: number
          format: double
          example: 171.0
          description: Sumatoria de todos los impuestos
        totalValorVenta:
          type: number
          format: double
          example: 200
          description: Valor del total de la venta sin impuestos
        totalVenta:
          type: number
          format: double
          example: 500
          description: Valor del total de la venta incluido todos los impuestos
        cliente:
          $ref: '#/components/schemas/ClienteObject'
        empresa:
          $ref: '#/components/schemas/EmpresaRucObject'
        detallesInvoice:
          $ref: '#/components/schemas/ListaDeallesInvoice'            
    ClienteObject:
      type: object
      properties:
        tipoDocumento:
          type: string
          example: '6'
          description: Tipo de documento segun catalogo 1 (dni 1, ruc 6 )
        numeroDocumento:
          type: string
          example: '1070870990'
          description: De acuerdo al tipo de documento
        razonSocial:
          type: string
          example: 'Mi razon social'
          description: Si el tipo de documento fue 6
        nombres:
          type: string
          example: 'Arturo'
          description: Nombres del cliente
        apellidos:
          type: string
          example: 'Badillo Alvarado'
          description: Apellidos del cliente
          
    EmpresaRucObject:
      type: object
      properties:
        ruc:
          type: string
          example: '10708702970'
          description: Numero de ruc de la empresa que ya debe haber sido registrada
    ListaDeallesInvoice:
      type: array
      items:
        $ref: '#/components/schemas/DetalleInvoiceObject'
    DetalleInvoiceObject:
      type: object
      properties:
        codigoProducto:
          type: string
          example: 'PROD1'
          description: Codigo del producto con el cual fue registrado en tu app.
        descripcion:
          type: string
          example: 'LECHE CONDENSADA'
          description: Descripcion del producto a registrar
        unidad:
          type: string
          example: 'NIU'
          description: Unidad validada de acuerdo a SUNAT
        cantidad:
          type: number
          format: double
          example: 5
          description: Cantidad del producto que se esta comprando
        afectacionIGV:
          type: string
          example: "10"
          description: Tipo de afectacion de impuesto catalogo 7
        porcentajeIGV:
          type: number
          format: double
          example: 18
          description: Porcentaje que se aplicara al impuesto
        totalImpuestos:
          type: number
          format: double
          example: 18.0
          description: Total de la suma de impuestos
        igv:
          type: number
          format: double
          example: 18.0
          description: Monto de igv que fue afectado
        icbper:
          type: number
          format: double
          example: 0.4
          description: Monto total de icbper afectado para este item
        montoBaseIgv:
          type: number
          format: double
          example: 100.0
          description: Total de operaciones que son inafectas a igv
        valorVenta:
          type: number
          format: double
          example: 100.0
          description: Monto total de la venta sin impuestos
        valorUnitario:
          type: number
          format: double
          example: 20.0
          description: Valor unitario del producto sin impuesto
        precioUnitario:
          type: number
          format: double
          example: 23.6
          description: Valor unitario del producto con impuestos
    
    
    
    
    
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int64
        type:
          type: string
        message:
          type: string
    ClientError:
      type: object
      properties:
        code:
          type: string
        httpStatus:
          type: integer
          format: int32
        timestamp:
          type: string
          format: date-time
        message:
          type: string
        debugMessage:
          type: string
        suberror:
          type: array
          items:
            $ref: '#/components/schemas/SubError'
    SubError:
      type: object
      properties:
        object:
          type: string
        field:
          type: string
        rejectValue:
          type: string
        message:
          type: string
    ServerError:
      type: object
      properties:
        code:
          type: string
        httpStatus:
          type: integer
          format: int32
        timestamp:
          type: string
          format: date-time
        message:
          type: string
        debugMessage:
          type: string
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
          scopes:
            'write:pets': modify pets in your account
            'read:pets': read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
