openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'AuthenticationAPI'
  description: 'Will use this API to simulate authenticaton purpose'
  termsOfService: https://fund.com/terms-of-use
  contact:
    name: Shahriar
    url: https://fund.com
    email: email@domain.com
  license:
    name: Fund License
    url: https://fund.com/license
servers:
  - url: https://virtserver.swaggerhub.com/fmshahriar/FundRAuthentication/1.0.0
    description: Dev Server
paths: 
  /checkNID:
    post:
      description: Verify NID information from NID server.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nidNo: 
                  type: integer
                  example: 1234567890
                userName:
                  type: string
                  example: Omar Ahmed
                fatherName:
                  type: string
                  example: Jalal Ahmed
                motherName:
                  type: string
                  example: Tania Ahmed
                dateOfBirth:
                  type: string
                  example: 31-12-2000
                issueDate:
                  type: string
                  example: 31-12-2018
      responses:
        200:
          description: NID verfied.
  /checkTIN:
    post:
      description: Verify TIN information from NBR server.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tinNo: 
                  type: integer
                  example: 1234567890
                userName:
                  type: string
                  example: Omar Ahmed
                fatherName:
                  type: string
                  example: Jalal Ahmed
                texZone:
                  type: string
                  example: Dhaka-06
                issueDate:
                  type: string
                  example: 31-12-2018
      responses:
        200:
          description: TIN verfied.
  /checkPassport:
    post:
      description: Verify Passport information from Passport server.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                passportNo: 
                  type: string
                  example: BA1234567890
                userName:
                  type: string
                  example: Omar Ahmed
                fatherName:
                  type: string
                  example: Jalal Ahmed
                motherName:
                  type: string
                  example: Tania Ahmed
                dateOfBirth:
                  type: string
                  example: 31-12-2000
                issueDate:
                  type: string
                  example: 31-12-2018
      
      responses:
        200:
          description: Passport verfied.
  /checkNBR:
    post:
      description: Verify organization information from NBR server.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                registrationNo: 
                  type: string
                  example: 1234567890
                organizationName:
                  type: string
                  example: Ali Enterprise
                vatRegistrationNo:
                  type: string
                  example: 234093
      responses:
        200:
          description: Organization verfied.
