openapi: 3.0.0
info:
  version: "1.1.1"
  title: Jelli to MongoDB Api
tags:
  - name: Jelli to MongoDB

paths:
  /post/jellyorder:
    post:
      tags:
        - Jelli to MongoDB
      summary: "Retrieve json body and store in mongo DB"
      operationId: postJellyMonthly
      requestBody:
        content:
          application/json:
              schema:
                type: object
                items:
                  $ref: 'https://virtserver.swaggerhub.com/Ameliom/JelliOrders/1.0.0#/components/schemas/Order'
               
      responses:
        "200":
          description: Accepted
        '400':
          description: bad input parameter
          
  /get/jellyorder:     
    get:
      tags:
        - Jelli to MongoDB
      summary: "Retrieve json body from mongo DB by PageId"
      operationId: GetMetricsByPageId 
      description: return docs
      parameters:
        - name: PageId
          in: query
          schema:
            type: integer
          required: true
          example: 100032
      responses:
        '200':
          description: document returned
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          description: bad input parameter
components:
  schemas:
    Order:
      type: object
      required:
        - "PageId"
        - "orderId"
        - "startDate"
        - "endDate"
        - "billingCycle"
      properties:
        PageId:
          type: string
        orderId:
          type: string
          example: "7800018297"
        startDate:
          type: string
          example: "11/1/2019"
        endDate:
          type: string
          example: "11/30/2019"
        billingCycle:
          type: string
          example: someBillingCycle
        fulfillmentList:
          type: array
          items:
            oneOf:
               - $ref: 'https://virtserver.swaggerhub.com/Ameliom/JelliOrders/1.0.0#/components/schemas/OrderLine'
    OrderLine:
      type: object
      properties:      
        ProposalId:
          type: string
          example: "7800018297"
        Station ID:
          type: string
          example: "WGIR-FM"
        FCC ID:
          type: string
          example: "35240"
        Market:
          type: string
          example: "Boston (Manchester), MA"
        Advertiser:
          type: string
          example: "Ownable"
        Creative:
          type: string
          example: "Gen Market Male V2 = RADIO"
        PlaytimeGMT:
          type: string
          example: "2019-12-02 05:00:36 GMT"
        Duration:
          type: string
          example: "29.962"
        Plan Day Part:
          type: string
          example: "mo-fr 12a-6a"
        status:
          type: string
          example: "Aired"
        Price:
          type: string
          example: "3.62"
        Playtime Local:
          type: string
          example: "2019-12-02 00:00:36 EST"
        Campaign Impressions:
          type: string
          example: "500"
        Optimized Day Part:
          type: string
          example: "mo-fr 12a-6a"
# Added by API Auto Mocking Plugin
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Ameliom/JelliOrders/1.0.0
