openapi: 3.0.0
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/wrodrigo/Habibs/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: http://
info:
  description: SemParar & Habib's API
  version: "1.0.0"
  title: SemParar & Habib's API
  contact:
    email: henrique.serrao@semparar.com.br

paths:
  /getpool:
    get:
      tags:
        - Get Authorization Pool
      summary: List the vehicle from the specific lane from Authorization Pool
      operationId: getPool
      description: |
        Return an object item of authorized user from SemParar Authorization Pool
      parameters:
        - in: header
          name: value
          description: Transaction value in cents. Ex R$10.00 = 1000 
          required: true
          schema:
            type: integer
            format: int32
          example: 1000
        - in: header
          name: lane
          description: Lane identification Ex 1=lane1, 2=lane2, etc. 
          required: true
          schema:
            type: integer
            format: int32
          example: 1
      responses:
        '200':
          description: Response array of authorized clients
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayAuth'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  
  /reportuse:
    post:
      tags:
        - Report usage 
      summary: Report authorization usage
      operationId: reportuse
      description: Report authorization used to process the payment by SemParar
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:          
                  type: string
                  example: '0b4c4ce3b488c27dc337bd031aff7749'
                  description: SemParar Authorization Token
                plate:          
                  type: string
                  example: 'abc1234'
                  description: Plate Number
              
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
        '500':
          description: Internal server error
          
  
components:
  schemas:
    ArrayAuth:
      type: array
      items: 
        $ref: "#/components/schemas/AuthItem"

    AuthItem:
      type: object
      properties:
        dateTimeRead:
          type: string
          format: date-time
          example: '2019-11-26T08:00:00'
          description: Tag read datetime
        lane:
          type: integer
          example: 1
          description: Lane Number
        sticker:
          type: string
          example: '0700000000'
          description: Sticker Number
        plate:
          type: string
          example: PXX0000
          description: Plate Number
        document:
          type: string
          example: 31822
          description: First 5 digits from document account owner (CPF)
        mobile:
          type: string
          example: 5678
          description: Last 4 digits from mobile number account owner
        storeCode:
          type: integer
          example: 10001
          description: SemParar drivethru store code
        statusCode:
          type: integer
          example: 0
          description: SemParar status code
        statusMessage: 
          type: string
          example: Success
          description: Status message
        token:
          type: string
          example: 0b4c4ce3b488c27dc337bd031aff7749
          description: SemParar Authorization token
