openapi: 3.0.0
servers:
  - url: 'https://api.acc.eindhovenairport.nl/public-flight/v1'
  - url: 'https://api.eindhovenairport.nl/public-flight/v1'
info:
  version: "1.2"
  title: PublicFlightAPI
paths:
  /flights:
    get:
      tags:
        - public
      summary: Search for flights
      operationId: searchFlights
      parameters:
        - in: query
          name: startDate
          description: 'search period start date'
          required: true
          schema:
            type: string
            format: date-time
        - in: query
          name: endDate
          description: 'search period end date'
          required: true
          schema:
            type: string
            format: date-time
        - in: query
          name: flightDirection
          description: 'Flight direction indicator'
          required: false
          schema:
            type: string
            minLength: 1
            maxLength: 1
        - in: query
          name: pageSize
          description: 'Maximum size of the result set'
          required: false
          schema:
            type: integer
            default: 100
        - in: query
          name: offset
          description: 'Offset of the result set'
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flight'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '406':
          description: Not acceptable
        '422':
          description: Unprocessable entity
        '503':
          description: Service not available
  /flights/{id}:
    get:
      tags:
        - public
      summary: Get a flight
      operationId: getFlight
      parameters:
        - in: path
          name: id
          required: true
          description: 'Flight id'
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flight'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '406':
          description: Not acceptable
        '503':
          description: Service not available
components:
  schemas:
    Aerodrome:
      type: object
      properties:
        codeIATA:
          type: string
          example: 'EIN'
        codeICAO:
          type: string
          example: 'EHEH'
        name:
          type: string
          example: 'Eindhoven'
    Flight:
      type: object
      required:
        - id
      properties:
        actualTimeLT:
          type: string
          format: date-time
          description: Actual arrival or departure date time
          example: '2017-12-19T08:15:00+02:00'
        callSign:
          type: string
          description: Call sign
          example: 'KLM64L'
        codeshares:
          type: array
          items:
            type: string
          description: Codeshare flight names
        direction:
          type: string
          description: Flight direction code
          example: 'A'
        displayText:
          $ref: '#/components/schemas/Text'
        expectedTimeLT:
          type: string
          format: date-time
          description: Expected arrival or departure date time
          example: '2017-12-19T08:10:00+02:00'
        flightName:
          type: string
        id:
          type: string
          format: uuid
          description: Flight id
          example: 'd290f1ee-6c54-4b01-90e6-d701748f0851'
        isEU:
          type: boolean
          description: Flight is within the European Union
          example: false
        isSchengen:
          type: boolean
          description: Flight is within the Schengen area
          example: false
        linkedFlightId:
          type: string
          format: uuid
          description: Linked flight id
          example: '2a4723d6-5a71-459e-946e-bf96785b081e'
        publicTimeLT:
          type: string
          format: date-time
          description: Public scheduled arrival or departure date time
          example: '2017-12-19T08:00:00+02:00'
        route:
          $ref: '#/components/schemas/Route'
        version:
          type: integer
          format: int64
          description: Version of the Flight object
          example: 1509120429
    Route:
      description: Flight route
      properties:
        origin:
          $ref: '#/components/schemas/Aerodrome'
        destination:
          $ref: '#/components/schemas/Aerodrome'
        via-1:
          $ref: '#/components/schemas/Aerodrome'
        via-2:
          $ref: '#/components/schemas/Aerodrome'
      type: object
    Text:
      description: Text
      properties:
        en:
          type: string
        nl:
          type: string
        colour:
          type: string
          example: '#FFFFFF'
security:
  - bearerAuth: [public-r]
