openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/erezblm/IoTAdapterDownlink/1.0.0
info:
  version: "0.1.1"
  title: IoT Adapter -> AT IoT Server
  description: API for updates sent from IoT Adapter server
paths:
          
  /updates/devices/telemetry:
    post:
      tags:
        - Devices
      description: "Telemetry sent from device"
      parameters:
      - $ref: '#/components/parameters/deviceId'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest' 
        '404':
          $ref: '#/components/responses/NotFound' 
        '500':
          $ref: '#/components/responses/InternalError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TelemetryData'        
  
      
  /updates/devices/configurations:
    post:
      tags:
        - Devices
      description: "Current full configuration set of device, sent upon any change"
      parameters:
      - $ref: '#/components/parameters/deviceId'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest' 
        '404':
          $ref: '#/components/responses/NotFound' 
        '500':
          $ref: '#/components/responses/InternalError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceConfigs'
              
  /updates/devices/command:
    post:
      tags:
        - Devices
      description: "Status for command request completed/rejected/timeout"
      parameters:
      - $ref: '#/components/parameters/deviceId'
      - $ref: '#/components/parameters/commandId'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest' 
        '404':
          $ref: '#/components/responses/NotFound' 
        '500':
          $ref: '#/components/responses/InternalError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommandStatus'
              
  /updates/devices/version:
    post:
      tags:
        - Devices
      description: "Device version update status"
      parameters:
      - $ref: '#/components/parameters/deviceId'
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest' 
        '404':
          $ref: '#/components/responses/NotFound' 
        '500':
          $ref: '#/components/responses/InternalError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VersionStatus'
    
              
              
          
components:
  responses:
    BadRequest:
      description: The request was not properly formatted
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: The server encountered an error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  
  parameters:
    deviceId:
      in: query
      description: ID of device (base64 + URL encoded)
      name: deviceId
      required: true
      schema:
        type: string
        format: byte
    commandId:
      in: query
      description: Unique ID of command instance, received upon creation of command
      name: commandId
      required: true
      schema:
        type: string
        format: guid
      
  
  schemas:
    VersionStatus:
      description: Details of updated version
      allOf:
      - $ref: '#/components/schemas/VersionID'
      - type: object
        properties:
          status:
            type: string
            enum:
            - completed
            - failed
          totalRetries:
            type: integer
        required:
        - versionID
        - status
        - totalRetries
      
            
    DeviceConfigs:
      description: List of device configurations 
      type: array
      items:
        type: object
        properties:
          key:
            description: Configuration key name (base64)
            type: string
            format: byte
          value:
            description: Value reported by device (base64)
            type: string
            format: byte
        required:
        - key
        - value
    CommandStatus:
      description: Payload of command (can be empty)
      type: object
      properties:
        status:
          description: Command status
          type: string
          enum:
          - completed
          - rejected
          - timeout
      required:
      - status
    VersionID:
      type: object
      properties:
        versionID:
          description: Version ID (base64)
          type: string
          format: byte
    
          
    TelemetryData:
      type: object
      properties:
        time:
          description: timestamp taken in IoT Adapter context.
          type: string
          format: date-time
        data:
          description: Telemetry data (base64)
          type: string
          format: byte
      required:
      - time
      - data
          

        
    Error:
      type: object
      properties:
        description:
          type: string
