openapi: 3.0.0
info:
  version: "1.0.0-mvp"
  title: red5.ai API
  description: Описание програмного интерфейса системы оценки недвижимого имущества red5.ai
servers:
  - url: 'http://34.244.17.82/api/v1'
    description: Internal staging server for testing and development
paths:
  '/property_kpi/':
    get:
      summary: Return KPI for property in set location, segment and class.
      parameters:
        - in: query
          name: token
          schema:
            type: string
        - in: query
          name: lat
          description: latitude
          schema:
            type: number
            format: float
        - in: query
          name: lng
          description: langitude
          schema:
            type: number
            format: float
        - in: query
          name: segment_id
          schema:
            type: integer
        - in: query
          name: class_id
          description: property class - A+, A, B+, B, B-, C, D
          schema:
            type: string
        - in: query
          name: currency
          description: "ISO 3 currency code"
          schema:
            type: string
        - in: query
          name: geofence_method_id
          schema:
            type: string
        - in: query
          name: gla
          schema:
            type: number
            format: "float (sqm)"
        - in: query
          name: nla
          schema:
            type: number
            format: "float (sqm)"
        - in: query
          name: noi
          schema:
            type: number
            format: float
        - in: query
          name: opex
          schema:
            type: number
            format: float
        - in: query
          name: capex
          schema:
            type: number
            format: float
            
      responses:
        '200':
          description: Ok
          content: 
            application/json:
              schema:
                type: object
                properties:
                  market_value:
                    type: number
                    format: float
                  market_value_currency:
                    type: string
                    format: ISO3 currency code
                  market_value_method:
                    type: string
                  normolized_noi:
                    type: number
                    format: float
                  cap_rate:
                    type: number
                    format: float
                  triple_net_rate:
                    type: number
                    format: float
                  own_triple_net_rate:
                    type: number
                    format: float
        '403':
          description:  Unauthorized request
                    
  '/triple_net_rate/':
    get:
      summary: Return Triple Net Rate for property in set coords, segment and class
      parameters:
        - in: query
          name: token
          schema:
            type: string
        - in: query
          name: lat
          schema:
            type: number
            format: float
        - in: query
          name: lng
          schema:
            type: number
            format: float
        - in: query
          name: segment_id
          schema:
            type: integer
        - in: query
          name: class_id
          schema:
            type: string
        - in: query
          name: geofence_method_id
          description: "radius by default"
          schema:
            type: integer
        - in: query
          name: score_method
          description: "median by default"
          schema:
            type: string
        - in: query
          name: currency_code
          schema:
            type: string
            format: "ISO3 currency code"
      responses:
        '200':
          description: Ok
          content: 
            application/json:
              schema:
                type: object
                properties:
                  triple_net_rate:
                    type: number
                    format: float
                  triple_net_rates:
                    type: array
                    items:
                        type: number
                        format: float
                  method:
                    type: string
        '403':
          description:  Unauthorized request
                
                
  '/currencies/':
      get:
        summary: Returns a list of available currencies
        responses:
          "200":
            description: Ok
            content: 
              application/json:
                schema:
                  type: array
                  items: 
                    $ref: '#/components/schemas/Currency'
          "403":
            description: Unauthorized request
            
  '/segments/':
    get:
      summary: Returns a list of property segments
      responses:
        "200":
          description: Ok
          content: 
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Segment'
        "403":
          description: Unauthorized request
  '/geofence_methods/':
    get:
      summary: Return a list of geofence methods.
      responses:
        "200":
          description: Ok
          content: 
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/GeofenceMethod'
        "403":
          description: Unauthorized request
  '/property_classes/':
    get:
      summary: Return a list of asset classes.
      responses:
        "200":
          description: Ok
          content: 
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/PropertyClass'
        "403":
          description: Unauthorized request
        
      
schemes:
  - https
  
components:
  schemas:
    Segment:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        definition:
          type: string
        
    PropertyClass:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        definition:
          type: string
          
    GeofenceMethod:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        definition:
          type: string
  
    Currency:
      properties:
        code:
          type: string
          format: "ISO 3 currency code"
        name:
          type: string
        symbol:
          type: string
          format: "unicode currency symbol"
