fo:
  description: Fondeadora pin API
  title: Fondeadora Test pin API
  version: 1.0.0
paths:
  /:
    get:
      description: Get Health
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthSchema'
openapi: 3.0.0
components:
  schemas:
    HealthSchema:
      type: object
      properties:
        status:
          type: string