openapi: 3.0.0
info:
  version: '1.0'
  title: 'People'
  description: '4software People API documentation'
tags:
- name: userResource
  description: Controller for managing users

paths: 
  /people:
    get:
      tags:
      - userResource
      summary: Get all users in application
      operationId: getAllUsersUsingGET
      parameters:
       - name: q
         in: query
         description: Global searching
         schema:
           type: string
       - name: zipCode
         in: query
         description: Number of records per page.
         schema:
           type: string
       - name: city
         in: query
         description: Number of records per page.
         schema:
           type: string
       - name: email
         in: query
         description: Number of records per page.
         schema:
           type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The user ID.
                  name:
                    type: string
                    description: The user name.
                    example:  John
                  surname:
                    type: string
                    description: The user surname.
                    example:  Doe
                  zipCode:
                    type: string
                    description: City zip code.
                    example:  38891
                  country:
                    type: string
                    description: Country name.
                    example: Germany
                  city:
                    type: string
                    description: City name.
                    example: Hamburg
                  street:
                    type: string
                    description: Street name.
                    example: 8921 Johans Muller
                  phone:
                    type: string
                    description: User phone.
                    example: +48 211 111 222
                  email:
                    type: string
                    description: User email.
                    example:  test@test.com
                  avatar:
                    type: string
                    description: Link to user avatar
                    example: https://s3.amazonaws.com/exampleface
    post:
      tags:
      - userResource
      summary: Create user in application
      operationId: createUserUsingPOST
      requestBody:
        description: User model
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                  name:
                    type: string
                    description: The user name.
                    example:  John
                  surname:
                    type: string
                    description: The user surname.
                    example:  Doe
                  zipCode:
                    type: string
                    description: City zip code.
                    example:  "38891"
                  country:
                    type: string
                    description: Country name.
                    example: Germany
                  city:
                    type: string
                    description: City name.
                    example: Hamburg
                  street:
                    type: string
                    description: Street name.
                    example: 8921 Johans Muller
                  phone:
                    type: string
                    description: User phone.
                    example: +48 211 111 222
                  email:
                    type: string
                    description: User email.
                    example:  test@test.com
                  avatar:
                    type: string
                    description: Link to user avatar
                    example: https://s3.amazonaws.com/exampleface
              required:
                - name
                - surname
                - email
          text/plain:
            schema:
              type: string
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: The user name.
                    example:  John
                  surname:
                    type: string
                    description: The user surname.
                    example:  Doe
                  zipCode:
                    type: string
                    description: City zip code.
                    example:  "38891"
                  country:
                    type: string
                    description: Country name.
                    example: Germany
                  city:
                    type: string
                    description: City name.
                    example: Hamburg
                  street:
                    type: string
                    description: Street name.
                    example: 8921 Johans Muller
                  phone:
                    type: string
                    description: User phone.
                    example: +48 211 111 222
                  email:
                    type: string
                    description: User email.
                    example:  test@test.com
                  avatar:
                    type: string
                    description: Link to user avatar
                    example: https://s3.amazonaws.com/exampleface
                  id:
                    type: integer
                    description: The user ID.
              
    
  /people/{id}:
  
    get:
      tags:
      - userResource
      summary: Get user by id
      operationId: getUserUsingGET
      parameters:
      - name: id
        in: path
        description: Unique id used for indicate user
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The user ID.
                  name:
                    type: string
                    description: The user name.
                    example:  John
                  surname:
                    type: string
                    description: The user surname.
                    example:  Doe
                  zipCode:
                    type: string
                    description: City zip code.
                    example:  38891
                  country:
                    type: string
                    description: Country name.
                    example: Germany
                  city:
                    type: string
                    description: City name.
                    example: Hamburg
                  street:
                    type: string
                    description: Street name.
                    example: 8921 Johans Muller
                  phone:
                    type: string
                    description: User phone.
                    example: +48 211 111 222
                  email:
                    type: string
                    description: User email.
                    example:  test@test.com
                  avatar:
                    type: string
                    description: Link to user avatar
                    example: https://s3.amazonaws.com/sampleface
                    
  
    patch:
      tags:
      - userResource
      summary: Update user in application
      operationId: updateUserUsingPUT
      parameters:
      - name: id
        in: path
        description: Unique id used for indicate user
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: User model
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                  name:
                    type: string
                    description: The user name.
                    example:  John
                  surname:
                    type: string
                    description: The user surname.
                    example:  Doe
                  zipCode:
                    type: string
                    description: City zip code.
                    example:  "38891"
                  country:
                    type: string
                    description: Country name.
                    example: Germany
                  city:
                    type: string
                    description: City name.
                    example: Hamburg
                  street:
                    type: string
                    description: Street name.
                    example: 8921 Johans Muller
                  phone:
                    type: string
                    description: User phone.
                    example: +48 211 111 222
                  email:
                    type: string
                    description: User email.
                    example:  test@test.com
                  avatar:
                    type: string
                    description: Link to user avatar
                    example: https://s3.amazonaws.com/sampleface
          text/plain:
            schema:
              type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: The user name.
                    example:  John
                  surname:
                    type: string
                    description: The user surname.
                    example:  Doe
                  zipCode:
                    type: string
                    description: City zip code.
                    example:  "38891"
                  country:
                    type: string
                    description: Country name.
                    example: Germany
                  city:
                    type: string
                    description: City name.
                    example: Hamburg
                  street:
                    type: string
                    description: Street name.
                    example: 8921 Johans Muller
                  phone:
                    type: string
                    description: User phone.
                    example: +48 211 111 222
                  email:
                    type: string
                    description: User email.
                    example:  test@test.com
                  avatar:
                    type: string
                    description: Link to user avatar
                    example: https://s3.amazonaws.com/sampleface
              
    
    
    delete:
      tags:
      - userResource
      summary: Delete user by id
      operationId: deleteUserUsingDELETE
      parameters:
      - name: id
        in: path
        description: Unique id used for indicate user
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: OK
          
servers:
  - description: URI address
    url: http://localhost:3000
