openapi: 3.0.0
info: 
  title: "Api for sports"
  description: "Test api for sport"
  version: "1"
paths:
  /products/{productId}:
    get:
      parameters: 
        - in: path
          name: productId
          required: true
          schema:
            type: integer
            example: 1
        - in: header
          name: custom-security-header
          required: false
          schema:
            type: integer
            example: 12345-213123-123123
      responses:
        200:
          description: "Product"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        500:
          $ref: '#/components/responses/500ApiError'
  /products:
    post: 
      description: Create product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        200:
          description: "The product has been created"
        500:
          $ref: '#/components/responses/500ApiError'
    get:
      parameters: 
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/PageNumber'
      responses:
        200:
          description: "List of the products in the catalog"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        500:
          $ref: '#/components/responses/500ApiError'
components:
  parameters:
    PageNumber:
      in: query
      name: pageNumber
      description: Page number to return
      required: false
      schema:
        type: integer
        example: 1
    PageSize:  
      in: query
      name: pageSize
      description: Page size
      required: false
      schema:
        type: integer
        example: 10
        maximum: 100
  schemas:
    Product:
      type: object
      required: 
        - name
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Bicycle
        description:
          type: string
          example: Cool Bicycle
        image_title:
          type: string
          example: Bicycle red
        image:
          type: string
          example: https://test/123.png
  responses:
    500ApiError:
      description: This is an unexpected error
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: string
                example: 500
              message:
                type: string
                example: This is an error
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/falsealarm90/test-api/1
