openapi: 3.0.0
info:
  version: "10.3.1"
  title: DocumentsList
  description: Common DocumentsList API
paths:
  /documents/:
    get:
      tags:
      - document center
      summary: Get a list of Documents based on the requestor.
      description: 'This API returns a list of document object associated with the
        member or provider or broker based on the information provided on x-zpr-user-identities. Additional search filters can be included as part of the configuration,
        for example, can include a date range search.

        '
      operationId: documents_list
      parameters:
      - name: document_category
        in: query
        description: carrier specific document categorization for filtering. New categories
          can be included based on configuration.
        required: false
        style: form
        explode: false
        schema:
          type: string
          enum:
          - claims
          - benefits
          - forms
          - policies
          - tax_documents
          - policies_and_guidelines
          - training_material
          - resources
          - id_cards
          - anocs
          - eobs
          - provider_directory
          - sbcs
          - drug_formulary
          - otc_catalog
      - name: policy_id
        in: query
        description: unique policy id.
        required: false
        style: form
        explode: false
        schema:
          type: string
      - name: member_id
        in: query
        description: this is the internal unique identifier for the member to be used
          when requesting a document that is built based on this list of members e.g.
          If an ID Card PDF is to be generated based on a selection of members on
          the plan, then this parameter will be used to provide that list of member_id's.
          Note that the document_category will be used in conjunction with this parameter.
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: date_received_before
        in: query
        description: 'Filters for entries with date_received before the specified date. Documents
          with a date_received before the date passed in this parameter will be listed in the response.'
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: date
      - name: date_received_after
        in: query
        description: 'Filters for entries with date_received after the specified date. Documents
          with a date_received after the date passed in this parameter will be listed in the response.'
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: date
      - name: search_string
        in: query
        description: Keyword search that can be implemented by Payer's depending on their search capabilities
        required: false
        style: form
        explode: true
        schema:
          type: string
      - $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/PaginationQueryParameters/10.1#/components/parameters/orderingParam
      - $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/PaginationQueryParameters/10.1#/components/parameters/pageParam
      - $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/PaginationQueryParameters/10.1#/components/parameters/pageSizeParam
      responses:
        '200':
          description: provides list of Document object associated with the search
            parameters.
          content:
            application/json:
              schema:
                required:
                - count
                - results
                type: object
                properties:
                  count:
                    type: integer
                    description: Count representing the total number of objects available
                      to be returned in the results array
                  next:
                    type: integer
                    description: query identifier defined by the api developer for
                      getting the next set of records
                  previous:
                    type: integer
                    description: query identifier defined by the api developer for
                      getting the previous set of records
                  results:
                    type: array
                    items:
                      $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/DocumentModel/10.3.1#/components/schemas/Document
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/ErrorModel/10.0.2#/components/schemas/Error'
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/ErrorModel/10.0.2#/components/schemas/Error'
