openapi: 3.0.0
info:
  version: "1.0.2"
  title: 'Dokumentation - DMS (Basis)'
  description: 'Synchronisation der Dokumentationen aus Alberta für den Import in ein DMS'
paths:
  /document:
    get:
      tags:
        - document
      parameters:
        - name: api_key
          in: header
          required: true
          schema:
            type: string
          description: The API-Key
        - name: createdAfter
          in: query
          required: true
          schema:
            type: string
          description: '2019-02-21T09:30:00.000Z (im UTC-Format)'    
      summary: Abgeschlossene Dokumentationen abrufen
      description: Szenario - das WaWi/DMS fragt in einem bestimmten Intervall bei Alberta nach, ob es abgeschlossene Dokumentationen gibt
        ----- Aufruf => document/?createdAfter=[updatedAfter]
      operationId: getClosedDocuments 
      responses:
        '200':
          description: Abgeschlossene Dokumentationen konnten angefragt werden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfDocuments'
            application/xml:
              schema:
                $ref: '#/components/schemas/ArrayOfDocuments'
        '400':
          description: Bad Request -> Syntaxfehler im Request
        '401':
          description: Unauthorized -> keine Berechtigung für Operation
components:
  schemas:
    Document:
      type: object
      properties:
        alberta:
          type: object
          properties:
            _id: 
              type: string
              example: a4adecb6-126a-4fa6-8fac-e80165ac8980
              description: Id der Dokumentation in Alberta
            fileName: 
              type: string
              example: a4adecb6-126a-4fa6-8fac-e80165ac8980.pdf
              description: Dateiname bei Upload
            timestamp:
              type: string
              format: date
              example: "12.10.2017 15:00:33"
              description: Der Zeitstempel der letzten Änderung
        DocumentData:
          type: object
          properties:
            DocumentKey: 
              type: string
              example: a4adecb6-126a-4fa6-8fac-e80165ac8980
              description: Id der Dokumentation in Alberta
            Fields:
              type: object
              properties:
                DokArt: 
                  type: string
                  example: Patientenwahlrechtserklärung
                  description: Name der Dokumentation in Alberta
                Modul: 
                  type: string
                  example: VERKAUF  
                  description: Optional, falls nötig für DMS
                Zugriffsliste:
                  type: string
                  example: Zugriffsliste
                  description: Optional, falls nötig für DMS
                Debitor:
                  type: string
                  example: D1234567
                  description: Debitorennummer des Patienten
                Kontaktnummer:
                  type: string
                  example: KT324234234
                  description: Kontaktnnummer des Patienten im Wawi (Kumavision)
                Mandant:
                  type: string
                  example: Happy Homecare GmbH
                  description: falls Mandantenkennung nötig
      xml:
        name: Dokumentation
    ArrayOfDocuments:
      type: array
      items:
        $ref: '#/components/schemas/Document'
      description: Eine Liste von Dokumentationen
  requestBodies:
    Document:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Document'
        application/xml:
          schema:
            $ref: '#/components/schemas//Document'
      description: Die Dokumentation
      required: true
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/it-labs.de/AuftragWawi/1.0.1
