openapi: 3.0.0

info:
  title: SAP Forecasts
  description: description.
  version: 0.0.1

servers:
  - url: https://atsapngwd01.aucklandtransport.govt.nz:8443
    description: SAP Dev
  - url: https://atsapngwu01.aucklandtransport.govt.nz:8443
    description: SAP QA
  - url: https://atsapngwp01.aucklandtransport.govt.nz:8443
    description: SAP Production

paths:
  /sap/projects/{edison_project_id}/forecasts/plans/{plan_version}:
    post:
      summary: Option 1.
      description: description.
      
      parameters: 
        - name: edison_project_id
          in: path
          required: true
          description: description.
          schema:
            type: string
            
        - name: plan_version
          in: path
          required: true
          description: description.
          schema:
            type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                FiscalYear: 
                  $ref: '#/components/schemas/FiscalYear'

                ForecastData:
                  $ref: '#/components/schemas/ForecastData'

      responses:
        '200':
          description: description
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ResponseBody'
                
  /sap/forecasts:
    post:
      summary: Option 2.
      description: description.

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                PlanVersion:
                  $ref: '#/components/schemas/PlanVersion'
                  
                FiscalYear: 
                  $ref: '#/components/schemas/FiscalYear'
                  
                e365ProjectId:
                  $ref: '#/components/schemas/EdisonProjectId'

                ForecastData:
                  $ref: '#/components/schemas/ForecastData'

      responses:
        '200':
          description: description
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ResponseBody'
                  
components:
  schemas:
    FiscalYear:
      type: string
      description: Mapped from CostTypeYear
    
    PlanVersion:
      type: string
      description: description
      
    EdisonProjectId:
      type: string
      description: Mapped from ProjectIdentifier
      
    ForecastData:  
      type: array
      items:
        type: object
        properties:
          WBSElementId:
            type: string
            description: Mapped from CostTypeFree1
          CostElementCode:
            type: string
            description: Mapped from CostTypeCat5
          Month1:
            type: string
            description: Mapped from CostTypePeriod1
          Month2:
            type: string
            description: Mapped from CostTypePeriod2
          Month3:
            type: string
            description: Mapped from CostTypePeriod3
          Month4:
            type: string
            description: Mapped from CostTypePeriod4
          Month5:
            type: string
            description: Mapped from CostTypePeriod5
          Month6:
            type: string
            description: Mapped from CostTypePeriod6
          Month7:
            type: string
            description: Mapped from CostTypePeriod7
          Month8:
            type: string
            description: Mapped from CostTypePeriod8
          Month9:
            type: string
            description: Mapped from CostTypePeriod9
          Month10:
            type: string
            description: Mapped from CostTypePeriod10
          Month11:
            type: string
            description: Mapped from CostTypePeriod11
          Month12:
            type: string
            description: Mapped from CostTypePeriod12
      
    ResponseBody:
      type: object
      properties:
        Message:
          type: string
