openapi: 3.0.0

servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/TheCezae/VUTTR/1.0.0
info:
  description: API for VUTTR (Veru Useful Tools To Remember)
  version: "1.0.0"
  title: VUTTR
  contact:
    email: lucianodecezare@gmail.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: Users
    description: Operations available to all users
paths:
  /tools:
    get:
      tags:
        - Users
      summary: searches all or within all tools
      operationId: searchAllTools
      description: Brings all tools
      parameters:
        - in: query
          name: tag
          required: false
          schema:
            type: string
          description: The tag to be searched
      responses:
        '200':
          description: search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tool'
        '500':
          description: error
    post:
      tags:
        - Users
      summary: adds a tool
      operationId: addTool
      description: Adds a tool
      responses:
        '201':
          description: item created
        '500':
          description: error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tool'
        description: Tool to add
    delete:
      tags:
        - Users
      summary: delete a tool
      operationId: deleteTool
      description: Delete a tool
      responses:
        '204':
          description: no content
        '500':
          description: error
components:
  schemas:
    tool:
      type: object
      required:
        - title
        - link
        - description
        - tags
      properties:
        id:
          type: string
          format: uuid
          example: 5e1f817bc2f3850373a7462f
        title:
          type: string
          example: NodeJS
        description:
          type: string
          example: Runs javascript everywhere
        tags:
          type: array
          items:
            type: string
          example: [nodejs, javascript]
