openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/lavakan/test/1.0.0
info:
  description: This is a simple API
  version: "1.0.1"
  title: Lavakan API
  contact:
    email: ismael@lavakan.es
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /ClubCard:
    post:
      tags:
        - developers
      summary: Inserts a card to the db
      operationId: insertClubCard
      description: Insert a Card to the db
      responses:
        '200':
          description: ClubCard created
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pclubcard'
        description: Inventory item to 
  '/ClubCard/{ClubCardSN}':
    get:
      tags:
        - developers
      summary: Show info from card SN
      operationId: getClubCard
      parameters:
        - name: ClubCard
          in: path
          description: The SN of the card we want to fetch. Use test1 for testing.
          required: true
          schema:
            type: string
      description: Modify a Card from the system
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: 'clubcard'
        '400':
          description: 'invalid input, object invalid
  '/ClubCard/{ClubCardSN}':
    put:
      tags:
        - developers
      summary: Update an existing club card
      operationId: updateClubCard
      parameters:
        - name: ClubCard
          in: path
          description: The SN of the card we want to fetch. Use test1 for testing.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/clubcard'
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception

components:
  schemas:
    pclubcard:
      type: object
      required:
        - id
        - cardtype
        - balance
        - mail
      properties:
        cardSN:
          type: string
          format: uuid
          example: 123A456B
        cardType:
          type: string
          example: 5041
        balance:
          type: string
          example: 24
        fPoints:
          type: string
          example: 10
        lastWriteSN:
          type: string
          example: 178BBBFF00800A11
        mail:
          type: string
          example: test@lavakan.es
        phone:
          type: integer
          example: 7555172
        country:
          type: integer
          example: 0
        petName:
          type: string
          example: Dipsy
        animal:
          type: integer
          example: 0
        race:
          type: string
          example: Pastor Aleman
        sex:
          type: integer
          example: 0
        birthDate:
          type: string
          example: 2018/04/03
        status:
          type: boolean
          example: true
    clubcard:
      type: object
      required:
        - id
        - cardtype
        - balance
        - mail
      properties:
        id:
          type: integer
          example: 1
        cardSN:
          type: string
          format: uuid
          example: 123A456B
        cardType:
          type: string
          example: 5041
        balance:
          type: string
          example: 24
        fPoints:
          type: string
          example: 10
        lastWriteSN:
          type: string
          example: 178BBBFF00800A11
        mail:
          type: string
          example: test@lavakan.es
        phone:
          type: integer
          example: 7555172
        country:
          type: integer
          example: 0
        petName:
          type: string
          example: Dipsy
        animal:
          type: integer
          example: 0
        race:
          type: string
          example: Pastor Aleman
        sex:
          type: integer
          example: 0
        birthDate:
          type: string
          example: 2018/04/03
        status:
          type: boolean
          example: true
