openapi: 3.0.0
info:
  version: "10.3.1"
  title: DocumentsDetail
  description: Common DocumentsDetail API
paths:
  /documents/{id}/:
    get:
      tags:
      - document center
      summary: Get document using the document id.
      description: |
        This API returns a document object associated with the requestor
        for an request to get meta data as application/json.
        This API endpoint also can be configured to return a binary stream if the
        response needed is for an application/pdf or image/*.
      operationId: documents_read
      parameters:
      - name: id
        in: path
        description: unique document identifier to retrieve the associated document.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: policy_id
        in: query
        description: unique policy id.
        required: false
        style: form
        explode: false
        schema:
          type: string
      - name: member_number
        in: query
        description: |
          member number to retrieve associated id card. This is only applicable
          when a member is requesting an ID Card for other members on the plan i.e.
          spouse, dependents. Multiple member numbers can be supported as member_number=1&member_number=2&member_number=3
          as an example.
        required: false
        style: form
        explode: false
        schema:
          type: string
      - name: member_coverage_id
        in: query
        description: |
          Member Coverage ID identifying document for a specific Member's
          coverage type i.e. Medical, Dental etc. This is mainly only applicable if
          a document such as an ID Card is to be downloaded for a specific member
          and a specific product type.
        required: false
        style: form
        explode: false
        schema:
          type: string
      - name: effective_date
        in: query
        description: |
          effective date of the document. Usually only applies to downloading
          ID Cards for current benefit period or future benefit period.
        required: false
        style: form
        explode: false
        schema:
          type: string
      - name: termination_date
        in: query
        description: |
          termination date of the document. Usually only applies to downloading
          ID Cards for current benefit period or future benefit period.
        required: false
        style: form
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: provides the Document object associated with the document id.
          content:
            application/json:
              schema:
                $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/DocumentModel/10.3.1#/components/schemas/Document
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/ErrorModel/10.0.2#/components/schemas/Error'
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/ErrorModel/10.0.2#/components/schemas/Error'
