openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: Test and Learn API
    url: https://virtserver.swaggerhub.com/faisalsikder/test-new-rest-api/1.0.0
info:
  description: This is a simple API
  version: "1.0.0"
  title: Simple Inventory API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  '/product/{productId}':
    get:
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: integer
            example: 12345
        - in: header
          name: customer-security-header
          required: false
          schema:
            type: integer
            example: 123-123-123
      responses:
        200:
          description: This is a list of the products in the catalog
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        500:
          $ref: '#/components/responses/500APIError'
  /product:
    post:
      description: Add a product to the catalog
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        200:
          description: This is a list of the products in the catalog
        500:
          $ref: '#/components/responses/500APIError'
    get:
      parameters:
        - $ref: '#/components/parameters/pageNumber'
        - $ref: '#/components/parameters/pageSize'
      responses:
        200:
          description: This is a list of the products in the catalog
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        500:
          $ref: '#/components/responses/500APIError'
components:
  parameters:
    pageNumber:
      in: query
      name: pageNumber
      description: page number to return
      required: false
      schema:
        type: integer
        example: 1
    pageSize:
      in: query
      name: pageSize
      description: number of results in the page
      required: false
      schema:
        type: integer
        example: 10
        maximum: 100  
  schemas:
    Product:
      type: object
      required: 
        - name
      properties:
        id:
          type: integer
          example: 400
        name:
          type: string
          example: Faisal Sikder
        description:
          type: string
          example: xxxx xxxx xxx yyy yyy
        image_title:
          type: string
          example: mineral-water-lemon-lime
        image:
          type: string
          example: https://hplussport.com/images/1234
  responses:
    500APIError:
      description: This is an unexpected error
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: string
                example: 500
              message:
                type: string
                example: this is an error
