openapi: 3.0.1
info:
  title: Winds
  description: Calculates XXX.
  version: '1.0'
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/noaplica6/info/1.0
  - url: 'https://api.example.com/winds'
paths:
  /v1/stillairdistance:
    get:
      tags:
        - Winds API
      summary: getStillAirDistance
      description: Calculates head wind (knots) and equivalent still air distance (nautical miles) for a given great circle route. The route is computed using the great circle distance. The arc of a great circle connecting two points represents the shortest distance on the surface between them.
      operationId: getStillAirDistance
      parameters:
        - name: originLat
          in: query
          description: Latitude of the route origin (decimal degrees). Must be >= -90 and <=90.
          required: true
          schema:
            type: number
        - name: originLong
          in: query
          description: Longitude  of the route origin (decimal degrees). Must be >= -180 and <=180.
          required: true
          schema:
            type: number
        - name: destinationLat
          in: query
          description: Latitude of the route destination (decimal degrees). Must be >= -90 and <=90.
          required: true
          schema:
            type: number
        - name: destinationLong
          in: query
          description: Longitude  of the route destination (decimal degrees). Must be >= -180 and <=180.
          required: true
          schema:
            type: number
        - name: altitude
          in: query
          description: Altitude (feet). Must be >=364 and <=101885.Wind data is only available for standard altitudes (according to United States Standard Atmosphere). For non-standard altitudes calculation is done using an interpolation. Route equivalent winds for the two standard altitudes above and the two standard altitudes below are used for a non-standard altitude. A bi-parabolic fit is used to compute values at the requested altitude.
          required: true
          schema:
            type: number
        - name: airspeed
          in: query
          description: Airspeed (knots). Must be >=150.
          required: true
          schema:
            type: number
        - name: reliability
          in: query
          description: Reliability (%). Must be >=50 and<=99. Decimal values are not allowed.
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Still air distance calculation.
          content:
            application/json:
              example: 2000
        '404':
          description: 404 Mensaje.
          content:
            application/json:
              example: 4004
  /v1/rangemap:
    get:
      tags:
        - Winds API
      summary: getRangeMap
      description: 'Calculates aircraft range from a given location (origin), adjusting the distances in all directions based on the historical wind data. The resulting range map is presented as a GeoJSON FeatureCollection consisting of 360 points around the given origin. Coordinates of each point are specified using decimal degree format. Each point also contains bearing from the origin (degrees), head wind speed (knots), and wind adjusted aircraft range (nautical miles) on the corresponding great circle route.'
      operationId: getRangeMap
      parameters:
        - name: originLat
          in: query
          description: Latitude of the route origin (decimal degrees). Must be >= -90 and <=90.
          required: true
          schema:
            type: number
        - name: originLong
          in: query
          description: Longitude  of the route origin (decimal degrees). Must be >= -180 and <=180.
          required: true
          schema:
            type: number
        - name: stillAirRange
          in: query
          description: Range of the aircraft in still air (nautical miles). Must be >= 20 and <= 10000.
          required: true
          schema:
            type: number
        - name: altitude
          in: query
          description: Altitude (feet). Must be >=364 and <=101885.Wind data is only available for standard altitudes (according to United States Standard Atmosphere). For non-standard altitudes calculation is done using an interpolation. Route equivalent winds for the two standard altitudes above and the two standard altitudes below are used for a non-standard altitude. A bi-parabolic fit is used to compute values at the requested altitude.
          required: true
          schema:
            type: number
        - name: airspeed
          in: query
          description: Airspeed (knots). Must be >=150.
          required: true
          schema:
            type: number
        - name: reliability
          in: query
          description: Reliability (%). Must be >=50 and<=99. Decimal values are not allowed.
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Range map calculation.
          content:
            application/json: {}
components: {}
tags:
  - name: Winds API
x-ms-export-notes:
  - 'The exported API contains schemas that aren''t of content type ''application/vnd.oai.openapi.components+json'', and are hence not exported as OpenAPI components.'
