openapi: 3.0.0
servers:
  - description: Daylite API
    url: 'https://api.marketcircle.net/v1'
info:
  version: v1
  description: Daylite API Documentation
  title: Daylite API Documentation
security:
  - oAuth2:
      - 'daylite:read'
      - 'daylite:write'
  - bearerAuth: []
tags:
  - name: Authentication
  - name: Contacts
  - name: Companies
  - name: Opportunities
  - name: Projects
  - name: Notes
  - name: Tasks
  - name: Appointments
  - name: Emails
  - name: Forms
  - name: Groups
  - name: Users
  - name: Teams
  - name: Extra Fields
paths:
  /:
    get:
      tags:
        - Authentication
      summary: Token verification
      description: Endpoint to test for network connectivity to the API and to check if an authentication token is valid.
      security:
        - oAuth2:
            - 'daylite:read'
  /info:
    get:
      tags:
        - Authentication
      summary: Token metadata
      description: 'This endpoint displays information about the authentication token. The application_identifier, ip_address, scopes, user, and customer are returned. '
  /contacts:
    get:
      tags:
        - Contacts
      summary: List all contacts
      description: This endpoint returns a list of all contacts
      security:
        - oAuth2:
            - 'daylite:read'
    post:
      x-tags: public
      tags:
        - Contacts
      summary: Create a new contact
      description: This endpoint creates a contact
      security:
        - oAuth2:
            - 'daylite:write'
  '/contacts/{id}':
    get:
      tags:
        - Contacts
      summary: Retrieve a contact
      description: "This endpoint returns a contact's details"
      security:
        - oAuth2:
            - 'daylite:read'
    patch:
      tags:
        - Contacts
      summary: Update an existing contact
      description: "This endpoint updates a contact's details"
      security:
        - oAuth2:
            - 'daylite:write'
    delete:
      tags:
        - Contacts
      summary: Remove an existing contact
      description: 'This endpoint removes a contact. If it is not in the trash, it will be placed there. If it is in the trash, it will be permanently deleted. '
      security:
        - oAuth2:
            - 'daylite:write'
  /contacts/extra_fields:
    get:
      tags:
        - Contacts
        - Extra Fields
      summary: Display contact extra field names
      description: Display contact extra field names
      security:
        - oAuth2:
            - 'daylite:read'
  /contacts/emails:
    get:
      tags:
        - Contacts
      summary: List of email message links
      description: List of email message links
      security:
        - oAuth2:
            - 'daylite:read'
  /companies:
    get:
      tags:
        - Companies
      summary: List all companies
      description: This endpoint returns a list of all companies
      security:
        - oAuth2:
            - 'daylite:read'
    post:
      x-tags: public
      tags:
        - Companies
      summary: Create a new company
      description: This endpoint creates a company
      security:
        - oAuth2:
            - 'daylite:write'
components:
  securitySchemes:
    oAuth2:
      type: oauth2
      description: 'For more information, see https://developer.marketcircle.com/docs/authentication'
      flows:
        authorizationCode:
          authorizationUrl: 'https://www.marketcircle.com/account/oauth/authorize'
          tokenUrl: 'https://www.marketcircle.com/account/oauth/token'
          refreshUrl: 'https://www.marketcircle.com/account/oauth/token'
          scopes:
            'daylite:read': Read user information
            'daylite:write': Modify user information
    bearerAuth:
      type: http
      scheme: bearer