openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ksinghrajeev/customer/1.0.0
info:
  description: This is an API HPlusSport Customer
  version: "3.0.0"
  title: Customer API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: customer
    description: Customer related calls
paths:
  /customer:
    get:
      tags:
        - cusotmer
      summary: searches cusotmer
      operationId: searchCustomer
      description: |
        By passing in the appropriate options, you can search for
        available customer in the system
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/ksinghrajeev/hplus/1.0.0#/components/schema/Customer'
        '400':
          description: bad input parameter
