openapi: 3.0.0
info:
  version: "1.0.0-oas3"
  title: AWS SES API
  description: >-
    All endpoints of `AWS SES API` are private and protected by an
    `customs headers`. So first you should `contact the
    developer` or refer to the [Documentation](https://docs.google.com/document/d/1wGL9lLIYX3YXIr2UDU5RrGYoexPTcrk0r0PKip1QJ7E/edit#)
  contact:
    email: gianni.prata@soitec.com
paths:
  /sendEmail:
    post:
      tags:
        - SendMail
      summary: Send an Email
      parameters:
        - in: header
          name: X-Soitec-Message
          schema:
            type: string
            example: XXXXXXXX
          description: store in keepass
        - in: header
          name: X-Soitec-Hash
          schema:
            type: string
            example: XXXXXXXX
          description: store in keepass
          
      requestBody:
        description: Parameters to pass in body request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sendEmailRequest'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
        '500':
          description: Internal error
      security:
        - ApiKeyAuth: []

  
servers:
  - url: 'https://us-central1-ses-api-bb663.cloudfunctions.net/awsses'
components:
  schemas:
    sendEmailRequest:
       type: object
       required:
        - addresses
        - sender
        - text
        - subject
       properties:
        addresses:
          type: string
          example: Destination.ToAddresses.member.1=recipient1, Destination.ToAddresses.member.2=recipient2
        sender:
          type: string
          example: no-reply%40soitec.com
        text:
          type: string
        subject:
          type: string
  
  responses:
    NotFound:
      description: The specified resource was not found
    NoContent:
      description: No content to return
    BadRequest:
      description: Bad request
    Unauthorized:
      description: Unauthorized
    InternalError:
      description: Internal Server Error
