openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/mgjoyce/Wellness/1.0.0
info:
  description: Animal Wellness API
  version: "1.0.0"
  title: Animal Wellness API
  contact:
    email: api@lic.co.nz
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: bcs-recorder
    description: Operations available to parties authorised to record Body Condition Scores
  - name: bcs-reader
    description: Operations available to parties authorised to read Body Condition Scores
paths:
  /body-condition-score:
    get:
      tags:
        - bcs-reader
      summary: searches Body Condition Scores for the specified Animal and/or Date
      operationId: searchBodyConditionScore
      description: By passing in the appropriate options, you can search for
        Body Condition Scores in the system
      parameters:
        - in: query
          name: searchString
          description: pass an optional search string for looking up Body Condition Scores
          required: false
          schema:
            type: string
        - in: query
          name: skip
          description: number of records to skip for pagination
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: limit
          description: maximum number of records to return
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BodyConditionScore'
        '400':
          description: bad input parameter
    post:
      tags:
        - bcs-recorder
      summary: adds a Body Condition Score to an Animal
      operationId: addBodyConditionScore
      description: Sends a Body Condition Score observation for an Animal to be recorded
      responses:
        '204':
          description: the Body Condition Score has been accepted for processing, the unique event id can be used to check if this has been successful.
        '400':
          description: the input did not pass initial validation and has been rejected.
        '409':
          description: an existing Body Condition Score already exists for this Animal on the Date specified.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BodyConditionScore'
        description: Body Condition Score to add
components:
  schemas:
    BodyConditionScore:
      type: object
      required:
        - animal-id
        - date
        - score
      properties:
        animal-id:
          type: integer
          example: 29837645
        date:
          type: string
          format: date
          example: "2020-04-01"
        score:
          type: string
          example: "4.5"
          description: "The condition score of animal. The person eyeballs the animal and assigns a score from 0.5 to 9.5 in 0.5 intervals.  Usual measurement is 4.5."
        stature:
          type: integer
          example: 5
          description: "The height of the animal at the shoulder. This measurement is taken from a ruler that is stepped from 1 to 9"
