openapi: 3.0.0
info:
  description: 
      Dinger api for generation payment key and validation payement key.
  version: "1.0.0-oas3-oas3"
  title: Dinger Api
  contact:
    email: yewintnaing44@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
    
servers:
  - url: 'https://dinger.tech/staging/v1/dinger/payment/'

    
tags:
  - name: Dinger
    description: Secured Api calls
  - name: developers
    description: Operations available to regular developers

paths:
  /generate:
    post:
      tags:
        - developers
      summary: generate payment id
      description: |
        By passing in the appropriate options, you can generate 
        payement id in the system
      parameters:
        - name: apiKey
          in: query
          description: pass apiKey for api access control
          schema:
            type: string
            default: 1580124868872
        - name: username
          in: query
          description: custmer name
          schema:
            type: string
        - name: amount
          in: query
          description: order total amount
          schema:
            type: integer
            default: 10000
        - name: phone
          in: query
          description: customer phone number
          schema:
            type: string
        - name: shopUniqueKey
          in: query
          description: shop key
          schema:
            type: string
            default: jrmpjGaBCN
        - name: hashAmount
          in: query
          description: hash-amount
          schema:
            type: string
            default: 2a55ed202fcec592954e937cb8aef7236a90bb05965236c3682a55aed43a43da
      responses:
        '200':
          description: Successfully returned the generated payment id
          content:
            application/json:
              schema:
                type: object
                properties:
                  paymentId:
                    type: string
                    format: uuid
                  createdDate:
                    type: string
                    format: date-time
        '400':
          description: bad input parameter
  /validate:
    get:
      tags:
        - developers
      summary: validate payment id
      description: |
        By passing in the appropriate options, you can validate 
        payement id in the system
      parameters:
        - in: query
          name: apiKey
          description: pass apiKey for api access control
          schema:
            type: string
            default: 1580124868872
        - in: query
          name: paymentId
          schema:
            type: string
      responses:
        '200':
          description: results matching criteria
          content:
            application/json:
              schema:
                type: object
                properties:
                  paymentId:
                    type: string
                    format: uuid
                  username:
                    type: string
                  phone:
                    type: string
                  amount:
                    type: integer
                  createdDate:
                    type: string
        '400':
          description: bad input parameter
