openapi: 3.0.1
info:
  title: News Service
  description: AccelByte news service allows developers to integrate 3rd party application to AccelByte news stream, so that it is easier for them to publish contents from their own custom client application. 
  contact:
    name: Engineering Team at AccelByte
    url: https://accelbyte.io
    email: engineering@accelbyte.io
  version: v1.0.0
servers:
- url: news.accelbyte.io/v1
tags:
- name: News
paths:
  /publisher/category/{category}/news:
    get:
      tags:
      - News
      summary: List news by category
      description: List of all news by the specified category 
      operationId: getNewsUsingGET
      parameters:
      - name: category
        in: path
        description: Category of the news going to be retrieved
        required: true
        schema:
          type: string
      responses:
        200:
          description: Valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsContents'
        404:
          description: <table> <tr><td>Error Code</td><td>Error Message</td></tr>
            <tr><td>90011</td><td>news not found</td></tr><table>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEntity'
    post:
      tags:
      - News
      summary: Publish news to a category
      description: Publish news to the specified category
      operationId: publishNewsUsingPOST
      parameters:
      - name: category
        in: path
        description: Category of the news going to be published
        required: true
        schema:
          type: string
      requestBody:
        description: Publish news example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewsCreate'
        required: true
      responses:
        201:
          description: News published successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsContent'
        400:
          description: <table> <tr><td>Error Code</td><td>Error Message</td></tr>
            <tr><td>90021</td><td>category is required</td></tr><table>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEntity'
        404:
          description: <table> <tr><td>Error Code</td><td>Error Message</td></tr>
            <tr><td>90022</td><td>category does not exist</td></tr><table>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEntity'
  /publisher/category/{category}/news/{newsId}:
    put:
      tags:
      - News
      summary: Update news in a category
      description: Update a specific news in a category by the news id
      operationId: updateNewsUsingPUT
      parameters:
      - name: category
        in: path
        description: Category of the news going to be updated
        required: true
        schema:
          type: string
      - name: newsId
        in: path
        description: Id of the news going to be updated
        required: true
        schema:
          type: string
      requestBody:
        description: Update news example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewsUpdate'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsContent'
        404:
          description: <table> <tr><td>Error Code</td><td>Error Message</td></tr>
            <tr><td>90031</td><td>news not found</td></tr><table>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEntity'
    delete:
      tags:
      - News
      summary: Delete news in a category
      description: Delete a specific news in a category
      operationId: deleteNewsUsingDELETE
      parameters:
      - name: category
        in: path
        description: Category of the news going to be deleted
        required: true
        schema:
          type: string
      - name: newsId
        in: path
        description: Id of the news going to be updated
        required: true
        schema:
          type: string
      responses:
        204:
          description: News deleted successfully
          content: {}
        404:
          description: <table> <tr><td>Error Code</td><td>Error Message</td></tr>
            <tr><td>90041</td><td>news not found</td></tr><table>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorEntity'
components:
  schemas:
    ErrorEntity:
      required:
        - errorCode
        - errorMessage
      type: object
      properties:
        errorCode:
          type: integer
          format: int32
        errorMessage:
          type: string
    NewsCreate:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        tags:
          type: array
          uniqueItems: true
          items:
            type: string
    NewsContent:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        newsId:
          type: string
        title:
          type: string
        content:
          type: string  
        category:
          type: string
        tags:
          type: array
          uniqueItems: true
          items:
            type: string
        updatedAt:
          type: string
          format: date-time
    NewsContents:
      type: object
      properties:
        news:
          type: array
          items:
            $ref: '#/components/schemas/NewsContent'
    NewsUpdate:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        tags:
          type: array
          uniqueItems: true
          items:
            type: string
