openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: Mock Server - no real data
    url: https://virtserver.swaggerhub.com/adoherty47/Score/1.0.0
  - description: TeleSign Enterprise Production Servers - you will be charged for transactions!
    url: https://rest-ww.telesign.com/v1/
info:
  description: This page includes general requirements and service details for this API, as well as instructions on how to use all of its actions.<br/> Looking for Insights reason codes? Check out Insights Reason Code Mappings.
  version: "1.0.0"
  title: Get Started with the Score API
  contact:
    name: docs@telesign.com to provide feedback
    email: docs@telesign.com
tags:
  - name: enterprise
    description: Operations available to enterprise customers
  - name: standard
    description: Operations available through self-service
paths:
  /score/{complete_phone_number}:
    post:
      tags:
        - enterprise
        - standard
      summary: Creates a Score request
      operationId: postScore
      description: Obtain a score for this phone number, as well as other relevant information.
      parameters:
        - name: complete_phone_number
          in: path
          description: The phone number you want to collect information about. Provide the entire phone number, including the country code, with no spaces or special characters.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Your request was fulfilled and resulted in a new resource being created. If you want to code against a response, you should retrieve the status code property in the response object and use that, rather than the HTTP status code. Individual packages within the response may have their own status codes as well.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scoreResponse'
        '400':
          description: 'invalid input, object invalid'
        '401':
          description: an existing item already exists
        '402':
          description: an existing item already exists
        '404':
          description: an existing item already exists
        '429':
          description: an existing item already exists
        '500':
          description: an existing item already exists
        '503':
          description: an existing item already exists
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/scoreRequest'
        description: Input fields for score request
components:
  schemas:
    scoreRequest:
      type: object
      required:
        - account_lifecycle_event
      properties:
        account_lifecycle_event:
          description: Indicate what stage an end user's account is in.
          type: string
          enum:
          - create
          - sign-in
          - transact
          - update
          - delete
          example: create
        originating_ip:
          type: string
          description: Your end user's IP address (do not send your own Ip address). IPv4 and IPv6 are supported. For IPv4, the value must be in the format defined by the Internet Engineering Task Force (IETF) in the Internet-Draft doucment titled [Internet Protocol](https://tools.ietf.org/html/rfc791). For IPv6, the value must be in the format defined by the IETF in the Internet-Draft document titled [IP Version 6 Addressing Architecture](https://tools.ietf.org/html/rfc4291#section-2.2).
        device_id:
          type: string
          description: Your end user's device ID. This value is case sensitive.
        account_id:
          type: string
          description: Your end user's account ID. This value is case sensitive.
        email_address:
          type: string
          description: Your end user's email address. This value is case sensitive.
        request_risk_insights:
          type: string
          description: __(Beta Version Only)__ Pass a `"true"` value for this parameter to receive **score + insights** from the API, instead of just the score. You must also contact Customer Success to enable this new feature before using it. The additional response property `risk_insights` is also returned when including a `"true"` value here.
    scoreResponse:
      type: object
      properties:
        reference_id:
          type: string
          description: A 32-digit hex value used to identify the web service request. The value is unique to each web service request, is randomly-generated by TeleSign, and is returned in the response message immediately following the web service request.
        external_id:
          type: string
        status:
          type: object
          description: An object containing details about the request status. 
          properties:
            code:
              type: integer
            description:
              type: string
            updated_on:
              type: string
