openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Notification Server'
  description: 'Notification'
paths:
  /sendNotification:
    post:
      tags:
      - "NotificationServer"
      operationId: "sendNotification"
      requestBody:        
        description: "Notification to be sent to channel"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Notification"
      responses:
        200:
          description: "A success response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotificationResponse"
        500:
          description: "An error response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotificationResponse"
        
components:
  schemas:
    Notification: 
      type: "object"
      properties:
        notificationId:
          type: "string"
        notificationParameters:
          type: "array"
          items:
            $ref: "#/components/schemas/NotificationParam"
        destination:
          type: "string"
        deliveryChannel:
          type: "string"
    NotificationParam:
      type: "object"
      properties:
        name:
          type: "string"
        value:
          type: "string"
    NotificationResponse:
      type: "object"
      properties:
          out:
            type: "string"
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/s94797/NotificationServer/1.0.0
