openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/tom.hwc/WUC/1.0.0
  - url: https://api-waterusage.hunterwater.com.au/api
    description: Production environment intended for public access
  - url: https://staging-api-waterusage.hunterwater.com.au/api
    description: Staging environment for internal developer and business testing.
info:
  version: "1.0.0"
  title: Water Usage Calculator
  contact:
    email: website@hunterwater.com.au
    name: Hunter Water - Web Projects Team
    url: https://www.hunterwater.com.au/
  description: |
    The water usage calculator is a tool to allow households estimate their average annual water consumption. By answering a series of simple questions, they are presented with their usage profile. Additionally users are able to share their results.

    The API requirements are simple:
    1. download the questions configuration data,
    2. update the answers to the questions,
    2. send an email with results.

    All access is unauthenticated and managed by browser sessions.            
paths:
  /questions:
    get:
      summary: downloads question data
      description: |
        Downloads questionnaire information and configuration, optionally populating response with answers from a previous session.
      parameters:
        - in: query
          name: share_key
          description: share key of a previous session, exposed to users when emailing results
          required: false
          schema:
            type: string
            pattern: '^[a-z0-9]{40}$'
        - in: query
          name: unit
          description: unit of volume measure to use when calculating water usage
          required: false
          schema:
            $ref: '#/components/schemas/UnitValue'
        - in: query
          name: period
          description: period of usage to use when calculating water usage
          required: false
          schema:
            $ref: '#/components/schemas/PeriodValue'
      responses:
        '200':
          description: questionnaire data available, optionally prefilled with answers and usage using share key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuestionsResponse'
        '400':
          description: invalid share key or calculation attempt failure
      tags:
        - Public
  /answers:
    post:
      summary: save answers
      description: |
        Updates user session with any answers provided, also providing a new usage calculation result.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnswersRequest'
      responses:
        '200':
          description: answers saved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswersResponse'
        '400':
          description: invalid answers provided, unable to calculate or unable to save
      tags:
        - Public
  /share:
    post:
      summary: send email with results
      description: |
        Email user with results, also updates user session with any answers provided and reculating usage.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShareRequest'
      responses:
        '200':
          description: email sent to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswersResponse'
        '400':
          description: invalid answers provided, invalid session, invlaid email, unable to calculate or unable to save
      tags:
        - Public
components:
  schemas:
    UnitValue:
      type: string
      enum:
        - kl
        - kilolitre
        - kilolitre
        - l
        - litre
        - litres
    PeriodValue:
      type: string
      enum:
        - hour
        - hours
        - hourly
        - day
        - days
        - daily
        - week
        - weeks
        - weekly
        - month
        - months
        - monthly
        - quarter
        - quarter
        - quarterly
        - year
        - yearly
        - annual
        - annually
    CategoryItem:
      type: object
      properties:
        name:
          type: string
          example: "Household"
        questions:
          type: array
          items:
            $ref: '#/components/schemas/QuestionItem'
    QuestionItem:
      type: object
      properties:
        id:
          type: integer
          nullable: false
          example: 3
        question:
          type: string
          nullable: false
          example: "What is the average shower time in your household?"
        tooltip_heading:
          type: string
          nullable: true
          example: null
        tooptip_body:
          type: string
          nullable: true
          example: "The average time each member of your household spends in the shower."
        statement:
          type: string
          nullable: false
          example: "Average shower time"
        tip_heading:
          type: string
          nullable: true
          example: null
        tip_body:
          type: string
          nullable: true
          example: "Did you know that for every 1 minute you reduce your shower by, you could save 1 bucket of water? Aim for 4 minutes or the length of your favourite song!"
        tip_link:
          type: string
          nullable: true
          example: "https://www.hunterwater.com.au/Save-Water/In-the-Home/4-Minute-showers.aspx"
        positive_feedback_minimum:
          type: string
          nullable: true
          example: null
        positive_feedback_maximum:
          type: string
          nullable: true
          example: "4.0"
        positive_feedback:
          type: string
          nullable: true
          example: "Great work! You can save more by placing a bucket in the shower while you wait for the water to heat up. That way, you can put this extra water to good use around the house, such as watering your garden!"
        positive_feedback_link:
          type: string
          nullable: true
          example: "https://www.hunterwater.com.au/Save-Water/In-the-Home/4-Minute-showers.aspx"
        negative_feedback:
          type: string
          nullable: true
          example: "Did you know that if we all shortened our shower by only 1 minute, we could save our region 4 million litres of water in a single day? Try aiming for the length of your favourite song next time you're in the shower!"
        negative_feedback_link:
          type: string
          nullable: true
          example: "https://www.hunterwater.com.au/Save-Water/In-the-Home/4-Minute-showers.aspx"
        field_type:
          type: string
          nullable: true
          example: "numeric"
        field_options:
          $ref: '#/components/schemas/FieldOptionList'
        field_other:
          $ref: '#/components/schemas/FieldOther'
        field_conditions:
          $ref: '#/components/schemas/FieldConditions'
        field_maximum:
          type: string
          nullable: true
          example: "40.0"
    FieldOptionList:
      type: array
      nullable: true
      items:
        $ref: '#/components/schemas/FieldOption'
    FieldOption:
      type: object
      required:
        - label
        - value
      properties:
        img:
          type: object
          properties:
            src:
              type: string
              example: "toilet-flush-single.png"
            alt:
              type: string
              example: "Single flush toilets have one button"
        label:
          type: string
          example: "Single flush"
        value:
          type: integer
          example: 1
    FieldOther:
      type: object
      nullable: true
      properties:
        unit:
          type: string
          example: "minute"
        units:
          type: string
          example: "minutes"
        placeholder:
          type: string
          example: "Another duration? Enter in minutes"
      example:
        unit: "minute"
        units: "minutes"
        placeholder: "Another duration? Enter in minutes"
    FieldConditions:
      type: object
      additionalProperties:
        type: string
      nullable: true
      example:
        "13":
          - 183
          - 91
          - 26
          - 6
    QuestionsResponse:
      type: object
      properties:
        status:
          type: integer
          example: 200
        response:
          type: object
          properties:
            categories:
              type: array
              nullable: false
              items:
                $ref: '#/components/schemas/CategoryItem'
            ideal_usage:
              type: object
              nullable: false
              additionalProperties:
                type: integer
              example:
                "1": 55
                "2": 100
                "3": 190
                "4": 235
                "5": 280
                "6": 325
                "7": 370
                "8": 415
                "9": 460
                "10": 505
                "11": 550
                "12": 595
            share_key:
              type: string
              pattern: '^[a-z0-9]{40}$'
              nullable: true
              example: null
            usage:
              type: integer
              nullable: true
              example: 150
        time:
          type: number
      example:
        status: 200
        response:
          categories:
            - name: Household
              questions:
                - id: 1
                  question: "How many people live in your household?"
                  tooltip_heading: null
                  tooltip_body: null
                  statement: "The people who live in your home"
                  tip_heading: "Change a little, save a lot!"
                  tip_body: "It's the little things we do in our homes and gardens that can make a big difference.\r\n\r\nLet's love our water together!"
                  tip_link: "https://www.hunterwater.com.au/Save-Water/Love-Water.aspx"
                  positive_feedback_minimum: null
                  positive_feedback_maximum: null
                  positive_feedback: "Now more than ever, we need to Love Water. It's the little things we do in our homes and gardens that can make a big difference."
                  positive_feedback_link: "https://www.hunterwater.com.au/"
                  negative_feedback: "Now more than ever, we need to Love Water. It's the little things we do in our homes and gardens that can make a big difference."
                  negative_feedback_link: "https://www.hunterwater.com.au/"
                  field_type: "numeric"
                  field_options:
                      - label: 1
                        value: 1
                      - label: 2
                        value: 2
                      - label: 3
                        value: 3
                      - label: 4
                        value: 4
                      - label: 5
                        value: 5
                  field_other:
                      unit: "person"
                      units: "people"
                      placeholder: "More people? Enter another number"
                  field_conditions: null
                  field_maximum: "12.0"
            - name: Bathroom
              questions:
                - id: 3
                  question: "What is the average shower time in your household?"
                  tooltip_heading: null
                  tooltip_body: "The average time each member of your household spends in the shower."
                  statement: "Average shower time"
                  tip_heading: null
                  tip_body": "Did you know that for every 1 minute you reduce your shower by, you could save 1 bucket of water? Aim for 4 minutes or the length of your favourite song!"
                  tip_link: "https://www.hunterwater.com.au/Save-Water/In-the-Home/4-Minute-showers.aspx"
                  positive_feedback_minimum: null
                  positive_feedback_maximum: "4.0"
                  positive_feedback: "Great work! You can save more by placing a bucket in the shower while you wait for the water to heat up. That way, you can put this extra water to good use around the house, such as watering your garden!"
                  positive_feedback_link: "https://www.hunterwater.com.au/Save-Water/In-the-Home/4-Minute-showers.aspx"
                  negative_feedback: "Did you know that if we all shortened our shower by only 1 minute, we could save our region 4 million litres of water in a single day? Try aiming for the length of your favourite song next time you're in the shower!"
                  negative_feedback_link: "https://www.hunterwater.com.au/Save-Water/In-the-Home/4-Minute-showers.aspx"
                  field_type: "numeric"
                  field_options:
                    - label: "2 mins"
                      value: 2
                    - label: "4 mins"
                      value: 4
                    - label: "7 mins"
                      value: 7
                    - label: "10 mins"
                      value: 10
                    - label: "15 mins"
                      value: 15
                    - label: "20 mins"
                      value: 20
                    - label: "30 mins"
                      value: 30
                  field_other:
                    unit: "minute"
                    units: "minutes"
                    placeholder: "Longer showers? Enter another number"
                  field_conditions: null
                  field_maximum: "40.0"
                - id: 4
                  question: "Do you have a water saving shower head?"
                  tooltip_heading: null
                  tooltip_body: null
                  statement: "Water saving shower head"
                  tip_heading: null
                  tip_body: "A water saving shower heads uses less than 9 litres of water per minute, compared to a old-style shower head which could use up to 15-20 litres per minute!"
                  tip_link: "https://www.hunterwater.com.au/Save-Water/In-the-Home/Bathroom.aspx"
                  positive_feedback_minimum: "1.0"
                  positive_feedback_maximum: null
                  positive_feedback: "Great work! Water saving shower heads use less than 9 litres of water per minute.  Remember to aim for 4 minutes or the length of your favourite song."
                  positive_feedback_link: "https://www.hunterwater.com.au/Save-Water/In-the-Home/4-Minute-showers.aspx"
                  negative_feedback: "Old-style shower heads can use up to 15-20 litres per minute, whereas upgrading to a three-star WELS rated shower head would reduce this to no more than 9 litres a minute. That's 4 buckets less water used in your 4 minute shower!"
                  negative_feedback_link: "https://www.hunterwater.com.au/Save-Water/In-the-Home/Bathroom.aspx"
                  field_type: "single"
                  field_options:
                    - label: "Yes"
                      value: 1
                    - label: "No"
                      value: 0
                  field_other: null
                  field_conditions: null
                  field_maximum: null
          ideal_usage:
            "1": 55
            "2": 100
            "3": 190
            "4": 235
            "5": 280
            "6": 325
            "7": 370
            "8": 415
            "9": 460
            "10": 505
            "11": 550
            "12": 595
          share_key: null
          usage: null
        time: 0.016993045806884766
    AnswersRequest:
      type: object
      properties:
        answers:
          $ref: '#/components/schemas/AnswersList'
    AnswersList:
      type: object
      additionalProperties:
        type: integer
      example:
        "1": 3
        "2": 2
        "3": 4
        "4": 1
        "5": 2
        "6": 2
        "7": 1
        "8": 3
        "9": 2
        "10": 3
        "11": 5
        "12": 26
        "13": 183
        "14": 10
        "15": 0
        "19": 0
        "20": 2
        "21": 10
    AnswersResponse:
      type: object
      properties:
        status:
          type: integer
          example: 200
        response:
          type: object
          properties:
            categories:
              type: array
              nullable: false
              items:
                type: object
                properties:
                  name:
                    type: string
                    example: "Household"
                  usage:
                    type: integer
                    example: 0
              example:
                - name: "Household"
                  usage: 2
                - name: "Bathroom"
                  usage: 130
                - name: "Kitchen"
                  usage: 12
                - name: "Laundry"
                  usage: 9
                - name: "Outside"
                  usage: 42
            ideal_usage:
              type: object
              nullable: false
              additionalProperties:
                type: integer
              example:
                "1": 55
                "2": 100
                "3": 190
                "4": 235
                "5": 280
                "6": 325
                "7": 370
                "8": 415
                "9": 460
                "10": 505
                "11": 550
                "12": 595
            share_key:
              type: string
              pattern: '^[a-z0-9]{40}$'
              nullable: true
              example: "9fde9815a55a57a69abb71a0bcc1324084ea6eec"
            usage:
              type: integer
              nullable: true
              example: 195
        time:
          type: number
          example: 0.11014008522033691
    ShareRequest:
      type: object
      properties:
        answers:
          $ref: '#/components/schemas/AnswersList'
        email:
          type: string
          nullable: false
          example: "hello@tom.id.au"
        postcode:
          type: string
          nullable: true
          example: "2291"
        name:
          type: string
          nullable: true
          example: null
      
tags:
  - name: Public
