openapi: 3.0.0
servers: []
info:
  description: API Target para callback Remessas Cash-To-Account ou Account-To-Account
  version: "1.0.4"
  title: API Callback Target
  contact:
    email: sistemas.ti@btcorretora.com.br
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /notificarRemessa:
    post:
      summary: notifica o andamento de uma cotação ou remessa, através da cotaçãoId
      operationId: notificarRemessa
      responses:
        '200':
          description: ok
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemNotificacao'
        description: Cotação a ser notificadca
components:
  schemas:
    ItemNotificacao:
      type: object
      required:
        - idCotacao
        - situacao
      properties:
        idCotacao:
          type: string
          format: guid
        situacao:
          type: number
          format: int32
          enum:
            - -1: Cotação não encontrada
            - 0: Obtendo valores para cotação
            - 1: Cotação aguardando aceite
            - 2: Cotação aceita, pagamento em andamento
            - 3: Cotação travada, pagamento em andamento
            - 4: Cotação negociada, pagamento em andamento
            - 10: Cotação finalizada, pagamento realizado com sucesso
            - 20: Cotação cancelada pelo usuário
            - 101: Falha no pagamento, incapaz de realizar
            - 101: Falha no pagamento, contraparte sem resposta
            - 103: Falha no pagamento, rejeitado
