openapi: 3.0.0

servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/greenfrogs/MSHealth2_Models/1.0.0
  - description: Swagger Virtual Server
    url: https://virtserver.swaggerhub.com/greenfrogs/MSHealth2/1.0.5
  - description: Server
    url: http://mshealth2.uksouth.cloudapp.azure.com:5010

info:
  description: "MSHealth2 API for COMP0016. All date-time fields are in GMT."
  version: "1.0.2"
  title: MSHealth2 Model API
  license:
    name: Copyright Retained
    url: 'https://www.gov.uk/guidance/ownership-of-copyright-works'

paths:
  /get_model:
    get:
      summary: "specific model information"
      description: |
        A json responses corresponding to a model after a particular time, automatically combines data from historical and prediction tables.
      parameters: 
        - in: query
          name: model
          description: "The model id to return"
          example: 47
          required: true
          schema:
            type: integer
        - in: query
          name: datetime
          description: "The prediction time requests from the model"
          example: "2019-01-01 00:00:00"
          required: true
          schema:
            type: string
            format: date-time
        - in: query
          name: limit
          description: "The number of time periods to request"
          example: 12
          required: true
          schema:
            type: integer
        - in: query
          name: frame
          description: "The time frame to take the prediction from"
          example: "2019-01-01 00:00:00"
          required: false
          schema:
            type: string
            format: date-time
        
      responses:
        '200':
          description: "Statistics matching critiera"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    time:
                      type: string
                      format: date-time
                      example: "Tue, 01 Jan 2019 00:00:00 GMT"
                    value:
                      type: integer
                      example: 1
      
        '400':
           $ref: '#/components/responses/Invalid'
        '401':
          $ref: '#/components/responses/Unauthorized'
          
  /get_model_insert:
    get:
      summary: "request specific model information"
      description: |
        A json responses corresponding to a model after a particular time, automatically combines data from historical and prediction tables. It also requests the information if it does not yet exist. It may not return the requests data immediately however on subsequent requests (and once it has been calculated) it will be returned.
      parameters: 
        - in: query
          name: model
          description: "The model id to return"
          example: 47
          required: true
          schema:
            type: integer
        - in: query
          name: datetime
          description: "The prediction time requests from the model"
          example: "2019-01-01 00:00:00"
          required: true
          schema:
            type: string
            format: date-time
        - in: query
          name: limit
          description: "The number of time periods to request"
          example: 12
          required: true
          schema:
            type: integer
        - in: query
          name: frame
          description: "The time frame to take the prediction from"
          example: "2019-01-01 00:00:00"
          required: false
          schema:
            type: string
            format: date-time
        
      responses:
        '200':
          description: "Statistics matching critiera"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    time:
                      type: string
                      format: date-time
                      example: "Tue, 01 Jan 2019 00:00:00 GMT"
                    value:
                      type: integer
                      example: 1
      
        '400':
           $ref: '#/components/responses/Invalid'
        '401':
          $ref: '#/components/responses/Unauthorized'
          
  /get_latest_model:
    get:
      summary: "request newest model information"
      description: |
        A json responses corresponding to the newest model after a particular time, automatically combines data from historical and prediction tables.
      parameters: 
        - in: query
          name: model
          description: "The model name"
          example: "BusynessHourly"
          required: true
          schema:
            type: string
        - in: query
          name: datetime
          description: "The prediction time requests from the model"
          example: "2019-01-01 00:00:00"
          required: true
          schema:
            type: string
            format: date-time
        - in: query
          name: limit
          description: "The number of time periods to request"
          example: 12
          required: true
          schema:
            type: integer
        - in: query
          name: frame
          description: "The time frame to take the prediction from"
          example: "2019-01-01 00:00:00"
          required: false
          schema:
            type: string
            format: date-time
        
      responses:
        '200':
          description: "Statistics matching critiera"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    time:
                      type: string
                      format: date-time
                      example: "Tue, 01 Jan 2019 00:00:00 GMT"
                    value:
                      type: integer
                      example: 1
      
        '400':
           $ref: '#/components/responses/Invalid'
        '401':
          $ref: '#/components/responses/Unauthorized'
  
  /get_latest_model_insert:
    get:
      summary: "request newest model information"
      description: |
        A json responses corresponding to the newest model after a particular time, automatically combines data from historical and prediction tables. It also requests the information if it does not yet exist. It may not return the requests data immediately however on subsequent requests (and once it has been calculated) it will be returned.
      parameters: 
        - in: query
          name: model
          description: "The model name"
          example: "BusynessHourly"
          required: true
          schema:
            type: string
        - in: query
          name: datetime
          description: "The prediction time requests from the model"
          example: "2019-01-01 00:00:00"
          required: true
          schema:
            type: string
            format: date-time
        - in: query
          name: limit
          description: "The number of time periods to request"
          example: 12
          required: true
          schema:
            type: integer
        - in: query
          name: frame
          description: "The time frame to take the prediction from"
          example: "2019-01-01 00:00:00"
          required: false
          schema:
            type: string
            format: date-time
        
      responses:
        '200':
          description: "Statistics matching critiera"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    time:
                      type: string
                      format: date-time
                      example: "Tue, 01 Jan 2019 00:00:00 GMT"
                    value:
                      type: integer
                      example: 1
      
        '400':
           $ref: '#/components/responses/Invalid'
        '401':
          $ref: '#/components/responses/Unauthorized'
  
  /get_available_model:
    get:
      summary: "request newest model information"
      description: |
        A json responses corresponding to any avaliable model (the most recent version takes priority) after a particular time, automatically combines data from historical and prediction tables.
      parameters: 
        - in: query
          name: model
          description: "The model name"
          example: "BusynessHourly"
          required: true
          schema:
            type: string
        - in: query
          name: datetime
          description: "The prediction time requests from the model"
          example: "2019-01-01 00:00:00"
          required: true
          schema:
            type: string
            format: date-time
        - in: query
          name: limit
          description: "The number of time periods to request"
          example: 12
          required: true
          schema:
            type: integer
        - in: query
          name: frame
          description: "The time frame to take the prediction from"
          example: "2019-01-01 00:00:00"
          required: false
          schema:
            type: string
            format: date-time
        
      responses:
        '200':
          description: "Statistics matching critiera"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    time:
                      type: string
                      format: date-time
                      example: "Tue, 01 Jan 2019 00:00:00 GMT"
                    value:
                      type: integer
                      example: 1
      
        '400':
           $ref: '#/components/responses/Invalid'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /current_time:
    get:
      summary: server time
      description: |
        The current time on the server, useful for interface mocking
      responses:
        '200':
          description: "current_time"
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_time:
                    type: string
                    format: date-time
                example: 
                  - datetime: "Fri, 01 Nov 2019 00:00:00 GMT"
        '400':
           $ref: '#/components/responses/Invalid'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  securitySchemes:
    apiKey:
      type: http
      scheme: bearer
      bearerFormat: jwt
  responses:
    Unauthorized:
      description: "Incorrect or no bearer token provided"
    Invalid:
      description: "Invalid request"
security: 
  - apiKey: []
