openapi: 3.0.0
info:
  description: Documentação do WebService de gerenciamento do Push SCI
  version: "1.0.0-oas3"
  title: Push SCI - WebService
  license:
    name: SCI
    url: 'https://sci.com.br/'
tags:
  - name: Push SCI - NodeJS
    description: Everything about your Pets
paths:
  /push/setClienteAtualizado:
    post:
      tags:
        - Push SCI - NodeJS
      summary: Push atualizado
      description: EndPoint destinado para informar quando o Push foi atualizado
      operationId: setClienteAtualizado
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sucesso'
        '500':
          description: Erro interno no servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente:
                  type: integer
                  example: 85901
                  description: Código do cliente
                numeroHD:
                  type: string
                  example: '1234554321'
                  description: Identificação unica do HD aonde o sistema está instalado
                versao:
                  type: string
                  example: 1.19.12.0
                  description: Versão para qual o sistema foi atualizado
  /push/setClienteAtivo:
    post:
      tags:
        - Push SCI - NodeJS
      summary: Push ativo
      description: >-
        EndPoint destinado para informar que o Push está ativo, chamar este
        endpoint de 12 em 12 horas ou uma vez por dia
      operationId: setClienteAtivo
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sucesso'
        '500':
          description: Erro interno no servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente:
                  type: integer
                  example: 85901
                  description: Código do cliente
                numeroHD:
                  type: string
                  example: '1234554321'
                  description: Identificação unica do HD aonde o sistema está instalado
                ult_processo:
                  type: string
                  example: '2019-11-10 09:00:00'
                  description: >-
                    Ultimo processo executado (Busca de notas, Download de
                    notas...)
                ult_processo_detalhe:
                  type: string
                  example: 'Busca de NFC-e'
                  description: >-
                    Descrição do ultimo processo executado (Busca de notas, Download de
                    notas...)
  /push/setClienteTotal:
    post:
      tags:
        - Push SCI - NodeJS
      summary: Push totalizado
      description: EndPoint destinado para envio das informações mensais do cliente.
      operationId: setClienteTotal
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sucesso'
        '500':
          description: Erro interno no servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente:
                  type: integer
                  example: 85901
                  description: Código do cliente
                numeroHD:
                  type: string
                  example: '1234554321'
                  description: Identificação unica do HD aonde o sistema está instalado
                referencia:
                  type: string
                  example: '201902'
                  description: Mês de referencia
                empresas_cadastradas:
                  type: integer
                  example: 10
                  description: Total de empresas cadastradas no Push
                empresas_integranet:
                  type: integer
                  example: 5
                  description: Total de empresas com Integra NET
                funcionario_total:
                  type: integer
                  example: 50
                  description: Total de funcionários exportados pelo Visual Practice
                funcionario_qualificados:
                  type: integer
                  example: 45
                  description: Total de funcionários qualificados
                nfe_total:
                  type: integer
                  example: 1500
                  description: Total de NF-e
                nfe_download:
                  type: integer
                  example: 1400
                  description: Total de NF-e que foram baixadas
                nfe_integrada:
                  type: integer
                  example: 1300
                  description: Total de NF-e que foram integradas
                nfce_total:
                  type: integer
                  example: 1200
                  description: Total de NFC-e
                nfce_download:
                  type: integer
                  example: 1100
                  description: Total de NFC-e que foram baixadas
                nfce_integrada:
                  type: integer
                  example: 1000
                  description: Total de NFC-e que foram integradas
                cte_total:
                  type: integer
                  example: 900
                  description: Total de CT-e
                cte_download:
                  type: integer
                  example: 800
                  description: Total de CT-e que foram baixadas
                cte_integrada:
                  type: integer
                  example: 700
                  description: Total de CT-e que foram integradas
                cfe_total:
                  type: integer
                  example: 600
                  description: Total de CF-e
                cfe_download:
                  type: integer
                  example: 500
                  description: Total de CF-e que foram baixadas
                cfe_integrada:
                  type: integer
                  example: 400
                  description: Total de CF-e que foram integradas
                nfse_total:
                  type: integer
                  example: 300
                  description: Total de NFS-e
                nfse_download:
                  type: integer
                  example: 200
                  description: Total de NFS-e que foram baixadas
                nfse_integrada:
                  type: integer
                  example: 100
                  description: Total de NFS-e que foram integradas
components:
  schemas:
    error:
      type: object
      properties:
        erro:
          type: string
          example: Erro no processamento
        errolog:
          type: object
          description: Aqui vira o erro detalhado.
    sucesso:
      type: object
      properties:
        Result:
          type: string
          example: ok
