openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/anton-a-baranov/PCDS/1.0.0
  - description: Pegas Client Data Service. Сервис для работы с клиентскими данными АИС Пегас
    url: https://localhost:8080/pcds/rest
info:
  description: API для проекта PCDS
  version: "1.0.0"
  title: Pegas Client Data Service
  contact:
    email: abaranov@lasptech.ru
  license:
    name: Lasp Technologies
    url: 'http://lasptech.ru'
tags:
  - name: webApiUsers
    description: Пользователи с авторизацией с помощью ключа API
paths:
  /person/natural/info_full/v1:
    get:
      tags:
        - webApiUsers
      summary: Получение полной информации о ФЛ
      operationId: naturalInfoFull
      description: |
        Поиск полной информации по ФЛ (ИД ФЛ, СНИЛС, ФИО, адреса, паспортные данные) по строке поиска
      parameters:
        - in: header
          name: X-CoreWeb-Auth-Key
          description: Ключ доступа API
          required: true
          schema:
            type: string
            format: uuid
        - in: query
          name: look_date
          description: Дата, на которую производится поиск данных
          required: false
          schema:
            type: string
            default: current_date
        - in: query
          name: insurance_number
          description: СНИЛС
          required: false
          schema:
            type: string
        - in: query
          name: id_person
          description: ИД ФЛ в АИС Пегас
          required: false
          schema:
            type: integer
        - in: query
          name: fullname
          description: ФИО
          required: false
          schema:
            type: string
        - in: query
          name: lastname
          description: Фамилия
          required: false
          schema:
            type: string
        - in: query
          name: firstname
          description: Имя
          required: false
          schema:
            type: string
        - in: query
          name: certificate_number
          description: Номер ДУЛ
          required: false
          schema:
            type: string
        - in: query
          name: certificate_series
          description: Серия ДУЛ
          required: false
          schema:
            type: string
        - in: query
          name: birth_date
          description: Дата рождения
          required: false
          schema:
            type: string
        - in: query
          name: limit
          description: Максимальное количество возвращаемых строк
          schema:
            type: integer
            format: int32
            minimum: 1
            default: 20
      responses:
        '200':
          description: Результаты поиска ФЛ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FullPersonInfo'
components:
  schemas:
    FullPersonInfo:
      type: object
      required:
        - idPerson
        - insuranceNumber
      properties:
        idPerson:
          type: string
          format: integer
          example: 666
        insuranceNumber:
          type: string
          example: 000-618-830 02
        lastname:
          type: string
          example: 'РЕПИНА'
        firstname:
          type: string
          example: 'ЯРОСЛАВА'
        middlename:
          type: string
          example: 'АНАТОЛЬЕВНА'
        birthDate:
          type: string
          format: date
          example: '1976-11-09'
        sex:
          type: string
          format: date
          enum: ['F', 'M']
          example: 'F'
        inn:
          type: string
          example: '561410000209'
        fundSelfnumber:
          type: string
          example: '130'
        raddress:
          type: string
          example: '602151, ВЛАДИМИРСКАЯ ОБЛ, СУДОГОДСКИЙ Р-Н, ТЮРМЕРОВКА П, МУРОМСКАЯ УЛ, 15'
        laddress:
          type: string
          example: '602151, ВЛАДИМИРСКАЯ ОБЛ, СУДОГОДСКИЙ Р-Н, ТЮРМЕРОВКА П, МУРОМСКАЯ УЛ, 15'
        idCertificate:
          type: string
          format: integer
          example: 14
        certificateSeries:
          type: string
          example: '1236'
        certificateNumber:
          type: string
          example: '123647'
        certificateType:
          type: string
          example: 'ПАСПОРТ ГРАЖДАНИНА РФ'
        certificateIssuer:
          type: string
          example: 'ОТДЕЛОМ ВНУТРЕННИХ ДЕЛ ЛЕНИНГРАДСКОГО РАЙОНА ГОРОДА КАЛИНИНГРАДА'
        certificateDate:
          type: string
          format: date
          example: '1976-11-09'
        certificateIssuerCode:
          type: string
          example: '033-072'
        citizenship:
          type: string
          example: 'РОССИЯ'
