openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/VictorFA/Ubeam_clientes_2019/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/VictorFA/ubeam_2019/1.0.0
  - description: API Ubeam - Clientes
    url: https://virtserver.swaggerhub.com/VictorFA/ubeam_clientes_2019/1.0.0
info:
  description: API para operações de clientes Ubeam
  version: "1.0.0"
  title: Clientes Ubeam
  contact:
    email: agostinho.victorf@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: clientes
    description: Operações relacionadas a clientes
  
paths:
  /clientes:
    get:
      tags:
        - clientes
      summary: buscar clientes na base
      operationId: searchCustomer
      description: Efetua a busca de clientes
      parameters:
        - in: query
          name: searchString
          description: definir um
          required: false
          schema:
            type: string
        - in: query
          name: skip
          description: número de registros para ignorar paginação
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: limit
          description: máximo de registro à retornar
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: Busca realizada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BaseClientes'
        '400':
          description: Parâmetro Inválio
    post:
      tags:
        - clientes
      summary: adicionar novo cliente
      operationId: addCustomer
      description: Adiciona novos clientes na base
      responses:
        '201':
          description: Cliente criado com sucesso
        '400':
          description: Dados inválidos
        '409':
          description: Já existe cliente
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseClientes'
        description: Incluir Clientes
    delete:
      tags:
        - clientes
      summary: Deletar cliente
      operationId: deleteCustomer
      description: Deleta clientes da base
      responses:
        '201':
          description: Cliente deletado com sucesso
        '400':
          description: Dados inválidos
        '409':
          description: Não é possível deletar
    put:
      tags:
        - clientes
      summary: Atualizar cliente
      operationId: refreshCustomer
      description: Atualiza clientes na base
      responses:
        '201':
          description: Cliente atualizado com sucesso
        '400':
          description: Dados inválidos
        '409':
          description: Não é possível atualizar
components:
  schemas:
    BaseClientes:
      type: object
      required:
        - id
        - nome
        - endereço
        - CPF/CNPJ
        - telefone
      properties:
        id:
          type: string
          format: uuid
          example: 001-002-003
        nome:
          type: string
          example: João da Silva
        endereço:
          type: string
          format: text
          example: Rua São Paulo, 331, São Paulo - SP
        CPF/CNPJ:
          type: string
          format: uuid
          example: 382.245.748-57
        telefone:
          type: string
          format: uuid
          example: (11) 98254-3719
