openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Api para Acoes Sincronas e Assincronas'
  description: ''
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/BTCorretora/Acoes/1.0.0
paths:
  /iniciar:
    post:
      summary: Api para iniciar ação assíncrona
      operationId: iniciar
      description: Dados do executor e ação de destino
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametrosAcaoAssincrona'
      responses:
        '200':
          description: resposta com identificador
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultadoAcaoGuid'
  /executar:
    post:
      summary: Api para executar ação síncrona
      operationId: executar
      description: Dados do executor e ação de destino
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametrosAcaoSincrona'
      responses:
        '200':
          description: resposta com identificador
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultadoAcaoInteger'
components:
  schemas:
    Resultado:
      required:
        - sucesso
      properties:
        sucesso:
          type: boolean
        codigoErro:
          type: integer
          format: int32
          nullable: true
        mensagem:
          type: string
          nullable: true
    ResultadoAcaoInteger:
      allOf:
        - $ref: '#/components/schemas/Resultado'
        - type: object
          properties:
            dados:
              type: integer
              nullable: true
    ResultadoAcaoGuid:
      allOf:
        - $ref: '#/components/schemas/Resultado'
        - type: object
          properties:
            dados:
              type: string
              format: guid
              nullable: true
    ParametrosAcaoSincrona:
      required:
        - acaoId
      properties:
        acaoId:
          type: integer
          format: int32
        sessao:
          type: string
          nullable: true
        dados:
          type: string
          format: json comprimido e base64
          nullable: true
    ParametrosAcaoAssincrona:
      required:
        - tipo
        - referencia
      properties:
        tipo:
          type: integer
          format: int32
        chave:
          type: integer
          format: int32
          nullable: true
        dados:
          type: string
          format: json comprimido e base64
          nullable: true
        sessao:
          type: string
          nullable: true
        referencia:
          type: string
          format: guid
        usuarioId:
          type: integer
          format: int32
          nullable: true
