openapi: 3.0.0
servers:
# Added by API Auto Mocking Plugin
  - description: Reveal API
    url: https://ds-cloud.styria.hr/reveal/api/test/v1
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Styria.AI/Reveal/1.0.0
info:
  description: The API exposes methods for inferring attributes of an image.
  version: "1.0.0"
  title: Reveal
  contact:
    email: info@styria.ai
security:
  - ApiKeyAuth: []
paths:
  '/models/{model_name}/actions/reveal':
    post:
      description: >-
        Infers the bounding box, class and computes the object selling price range.
      parameters:
        - in: path
          name: model_name
          required: true
          description: Name of the model to use. Available models are `njuskalo`.
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  description: Binary representation of the image. The image must be resized
                    to 248px at its largest side with a compression ratio of 80%.
                  type: string
                  format: binary
      responses:
        '200':
          description: Bounding box, object class and selling price range.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      bbox:
                        $ref: '#/components/schemas/BoundingBox'
                      class:
                        $ref: '#/components/schemas/Class'
                      price_range:
                        $ref: '#/components/schemas/PriceRange'
              examples:
                response:
                  value: |-
                    {
                      "data": {
                        "bbox": {
                          "top_left": [
                            0.067678968111674,
                            0.0813559889793396
                          ],
                          "bottom_right": [
                            0.8308719396591187,
                            0.921967089176178
                          ]
                        },
                        "class": {
                          "id": 9827,
                          "names": [
                            "njuskalo",
                            "Od glave do pete",
                            "Obuća"
                          ]
                        },
                        "price_range": [
                          127.5,
                          337.5
                        ]
                      }
                    }
        '400':
          description: Invalid image data, such as missing, truncated or wrongly resized image.
        '401':
          description: Invalid verification credentials specified.
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    BoundingBox:
      type: object
      properties:
        top_left:
          type: array
          items:
            type: integer
            format: int32
        bottom_right:
          type: array
          items:
            type: integer
            format: int32
    Class:
      type: object
      properties:
        id:
          type: integer
          format: int32
        names:
          type: array
          items:
            type: string
    PriceRange:
      type: array
      items:
        type: number
        format: float32
