openapi: 3.0.0
info:
  description: 'Blume Logistics Dispatch Manager API.  Category: Blume Logistics'
  version: "1.0.0-oas3"
  title: Blume Logistics Dispatch Manager API
  contact:
    email: Billy.Buzzard@bnsflogistics.com
tags:
  - name: blume
    description: Dispatch Manager API
paths:
  /create:
    post:
      tags:
        - workorder
      description: Create the given work order
      summary: Create Work Order
      operationId: createWorkOrder
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutputResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkOrder'
        description: Input Work Order Request
        required: true
  /update:
    put:
      tags:
        - workorder
      description: Update the given work order
      summary: Update Work Order
      operationId: updateWorkOrder
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutputResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkOrder'
        description: Update Work Order Request
        required: true
  /cancel:
    post:
      tags:
        - workorder
      description: Cancel the given work order
      summary: Cancel Work Order
      operationId: cancelWorkOrder
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutputResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CancelWorkOrder'
        description: Cancel Work Order Request
        required: true
servers:
  - url: 'https://api-dev.blumeglobal.com/si/workorders/v1'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: apikey
  schemas:
    OutputResponse:
      type: object
      properties:
        status:
          type: string
        id:
          type: string
        message:
          type: string
      required:
        - status
        - id
        - message
    WorkOrder:
      type: object
      properties:
        workOrder:
          type: object
          properties:
            originatorCode:
              type: string
            receiverCode:
              type: string
            workOrderNumber:
              type: string
              maxLength: 50
            carrierCode:
              type: string
            category:
              type: string
            createdBy:
              type: string
            workOrderDate:
              type: string
            billOfLadingNumber:
              type: string
              maxLength: 50
            bookingNumber:
              type: string
              maxLength: 50
            respondByDate:
              type: string
              nullable: true
            exportCutoffDate:
              type: string
            vessel:
              type: string
              maxLength: 50
            portOfLoading:
              type: string
              maxLength: 50
            portOfDischarge:
              type: string
              maxLength: 50
            eta:
              type: string
            masterAirWayBillNumber:
              type: string
              maxLength: 50
            houseAirWayBillNumber:
              type: string
              maxLength: 50
            paymentMethodIndicator:
              type: string
            shipmentReferenceNumber:
              type: string
              maxLength: 50
            originatorOrderReference:
              type: string
              maxLength: 50
            originatorImportReferenceNumber:
              type: string
              maxLength: 50
            voyage:
              type: string
              maxLength: 50
            shipper:
              type: string
              maxLength: 50
            billTo:
              type: string
              maxLength: 250
            comments:
              type: string
            equipmentList:
              type: array
              items:
                type: object
                properties:
                  equipmentNumber:
                    type: string
                    maxLength: 50
                  equipmentTypeCode:
                    type: string
                    enum:
                      - 20BK
                      - 20CZ
                      - 20FB
                      - 20FR
                      - 20HC
                      - 20HR
                      - 20OT
                      - 20RF
                      - 20RFTR
                      - 20ST
                      - 20TC
                      - 20TR
                      - 40BK
                      - 40CZ
                      - 40FB
                      - 40FR
                      - 40HC
                      - 40HCOT
                      - 40HCRF
                      - 40HR
                      - 40OT
                      - 40PB
                      - 40RF
                      - 40RFTR
                      - 40ST
                      - 40TC
                      - 40TR
                      - 45CZ
                      - 45FB
                      - 45HC
                      - 45OT
                      - 45PB
                      - 45RFTR
                      - 45TR
                      - 48DD
                      - 48DM
                      - 48EMPU
                      - 48FB
                      - 48FR
                      - 48NACS
                      - 48PB
                      - 48TR
                      - 48TRRF
                      - 53AIR
                      - 53DM
                      - 53DV
                      - 53EMHU
                      - 53EMUU
                      - 53TR
                      - GENSET
                      - LCL
                      - SPEC
                      - 40TK
                      - 40RQ
                      - 20RG
                      - 20FBZ
                      - 20SL
                      - 20SF
                      - 20TX
                      - 40RG
                      - 45GN
                      - 40CB
                      - 45EX
                      - 40GN
                      - 40SF
                      - 40TX
                      - GCL
                      - GCM
                      - GPP
                      - GSM
                  pieceCount:
                    type: integer
                    format: int32
                    minimum: 0
                    maximum: 9999999
                  netWeight:
                    type: number
                    minimum: 0.01
                    maximum: 9999999.99
                  tareWeight:
                    type: number
                    minimum: 0.01
                    maximum: 9999999.99
                  grossWeight:
                    type: number
                    minimum: 0.01
                    maximum: 9999999.99
                  weightUOM:
                    type: number
                    minimum: 0.01
                    maximum: 9999999.99
                  freightDescription:
                    type: string
                    maxLength: 50
                  emptyReleaseNumber:
                    type: string
                    maxLength: 50
                  isHazmat:
                    type: string
                    enum:
                      - false
                      - true
                  isOverweight:
                    type: string
                    enum:
                      - false
                      - true
                  shipmentnumber:
                    type: string
                    maxLength: 50
                  chargeList:
                    type: array
                    items:
                      type: object
                      properties:
                        serviceCode:
                          type: string
                        amount:
                          type: number
                          minimum: 0.01
                          maximum: 9999999.99
                        currency:
                          type: number
                          minimum: 0.01
                          maximum: 100
                        fscPercent:
                          type: number
                        isBillable:
                          type: string
                          enum:
                            - 'yes'
                            - 'no'
                      required:
                        - serviceCode
                        - amount
                        - isBillable
                required:
                  - equipmentTypeCode
            stopList:
              type: array
              items:
                type: object
                properties:
                  stopType:
                    type: string
                  stopName:
                    type: string
                  stopNumber:
                    type: string
                  facility:
                    type: object
                    properties:
                      stopReferenceNumber:
                        type: string
                      facilityCode:
                        type: string
                      address1:
                        type: string
                      address2:
                        type: string
                      city:
                        type: string
                      state:
                        type: string
                      country:
                        type: string
                      postalCode:
                        type: string
                      timezone:
                        type: string
                      contactName:
                        type: string
                      contactPhone:
                        type: string
                      comments:
                        type: string
                  appointmentList:
                    type: array
                    items:
                      type: object
                      properties:
                        EquipmentID:
                          type: object
                          properties:
                            equipmentTypeCode:
                              type: string
                            shipmentnumber:
                              type: string
                        scheduledGateInStart:
                          type: string
                        scheduledGetInForm:
                          type: string
                        assignedToDriverId:
                          type: string
                        assignedToDriverName:
                          type: string
                        assignedToDriverMobilePhone:
                          type: string
              minItems: 2
              required:
                - stopType
                - stopName
                - stopNumber
          required:
            - originatorCode
            - receiverCode
            - workOrderNumber
            - carrierCode
            - workOrderDate
            - paymentMethod
            - equipmentList
    CancelWorkOrder:
      type: object
      properties:
        workOrderNumber:
          type: string
          maximum: 50
        originatorCode:
          type: string
        receiverCode:
          type: string
      required:
        - originatorCode
        - receiverCode
        - workOrderNumber
security:
  - ApiKeyAuth: []
