openapi: 3.0.0
servers:
  - description: FeaturesFirst AutoHub
    url: https://virtserver.swaggerhub.com/featuresfirstauto/AutoHub/1.0.0
info:
  version: "1.0.0"
  title: Welcome to the FeaturesFirst AutoHub!
  description: >-
    Here you will find RESTful endpoints for integrating your client to the FeaturesFirst Auto hub.
  termsOfService: https://featuresfirstauto.com/terms
  contact:
    name: Our Support
    email: support@featuresfirstauto.com
    url: https://featuresfirstauto.com
security:
  - application:
      - read
      - write
paths:
  /users/{id}:
    get:
      summary: Gets a user by ID.
      description: >
        A detailed description of the operation.
        Use markdown for rich text representation,
        such as **bold**, *italic*, and [links](https://swagger.io).
      operationId: getUserById
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      externalDocs:
        description: Learn more about user operations provided by this API.
        url: http://api.example.com/docs/user-operations
  /preferences:
    get:
      summary: Get user preferences
      operationId: getUserPreferencesByUserId
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Preferences'
    put:
      summary: Update user preferences
      operationId: putUserPreferencesByUserId
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Preferences'
  /vehicles/{id}:
    get:
      summary: Get a user vehicle 
      operationId: getUserVehicleById
      parameters:
        - name: id
          in: path
          description: User Vehicle ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserVehicle'
    put:
      summary: Update a user vehicle profile
      operationId: putUserVehicleById
      parameters:
        - name: id
          in: path
          description: User Vehicle ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserVehicle'
  /ping:
    get:
      summary: Server heartbeat operation
      security: []
      responses:
        '200':
          description: OK
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - id
        - name
    Preferences:
      type: array
      items:
        $ref: '#/components/schemas/Notification'
    UserPreference:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - id
        - name
    Notification:
      type: object
      properties:
        email:
          type: boolean
          readOnly: true
        text:
          type: boolean
        phone:
          type: boolean
        push:
          type: boolean
    UserVehicle:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        makeId:
          type: integer
          format: int64
        modelId:
          type: integer
          format: int64
        year:
          type: integer
          format: int64
        postalCode:
          type: integer
          format: int64
        favoriteFeature:
          type: string
        encryptedVIN:
          type: string
      required:
        - userId
        - makeId
        - modelId
        - year
        - zipCode
        - favoriteFeature
  securitySchemes:
    application:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'http://featuresfirstauto.com/oauth/token'
          scopes:
            write: allows modifying resources
            read: allows reading resources
