openapi: 3.0.0
servers:
# CNE Single View API 1.1.0
  - url: https://dev-api.cmp.io/cne/singleview
    description: Test server
  - url: https://api.cmp.io/cne/singleview
    description: Production server
info:
  version: "1.1.0"
  title: CNE Single View API
  description: >
    This is the CNE Single View API
paths:
  /accounts/search:
    get:
      tags:
        - Accounts > Search
      summary: Account Search
      parameters:
        - name: singleViewId
          in: query
          description: Enter a Single View Id
          schema:
            type: string
            format: uuid
        - name: accountNumber
          in: query
          description: Enter an Account Number
          schema:
            type: string
        - name: customerNumber
          in: query
          description: Enter a Customer Number
          schema:
            type: string
        - name: ldcNumber
          in: query
          description: Enter a LDC Number
          schema:
            type: string
        - name: email
          in: query
          description: Enter an email address
          schema:
            type: string
            format: email
        - name: phone
          in: query
          description: Enter Phone Number
          schema:
            type: string
        - name: street1
          in: query
          description: Enter full street address
          schema:
            type: string
        - name: zip
          in: query
          description: Enter zip code
          schema:
            type: string
      responses:
        '200':
          description: An account object
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    singleViewId:
                      type: string
                      format: uuid
                      description: The Single View Id for the record.
                    accounts:
                      type: array
                      items:
                        type: object
                        properties:
                          accountNumber:
                            type: string
                            example: '283848544'
                            description: The account number for the record.
                          type:
                            type: string
                            example: 'power'
                            description: The type for record.
                          status:
                            type: string
                            example: 'active'
                            description: The status of the record.
                          customerNumber:
                            type: string
                            example: '27877383'
                            description: The customer number for the record.
                          ldcNumber:
                            type: string
                            example: '4515878822'
                            description: The LDC number for the record.
                          udc:
                            type: string
                            example: 'BGE'
                            description: The udc code for the record.
                          lastModifiedDate:
                            type: string
                            example: '2019-09-17T16:09:32Z'
                            description: When the record was last modified.
                          green:
                            type: boolean
                            description: If the record is green or not.
                          active:
                            type: boolean
                            example: false
                            description: if the account is active.
                          responseId:
                            type: string
                            example: '203939392'
                            description: The response Id the record.
                          crossSell:
                            type: object
                            properties:
                              gas:
                                type: boolean
                                example: true
                                description: If the record can be cross-sold gas.
                              power:
                                type: boolean
                                example: false
                                description: If the record can be cross-sold power.
                          contract:
                            type: object
                            properties:
                              start:
                                type: string
                                example: '2012-03-01'
                                description: Start date of the contract.
                              end:
                                type: string
                                example: '2015-03-30'
                                description: End date of the contract.
                          service:
                            type: object
                            properties:
                              start:
                                type: string
                                example: '2012-03-29'
                                description: Start date of service.
                              end:
                                type: string
                                example: '2015-03-30'
                                description: End date of service.
                          contact:
                            type: object
                            properties:
                              nameFirst:
                                type: string
                                example: 'Michael'
                                description: First name of record contact.
                              nameLast:
                                type: string
                                example: 'Scott'
                                description: Last name of record contact.
                              email:
                                type: string
                                format: email
                                description: Email address for record contact.
                              phone:
                                type: string
                                example: '3045553043'
                                description: Phone number for record contact.
                          addresses:
                            type: array
                            items:
                              type: object
                              properties:
                                type:
                                  type: string
                                  example: 'service'
                                  description: Type of address of the record.
                                street1:
                                  type: string
                                  example: '123 Main St.'
                                  description: Street Address 1 for the address of the record.
                                city:
                                  type: string
                                  example: 'Chesapeake Beach'
                                  description: City for the address of the record.
                                state:
                                  type: string
                                  example: 'MD'
                                  description:  State for the address of the record.
                                zip:
                                  type: string
                                  example: '20732'
                                  description: Zip code for the address of the record.
        '400':
          description: Problem with query parameter
        '403':
          $ref: "#/components/responses/ForbiddenError"
  /response/{id}:
    get:
      tags:
        - Response > Id
      summary: Response Id Detail
      parameters:
        - name: id
          in: path
          description: Response Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: An response object
          content:
            application/json:
              schema:
                type: object
                properties:
                  accountNumber:
                    type: string
                    example: '283848544'
                    description: The account number for the record.
                  active:
                    type: boolean
                    example: false
                    description: if the account is active.
                  responseId:
                    type: string
                    example: '203939392'
                    description: The response Id the record.
        '400':
          description: Error, duplicate record.
        '403':
          $ref: "#/components/responses/ForbiddenError"
components:
  responses:
    ForbiddenError:
      description: API key is missing or invalid
      headers:
        X-API-KEY:
          description: Cogensia provided API Key
          schema:
            type: string
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: x-api-key  # name of the header, query parameter or cookie
# 2) Apply the API key globally to all operations
security:
  - ApiKeyAuth: []     # use the same name as under securitySchemes
