openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'CREDENTIAL API'
  description: 'CREATING CREDENTIAL IN CREDENTIAL SERVICE WITH PROOF AND CLAIM ALONG WITH OTHER REQUIRED DETAILS'
  contact:
    name: Abhishek Kumar
    email: abhishek.kumar@kroger.com
servers: 
  - url: http://localhost:9090
    description: Localhost server for running the service as the code is not yet deployed
paths: 
  /credential:
    get:
      description: It will provide the slice of credentials requested with params
      parameters: 
        - name: id
          in: query
          description: the primary id of the credential
          schema:
            type: string
            maxLength: 30
      responses:
        200:
          description: SUCCESSFUL RESPONSE FOR CREDENTIALS
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: string
                      example: 1234-4332-33-323
                    claim:
                      type: string
                      example: abhishek.k@zopsmart.com
                      
                    
                
    post:
      description: It will create credential in the credential service with all params like cliam,proof,proofSalt,expiredAt,verifiedAt info.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                issuer:
                    type: string
                    maxLength: 100
                    example: urn:com:kroger:login
                audience:
                    type: string
                    maxLength: 100
                    example: urn:person:hanuman
                type:
                    type: string
                    maxLength: 50
                    example: urn:sec:basic
                subject:
                    type: string
                    maxLength: 100
                    example: urn:person:701efa94-aa30-4f37-94fb-958742b0ac42
                claim:
                    type: string
                    maxLength: 500
                    example: euid1234
                proof:
                    type: string
                    maxLength: 500
                    example: zopsmart
                    
      responses:
        200:
          description: SUCCESS RESPONSE for CREDENTIAL CREATION
          content:
            application/json:
              schema:
               type: object
               properties:
                id:
                    type: string
                    maxLength: 36
                    example: a2d2e916-1be2-11ea-9272-a683e7140e3d
                issuer:
                    type: string
                    maxLength: 100
                    example: urn:com:kroger:login
                audience:
                    type: string
                    maxLength: 100
                    example: urn:person:hanuman
                type:
                    type: string
                    maxLength: 50
                    example: urn:sec:basic
                subject:
                    type: string
                    maxLength: 100
                    example: urn:person:701efa94-aa30-4f37-94fb-958742b0ac42
                claim:
                    type: string
                    maxLength: 500
                    example: euid1234
                proof:
                    type: string
                    maxLength: 500
                    example: zopsmart
                issuedAt:
                    type: object
                    properties:
                      time:
                          type: string
                          example: 2019-12-11
                      timezone:
                          type: string
                          example: IST
