openapi: 3.0.0
info:
  title: TFC API
  description: ''
  contact: {}
  version: "2.2"
servers:
- url: https://stgapi.thefirstclub.com/v2
  variables: {}
- url: https://api.thefirstclub.com/v2
  variables: {}
paths:
  /voucher:
    post:
      tags:
      - Voucher
      summary: Create Voucher
      description: ''
      operationId: CreateVoucher
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateVoucherRequest'
            example:
              shop_id: 6
              account_id: A-002168
              prefix: TEST
              num_vouchers: 20
              points: 250
              content_type_id: 0
              content_id: 0
              voucher_type: 1
              user_id: 44
              start_time: "2020-02-10 00:00:00"
              points_start_time: "2020-02-10 00:00:00"
              exp_time: "2021-02-10 00:00:00"
              points_exp_time: "2021-02-10 00:00:00"
        required: true
        x-send-file-in-body: false
      responses:
        201:
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoucherResponse'
              example:
                shop_id: 6
                code: TEST5896189247
                points: 250
                start_time: "2020-02-10 00:00:00"
                points_start_time: "2020-02-10 00:00:00"
                exp_time: "2021-02-10 00:00:00"
                points_exp_time: "2021-02-10 00:00:00"
      deprecated: false
    
  /voucher/{code}:
    get:
      tags:
      - Voucher
      summary: List Vouchers
      description: ''
      operationId: ListVouchers
      parameters:
      - name: "code"
        in: path
        required: true
        style: simple
        schema:
          type: string
      responses:
        200:
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoucherResponse'
              example:
                shop_id: 6
                code: TEST56856758
                points: 250
                start_time: "2020-02-10 00:00:00"
                points_start_time: "2020-02-10 00:00:00"
                exp_time: "2021-02-10 00:00:00"
                points_exp_time: "2021-02-10 00:00:00"
      deprecated: false
    put:
      tags:
      - Voucher
      summary: Redeem Voucher
      description: ''
      operationId: RedeemVoucher
      parameters:
      - name: "code"
        in: path
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RedeemVoucherRequest'
            example:
              code: TEST4501526409503
              shop_id: 6
              end_user: a061a000003WaUhAAK
        required: true
        x-send-file-in-body: false
      responses:
        200:
          description: ''
          headers: {}
          content:
            text/plain:
              schema:
                type: object
      deprecated: false
    delete:
      tags:
      - Voucher
      summary: Invalidate Voucher
      description: ''
      operationId: InvalidateVoucher
      parameters:
      - name: "code"
        in: path
        required: true
        style: simple
        schema:
          type: string
      responses:
        200:
          description: ''
          headers: {}
          content:
            text/plain:
              schema:
                type: object
      deprecated: false
  /version:
    get:
      summary: Version
      description: ''
      operationId: Version
      parameters:
      - name: Content-Type
        in: header
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      responses:
        200:
          description: ''
          headers: {}
          content:
            text/plain:
              schema:
                type: object
      deprecated: false
  /test:
    get:
      summary: Test
      description: ''
      operationId: Test
      parameters:
      - name: Content-Type
        in: header
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      responses:
        200:
          description: ''
          headers: {}
          content:
            text/plain:
              schema:
                type: object
      deprecated: false
components:
  schemas:
    CreateVoucherRequest:
      title: CreateVoucherRequest
      required:
      - shop_id
      - account_id
      - prefix
      - num_vouchers
      - points
      - content_type_id
      - content_id
      - voucher_type
      - user_id
      - start_time
      - points_start_time
      - exp_time
      - points_exp_time
      type: object
      properties:
        shop_id:
          type: integer
          format: int32
        account_id:
          type: string
        prefix:
          type: string
        num_vouchers:
          type: integer
          format: int32
        points:
          type: integer
          format: int32
        content_type_id:
          type: integer
          format: int32
        content_id:
          type: integer
          format: int32
        voucher_type:
          type: integer
          format: int32
        user_id:
          type: integer
          format: int32
        start_time:
          type: string
        points_start_time:
          type: string
        exp_time:
          type: string
        points_exp_time:
          type: string
      example:
        shop_id: 6
        account_id: A-000000
        prefix: TEST
        num_vouchers: 20
        points: 250
        content_type_id: 0
        content_id: 0
        voucher_type: 1
        user_id: 99
        start_time: "2020-02-10 00:00:00"
        points_start_time: "2020-02-10 00:00:00"
        exp_time: "2021-02-10 00:00:00"
        points_exp_time: "2021-02-10 00:00:00"
    VoucherResponse:
      title: VoucherResponse
      required:
      - shop_id
      - points
      - code
      - start_time
      - points_start_time
      - exp_time
      - points_exp_time
      type: object
      properties:
        shop_id:
          type: integer
          format: int32
        points:
          type: integer
          format: int32
        code:
          type: string
        start_time:
          type: string
        points_start_time:
          type: string
        exp_time:
          type: string
        points_exp_time:
          type: string
      example:
        shop_id: 6
        points: 250
        code: TEST56785687678
        start_time: "2020-02-10 00:00:00"
        points_start_time: "2020-02-10 00:00:00"
        exp_time: "2021-02-10 00:00:00"
        points_exp_time: "2021-02-10 00:00:00"
    RedeemVoucherRequest:
      title: RedeemVoucherRequest
      required:
      - code
      - shop_id
      - end_user
      type: object
      properties:
        code:
          type: string
        shop_id:
          type: integer
          format: int32
        end_user:
          type: string
      example:
        code: TEST4501526409503
        shop_id: 6
        end_user: a061a000003WaUhAAK
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
- httpBearer: []
tags:
- name: Voucher
  description: ''
