openapi: "3.0.0"
info:
  version: 1.0.1
  title: DuoDiplomaGegevens
  contact:
    email: _dienstpostbus@minvws.nl
servers:
  - url: http://cibg-api-egw-dev.mso.mhsrijk.nl
  - url: http://cibg-api-egw-test.mst.mhsrijk.nl
  - url: http://cibg-api-egw-acc.frd.otassonet.local
  - url: http://cibg-api-egw-prod.frd.ssonet.nl
paths:
  /duo/dplrg/1/diplomagegevens/zorro/{bsn}:
    get:
      summary: Haal diploma's op voor persoon
      operationId: getZorroDiploma
      tags:
        - zorro
      parameters: 
        - $ref: '#/components/parameters/bsn'
      responses:
        '200':
          description: Een overzicht van de behaalde diploma's
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/diplomaBigregister"
        '400':
          description: Bsn voldoet niet aan de verwachte syntax
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CibgFault"
              example:
                fault:
                  code: 'Bad Request'
                  detail: 'Value 1234 does not match regular expression ^\d{9}$ for field bsn'
        '401':
          description: Geen JWT meegestuurd
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CibgFault"
              example:
                fault:
                  code: 'Unauthorized'
        '403':
          description: Geen toegang
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CibgFault"
              example:
                fault:
                  code: 'Foribdden'
        '500':
          description: Onverwachte fout
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CibgFault"
              example:
                fault:
                  code: 'Internal Server Error'
                  reason: 'Connection timeout'
  /duo/dplrg/1/diplomagegevens/vlr/{bsn}:
    get:
      summary: Haal diploma's op voor persoon
      operationId: getVlrDiploma
      tags:
        - vlr
      parameters: 
        - $ref: '#/components/parameters/bsn'
      responses:
        '200':
          description: Een overzicht van de behaalde diploma's
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/diplomaLerarenportfolio"
        '400':
          description: Bsn voldoet niet aan de verwachte syntax
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CibgFault"
              example:
                fault:
                  code: 'Bad Request'
                  detail: 'Value 1234 does not match regular expression ^\d{9}$ for field bsn'
        '401':
          description: Geen JWT meegestuurd
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CibgFault"
              example:
                fault:
                  code: 'Unauthorized'
        '403':
          description: Geen toegang
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CibgFault"
              example:
                fault:
                  code: 'Foribdden'
        '500':
          description: Onverwachte fout
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CibgFault"
              example:
                fault:
                  code: 'Internal Server Error'
                  reason: 'Connection timeout'
components:
  parameters:
    bsn:  
      name: bsn
      in: path
      description: Het bsn van een persoon.
      required: true
      example: 989103871
      schema:
        type: integer
  schemas:
    diplomaLerarenportfolio:
      type: object
      required:
        - diplomaLerarenportfolio
      properties:
        diplomaBigregister:
          type: array
          items:
            required:
              - type
              - opleiding
              - uitgegevenDoor
              - datum
              - niveau
              - opleidingcode
              - diplomaId
            properties:
              type:
                type: string
                example: 'Getuigschrift'
              opleiding:
                type: string
                example: 'HBO Bachelor Management Payroll Services 123456781'
              uitgegevenDoor:
                type: string
                example: 'Getuigschrift uitgegeven door Hogeschool Markus Verbeek Praehep te Utrecht'
              datum:
                type: string
                format: datetime
                example: '2018-01-19'
              onderdeel:
                type: string
                example: 'ECONOMIE'
              subonderdeel:
                type: string
                example: null
              opleidingcode:
                type: string
                example: '34132'
              niveau:
                type: string
                example: 'HBO Bachelor'
              diplomaId:
                type: number
                example: 123456781
    diplomaBigregister:
      type: object
      required:
        - diplomaBigregister
      properties:
        diplomaBigregister:
          type: array
          items:
            required:
              - opleidingNaam
              - onderwijsinstellingNaam
              - diplomaDatum
              - diplomaNiveau
              - diplomaId
              - onderwijsinstellingPlaats
            properties:
              opleidingNaam:
                type: string
                example: 'HBO Bachelor Management Payroll Services 123456781'
              onderwijsinstellingNaam:
                type: string
                example: 'Hogeschool Leiden'
              diplomaDatum:
                type: string
                format: date
                example: '2018-01-18'
              opleidingCode:
                type: string
                example: '34132'
              diplomaNiveau:
                type: string
                example: 'HBO Bachelor'
              diplomaId:
                type: number
                example: 123456781
              onderwijsinstellingPlaats:
                type: string
                example: 'Leiden'
    CibgFault:
      type: object
      properties:
        fault:
          type: object
          properties:
            code:
              type: string
              example: 'ErrorCode'
            reason:
              type: string
              example: 'Reden van fout'
            detail:
              type: string
              example: 'Extra informatie over fout'
  responses:
    badrequest: 
      description: bad request
      content:
        application/xml:
          schema:
            $ref: "#/components/schemas/CibgFault"
    notAuthorized:
      description: not authorized
      content:
        text/plain:
          schema:
           $ref: "#/components/schemas/CibgFault"
