openapi: 3.0.1
info:
  title: Chastia.IS.Lib.PluginRest.SLSPJira
  version: 'DEV'
  description: |
                ver 0.1 - first version wiht base structures (25.11.2019)
                
                ver 0.2 - updated version (9.12.2019)
servers:
  - url: https://localhost
  - url: https://helpdesk.engie-services.sk/hd-projekty-test 
paths:
  /api/HD/ExternalB/0/SLSPJira/Create:
    post:
      tags:
        - SLSP Jira
      summary: Creating job/ticket in Chastia
      operationId: postApiHDExternal0SLSPJiraCreate
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Chastia.IS.Lib.PluginRest.SLSPJira.Entities.CreateJobParams'
        required: true
      responses:
        '200':
          description: Object with SLSP Ticket ID and ExternalID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chastia.IS.Lib.PluginRest.SLSPJira.Entities.CreateJobResponse'
      security:
        - BasicAuth: [ ]
  /api/HD/ExternalB/0/SLSPJira/Update:
    post:
      tags:
        - SLSP Jira
      summary: Uprade job/ticket in Chastia
      operationId: postApiHDExternal0SLSPJiraUpdate
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Chastia.IS.Lib.PluginRest.SLSPJira.Entities.UpdateJobToChastiaParams'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chastia.IS.Lib.PluginRest.SLSPJira.Entities.UpdateJobResponse'
  /api/HD/ExternalB/0/SLSPJira/Acceptance:
    post:
      tags:
        - SLSP Jira
      summary: Uprade job/ticket in Chastia
      operationId: postApiHDExternal0SLSPJiraAcceptance
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Chastia.IS.Lib.PluginRest.SLSPJira.Entities.AcceptanceByReporterParams'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chastia.IS.Lib.PluginRest.SLSPJira.Entities.AcceptanceByReporterResponse'
components:
  schemas:
    Chastia.IS.Lib.PluginRest.SLSPJira.Entities.CreateJobParams:
      required:
        - Reporter
        - Contact
        - Locality
        - Summary
        - Description
        - Priority
        - RequestType
        - ActivityType
        - TicketID
      type: object
      properties:
        Reporter:
          type: string
          description: Name of reporter
        Contact:
          type: string
          description: Tel.number of reporter
        Locality:
          type: string
          description: Locality of reporter
        Summary:
          type: string
          description: Short description of the ticket
        Description:
          type: string
          description: Description of the ticket
        Priority:
          type: integer
          description: Priority
          format: int32
        RequestType:
          type: string
          description: Type of ticket
        ActivityType:
          type: string
          description: Type of Activity
        Attachments:
          type: array
          items:
            type: object
          description: Attachments
        TicketID:
          type: string
          description: Ticket number in SLSP application
    Chastia.IS.Lib.PluginRest.SLSPJira.Entities.CreateJobResponse:
      required:
        - TicketID
        - ExternalID
      type: object
      properties:
        TicketID:
          type: string
          description: Ticket number in SLSP application
        ExternalID:
          type: string
          description: Vendor ticket number information
    Chastia.IS.Lib.PluginRest.SLSPJira.Entities.UpdateJobToChastiaParams:
      required:
        - Priority
        - ExternalID
        - Comment
      type: object
      properties:
        Priority:
          type: integer
          description: Priority
          format: int32
        ExternalID:
          type: string
          description: Vendor ticket number
        Comment:
          type: string
          description: Additional information
        Attachments:
          type: array
          items:
            $ref: '#/components/schemas/Chastia.IS.Lib.PluginRest.SLSPJira.Entities.Attachement'
          description: Attachments
    Chastia.IS.Lib.PluginRest.SLSPJira.Entities.Attachement:
      type: object
      properties:
        Name:
          type: string
          description: File name
        Size:
          type: integer
          description: File size in bytes
          format: int32
        ContentType:
          type: string
          description: http content type
        BinaryData:
          type: array
          items:
            type: string
            format: byte
          description: Binary data
    Chastia.IS.Lib.PluginRest.SLSPJira.Entities.UpdateJobResponse:
      required:
        - ExternalID
        - StatusMessage
      type: object
      properties:
        ExternalID:
          type: string
          description: Vendor ticket number
        StatusMessage:
          type: string
          description: Info message
    Chastia.IS.Lib.PluginRest.SLSPJira.Entities.AcceptanceByReporterParams:
      required:
        - ExternalID
        - Comment
      type: object
      properties:
        ExternalID:
          type: string
          description: Vendor ticket number
        Comment:
          type: string
          description: Required information
    Chastia.IS.Lib.PluginRest.SLSPJira.Entities.AcceptanceByReporterResponse:
      required:
        - ExternalID
        - StatusMessage
      type: object
      properties:
        ExternalID:
          type: string
          description: Vendor ticket number
        StatusMessage:
          type: string
          description: Info message
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
