openapi: 3.0.0
info:
  version: '2.0.0'
  title: 'Candidate Video Interview'
  description: 'Candidate video application for job interview'
  contact:
    name: Jupiter Barua
    email: jupiter.barua@metru.de
  license:
    name: Metru GMBH
servers: 
  - url: http://api.metru.at
    description: Staging Server
    
  - url: https://metru.de
    description: Production Server
paths: 
  /v1/jobcode/findbyid:
    get:
      summary: To access jobcode information. When a qrcode is scanned this api get called. Candidate api.
      security: 
        - bearerAuth: []
      parameters: 
        - name: id
          in: query
          description: Booking id of the jobcode.
          example: 5ada0a94b8390d10ff390d10
          required: true
          schema:
            type: string
        - name: noauth
          in: query
          description: Booking id of the jobcode.
          example: true
          schema:
            type: boolean
            description: when this parameter is included it will by pass the security. This flag should be included if the user is not logged in.
      responses:
        '200':
          description: Retrun the jobcode information in json format
  /v1/jobcode/findbybookingid:
    get:
      summary: To access jobcode information. When a booking id is entered insteadt of qrcode this api get called. Candidate api.
      security: 
        - bearerAuth: []
      parameters: 
        - name: bookingId
          in: query
          description: Booking id of the jobcode.
          example: 1204
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Retrun the jobcode information in json format  
  /v1/jobcode/upload/videoanswer:
    post:
      summary: This path is for uploading candidate interview video. Only accessible to candidate.
      security:
        - bearerAuth: []
      parameters: 
        - name: bookingId
          in: query
          description: Booking id of the jobcode.
          example: 1204
          required: true
          schema:
            type: number
        - name: questionNo
          in: query
          description: Question number.
          example: 1
          required: true
          schema:
            type: number
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                videoFile:
                  type: string
                  format: binary
                isTrimmed:
                  type: boolean
                trimStartTime:
                  type: number
                trimEndTime:
                  type: number
                isLastAnswer:
                  type: number
                  description: Value should be true if the last question answer is being send. Else false.
      responses:
        200:
          description: ok.
  /v1/jobcode/candidate/scannedlist:
    get:
      summary: To access list of jobcodes scanned or applied by candidate. Candidate api.
      security: 
        - bearerAuth: []
      responses:
        '200':
          description: Retrun jobcode list json format  
  /v1/jobcode/candidate/scannedlist/delete:
    get:
      summary: This path is for uploading candidate interview video. Only accessible to candidate.
      security:
        - bearerAuth: []
      parameters: 
        - name: id
          in: query
          description: id of the jobcode which is "jobcodeId" in scanned list api response.
          example: 5d4bd1db6f8f181a9790181a
          required: true
          schema:
            type: string
      responses:
        200:
          description: ok.
  /v2/jobad/mark:
    post:
      summary: This path marking a jobad from jobsearch list. Only accessible to candidate.
      security:
        - bearerAuth: []
      parameters: 
        - name: jobAdId
          in: query
          description: id of the jobad which is "_id" in job search api response.
          example: 5d4bd1db6f8f181a9790181a
          required: true
          schema:
            type: string
        - name: bookingId
          in: query
          description: Booking id of the jobad.
          example: 1203
          required: true
          schema:
            type: number
      responses:
        200:
          description: ok.
  /v2/jobad/mark/list:
    get:
      summary: This path marked job list. Only accessible to candidate.
      security:
        - bearerAuth: []
      responses:
        200:
          description: ok. List of jobad
  
components:
  schemas:
    "VideoAnswer":
      type: object
      properties:
        _id: 
          type: string
          example: 5ca52986133fcef1e1d2ff8e
          description: Not required to send with request body.
        video_path:
          type: string
          description: URL of the interview video
        jobCodeId: 
          type: string
        jobAdId: 
          type: string
        bookingId:
          type: number
        candidateEmail:
          type: string
        candidateProfilePic:
          type: string
          description: URL of the image
        candidateProfileVideo:
          type: string
          description: URL of the image
        canStatus: 
          type: number
          description: status
      
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: token
