openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/myorg269/assures/1.0.0
info:
  description: This is an API to get context user
  version: "2.0.0"
  title: Assures API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: assure
    description: assures related calls
paths:
  /assure:
    get:
      tags:
        - assure
      summary: searches context user
      operationId: searchAssure
      description: |
        By passing in the appropriate options, you can search for
        available assure in the system
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Assure'
        '400':
          description: bad input parameter
components:
  schemas:
    Assure:
      type: object
      required:
        - firstName
        - lastName
        - assureNir
      properties:
        assureNir:
          type: string
          example: 12398789856745
        firstName:
          type: string
          example: TOTO
        lastName:
          type: string
          example: Christian
        phone:
          type: string
          example: '0156545667'
