openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'demo_api '
  description: 'test api for learning'
servers:
- url: https://demo.testapi.com/v1
paths: 
  /users/{usersId}:
    get:
      
      parameters: 
        - name: usersId
          in: path
          required: true
          description: the id of the users to return
          schema:
            type: integer
        - name: userName
          in: query
          required: true
          description: input user_name
          schema:
            type: string
              
      summary: Returns a User id.
      responses:
        '200':
          description: ok working ..
          content: 
            application/json:
              schema:
                type: object 
                properties:
                  id: 
                    type: integer
                  name: 
                    type : string 
        '400':
          description: The specified user ID is invalid (e.g. not a number)
        '404':
          description: A user with the specified ID was not found
