openapi: 3.0.0
info:
  description: |
    This is a sample API document for review by hiring manager at Zendesk.  
  version: "1.0.0"
  title: Zendesk SupportGuide User Create
  termsOfService: 'http://zendesk.com'
  contact:
    email: matthew.davis.cv@gmail.com
  license:
    name: Not Applicable
    url: 'http://zendesk.com'
    
tags:
  - name: user
    description: Create Operations for Users 
    externalDocs:
      description: Find out more about Zendesk
      url: 'https://develop.zendesk.com/hc/en-us/articles/360001074248'
paths:
  /SupportGuideUser:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: SGcreateUser
      responses:
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: Created user object
        required: true
  /SupportGuideAgentorAdmin:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: AgentorAdmincreateUser
      responses:
        default:
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: Created user object
        required: true
  /SupportGuideUser/createWithArray:
    post:
      tags:
        - user
      summary: Creates list of users with given input array
      operationId: createUsersWithArrayInput
      responses:
        default:
          description: successful operation
      requestBody:
        $ref: '#/components/requestBodies/UserArray'

externalDocs:
  description: Find out more about Zendesk
  url: 'http://zendesk.com'
servers:
  - url: 'https://virtserver.swaggerhub.com/BigDivot16/SupportGuideUser/1.0.0'
components:
  requestBodies:
    UserArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
      description: List of user object
      required: true
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        name:
          type: string
        active:
          type: boolean
        alias:
          type: string
          description: "Agent or Admin only"
        chat_only:
          type: boolean
          description: "Agent or Admin only"
        created_at:
          type: number
        custom_role_id:
          type: integer
          description: "Agent or Admin only"
        support_role_type:
          type: integer
          description: "New Support-agent-only role type field: 0 for custom agent, 1 for light agent and 2 for chat agent."
        details:
          type: string
          description: "Agent or Admin only"
        external_id:
          type: string
        last_login_at: 
          type: number
        locale:
          type: string
        locale_id:
          type: integer
        moderator:
          type: boolean
          description: "Now supports Logged_in_users as moderators"
        notes:
          type: string
          description: "Agent or Admin only"
        only_private_comments:
          type: boolean
          description: "Agent or Admin only"
        organization_id:
          type: integer
        default_group_id:
          type: integer
          description: "Agent or Admin only"
        phone:
          type: string
        shared_phone_number:
          type: boolean
        photo:
          type: object
        restricted_agent:
          type: boolean
          description: "Agent or Admin only"
        support_role: 
          type: string
          description: "New Support-only role field: end user, agent, or admin"
        guide_role:
          type: string
          description: "New Guide-only roles field: signed_in_user, light viewer, guide agent, or manager"
        shared:
          type: boolean
          description: "Agent or Admin only"
        shared_agent:
          type: boolean
          description: "Agent or Admin only"
        signature:
          type: string
          description: "Agent or Admin only"
        suspended:
          type: boolean
          description: "Agent or Admin only"
        tags:
          type: array
          items:
            type: object  
            description: "only present when enabled. Agent or Admin only"
        ticket_restriction:
          type: string
          description: "Agent or Admin only"
        time_zone:
          type: string
        two_factor_auth_enabled:
          type: boolean
          description: "Agent or Admin only"
        updated_at:
          type: number
        url:
          type: string
        user_fields:
          type: object
        verified:
          type: boolean
        report_csv:
          type: boolean
          description: "Agent or Admin only"
      xml:
        name: User
