openapi: 3.0.0
info:
  version: "1.0-oas3"
  title: AWS Cumulus
  description: The AWS Cumulus backend API documentation.
paths:
  /login:
    post:
      operationId: loginV1
      summary: Authenticate a user with their AWS credentials
      responses:
        '200':
          description: The authentication token
          content:
            application/json:
              schema:
                properties:
                  aws_auth:
                    type: string
                    description: The AWS authentication token
              examples:
                response:
                  value: |-
                    {
                      "aws_auth": "78a859572c7ba0b2860a34842528a159ec51e9e958a5a08afad042cdd3c7c508"
                    }
        '404':
          description: The user credentials do not match a known combination
      requestBody:
        content:
          application/json:
            schema:
              required:
                - aws_user
                - aws_pass
              properties:
                aws_user:
                  type: string
                  example: bob@amazon.com
                aws_pass:
                  type: string
                  example: BobsPassword
        description: The user's AWS credentials
  /instances:
    get:
      operationId: getInstancesV1
      summary: Get the IP addresses of all Cumulus-generated instances
      description: |-
        Will only return instances that have the "Cumulus" tag.
      parameters:
        - in: header
          name: X-AWS-Auth
          description: The user's AWS authentication token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A dictionary of instances
          content:
            application/json:
              examples:
                response:
                  value: |-
                    {
                      "t2.micro": "55.76.123.94",
                      "t3.micro": "73.91.143.85",
                      ...
                    }
  /start_instances:
    post:
      operationId: startInstancesV1
      summary: Start the instance families specified
      parameters:
        - in: header
          name: X-AWS-Auth
          description: The user's AWS authentication token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The IP addresses of the instance families requested
          content:
            application/json:
              examples:
                response:
                  value: |-
                    {
                      "t2.micro": "55.76.123.94",
                      ...
                      "t3.micro": "73.91.143.85",
                      ...
                      "m5.micro": "84.55.194.17",
                      ...
                    }
      requestBody:
        content:
          application/json:
            schema:
              required:
                - families
              properties:
                families:
                  type: array
                  items:
                    description: The identifier of an instance family
                    type: string
              example: |-
                {
                  "families": [
                    "t2", "t3", "m5"  
                  ]
                }
        description: The specified instance families to start
  /upload_workload:
    put:
      operationId: uploadWorkloadV1
      summary: Push the workload to all instances specified
      description: |-
        The workload will be uploaded onto each instance specified, if it has the "Cumulus" tag.
      parameters:
        - in: header
          name: X-AWS-Auth
          description: The user's AWS authentication token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The status of the workload deployment for each instance
          content:
            application/json:
              examples:
                response:
                  value: |-
                    {
                      "55.76.123.94": 200,
                      "73.91.143.85": 200,
                      ...
                    }
      requestBody:
        content:
          application/json:
            schema:
              required:
                - workload
                - instances
              properties:
                workload:
                  type: string
                  description: The workload in binary file format
                instances:
                  type: array
                  items:
                    description: The IP address of an instance
                    type: string
                  example:
                    - 55.76.123.94
                    - 84.55.194.17
        description: The workload binary and instances to push to
  /kill_instances:
    post:
      operationId: killInstancesV1
      summary: Kill the instances specified
      description: |-
        Will kill each of the instances specified, if they have the "Cumulus" tag.
      parameters:
        - in: header
          name: X-AWS-Auth
          description: The users' AWS authentication token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The status of the killed instances
          content:
            application/json:
              examples:
                response:
                  value: |-
                    {
                      "55.76.123.94": 200,
                      "73.91.143.85": 200,
                      ...
                    }
      requestBody:
        content:
          application/json:
            schema:
              required:
                - instances
              properties:
                instances:
                  type: array
                  description: The IP address of an instance
                  items:
                    type: string
                  example:
                    - 55.76.123.94
                    - 73.91.143.85
        description: The IP addresses of the specified instances to kill
servers:
  - url: 'https://virtserver.swaggerhub.com/AWS-Cumulus/Cumulus/1.0'
