openapi: 3.0.0
info:
  description: |
    API for retrieving mobile app and mobile app SDK, toolkit, and framework information from AppSight. App information including universal links and SDKs and frameworks used are processed by AppSight shortly after apps are uploaded to the Google Play or iTunes stores.
  version: "0.3.0"
  title: AppSight API
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: contact@appsight.io
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

servers:
  - description: SwaggerHub API Auto Mocking
    url: "https://virtserver.swaggerhub.com/appsightio/appsight/0.3.0"
  - url: "https://api.appsight.io/api/0.3"

tags:
  - name: app
    description: "Mobile applications"
  - name: sdk
    description: "Mobile SDKs, toolkits, and frameworks"

paths:
  "/app/{id}":
    get:
      tags:
        - app
      summary: "Get app by ID"
      description: "Returns a single app by AppSight's unique ID. The app includes a list of the IDs of all SDKs, toolkits, and frameworks used."
      operationId: app_get
      parameters:
        - name: id
          in: path
          description: "ID of app to return"
          required: true
          schema:
            type: integer
            format: int64
            example: 40191203
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/app'
        "404":
          description: "Not found"
      security:
        - api_key: []

  "/app/find":
    get:
      tags:
        - app
      summary: "Find an app by a link to its app store page or its unique identifier in an app store"
      description: "Returns a list of apps matching the search criteria"
      operationId: app_find
      parameters:
        - name: query
          in: path
          description: "Idenfier or link to the app's app store page"
          required: true
          schema:
            type: string
          examples:
            itunes_url:
              value: "https://itunes.apple.com/app/id40191203"
            gplay_id:
              value: "com.game.checkers"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/app_list_response"
        "404":
          description: "Not found"
      security:
        - api_key: []

  "/app/list":
    get:
      tags:
        - app
      summary: "Retrieve a list of apps published on the app stores. Defaults to requesting the most recently released apps and sorting backwards in time from the release date/time of the apps latest version"
      operationId: app_list
      parameters:
        - name: os
          in: query
          description: "Mobile operating systems to limit the results to"
          schema:
            $ref: "#/components/schemas/os_id"
          examples:
            ios:
              value: "ios"
            android:
              value: "android"
        - name: popularity
          in: query
          description: "Limit the results to the top 500, 1000, or 5000 apps, or apps that are only in the top 1000 in any category/genre"
          schema:
            type: string
            enum:
              - "top-500"
              - "top-1000"
              - "top-5000"
              - "top-1000-in-cat"
        - name: order
          in: query
          description: "The order of returned records. In ascending or descending order by release date"
          schema:
            type: string
            enum:
              - "asc"
              - "desc"
            default: "desc"
        - name: limit
          in: query
          description: "Maximum number of records to return"
          schema:
            type: integer
            format: int16
            default: 200
        - name: at
          in: query
          description: "Identifier used for pagination. After making an initial request, the response will include a pagination link in _links.next"
          schema:
            type: string
          example: "cGFnaW5hdGlvbiBsaW5r"
        - name: app_released_since
          in: query
          description: "Return only results where the app was released since this timestamp (the first version of the app on this app store)"
          schema:
            type: string
            format: date-time
          example: "2019-12-01 09:00:00Z"
        - name: version_released_since
          in: query
          description: "Return only results where the app has a version released since this timestamp."
          schema:
            type: string
            format: date-time
          example: "2019-12-01 09:00:00Z"
        - name: processed_since
          in: query
          description: "Return only results where the app (latest version) was processed by AppSight since this timestamp"
          schema:
            type: string
            format: date-time
          example: "2019-12-01 09:00:00Z"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/app_list_response"
      security:
        - api_key: []

  "/sdk/{id}":
    get:
      tags:
        - sdk
      summary: "Get SDK or framework by ID"
      operationId: sdk_get
      parameters:
        - name: id
          in: path
          description: "ID of the SDK, toolkit, or framework that needs to be fetched"
          required: true
          schema:
            type: string
          example: "unity3d"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/sdk"
        "404":
          description: "Not found"

  "/sdk/list":
    get:
      tags:
        - sdk
      summary: "Returns a list of SDKs"
      description: "Returns a list of SDKs"
      operationId: sdk_list
      parameters:
        - name: at
          in: query
          description: "Identifier used for pagination. After making an initial request, the response will include a pagination link in _links.next"
          schema:
            type: string
          example: "cGFnaW5hdGlvbiBsaW5r"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/sdk_list_response"
      security:
        - api_key: []

components:
  schemas:
    app_store_info:
      type: object
      properties:
        native_id:
          type: string
          description: "Native ID of the application in the app store. IDs in the iTunes store are numberic. IDs in the Google Play store are text (package style format)."
          example: "61191263"
        name:
          type: string
          description: "App name as it appears in the app store"
          example: "Checkers"
        release_timestamp:
          type: string
          format: date-time
          description: "The timestamp when the app version was released on the app store"
          example: "2019-08-15 08:12:03Z"
        author:
          type: object
          properties:
            name:
              type: string
              example: "Awesome Games"
            native_id:
              description: "Unique ID for the author in this app store"
              type: string
              example: "606618"
            url:
              description: "Link to the author page on the app store"
              type: string
              example: "https://itunes.apple.com/author/id606618"
        store:
          $ref: "#/components/schemas/app_store_id"
        url:
          type: string
          description: "URL for the app on the app store"
          example: "https://itunes.apple.com/app/id61191263"
        version:
          type: string
          description: "Version visible in the app store"
          example: "2.34.3"
        categories:
          type: array
          description: "Categories (aka genres) of the app in the app store. First in the list will be the app's primary category/genre"
          items:
            type: string
          example:
            - "Games/Adventure"
            - "Games/Action"

    app:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
          example: 40191203
        os:
          $ref: "#/components/schemas/os_id"
        store_info:
          $ref: '#/components/schemas/app_store_info'
        sdks_used:
          type: array
          items:
            type: string
          example:
            - "unity3d"
            - "app-lovin"
        processed_at:
          type: string
          format: date-time
          description: "The timestamp when the latest version of this app was processed by AppSight"
        urls_called:
          type: array
          description: "A list of universal links or deep links that the app registered to be able to invoke (to call other apps running on the mobile device)"
          items:
            type: string
          example:
            - "maps://"
            - "waze://"
        urls_handled:
          type: array
          description: "A list of universal links or deep links that will be handled by the app"
          items:
            type: string
          example:
            - "checkers://"
            - "checkers-v1://"
        content:
          type: object
          properties:
            files:
              description: "A list of the counts of file types inside the app itself (class files, javascript, etc)"
              type: array
              items:
                type: object
                properties:
                  count:
                    type: integer
                    example: 35
                  extension:
                    description: "The filename extension counted here, not including the period."
                    type: string
                    example: "lua"
            classes:
              description: "A list of the counts of classes by type"
              type: array
              items:
                type: object
                properties:
                  count:
                    type: integer
                    example: 17
                  language:
                    description: "The programming language for the class."
                    type: string
                    enum:
                      - "objective-c"
                      - "swift"
                      - "kotlin"
    app_list_response:
      type: object
      properties:
        apps:
          type: array
          items:
            $ref: "#/components/schemas/app"
        _links:
          type: object
          properties:
            next:
              type: string
              example: "https://api.appsight.io/api/0.3/app/list/?at=H72uahfua8hg"

    app_store_id:
      description: Identifier for the app store
      type: string
      enum:
        - "itunes"
        - "gplay"

    link_type_id:
      type: string
      enum:
        - "cocoapods"
        - "github"
        - "developer"
        - "support"

    os_id:
      type: string
      enum:
        - "ios"
        - "android"

    sdk:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          example: "unity3d"
        name:
          type: string
          example: "Unity 3D"
        os:
          $ref: "#/components/schemas/os_id"
        links:
          type: array
          items:
            type: object
            properties:
              type:
                $ref: "#/components/schemas/link_type_id"
              url:
                type: string
                example: "https://cocoapods.org/pods/Unity3D"

    sdk_list_response:
      type: object
      properties:
        sdks:
          type: array
          items:
            $ref: "#/components/schemas/sdk"
        _links:
          type: object
          properties:
            next:
              type: string
              example: "https://api.appsight.io/api/0.3/sdk/list/?at=H72uahfua8hg"

  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
