openapi: 3.0.0
info:
  description: NYSHEX Enforceable Booking API
  version: "1.0.4"
  title: Enforceable Booking API
  contact:
    email: peter.savitsky@nyshex.com
tags:
    - name: carrier
      description: operations for direct carrier integrations
paths:
  /customers:
    get:
      tags:
          - carrier
      summary: searches for customers
      operationId: search_customers
      description: |
        By passing in the appropriate options, you can search for
        available customers in the system
      parameters:
        - in: query
          name: reference
          description: pass an optional user reference for filtering customers
          required: false
          schema:
            type: string
        - in: query
          name: skip
          description: number of records to skip for pagination
          required: false
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: limit
          description: maximum number of records to return
          required: false
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/customer'
        '400':
          description: bad input parameter
    post:
      tags:
        - carrier
      summary: creates a new customer
      operationId: create_customer
      description: Creates a new customer for use in creating enforceable bookings
      responses:
        '201':
          description: customer created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/created_customer'
        '400':
          description: 'invalid input, object invalid'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request'
        '409':
          description: a customer with this reference already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/customer'
        description: customer to create
  /customers/{customer_id}/reliability:
      get:
        tags:
            - carrier
        summary: gets customer reliability data
        operationId: get_customer_reliability
        description: returns customer reliability data for the specified customer
        parameters:
          - in: path
            name: customer_id
            description: the nyshex assigned customer id
            required: true
            schema:
              type: string
              format: uuid
        responses:
          '200':
            description: reliability data for customer
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/reliability_data'
          '404':
            description: could not find reliability data for the specified customer
  /enforceable-booking:
    post:
      tags:
          - carrier
      summary: creates a new enforceable booking
      operationId: create_enforceable_booking
      description: Creates a new enforceable booking
      responses:
        '201':
          description: enforceable booking created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/enforceable_booking'
        '400':
          description: 'invalid input, object invalid'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request'
        '409':
          description: a booking with this reference already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/enforceable_booking'
        description: enforceable booking to create
  /enforceable-booking/{enforceable_booking_id}/amend:
    post:
      tags:
          - carrier
      summary: amends an enforceable booking
      operationId: amend_enforceable_booking
      description: Amends an existing enforceable booking
      parameters:
          - in: path
            name: enforceable_booking_id
            schema:
                type: string
                format: uuid
            required: true
            description: the nyshex assigned id for the enforceable booking
      responses:
        '200':
          description: enforceable booking amended
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/enforceable_booking'
        '400':
          description: 'invalid input, object invalid'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/enforceable_booking'
        description: enforceable booking to create
  /enforceable-booking/{enforceable_booking_id}/cancel:
      post:
        tags:
            - carrier
        summary: cancels an enforceable booking
        operationId: cancel_enforceable_booking
        description: Cancels an existing enforceable booking
        parameters:
            - in: path
              name: enforceable_booking_id
              schema:
                  type: string
                  format: uuid
              required: true
              description: the nyshex assigned id for the enforceable booking
        responses:
          '200':
            description: enforceable booking canceled
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/enforceable_booking'
          '400':
            description: 'invalid input, object invalid'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/bad_request'
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cancelled_enforceable_booking'
          description: enforceable booking to create
  /equipment-event:
      post:
        tags:
            - carrier
        summary: register a new equipment event
        operationId: register_equipment_event
        description: Registers a new equipment event
        responses:
          '200':
            description: equipment event registered
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/equipment_event'
          '400':
            description: 'invalid input, object invalid'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/bad_request'
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/equipment_event'
          description: equipment_event_to_register

components:
  schemas:
    customer:
      type: object
      required:
        - reference
        - company
        - default_contact
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          example: 12345678-1234-5678-1234-123456789abc
        reference:
          type: string
          example: acme-shipper
        company:
          $ref: '#/components/schemas/company'
        default_contact:
          $ref: '#/components/schemas/person'
    person:
      type: object
      required:
        - first_name
        - last_name
        - email
      properties:
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: Smith
        email:
          type: string
          format: email
          example: john.smith@acmeshipper.com
    company:
      type: object
      required:
        - name
        - address_line_one
        - city
        - state_province_region
        - postal_code
        - country
        - url
      properties:
        name:
          type: string
          example: Acme Shipping Company, LLC.
        ein:
          type: string
          example: 123456789
        address_line_one:
          type: string
          example: 123 Main Street
        address_line_two:
          type: string
          example: Suite 123
        city:
          type: string
          example: New York
        state_province_region:
          type: string
          example: New York
        postal_code:
          type: string
          example: 10279
        country:
          type: string
          example: United States of America
        kyc_confirmation:
          type: string
          example: 128749382
        url:
          type: string
          format: uri
          example: 'http://shipper123.com'
    cancelled_enforceable_booking:
      type: object
      required:
        - cancelling_party
        - cancelled
      properties:
        cancelling_party:
          type: string
          enum: [SELLER, PURCHASER]
        cancelled:
          type: string
          format: date-time
          example: '2019-10-11T18:22:83Z'
        reason:
          type: string
          example: Shipper cancelled
    amended_enforceable_booking:
      type: object
      required:
        - container_size_types
        - place_of_receipt
        - place_of_receipt_terminal
        - port_of_load
        - place_of_delivery
        - place_of_delivery_terminal
        - port_of_discharge
        - container_yard_cutoff
        - departure_cutoff
        - estimated_arrival
      properties:
          container_size_types:
            type: array
            items:
              $ref: '#/components/schemas/container_quantity'
          place_of_receipt:
            $ref: '#/components/schemas/location'
          place_of_receipt_terminal:
            $ref: '#/components/schemas/terminal'
          port_of_load:
            $ref: '#/components/schemas/location'
          place_of_delivery:
            $ref: '#/components/schemas/location'
          place_of_delivery_terminal:
            $ref: '#/components/schemas/terminal'
          port_of_discharge:
            $ref: '#/components/schemas/location'
          service:
            type: string
            example: NX1746
          vessel:
            type: string
            example: NYSHEX Enforcer
          voyage:
            type: string
            example: 2019-10-xyz
          container_yard_cutoff:
            type: string
            format: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}'
            example: '2019-10-22T12:34:20'
          departure_cutoff:
            type: string
            format: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}'
            example: '2019-10-22T12:34:20'
          estimated_arrival:
            type: string
            format: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}'
            example: '2019-10-22T12:34:20'
    enforceable_booking:
        allOf:
            - $ref: '#/components/schemas/amended_enforceable_booking'
            - type: object
              required:
                - reference_number
                - created
                - terms_and_conditions_acceptance
              properties:
                reference_number:
                  type: string
                  example: ABC123
                created:
                  type: string
                  format: date-time
                  example: '2017-07-21T17:32:28Z'
                terms_and_conditions_acceptance:
                  $ref: '#/components/schemas/terms_and_conditions_agreement'
                id:
                  type: string
                  format: uuid
                  example: 12345678-1234-5678-1234-123456789abc
                  readOnly: true
                status:
                  type: string
                  enum: [CONFIRMED, CANCELLED]
                  readOnly: true
    location:
      type: object
      required:
        - code
      properties:
        value:
          type: string
          example: USLAX
        type:
          type: string
          example: UNLOCODE
        version:
          type: string
          example: 2019-1
    terminal:
      type: object
      required:
        - code
      properties:
        value:
          type: string
          example: USLAX-APMT
        type:
          type: string
          example: SMDG
    created_customer:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
          example: 12345678-1234-5678-1234-123456789abc
    bad_request:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: string
            example: 'Invalid container size type'
    terms_and_conditions_agreement:
      type: object
      required:
        - customer_agreed
        - version
      properties:
        customer_agreed:
          type: boolean
          example: true
        version:
          type: string
          example: carrier-nyshex-tandc-2019-10
    reliability_data:
        type: object
        required:
            - currently_in_default
            - last_default
        properties:
          currently_in_default:
              type: boolean
              example: true
          last_default:
              type: string
              format: date
              example: '2018-10-19'
    equipment_event:
        type: object
        required:
            - booking_number
            - equipment_number
            - equipment_size_type
            - location
            - occurence
            - vessel
            - voyage
            - commodity
            - weight_in_kg
            - milestone_type
        properties:
            id:
                type: string
                format: uuid
                readOnly: true
                example: 12345678-1234-1234-1234-1234567890ab
            contract_number:
                type: string
                example: NX-10293
            booking_number:
                type: string
                example: 123645AOEU
            equipment_number:
                type: string
                example: 123ABC123EA
            equipment_size_type:
                type: string
                example: 42GP
                description: the ISO6436 code representing the container size type
            location:
                $ref: '#/components/schemas/location'
            terminal:
                $ref: '#/components/schemas/terminal'
            occurence:
                type: string
                format: date-time
                example: '2018-10-22T18:38:38'
                description: the local date time the event occured, based on the accompanying location
            vessel:
                type: string
                example: NYSHEX Reliability
            voyage:
                type: string
                example: 123ABC
            commodity:
                $ref: '#/components/schemas/commodity'
            weight_in_kg:
                type: number
                format: int32
                example: 20000
            milestone:
                type: string
                example: GATE_IN
    commodity:
        type: object
        required:
            - hs_code
            - description
        properties:
            hs_code:
              type: string
              example: 121292
            description:
              type: string
              example: Sugar cane; of a kind used primarily for human consumption, fresh or dried, whether or not ground
    container_quantity:
        type: object
        required:
            - size_type
            - quantity
            - commodity
        properties:
            size_types:
                type: array
                items:
                    type: string
                    example: 42G0
                    description: ISO6436 container size type
            quantity:
                type: number
                format: int32
                description: the number of containers
            commodity:
                $ref: '#/components/schemas/commodity'

# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/NYSHEX/enforceable-bookings/1.0.0
