openapi: 3.0.1
info:
   title: Notification Endpoint
   version: 1.0.0
paths:
   /notification:
     post:
       description: Ingest Notifications of Vessel Information
       operationId: postNotification
       requestBody:
         description: Vessel Information Notifications
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/Notification'
             example:
               source: ORBCOMM_AIS
               targetUrl: http://a.b.c/d/e
               emitted: '2019-11-20T13:24:45Z'
               vesselInfo:
               - imo: 12345
                 mmsi: 54321
                 callsign: CQLKU
                 shipName: Poseidon
                 shipType: Cargo, all ships of this type
                 vesselDimensions:
                   metersToBow: 150
                   metersToStern: 175
                   metersToPort: 25
                   metersToStarboard: 38
                 metersDraught: 10.0
                 lastUpdate: '2019-11-20T13:24:45Z'
         required: true
       responses:
         '200':
           description: ''
         default:
           description: ''
           content:
             text/plain:
               schema:
                 type: string
components:
   schemas:
     VesselInfo:
       required:
       - imo
       - mmsi
       - callsign
       - shipName
       - shipType
       - vesselDimensions
       - metersDraught
       - lastUpdate
       type: object
       properties:
         imo:
           type: integer
           format: int64
         mmsi:
           type: integer
           format: int64
         callsign:
           type: string
         shipName:
           type: string
         shipType:
           type: string
         vesselDimensions:
           $ref: '#/components/schemas/VesselDimensions'
         metersDraught:
           type: number
           format: double
         lastUpdate:
           type: string
           format: date-time
     NavigationInfo:
       required:
       - mmsi
       - longLat
       - course
       - heading
       - maneuver
       - lastUpdate
       type: object
       properties:
         mmsi:
           type: integer
           format: int64
         longLat:
           $ref: '#/components/schemas/LongLat'
         course:
           type: number
           format: double
         heading:
           type: integer
         maneuver:
           type: string
         lastUpdate:
           type: string
           format: date-time
         imoKey:
           type: integer
           format: int64
     LongLat:
       required:
       - longitude
       - latitude
       type: object
       properties:
         longitude:
           type: number
           format: double
         latitude:
           type: number
           format: double
     Notification:
       required:
       - source
       - targetUrl
       - emitted
       type: object
       properties:
         source:
           type: string
         targetUrl:
            type: string
         emitted:
           type: string
           format: date-time
         vesselInfo:
           type: array
           items:
             $ref: '#/components/schemas/VesselInfo'
         navigationInfo:
           type: array
           items:
             $ref: '#/components/schemas/NavigationInfo'
         destinationInfo:
           type: array
           items:
             $ref: '#/components/schemas/DestinationInfo'
     DestinationInfo:
       required:
       - imo
       - mmsi
       - destination
       - lastUpdate
       type: object
       properties:
         imo:
           type: integer
           format: int64
         mmsi:
           type: integer
           format: int64
         destination:
           type: string
         eta:
           type: string
           format: date-time
         lastUpdate:
           type: string
           format: date-time
     VesselDimensions:
       required:
       - metersToBow
       - metersToStern
       - metersToPort
       - metersToStarboard
       type: object
       properties:
         metersToBow:
           type: integer
           format: int64
         metersToStern:
           type: integer
           format: int64
         metersToPort:
           type: integer
           format: int64
         metersToStarboard:
           type: integer
           format: int64
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Crux-Systems/attic/1.0.0
