openapi: 3.0.0
servers: []
info:
  description: AI Sandbox API specification for the Mine Hunter scenario.
  version: "1.0.0"
  title: Mine Hunter API
  contact:
    url: www.aisandbox.dev
  license:
    name: GPLv3
    url: 'https://www.aisandbox.dev/licence.html'
paths:
  /api/mine:
    post:
      summary: Summary
      description: Description
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MineRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/MineRequest'
      responses:
        '200':
          description: The action to perform.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MineResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/MineResponse'
        '500':
          description: Server error - halt simulation.
    
components:
  schemas:
    MineRequest:
      type: object
      required:
        - boardID
        - board
        - flagsRemaining
      properties:
        lastMove:
          type: object
          required:
            - boardID
            - result
          properties:
            boardID:
              type: string
              example: 1233-5678-90abc
            result:
              type: string
              example : LOST
              enum: [WON,LOST,PLAYING]
        boardID:
          type: string
          example: 1234-1234-1234-1234
        board:
          type: array
          items:
            type: string
            example: "#..3F###"
        flagsRemaining:
          type: integer
          format: int32
          example: 6
    MineResponse:
      type: object
      required: 
        - moves
      properties:
        moves:
          type: array
          items:
            $ref: '#/components/schemas/Move'
    Move:
      type: object
      required:
        - x
        - y
        - flag
      properties:
        x:
          type: integer
          format: int32
          example: 4
        y:
          type: integer
          format: int32
          example: 6
        flag:
          type: boolean
          description: True to place a flag, false to uncover
