openapi: 3.0.0
info:
  version: "1.0.0"
  title: User settings service
tags:
  - name: setting
    description: User prefferences
paths:
  /settings:
    get:
      tags:
        - setting
      summary: Get settings for current loggedin user
      responses:
        '200':
          description: Rich json with merged collections of default/group/user settings
        '404':
          description: User not recognized
        '405':
          description: Validation of JSON exception
    put:
      tags:
        - setting
      summary: Update an existing settings for current user
      responses:
        '404':
          description: User not recognized
        '405':
          description: Validation of JSON exception
    delete:
      tags:
        - setting
      summary: Reset settings for current loggedin user
      responses:
        '404':
          description: User not recognized
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/andreyjkee/settings-service/1.0.0
