openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Api para Consultas Genéricas'
  description: 'Api para utilizada para efetuar consultas genéricas de aplicativos e sites'
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/BTCorretora/ConsultasGenericas/1.0.0
paths:
  /obter:
    post:
      summary: Api obter uma consulta direta
      operationId: obter
      description: Obtém dados de uma consulta direta pela consultaId definida
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametrosConsulta'
      responses:
        '200':
          description: resultado da consulta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultadoConsulta'
components:
  schemas:
    ResultadoConsulta:
      type: object
      required:
        - dados
        - situacao
        - sucesso
      properties:
        sucesso:
          type: boolean
        codigoErro:
          type: integer
          nullable: true
        mensagem:
          type: string
          nullable: true
        dados:
          type: string
          description: base64 string
        situacao:
          type: integer
    ParametrosConsulta:
      type: object
      properties:
        parametrosDb:
          type: string
          nullable: true
          description: base64 from compressed bytes 
        parametrosJson:
          type: string
          nullable: true
          description: base64 from json parameters
