openapi: 3.0.1
info:
  title: DSP API
  description: >-
    API voor DSP deelnemers.


    De API bevat momenteel 2 operaties:

    1. Lijst van Opdrachten ophalen

    2. Specifieke Opdracht ophalen


    Operaties die een lijst retourneren ondersteunen paging, zodat het aantal entries dat terug
    wordt gegeven altijd beperkt is. De logica om deze pages uit te vragen dient
    door de client te worden geimplementeerd.


    Exacte autorisatie scopes worden door het DSP verstrekt.
  contact:
    email: functioneelbeheer@dsplatform.nl
  version: 1.0.0
servers:
  - url: 'https://qas-services.dsplatform.nl/api'
tags:
  - name: dsp
    description: DSP data voor de deelnemers.
paths:
  /opdrachten:
    get:
      tags:
        - opdrachten
      summary: Lijst van opdrachten voor de huidige deelnemer
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: page number
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpdrachtList'
        '204':
          description: No content
          content: {}
        '400':
          description: Bad request
          content: {}
      security:
        - auth0:
          - 'https://services.dsplatform.nl/api/deelnemer:<deelnemernaam>'
  /opdrachten/{opdrachtId}:
    get:
      tags:
        - opdrachten
      summary: Specifieke Opdracht voor de huidige deelnemer
      parameters:
        - in: path
          name: opdrachtId
          required: true
          schema:
            type: string
          description: opdrachtId om een specifieke opdracht op te halen
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpdrachtItem'
        '400':
          description: Bad request
          content: {}
        '404':
          description: Not found
          content: {}
      security:
        - auth0:
          - 'https://services.dsplatform.nl/api/deelnemer:<deelnemernaam>'
components:
  schemas:
    OpdrachtList:
      type: object
      properties:
        paging:
          $ref: '#/components/schemas/PagingInfo'
        docs:
          type: array
          items:
            $ref: '#/components/schemas/OpdrachtItem'
    PagingInfo:
      type: object
      properties:
        totalDocs:
          type: integer
          description: total nr of entries found
        limit:
          type: integer
          description: nr of entries per page
        hasPrevPage:
          type: boolean
          description: previous page available
        hasNextPage:
          type: boolean
          description: next page available
        page:
          type: integer
          description: current page number
        totalPages:
          type: integer
          description: total nr of pages
        pagingCounter:
          type: integer
          description: nr of first item on current page
        prevPage:
          type: integer
          description: previous page number if available
        nextPage:
          type: integer
          nullable: true
          description: next page number if available
        total:
          type: integer
          nullable: true
          description: total pages
    OpdrachtItem:
      type: object
      properties:
        opdrachtId:
          type: string
        versienummer:
          type: string
        proces:
          type: string
        postcode:
          type: string
          nullable: true
        woonplaats:
          type: string
          nullable: true
        status:
          type: string
        statusTG:
          type: string
        statusAGA:
          type: string
        statusAGP:
          type: string
        discipline:
          type: string
        netbeheerder:
          type: string
        aannemer:
          type: string
        opdrachtnemer:
          type: string
          nullable: true
        clusterId:
          type: string
          nullable: true
        wijzigingsdatum:
          type: string
          format: date-time
  securitySchemes:
    auth0:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: >-
            https://services-dsplatform.auth.eu-central-1.amazoncognito.com/oauth2/token
          scopes:
            'https://services.dsplatform.nl/api/deelnemer:<deelnemernaam>': read DSP opdrachten data
