openapi: 3.0.0
info:
  title: eKeeper 5X API
  version: '1.0'
paths:
  /new/api/mortgage/new-lead:
    post:
      tags:
        - Mortgage
      description: Generate a new lead
      operationId: 'Modules\Mortgage\Http\Controllers\MortgageController::createNewLead'
      requestBody:
        description: Application for new lead
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationRequestBody'
      responses:
        '200':
          description: Mortgage new lead response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MortgageNewLeadResponse'
      security:
        - apiAuth: []
components:
  schemas:
    Applicant:
      required:
        - firstname
        - surname
        - dateOfBirth
      type: object
      allOf:
        - properties:
            firstname:
              description: The firstname of applicant
              type: string
              example: Tony
            middlename:
              description: The middlename of applicant
              type: string
              example: Trevor
            surname:
              description: The surname of applicant
              type: string
              example: Stark
            dateOfBirth:
              description: The date of birth applicant
              type: string
              format: date-time
              example: '1988-01-01'
            phoneNumber:
              description: The phone number of birth applicant
              type: string
              example: '01632555444'
            emailAddress:
              description: The Email Address of birth applicant
              type: string
              example: tony@example.com
            employmentStatus:
              description: Employment Status
              type: string
              example: Employed
            grossAnnualIncome:
              description: Basic gross annual income
              type: integer
              example: 100000000
            addresses:
              type: array
              items:
                $ref: '#/components/schemas/Address'
          type: object
    Address:
      required:
        - postcode
      type: object
      allOf:
        - properties:
            flat:
              description: 'Name or number of flat, if applicable'
              type: string
            houseNumber:
              description: 'Number of house, if applicable'
              type: string
            houseName:
              description: 'Name of house, if applicable'
              type: string
            street:
              description: Street
              type: string
            town:
              description: Town
              type: string
            postcode:
              description: Postcode
              type: string
          type: object
    Application:
      required:
        - mortgageAmount
        - clientType
        - applicants
      properties:
        purchasePrice:
          description: Purchase Price of the property
          type: integer
          example: 2500000
        mortgageAmount:
          description: The total amount the mortgage will be for
          type: integer
          example: 2000000
        mortgageTermYears:
          description: The term of the mortgage in years
          type: integer
          example: 25
        clientType:
          description: >-
            Client Type (eg. First Time Buyer, Home Mover, Investor, Remortgage,
            Other)
          type: string
          example: FirstTimeBuyer
        applicants:
          type: array
          items:
            $ref: '#/components/schemas/Applicant'
      type: object
    ApplicationRequestBody:
      required:
        - enquiryId
        - productSubType
        - application
      type: object
      allOf:
        - properties:
            enquiryId:
              description: The uuid for the enquiry
              type: string
              example: 75d2ad04-345e-4623-b9ee-e6a5b0d05673
            productSubType:
              description: The product subtype that will be created for new lead
              type: integer
              example: 36
            application:
              type: string
              $ref: '#/components/schemas/Application'
          type: object
    MortgageNewLeadResponse:
      description: Mortgage new lead response
      type: object
      allOf:
        - properties:
            message:
              type: string
          type: object
  securitySchemes:
    apiAuth:
      type: apiKey
      description: Api Key Authentication
      name: Authorization
      in: header
tags:
  - name: Mortgage
    description: A set of endpoints for working with mortgages
