openapi: 3.0.0
info:
  description: >-
    This service is a gateway for routing to specific services that recognize
    text from certain types of sources.

    For example, they recognize an image engraved on a metal surface.

    Or a piece of text from a PDF document.

    [http://swagger.io](http://swagger.io) or on 

    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  version: "1.0.0-oas3"
  title: OCR API Gateway
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  contact:
    url: 'https://kt-team.de'
tags:
  - name: ocr
    description: gateway entry point
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
paths:
  '/ocr/{type}/{lang}':
    post:
      tags:
        - ocr
      summary: Return recognized text from image
      description: Returns json with recognized text fragments
      requestBody:
        description: multipart/form-data body content
        required: false
        content:
           multipart/form-data:
            schema:
              required: [image]
              type: object
              properties:
                image:
                  type: string
                  format: binary
                patterns:
                  type: array
                  items:
                    type: string
      parameters:
        - in: path
          name: type
          description: engraving or pdf text and etc.
          required: true
          schema:
            type: string
            format: string
        - in: path
          name: lang
          required: true
          description: image lang
          schema:
            type: string
            format: string
      responses:
        '200':
          description: successful operation with json response
        '400':
          description: Invalid params
host: virtserver.swaggerhub.com
schemes:
  - https
  - http
basePath: /bkt63593/ocr-api-gateway/1.0.0
servers:
  - url: http://api.sherlocktest.kt-team.de
    description: Test server
