openapi: 3.0.0
info:
  version: "1-oas3"
  title: User API
  description: ''
paths:
  /users:
    get:
      description: Returns a list of users
      responses:
        '200':
          description: Successfully returned a list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Users'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Users'
            application/yaml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Users'
    post:
      description: Create a new User
      responses:
        '200':
          description: Successfully added a new user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Users'
    
    
    delete:
      description: Delete a user
      responses:
        '200':
          description: User deleted
        '404':
          description: User not found
  
        
components:
  schemas:
    Users:
      type: object
      required:
        - userID
      properties:
        userID:
          type: integer
          example: 1
        userName:
          type: string
          example: Rachel
        email:
          type: string
          example: rachel@gmit.ie
        password:
          type: string
          example: testing

servers:
  - description: SwaggerHub API Auto Mocking
    url: 'https://virtserver.swaggerhub.com/rachelmcclelland6/UserAPI/1'
