openapi: 3.0.0
info:
  version: '0.0.1'
  title: 'PirApp'
  description: ''
servers: 
  - url: https://pirapp.tech/api
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /auth/signup:
      post:
        description: Create a new user
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: yoda@hoth.ally
                  password:
                    type: string
                    example: M@ythe4th
        responses:
          201:
            description: User Created
          409:
            description: Email already exists
            content:
              application/json:
                schema:
                  type: object 
                  properties:           
                    message:
                      type: string
                      example: Email already exists
          500:
            description: Internal Server Error
            content:
              application/json:
                schema:
                  type: object 
                  properties:           
                    message:
                      type: string
                      example: An error ocurred on creating user
  /auth/sigin:
      post:
        description: Sign in a new user
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: yoda@hoth.ally
                  password:
                    type: string
                    example: M@ythe4th
        responses:
          200:
            description: User successfully logged in
            content:
              application/json:
                schema:
                  type: object
                  properties:
                      accessToken:
                        type: string
          500:
            description: Internal Server Error
            content:
              application/json:
                schema:
                  type: object 
                  properties:           
                    message:
                      type: string
                      example: An error ocurred on creating user
