openapi: 3.0.0
info:
  title: MSLA Cloud Service API
  description: This service allow registering Westcon's MSLA customers to have its
    consumption data monitored and them generate reports from it
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/andre.vellinha/MSLACloudServices/1.0.0
  description: SwaggerHub API Auto Mocking
  
paths:
  /msla/credentials:
    post:
      tags:
      - Credentials
      summary: Add new partner's credentials to be monitored by the system
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        201:
          description: credential(s) successfully added to the system
        500:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      tags:
      - Credentials
      summary: List partners' credentials that are currently being monitored by the
        system
      parameters:
        - name: internalResellerId
          in: query
          description: Internal reseller id used when submiting the credentials to be
            monitored
          required: true
          style: form
          explode: true
          schema:
            type: string
          example: "10294"
        - name: limit
          in: query
          description: How many items to return at one time (max 50)
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            default: 20
            maximum: 50
        - name: page
          in: query
          description: Page number for paginated queries
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            default: 1
            minimum: 1
      responses:
        200:
          description: previously submitted credentials for the given reseller
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Credentials'
                  metadata:
                    $ref: '#/components/schemas/Metadata'
        500:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
  /msla/report/usage:
    get:
      tags:
      - Report
      summary: retrieve reseller's consumption data for a given period (per default,
        return the last closed billing cycle)
      parameters:
        - name: month
          in: query
          description: billing cycle's month in "MM" format
          required: true
          style: form
          explode: true
          schema:
            type: string
            pattern: '^\d{2}$'
          example: "09"
        - name: year
          in: query
          description: billing cycle's year in "YYYY" format
          required: true
          style: form
          explode: true
          schema:
            type: string
            pattern: '^\d{4}$'
          example: "2019"
        - name: grouped
          in: query
          description: return the usage report information grouped based on the vendor's provided logic or return the data acquired on daily basis
          required: true
          style: form
          explode: true
          schema:
            type: boolean
        - name: serviceName
          in: query
          description: inform if needed to filter report per service
          required: false
          style: form
          explode: true
          schema:
            type: string
            enum:
            - AMP
            - Umbrella
          example: AMP
        - name: limit
          in: query
          description: How many items to return at one time (max 50)
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            default: 20
            maximum: 50
        - name: page
          in: query
          description: Page number for paginated queries
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            default: 1
            minimum: 1
      responses:
        200:
          description: expected report in a json format
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Report'
                  metadata:
                    $ref: '#/components/schemas/Metadata'
        500:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
  /msla/report/confirmUsage:
    post:
      tags:
      - Report
      summary: confirm billing cycle usage
      requestBody:
        description: Partner's credentials used for monitoring the service consumption
          on daily basis
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmRequest'
      responses:
        200:
          description: Usage report confirmed for the given period
        500:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    AMPCredential:
      required:
        - customerName
        - customerGuid
        - apiClientId
        - apiClientKey
      properties:
        customerName:
          type: string
          description: Customer name as provided by Cisco
          example: 'P. R. Home Insurance'
        customerGuid:
          type: string
          description: Customer guid as provided by Cisco
          example: '14267399-e565-4cd0-89cd-02286f9504d9'
        apiClientId:
          type: string
          description: Api client id as provided by Ciscofor monitoring AMP4EP consumption
          example: 'ae39a532595f21f373b6'
        apiClientKey:
          type: string
          description: Api client key as provided by Cisco for monitoring AMP4EP consumption
          example: 'feeab225-2788-46e2-yz78-956e831fc5db'
        serviceName:
          type: string
          example: 'amp'
        createdAt:
          type: string
          description: Date when the credential was submitted to the system
          format: date
          readOnly: true
          example: '2020-01-01'
        internalResellerId:
          type: string
          description: Internal reseller id from the system using the service used
            for linking data between systems. Use unique identifiers.
          readOnly: true
          example: "5503"
    UmbrellaCredential:
      required:
        - subscriptionId
        - serviceKey
        - serviceSecret
        - mspid
      properties:
        subscriptionId:
          type: string
          description: Subscription id information as provided by the vendor
          example: Sub12345
        serviceKey:
          type: string
          description: Service key as provided by the vendor in order to monitor umbrella usage
          example: f08746ca31dc4759991f9612927a9328
        serviceSecret:
          type: string
          description: Service secret as provided by the vendor in order to monitor
            umbrella usage
          example: f5ca97e256521ec9ac05631474dc6a18
        mspid:
          type: string
          description: MSPID as provided by the vendor in order to monitor umbrella
            usage
          example: "2538670"
        serviceName:
          type: string
          example: 'umbrella'
        createdAt:
          type: string
          description: Date when the credential was submitted to the system
          format: date
          readOnly: true
          example: '2020-01-01'
        internalResellerId:
          type: string
          description: Internal reseller id from the system using the service used
            for linking data between systems. Use unique identifiers.
          readOnly: true
          example: "5503"
    
    Credentials:
      type: array
      items:
        oneOf:
          - $ref: '#/components/schemas/AMPCredential'
          - $ref: '#/components/schemas/UmbrellaCredential'
        discriminator:
          propertyName: serviceName
          mapping:
            amp: '#/components/schemas/AMPCredential'
            umbrella: '#/components/schemas/UmbrellaCredential'
            
    Report:
      properties:
        lines:
          type: array
          items:
            $ref: '#/components/schemas/ReportLine'
            
    ReportLine:
      type: object
      properties:
        serviceName:
          type: string
          description: Service monitored by the line
          example: Umbrella
        endCustomerName:
          type: string
          description: End customer's name
          example: Maxlog Imports
        externalRefId:
          type: string
          description: ???
          example: ???
        from:
          type: string
          description: Billing cycle start date
          format: date
        to:
          type: string
          description: Billing cycle end date
          format: date
        usage:
          type: integer
          format: int32
          description: Amount of service usage
          example: 150
        unitOfMeasure:
          type: string
          description: Vendor's unit of measure
          example: Seats
        confirmed:
          type: boolean
          description: Indicates if the usage consumption was confirmed by the partner
          example: true
          
    ConfirmRequest:
      required:
        - internalResellerId
        - serviceName
        - month
        - year
      properties:
        internalResellerId:
          type: string
          description: Internal reseller id from the system using the service used
            for linking data between systems. Use unique identifiers.
          example: "5503"
        month:
          type: string
          description: billing cycle's month in "MM" format
          example: "03"
          pattern: '^\d{2}$'
        year:
          type: string
          description: billing cycle's year in "YYYY" format
          example: "2020"
          pattern: '^\d{4}$'
        serviceName:
          type: string
          description: inform service related to the consumption data to be confirmed
          example: AMP
          enum:
            - AMP
            - Umbrella
            
    Error:
      type: object
      properties:
        error: 
          type: object
          properties:
            type:
              type: string
              description: exception message slug
            title:
              type: string
            code:
              type: integer
              description: error code
              format: int32
            detail:
              type: string
              description: exception message
              
    Metadata:
      type: object
      properties:
        currentPage:
          type: integer
          description: current page
          example: 3
        count:
          type: integer
          description: number of items in the current page
          example: 50
        totalItems:
          type: integer
          description: total items
          example: 175
        previous:
          type: string
          description: link for previous page
          example: '{serviceURL}?page=2'
        next:
          type: string
          description: link for next page
          example: '{serviceURL}?page=4'
