openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: PTTOR AMAZON MKIS
    url: https://virtserver.swaggerhub.com/One-Mahassajun/MKIS/1.0.0
info:
  description: PTTOR AMAZON MKIS
  version: "1.0.0"
  title: PTTOR AMAZON MKIS
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: master
    description: Master Data
  - name: MKIS
    description: MKIS Data
security:
  - bearerAuth: [] 
paths:
  /get-location:
    get:
      tags:
        - master
      summary: Get Location Data
      description: |
        Get Location Data

      responses:
        '200':
          description: result of location data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocationItem'
        '400':
          description: bad input parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorItem'

        '401':
          description: Invalid Autentication
        '500':
          description: System Error
  /get-province:
    get:
      tags:
        - master
      summary: Get Province Data
      description: |
        Get Province Data

      responses:
        '200':
          description: result of provine data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProvinceItem'
        '400':
          description: bad input parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorItem'

        '401':
          description: Invalid Autentication
        '500':
          description: System Error

  /get-district/{provinceId}:
    get:
      tags:
        - master
      summary: Get District Data
      description: |
        Get District Data

      parameters:
        - in: path
          name: provinceId
          description: Id of Province
          required: true
          schema:
            type: integer
            example: 12
      responses:
        '200':
          description: result of district data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DistrictItem'
        '400':
          description: bad input parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorItem'
        '401':
          description: Invalid Autentication
        '500':
          description: System Error
  
  /get-sub-district/{districtId}:
    get:
      tags:
        - master
      summary: Get Sub District Data
      description: |
        Get Sub District Data

      parameters:
        - in: path
          name: districtId
          description: Id of District
          required: true
          schema:
            type: integer
            example: 12
      responses:
        '200':
          description: result of sub district data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubDistrictItem'
        '400':
          description: bad input parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorItem'
        '401':
          description: Invalid Autentication
        '500':
          description: System Error

  /check-status/{amazonId}:
    get:
      tags:
        - MKIS
      summary: Get Status of Franchise Application
      description: |
        Get Status of Franchise Application

      parameters:
        - in: path
          name: amazonId
          description: Amazon reference Id
          required: true
          schema:
            type: string
            example: AMZ00842254
      responses:
        '200':
          description: result of status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusItem'
        '400':
          description: bad input parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorItem'
        '401':
          description: Invalid Autentication
        '500':
          description: System Error

  /insert-mkis:
    post:
      tags:
        - MKIS
      summary: Post Data to MKIS System
      description: |
        Post Data to MKIS System
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MKISItem'
      responses:
        '200':
          description: result of status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MKISReturn'
        '400':
          description: bad input parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorItem'
        '401':
          description: Invalid Autentication
        '500':
          description: System Error

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: api_token    # optional, arbitrary value for documentation purposes
  schemas:
    ProvinceItem:
      type: object
      properties:
        id: 
          type: integer
          example: 12
        nameTh: 
          type: string
          example: กรุงเทพ
        nameEn:
          type: string
          example: Bangkok
    DistrictItem:
      type: object
      properties:
        id: 
          type: integer
          example: 12
        provinceId:
          type: integer
          example: 34
        nameTh: 
          type: string
          example: ปากเกร็ด
        nameEn:
          type: string
          example: Pakred
    SubDistrictItem:
      type: object
      properties:
        id: 
          type: integer
          example: 12
        provinceId:
          type: integer
          example: 34
        districtId:
          type: integer
          example: 56
        nameTh: 
          type: string
          example: ท่าอิฐ
        nameEn:
          type: string
          example: Thait
    LocationItem:
      type: object
      properties:
        id: 
          type: integer
          example: 12
        nameTh: 
          type: string
          example: ตลาด
        nameEn:
          type: string
          example: Market
    StatusItem:
      type: object
      properties:
        id: 
          type: integer
          example: 2
        descriptionTh: 
          type: string
          example: อยู่ระหว่างการตรวจสอบ
        descriptionEn:
          type: string
          example: In progress
    ErrorItem:
      type: object
      properties:
        code:
          type: string
          description: Error return code
          example: '001'
        message:
          type: string
          description: Error message
          example: data not found
    BoardItem:
      type: object
      properties:
        titleName:
          type: integer
          enum:
            - 1
            - 2
            - 3
          description: > 
            Id of Tilte Name :
              * `1` - นาย
              * `2` - นาง
              * `3` - นางสาว
          example: 1
        firstName:
          type: string
          description: Board first name
          example: Wichian
        lastName:
          type: string
          description: Board last name
          example: Yung

    AttachmentItem:
      type: object
      properties:
        type:
          type: string
          enum:
            - 'citizen'
            - 'map'
            - 'place'
            - 'statement'
          description: >
            Attachment Type : 
              * `citizen` - บัตรประจำตัวประชาชน หรือ ทะเบียนบริษัท
              * `map` - แผนที่
              * `place` - ภาพถ่ายสถานที่
              * `statement` - Statement ธนาคาร
          example: citizen
        url:
          type: string
          description: Url of file
          example: http://www.cafe-amazon.com/upload/abc.jpg
    
    MKISReturn:
      type: object
      properties:
        result: 
          type: boolean
          example: true
        MKISId:
          description: Return MKIS ID 
          type: integer
          example: 12
    MKISItem:
      type: object
      description: >
        ขยายความ required:
          * ถ้า entrepreneurTypeId = 1 จะ required field ดังต่อไปนี้
            - juristicPersonName
            - juristicId
            - boards
          * ถ้า entrepreneurTypeId = 2 จะ required field ดังต่อไปนี้
            - personTitleName
            - personFirstName
            - personLastName
      required:
        - amazonId
        - requestId
        - registerDate
        - entrepreneurTypeId
        - personTitleName
        - personFirstName
        - personLastName
        - juristicPersonName
        - boards
        - juristicId
        - mobile
        - email
        - experience
        - storeLocation
        - addressNo
        - provinceId
        - districtId
        - subDistrictId
        - ownerTypeArea
        - areaSquareMeter
        - areaRentalCost
        - locationTypeId
        - locationTypeName
        - latitude
        - longitude
        - hasRelation
        - coiRelate
        - pisRelate

      properties:
        boards:
          description: รายชื่อคณะกรรมการ
          type: array
          items:
            $ref: '#/components/schemas/BoardItem'
        attachments:
          description: ไฟล์แนบ
          type: array
          items:
            $ref: '#/components/schemas/AttachmentItem'
        amazonId:
          type: integer
          description:  Running number on Amazon database
          example: 11
        requestId:
          type: string
          description: Request Id that be generate by system and send to application/json
          example: AMZ00842254
        registerDate:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}$'
          description: Register date
        entrepreneurTypeId:
          type: integer
          enum:
            - 1
            - 2
          description: >
            ประเภทผู้สมัคร:
              * `1` - นิติบุคคล
              * `2` - บุคคลธรรมดา
          example: 1
        personTitleName:
           type: integer
           enum: [1,2,3]
           description: > 
            Id of Tilte Name :
              * `1` - นาย
              * `2` - นาง
              * `3` - นางสาว
           example: 1
        personFirstName:
          type: string
          description: ชื่อผู้สมัคร
          example: นคร
        personLastName:
          type: string
          description: นามสกุลผู้สมัคร
          example: กิจพิทักษ์
        citizenId:
          type: string
          description: เลขบัตรประจำตัวประชาชน
          example: 325325232552
        juristicPersonName:
          type: string
          description: ชื่อบริษัท
          example: บริษัท เอพีเอดีสทริบิวเตอร์ จำกัด
        juristicId:
          type: string
          description: เลขทะเบียนบริษัท
          example: 325325232552
        tel:
          type: string
          description: 'เบอร์โทรศัพทื'
          example: '0212345678'
        mobile:
          type: string
          description: 'เบอร์โทรศัทพ์มือถือ'
          example: '0891112532'
        email:
          type: string
          description: 'Email Address'
          example: 'example@gmail.com'
        fax:
          type: string
          description: 'Fax'
          example: '021234523'
        experience:
          type: boolean
          description: 'มีประสบการณในการทำงานหรือไม่'
          example: true
        experienceDesc:
          type: string
          description: 'รายละเอียดประสบการณ์ในการทำงาน'
          example: 'มีร้านกาแฟที่รามคำแหง'
        storeLocation:
          type: string
          enum:
            - T
            - O
          description: >
           สถานที่ตั้ง: 
            * `T` - ในประเทศไทย
            * `O` - ตางประเทศ
          example: 'T'
        addressNo:
          type: string
          description: 'บ้านเลขที่'
          example: '253'
        moo:
          type: string
          description: 'หมู่ที่'
          example: '1'
        building:
          type: string
          description: 'อาคาร'
          example: 'ซีพีทาว์เวอร์'
        floor:
          type: string
          description: 'ชั้น'
          example: '12'
        room:
          type: string
          description: 'ห้องเลขที่'
          example: '35'
        road:
          type: string
          description: 'ถนน'
          example: 'งามวงศ์วาน'
        provinceId:
          type: integer
          description: 'Id ของ จังหวัด'
          example: 15
        districtId:
          type: integer
          description: 'Id ของ อำเภอ'
          example: 16
        subDistrictId:
          type: integer
          description: 'Id ของ ตำบล'
          example: 17
        postcode:
          type: string
          description: 'รหัสไปรษณีย์'
          example: '70000'
        ownerTypeArea:
          type: string
          enum:
            - 'o'
            - 'r'
          description: >
           ความเป็นเจ้าของ :
            * `o` - เป็นเจ้าของ
            * `r` - เช่า
          example: 'o'
        areaRentalCost:
          type: integer
          description: 'ค่าเช่า'
          example: 1000
        areaSquareMeter:
          type: number
          description: 'ขนาดพื้นที่'
          example: 35.5
        locationTypeId:
          type: integer
          description: 'Id ของทำเลขที่ตั้ง'
          example: 12
        locationTypeName:
          type: string
          description: 'ชื่อสถานที่'
          example: 'บ้านจันเจ้า'
        latitude:
          type: string
          description: 'Latitude'
          example: '34.23564'
        longitude:
          type: string
          description: 'Longitude'
          example: '100.3232'

        overallEnverloment:
          type: string
          description: 'สถาพแวดล้อมโดยรวมของสถานที่ที่จะนำเสนอ'
          example: 'เป็นถนนสายหลัก'
        carPark:
          type: boolean
          description: 'ที่จอดรถ'
          example: true
        placeAround:
          type: string
          description: 'สถานที่โดยรอบรัศมี 1 กิโลเมตร มีอะไรบ้าง'
          example: 'บิกซี'
        volumn:
          type: integer
          description: 'ปริมาณคนโดยเฉลี่ยต่อวัน'
          example: 2000
        reason:
          type: string
          description: 'เหตุผลในการสมัคร'
          example: 'ชอบทำธุรกิจ'
        hasRelation:
          type: boolean
          description: 'ความสัมพันธ์กับบุคลากรหรือไม่'
          example: true
        relationType:
          type: string
          description: >
           ประเภทสความสำพันธ์:
              * `B` - ทางสายโลหิต
              * `W` - คู่สมรส
              * `R` - การจดทะเบียนตามกฏหมาย เช่น บุตรบุญธรรม
          example: 'B'
        relationTypeName:
          type: string
          description: 'ในกรณที่มีความสัมพันธ์ทางสายโลหิต (B) เป็นความสำพันธ์ประเภท'
          example: 'พ่อ'
        relationName:
          type: string
          description: 'ชื่อบุคลากรในบริษัทที่มีความสำพันธ์ด้วย'
          example: 'นาย เอ นามสมมุติ'
        relationText:
          type: string
          description: 'รายละเอียดความสัมพันธ์'
          example: 'มีความสัมพันธ์กับบุคลากรบริษัทฯ ชื่อ Mr Tester Test12112018  โดยทางสายโลหิตเป็น ญาติ'
        coiRelate:
          type: boolean
          description: 'ระบบตรวจสอบว่ามีความสัมพันธ์กับระบบ COI หรือไม่'
          example: true
        pisRelate:
          type: string
          description: 'ระบบตรวจสอบว่ามีความสัมพันธ์กับระบบ PIS หรือไม่'
          example: true
        relateDetail:
          type: string
          description: 'รายละเอียดความสัมพันธ์ของระบบ'
          example: '[คุณ เพทาย คุ้มคำมี  เป็นพนักงาน PTTOR รหัส 180040 ,]  '
        remark:
          type: string
          description: 'Remark ของ Admin'
          example: 'Remark'
