openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/JohnKlein1991/PostServiceApi/1.0.0
  - description: api.postsrvs.ru
    url: https://home.courierexe.ru/api/
info:
  description: Интерактивная документация для API Post Service
  version: "1.0.0"
  title: API Post Service
paths:
  /:
    post:
      summary: Получение вложений к накладной
      operationId: attachments
      requestBody:
        description: |
          Описание полей:
            
            attachments - Корневой контейнер. Обязательный элемент.
            
            auth - Авторизация. Обязательный элемент.
            
            orderno - Номер/код заказа. Обязательный элемент.
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/attachements'
      responses:
        '200':
          description: |
            Список вложений. В тегах item возвращаются бинарные данные (файлы), закодированные в base64.
            
            Также тегах item передаются атрибуты:
             - name - имя файла
             - size - размер
          content:
            application/xml:
              schema:
                type: array
                items:
                  type: string
                  xml:
                    name: item
                example:
                 - JVBERi0xLjMNJUBQREYwMTIzNDU2Nzg5IDI NMyAwIG9iag08PA0vVHlwZSAU3VidHlwZSAvSW1hZ2UNL1d
                 - JVBERi0xLjMNJUBQREYwMTIzNDU2Nzg5IDI NMyAwIG9iag08PA0vVHlwZSAU3VidHlwZSAvSW1hZ2UNL1d
                 - JVBERi0xLjMNJUBQREYwMTIzNDU2Nzg5IDI NMyAwIG9iag08PA0vVHlwZSAU3VidHlwZSAvSW1hZ2UNL1d
                xml:
                  wrapped: true
                  name: attachments
components:
  schemas:
    attachements:
      type: object
      xml:
        name: attachements
      properties:
        auth:
          $ref: '#/components/schemas/auth'
        orderno:
          type: string
          example: "1234567"
      
    auth:
      type: object
      xml:
        name: auth
      properties:
        extra:
          type: string
          example: "8"
          xml:
            attribute: true
        login:
          type: string
          example: "test"
          xml:
            attribute: true
        pass:
          type: string
          example: "testm"
          xml:
            attribute: true
