openapi: 3.0.0
info:
  description: The Emory Student Mobile REST Service is an interface based RESTful web API.  It uses HTTP methods for operations and supports input and output in JSON and XML. It allows users to retrieve student profile information or obtain data of Emory news and events. 
  version: "1.0.0"
  title: Emory Student Mobile RESTful API - 1.0
  termsOfService: http://emory.edu
  contact: 
    name: Emory LITS Development and Integration
    url: rxing2@emory.edu
    email: richard.xing@emory.edu
servers:
  - url: http://dev-api.app.emory.edu/emory-mobile-rs/api/v1/studentmobile
    description: The development server for Emory Student Mobile RESTful API
tags:
  - name: students
    description: Access student profile by student ID.
    externalDocs:
      description: Find out more
      url: 'http://dev-api.app.emory.edu/emory-mobile-rs/api/v1/studentmobile/students/1'
  - name: events
    description: Access to Emory Calendar and Events sites
    externalDocs:
       description: The emory calendar and events
       url: 'http://dev-api.app.emory.edu/emory-mobile-rs/api/v1/studentmobile/events/1'
  - name: news
    description: Access to Emory news
    externalDocs:
      description: In addition to the main news feed page, there are over 30 feeds pages available on Emory, the newsid will be passed in as a parameter to generate a new 'feed' response.
      url: 'http://dev-api.app.emory.edu/emory-mobile-rs/api/v1/studentmobile/news/1'
paths:
  /news/{newsid}:
    get:
      tags:
        - news
      summary: Finds Emory news by category Id
      description: A newsid parameter is required to pass in. 
                   1. Academics 
                   2. Admissions
                   3. Around Campus
                   4. Art Culture
                   5. Athletics
                   6. Biology
                   7. Biomedicine
                   8. Campus
                   9. Campus Life
                   10.Chemistry  
                   11.Commencement
                   12.Emory College
                   13.Emory Healthcare
                   14.Financial Aid
                   15 Graduate School
                   16.Law
                   17.Libraries
                   18.Museums
                   19.Neuroscience
                   20.Nursing
                   21.Oxford College
                   22.Research
                   23.School Of Law
                   24.School Of Business
                   25.School Of Medicine
                   26.School of Nursing
                   27.School Of Public Health
                   28.School of Theology
                   29.Student Campus Life
                   30.University Announcement
                  
      operationId: getCascadeNewsJSON
      parameters:
        - name: newsid
          in: path
          description: newsid values that need to be considered  for filter
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/newsData'
        '503':
          description: Gateway Timeout
        '500':
          description: Server Error
        '400':
          description: Bad Requst
        '403':
          description: Forbidden
  /events/{eventid}:
    get:
      tags:
        - events
      summary: Finds Emory events by category Id. The parameter passed in the request will always be 1 for the request. 
      description: >-
        Will not accept Muliple tags. The response will return the calendar and events. 
      operationId: getTrumbaNewsJSON
      parameters:
        - name: eventid
          in: path
          description: Tags to filter by
          required: true
          explode: true
          schema:
            type: string
            items:
              type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/eventData'
        '503':
          description: Gateway Timeout
        '500':
          description: Server Error
        '400':
          description: Bad Requst
        '403':
          description: Forbidden
  /students/{studentid}:
    get:
      tags:
        - students
      summary: Finds Emory student profile information  by student Id. The parameter passed in the  request will always be 1 for the request. 
      description: >-
        Will not accept Muliple tags. The response will return the student profile for the specified student Id. 
      operationId: getStudentProfileJSON
      parameters:
        - name: studentid
          in: path
          description: Tags to filter by
          required: true
          explode: true
          schema:
            type: string
            items:
              type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/studentData'
        '503':
          description: Gateway Timeout
        '500':
          description: Server Error
        '400':
          description: Bad Requst
        '403':
          description: Forbidden
components:
  schemas:
    eventData:
      type: object
      properties:
        image:
          type: string
          description: The image link of the event
          example: https://www.trumba.com/images/trumba_logo_sm.gif
        lastBuildDate:
          type: string
          description: The latest date the feed was built
          example: '05 Nov 2019 16:26:45 GMT'
        link:
          type: string
          description: URL of the event link
          example: http://www.emory.edu/home/events/
        description:
          type: string
          description: Preferred name of the user
          example: Emory Events
        language:
          type: string
          description: language used with locale, for example 'fr-ca'
          example: en-us
        category:
          type: string
          description: event category
          example: Geoff
        feedmessage:
          type: array
          items:
            $ref: '#/components/schemas/feedmessage'
    feedmessage:
      type: object
      properties:
        author:
          type: string
          example: ''
        link:
          type: string
          description: The link for the event item
          example: http://www.emory.edu/home/events/?trumbaEmbed=view%3devent%26eventid%3d138630883
        description:
          type: string
          description: The description of the event item
          example: 'Tuesday, November 19, 2019, 12&nbsp;&ndash;&nbsp;2&nbsp;p.m.&nbsp;EST <br/><br/><img src=\"https://www.trumba.com/i/DgB8TcmwPatUwYeglh8dc6lX.png\" title=\"Therapy Dog Study Break\" alt=\"Therapy Dog Study Break\" width=\"200\" height=\"120\" /><br/><br/>Take a break from school stress and come visit with therapy dogs from Canine Assistants in the Science Commons! There is no need to make an appointment, just stop by!&#160; <br/><br/><b>More info<\/b>:&nbsp;<a href=\"https://www.canineassistants.org/faqs/\" target=\"_blank\" title=\"https://www.canineassistants.org/faqs/\">www.canineassistants.org&#8230;<\/a>'
        category:
          type: string
          description: The type of event
          example: '2019/11/19 (Tue)'
        title:
          type: string
          description: The title of the event
          example: Pharm Seminar - Edward Morgan, PhD
      description: The feed messages of the news
    newsData:
      type: object
      properties:
        copyright:
          type: string
          description: The copyright of the news
          example: ''
        pubDate:
          type: string
          description: The last day the news published
          example: Fri, 15 Nov 2019 03:28:05 -0500
        link:
          type: string
          description: Preferred name of the user
          example: http://feedproxy.google.com/~r/emory_Academics_news/~3/3jh_MC0tElI/campus.html
        title:
          type: string
          description: The description of the title
          example: Academics
        description:
          type: string
          description: The news description
          example: Academics news from the Emory News Center
        language:
          type: string
          description: The language and locacle
          example: en-US
        feedmessage:
          type: array
          items:
            $ref: '#/components/schemas/newsfeedmessage'
    newsfeedmessage:
      type: object
      properties:
        author:
          type: string
          example: ''
        link:
          type: string
          description: The news item 
          example: http://feedproxy.google.com/~r/emory_Academics_news/~3/WVbXq8Ewgi4/campus.html
        description:
          type: string
          description: The detailed news
          example: With experience honed as a writer for NBC's 'The Blacklist' and shows on Netflix and BBC America, creative writing professor T Cooper guides students in the highly collaborative craft of writing TV scripts.<img src=\"http://feeds.feedburner.com/~r/emory_Academics_news/~4/IpUkMCvVmUk\" height=\"1\" width=\"1\" alt=\"\"/>
        guid:
          type: string
          description: The guid
          example: https://news.emory.edu//stories/2019/10/er_one_emory_profile_acampora/campus.html
        title:
          type: string
          description: The title of the news
          example: 'One Emory: Investing in faculty'
      description: The feed messages of the news
    studentData:
      type: object
      properties:
        studentId:
          type: string
          description: The Id of the student 
          example: 000001
        term:
          type: string
          description: ''
          example: '5199'
        termDescr:
          type: string
          description: ''
          example: 'Fall 2019'
        academicCareer:
          type: string
          description: ''
          example: 'GNUR'
        institution:
          type: string
          description: ''
          example: 'Emory'
        preferredFirstName:
          type: string
          description: ''
          example: 'Jon'
        firstName:
          type: string
          description: ''
          example: 'Jonathan'
        lastName:
          type: string
          description: ''
          example: 'Smith'
        academicLevel:
          type: string
          description: ''
          example: 'Gradudate'
        role:
          type: string
          description: ''
          example: 'P000001'  
        pPid:
          type: string
          description: ''
          example: 'Gradudate'
        majorMinor:
          type: array
          items:
            $ref: '#/components/schemas/majormessage'
    majormessage:
      type: object
      properties:
        major:
          type: string
          example: 'Acute Care'
        description:
          type: string
          example: 'Adult/Gerontology Pri Care NP'
