openapi: 3.0.0
info:
  description: |
    CPM -Cost Per Mile.
    cpm report will generate at the end date+1day of the billboard. madatory - while onboarding the billboard in registry customer should provide the enddate considering this end date going to process the CPM.
    Rule CPM will always generate  enddate+1 day rest all days displaying as null.
    For Ex -
    Start Date of the billboard 19th end 20th 
    CPM will generate on 21st.
  version: "1.0.0"
  title: CPM Integration
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: rubiya@movingwalls.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/RubiyaKadarBasha/cpm/1.0.0

tags:
  - name: data/api/v3/rest/
    description: Everything about cpm
    externalDocs:
      description: Find out more
      url: 'https://docs.google.com/document/d/1OTvJEWQuir8o1qjTEjEQI1L1HeZNB7bsPe-DB5wg6ac/edit?ts=5ec20423#heading=h.fpav5h5qbki5'

paths:

  '/mad/campaign/{campaignId}/audience-overview/overall':
    get:
      tags:
        - data/api/v3/rest
      summary: Campaign Reach Card Request URL
      operationId: overall
      parameters:
        - name: campaignId
          in: path
          description: Following Campaign Reach overall end points required cpm
          required: true
          schema:
            type: integer
            format: int64
        - name: from_summary
          in: query
          description: Following Campaign Reach overall end points when from_summary=true that time only cpm is required 
          required: true
          schema:
            type: boolean
            
          
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignAudienceOverallSummary'

  '/mad/campaign/{campaignId}/location/{locationId}/audience-overview/overall':
    get:
      tags:
        - data/api/v3/rest
      summary: Top Sites Card Request URL
      operationId: location overall
      parameters:
        - name: campaignId
          in: path
          description: Following Campaign Reach overall end points required cpm
          required: true
          schema:
            type: integer
            format: int64
        - name: locationId
          in: path
          description: Following Campaign Reach overall end points required cpm
          required: true
          schema:
            type: integer
            format: int64
        - name: from_summary
          in: query
          description: Following Campaign Reach overall end points required cpm
          required: true
          schema:
            type: boolean
            
          
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationAudienceOverallSummary'
                
  '/mad/campaign/{campaignId}/location/{locationId}/audience-overview/by-day':
    get:
      tags:
        - data/api/v3/rest
      summary: Overview By The Day card Request URL
      operationId: location audience-overview by day
      parameters:
        - name: campaignId
          in: path
          description: Following Campaign Reach overall end points required cpm
          required: true
          schema:
            type: integer
            format: int64
        - name: locationId
          in: path
          description: Following Campaign Reach overall end points required cpm
          required: true
          schema:
            type: integer
            format: int64
        - name: startDate
          in: query
          description: Following Campaign Reach overall end points required cpm
          required: false
          schema:
            type: string
        - name: endDate
          in: query
          description: Following Campaign Reach overall end points required cpm
          required: false
          schema:
            type: string

        - name: sov
          in: query
          description: Following Campaign Reach overall end points required cpm
          required: true
          schema:
            type: boolean
            
          
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationAudienceOverviewCpmDailySummary'
                
  '/mad/campaign/{campaignId}/location/{locationId}/audience-overview/by-hour':
    get:
      tags:
        - data/api/v3/rest
      summary: Hourly Performance Card Request URL
      operationId: location audience-overview by hour
      parameters:
        - name: campaignId
          in: path
          description: Following Campaign Reach overall end points required cpm
          required: true
          schema:
            type: integer
            format: int64
        - name: locationId
          in: path
          description: Following Campaign Reach overall end points required cpm
          required: true
          schema:
            type: integer
            format: int64
        - name: sov
          in: query
          description: Following Campaign Reach overall end points required cpm
          required: true
          schema:
            type: boolean
            
          
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationAudienceOverviewCpmHourlySummary'

components:
  schemas:
    LocationAudienceOverviewCpmHourlySummary:
      type: object
      properties:
        locationId:
          type: string
        hourlySummary:
          type: array
          items:
            $ref: '#/components/schemas/HourlyReachDTO'
  
  
    LocationAudienceOverviewCpmDailySummary:
      type: object
      properties:
        locationId:
          type: string
        dailySummary:
          type: array
          items:
            $ref: '#/components/schemas/DailyReachDTO'


    CampaignAudienceOverallSummary:
      type: object
      properties:
        campaignId:
          type: string
        nonSpotBase:
          $ref: '#/components/schemas/NonSpotBase'
        spotBase:
          $ref: '#/components/schemas/SpotBase'

    LocationAudienceOverallSummary:
      type: object
      properties:
        locationId:
          type: string
        nonSpotBase:
          $ref: '#/components/schemas/NonSpotBase'
        spotBase:
          $ref: '#/components/schemas/SpotBase'

    NonSpotBase:
      type: object
      properties:
        cpm:
          type: number
          example: 45.99
        totalReach:
          type: integer
          format: int64
        actualReach:
          type: integer
          format: int64
        frequency:
          type: number
          example: 12.345
          
    DailyReachDTO:
      type: object
      properties:
        day:
          type: integer
          format: int32
        cpm:
          type: number
          example: 45.99
        totalReach:
          type: number
          example: 12.345
        actualReach:
          type: number
          example: 12.345
        frequency:
          type: number
          example: 12.345
          
    HourlyReachDTO:
      type: object
      properties:
        hour:
          type: integer
          format: int32
        cpm:
          type: number
          example: 45.99
        totalReach:
          type: number
          example: 12.345
        actualReach:
          type: number
          example: 12.345
        frequency:
          type: number
          example: 12.345

    SpotBase:
      type: object
      properties:
        cpm:
          type: number
          example: 45.99
        totalReach:
          type: integer
          format: int64
        actualReach:
          type: integer
          format: int64
        frequency:
          type: number
          example: 12.345
