openapi: 3.0.1
info:
  title: Axur Dataservices
  description: 'This is a sample server. You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). For this sample, you can use the api key `special-key` to test the authorization filters.'
  version: v1
servers:
- url: https://api.axur.io


tags:
- name: Hashcast
  description: Get


paths:
  /hashcast:
    get:
      tags:
      - Hashcast
      summary: Get leaks for all domains or a single domain
      description: Description...
      parameters:
      - name: domain
        in: query
        description: Domain
        required: false
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                      email:
                        type: string
                      password:
                        type: string
        400:
          description: Invalid domain
        204:
          description: No leaks found
        401:
          description: Access token is missing or invalid

      security:
      - bearerAuth: []


  /refresh-token:
    get:
      tags:
      - Refresh Token
      summary: Refresh expired JWT berer token
      description: Description...
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                    access_token:
                      type: string
                    token_type:
                      type: string
        401:
          description: Access token is missing or invalid
      security:
      - bearerAuth: []


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
