openapi: 3.0.1
info:
  title: API РОН для ЕХПД
  version: 1.0.0
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/tsdv/Ehpd/1.0.0
  - url: /api/ehpd
paths:
  /find/on:
    post:
      summary: Получение идентификатора объекта наблюдения      
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FindOnRequestModel'
        description: Массив сведений об объектах наблюдения 
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindOnResponseModel'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageModel'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageModel'
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageModel'

  /find/form:
    post:
      summary: Получение сведений по формах статистического наблюдения для ОН      
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdsRequestModel'
        description: Массив идентификаторов об объектов наблюдения 
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindFormResponseModel'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageModel'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageModel'
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageModel'

  /find/attribute:
    post:
      summary: Получение признаков по ОН
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdsRequestModel'
        description: Массив идентификаторов об объектов наблюдения 
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FindAttributeResponseModel'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageModel'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageModel'
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageModel'

  /form:
    post:
      summary: Получение данных о ПСД
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormFactRequestModel'
        description: Тип уведомления
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyModel'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageModel'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageModel'
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessageModel'                

components:
  schemas:  
  
    EmptyModel:
      type: object


    FindOnRequestModel:
      type: object
      required:
        - On
      properties:
        On:
          type: array
          items: { $ref: '#/components/schemas/OnRequestModel' }

    FindOnResponseModel:
      type: object
      required:
        - On
      properties:
        On:
          type: array
          items: { $ref: '#/components/schemas/OnResponseModel' }

    OnRequestModel:
      type: object
      required:
        - Okpo
        - Name
        - Year
      properties:
        Inn: 
          description: ИНН объекта наблюдения (далее – ОН),   по которому получена форма с первичными статистическими данными (далее – ПСД) от Министерств и ведомств федеральных органов исполнительной власти Российской Федерации, субъектов официального статистического учета (далее – ФОИВ)
          type: string
          example: "124567890"
        Okpo: 
          description: ОКПО ОН, по которому получена форма с ПСД от ФОИВ
          type: string
          example: "124567890"
        Name:
          description: Краткое наименование ОН, по которому получена форма с ПСД от ФОИВ
          type: string
          example: "ООО 'Ромашка'"
        Year:
          description: Год предоставления отчетности
          type: integer
          example: 2019       

    OnResponseModel:
      allOf:
        - $ref: "#/components/schemas/OnRequestModel"
        - type: object
      type: object
      required:        
        - FindResult
      properties:
        Id: 
          description: Идентификатор ОН в Реестре ОН
          type: string
          example: "124567890"
        FindResult: {$ref: '#/components/schemas/FindResultTypeModel'}

    IdsRequestModel:
      type: object
      required:
        - Id
      properties:
        Id:
          type: array
          description: Идентификатор ОН Реестр ОН
          items:
            type: string
            example: "123123123123"

    FindFormResponseModel:
      type: object
      required:
        - On
      properties:
        On:
          type: array
          items: { $ref: '#/components/schemas/FormResponseModel' }

    FormResponseModel:
      type: object
      required: 
       - Id
       - Result
      properties:
        Id: 
          description: Идентификатор ОН в Реестре ОН
          type: string
          example: "124567890"
        Form: 
          type: array
          items: { $ref: '#/components/schemas/FormModel' }
        Result: {$ref: '#/components/schemas/FindFormResultTypeModel'}
          
    FormModel:
      type: object
      description: Сведения по формам
      required: 
       - Idf
       - Index
       - Idp
       - Period
      properties:
        Idf: 
          description: Идентификатор формы в Реестре форм статистического наблюдения и статистических показателей
          type: string
          example: "124567890"
        Index: { $ref: '#/components/schemas/FormIndexModel' }
        Idp: 
          description: Код периодичности формы
          type: string
          example: "01"
        Period: { $ref: '#/components/schemas/FormPeriodModel' }

    FormIndexModel:
      type: object
      description: Сведения по формам
      required: 
       - Name
       - Code
      properties:
        Name: 
          description: Краткое наименование формы
          type: string
          example: "1-Предприятие"
        Code: 
          description: Шифр формы
          type: string
          example: "1-predpr"

    FormPeriodModel:
      type: object
      description: Сведения по формам
      required: 
       - Id
       - Year
      properties:
        Id: 
          description: Код отчетного периода
          type: string
          example: "124567890"
        Year: 
          description: Год 
          type: string
          example: "2019"


    FindAttributeResponseModel:
      type: object
      required:
        - On
      properties:
        On:
          type: array
          items: { $ref: '#/components/schemas/AttributeResponseModel' }          
    
    AttributeResponseModel:
      type: object
      required:
        - Result
      properties:
        Type:
          type: array
          items: { $ref: '#/components/schemas/AttributeTypeResponseModel' }          
        Result: {$ref: '#/components/schemas/FindAttributeResultTypeModel'}    

    AttributeTypeResponseModel:
      type: object
      required:
        - Id
        - Name
      properties:
        Id: 
          description: Идентификатор признака
          type: string
          example: "124567890"
        Name: 
          description: Наименование признака  
          type: string
          example: "2019"
    
    FormFactRequestModel:
      type: object
      required:
        - On
      properties:
        On:
          type: array
          items: { $ref: '#/components/schemas/FormFactOnModel' }          
      
    FormFactOnModel:
      type: object
      required:
        - Id
        - Form
      properties:
        Id:
          description: Идентификатор ОН Реестр ОН
          type: string
          example: "124567890"
        Form:
          type: array
          items: { $ref: '#/components/schemas/FormFactModel' }  

    FormFactModel:
      allOf:
        - $ref: "#/components/schemas/FormModel"
        - type: object
      type: object
      required:        
        - ZeroFlag
        - Organization
        - Date
      properties:
        ZeroFlag:
          description: Признак незаполненной формы или заполненной формы нулями
          type: boolean
          example: false
        Organization: {$ref: '#/components/schemas/OrganizationModel'}    
        Date:
          description: Дата и время предоставления ПСД в Единое хранилище первичных данных
          type: string
          format: datetime(iso8601)
          example: 20130225T182510+03
      
    OrganizationModel:
      description: Федеральный орган исполнительной власти (далее - ФОИВ), предоставивший форму
      type: object
      required: 
        - Name
        - Inn
        - Kpp
        - Okpo
      properties:
        Id:
          description: Идентификатор Реестра ФП
          type: string
          example: "124567890"
        Name:
          description: Наименование ФОИВ
          type: string
        Inn:
          description: ИНН ФОИВ
          type: string
        Kpp:
          description: КПП ФОИВ
          type: string
        Okpo:
          description: ОКПО ФОИВ
          type: string

    ErrorMessageModel:
      type: object
      
      properties:
        message:
          type: string

    FindResultTypeModel:
      type: string
      description: |
        Тип результата поиска:
        * **found** - ОН найден в  Реестре ОН
        * **notFound** - ОН не найден в Реестре ОН        
      example: found   
      enum:
        - found
        - notFound

    FindFormResultTypeModel:
      type: string
      description: |
        Тип результата поиска:
        * **found** - форма(ы) найдена
        * **notFound** - по ОН не найдено ни одной формы статистического наблюдения
      example: found
      enum:
        - found
        - notFound

    FindAttributeResultTypeModel:
      type: string
      description: |
        Тип результата поиска:
        * **found** - признак(и) передан
        * **notFound** - по ОН не найдено ни одного признака для обогащения
      example: found
      enum:
        - found
        - notFound
