openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:

# Added by API Auto Mocking Plugin
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/MyV-javeriana/bancoabc-transformacion/1.0.0
  - description: Servicios de consulta y pago 
    url: http://40.117.38.177:9578/bankabc/services
info:
  description: Servicios de pago y consulta de convenios banco abc
  version: "1.0.0"
  title: Servicio banco abc
  contact:
    email: ma-alcala@javeriana.edu.co
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: convenio
    description: Servicio donde se pueden realizar consultas y pagos de los convenios

paths:
  /consultpayment:
    get:
      tags:
        - convenio
      summary: Consulta de saldo a pagar
      operationId: consultpayment
      parameters:
        - in: query
          name: reference
          description: Referencia del convenio a consultar
          required: true
          schema:
            type: string
        
      responses:
        '200':
          description: Referencia encontrada
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/CheckPayRespModel'
        '400':
          description: Referencia no encontrada
  /payagreement:
    post:
      tags:
        - convenio
      summary: pagar convenio
      operationId: payagreement
      description: Pago de la referencia del convenio
      responses:
        '200':
          description: Factura pagada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PayAgreementRespModel'
        '400':
          description: 'Factura no encontrada'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PayAgreementReqModel'
        description: Mensaje para realizar pago de la referencia
      
components:
  schemas:
    CheckPayRespModel:
      type: object
      required:
        - totalPay
      properties:
        id:
          type: number
          example: 454554.555
    PayAgreementReqModel:
      type: object
      required:
        - reference
        - totalPay
      properties:
        reference:
          type: string
          example: 1235698
        totalPay:
          type: number
          example: 234.343
    PayAgreementRespModel:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: Factura Pagada Exitosamente
