openapi: 3.0.0
info:
  version: 3.0.0
  title: 通用版 Buyer API
  description: "提供給通用能Buyer的API，做為後台管理使用，加上權限管理用"

servers:
# Added by API Auto Mocking Plugin
  - url: https://beta2-api.dforcepro.com/buyer
    description: 開發站

tags:
  - name: box
    description: box權限相關API
    
paths:
  /v3/box/confirm:
    post:
      tags: [box]
      summary: 新增權限
      description: 新增不能直接加到permission。加入權限後要加上使用者的歷史清單10筆
      operationId: add-box-permission
      security:
        - ApiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 使用者email
                projectID:
                  type: string
                boxes:
                  type: array
                  items:
                    type: object
                    properties:
                      boxID:
                        type: string
                      permission:
                        type: string
                        description: 權限
                        enum: [buyer, classA, classB, project]
              example:
                email: ch.focke@gmail.com
                projectID: "5bddbe8d51c78d7f3ew5845d"
                boxes:
                  - boxID: "5bddbe8d51c78d7f3ef5845d"
                    permission: classA
                  - boxID: "5be5932551c78d7f3e5fcfcf"
                    permission: classA
      responses:
        '200':
          description: OK
        '400':
          description: 無效的輸入
        '500':
          description: 伺服器發生錯誤
    get:
      tags: [box]
      summary: 取得權限
      description: 列出權限清單
      operationId: list-box-permission
      security:
        - ApiKeyAuth: []
      parameters:
        - in: query
          name: projectid
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    email:
                      type: string
                      description: 使用者email
                    projectID:
                      type: string
                    boxes:
                      type: array
                      items:
                        type: object
                        properties:
                          boxID:
                            type: string
                          permission:
                            type: string
                            description: 權限
                            enum: [buyer, classA, classB, project]
              example:
                - id: "5bddbe8d51c78d7f3ef5845d"
                  email: ch.focke@gmail.com
                  projectID: "5bddbe8d51c78d7f3ew5845d"
                  boxes:
                    - boxID: "5bddbe8d51c78d7f3ef5845d"
                      permission: classA
                    - boxID: "5be5932551c78d7f3e5fcfcf"
                      permission: classA
                - id: "5bddbe8d51c78d7f3ef5845d"
                  email: ch.focke@gmail.com
                  projectID: "5bddbe8d51c78d7f3ew5845d"
                  boxes:
                    - boxID: "5bddbe8d51c78d7f3ef5845d"
                      permission: classA
                    - boxID: "5be5932551c78d7f3e5fcfcf"
                      permission: classA
        '204':
          description: 沒有資料
        '400':
          description: 無效的輸入
        '500':
          description: 伺服器發生錯誤
  /v3/box/confirm/{ID}:
    delete:
      tags: [box]
      summary: 刪除確認
      description: 刪除permission
      operationId: delete-box-permission
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: not found
        '500':
          description: 伺服器發生錯誤
  /v3/box/confirm/{ID}/_mail:
    post:
      tags: [box]
      summary: 新增權限
      description: 新增不能直接加到permission。加入權限後要加上使用者的歷史清單10筆
      operationId: mail-box-permission
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: not found
        '500':
          description: 伺服器發生錯誤
components:
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: Auth-Token  # name of the header, query parameter or cookie
