openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: Test
    url: https://fileupload_dev.wes.org/api/v2
  - description: Production
    url: https://euploads.wes.org/api/v2
info:
  description: WES file upload API
  version: "2.0"
  title: WES File Upload API
  contact:
    email: abaryah@wes.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

tags:
  - name: Authenticate
    description: Authenticate to interact with the API.
  - name: Upload
    description: File upload endpoint.
paths:
  /authenticate:
    post:
      tags:
        - Authenticate
      summary: Authenticate
      operationId: auth
      description: |
        Use the username and password you received from WES. If correct information is used, youd
        receive a JWT token, which you'd use to interect with rest of the APIs, for example: /file. Once you have the JWT token. It must be provided as authorization header.
      security: []
      requestBody:
        description: User Info
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfo'
      responses:
        '200':
          description: JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
        '401':
          description: Unauthorized (Username or password incorrect)
  /file/{refnumber}:
    post:
      tags:
        - Upload
      summary: Upload File
      operationId: uploadFileWithoutType
      description: Use this endpoint to upload a file. Type of the file and WES Reference number are both required.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: refnumber
          required: true
          schema:
            type: string
          description: WES Reference Number
      requestBody:
        description: file to be uploaded.
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fileName:
                  type: string
                  format: binary
      responses:
        '201':
          description: Created At
          headers:
            Location:
              schema:
                type: string
              description: URI to access the file information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileUploadResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                description: 'missing parameters/no file uploaded'
        '401':
          description: UnAuthorized
  /file/{refnumber}/{filetype}:
    post:
      tags:
        - Upload
      summary: Upload File
      operationId: uploadFileWithType
      description: Use this endpoint to upload a file. Type of the file and WES Reference number are both required.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: refnumber
          required: true
          schema:
            type: string
          description: WES Reference Number
        - in: path
          name: filetype
          allowEmptyValue: true
          required: true
          schema:
            type: string
          description: File type
      requestBody:
        description: file to be uploaded.
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fileName:
                  type: string
                  format: binary
      responses:
        '201':
          description: Created At
          headers:
            Location:
              schema:
                type: string
              description: URI to access the file information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileUploadResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                description: 'missing parameters/no file uploaded'
        '401':
          description: UnAuthorized
  /applicantinfo/{refNumber}:
    get:
      tags:
        - Applicant Info Verification
      summary: Get applicant information using WES Reference Number
      operationId: verifyApplicantInfo
      description: Use this endpoint to get back applicant's first name, last name and email address
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: refNumber
          required: true
          schema:
            type: integer
          description: WES Reference Number
      responses:
        '200':
          description: user information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicantInfo'
        '401':
          description: Unauthorized 
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    AuthToken:
      type: object
      properties:
        token:
          type: string
          example: shfs634867hjfldhg475hkdfjhgd455.df745ythjkdhfjkgh8997456jkdh9fghfg.34o853ydfhgkjdhgo4i5tjklgdfg
    ApplicantInfo:
      type: object
      properties:
        FirstName:
          type: string
        LastName:
          type: string
        Email:
          type: string
    UserInfo:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    FileUploadResponse:
      type: object
      properties:
        referenceNumber:
          type: string
          example: 12356433
        status:
          type: string
          example: Accepted
        fileName:
          type: string
          example: 12356433.pdf
        id: 
          type: integer
          example: 1625478268446
