openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/heaps926/Katie-Test/1.0.0
info:
  description: This API provides inventory data from the Answers Database
  version: "1.0.0"
  title: Answers Inventory API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: developers
    description: Operations available to all developers
paths:
  /inventory-metrics/{customerCode}:
    get:
      tags:
        - developers
      summary: returns inventory metrics for pharmacy
      operationId: inventoryMetrics
      description: This API gives metric inforation about a pharmacy's inventory for a given time period
      parameters:
        - $ref: '#/components/parameters/customerCode'
        - $ref: '#/components/parameters/firstMonth'
        - $ref: '#/components/parameters/lastMonth'
      responses:
        '200':
          description: metrics for specified customer and time range
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/InventoryMetrics'
        '401':
          description: Unauthorized
  /inventory-benchmarks/{customerCode}:
    get:
      tags:
        - developers
      summary: returns inventory benchmarks for pharmacy
      operationId: inventoryBenchmarks
      description: This API gives benchmark inforation about a pharmacy's inventory for a given time period
      parameters:
        - $ref: '#/components/parameters/customerCode'
        - $ref: '#/components/parameters/firstMonth'
        - $ref: '#/components/parameters/lastMonth'
      responses:
        '200':
          description: benchmarks for specified customer and time range
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/InventoryBenchmarks'
        '401':
          description: Unauthorized          
components:
  schemas:
    InventoryMetrics:
      type: object
      properties:
        monthnumber:
          type: number
          example: 9
        totalvalue:
          type: number
          example: 1806198.2724661455
        inventoryturns:
          type: number
          example: 50.9639062351198
        carrycost:
          type: number
          example: 494.84884177154669
        rxperhour:
          type: number
          example: 7.061111
        daysininventory:
          type: number
          example: 7.0
        totalfills:
          type: number
          example: 2542
        profit:
          type: number
          example: 892985.96000002231
        revenue:
          type: number
          example: 8563895.9100000225
    InventoryBenchmarks:
      type: object
      properties:
        monthnumber:
          type: number
          example: 9      
        bmPop:
          type: number
          example: 2      
        rankIRR:
          type: number
          example: 1.0      
        medianIRR:
          type: number
          example: 0.57396373135515621      
        starIRR:
          type: number
          example: 5.0      
        rankITT:
          type: number
          example: 1.0      
        medianITT:
          type: number
          example: 23.225491734490443      
        starITT:
          type: number
          example: 5.0      
        rankCCS:
          type: number
          example: 1.0      
        medianCCS:
          type: number
          example: 7.3979187438638041      
        starCCS:
          type: number
          example: 5.0     
        rankXHR:
          type: number
          example: 0.5      
        medianXHR:
          type: number
          example: 0.744444      
        starXHR:
          type: number
          example: 3.0      
        rankDII:
          type: number
          example: 1.0    
        medianDII:
          type: number
          example: 21.0     
        starDII:
          type: number
          example: 5.0     
        invrevratio:
          type: number
          example: 0.57396373135515621      
        inventoryturns:
          type: number
          example: 23.225491734490443      
        carrycost:
          type: number
          example: 7.3979187438638041     
        rxperhour:
          type: number
          example: 0.744444      
        daysininventory:
          type: number
          example: 21.0     
  parameters:
    customerCode:
      in: path
      name: customerCode
      description: numeric code that identifies the pharmacy
      required: true
      schema:
        type: string
    firstMonth:
      in: query
      name: firstMonth
      description: integer representing first month of desired date range
      required: true
      schema:
        type: integer
        format: int32
        minimum: 0
    lastMonth:
      in: query
      name: lastMonth
      description: integer representing last month of desired date range
      required: true
      schema:
        type: integer
        format: int32
        minimum: 0
        maximum: 5000
