openapi: 3.0.0
info:
  version: "1.2.1"
  title: MOST Device Data Push
  description: |
    MOST device push is a per customer defined webhook to receive device locations and sensor reading. Data is pushed in real time when device transmits data.
    
    ## Playback
    It is possible to playback messages from a specified point in time.
    
    Please contact [support](mailto:support@most.tech). 
    
    ## Security
    Optional Basic Auth header can be added to protect the endpoint.</br> 
    Please contact MOST to agree on preshared secrets
    
    ## Technical details
    The unique key for pushed messages will be `device_imei` and `location/measured_at`
    
    The consuming endpoint must handle
    - duplicate messages
    - out of order messages 
    

  contact:
    email: support@most.tech
security: 
  - {}
  - BasicAuth: []

paths:
  /customer_defined_end_point:
    post:
      summary: Location and sensor readings for device
      operationId: add_sensor_data
      responses:
        '200':
          description: 'Successful push'
        '403':
          description: 'Failed push'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/push_message'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    push_message:
      type: object
      required:
        - device_imei
        - data_type
        - data
      properties:
        device_imei:
          type: string
          example: '162950025449508'
        data_type:
          type: string
          description: Type of data, 'device' for sensor update
          example: 'device'
        data:
          $ref: '#/components/schemas/data'
    data:
      type: object
      properties:
        shipment:
          type: object
          properties:
            shipment_id:
              type: string
              example: "8b9fad20-ec7a-4825-9cb4-ef7f3af142a9"
            container_id:
              type: string
              example: 'TGHU759933045G1'
            company_name:
              type: string
              example: 'MOST Tech'
            personal_ref:
              type: string
              example: 'REF122'
        device:
          type: object
          required:
            - device_imei
          properties:
            device_imei:
              type: string
              example: '162950025449508'
            battery_voltage:
              type: integer
              description: Battery level in percent
              minimum: 0
              maximum: 100
              example: 63
        location:
          type: object
          required:
            - latitude
            - longitude
            - measured_at
          properties:
            measured_at:
              type: string
              format: date-time
              description: Timestamp in UTC when location was measured
              example: '2018-06-27T08:31:17Z'
            latitude:
              type: number
              format: double
              example: 22.5380565
            longitude:
              type: number
              format: double
              example: 113.940758
        sensor_readings:
          type: array
          items:
            type: object
            required:
              - measured_at
            minItems: 0
            properties:
              measured_at:
                type: string
                format: date-time
                description: Timestamp in UTC when sensor readings were measured
                example: '2018-06-27T08:31:17Z'
              temperature:
                type: number
                format: double
                description: Temperature in Celsius
                example: 10.4
              humidity:
                type: number
                format: double
                description: Relative humidity in percent
                minimum: 0
                example: 39.6
              luminosity:
                type: number
                format: double
                description: Luminosity in lux
                minimum: 0
                example: 155.8
              shock:
                type: number
                format: double
                description: Shock in g
                example: 1
              dew_point:
                type: number
                format: double
                description: Dew point as degree Celsius
                example: -2.73
servers:
- url: https://customer.address
- url: http://customer.address
