openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Sample API'
  description: 'arbitrary description'
servers:
  - url: https://api.example.com/v1

paths:
  /users/{userId}:
    get:
    
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user to return.
          schema:
            type: integer
       
      summary: Returns a user by ID.
      responses:
        '200':
          description: OK
          content:
            application/yaml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
          
        '400':
          description: The specified user ID is invalid (e.g. not a number)
        '404':
          description: A user with the specified ID was not found
