openapi: 3.0.0
servers:
- url: http://35.236.202.220:3000/v1
  description: Localhost
info:
  description: Servicios plataforma Jacoma
  version: "1.0.0"
  title: Jacoma Services
  contact:
    email: crm@jacoma.pe
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: auth
    description: Servicios para la autenticación
paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: Logearse en el sistema
      operationId: authLogin
      description: Logearse en el sistema
      responses:
        '200':
          description: 'Logeado con exito'
        '500':
          description: 'Errores de validación o un error en el endpoint'
        '401':
          description: 'El usuario ingresado no se encuentra en nuestra BD o la contraseña es incorrecta'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/authLogin'
        description: Logearse en el sistema
components:
  schemas:
    structuredResponse:
      type: object
      properties:
        response:
          properties:
            systemMessage:
              type: string
              description: 'Mensaje que enviara el backend'
            apiResponse:
              type: object
              description: 'Objeto que retorna el backend con informacion o objeto'
            requestValidate:
              type: boolean
              description: 'Si retorna true es decir que todo lo necesario ha sido validado, de lo contrario devolvera false dando un cambio al systemMessage volviendolo un objeto'
            statusCode:
              type: number
              description: 'Codigo de estado HTTP'
              
    authLogin:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: 'admin'
        password:
          type: string
          example: 'admin'
