openapi: 3.0.0
info:
  title: CaseWorx API
  description: CaseWorx API.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/anton.yaskou/CaseWorx/1.0.0
  description: SwaggerHub API Auto Mocking
security:
- password:
  - openid
  - profile
  - email
  apiKey: []
tags:
- name: Mandate
  description: This is Mandate Related Operation
- name: Document
  description: This is Document Related Operation
paths:
  /mandate:
    post:
      tags:
      - Mandate
      summary: Creates a Mandate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mandate'
        required: true
      responses:
        201:
          description: Mandate Successfully Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mandate'
      x-amazon-apigateway-integration:
        passthroughBehavior: when_no_match
        httpMethod: POST
        uri: http://testserverproxy.com/mandate
        responses:
          default:
            statusCode: "200"
        type: http
  /mandate/{mandateID}:
    get:
      tags:
      - Mandate
      summary: Get Mandate By ID
      description: Returns Mandate Information.
      parameters:
      - name: mandateID
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          x-disabled-for-amazon-gateway:
            example: 1
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mandate'
      x-amazon-apigateway-integration:
        passthroughBehavior: when_no_match
        httpMethod: GET
        uri: http://testserverproxy.com/mandate/{mandateID}
        requestParameters:
          integration.request.path.mandateID: method.request.path.mandateID
        responses:
          default:
            statusCode: "200"
        type: http
  /mandate/{mandateID}/document:
    post:
      tags:
      - Mandate
      - Document
      summary: Upload Document to the Mandate
      description: Returns The ID of the uploaded document.
      parameters:
      - name: mandateID
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          x-disabled-for-amazon-gateway:
            example: 1
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: OK
      x-amazon-apigateway-integration:
        passthroughBehavior: when_no_match
        httpMethod: POST
        uri: http://testserverproxy.com/mandate/{mandateID}/document
        requestParameters:
          integration.request.path.mandateID: method.request.path.mandateID
        responses:
          default:
            statusCode: "200"
        type: http
components:
  schemas:
    Mandate:
      required:
      - customerName
      - name
      - referenceNumber
      type: object
      properties:
        id:
          type: integer
          format: int64
          x-disabled-for-amazon-gateway:
            example: 1
        name:
          maxLength: 256
          type: string
          x-disabled-for-amazon-gateway:
            example: Franzen GmbH ./. Müller OHG
        referenceNumber:
          maxLength: 256
          type: string
          x-disabled-for-amazon-gateway:
            example: 291/18
        customerName:
          maxLength: 256
          type: string
          x-disabled-for-amazon-gateway:
            example: Franzen GmbH ./. Müller OHG
  parameters:
    MandateID:
      name: mandateID
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: integer
        format: int64
        x-disabled-for-amazon-gateway:
          example: 1
  securitySchemes:
    password:
      type: oauth2
      flows:
        password:
          tokenUrl: https://login.intelliconnect.inta.cch.com/as/token.oauth2
          scopes:
            openid: allows modifying resources
            profile: allows reading resources
            email: allows sharing emails
    apiKey:
      type: apiKey
      in: header
      name: X-API-KEY
x-aws-api-id: 75fiw1ws7e
