openapi: 3.0.0
info:
  description: This API returns balance for digital service
  version: "1.0.0-oas3"
  title: Get Digital Service Balance
  contact:
    email: gagan.s@appgallop.com
tags:
  - name: Customer
    description: Get Digital Service Balance
paths:
  /subscription/getServiceBalance:
    post:
      tags:
        - Customer
      responses:
        '200':
          description: success
        '401':
          description: unauthorized
        '500':
          description: internal server error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestBody'
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  schemas:
    requestBody:
      type: object
      properties: 
        digitalService:
          type: object
          properties:
            identifier:
              type: object
              required: 
                - value
              properties:
                value:
                  type: string
                  example: 'XXXXXXXX-3EFA-46D3-9781-9317XXXXXXXX'
                subCategory:
                  type: string
                  example: '1'
        channelId:
          type: string
          example: '31'
        agentCode:
          type: string
          example: '55018940'
servers:
  - url: https://api.appgallop.com/Appgallop-APICenter
