openapi: 3.0.0
info:
  description: This API returns List of Microsoft Support Topics.
  version: "1.0.0-oas3"
  title: Microsoft get Support Topics for PartnerCenter
  contact:
    email: gagan.s@appgallop.com
tags:
  - name: Customer
paths:
  /MicrosoftSupport/getTopics:
    post:
      parameters:
        - in: query
          name: id
          required: false
          description: get Support Topics for PartnerCenter
          schema:
            type: string
      tags:
        - Customer
      description: This API returns List of Microsoft Support Topics.
      responses:
        '200':
          description: success
        '401':
          description: unauthorized
        '500':
          description: internal server error
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes

servers:
  - url: https://api.appgallop.com/Appgallop-APICenter
