openapi: 3.0.0
info:
  description: List OneClub SKUs for partner and their purchase
  version: "1.0.0-oas3"
  title: Get Customer Pricebook
  contact:
    email: gagan.s@appgallop.com
tags:
  - name: Reseller
    description: Must pass the entity code of customer.
  - name: Customers
    description: >-
      No need for entity code. Authourization will be used to authenticate
      customer.
paths:
  /pricebook/get:
    post:
      tags:
        - Reseller
      summary: Authorization Bearer Token (JWT)
      description: Gets pricebook from appgallop to customer
      responses:
        '200':
          description: success
        '401':
          description: unauthorized
        '500':
          description: internal server error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pricebook'
        description: pricebook to add
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  schemas:
    pricebook:
      type: object
      properties:
        entity code:
          type: string
          example: 'CUST1234'
servers:
  - url: https://api.appgallop.com/Appgallop-APICenter
