openapi: 3.0.0
info:
  description: This API returns list of end customers of a partner.
  version: "1.0.0-oas3"
  title: List End Customers under partner
  contact:
    email: gagan.s@appgallop.com
tags:
  - name: End Customer
paths:
  /endcustomers/get:
    post:
      parameters:
        - in: query
          name: entity_code
          required: false
          schema:
            type: string
          description: entity Code of the reseller
      tags:
        - End Customer
      description: This API returns list of end customers of a partner.
      responses:
        '200':
          description: success
        '401':
          description: unauthorized
        '500':
          description: internal server error
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes


servers:
  - url: https://api.appgallop.com/Appgallop-APICenter
