openapi: 3.0.0
servers: 
  - url: https://fsdi-dev.auth0.com/oauth
info:
  description: This is the OAuth0 endpoint to generarte the Bearer Token, for the iQuatic endpoints
  version: "1.0.0"
  title: Client credentials
paths:  
  /token:
    post:
      summary: Obtain the bearer token for iQuatic endpoint authorization
      operationId: getClientCredentials
      description: Access to iQuatic dashboard, at the sidebar go to Setup and then Integrations. You will find many integrations (Madan, Metric, Jetfeeder), activate the integration that you need if it's already not, and then you will able to see two keys, Client ID and Client Secret, copy that both values and use it in the next endpoint

      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObtainTokenResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObtainToken'
components:
  schemas:
    ObtainToken:
      type: object
      required:
      - grant_type
      - client_id
      - client_secret
      - audience
      properties:
        grant_type:
          type: string
          description: The type of the credentials
          example: client_credentials
        client_id:
          type: string
          description: The id key that you obtain on integrations page on iQuatic
          example: "{CLIENT_ID}"
        client_secret:
          type: string
          description: The secret key that you obtain on integrations page on iQuatic
          example: "{CLIENT_SECRET}"
        audience:
          type: string
          description: The audience for the token
          enum:
          - https://iquatic-api
    ObtainTokenResponse:
      type: object
      properties:
        access_token:
          type: string
          description: The Bearer token that you can use in iQuatic endpoint invocations
        scope:
          type: string
          description: The scope in where the token could be used
        expires_in:
          type: string
          description: The duration of the token, commonly one day
        token_type:
          type: string
          description: The type of the token
