openapi: 3.0.1
info:
  title: Message Dispatcher
  description: 'This is a simple virtual agent service to handle messages.   '
  version: 1.0.0-alpha
servers:
  - url: 'https://localhost:3002/api'
tags:
  - name: authenticate
  - name: message
paths:
  /v1/authenticate:
    get:
      tags:
        - authenticate
      summary: Authenticate user to use API methods
      description: The returned token expires in 8 hours
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                jwt: >-
                  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        '400':
          description: Invalid Request
          content: {}
        '500':
          description: Internal Server Error
          content: {}
      security:
        - basicAuth: []
    post:
      tags:
        - authenticate
      summary: Authenticate user to use API methods
      description: The returned token expires in 8 hours
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                jwt: >-
                  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        '400':
          description: Invalid Request
          content: {}
        '500':
          description: Internal Server Error
          content: {}
      security:
        - basicAuth: []
  /v1/authenticate/jwt:
    get:
      tags:
        - authenticate
      summary: Create token without expiration for application use
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                jwt: >-
                  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        '400':
          description: Invalid Request
          content: {}
        '500':
          description: Internal Server Error
          content: {}
      security:
        - Bearer: []
    delete:
      tags:
        - authenticate
      summary: Disable token without expiration
      description: Disable token that was previously generated for the application
      responses:
        '200':
          description: Success
          content: {}
        '400':
          description: Invalid Request
          content: {}
        '500':
          description: Internal Server Error
          content: {}
      security:
        - Bearer: []
  '/v1/message/{apikey}':
    post:
      tags:
        - message
      summary: Send user input to a virtual agent and receive a response
      parameters:
        - name: apikey
          in: path
          description: ID of the virtual agent to call
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                input:
                  type: object
                  properties:
                    type:
                      type: string
                      enum:
                        - text
                    text:
                      type: string
                      example: Hello
                context:
                  type: object
                  properties: {}
                channel:
                  type: string
                  example: WEB
                  enum:
                    - PHONE
                    - APP
                    - WEB
                    - WHATSAPP
                    - SKYPE
                    - TEAMS
                    - SLACK
                customer:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    email:
                      type: string
                    phone:
                      type: string
                set_to_context:
                  type: object
                  properties: {}
        required: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                intents: []
                entities: []
                input:
                  type: text
                  text: Hello
                output:
                  generic:
                    - response_type: text
                      text: Hello! What can I do for you?
                  text:
                    - Hello! What can I do for you?
                  nodes_visited:
                    - node_8_1571762596267
                    - node_10_1571767513252
                    - Welcome
                  log_messages: []
                context:
                  channel: WEB
                  virtual_agent:
                    apikey: a96ec62f-773c-4e84-8be9-f9dbca9f83d0
                    master: false
                  customer: {}
                  attendance_id: '20191023000001'
                  conversation_id: 83a3db7b-f1a6-430f-be2e-e297904436a6
                  system:
                    initialized: true
                    dialog_stack:
                      - dialog_node: root
                    dialog_turn_counter: 1
                    dialog_request_counter: 1
                    _node_output_map:
                      Welcome:
                        '0':
                          - 0
                    branch_exited: true
                    branch_exited_reason: completed
        '400':
          description: Invalid Request
          content: {}
        '500':
          description: Internal Server Error
          content: {}
      security:
        - Bearer: []
      x-codegen-request-body-name: body
  '/v2/message/{apikey}':
    post:
      tags:
        - message
      summary: Send user input to a virtual agent and receive a response
      parameters:
        - name: apikey
          in: path
          description: ID of the virtual agent to call
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                input:
                  type: object
                  properties:
                    type:
                      type: string
                      enum:
                        - text
                    text:
                      type: string
                      example: Hello
                context:
                  type: object
                  properties: {}
                channel:
                  type: string
                  example: WEB
                  enum:
                    - PHONE
                    - APP
                    - WEB
                    - WHATSAPP
                    - SKYPE
                    - TEAMS
                    - SLACK
                customer:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    email:
                      type: string
                    phone:
                      type: string
                set_to_context:
                  type: object
                  properties: {}
        required: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                output:
                  generic:
                    - response_type: text
                      text: Hello! What can I do for you?
                  intents:
                    - intent: hello
                      confidence: 0.9270244216918946
                  entities: []
                context:
                  skills:
                    main skill:
                      user_defined:
                        channel: WEB
                        session_id: 2f193895-ede6-4a60-83af-925e80d2d193
                        virtual_agent:
                          apikey: a96ec62f-773c-4e84-8be9-f9dbca9f83d0
                          master: false
                        customer: {}
                        attendance_id: '20191023000001'
                      system: {}
                  global:
                    system:
                      turn_count: 1
        '400':
          description: Invalid Request
          content: {}
        '500':
          description: Internal Server Error
          content: {}
      security:
        - Bearer: []
      x-codegen-request-body-name: body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    Bearer:
      type: apiKey
      name: Authorization
      in: header
