openapi: 3.0.0
info:
  version: 'test'
  title: 'test'
  description: 'test'
paths: {}
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/agaria/test/test
