openapi: 3.0.0
# Added by Tangram Mocking 
servers:
  - description: Tangram API Mocking
    url: https://virtserver.swaggerhub.com/SwissRe-Life-Capital/tangram/1.0.0
info:
  description: Tangram Mock Services
  version: "1.0.0"
  title: Tangram API Mocking Services 
  contact:
    name: iptiQ Software Engineering Team
    email: support@iptiq.com
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
  - name: policies
    description: Operations available to policies operationa
paths:
  /policies/{policyId}:
    get:
      tags:
        - policies
      summary: get a policy
      description: |
        By passing in the appropriate options, you can search for
        available tangram policy      
      parameters:
      - in: path
        name: policyId
        required: true
        description: Policy ID to identify the policy to be retrieved
        schema:
            type: string     
      responses:
        "200":
          description: Policy object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Policy" 
        "500":
          $ref: "#/components/responses/InternalServerError"
        default:
          $ref: "#/components/responses/DefaultError"                
                
  /events/{eventId}:
    get:
      tags:
        - policies
      summary: get a event triggered by tangram
      description: |
        Simulates an policy event from tangram       
      parameters:
      - in: path
        name: eventId
        required: true
        description: Event ID to identify the policy to be retrieved 
        schema:
            type: string     
      responses:
        "200":
          description: Event object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        "500":
          $ref: "#/components/responses/InternalServerError"
        default:
          $ref: "#/components/responses/DefaultError"
                
components:
  responses:
    InternalServerError:
      description: Internal server error
      content:
        "*/*":
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Error"
    DefaultError:
      description: Unexpected error
      content:
        "*/*":
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Error"

  schemas:
    Policy:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          example: PolicyID123456    
        quotes:
          type: array
          items:
            $ref: '#/components/schemas/Quote'
        parties:
          type: array
          items:
            $ref: '#/components/schemas/Party' 
        unnamedBeneficiary:
          $ref: "#/components/schemas/Beneficiary"  
        paymentDetails:
          $ref: "#/components/schemas/PaymentDetails"          
        status:
          type: string
        acceptedQuoteId:
          type: string
        productId:
          type: string
        cancellationInformation:
          $ref: "#/components/schemas/CancellationInformation" 
          
    CancellationInformation:
      type: object
      required:
        - cancellationType
      properties:
        cancellationType:
          $ref: "#/components/schemas/CancellationType"
        cancellationReasons:
          type: array
          items:
            $ref: "#/components/schemas/CancellationReason"
    CancellationType:
      type: string
      enum:
        - NOT_PROCEEDED_WITH
        - CANCEL_FROM_INCEPTION
        - COOL_OFF
        - CUSTOMER_CANCELLATION
        - ADMIN_CANCELLATION
        - LAPSE
        - SURRENDER
        - CLAIM_DECLINED
    CancellationReason:
      type: string
      enum:
        - NOT_PROVIDED
        - BUYING_ANOTHER_POLICY_WITH_SAME_DISTRIBUTOR
        - SWITCHING_TO_A_COMPETITOR
        - ADMIN_ERROR
        - FAMILY_REASONS
        - ECONOMIC_REASONS
        - CHANGE_OF_MIND
        - COMPLIANCE
        - CLAIM_CFI
        - REINSTATEMENT_REJECTED
        - DEATH_CLAIM_REJECTED
        - INELIGIBLE_T_AND_C
        - CUSTOMER_CANCEL_POST_CLAIM_REJECTION
        - UNHAPPY_WITH_PRESALES_CUSTOMER_SERVICE
        - UNHAPPY_WITH_POST_SALES_CUSTOMER_SERVICE 
 
    PaymentDetails:
      type: object
      required:
        - occupationCode
        - accountDetails
        - premiumCollectionDetails
      properties:
        occupationCode:
          type: string
          example: 7895 Q
        accountDetails:
          $ref: "#/components/schemas/AccountDetails"
        premiumCollectionDetails:
          $ref: "#/components/schemas/PremiumCollectionDetails" 

    PremiumCollectionDetails:
      type: object
      required:
        - frequency
        - startDate
      properties:
        frequency:
          $ref: "#/components/schemas/FrequencyType"
        startDate:
          type: string
          format: date
          example: 2019-05-16
          
    FrequencyType:
      type: string
      example: MONTHLY
      enum:
        - MONTHLY
        - YEARLY          
    AccountDetails:
      type: object
      properties:
        paymentMethod:
          type: string
          example: DIRECT_DEBIT
          enum:
            - DIRECT_DEBIT
        accountHolderName:
          type: string
          example: Jack I
        iban:
          type: string
          example: DE89370400440532013000
        accountNumber:
          type: string
          description: UK only - numeric, between 6 and 11 digits
          example: "12345678"
        sortCode:
          type: string
          description: UK only - numeric 6 digits
          example: "123456"          
    Beneficiary:
      type: string
      enum:
        - SPOUSE
        - PARTNER
        - HEIRS
        - CHILDREN
        - SPOUSE_AND_CHILDREN
        - PARTNER_AND_CHILDREN   
    Party:
      type: object
      properties:
              id:
                type: string
              version:
                type: integer
              status:
                type: string
              roles:
                type: array
                items:
                  $ref: "#/components/schemas/Role"  
    Role:
      type: string
      example: OWNER
      description: The type of the role
      enum:
        - OWNER
        - PAYER
        - LIFE_ASSURED
        - ASSIGNEE
        - BENEFICIARY
        - TRUSTEE         
    Quote:
      type: array
      items:
            $ref: '#/components/schemas/QuoteResponse'   
   
    QuoteResponse:
        allOf:
        - $ref: "#/components/schemas/QuotePayload"
        - type: object
          properties:
            id:
              type: string
              description: The ID of the Quote - if the quote is not transient
            requestDate:
              type: string
              format: date
              description: Request date represents the virtual date when the activity was
                requested, which drives all time-dependent business rules
                (business process versions, product versions, tariff versions,
                etc.) and is set as the creation date per default.
            creationTime:
              type: string
              format: date-time
              description: Represents the time on which the activity is created and is
                calculated as the current date of the business transaction creation.
            creationDate:
              type: string
              format: date
              description: Represents the date on which the activity is created and is
                calculated as the current date of the business transaction creation.
            policyCalculationModel:
              type: object
            riskPremiums:
              type: array
              items:
                $ref: "#/components/schemas/RiskPremium"
    RiskPremium:
      type: object
      properties:
        benefit:
          type: string
          description: The benefit ID (or "TOTAL") for which these premiums have been
            calculated
        premiums:
          type: array
          items:
            $ref: "#/components/schemas/RiskPremiumResult"
    QuotePayload:
      type: object
      required:
        - channel
        - quoteDate
        - productId
        - effectiveDate
        - coverTerm
        - premiumTerm
        - premiumFrequency
      properties:
        channel:
          $ref: "#/components/schemas/ChannelType"
        quoteDate:
          type: string
          format: date
          description: Represents the date used for calculation of the technical age initial.
          example: "2019-08-30"
        type:
          $ref: "#/components/schemas/QuoteType"
        productId:
          type: string
          description: The ID of the product
        policyId:
          type: string
          description: The ID of the created policy, if this request is not marked as
            transient
        selectedBenefits:
          type: array
          description: A list with the selected benefits which will be included in the
            calculation
          items:
            $ref: "#/components/schemas/PolicyBenefitInput"
        baseCoverId:
          type: string
          example: "123"
          description: Instructs the Calculation Engine which benefit is the main Cover
        effectiveDate:
          type: string
          format: date
          description: Represents the date when the policy starts (yyyy-MM-dd)
          example: "2019-01-01"
        decreasingRundown:
          type: number
          format: double
          description: The percentage of Decreasing Rundown - a value from 0 to 100%
          example: 3
        premiumTerm:
          type: integer
          description: The length of the premium in months
          example: 10
        premiumType:
          $ref: "#/components/schemas/PremiumType"
        premiumFrequency:
          $ref: "#/components/schemas/PremiumFrequency"
        lowStartPercentage:
          type: number
          format: double
          description: The percentage of Low Start - a value from 0 to 100%
          example: 1
    QuoteType:
      type: string
      title: QuoteType
      description: "The type of the quote - it can be one of the values: QUICK_QUOTE,
        FULL_QUOTE"
      enum:
        - QUICK_QUOTE
        - FULL_QUOTE
    PremiumFrequency:
      type: string
      description: The premium frequency, describing the frequency of the payments once a
        policy is accepted
      enum:
        - YEARLY
        - MONTHLY
    PolicyBenefitInput:
      type: object
      properties:
        coverId:
          type: string
        coverTerm:
          type: integer
          description: The length of the cover in months
          example: 10
        coverType:
          $ref: "#/components/schemas/CoverType"
        sumAssured:
          type: number
          description: The sum assured input
          example: 100000
        lifeType:
          type: string
          description: defines how the covered event relates to the insured life/lives. eg
            single or first_event.
          example: SINGLE
          enum:
            - SINGLE
            - FIRST_EVENT
        lives:
          type: array
          items:
            $ref: "#/components/schemas/Life"
    PremiumType:
      type: string
      example: LOW_START
      description: "The type of the premium - it can be one of the values: LEVEL,
        LOW_START, NATURAL"
      enum:
        - LEVEL
        - LOW_START
        - NATURAL
    CoverType:
      type: string
      example: DECREASING
      description: "The type of the cover - it can be one of the values: LEVEL, INDEXING,
        DECREASING"
      enum:
        - LEVEL
        - INDEXING
        - DECREASING
    Life:
      type: object
      properties:
        birthdate:
          type: string
          format: date
          description: The birth date of the insured life (yyyy-MM-dd)
          example: "1984-01-01"
        smokerStatus:
          type: string
          description: The smoker status of the client
          example: Non-smoker
        permanentPercentageRating:
          type: number
          format: double
          description: The percentage of permanent rating - a value from 0 to 100%
          example: 50
        temporaryPercentageMonths:
          type: integer
          description: The number of Temporary Percentage Months
          example: 12
        temporaryPercentageRating:
          type: number
          format: double
          description: The Temporary Percentage Rating - a value from 0 to 100%
          example: 100
        permanentPerMileRating:
          type: number
          format: double
          description: The Permanent Per Mile Rating - a value from 0 to 100%
          example: 0.1
        temporaryPerMileMonths:
          type: integer
          description: The number of Temporary Per Mile Months
          example: 24
        temporaryPerMileRating:
          type: number
          format: double
          description: The Temporary Per Mile Rating - a value from 0 to 100%
          example: 0.2
    RiskPremiumResult:
      type: object
      properties:
        insuranceMonth:
          type: integer
        riskPremium:
          type: number
          format: double
    ChannelType:
      type: string
      description: The channel this Quote has been generated through
      example: ONLINE
      enum:
        - CALL_CENTRE
        - ONLINE
        - BROKER
        - BANK_ASSURANCE
        - AGGREGATOR
    Events:
      type: object
      properties:
        events:
          type: array
          items:
            $ref: "#/components/schemas/Event"

    Event:
      type: object
      required:
        - customerId
        - type
        - webHookId
        - eventType
      properties:
        id:
          readOnly: true
          type: string
        eventId:
          readOnly: true
          type: string
        customerId:
          type: string
        webHookId:
          type: string
        eventType:
          type: string
          example: CREATED_POLICY
        status:
          type: string
          readOnly: true
          enum:
            - SUCCESS
            - PENDING
            - FAILED
        date:
          type: string
          format: date-time
        attempt:
          type: integer
        payload:
          type: object
        error:
          readOnly: true
          type: string
        event:
          type: string
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        attributes:
          type: array
          items:
            $ref: "#/components/schemas/ErrorAttribute"
    ErrorAttribute:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
