openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/azhar-cograph/product-search-api/1.1.0
info:
  description: Product search API
  version: "1.1.0"
  title: Product Search API
  contact:
    email: you@your-company.com
tags:
  - name: users
    description: Operation available to site users
paths:
  /search_products:
    post:
      summary: Searches and retrieves products based on query keywords
      operationId: searchProducts
      description: Search for products in the database by passing in keywords which describe the product.  Multiple keywords will result in 'AND' query.  Note we are using POST instead of GET to return products.
      requestBody:
        description: pass single or multiple keywords as strings to find related products.
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/SearchKeywords'
            example: {query: [blue, jeans, skinny],
              start: 1,
              rows: 1
            }
      responses:
        '200':
          description: Return an array of products found.  If no products are found return an empty array. 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: Invalid parameter was specified in SearchKeyword parameters. Such as no object, no keyword or invalid json object being sent. 
        '500':
          description: If server error occured in the backend
components:
  schemas:
    SearchKeywords:
      type: object
      properties:
        query:
          type: array
          items:
            type: string
        start:
          description: When specified, the start parameter specifies an offset into a query’s result set and instructs Solr to begin displaying results from this offset
          type: integer
          format: int64
          minimum: 1
        rows:
          description: Use the rows parameter to paginate results from a query. The parameter specifies the maximum number of documents from the complete result set that Solr should return to the client at one time. The default value is 10. That is, by default, Solr returns 10 documents at a time in response to a query
          type: integer
          format: int64
          minimum: 1
      required:
        - query
    Product:
      type: object
      required:
        - id
        - title
        - manufacturer_id
        - manufacturer_name
        - url
        - category
        - digest
        - last_modified_at
        - score
      properties:
        id:
          type: string
        title:
          type: string
        manufacturer_id:
          type: string
        manufacturer_name:
          type: string
        url:
          type: string
          format: url
        category:
          type: string
        digest:
          type: string
        last_modified_at:
          type: string
          format: date-time
        score:
          type: number
          format: float
      example: { id: 101,
        title: "'UNIQLO | High Rise Skinny Flare Ankle Jeans (Standard Length 67cm) | WOMEN    (Ladies') | Official Online Store (Online Store)",
        manufacturer_id: "1",
        manufacturer_name: "UNIQLO",
        url: "https://www.uniqlo.com/us/en/men-ultra-stretch-skinny-fit-jeans-408490.html",
        category: "jeans",
        digest: "WOMEN ⁄ Jeans High Rise Skinny Flare Ankle Jeans (Standard Length 67cm) The flares and ankle length are clearly and lightly determined. It also has a high rise and looks like a leg length. ¥ 1,990 + consumption tax Item No ....",
        last_modified_at: "2019-07-21T17:32:28Z",
        score: 0.98 
      }
