openapi: 3.0.1
info:
  title: Get Rates
  description: 'This a rating Test Service '
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  - url: 'https://filler.io/v2'
  - url: 'http://filler.io/v2'
tags:
  - name: rate
    description: Request a Rate
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
paths:
  /rate:
    post:
      tags:
        - rate
      summary: Request a rate
      operationId: rate
      requestBody:
        description: rate request object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rateRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/rateRequest'
        required: true
      responses:
        '405':
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
components:
  schemas:
    rateRequest:
      type: object
      properties:
        referenceNumber:
          type: string
          example: S1235412
        quoteType:
          type: string
          description: Order Status
          enum:
            - TL
            - VPTL
        equipmentTypes:
          type: array
          xml:
            name: equipmentTypes
            wrapped: true
          items:
            type: string
            enum:
              - DRY_VAN
              - FLATBED
        weight:
          $ref: '#/components/schemas/weight'
        hazmat:
          type: boolean
          example: false
        stops:
          type: array
          minItems: 2
          xml:
            name: stops
            wrapped: true
          items:
            $ref: '#/components/schemas/stop'
        accessorials:
          type: array
          xml:
            name: accessorials
            wrapped: true
          items:
            type: string
            enum:
              - DUNN
              - ETRACK
      required:
        - shipmentType
        - equipmentTypes
        - weight
        - hazmat
        - stops
      xml:
        name: rateRequest
    weight:
      type: object
      properties:
        amount:
          type: number
          format: double
          example: 40000
        unit:
          type: string
          enum:
            - LB
            - KG
      required:
        - amount
        - unit
      xml:
        name: weight
    stop:
      type: object
      properties:
        sequenceNumber:
          type: integer
          example: 1
        stopType:
          type: string
          enum:
            - PICK
            - DROP
        loadType:
          type: string
          enum:
            - LIVE
            - DROPTRAILER
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        address:
          $ref: '#/components/schemas/address'
      required:
        - sequenceNumber
        - stopType
        - loadType
        - startTime
      xml:
        name: stop
    address:
      type: object
      properties:
        locationName:
          type: string
          example: 1233 co
        locationCode:
          type: string
          example: '3120'
        addressOne:
          type: string
          example: 3665 North Harbor Drive
        addressTwo:
          type: string
          example: Suite 1
        city:
          type: string
          example: San Diego
        state:
          type: string
          example: CA
        postalCode:
          type: string
          example: '92101'
        country:
          type: string
          example: US
      required:
        - postalCode
        - country
      xml:
        name: address
