openapi: 3.0.0
servers:
- description: Local Server
  url: http://localhost:8080
info:
  description: |
    With Lindenbaum Cognitive Voice API you can easily do things like building your voicebots,
      which can be reached via phone calls. You can receive speech input of the caller as
      transcripted text in many languages. Let different voices say your text in this call.
      After the voicebot dialog you may drop the call (call fully completed by bot) or transfer
      the call e.g. to the relevant service hotline (human agent required to satisfy caller).


      Find documentation about the API provided on our site below voice endpoints.


      By some events, such as receiving an incoming phone call or transcription of a callers
      utterance, Lindenbaum make an HTTP request to an URL to be provided by you. This is called
      a webhook. To handle a webhook, you need to build a small web application that can accept
      the HTTP requests. The required webhooks are listed as bot endpoints.
  version: 1.0.13
  title: Lindenbaum Cognitive Voice Core API
  contact:
    email: cvp@lindenbaum.eu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
- name: voice
  description: endpoints related to voice and call operations
security:
- OAuth2: []
paths:
  /call/say:
    post:
      tags:
      - voice
      summary: Say something to the call
      operationId: say
      description: Say something to the call
      responses:
        '204':
          description: Operation successful
        '400':
          description: Bad request
        '413':
          description: Text is longer than 10,000 characters
      requestBody:
        description: Parameters for the say operation. Use SSML tags to customize
          and control aspects of speech such as pronounciation, volume, and speech
          rate. When using SSML enclose the entire text in a < speak > tag.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SayParameters'
  /call/play:
    post:
      tags:
      - voice
      summary: Play something to the call
      operationId: play
      description: Play something to the call
      responses:
        '204':
          description: Operation successful
        '400':
          description: Bad request
      requestBody:
        description: Parameters for the play operation.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayParameters'
  /call/bridge:
    post:
      tags:
      - voice
      summary: Bridge the call to a different destination
      operationId: bridge
      description: Bridge the call to a different destination. The bot is now out
        of the loop and will neither receive further messages nor can send any commands.
      responses:
        '204':
          description: Operation successful
        '400':
          description: Bad request
      requestBody:
        description: Parameters for the bridge operation
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BridgeParameters'
  /call/forward:
    post:
      tags:
      - voice
      summary: Forward the call to a different destination
      operationId: forward
      description: Forward the call to a different destination. The bot is now out
        of the loop and will neither receive further messages nor can send any commands.
      responses:
        '204':
          description: Operation successful
        '400':
          description: Bad request
      requestBody:
        description: Parameters for the forward operation
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForwardParameters'
  /call/drop:
    post:
      tags:
      - voice
      summary: Drop the call
      operationId: drop
      description: Drop the call
      responses:
        '204':
          description: Operation successful
        '400':
          description: Bad request
      requestBody:
        description: Parameters for the drop operation
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DropParameters'
  /call/data:
    post:
      tags:
      - voice
      summary: Send non-audio data to the call
      operationId: data
      description: Send non-audio data to the call
      responses:
        '204':
          description: Operation successful
        '400':
          description: Bad request
      requestBody:
        description: Parameters for the data operation
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataParameters'
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://example.com/oauth/auth
          scopes: {}
  schemas:
    SayParameters:
      type: object
      required:
      - dialogId
      - text
      - language
      properties:
        dialogId:
          type: string
          format: uuid
          example: 09e59647-5c77-4c02-a1c5-7fb2b47060f1
        text:
          type: string
          description: The text to be synthesized. The text must not consist solely
            of whitespace.
          example: <speak><prosody rate="125%">Hello!</prosody><speak>
        language:
          $ref: '#/components/schemas/language'
        bargeIn:
          type: boolean
          default: false
    PlayParameters:
      type: object
      required:
      - dialogId
      - url
      properties:
        dialogId:
          type: string
          format: uuid
          example: 09e59647-5c77-4c02-a1c5-7fb2b47060f1
        url:
          type: string
          example: http://public.com/audio.wav
        bargeIn:
          type: boolean
          default: false
    BridgeParameters:
      type: object
      required:
      - dialogId
      - headNumber
      properties:
        dialogId:
          type: string
          format: uuid
          example: 09e59647-5c77-4c02-a1c5-7fb2b47060f1
        headNumber:
          type: string
          description: The head number of the system to bridge to. The head number
            will be augmented by an extension before doing the bridge call.
          example: '+49721123456789'
        extensionLength:
          type: integer
          format: int32
          minimum: 0
          maximum: 12
          default: 3
          description: The number of digits for the generated extension to the head
            number. The length of the head number plus the length of the extension
            must result in a valid phone number (no more than 15 digits).
    ForwardParameters:
      type: object
      required:
      - dialogId
      - destinationNumber
      properties:
        dialogId:
          type: string
          format: uuid
          example: 09e59647-5c77-4c02-a1c5-7fb2b47060f1
        destinationNumber:
          type: string
          description: The destination number of the system to forward to.
          example: '+49721123456789'
    DropParameters:
      type: object
      required:
      - dialogId
      properties:
        dialogId:
          type: string
          format: uuid
          example: 09e59647-5c77-4c02-a1c5-7fb2b47060f1
    DataParameters:
      type: object
      required:
      - dialogId
      - key
      - value
      properties:
        dialogId:
          type: string
          format: uuid
          example: 09e59647-5c77-4c02-a1c5-7fb2b47060f1
        key:
          type: string
          example: sentiment
        value:
          type: string
          example: neutral
    language:
      type: string
      enum:
      - ar-SA
      - bg-BG
      - ca-ES
      - cs-CZ
      - da-DK
      - de-DE
      - el-GR
      - en-GB
      - en-US
      - es-ES
      - es-US
      - fi-FI
      - fr-CA
      - fr-FR
      - he-IL
      - hi-IN
      - hr-HR
      - hu-HU
      - it-IT
      - ja-JP
      - ko-KR
      - nb-NO
      - nl-NL
      - pl-PL
      - pt-BR
      - pt-PT
      - ro-RO
      - ru-RU
      - sk-SK
      - sl-SI
      - sr-RS
      - th-TH
      - yue-Hant-HK
      - zh-HK
      - zh-TW
      - zh
      example: de-DE
