openapi: 3.0.0
servers:
  - description: CQuentia FHIR API
    url: https://lab.cquentia.io/api/v1/FHIR
info:
  version: "1.0.1"
  title: CQuentia FHIR API
  description: >-
    This is the CQuentia FHIR api used to access and retrieve FHIR bundles
security:
  - password:
      - read
      - write
paths:
  /Authenticate:
    get:
      tags:
        - Authentication
      summary: Retrieve a token for api use
      description: >-
        Performing this call allows you to receive an access token to use with 
        subsqueunt protected routes. Use Basic auth.
      responses:
        '401':
          description: Invalid Login
        '200':
          description: OK
      security: 
        - Basic:
          - read          
  /DiagnosticReport:
    get:
      tags: 
        - Report
      summary: Retrieve 1 diagnostic report
      description: >-
        Performing this call will return a diagnostic report for a single
        barcode or patient.
      parameters: 
        - in: query
          name: patient.identifier
          schema:
            type: string
          description: The identifier for the patient (MRN Number)
        - in: query
          name: specimen.identifier
          schema:
            type: string
          description: The identifier for the barcode 
      security: 
        - Bearer:
          - read
      responses:
        '200':
          description: OK
        '404':
          description: Report not found

components:
  schemas: {}
  securitySchemes:
    Basic:
      type: http
      scheme: basic
    Bearer:
      type: http
      scheme: bearer
