openapi: 3.0.0
info:
  description: This is the documentation for VOP interface.
  version: "1.0.0"
  title: VOP interface
  contact:
    email: support@wayzz.fr

tags:
- name: Invoice

paths:
  /vop/society/{id}/booking-invoice:
    get:
      tags:
        - Invoice
      summary: "Get society invoices"
      description: ""
      security: 
        - BasicAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: "The society id"
        - in: query
          name: page
          schema:
            type: integer
          description: The page number
        - in: query
          name: pageSize
          schema:
            type: integer
          description: The page size
      responses:
        '200':
          description: "A list of BookingInvoice"
          content:
            appliction/json:
              schema:
                $ref: '#/components/schemas/BookingInvoice'
  
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    BookingInvoice:
      type: object
      properties:
        IdInvoice:
          type: integer
        InvoiceNumber:
          type: string
        IdSociety:
          type: integer
        IdAccount:
          type: integer
        IdBooking:
          type: integer
        IdEntreprise:
          type: integer
        InvoiceStatus:
          type: integer
        PaymentStatus:
          type: integer
        ISOBillingDate:
          type: string
          format : datetime
        ISOGenerationDate:
          type: string
          format : datetime
        InvoiceFields:
          type: array
          items:
            $ref: '#/components/schemas/BookingInvoiceField'
      format: array
      
    BookingInvoiceField:
      type: object
      properties:
        IdInvoiceField:
          type: integer
        ExcludingTaxes:
          type: number
        VAT:
          type: number
        IncludingTaxes:
          type: number
        Title:
          type: string
      
servers:
  - url: 'http://modulauto.homedns.org:8080/WS/MI_GALAGO/REST'
