openapi: 3.0.0
servers: 
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/interzoid/email_validation/1.0.0
  - url: https://api.interzoid.com
info:
  version: "1.0.0"
  title: Interzoid Get Email Information API
  description: This API provides validation information for email addresses to aid in deliverability. Syntax, existence of mail servers, and other tests are run to ensure delivery. Additional demographics are provided for the email address as well, including identifying generic, vulgar, education, government, or other entity type email addresses.
  contact:
    name: API Support
    email: support@interzoid.com
    url: https://www.interzoid.com
  termsOfService: https://www.interzoid.com/terms
  license:
    name: Interzoid license
    url: 'https://www.interzoid.com/license'
externalDocs:
  description: API home page and documentation
  url: https://www.interzoid.com/services/getemailinfo
paths:
  /getemailinfo:
    get:
      tags:
        - Email Address Information
      summary: Gets email validation information for an email address
      operationId: getemailinfo
      description: |
        Get email validation information and other demographics for an email address
      parameters:
        - in: query
          name: license
          description: Your Interzoid license API key. Register at www.interzoid.com/register
          required: true
          schema:
            type: string
        - in: query
          name: email
          description: Email address to retrieve validation information
          required: true
          schema:
            type: string  
      responses:
        '200':
          description: Email validation and demographic information
          content:
            application/json:
              schema:
                type: object
                properties:
                  Email:
                    type: string
                  Response:
                    type: string
                  Info:
                    type: string
                  IsGovernment:
                    type: string
                  IsEducational:
                    type: string
                  IsOrganizational:
                    type: string
                  IsVulgar:
                    type: string
                  IsGeneric:
                    type: string
                  Geolocation:
                    type: string
                  Code:
                    type: string
                  Credits:
                    type: string
        '400':
          description: bad request - insufficient parameters
        '402':
          description: credits exhausted
        '403':
          description: invalid license API key
        '404':
          description: email address not valid
        '405':
          description: method not allowed
        '500':
          description: internal server error
