openapi: 3.0.0
servers: 
  - url: https://api.interzoid.com
info:
  version: "1.0.0"
  title: Interzoid Country Data Standardization API
  description: This API provides a standard for country name for the purposes of standardizing country name data, improving query results, analytics, and data merging.
  contact:
    name: API Support
    email: support@interzoid.com
    url: https://www.interzoid.com
  termsOfService: https://www.interzoid.com/terms
  license:
    name: Interzoid license
    url: 'https://www.interzoid.com/license'
externalDocs:
  description: API home page and documentation
  url: https://www.interzoid.com/services/getcountrystandard
paths:
  /getcountrystandard:
    get:
      tags:
        - Country Name Standardization
      summary: Gets country name standard
      operationId: getcountrystandard
      description: |
         Gets a pre-selected country name standard for various permutations of a given country name.
      parameters:
        - in: query
          name: license
          description: Your Interzoid license API key. Register at www.interzoid.com/register
          required: true
          schema:
            type: string
        - in: query
          name: country
          description: Country name from which to retrieve the standardized version
          required: true
          schema:
            type: string  
      responses:
        '200':
          description: Standardized country name data
          content:
            application/json:
              schema:
                type: object
                properties:
                  CountryStandard:
                    type: string
                  Code:
                    type: string
                  Credits:
                    type: string
                    
        '400':
          description: bad request - insufficient parameters
        '402':
          description: credits exhausted
        '403':
          description: invalid license API key
        '405':
          description: method not allowed
        '500':
          description: internal server error
