openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
   - url: https://virtserver.swaggerhub.com/T36388/parking-api/1.0.0
info:
  version: "1.0.0"
  title: Макет API для приема данных о платежах (парковка)
  description: "Это просто пример. Шлюз ТТС может отправлять любые другие запросы в любом формате. "
paths:
  /check:
    get:
      summary: Проверка данных перед платежом. 
      parameters:
        - name: carNumber
          in: query
          required: true
          description: Госномер автомобиля.
          schema:
            type: string
        - name: parkingNumber
          in: query
          required: true
          description: Номер парковки.
          schema:
            type: string
        - name: parkingStartTime
          in: query
          required: true
          description: Время начала парковки.
          schema:
            type: string
        - name: parkingEndTime
          in: query
          required: true
          description: Время конца парковки.
          schema:
            type: string
      responses: 
        '200': 
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckItem'
        '500': 
          description: Внутренняя ошибка сервера
  /payment:
    post:
      summary: Отправка данных о платеже.
      operationId: SendPayment
      description: Adds an item to the system
      responses:
        '201':
          description: Платеж успешно создан.
        '500':
          description: Внутренняя ошибка сервера.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentItem'
        description: Данные о платеже
components:
  schemas:
    CheckItem:
      type: object
      required:
        - description
      properties:
        description:
          type: string
          example: 'Госномер: о123аа072. Время: 11:00. Рекомендуемая сумма для пополнения 1100,75 рублей.'
    PaymentItem:
      type: object
      required:
        - paymentId
        - paymentDate
        - carNumber
        - parkingNumber
        - parkingStartTime
        - parkingEndTime
        - amount
      properties:
        paymentId:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        paymentDate:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        carNumber:
          type: string
          example: 'а007аа072'
        parkingNumber:
          type: integer
          example: 1
        parkingStartTime:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        parkingEndTime:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
