openapi: 3.0.0
servers:
  - url: https://auth.equityeng.com/service/api/ApiToken
info:
  description: Get Bearer Token from API Access Token
  version: "1.0.0"
  title: Api Access Token
  contact:
    email: tblue@e2g.com
tags:
  - name: public
    description: Not Secured
paths:
  /GetApiAccessToken:
    get:
      tags:
        - public
      summary: Retrieve Bearer Token
      operationId: GetApiAccessToken
      description: |
        Pass in a Bearer Token by passing in an API Access Token
      parameters:
        - in: query
          name: token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: string
