openapi: 3.0.0
info:
  title: 'Ambev PO7.5 PortalB2B Integration'
  version: "1.1.0-oas3"  
  description: |
    Ambev Zeus: PortalB2B Integration
    Methods:
      <br>• Order Create
      <br>• Order Consult (unavailable)
      <br>• Order Cancellation (unavailable)
      <br>• Notification Consult (unavailable)
      <br>• Product Consult (unavailable)
      <br>• Branch Consult (unavailable)
      
      1.1.0-oas3 :
      <br>&nbsp;&nbsp;&nbsp;&nbsp;• Structure postOrder_res
      <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Whole structure was updated, requested by WebJump team.
      
      1.0.0-oas3 : 
      <br>&nbsp;&nbsp;&nbsp;&nbsp;• Creation of Interface []Order Create]
  termsOfService: http://swagger.io/terms/
  contact:
    name: Partner evt/IT
    email: contato@evtit.com
    url: http://www.evtit.com/
#  license:
#    name: Apache 2.0
#    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: 'Developer: Daniel G. Alexandre'
  url: 'mailto:daniel.dgatech@gmail.com'
servers:
- url: https://sappodev.ambevdevs.com.br/RESTAdapter
  description: SAP PO Development server (DP1) - External URL
- url: https://sappoqas.ambevdevs.com.br/RESTAdapter
  description: SAP PO Quality server (QP1) - External URL
- url: https://sappoprd.ambevdevs.com.br/RESTAdapter
  description: SAP PO Production server (PP1) - External URL
tags:
- name: PortalB2B
  description: Everything about PortalB2B integration for Ambev
paths:
  /v1/PortalB2B/postOrder:
    post:
      tags:
      - PortalB2B
      summary: Create Order at SAP
      operationId: b2bPortalPostOrder_OB_Sync
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postOrder_req'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/postOrder_res'
        400:
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/postOrder_exc'
      security:
      - po75_auth: []
components:
  schemas:
    postOrder_req:
      title: postOrder_req
      type: object
      properties:
        cgcCliente:
          type: string
          description: Client Number identification (CGC)
        numPedidoEDI:
          type: number
          description: Order Number
        dataPuxadaCarro:
          type: string
          description: Delivery Date
          format: date
        dataValidadePedido:
          type: string
          description: Expiration Date
          format: date
        itens:
          type: object
          properties:
            item:
              type: array
              items:
                type: object
                properties:
                  codProduto:
                    type: integer
                    description: Product Code
                  qtdProdutoAS:
                    type: integer
                    description: Product Quantity
                required:
                - codProduto
                - qtdProdutoAS
          required:
          - numPedidoEDI
          - dataPuxadaCarro
          - dataValidadePedido
      xml:
        name: postOrder_req
    postOrder_res:
      title: postOrder_res
      type: object
      properties:
        statusCode:
          type: string
        error:
          type: string
        success:
          type: string
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              msg:
                 type: string
              param:
                type: string
              location:
                type: string
      xml:
        name: postOrder_res
    postOrder_exc:
      type: object
      properties:
        standard:
          $ref: '#/components/schemas/auxException'
      xml:
        name: postOrder_exc
    auxException:
      properties:
        faultText:
          type: string
        faultUrl:
          type: string
        faultDetail:
          type: array
          items:
            type: object
            properties:
              severity:
                 type: string
              text:
                type: string
              url:
                type: string
              id:
                type: string
  securitySchemes:
    po75_auth:
      type: http
      scheme: basic
    api_key:
      type: apiKey
      name: api_key
      in: header
