openapi: 3.0.0
info:
  version: "10.2.1"
  title: IDCardsList
  description: Common IDCardsList API
paths:
  /id-cards/:
    get:
      tags:
      - id cards
      summary: Get Digital ID Cards associated with Members (can be used for multiple members)
      description: |
        Returns a list of ID Card objects with ids for the front, back images of the id card and the details of the members.The ids in the response is used by the documents/{id} call to stream the document as pdf or image.
      operationId: idcards_list
      parameters:
      - name: member_id
        in: query
        description: member id to retrieve associated id card and can be a list of member ids
        example:
          "member_id=1&member_id=2&member_id=3"
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: policy_id
        in: query
        description: unique policy id and can be a list of policy ids
        example:
          "policy_id=1&policy_id=2&policy_id=3"
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: effective_date
        in: query
        description: effective date of the ID Card, typically this will align with the coverage period for the ID Card
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: termination_date
        in: query
        description: termination date of the ID Card
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: member_coverage_id
        in: query
        description: Member Coverage ID identifying ID Card for a specific Member's coverage type i.e. Medical, Dental etc. This parameter can be used to indicate multiple members and multiple coverages.
        example:
          "member_coverage_id=1&member_coverage_id=2&member_coverage_id=3"
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                required:
                  - results
                type: object
                properties:
                  count:
                    type: integer
                    description: Count representing the total number of objects available to be returned in the results array
                  next:
                    type: integer
                    description: query identifier defined by the api developer for getting the next set of records
                  previous:
                    type: integer
                    description: query identifier defined by the api developer for getting the previous set of records
                  results:
                    type: array
                    items:
                      $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/IDCardModel/10.2.1#/components/schemas/IDCard'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/ErrorModel/10.0.2#/components/schemas/Error'
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/ErrorModel/10.0.2#/components/schemas/Error'
