openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'sampleAPI'
  description: ''
  
servers:
  - url: http://52.35.172.159:8084/api/broker/
  
paths:
  /GetPlans/{Key}:
    get:
      summary: Returns a user by ID
      parameters:
        - name: Key
          in: path
          required: true
          description: The ID of the user to return
          schema:
            type: integer
      responses:
        '200':
          description: OK
