openapi: 3.0.0
info:
  title: Students in rooms API
  description: Collection of documentation of how to use students in rooms.
  version: "1.0.0-oas3"
servers:
  - url: https://github.com/Dalalaler/leverx_day_4
    description: GitHub repository url of project
tags:
- name: students
  description: Everything about students
  externalDocs:
    description: Show everything about students
    url: http://example.com/students
- name: rooms
  description: Show everything about rooms
  externalDocs:
    description: Find out more
    url: http://example.com/rooms
- name: students in rooms
  description: Show students and theirs rooms
  externalDocs:
    description: Find out more
    url: http://example.com/studentsinrooms
# schemes:
# - http
paths:
  /students/post:
    post:
      tags:
      - students
      summary: Add new students into database.
      description: Accept a json file with a list of new students
      responses:
        default:
          description: Unexpected error
        '400':
          description: Invalid record parameters(name or type of columns).
        '201':    # status code
          description: A JSON array of students information
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
      
  /students/get:
    get:
      tags:
      - students
      summary: Returns a list of students
      description: Accept a sample query
      responses:
        '400':
          description: Invalid record parameters(name or type of columns).
        default:
          description: Unexpected error  
        '202':    # status code
          description: A JSON array of students information
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string  
  /students/put:
    put:
      tags:
      - students
      summary: Update information about students.
      description: Find a necessary students and change theirs information.
      responses:
        default:
          description: Unexpected error
        '400':
          description: Invalid record parameters(name or type of columns).
        '404':
          description: Student not found.
        '200':    # status code
          description: A JSON array of new information about students
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /students/delete:
    delete:
      tags:
      - students
      summary: Delete records of necessary students.
      description: Delete records of necessary studenst.
      responses:
        default:
          description: Unexpected error
        '400':
          description: Invalid record parameters(name or type of columns).
        '404':
          description: Student not found.
        '200':    # status code
          description: Delete records in database
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /rooms/post:
    post:
      tags:
      - rooms
      summary: Add new rooms into database.
      description: Accept a json file with a list of new rooms
      responses:
        '400':
          description: Invalid record parameters(name or type of columns).
        default:
          description: Unexpected error
        '201':    # status code
          description: A JSON array of rooms information
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string 
  /rooms/get:
    get:
      tags:
      - rooms
      summary: Returns a list of rooms
      description: Accept a sample query
      responses:
        '400':
          description: Invalid record parameters(name or type of columns).
        '404':
          description: Room not found.
        default:
          description: Unexpected error      
        '202':    # status code
          description: A JSON array of rooms information
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string  
  /rooms/put:
    put:
      tags:
      - rooms
      summary: Update information about rooms.
      description: Find a necessary rooms and change theirs information.
      responses:
        '400':
          description: Invalid record parameters(name or type of columns).
        '404':
          description: Room not found.
        default:
          description: Unexpected error
        '200':    # status code
          description: A JSON array of new information about rooms
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /rooms/delete:
    delete:
      tags:
      - rooms
      summary: Delete records of necessary rooms.
      description: Delete records of necessary rooms.
      responses:
        '400':
          description: Invalid record parameters(name or type of columns).
        '404':
          description: Room not found.
        default:
          description: Unexpected error
        '200':    # status code
          description: Delete records in database
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /studentsinrooms/find:
    get:
      tags:
      - students in rooms
      summary: Find all students in necessary room.
      description: Takes a number of room and gives list of students.
      responses:
        '400':
          description: Invalid query parameters(name or type of columns).
        '404':
          description: Room not found.
        default:
          description: Unexpected error
        '200':    # status code
          description: Delete records in database
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /studentsinrooms/move:
    put:
      tags:
      - students in rooms
      summary: Change a room of students.
      description: Takes a students name/id and changes his room.
      responses:
        '400':
          description: Invalid query parameters(name or type of columns).
        '404':
          description: Student or room not found.
        default:
          description: Unexpected error
        '200':    # status code
          description: Delete records in database
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
