openapi: 3.0.0
info:
  description: This is a simple Athuentication API.
  version: "1.0.0-oas3"
  title: Get Authentication Token
  contact:
    email: gagan.s@appgallop.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /authenticate:
    post:
      tags:
        - Users
      summary: Authenticate User
      operationId: Authenticatate
      description: Authenticates a User and provides a token
      responses:
        '200':
          description: token created
        '400':
          description: invalid Address
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/credentials'
        description: emailId provided by AppGallop
servers:
  - url: 'https://api.appgallop.com/Appgallop-APICenter'
components:
  schemas:
    credentials:
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: abc@appgallop.com
        password:
          type: string
          example: password
