openapi: "3.0.2"
info:
  title: Rebate Event
  version: 0.0.1
paths:
  /info:
    get:
      x-scala-package: info
      operationId: getInfo
      responses:
        200:
          description: info success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
  /history:
    get:
      x-scala-package: history
      operationId: getHistory
      parameters:
        - in: query
          name: page
          required: false
          schema:
            type: integer
            format: int32
        - in: query
          name: pageSize
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: history success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistoryResponse'

components:
  schemas:
    InfoResponse:
      type: object
      required:
        - code
        - data
      properties:
        code:
          type: integer
          format: int32
        data:
          $ref: '#/components/schemas/Info'
    Info:
      type: object
      required:
        - isControl
        - isLeader
        - rebatePercentage
      properties:
        isControl:
          type: boolean
        isLeader:
          type: boolean
        rebatePercentage:
          type: integer
          format: int32
        refundPercentage:
          type: integer
          format: int32
    HistoryResponse:
      type: object
      required:
        - code
        - data
      properties:
        code:
          type: integer
          format: int32
        data:
          $ref: '#/components/schemas/PaginatedHistory'
    PaginatedHistory:
      type: object
      required:
        - page
        - pageSize
        - hasNext
        - data
      properties:
        page:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        hasNext:
          type: boolean
        data:
          type: array
          items:
            $ref: '#/components/schemas/HistoryItem'
    HistoryItem:
      type: object
      required:
        - todayProfit
        - todaySourceVolume
        - todayFee
        - todayRebate
        - todayRefund
        - todayNewUser
        - cumProfit
        - cumSourceVolume
        - cumFee
        - cumRebate
        - cumRefund
        - totalUser
      properties:
        todayProfit:
          type: string
        todaySourceVolume:
          type: string
        todayFee:
          type: string
        todayRebate:
          type: string
        todayRefund:
          type: string
        todayNewUser:
          type: integer
          format: int32
        cumProfit:
          type: string
        cumSourceVolume:
          type: string
        cumFee:
          type: string
        cumRebate:
          type: string
        cumRefund:
          type: string
        totalUser:
          type: integer
