openapi: 3.0.0
servers:
  - url: "https://api.varden.info/smr/"

info:
  description: The official API used by the StopModReposts campaign
  version: "1.0.0"
  title: StopModReposts API
  license:
    name: License
    url: 'https://creativecommons.org/licenses/by-sa/4.0/'

tags:
  - name: API

paths:
  /sitelist.php:
    get:
      tags:
        - API
      summary: Returns the list of blacklisted sites
      operationId: getSiteList
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Site'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Site'
                xml:
                  wrapped: true
                  name: sites
            application/x-nbt:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Site'
                example: Returns an .nbt file
            application/x-yaml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Site'
                example: "---\nsites:\n  -\n    domain: '9minecraft.net'\n    path: '/'\n    pattern: 'https?://([^\\s\\.]+\\.)*9minecraft\\.net(/[^\\s]*)?'\n    advertising: '5'\n    redistribution: '5'\n    miscellaneous: '1'\n    notes: ''\n"
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Site'
                example: '9minecraft.net'
  /hosts.php:
    get:
      tags:
        - API
      summary: Returns the list of blacklisted sites as a hosts.txt file
      operationId: getHosts
      responses:
        '200':
          description: ''
          content:
            text/plain:
              schema:
                example: "# Informational header at the top of the file\n\n0.0.0.0  9minecraft.net\n\n# === End of StopModReposts site list ==="

components:
  schemas:
    Site:
      type: object
      required:
        - domain
        - path
        - pattern
        - advertising
        - redistribution
        - miscellaneous
        - notes
      properties:
        domain:
          type: string
          example: 9minecraft.net
        path:
          type: string
          example: '/'
        pattern:
          type: string
          example: 'https?://([^\s\.]+\.)*9minecraft\.net(/[^\s]*)?'
        advertising:
          type: string
          example: '5'
        redistribution:
          type: string
          example: '5'
        miscellaneous:
          type: string
          example: '1'
        notes:
          type: string
          example: ''
      xml:
        name: site
