openapi: 3.0.0
info:
  description: Service API for Söderberg & Partners
  version: "v1"
  title: Söderberg & Partners API2
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: goo@thinc.no
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: InWork-NOTREADY
    description: Soon to be ready
  - name: Customers
    description: Get Customers by OrganizationId
  - name: Token
    description: >-
      Get a token by sending ian myToken as base64encoded(ClientId + ':' +
      ClientSecret) in header:Authentication: Bearer myToken
paths:
  '/Customers/getPartnerAgreements':
    post:
      tags:
        - Customers
      description: get customer with more
      operationId: getPartnerAgreements
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: 
                - UnionCode
                - ssn
                - productlist
                - damagedate
                - ssninsured
              properties:
                unioncode:
                  type: integer
                ssn:
                  type: integer
                  format: int64
                productlist:
                  type: string
                damagedate:
                  type: string
                  format: date
                ssninsured:
                  type: integer
                  format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Request_getPartnerAgreements'
        '400':
          description: Invalid ID supplied
        '404':
          description: Customers not found
      security:
        - api_key: []
  /Token:
    get:
      tags:
        - Token
      summary: Returns a token for use when calling the API
      description: ''
      operationId: ''
      parameters:
        - name: Authentication
          in: header
          description: 'Bearer "ClientId:ClientSecret" (in base64endcoding)'
          required: true
          schema:
            type: string
            format: ''
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '400':
          description: Invalid ID supplied
      security:
        - api_key: []
components: 
  securitySchemes: 
    BearerAuth: 
      type: http
      scheme: bearer
  schemas: 
    Token: 
      type: object
      properties: 
        Token: 
          type: string
          description: base64encoded string
        Expires: 
          type: string
          format: date-time
          description: Token utgår
    Request_getPartnerAgreements: 
      type: object
      properties: 
        CompanyCode: 
          type: string
        OrganizationCode: 
          type: string
        MemberSSN: 
          type: integer
          format: int64
        MemberId: 
          type: integer
          format: int64
        ProductNumberList: 
          type: string
        ValidOnDate: 
          type: string
          format: date
        SSNInsuredObject: 
          type: integer
          format: int64
    Member: 
      type: object
      properties: 
        UnionCode: 
          type: integer
        MemberSSN: 
          type: integer
          format: int64
        MemberType: 
          type: string
        MemberTypeName: 
          type: string
        MemberTypeCat: 
          type: string
        MemberCategory: 
          type: string
        MemberCategoryName: 
          type: string
        FirstName: 
          type: string
        LastName: 
          type: string
        Email: 
          type: string
        Phone: 
          type: string
        Address1: 
          type: string
        Address2: 
          type: string
        Address3: 
          type: string
        Address4: 
          type: string
        PostalCode: 
          type: string
        PostalCity: 
          type: string
        RelationSSN: 
          type: string
        RelationOrgNo: 
          type: string
        RelationFirstName: 
          type: string
        RelationLastName: 
          type: string
        RelationType: 
          type: integer
        RelationTypeName: 
          type: string
        Escalation: 
          type: string
        StartDate: 
          type: string
          format: date
        EndDate: 
          type: string
          format: date
        Agreements: 
          type: array
          items: 
            $ref: '#/components/schemas/Agreement'
        Relations: 
          type: array
          items: 
            $ref: '#/components/schemas/Relation'
    Agreement: 
      type: object
      properties: 
        AgreementNumber: 
          type: integer
          format: int64
        AnnualPrice: 
          type: integer
        DocURL: 
          type: string
        Products: 
          type: array
          items: 
            $ref: '#/components/schemas/Product'
    Product: 
      type: object
      properties: 
        ProductNumber: 
          type: integer
        ProductName: 
          type: string
        InsuranceCompanyCode: 
          type: integer
        ProductAnnualPrice: 
          type: integer
        TermsURL: 
          type: string
        InsuranceCertificate: 
          type: string
        Address1: 
          type: string
        Address2: 
          type: string
        Address3: 
          type: string
        Address4: 
          type: string
        PostalCode: 
          type: string
        PostalCity: 
          type: string
        StartDate: 
          type: string
          format: date
        EndDate: 
          type: string
          format: date
        InsuredObject: 
          type: array
          items: 
            $ref: '#/components/schemas/InsuredObject'
    InsuredObject: 
      type: object
      properties: 
        SSN: 
          type: integer
          format: int64
        FirstName: 
          type: string
        LastName: 
          type: string
        Address1: 
          type: string
        Address2: 
          type: string
        Address3: 
          type: string
        Address4: 
          type: string
        PostalCode: 
          type: string
        PostalCity: 
          type: string
        ReservationCode: 
          type: integer
        ReservationDescription: 
          type: string
        Zone: 
          type: string
        ZoneInsured: 
          type: number
        ZoneInsuredModified: 
          type: string
          format: date
        NumberOfG: 
          type: number
        NumberOfGModifiedDate: 
          type: string
          format: date
        StartDate: 
          type: string
          format: date
        EndDate: 
          type: string
          format: date
        Beneficiaries: 
          type: array
          items: 
            $ref: '#/components/schemas/Beneficiary'
    Beneficiary: 
      type: object
      properties: 
        FirstName: 
          type: string
        LastName: 
          type: string
        BirthDate: 
          type: string
          format: date
        Share: 
          type: number
        Coverages: 
          type: array
          items: 
            $ref: '#/components/schemas/Coverage'
    Coverage: 
      type: object
      properties: 
        CoverageNumber: 
          type: number
        CoverageName: 
          type: string
        SumInsured: 
          type: number
        SumInsuredModified: 
          type: string
          format: date
        CoverageAnnualPrice: 
          type: number
        Deductible: 
          type: number
        NumberOfG: 
          type: number
        NumberOfGModifiedDate: 
          type: string
          format: date
        StartDate: 
          type: string
          format: date
        EndDate: 
          type: string
          format: date
    Relation: 
      type: object
      properties: 
        RelationSSN: 
          type: string
        RelationFirstName: 
          type: string
        RelationLastName: 
          type: string
        RelationType: 
          type: string
        RelationTypeName: 
          type: string
        Address1: 
          type: string
        Address2: 
          type: string
        Address3: 
          type: string
        PostalCode: 
          type: string
        PostalCity: 
          type: string
        StartDate: 
          type: string
          format: date
        EndDate: 
          type: string
          format: date

externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: https://oeprod.rest.soderbergpartners.no/web/v1
    description: Produksjons environment 
  - url: https://oetest.rest.soderbergpartners.no/web/v1
    description: Test environment
