openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Yibeltalh/PaymentHub2/1.0.0
info:
  description: This is a simple API
  version: "1.0.0"
  title: Simple PaymentHub API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: developers
    description: Operations available to regular developers
paths:
  /PaymentHub/transactions/{transaction}:
    get:
      tags:
        - developers
      summary: searches transaction
      operationId: searchTransaction
      description: |
        By passing in the appropriate options, you can search for
        available payment in the system
      parameters:
        - in: path
          name: transaction
          description: pass an optional search string for looking up transaction
          required: true
          schema:
            type: string
            example: PH000000000000000003
       
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Transaction'
        '400':
          description: bad input parameter
   
components:
  schemas:
    Transaction:
     
      properties:
        transactionID:
          type: string
          example: PH000000000000000003
        
        result:
          $ref: '#/components/schemas/Result'
    Result:
     
      properties:
        code:
          type: string
          example: SL1
        text:
          type: string
          format: string
          example: Received transaction. In process.
        actualSettlementTimeISO8601:
          type: string
          example: 2012-03-29T10:05:45-06:00
        additionalData:
          type: string
          example: "test"
