openapi: "3.0.2"
info:
  title: "PunchList API"
  description: "PunchList API for submitting Home Inspection Reports and generating PunchList Estimates."
  version: "1.1"
  termsOfService: "https://punchlistusa.com/terms"
  contact:
    name: "PunchList API"
    url: "https://punchlistusa.com/api"
    email: "developers@punchlistusa.com"
servers:
  - url: https://api.punchlistusa.com/1.1
    description: Production API server
  - url: https://sandbox.api.punchlistusa.com/1.1
    description: Sandbox API server
paths:

  /territory/postalcode/{postalcode}:
    get:
      tags:
        - Get Territory By Postal Code
      summary: "Get PunchList Territory by Postal Code"
      description: "Get PunchList Territory for a given postal code. Out-Of-Area returned if out of a serviceable territory. IsServiceable property will return true or fale to indicate vendor servicability."
      operationId: "Get PunchList Territory By Postal Code"
      parameters: 
        - $ref: '#/components/parameters/Postalcode'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  Name:
                    type: string
                    example: "Charleston"
                  IsServiceable:
                    type: boolean
                    example: true
  
        404:
          description: Not found response
          content:
            text/plain:
              schema:
                title: Report Not Found
                type: string
                example: Not found

      
  /estimate:
    post:
      tags:
        - Save Home Inspection Report and Generate Estimate
      summary: "Save Single Home Inspection Report"
      description: "Save a single Home Inspection Report for any US address to be used to generate a PunchList Repair Estimate."
      operationId: "Save Home Inspection Report and Generate Estimate"
      requestBody:
        description: Home Inspection Report
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Customer:
                  $ref: '#/components/schemas/Customer'
                Address:
                  $ref: '#/components/schemas/Address'
                Items:
                  type: array
                  items:
                    $ref: '#/components/schemas/Item'
                Files:
                  type: array
                  items:
                    $ref: '#/components/schemas/File'
              required:
                - Customer
                - Address
                - Items
                
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: string
                    example: "HDAvXAY6WmKQRnSeQ"
                  EstimateId:
                    type: string
                    example: "FDGvXAY5WmKTRNs1Q"

        404:
          description: Not found response
          content:
            text/plain:
              schema:
                title: Report Not Found
                type: string
                example: Not found

security:
  - bearerAuth: []  
  
components:

  parameters:
    Postalcode:
      name: postalcode
      required: true
      in: path
      description: "Search for PunchList Territories by Postal Code"
      schema:
        type: string
          
 

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: KIO

  schemas:

    Customer: 
        description: "The contact information of the person requesting the estimate. Use the Role property to describe who it is submitting this request. This contact detail will be used to send the final estimate once released."
        type: object
        properties:
            GivenName: 
              type: string
            FamilyName:
              type: string        
            PrimaryEmailAddr:
              type: string
              format: email
            PrimaryPhone: 
              type: string
            Role: 
              type: string
              enum: ['selling', 'buying', 'closing-buyers', 'closing-sellers','homeowner','buyer','other']
              default: "other"
            RoleOther:
              type: string
        required:
          - GivenName
          - FamilyName
          - PrimaryEmailAddr
          - PrimaryPhone

    Address: 
        description: "The proper address of the property evaluated and to be estimated."
        type: object
        properties:
            CountrySubDivisionCode:
                type: string
            City:
                type: string
            PostalCode: 
                type: string
            Line1:
                type: string
            Line2:
                type: string
            Country:
                type: string
        required: 
          - CountrySubDivisionCode
          - City
          - PostalCode
          - Line1
          - Country
    Item: 
      description: "An array of inspection items requiring estimation. The more detail the more accurate the final estimate. Items without enough detail will be categorized into an Evaluate category for further evaluation."
      type: object
      properties:
        Quantity:
          type: integer
          default: 1
        ReferenceNum:
          type: string
        Location:
          type: string
        Description:
          type: string
        Action: 
          type: string
        Category:
          type: string
        ImageURIs:
          type: array
          items:
            type: string
      required:
        - Description
        - ImageURIs
          
    File:
      description: "Supporting files useful for estimating. Please include the original home inspection, repair list/addendums, and/or pictures or documents that will assist in a more accurate estimate."
      properties:
        Name:
          type: string
        URI:
          type: string
      required:
        - Name
        - URI
