openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/hslagter/simple/1.0.0
info:
  description: This is an API for learning purposesI
  version: "2.0.0"
  title: Customers API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: customers
    description: Customer related calls
paths:
  /customers:
    get:
      tags:
        - customers
      summary: searches customers
      operationId: searchCustomer
      description: |
        Search for customers in the system
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
        '400':
          description: Bad input parameter
components:
  schemas:
    Customer:
      type: object
      required:
        - firstName
        - lastName
        - customerNumber
      properties:
        customerNumber:
          type: string
          example: d290f1ee
        firstName:
          type: string
          example: John
        lastName: 
          type: string 
          example: Smith
        phone:
          type: string
          example: '555-55555'
