openapi: 3.0.0
info:
  title: E-Lucky Draw API
  description: Manage the participation as well as chances of customer in ELD campaign
  version: "1.0.5"
servers:
  - url: 'http://tobedefined.uat'
    description: UAT server
  - url: 'http://tobedefined.prod'
    description: Prod server
tags:
  - name: customers
    description: To manage the pariticipation in ELD campaign of a customer
  - name: chances
    description: To manage chances rewarded to an order
paths:
  /customers/{customerID}:
    get:
      tags:
        - customers
      summary: Find customer by ID
      description: Returns the details of customer
      operationId: getCustomerByID
      parameters:
        - name: customerID
          in: path
          required: true
          description: ID of customer to return
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Invalid ID supplied
        '404':
          description: Customer not found
    delete:
      tags:
        - customers
      summary: Opt out a customer from Eld campaign
      description: ''
      operationId: deleteCustomer
      parameters:
        - name: customerID
          in: path
          required: true
          description: ID of customer to opt out
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Customer not found
  /customers:
    post:
      tags:
        - customers
      summary: Opt in a customer into Eld Campaign
      description: ''
      operationId: insertCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerID:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '405':
          description: Invalid input
  /chances:
    get:
      tags:
        - chances
      summary: 'Get chances rewarded to an order by ZS ID, using customer access token'
      description: Return chances a customer will earn after the order completed.
      operationId: getChanceByOrderID
      parameters:
        - in: query
          name: orderID
          schema:
            type: integer
          description: The ZS id of order
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Response:
      type: object
      required:
        - data
        - code
      properties:
        data:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600
        status: 
          type: string
    Customer:
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          required:
            - data
          properties:
            data:
              type: object
              properties:
                id:
                  type: integer
                  description: ZS ID
                  example: 6814839
                status:
                  type: integer
                  enum:
                    - 0
                    - 1
                  description: |
                    Participation status:
                     * `0` - Opted in
                     * `1` - Opted out
                noOfChances:
                  type: integer
                  example: 230
                campaignName:
                  type: string
                  example: FairPrice Raya Festive Draw
                campaigns:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        example: Happy Raya
                      noOfChances:
                        type: integer
                        example: 230
              required:
                - id
                - status
                - noOfChances
                - campaignName
    Order:
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          required:
            - data
          properties:
            data:
              type: object
              properties:
                id:
                  type: integer
                  description: Order ID.
                  example: 10030888
                noOfChances:
                  type: integer
                  example: 230
                campaignName:
                  type: string
                  example: FairPrice Raya Festive Draw
              required:
                - id
                - noOfChances
                - campaignName
security:
  - bearerAuth: []
