openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/filippolp/ThingworxAPI/1.0.0
info:
  version: "1.0.0"
  title: thingworx-api
  description: The API for Thingworx Platform
externalDocs:
  description: Thingworx API Design
  url: https://tpg-twxdevzone.s3.amazonaws.com/files/media/REST%20API/REST_API_overview.png
paths:
  '/{host}:{port}/Thingworx/Resources/EntityServices/Services/CreateThing':
    post:
      tags:
        - Thing
        - Create New Thing
      description: After a Thing has been created by using an API call, it must be ENABLED and RESTARTED with additional API calls before it can be used.
      operationId: createThing
      parameters:
        - name: host
          in: path
          description: thingworx server
          required: true
          schema:
            type: string
        - name: port
          in: path
          description: thingworx port
          required: true
          schema:
            type: string
        - name: appKey
          in: header
          description: appKey
          required: true
          schema:
            type: string
      requestBody:
          description: Insert in the body the name of the new thing and the base Template
          required: true
          content:
            application/json:
              schema:
                properties:
                  name:
                    type: string
                  thingTemplateName:
                    type: string
      responses:
        '200':
          description: result
          content:
            application/json:
              schema:
                type: object
  '/{host}:{port}/Thingworx/Things/{ThingName}/Services/EnableThing':
    post:
        tags:
          - Create New Thing
          - Thing
        description: After a Thing is created and whenever any changes are made to its structure, the Thing has to be restarted.
        operationId: EnableThing
        parameters:
          - name: host
            in: path
            description: thingworx server
            required: true
            schema:
              type: string
          - name: port
            in: path
            description: thingworx port
            required: true
            schema:
              type: string
          - name: appKey
            in: header
            description: appKey
            required: true
            schema:
              type: string
          - name: ThingName
            in: path
            description: the name of the thing
            required: true
            schema:
              type: string  
        responses:
          '200':
            description: result
            content:
              application/json:
                schema:
                  type: object
  '/{host}:{port}/Thingworx/Things/{ThingName}/Services/RestartThing':
    post:
        tags:
          - Create New Thing
          - Thing
        description: After a Thing has been created by using an API call, it must be enabled and restarted with this API call before it can be used.
        operationId: RestartThing
        parameters:
          - name: host
            in: path
            description: thingworx server
            required: true
            schema:
              type: string
          - name: port
            in: path
            description: thingworx port
            required: true
            schema:
              type: string
          - name: appKey
            in: header
            description: appKey
            required: true
            schema:
              type: string
          - name: ThingName
            in: path
            description: the name of the thing
            required: true
            schema:
              type: string  
        responses:
          '200':
            description: result
            content:
              application/json:
                schema:
                  type: object
  '/{host}:{port}/Thingworx/Things/{ThingName}/Properties/{PropertyName}':
    get:
      tags:
        - Get Thing Property
        - Thing
      description: You can retrieve Property values of a specific Thing with the REST API using the GET verb.
      operationId: getThingProperty
      parameters:
        - name: host
          in: path
          description: thingworx server
          required: true
          schema:
            type: string
        - name: port
          in: path
          description: thingworx port
          required: true
          schema:
           type: string
        - name: appKey
          in: header
          description: appKey
          required: true
          schema:
            type: string
        - name: ThingName
          in: path
          description: the name of the thing
          required: true
          schema:
            type: string  
        - name: PropertyName
          in: path
          description: the name of the property
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  dataShape:
                    type: object
                    properties:
                      fieldDefinitions:
                        type: object
                  rows:
                    type: array
                    items:
                      type: object
    put:
      tags:
        - Set Thing Property
        - Thing
      description: You can set the value of a specific Property with the REST API using the PUT verb.
      operationId: setThingProperty
      parameters:
        - name: host
          in: path
          description: thingworx server
          required: true
          schema:
            type: string
        - name: port
          in: path
          description: thingworx port
          required: true
          schema:
            type: string
        - name: appKey
          in: header
          description: appKey
          required: true
          schema:
            type: string
        - name: ThingName
          in: path
          description: the name of the thing
          required: true
          schema:
            type: string  
        - name: PropertyName
          in: path
          description: the name of the property
          required: true
          schema:
            type: string
      requestBody:
          description: Insert in the body the name of the property and the value to set
          required: true
          content:
            application/json:
              schema:
                properties:
                  propertyName: 
                    example: propertyValue
      responses:
        '200':
          description: result
          content:
            application/json:
              schema:
                type: object
  '/{host}:{port}>/Thingworx/Things/{ThingName}/Services/{ServiceName}':
    post:
      tags:
        - Call Thing Service
        - Thing
      description: In order to execute a Service of a specific Thing with the REST API, you can use the POST verb
      operationId: callThingService
      parameters:
        - name: host
          in: path
          description: thingworx server
          required: true
          schema:
            type: string
        - name: port
          in: path
          description: thingworx port
          required: true
          schema:
            type: string
        - name: appKey
          in: header
          description: appKey
          required: true
          schema:
            type: string
        - name: ThingName
          in: path
          description: the name of the thing
          required: true
          schema:
            type: string  
        - name: ServiceName
          in: path
          description: the name of the service
          required: true
          schema:
            type: string
      requestBody:
          description: The names of the inputs along with their values are sent in the body of the POST as a JSON object
          required: false
          content:
            application/json:
              schema: 
                type: object
      responses:
        '200':
          description: result
          content:
            application/json:
              schema:
                type: object
  '/{host}:{port}/Thingworx/Exporter/Things/{ThingName}':
    get:
      tags:
        - Export Thing
        - Thing
      description: The REST API can be used to export a file representation of Things on a ThingWorx Foundation server
      operationId: exportThing
      parameters:
        - name: host
          in: path
          description: thingworx server
          required: true
          schema:
            type: string
        - name: port
          in: path
          description: thingworx port
          required: true
          schema:
            type: string
        - name: appKey
          in: header
          description: appKey
          required: true
          schema:
            type: string
        - name: ThingName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: result
          content:
            text/xml:
              schema:
                type: object
  '/{host}:{port}/Thingworx/Resources':
    get:
      tags:
        - Resource
        - List Resources
      operationId: listResources
      description: List Resources
      parameters:
        - name: host
          in: path
          description: thingworx server
          required: true
          schema:
            type: string
        - name: port
          in: path
          description: thingworx port
          required: true
          schema:
            type: string
        - name: appKey
          in: header
          description: appKey
          required: true
          schema:
            type: string
      responses:
        '200':
          description: result
          content:
            application/json:
              schema:
                type: object
  '/{host}{port}>/Thingworx/Resources/{ResourceName}/Services/{ServiceName}':
    post:
      tags:
        - Resource
        - Call Resource Service
      description: In order to execute a Service of a specific Resource with the REST API, you can use the POST verb
      operationId: callResourceService
      parameters:
        - name: host
          in: path
          description: thingworx server
          required: true
          schema:
            type: string
        - name: port
          in: path
          description: thingworx port
          required: true
          schema:
            type: string
        - name: appKey
          in: header
          description: appKey
          required: true
          schema:
            type: string
        - name: ResourceName
          in: path
          description: the name of the resource
          required: true
          schema:
            type: string  
        - name: ServiceName
          in: path
          description: the name of the service
          required: true
          schema:
            type: string
      requestBody:
          description: The names of the inputs along with their values are sent in the body of the POST as a JSON object
          required: false
          content:
            application/json:
              schema: 
                type: object
      responses:
        '200':
          description: result
          content:
            application/json:
              schema:
                type: object
