openapi: 3.0.0
info:
  description: Authentication API for ACP tokens
  version: "1.0.0"
  title: ACP Auth API
  termsOfService: "http://swagger.io/terms/"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  /v1/acp-token/{acpToken}:
    get:
      summary: "Parse acp token and return user data"
      description: "Parse acp token and return user data"
      operationId: "getAcpToken"
      parameters:
        - name: "acpToken"
          in: "path"
          description: "Token value"
          required: true
          schema:
            type: "string"
      responses:
        '200':
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AcpTokenResponse"
            application/xml:
              schema:
                $ref: "#/components/schemas/AcpTokenResponse"
        '404':
          description: "User not found"
      tags:
        - ail-auth
components:
  schemas:
    AcpUserDetails:
      type: "object"
      properties:
        userId:
          type: "string"
          example: "12345"
        userName:
          type: "string"
          example: "Tony Stark"
        userReference:
          type: "string"
          example: "sg80317"
        roles:
          type: array
          items:
            type: string
            example: "ADMIN"
          example: ["ADMIN", "USER"]
      xml:
        name: "acpUserDetails" 
    AcpTokenResponse:
      type: "object"
      properties:
        AcpUserDetails:
          $ref: "#/components/schemas/AcpUserDetails"
        operationStatus:
          $ref: "#/components/schemas/TypeOperationStatus"
      xml:
        name: "AcpTokenResponse"
    TypeOperationStatus:
      type: "object"
      required:
        - "status"
      properties:
        status:
          type: "string"
          enum: [SUCCESS, FAILED]
        failedReason:
          type: "string"
