openapi: 3.0.0
servers:
  - url: 'https://dc4.disc-check.net'
    description: Production Disc-check Server
info:
  description: Upload *.DDD Files into disc-check for analysis. Please contact us for an API Key and further information
  version: "0.1"
  title: Disc-check Transfer API
  contact:
    email: support@tdi.tc
    
paths:
  /transfer:
    put:
      parameters:
        - in: header
          name: X-AUTH-TOKEN
          required: true
          schema:
            
            type: string
            
      summary: Uploads Raw Data File
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Upload'
      responses:
        '201':
          description: item created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    enum: [-1,0]
        '400':
          description: 'invalid input, object invalid'
components:
  schemas:
    Upload:
      type: object
      required:
        - depotId
        - files
      properties:
        depotId:
          type: integer
          example: 2
          description: Depot ID Belonging to the end user (provided by TDi)
        files:
          type: array
          items:
            $ref: '#/components/schemas/UploadFile'
    UploadFile:
      type: object
      required:
        - filename
        - filecontent
      properties:
        filename:
          type: string
          example: BOB_SMITH_20191007.DDD
          description: File name to be displayed to the customer. Must end in .DDD
        filecontent:
          type: string
          example: REREIEZpbGUgQ29udGVudCBpbiBiYXNlNjQgZW5jb2RlZCBmb3JtYXQ=
          description: Base64 encoded content of the raw data
