openapi: 3.0.2
info:
  version: 3000.10.31
  title: '{my json:api} Specification'
paths:
  /myThing:
    parameters:
      - name: Thing
        in: query
        required: true
        schema:
          type: string
    get:
      deprecated: true
      description: get a collection
      operationId: get collection
      parameters:
        - name: token
          in: header
          description: token to be passed as a header
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
          style: simple
      responses:
        '200':
          description: '[OK](https://jsonapi.org/format/#fetching-resources-responses-200)'
          content:
            application/vnd.api+json:
              schema:
                type: string
        '404':
          description: >-
            [Not
            found](https://jsonapi.org/format/#fetching-resources-responses-404)
          content:
            application/vnd.api+json:
              schema:
                type: string
