openapi: 3.0.0
info:
  title: BriteNotes API
  contact:
    email: engineering@britecore.com
  version: '0.1'

tags:
  - name: notes
    description: BriteNotes Operations

paths:
  /notes:
    get:
      description: Lists all notes
      operationId: getNotes
      responses:
        '200':
          description: Notes successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
    post:
      tags:
        - notes
      summary: Adds a new note
      operationId: addNote
      description: Adds a new note
      responses:
        '201':
          description: Note successfully created
  /notes/{id}:
    get:
      tags:
        - notes
      summary: Gets a specific note
      operationId: getNote
      description: Gets a specific note
      parameters:
        - required: true
          in: path
          name: id
          description: Unique identifier for retrieving single object
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Note successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
    patch:
      tags:
        - notes
      summary: Partially updates a note
      operationId: partiallyUpdateNote
      description: Updates one or more fields of a note
      parameters:
        - required: true
          in: path
          name: id
          description: Unique identifier
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Note successfully updated
    delete:
      tags:
        - notes
      summary: Deletes an existing note
      operationId: deleteNote
      description: Deletes an existing note
      parameters:
        - required: true
          in: path
          name: id
          description: Unique identifier
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Note successfully deleted
  /notes/{id}/history:
    get:
      tags:
        - notes
      summary: Gets the modifications history of a note
      operationId: getNoteHistory
      description: Gets a specific note's history
      parameters:
        - required: true
          in: path
          name: id
          description: Unique note identifier
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Note history successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NoteHistoryEvent'
  /notes/types:
    get:
      tags:
        - notes
      summary: List all note types
      operationId: getNoteTypes
      responses:
        '200':
          description: Note types successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NoteType'
    post:
      tags:
        - notes
      summary: Adds a new note type
      operationId: addNoteType
      description: Adds a new note type
      responses:
        '201':
          description: Note type successfully created
  /notes/types/{id}:
    get:
      tags:
        - notes
      summary: Gets a specific note type
      operationId: getNoteType
      description: Gets a specific note type
      parameters:
        - required: true
          in: path
          name: id
          description: Unique identifier for retrieving single object
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Note type successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoteType'
    patch:
      tags:
        - notes
      summary: Partially updates a note type
      operationId: partiallyUpdateNoteType
      description: Updates one or more fields of a note type
      parameters:
        - required: true
          in: path
          name: id
          description: Unique identifier
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Note type successfully updated
    delete:
      tags:
        - notes
      summary: Deletes an existing note type
      operationId: deleteNoteType
      description: Deletes an existing note type
      parameters:
        - required: true
          in: path
          name: id
          description: Unique identifier
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Note type successfully deleted
        '400':
          description: When trying to delete a note type that is being used by a Note
components:
  schemas:
    Note:
      type: object
      required:
        - author_name
        - reference
        - title
      properties:
        creator:
          type: object
          properties:
            username:
              type: string
              description: username from BriteAuth
            name:
              type: string
              description: the creator name
        title:
          type: string
          description: The note title
        reference:
          type: object
          description: Information about the entity to which the note belongs to
          properties:
            id:
              type: string
              format: uuid
              description: The reference's immutable identifier
            label:
              type: string
              description: The reference's application-level mutable identifier
            domain:
              type: string
              description: The domain to which the reference belongs to
            level:
              type: string
              description: The level inside the domain
        body:
          type: string
        custom_data:
          type: object
          description: Custom information provided and used solely by the consumer
    NoteHistoryEvent:
      type: object
      description: Represents an event in the note life
      properties:
        type:
          type: string
          description: the event type
        modified_by:
          type: object
          properties:
            username:
              type: string
              description: BriteAuth's username
            name:
              type: string
              description: BriteAuth's user name
        date_modified:
          type: string
          description: the event date
    NoteType:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: the note type name
        description:
          type: string
          description: the note type description
