openapi: 3.0.1
info:
  title: TRASE-API
  version: 'v0.0'
servers:
  - url: 'https://73iro72e0i.execute-api.eu-west-1.amazonaws.com/{basePath}'
    variables:
      basePath:
        default: production
paths:
  /traders/names/default/group:
    post:
      description: Suggest default name for group
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuggestDefaultGroupNameInputModel'
        required: true
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponseModel'
      security:
        - api_key: []
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:614804060947:function:suggest-default-group-name/invocations'
        responses:
          default:
            statusCode: '200'
        passthroughBehavior: when_no_match
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws
  /traders/names/default/trader:
    post:
      description: Suggest default name for trader
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuggestDefaultTraderNameInputModel'
        required: true
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponseModel'
      security:
        - api_key: []
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:614804060947:function:suggest-default-trader-name/invocations'
        responses:
          default:
            statusCode: '200'
        passthroughBehavior: when_no_match
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws
  /traders/names/synonyms:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuggestTradersSynonymInputModel'
        required: true
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponseModel'
      security:
        - api_key: []
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:614804060947:function:suggest-trader-synonym/invocations'
        responses:
          default:
            statusCode: '200'
        passthroughBehavior: when_no_match
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws
  '/traders/hierarchy/{country}':
    get:
      description: Retrieve trader hierarchy for country of interest
      parameters:
        - name: country
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponseModel'
      security:
        - api_key: []
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:614804060947:function:get-traders-dictionary/invocations'
        responses:
          default:
            statusCode: '200'
        passthroughBehavior: when_no_templates
        httpMethod: POST
        requestTemplates:
          application/json: '{"country": "$input.params(''country'')"}'
        contentHandling: CONVERT_TO_TEXT
        type: aws
  /traders/hierarchy/groups:
    post:
      description: Suggest a trader as a member of a group
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuggestGroupTraderInputModel'
        required: true
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponseModel'
      security:
        - api_key: []
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:614804060947:function:suggest-group-trader/invocations'
        responses:
          default:
            statusCode: '200'
        passthroughBehavior: when_no_match
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws
  /traders:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostTradersInputModel'
        required: true
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponseModel'
      security:
        - api_key: []
      x-amazon-apigateway-request-validator: Validate body
      x-amazon-apigateway-integration:
        uri: 'arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:614804060947:function:post-traders/invocations'
        responses:
          default:
            statusCode: '200'
        passthroughBehavior: when_no_match
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws
components:
  schemas:
    SuggestDefaultGroupNameInputModel:
      title: SuggestDefaultGroupNameInputModel
      type: object
      properties:
        current_group_name:
          type: string
        suggested_group_name:
          type: string
    SuggestTradersSynonymInputModel:
      title: SuggestTradersSynonymInputModel
      type: object
      properties:
        trader_name:
          type: string
        synonym:
          type: string
    PostTradersInputModel:
      title: PostTradersInputModel
      type: object
      properties:
        country:
          type: string
        trader_names:
          type: array
          items:
            type: string
    SuggestGroupTraderInputModel:
      title: SuggestGroupTraderInputModel
      type: object
      properties:
        trader_name:
          type: string
        group_name:
          type: string
    SuggestDefaultTraderNameInputModel:
      title: SuggestDefaultTraderNameInputModel
      type: object
      properties:
        current_trader_name:
          type: string
        suggested_trader_name:
          type: string
    DefaultResponseModel:
      title: PostTradersOutputModel
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: object
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
x-amazon-apigateway-documentation:
  version: v0.5
  createdDate: '2019-10-02T22:18:03Z'
  documentationParts:
    - location:
        type: API
      properties:
        description: Trase API
    - location:
        type: METHOD
        path: /traders/hierarchy/groups
        method: POST
      properties:
        description: Suggest a trader as a member of a group
    - location:
        type: METHOD
        path: '/traders/hierarchy/{country}'
        method: GET
      properties:
        description: Retrieve trader hierarchy for country of interest
    - location:
        type: METHOD
        path: /traders/names/default/group
        method: POST
      properties:
        description: Suggest default name for group
    - location:
        type: METHOD
        path: /traders/names/default/trader
        method: POST
      properties:
        description: Suggest default name for trader
    - location:
        type: RESOURCE
        path: /traders/hierarchy/groups
      properties:
        description: Functions related to group membership of traders
    - location:
        type: RESOURCE
        path: '/traders/hierarchy/{country}'
      properties:
        description: Functions related to countries of traders
    - location:
        type: RESOURCE
        path: /traders/hierarchy
      properties:
        description: Functions related to hierarchy of groups and traders
    - location:
        type: RESOURCE
        path: /traders/names/default/group
      properties:
        description: Functions realated to default group names
    - location:
        type: RESOURCE
        path: /traders/names/default/trader
      properties:
        description: Functions realated to default trader names
    - location:
        type: RESOURCE
        path: /traders/names/default
      properties:
        description: Functions realated to default names
    - location:
        type: RESOURCE
        path: /traders/names/synonyms
      properties:
        description: Functions related to trader synonyms
    - location:
        type: RESOURCE
        path: /traders/names
      properties:
        description: Functions related to trader and group names
    - location:
        type: RESOURCE
        path: /traders
      properties:
        description: Traders enpoints
x-amazon-apigateway-request-validators:
  Validate body:
    validateRequestParameters: false
    validateRequestBody: true
