openapi: 3.0.0
info:
  version: '1'
  title: ''
  description: ''
paths: {}
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Punksolid/come-yapi/1
