openapi: 3.0.0
info:
  version: '1.0'
  title: 'ViewMainHasilUjian'
  description: 'ViewMainHasilUjian'
paths:
 /api_get_Main_hasil_ujian_siswa.php:
    get:
      summary: list daftar ujian setiap kelas 
      description : list daftar ujian setiap kelas
      parameters :
        - name: schedjadwalid
          in : query
          schema:
            type: integer
          required: false
        
      responses :
        200: 
          description : successfull HTTP Request
          content:
            application/json:
              schema : 
                $ref : '#/components/schemas/response'
        422: 
          description : warning
          content:
            application/json:
              schema : 
                $ref : '#/components/schemas/warning'
components : 
  schemas:
    response:
      type: object
      properties:
        response:
          type: array
          items:
            type: object
            properties:
              schedjadwalid:
                type: integer
              Kelompok_Soal:
                type: string
              mapelcode:
                type: string
              examtypename:
                type: string
              schedstartdate:
                type: string
              Kelas_jurcode_soal:
                type: string
      
      example:
        - schedjadwalid: 3
          Kelompok_Soal: Sejarah_X_MM
          mapelcode: SJR
          examtypename: UTS
          schedstartdate: 2018-12-05
          Kelas_jurcode_soal: XMM1
          
        - schedjadwalid: 4
          Kelompok_Soal: Sejarah_X_MM
          mapelcode: SJR
          examtypename: UHAR
          schedstartdate: 2018-12-06
          Kelas_jurcode_soal: XMM1
         
          
    warning:
      type: object
      properties:
        warning:
          type: array
          items:
            type: object
            properties:
              param:
                type: string
              message:
                type: string  
      example :
        param: 422
        message: The server understands the content type of the request entity
        
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/T2125/DigischoolViewMainHasilUjian/1.0
