openapi: 3.0.0
info:
  description: >-
    This API allows users to integrate with the Midsouth Digitizng Portal. Usage
    of this API requires a header parameter called `api-key`, which can be
    retrieved from the Midsouth Digitizing Portal. The API key is passed as a
    header parameter on each call. The API can be accessed at
    https://api.midsouthdigitizing.com.
  version: "1.0.0-oas3"
  title: Midsouth Digitizing API
tags:
  - name: Create Order
    description: Methods to create a digitizing order.
  - name: Retrieve Order
    description: Methods for getting information about an order.
paths:
  /digitization/request:
    post:
      tags:
        - Create Order
      description: Adds an item to the system
      responses:
        '200':
          description: Order created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '401':
          description: Unauthorized. API Key is incorrect.
        '500':
          description: An error occured.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
        description: The order that will be added.
  '/digitization/status/{referenceNumber}':
    get:
      tags:
        - Retrieve Order
      description: Retrieve a status for the order in the digitization process.
      parameters:
        - name: referenceNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order status was found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderStatus'
        '401':
          description: Unauthorized. API Key is incorrect.
        '404':
          description: Order not found
  '/digitization/results/{referenceNumber}':
    get:
      tags:
        - Retrieve Order
      description: Retrieve Info about the completed order and `fileId`
      parameters:
        - name: referenceNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '401':
          description: Unauthorized. API Key is incorrect.
        '404':
          description: Order not found
  '/digitization/results/file/{fileId}':
    get:
      tags:
        - Retrieve Order
      description: >-
        Streams a zip file of the digitized assets. Once the file is downloaded,
        it is removed. If another copy is desired, you must call
        `/digitization/results/{referenceNumber}` again to obtain a new fileId.
      parameters:
        - name: fileId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Zip file containing the assets
          content:
            application/zip:
              schema:
                type: string
                format: binary
        '401':
          description: Unauthorized. API Key is incorrect.
        '404':
          description: File not found
components:
  schemas:
    OrderRequest:
      type: object
      required:
        - OrderDate
        - LogoID
        - PurchaseOrder
        - ServiceType
        - Template
        - ProductColor
        - Placement
        - Width
        - Height
      properties:
        OrderDate:
          type: string
          example: '11/30/2019 12:00:00 AM'
        LogoID:
          type: string
          example: 0123456_001.PNG
        PurchaseOrder:
          type: string
          example: CCG12345689
        ServiceType:
          type: string
          example: Embroidery or Artwork
        Template:
          type: string
          example: Name of the Design Template
        ProductColor:
          type: string
          example: Green
        Placement:
          type: string
          example: UL
        Width:
          type: number
          example: 4
        Height:
          type: number
          example: 2.5
    OrderResponse:
      type: object
      required:
        - status
        - ReferenceNumber
      properties:
        status:
          type: string
          example: success or error
        ReferenceNumber:
          type: string
          example: MS-DTCCE84D
    OrderStatus:
      type: object
      required:
        - status
        - OrderStatus
      properties:
        status:
          type: string
          example: success or error
        OrderStatus:
          type: integer
          example: '1=Received, 2=InProgress,3=Completed'
    Order:
      type: object
      required:
        - status
        - fileId
      properties:
        status:
          type: string
          example: success or error
        fileId:
          type: string
          example: 5d8ebd38b85ae
        width:
          type: number
          example: 4
        height:
          type: number
          example: 2.5
        units:
          type: string
          example: in or cm
        comments:
          type: string
          example: Coments from the digitizer
