openapi: 3.0.1
info:
  title: Document-Extension
  description: Document extension application services
  version: '1.0.0'
servers:
  - url: 'https://api-test.wnins.com/doc-ext'
    description: 'Test'
  - url: 'https://api-stage.wnins.com/doc-ext'
    description: 'Stage'
  - url: 'https://api.wnins.com/doc-ext'
    description: 'Production'
security:
  - application:
      - api-application
paths:
  /documents:
    get:
      summary: retrieve ImageRight documents
      parameters:
        - $ref: '#/components/parameters/fileId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocumentResponse'
  /documents/{id}:
    get:
      summary: retrieve an ImageRight document
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
  /folders:
    get:
      summary: retrieve ImageRight folders
      parameters:
        - $ref: '#/components/parameters/fileId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocumentResponse'
  /health:
    get:
      summary: health check
      responses:
        '200':
          description: OK
components:
  parameters:
    fileId:
      name: fileId
      in: query
      required: true
      schema:
        type: integer
    id:
      name: id
      in: path
      required: true
      schema:
        type: integer
  schemas:
    DocumentResponse:
      type: object
      properties:
        AttributeList:
          type: array
          items:
            $ref: '#/components/schemas/Attribute'
        DateCreated:
          type: string
        DateLastModified:
          type: string
        Description:
          type: string
        DocumentDate:
          type: string
        DocumentTypeId:
          type: string
        EffectivePermissions:
          type: integer
          format: int64
        Id:
          type: string
        IsDeleted:
          type: boolean
        ObjectType:
          $ref: '#/components/schemas/ObjectType'
        PageCount:
          type: integer
        PageList:
          type: array
          items:
            $ref: '#/components/schemas/Page'
        Parent:
          $ref: '#/components/schemas/FolderResponse'
        ParentId:
          type: integer
          format: int64
        ReceivedDate:
          type: string
    FolderResponse:
      type: object
      properties:
        AttributeList:
          type: array
          items:
            $ref: '#/components/schemas/Attribute'
        DateCreated:
          type: string
        Description:
          type: string
        EffectivePermissions:
          type: integer
        FileId:
          type: integer
          format: int64
        FolderTypeId:
          type: integer
          format: int64
        HasNotes:
          type: boolean
        Id:
          type: string
        IsDeleted:
          type: boolean
        LastModified:
          type: string
        Name:
          type: string
        ObjectType:
          $ref: '#/components/schemas/ObjectType'
        ParentFolderId:
          type: integer
          format: int64
    Attribute:
      type: object
      properties:
        AttributeType:
          type: string
        DisplayName:
          type: string
        Name:
          type: string
        Value:
          type: string
    ObjectType:
      type: object
      properties:
        AutomationId:
          type: string
        ClassId:
          type: string
        DateLastModified:
          type: string
        Description:
          type: string
        EffectivePermissions:
          type: integer
          format: int64
        Id:
          type: integer
          format: int64
        Name:
          type: string
        OverlayId:
          type: integer
          format: int64
    Page:
      type: object
      properties:
        Deleted:
          type: boolean
        DeleteOpType:
          type: integer
        Description:
          type: string
        DocumentId:
          type: integer
          format: int64
        Id:
          type: integer
          format: int64
        LatestImages:
          type: array
          items:
            $ref: '#/components/schemas/LatestImage'
        Marks:
          type: array
          items:
            $ref: '#/components/schemas/Mark'
        PageNumber:
          type: integer
        Version:
          type: integer
    LatestImage:
      type: object
      properties:
        ImageMetaData:
          type: array
          items:
            $ref: '#/components/schemas/ImageMetaData'
        PreRotation:
          type: integer
        Rotation:
          type: integer
    ImageMetaData:
      type: object
      properties:
        ContentType:
          type: integer
        Extension:
          type: string
        Id:
          type: integer
          format: int64
        ImageData:
          type: array
          items:
            type: integer
            format: int64
        ImageType:
          type: integer
        Size:
          type: integer
          format: int64
        Version:
          type: integer
    Mark:
      type: object
      properties:
        BinaryData:
          type: array
          items:
            type: integer
            format: int64
        Color:
          type: integer
        Description:
          type: string
        FileTypeId:
          type: integer
          format: int64
        MarkId:
          type: integer
          format: int64
        ProgrammaticName:
          type: string
  securitySchemes:
    test:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://api-test.wnins.com/auth/oauth2/token'
          scopes:
            api-application: allows modifying resources
    stage:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://api-stage.wnins.com/auth/oauth2/token'
          scopes:
            api-application: allows modifying resources
    production:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://api.wnins.com/auth/oauth2/token'
          scopes:
            api-application: allows modifying resources
