openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/yuvalnavon.com/travelTimes/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/yuvalnavon.com/SectionTime/1.0.0
info:
  description: Provides all travel time by section
  version: "1.0.0"
  title: Travel Time API
  contact:
    email: yuval@jennytech.com.au
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: support
    description: Operations available to support officers
  - name: reporing
    description: reporing data
paths:
  /travelTime:
    get:
      tags:
        - reporting
      summary: Provides sign data
      operationId: getSignData
      description: Provides sing operational data
      parameters:
        - in: query
          name: key
          required: true
          description: provide the access key (contract number)
          schema:
            type: string
            example: ABCDE-0000-123

      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/travelTime'
        '400':
          description: bad input parameter
components:
  schemas:
    segmentTemplate:
      type: object
      properties:
        segmentid:
          type: string
          example: link/123
        timestamp:
          type: number
          example: 12345.678
        traveltimesec:
          type: integer
          example: 600
          
  
    travelTime:
      type: object
      properties:
        collection:
          type: object
          properties:
            version:
              type: string
              example: 1.0.0
            href:
              type: string
              example: api01.j1led.com/travelTimes
            items:
              type: array
              items:
                $ref: '#/components/schemas/segmentTemplate'
