openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: API Document for API Builder
    url: https://virtserver.swaggerhub.com/SacredMinds/DDAB-API/1.0.0
info:
  description: API for Data Driven API Builder
  version: "1.0.0"
  title: Data Driven API Builder
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /:
    post:
      summary: To create an API Document for provided Data Schema of XSD or JSON format
      operationId: createArtifact
      description: To create an API Document for provided Data Schema of XSD or JSON format
      responses:
        '200':
          description: item created
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormWrapper'
        description: Inventory item to add
components:
  schemas:
    FormWrapper:
      type: object
      required:
        - title
        - description
        - host
        - basePath
        - artifactType
        - file
      properties:
        title:
          type: string
        description:
          type: string
          example: Widget Adapter
        host:
          type: string
          example: app.cg.osce
        basepath:
          type: string
          example: /v1/api
        artifactType:
          type: string
          example: JSON/YAML/RAML
        file:
          type: string
          example: http://someendpoint/document.xsd
    SuccessResponse:
      type: object
      properties:
        artifactURL:
          type: string
          example: https://petstore.swagger.io/v2/swagger.json
