openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Business-Banking'
  description: ''
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/tyfones/Banking/1.0.0
paths:
  /users:
    get:
      description: Add user
      parameters: 
        - in: query
          name: UUIDs
          required: true
          description: UUID number of employee
          schema:
            type: string
        - in: query
          name: first_name
          required: true
          description: Users first Name
          schema:
            type: string
        - in: query
          name: last_name
          required: true
          description: Users last Name
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: Status Code
                    example: 200
