openapi: 3.0.0
servers:
- url: http://{CallbackURL}
  description: The production API server
  variables:
    CallbackURL:
      # note! no enum here means it is an open value
      default: '192.168.101.98:9005'
      description: Callback URL

info:
  version: "1.0.1"
  title: AndroidVideo PE Fall Down
  description: AndroidVideo PE Fall Down API
tags:
  - name: PE Fall Down
    description: AndroidVideo PE Fall Down API
security:
  - basicAuth: []
paths:
  /:
    post:
      tags:
        - PE Fall Down
      summary: Subscribe PE Fall Down.
      description: >-
        Subscribe PE Fall Down.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Data'
                
              # required:
              #   - callbackUrl
     
      responses:
        '200':
          description: Success
          # content:
          #   application/json:
          #     schema:
          #       type: object
          #       properties:
          #         subscriberId:
          #           type: string
          #           format: uuid
          #           example: 111-222-333-444
          #         frameWidth:
          #           type: integer
          #           example: 1920
          #         frameHeight:
          #           type: integer
          #           example: 1080
        # '400':
        #   description: Subscribe failure.
        # '403':
        #   description: The uri is already exist. Multiple subscription is not allowed.
      
components:
  schemas:
    Data:
      type: object
      properties:
        command:
          type: string
          example: 'fall_down_report'
        response:
          type: string
          example: 'success'
        uuid:
          type: string
          example: ''
        cid:
          type: integer
          example: 1568793785279
        snapshot_format:
          type: string
          example: 'jpeg'
        ip:
          type: string
          example: 'rtsp://192.168.101.127:8554/CH001.sdp'
        snapshot:
          type: string
          example: 'pic(base64 string)'
        snapshot_top:
          type: string
          example: '111'
        snapshot_bottom:
          type: string
          example: '308'
        snapshot_left:
          type: string
          example: '255'
        snapshot_right:
          type: string
          example: '467'
        timestamp:
          type: string
          example: '1568793784.2057025'
                # response:
                #   type: string
                #   example: 'success'
