openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/b3371/BHV/1.0.0
info:
  description: Return a Quote  or a Certificate
  version: "1.0.0"
  title: API OPERATIONS
  contact:
    email: truong.nx@bhv.com.vn
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Certificates
    description: User can create a Quote  or a Certificate
paths:
  /Certificate:
    post:
      summary: adds a certificate item
      operationId: addCertificate
      description: Adds a Certificate to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CertificateItem'
        description: Certificate item to add
      tags:
        - Certificates
  '/Certificate/{RefNo}':
    get:
      summary: Get Certificate
      operationId: GetCertByRefNo
      description: 
        Get a Certificate by RefNo
      parameters:
        - name: RefNo
          in: path
          description: RefNo of Certificate to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Get a Certificate
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CertificateItem'
        '400':
          description: bad input parameter
      tags:
        - Certificates
components:
  schemas:
    CertificateItem:
      type: object
      required:
        - PolicyHolder
        - PolicyHolderAddress
        - OriginCountry
        - PlanID
        - Itinerary
        - PremiumType
        - DepartureDate
        - ReturnDate
        - InsuredPersonList
        - Trial
      properties:
        PNRNo:
          type: string
          example: 'f0851'
        RefNo:
          type: string
          example: '01'
        PolicyHolder:
          type: string
          example: 'HV-324242'
        PolicyHolderAddress:
          type: string
          example: '126 Nguyen Cong Tru, P. Nguyen Thai Binh, Q.1, Tp. HCM'
        PolicyHolderTel:
          type: string
          example: '0932999999'
        PolicyHolderEmail:
          type: string
          example: 'name@company.com'
        OriginCountry:
          type: string
          example: 'VN'
        PlanID:
          type: string
          example: 'AN'
        Itinerary:
          type: string
          example: 'BKK-SGN-BKK'
        PremiumType:
          type: string
          example: 'Individual'
        DepartureDate:
          type: string
          format: date-time
          example: '28/09/2019'
        ReturnDate:
          type: string
          format: date-time
          example: '30/09/2019'
        InsuredPersonList:
          $ref: '#/components/schemas/InsuredPersonList'
        Trial:
          type: integer
          format: int64
          example: 1
    InsuredPersonList:
      required:
        - name
        - DateOfBirth
        - MemberType
        - RentalCarProtection
      properties:
        name:
          type: string
          example: 'NGUYEN VAN A'
        DateOfBirth:
          type: string
          example: '28/09/1987'
        Gender:
          type: string
          example: 'M'
        Passport:
          type: string
          example: 'B1100020203'
        MemberType:
          type: string
          example: 'Applicant'
        RentalCarProtection:
          type: string
          example: 'Yes'
        RentalCarFrom:
          type: string
          example: '28/09/2010'
        RentalCarTo:
          type: string
          example: '28/09/2019'
      type: object
