openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: Mock server
    url: https://virtserver.swaggerhub.com/GLO-4003-a19/good-or-naugthy/1.0.0
info:
  description: API pour déterminer si l'assuré fut bon ou mauvais 
  version: "1.0.2"
  title: UlavalPereNoelAPI
  contact:
    email: antoine.lefrancois@ift.ulaval.ca
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: assurance-api
    description: Compte pour Système d'assurance 
paths:
  /santa/goodorbad:
    post:
      tags:
        - assurance-api
      summary: Le père Noël évalue si une personne a été bonne ou méchante dans la dernière année
      operationId: evaluateGoodOrEvil
      description: Évalue la bonté de la personne 
      responses:
        '200':
          description: 'Père Noël a terminé son évaluation'
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Eval'
            
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/Person'
        description: Personne a évalué
components:
  schemas:
    Person:
      type: object
      required:
        - name
        - birthdate
        - currentDate
      properties:
        name:
          type: string
          example: Claude Legault
        birthdate:
          type: string
          format: date
          example: '1963-05-26'
        currentDate:
          type: string
          format: date
          example: '2019-09-04'
    Eval:
      required:
        - name
        - verdict
      type: object
      properties:
        name:
          type: string
          example: Claude Legault
        primeIncrease:
          type: number
          example: 25
          maximum: 100
          minimum: 1
        verdict:
          type: string
          default: GOOD
          enum: ['GOOD', 'BAD']
          example: 'BAD'
