openapi: "3.0.0"
info:
  title: Car Monitor
  description: A service to handle cars detections
  version: "0.9.1"
servers:
  - url: 'http://localhost:8080/car_monitor/v1'
paths:
  /detected_cars:
    post:
      summary: Announce a car that crossed a border line.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Detection'
      responses:
        '200':
          description: Success
        default:
          description: Generic error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Detection:
      description: Object representing a detected car
      required:
      - division_line_id
      - timestamp
      type: object
      properties:
        division_line_id:
          description: Identifier refering to the line passed
          type: string
        timestamp:
          description: Timestamp (epoch time) when the car passed the line
          type: integer
          format: int64
        car_type:
          description: Basic categorization of the car
          type: string
    Error:
      description: Object representing an error
      type: object
      properties:
        code:
          format: int32
          description: Error code that identify of the error
          type: integer
        message:
          description: Short description of the error
          type: string
