openapi: 3.0.0
info:
  description: Zorginformatiebouwstenen (ZIBs) worden gebruikt om inhoudelijke afspraken vast te leggen ten behoeve van het standaardiseren van informatie, die gebruikt wordt in het zorgproces. Het doel van de standaardisatie is dat deze informatie uit het zorgproces wordt hergebruikt voor andere doeleinden zoals kwaliteitsregistraties, overdracht of patiëntgebonden onderzoek. Een zorginformatiebouwsteen is een informatiemodel, waarin een zorginhoudelijk concept wordt beschreven in termen van de gegevenselementen waaruit dat concept bestaat, de datatypes van die gegevenselementen etc. Zorginformatiebouwstenen zijn informatiemodellen van minimale klinische concepten, die elk meerdere gegevens in zich herbergen met een afgesproken inhoud, structuur en onderlinge relatie.
  version: "1.0.0"
  title: ZIBs - Restful API
  contact:
    name: Gündüz Aydin
    email: gaydin@dxc.com
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/DXC-Technology-NL/zibs/1.0.0
tags:
  - name: medicatiegebruik
    description: Een leesbaar overzicht en een downloadbare versie van de medicatiegebruik
paths:
  /medicatiegebruik/overzicht:
    get:
      tags:
        - medicatiegebruik
      summary: Zoek medicatiegebruik op patientnummer
      description: Een overzicht van medicatiegebruik die leesbaar is door patient
      operationId: getMedicationUseOverviewByPatientId
      parameters:
        - name: patientId
          in: query
          description: patientnummer waar de medicatiegebruik bijhoort
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/PageNumber'
        - $ref: '#/components/parameters/PageSize'
      responses:
        '200':
          description: Een overzicht van de medicaties die gebruikt zijn door de patient
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Medicatiegebruik'
        '400':
          description: Ongeldige Patientnummer verstrekt
    
        '404':
          description: Patient niet gevonden
      security:
        - api_key: []
  /medicatiegebruik:
    get:
      tags:
        - medicatiegebruik
      summary: Zoek medicatiegebruik op patientnummer
      description: Een lijst van medicatiegebruik die downloadbaar is voor patient
      operationId: getMedicationUseByPatientId
      parameters:
        - name: patientId
          in: query
          description: patientnummer bij wie hoort de medicatiegebruik
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Een overzicht van de medicaties die gebruikt zijn door de patient
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Medicatiegebruik'
            application/xml:
              schema:
                $ref: '#/components/schemas/Medicatiegebruik'
        '400':
          description: Ongeldige Patientnummer verstrekt
        '401':
           $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Patient niet gevonden
      security:
        - api_key: []
components:
  parameters:
    PageNumber:
      in: query
      name: pageNumber
      description: Page number om terug te keren
      required: false
      schema:
        type: integer
        example: 1
    PageSize:
      in: query
      name: pageSize
      description: Aantal resultaten in de pagina
      required: false
      schema:
        type: integer
        example: 10
        maximum: 100 
  schemas:
   Medicatiegebruik:
      type: object
      required:
        - ProductNaam
        - StartDatum
        - Keerdosis
        - ToedieningsWeg
        - Status
        - RedenVanVoorschrijven
      properties:
        ProductNaam:
          type: string
        StartDatum:
          type: string
          format: date-time
        EindDatum:
          type: string
          format: date-time
        Keerdosis:
          type: string
        ToedieningsWeg:
          type: string
        Status:
          type: string
          description: Medicatiegebruikstatus
          enum:
            - Active
            - Suspended
            - Aborted
            - Completed
            - Cancelled
        RedenVanVoorschrijven:
          type: string
      example:
       - ProductNaam: Paracetamol tablet 500 mg
         StartDatum: 2015-07-20T15:49:04-07:00
         EindDatum: ""
         Keerdosis: Zo nodig 500mg (=1st), max. 4x/dag
         ToedieningsWeg: Oraal
         Status: Active
       - ProductNaam: Paracetamol tablet 500 mg
         StartDatum: 2015-07-20T15:49:04-07:00
         EindDatum: ""
         Keerdosis: Zo nodig 500mg (=1st), max. 4x/dag
         ToedieningsWeg: Oraal
         Status: Active
       - ProductNaam: Paracetamol tablet 500 mg
         StartDatum: 2015-07-20T15:49:04-07:00
         EindDatum: ""
         Keerdosis: Zo nodig 500mg (=1st), max. 4x/dag
         ToedieningsWeg: Oraal
         Status: Active
       - ProductNaam: Paracetamol tablet 500 mg
         StartDatum: 2015-07-20T15:49:04-07:00
         EindDatum: ""
         Keerdosis: Zo nodig 500mg (=1st), max. 4x/dag
         ToedieningsWeg: Oraal
         Status: Active
       - ProductNaam: Paracetamol tablet 500 mg
         StartDatum: 2015-07-20T15:49:04-07:00
         EindDatum: ""
         Keerdosis: Zo nodig 500mg (=1st), max. 4x/dag
         ToedieningsWeg: Oraal
         Status: Active
       - ProductNaam: Paracetamol tablet 500 mg
         StartDatum: 2015-07-20T15:49:04-07:00
         EindDatum: ""
         Keerdosis: Zo nodig 500mg (=1st), max. 4x/dag
         ToedieningsWeg: Oraal
         Status: Active
       - ProductNaam: Paracetamol tablet 500 mg
         StartDatum: 2015-07-20T15:49:04-07:00
         EindDatum: ""
         Keerdosis: Zo nodig 500mg (=1st), max. 4x/dag
         ToedieningsWeg: Oraal
         Status: Active
       - ProductNaam: Paracetamol tablet 500 mg
         StartDatum: 2015-07-20T15:49:04-07:00
         EindDatum: ""
         Keerdosis: Zo nodig 500mg (=1st), max. 4x/dag
         ToedieningsWeg: Oraal
         Status: Active
       - ProductNaam: Paracetamol tablet 500 mg
         StartDatum: 2015-07-20T15:49:04-07:00
         EindDatum: ""
         Keerdosis: Zo nodig 500mg (=1st), max. 4x/dag
         ToedieningsWeg: Oraal
         Status: Active
       - ProductNaam: Paracetamol tablet 500 mg
         StartDatum: 2015-07-20T15:49:04-07:00
         EindDatum: ""
         Keerdosis: Zo nodig 500mg (=1st), max. 4x/dag
         ToedieningsWeg: Oraal
         Status: Active
       - ProductNaam: Paracetamol tablet 500 mg
         StartDatum: 2015-07-20T15:49:04-07:00
         EindDatum: ""
         Keerdosis: Zo nodig 500mg (=1st), max. 4x/dag
         ToedieningsWeg: Oraal
         Status: Active
       - ProductNaam: Paracetamol tablet 500 mg
         StartDatum: 2015-07-20T15:49:04-07:00
         EindDatum: ""
         Keerdosis: Zo nodig 500mg (=1st), max. 4x/dag
         ToedieningsWeg: Oraal
         Status: Active
  securitySchemes:
    api_key:
      type: apiKey
      name: appId
      in: query
  responses:
    UnauthorizedError:
      description: API key ontbreekt of is ongeldig
      headers:
        WWW_Authenticate:
          schema:
            type: string
