openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'ocx genesis products api'
  description: 'Genesis Products API allows to obtain new or updated products. It will contain the full content for each product included in the response.'
paths:
  /products/brand/{brandId}:
    get:
      summary: Obtain all new and updated Products from Genesis
      parameters:
        - in: path
          name: brandId
          required: true
          schema:
            type: string
            maxLength: 30
            
      responses:
        '200':
          description: Successful pull of products
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/products'
              
        '400':
          description: Invalid request format
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
                    description: Invalid request format 
        '409':
            description: Invalid data in request
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message: 
                     type: string
                     description: Missing or invalid data in request
                     
  /products/{productCode}:
    get:
      summary: Obtain apecific product from Genesis
      parameters:
        - in: path
          name: productCode
          required: true
          schema:
            type: string
            maxLength: 30
            
      responses:
        '200':
          description: Successful pull of products
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/product'
              
        '400':
          description: Invalid request format
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
                    description: Invalid request format 
        '409':
            description: Invalid data in request
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message: 
                     type: string
                     description: Missing or invalid data in request

components:
  schemas:
    products:
      description: Array of products
      type: array
      items: 
        $ref: '#/components/schemas/product'

    product:
      description: Model contains product information 
      properties: 
        productCode:
          type: string
          example: SA2A0154
          maxLength: 30
          
        marketingTitle:
          type: string
          example: Brightening Starter Kit
          maxLength: 4000
          
        shortDescription:
          type: string
          example: blah blah
          maxLength: 4000
          
        longDescription:
          type: string
          example: blah blah blah
          maxLength: 4000
          
        brandId:
          type: string
          example: SA
          maxLength: 5
          
        productTypeDesc:
          type: string
          example: Bundle
          maxLength: 80
        
        supplySize:
          type: string
          example: 90-Day
        
          
        maxOrderQty:
          type: number
          example: 1
          
        renewalPlans:
          type: array
          items:
            $ref: '#/components/schemas/renewalPlans'
        
        installmentPlans:
          type: array
          items:
            $ref: '#/components/schemas/installmentPlans'
            
        bundledProducts:
          type: array
          items:
            $ref: '#/components/schemas/bundledProducts'
            
        options:
          type: array
          items:
            $ref: '#/components/schemas/options'
            
        productGroup:
          type: array
          items:
            $ref: '#/components/schemas/productGroup'
        
        productVariants:
          type: array
          items:
            $ref: '#/components/schemas/productVariants'
            
    renewalPlans:
      description: Model contains product - renewal plan association 
      properties: 
        renewalPlanCode:
          type: string
          example: RSAA334
          maxLength: 30
        
        default:
          type: string
          example: true
          maxLength: 5
    
    installmentPlans:
      description: Model contains product - installment plan association
      properties: 
        installmentPlanCode:
          type: string
          example: ISAA36J
          maxLength: 30
        
        default:
          type: string
          example: true
          maxLength: 5
          
        #installmentPlanCode:
          #type: string
          #example: ISAA334
          #maxLength: 30
    
    bundledProducts:
      description: Model contains bundled products information 
      properties: 
        productCode:
          type: string
          example: SA1A0033
          properties:
            qty:
              type: number
              example: 1
              
    options:
      description: Model contains product options information
      properties: 
        optionId:
          type: string
          example: multi pay
          
    productGroup:
      description: Model contains product group information
      # no product groups is itemX
    
    productVariants:
      description: Model contains product variants information
      # no product variants is itemX
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/OceanX6/ocx_genesis_products/1.0.0
