openapi: 3.0.0
info:
  description: |
    This is a sample Petstore server.  You can find
    out more about Swagger at
    [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  version: "1.0.0"
  title: Swagger Petstore
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/aalempar/Klikin/1.0.0
paths:
  /NotifyForSolred:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - RequestId
                - Description
                - Status
              properties:
                RequestId:
                  type: string
                Description:
                  type: string
                Status:
                  type: string
            example:
              RequestId: "1234"
              Description: "Prueba"
              Status: "OK"
      responses:
        '200':
          description: Successfull
          content:
            application/json:
              schema:
                type: object       
                properties:
                  message:
                    type: string
                    example: "OK"
                  status:
                    type: integer
                    example: 204
        '400':
          description: Bad request
