openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/DocuScan/DocuScan.Blackboard/1.0.0
info:
  description: Dieses API dient als Application Blackboard. Die Verwendung ist zunächst auf das Logging beschränkt.
  version: "1.0.0"
  title: DocuScan Blackboard API
  contact:
    email: s.bartsch@docuscan.de
    name: Sebastian
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: events
    description: Alle Events
  - name: products
    description: Alle Produkte
paths:
  "/products":
    get:
      tags:
        - "products"
      summary: "Liefert eine Liste mit allen verfügbaren Produkten."
      operationId: getProducts
      responses:
        '200':
          description: Liefert alle verfügbaren Produkte
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  "/products/{productName}":
    get:
      tags:
        - "products"
      summary: "Liefert Detailsinformationen zu einem Produkt"
      operationId: getProduct
      parameters: 
        - name: productName
          in: path
          required: true
          schema:
            type: string
            example: "StorageRobot"
      responses:
        '200':
          description: Liefert das Produkt
        '404':
          description: Produkt nicht gefunden
  "/events":
    get:
      tags: 
        - "events"
      summary: "Liefert eine Liste mit allen Events"
      operationId: getEvents
      responses:
        '200':
          description: Liefert alle verfügbaren Events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
  "/events/{productName}":
    get:
      tags:
        - "events"
      summary: "Liefert die Events anhand des Produkts."
      operationId: getEventsByProduct
      parameters: 
        - name: productName
          in: path
          required: true
          schema:
            type: string
            example: "StorageRobot"
      responses:
        '200':
            $ref: "#/components/schemas/Event"
        '404':
            description: "Produkt nicht gefunden"
    post:
      tags:
        - "events"
      summary: "Legt ein neues Event für ein Produkt an."
      operationId: createEventInProduct
      parameters:
       - name: productName
         in: path
         required: true
         schema:
            type: string
            example: "StorageRobot"
       - name: body
         in: query
         required: true
         schema: 
           $ref: "#/components/schemas/Event"
      responses:
        default:
          description: "OK"
components:
    schemas:
      Event:
        type: object
        required:
            - id
            - message
            - severity
            - date
            - product
        properties:
            id:
              type: integer
              format: int64
            name:
              type: string
              example: "Es ist ein Fehler aufgetreten."
            severity:
              type: string
              description: "Die Ereignisstufe"
              example: "Error"
              enum:
                - "Fatal"
                - "Error"
                - "Warning"
                - "Information"
                - "Debug"
            date:
              type: string
              format: date-time
            product:
              $ref: "#/components/schemas/Product"
      Product:
        type: object
        required:
          - id
          - name
        properties:
          id:
            type: integer
            format: int64
          name:
            type: string
            example: "StorageRobot"
          manufacturer:
            type: string
            example: "DocuScan GmbH"
          helpUrl:
            type: string
            example: "http://help.docuscan.de/storagerobot"
