openapi: 3.0.1

info:
  title: Referrals
  description: Referral System API
  version: "1.0.2"

paths:
  /leads:
    post:
      summary: Send a new lead into the referral system
      description: Send a new lead into the referral system. Subsequent requests will always result in a new lead being created. 
      tags:
        - Leads
      security:
        - sigv4: []
          api_key: []
      parameters:
        - in: header
          name: Content-Type
          schema:
            type: string
            example: 'application/json' 
          required: true
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/SellingReferral'
                - $ref: '#/components/schemas/BuyingReferral'
      responses:
        '204':
          description: Success
        '401':
          description: Unauthorized
        '422':
          description: Validation Failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  office_id:
                    $ref: '#/components/schemas/ValidationErrors'
                  referral_type:
                    $ref: '#/components/schemas/ValidationErrors'
                  property_type:
                    $ref: '#/components/schemas/ValidationErrors'
                  bedrooms:
                    $ref: '#/components/schemas/ValidationErrors'
                  vendor_title:
                    $ref: '#/components/schemas/ValidationErrors'
                  vendor_forename:
                    $ref: '#/components/schemas/ValidationErrors'
                  vendor_surname:
                    $ref: '#/components/schemas/ValidationErrors'
                  vendor_phone:
                    $ref: '#/components/schemas/ValidationErrors'
                  vendor_email:
                    $ref: '#/components/schemas/ValidationErrors'
                  # selling
                  value:
                    $ref: '#/components/schemas/ValidationErrors'
                  address_name:
                    $ref: '#/components/schemas/ValidationErrors'
                  address_number:
                    $ref: '#/components/schemas/ValidationErrors'
                  address_line1:
                    $ref: '#/components/schemas/ValidationErrors'
                  address_line2:
                    $ref: '#/components/schemas/ValidationErrors'
                  address_line3:
                    $ref: '#/components/schemas/ValidationErrors'
                  postcode:
                    $ref: '#/components/schemas/ValidationErrors'
                  country:
                    $ref: '#/components/schemas/ValidationErrors'
                  # buying
                  budget:
                    $ref: '#/components/schemas/ValidationErrors'
                  desired_area:
                    $ref: '#/components/schemas/ValidationErrors'
components:
  schemas:
    SellingReferral:
      type: object
      properties:
        office_id:
          type: integer
        referral_type:
          type: integer
        property_type:
          type: integer
        bedrooms:
          type: integer
        vendor_title:
          type: string
        vendor_forename:
          type: string
        vendor_surname:
          type: string
        vendor_phone:
          type: string
        vendor_email:
          type: string
        vendor_address_full:
          type: string
        vendor_address_name:
          type: string
        vendor_address_number:
          type: integer
        vendor_address_line1:
          type: string
        vendor_address_line2:
          type: string
        vendor_address_line3:
          type: string
        vendor_address_line4:
          type: string
        vendor_postcode:
          type: string
        vendor_country:
          type: string
        value:
          type: integer
          description: "Value of the property to the nearest pound (£)"
        address_full:
          type: string
        address_name:
          type: string
        address_number:
          type: integer
        address_line1:
          type: string
        address_line2:
          type: string
        address_line3:
          type: string
        postcode:
          type: string
        country:
          type: string
      required:
        - office_id
        - referral_type
        - property_type
        - vendor_title
        - vendor_forename
        - vendor_surname
        - vendor_phone
        - value
        - postcode
      example:
        office_id: 1
        referral_type: 1
        budget: 210000
        property_type: 0
        vendor_title: "Mr"
        vendor_forename: "Property"
        vendor_surname: "Logic"
        vendor_phone: "01536 510060"
        vendor_email: "support@propertylogic.net"
        address_name: "Unit"
        address_number: 2
        address_line1: "Orion Park"
        address_line2: "Orion Way"
        address_line3: "Kettering"
        address_line4: "Northamptonshire"
        postcode: "NN15 6PP"
        country: "United Kingdom"
    BuyingReferral:
      type: object
      properties:
        office_id:
          type: integer
        referral_type:
          type: integer
        property_type:
          type: integer
        bedrooms:
          type: integer
        vendor_title:
          type: string
        vendor_forename:
          type: string
        vendor_surname:
          type: string
        vendor_phone:
          type: string
        vendor_email:
          type: string
        vendor_address_name:
          type: string
        vendor_address_number:
          type: integer
        vendor_address_line1:
          type: string
        vendor_address_line2:
          type: string
        vendor_address_line3:
          type: string
        vendor_address_line4:
          type: string
        vendor_postcode:
          type: string
        vendor_country:
          type: string
        budget:
          type: integer
        desired_area:
          type: string
      required:
        - office_id
        - referral_type
        - property_type
        - vendor_title
        - vendor_forename
        - vendor_surname
        - vendor_phone
        - budget
        - desired_area
      example:
        office_id: 1
        referral_type: 2
        budget: 210000
        property_type: 0
        vendor_title: "Mr"
        vendor_forename: "Property"
        vendor_surname: "Logic"
        vendor_phone: "01536 510060"
        vendor_email: "support@propertylogic.net"
        vendor_address_name: "Unit"
        vendor_address_number: 2
        vendor_address_line1: "Orion Park"
        vendor_address_line2: "Orion Way"
        vendor_address_line3: "Kettering"
        vendor_address_line4: "Northamptonshire"
        vendor_address_postcode: "NN15 6PP"
        vendor_address_country: "United Kingdom"
        desired_area: "Kettering, Northamptonshire"
    ValidationErrors:
      type: array
      items:
        type: string
  securitySchemes:
    sigv4:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "awsSigv4"
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"
