openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/hlaustralia/Revenue-Banking-API/1.0.0
info:
  description: "The Sysnet  Revenue  & Banking application is a new  addition to the  core suite  of Sysnet  
applications.  This application has been  designed to  allow venues  to  record  and balance  all 
POS till  records  for  banking & reconciliation purposes across  the venue. Venues  can 
incorporate float management, petty cash deductions, manage till sktms  and balance till reads  
from  within this  application.  Some  functionality can be performed via this  applicatton and via 
the Exceed  POS terminal to streamline process and increase security for cash management.


Default Port: 8880


Example call http://127.0.0.1:8880/userList
"

  version: "1.0.2"
  title: Revenue And Banking API
  contact:
    email: DevTeam@hlaustralia.com.au
  license:
    name: H & L Australia Pty. Ltd.
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Users
    description: User information calls
  - name: Floats
    description: Float management calls. Note that the Float feature in Sysnet is optional and some venues may choose NOT to declare floats. This means that when the Float is dispensed from the CRS, there may be no Floats in Sysnet and therefore no Float to update.
  - name: Till Read
    description: Till Read management calls
  - name: Till Skim
    description: Till skim management calls
paths:
  /userList:
    get:
      tags:
        - Users
      summary: Returns a list of Sysnet users
      operationId: usersList
      description: Returns a list of Sysnet users
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserList'
  /floatList:
    get:
      tags:
        - Floats
      summary: Returns a list of floats
      operationId: floatList
      description: Returns a list of floats
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FloatList'
  /singleFloat/{id}:
    get:
      tags:
        - Floats
      summary: Returns a float for the supplied id
      operationId: singleList
      description: Returns a float for the supplied id
      parameters:
        - in: path
          name: id
          description: The unique identifier of the float
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FloatList'
  /tillReadList:
    get:
      tags:
        - Till Read
      summary: Returns a list of till reads
      operationId: tillReadList
      description: Returns a list of till reads.
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TillRead'
  /updateTillRead:
    put:
      tags:
        - Till Read
      summary: Updates the till read for the specified id
      operationId: updateTillRead
      description: Updates the till read for the specified id. When updating the till read, the Float quantity and Float declared quantity must be provided if the Denomination quantity count includes the float.
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/TillRead'
      responses:
        '200':
          description: "Success"
  /updateFloat:
    put:
      tags:
        - Floats
      summary: Updates the float for the specified id
      operationId: updateFloat
      description: Updates the float for the specified id
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/FloatList'
      responses:
        '200':
          description: "Success"
  /tillSkimList:
    get:
      tags:
        - Till Skim
      summary: Returns a list of active till skims
      operationId: tillSkimList
      description: Returns a list of active till skims
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TillSkim'
  /processTillSkim:
    post:
      tags:
        - Till Skim
      summary: Processes a till skim for the specified id
      operationId: processTillSkim
      description: Processes the till skim for the specified id
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/TillSkim'
      responses:
        '200':
          description: "Success"
components:
  schemas:
    UserList:
      type: object
      required:
        - UserId
        - UserName
      properties:
        FirstName:
          description: The users first name
          type: string
          example: John
        Surname:
          description: The users last name
          type: string
          example: Doe
        UserId:
          description: Unique identifier of the user
          type: integer
          example: 453
        UserName:
          description: Unique for each user
          type: string
          example: JohnD
    FloatList:
      type: object
      properties:
        FloatId:
          type: integer
          example: 28
          description: Unique identifier for the float
        FloatTemplateId:
          type: integer
          example: 1
          description: Unique identifier for the float template
        PeriodID:
          type: integer
          example: 325
          description: Reporting period identifier
        SiteID:
          type: integer
          example: 1
          description: Used to identify a venue within a company group
        StationId:
          type: integer
          example: 3
          description: Unique Identifier for a Station/Till
        StationName:
          type: string
          example: Sports Bar
          description: The name of the Station/Till
        Drawer:
          type: integer
          example: 1
          description: The cash drawer ID for the Station/Till
        UserId:
          type: integer
          example: 1
          description: Unique identifier of the user
        IsHeld:
          type: integer
          example: 0
          description: The Order of the float in the queue for the Station/Till eg. 0 = current
        FloatAmount:
          type: number
          format: float
          example: 580.5
          description: The total cash amount for the float
        TimePrepared:
          type: string
          format: date-time
          example: "27/12/2018 5:00:31 AM"
          description: The date and time the float was created
        TimeAccepted:
          type: string
          format: date-time
          example: "27/12/2018 10:00:00 AM"
          description: The date and time the float was accepted by the clerk at the Station/Till
        FloatDeclaredAmount:
          type: number
          format: float
          example: 570.3
          description: The total cash amount for the float received by the clerk at the Station/Till
        AcceptedBy:
          type: integer
          example: 453
          description: The unique identifer of the user who accepted the float at the Station/Till
        Variance:
          type: number
          format: float
          example: 10.2
          description: The difference between the FloatAmount and FloatDeclaredAmount
        AuthorisedBy:
          type: integer
          example: 657
          description: The unique identifier of the Manager who autherised the float if required
        DenominationControl:
          type: boolean
          example: 1
          description: Flag to show if Denomination controll is being used for the current float. eg. 1 = true, 2 = false
        ErrorCount:
          type: integer
          example: 2
          minimum: 0
          maximum: 3
          description: The number of attempts of entering the correct float amount by the clerk. 
        FloatTenderList:
          type: array
          items:
            $ref: '#/components/schemas/FloatTenderList'
      required:
        - FloatId
        - FloatTenderList
    FloatTenderList:
      type: object
      properties:
        FloatTenderID:
          type: integer
          example: 29
          description: The unique identifier of the TenderFloatTender record
        FloatId:
          type: integer
          example: 28
          description: The identifier of the parent float
        TenderType:
          type: integer
          example: 1
          description: The identifier of the tender type eg. 1 = Cash, 8 = EFTPOS, 17 = Account etc
        TotalAmount:
          type: number
          format: float
          example: 580.5
          description: The total amount assigned to the float of this tender type
        DeclaredAmount:
          type: number
          format: float
          example: 580.5
          description: The total amount declared by the clerk for this float of this tender type
        AllowedVariance:
          type: number
          format: float
          example : 15.5
          description: The allowed difference in dollar amount between TotalAmount and DeclaredAmount
        FloatDenominationsList:
          type: array
          items:
            $ref: '#/components/schemas/FloatDenominationsList'
      required:
        - FloatTenderID
        - FloatDenominationsList
    FloatDenominationsList:
      type: object
      properties:
        FloatTenderID:
          type: integer
          example: 29
          description: The unique identifier of the TenderFloatTender record
        Denomination:
          type: integer
          example: 1
          description: The unique identifer for the denomination
        Description:
          type: string
          example: $100 note
          description: The description of the denomination
        FloatQty:
          type: integer
          example: 1
          description: The quantity of the denomination
        FloatDeclaredQty:
          type: integer
          example: 1
          description: The quantity of the denomination declared by the clerk and the Station/Till
        Amount:
          type: number
          format: float
          example: 10
          description: The numerical value of the denomination
      required:
        - Denomination
        - FloatQty
    TillRead:
      type: object
      properties:
        TenderReadID:
          type: integer
          example: 975
          description: The unique identifier for the till read
        SiteID:
          type: integer
          example: 5
          description: Used to identify a venue within a company group
        StationID:
          type: integer
          example: 1
          description: Unique Identifier for a Station/Till
        StationName:
          type: string
          example: Sports Bar
          description: The name of the Station/Till
        Drawer:
          type: integer
          example: 1
          description: The cash drawer ID for the Station/Till
        UserId:
          type: integer
          example: 1
          description: Unique identifier of the user
        Status:
          type: integer
          example: 2
          description: The status of the till read eg 0 = untouched, 1 = processed, 2 = balanced, 3 = unbalanced
        ReadTime:
          type: string
          format: date-time
          example: '10/12/2018 4:10:00 PM'
          description: The date and time the Station/Till was read
        FloatID:
          type: integer
          example: 23
          description: The unique identifier for the assigned float
        TillReadDetailsList:
          type: array
          description: An array of tender types for the till read
          items:
            $ref: '#/components/schemas/TillReadDetailsList'
      required:
        - TenderReadID
        - SiteID
        - TillReadDetailsList
    TillReadDetailsList:
      type: object
      properties:
        TenderType:
          type: integer
          example: 1
          description: The identifier of the tender type eg. 1 = Cash, 8 = EFTPOS, 17 = Account etc
        TenderName:
          type: string
          example: Cash
          description: The meaningful name of the tender type
        Amount:
          type: number
          format: float
          example: 134.6
          description: The total of all sales transactions from the Station/Till
        TillReadDenominationsList:
          type: array
          description: A list of denominations for the Station/Till
          items:
            $ref: '#/components/schemas/TillReadDenominationsList'
      required:
        - TenderType
        - TillReadDenominationsList
    TillReadDenominationsList:
      type: object
      properties:
        Denomination:
          type: integer
          example: 1
          description: The unique identifier for the denomination
        Qty:
          type: integer
          example: 2
          description: The quantity of the denomination. When updating till reads, if the count includes float amounts then float qty and float declared qty must be provided
        FloatQty:
          type: integer
          example: 2
          description: The quantity set by the float template. If floats are not used by the venue the float qty should be provided by integrating system
        FloatDeclaredQty:
          type: integer
          example: 2
          description: The quantity declared by the clerk at the Station/Till. If floats are not used by the venue the float declared qty should be provided by integrating system and should be equal to the float qty
      required:
        - Denomination
        - Qty
    TillSkim:
      type: object
      properties:
        SkimId:
          type: integer
          example: 8
          description: The unipue identifier for the till skim
        SiteID:
          type: integer
          example: 5
          description: Used to identify a venue within a company group
        TenderReadID:
          type: integer
          example: 975
          description: The unique identifier for the till read
        StationID:
          type: integer
          example: 1
          description: Unique Identifier for a Station/Till
        StationName:
          type: string
          example: Sports Bar
          description: The name of the Station/Till
        Drawer:
          type: integer
          example: 1
          description: The cash drawer ID for the Station/Till
        UserId:
          type: integer
          example: 1
          description: Unique identifier of the user
        SkimAmount:
          type: number
          format: float
          example: 100
          description: the total amount of the till skim
        SkimDateTime:
          type: string
          example: '19/12/2018 8:30:53 AM'
          description: The date and time the skim was processed
        Status:
          type: integer
          example: 1
          description: The status of the skim eg. 1 = processed
        CashTotalBeforeSkim:
          type: number
          format: float
          example: 191.6
          description: The cash total for the Station/Till prior to the skim
        TillSkimDenominationsList:
          type: array
          items:
            $ref: '#/components/schemas/TillSkimDenominationsList'
      required:
        - StationID
        - Drawer
        - UserId
        - TillSkimDenominationsList
    TillSkimDenominationsList:
      type: object
      properties:
        Denomination:
          type: integer
          example: 1
          description: The unique identifier for the denomination
        Qty:
          type: integer
          example: 2
          description: The quantity of the denomination
      required:
        - Denomination
        - Qty
