openapi: 3.0.0
info:
  version: "1.0.0"
  title: 'Price API'
  description: 'Price REST API zum Abfragen und Editieren der Preise für Shops und externe Plattformen'

# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/knature/Price-Upload-BI/1.0.0
  - url: http://{endpoint}/interface.php
security:
  - basicAuth: []
  
paths:
  /ProductsPriceEntries/{shop_id}:
    get:
      summary: Abrufen der Preise eines Shops
      description: "Ruft die Produktpreis-Zeilen eines Shops ab"
      parameters:
        - in: path
          name: shop_id
          schema:
            $ref: '#/components/schemas/SHOP-ID'
          required: true
          description: Shop-ID 
      responses:
        '200':
          description: Rückgabewerte (Produktpreis-Zeilen) eines Shops
          content:
            'application/json':
              schema:
                properties:
                  result:
                    $ref: '#/components/schemas/SuccessResultType'
                  entries:
                    description: Array mit einem Eintrag
                    type: array
                    items:
                      $ref: '#/components/schemas/ResponseProductsPriceEntry'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalError'
  /ProductsPriceEntry/{shop_id}/{pzn}:
    get:
      summary: Abrufen einer Shop spezifischen Preiszeile
      description: "Ruft einen Shop spezifischen Eintrag einer Produktpreis-Zeile ab"
      parameters:
        - in: path
          name: shop_id
          schema:
            $ref: '#/components/schemas/SHOP-ID'
          required: true
          description: Shop-ID 
        - in: path
          name: pzn
          schema:
           $ref: '#/components/schemas/PZN'
          required: true
          description: Produkt-PZN
      responses:
        '200':
          description: Rückgabewerte eines Produkt-Preis Eintrags
          content:
            'application/json':
              schema:
                properties:
                  result:
                    $ref: '#/components/schemas/SuccessResultType'
                  entries:
                    description: Array mit einem Eintrag
                    type: array
                    items:
                      $ref: '#/components/schemas/ResponseProductsPriceEntry'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalError'
     
    put:
      summary: Überschreibt einen Produkt Preis Eintrag
      description: 'Überschreibt Shop spezifisch den Eintrag eines Produkt in den Produkt-Attribute'
      parameters:
        - in: path
          name: shop_id
          schema:
            $ref: '#/components/schemas/SHOP-ID'
          required: true
          description: Shop-ID 
        - in: path
          name: pzn
          schema:
            $ref: '#/components/schemas/PZN'
          required: true
          description: Produkt-PZN
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestProductsPriceEntry'
      responses:
        200:
          description: Eintragung erfolgreich
          content:
            'application/json':
              schema:
                properties:
                  result:
                    $ref: '#/components/schemas/SuccessResultType'
                  request:
                    $ref: '#/components/schemas/RequestProductsPriceEntry'
        '409':
          $ref: '#/components/responses/EntityConflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalError'     
          
          
components:
  schemas: 
    SHOP-ID:
       type: integer
       format: int32
       maxLength: 2
    PZN:
       type: string
       pattern: '^[0-9]{8,8}$'
       maxLength: 8
       minLength: 8
    INT-FORMAT:
      type: integer
      format: int32
    NUMBER-FORMAT:
      type: number
      format: float
      example: 13,20
    SuccessResultType:
      description: Resultat Typ
      type: string
      example: 'success'

    FailureResultType:
      description: Resultat Typ
      type: string
      example: 'failure'
    
    #Request Objekte
    RequestProductsPriceEntry:
      description: Array mit Daten zum Überschreiben eines Produkt-Preislisten Eintrag
      type: object
      properties:
        price:
          $ref: '#/components/schemas/NUMBER-FORMAT'
        price_extra_charge:
          $ref: '#/components/schemas/NUMBER-FORMAT'
        price_extra_charge_second:
          $ref: '#/components/schemas/NUMBER-FORMAT'
        price_extra_charge_third:
          $ref: '#/components/schemas/NUMBER-FORMAT'
        price_ebay:
          $ref: '#/components/schemas/NUMBER-FORMAT'
        price_amazon:
          $ref: '#/components/schemas/NUMBER-FORMAT'
        tax_id:
          $ref: '#/components/schemas/INT-FORMAT'
        tax_value_percent:
          $ref: '#/components/schemas/NUMBER-FORMAT'
       
          
    #Responseobjekte
    ResponseProductsPriceEntry:
      description: Ein Shop spezifischer Produkt-Preislisten Eintrag
      type: object
      properties:
        shop_id:
          $ref: '#/components/schemas/INT-FORMAT'
        products_id:
          $ref: '#/components/schemas/INT-FORMAT'
        pzn:
          $ref: '#/components/schemas/PZN'
        price:
          $ref: '#/components/schemas/NUMBER-FORMAT'
        price_extra_charge:
          $ref: '#/components/schemas/NUMBER-FORMAT'
        price_extra_charge_second:
          $ref: '#/components/schemas/NUMBER-FORMAT'
        price_extra_charge_third:
          $ref: '#/components/schemas/NUMBER-FORMAT'
        price_ebay:
          $ref: '#/components/schemas/NUMBER-FORMAT'
        price_amazon:
          $ref: '#/components/schemas/NUMBER-FORMAT'
        msrp:
          $ref: '#/components/schemas/NUMBER-FORMAT'
        tax_id:
          $ref: '#/components/schemas/INT-FORMAT'
        tax_value_percent:
          $ref: '#/components/schemas/NUMBER-FORMAT'
        
            
  #Responses für einzelne Fehler
  responses:
    InternalError:
      description: Interner Server Fehler
      content:
        application/json:
          schema:
            type: object
            properties:
              result:
                $ref: '#/components/schemas/FailureResultType'
              error_status:
                type: string
                example: 'INTERNAL_SERVER_ERROR'
              error_code:
                type: string
                example: '500'
              errors:
                type: object
                additionalProperties:
                  type: string
            required:
              - result
              - error_status
              - error_code
              - errors
            
    UnprocessableEntity:
      description: Falsche oder fehlende Parameter übergeben
      content:
        application/json:
          schema:
            type: object
            properties:
              result:
                $ref: '#/components/schemas/FailureResultType'
              error_status:
                type: string
                example: 'UNPROCESSABLE_ENTITY'
              error_code:
                type: string
                example: '422'
              errors:
                type: object
                additionalProperties:
                  type: string
            required:
              - result
              - error_status
              - error_code
              - errors
              
    EntityConflict:
      description: Entitätskonflikt
      content:
        application/json:
          schema:
            type: object
            properties:
              result:
                $ref: '#/components/schemas/FailureResultType'
              error_status:
                type: string
                example: 'ENTITY_CONFLICT'
              error_code:
                type: string
                example: '409'
              errors:
                type: object
                additionalProperties:
                  type: string
            required:
              - result
              - error_status
              - error_code
              - errors
              
  #Security Schema
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
