openapi: 3.0.0
info:
  version: 'v1.0'
  title: 'Microservice API'
  description: 'Microservice API'
paths: 
  /v1.0/room/list:
    post:
      tags:
        - 'Room'
      summary: 'POST list room'
      description: 'POST list room'
      operationId: 'getListRoom'
      requestBody:
        description: 'List booking room request body'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/listBookingRoom'
            examples:
              success:
                $ref: '#/components/examples/listBookingRoom'
      responses:
        200:
          description: |
            List booking room response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listBookingRoomResponse'
              examples:
                successExample:
                  $ref: '#/components/examples/listBookingRoomResponse'
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        405:
          description: Method Not Allowed
        500:
          description: Internal Server Error
  /v1.0/room/create:
    post:
      tags:
        - 'Room'
      summary: 'POST Create a booking room'
      description: 'POST Create a booking room'
      operationId: 'createBookingRoom'
      requestBody:
        description: 'Create booking room request body'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createBookingRoom'
            examples:
              success:
                $ref: '#/components/examples/createBookingRoom'
      responses:
        200:
          description: |
            Booking room response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createBookingRoomResponse'
              examples:
                successExample:
                  $ref: '#/components/examples/createBookingRoomResponse'
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        405:
          description: Method Not Allowed
        500:
          description: Internal Server Error
  /v1.0/room/cancel:
    post:
      tags:
        - 'Room'
      summary: 'POST Cancel a booking room'
      description: 'POST Cancel a booking room'
      operationId: 'cancelBookingRoom'
      requestBody:
        description: 'Cancel booking room request body'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cancelBookingRoom'
            examples:
              success:
                $ref: '#/components/examples/cancelBookingRoom'
      responses:
        200:
          description: |
            Booking room response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cancelBookingRoomResponse'
              examples:
                successExample:
                  $ref: '#/components/examples/cancelBookingRoomResponse'
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        405:
          description: Method Not Allowed
        500:
          description: Internal Server Error      
components:
  schemas:
    listBookingRoom:
        type: object
        description: List Booking Room Info
        required: 
          - bookDate
          - bookTime
          - buildingName
          - roomSize
          - duration
        properties:
          bookDate:
            description: Book Date
            type: string
            format: DD/MM/YYYY
            example: 30/08/2019
          bookTime:
            description: Book Time
            type: string
            format: 13:15, 24 hour format
            example: "13:15"
          buildingName:
            description: Building Name
            type: string
            example: mm
          roomSize:
            description: Room Size
            type: string
            example: small
            enum:
            - small
            - medium
            - big
          duration:
            $ref: '#/components/schemas/duration'
    createBookingRoom:
      type: object
      description: Create Booking Room Info
      required: 
        - organizer
        - roomId
        - bookDate
        - bookTime
        - duration
      properties:
        organizer:
          description: Organizer Email
          type: string
          example: xxx@maxis.com
        roomId:
          description: Room Id
          type: string
          example: mm-8-1
        bookDate:
          description: Book Date
          type: string
          format: DD/MM/YYYY
          example: 30/08/2019
        bookTime:
          description: Book Time
          type: string
          format: 13:15, 24 hour format
          example: "13:15"
        duration:
            $ref: '#/components/schemas/duration'
    cancelBookingRoom:
      type: object
      description: Cancel Booking Room
      required: 
        - organizer
        - meetingId
      properties:
        organizer:
          description: Organizer Email
          type: string
          example: xxx@maxis.com
        meetingId:
          description: Meeting Id
          type: string
          example: 1234  
    duration:
      type: object
      description: Duration
      required:
        - unit
        - amount
      properties:
        unit:
          description: Unit
          type: string
          example: hr
          enum:
          - min
          - hr
        amount:
          description: Amount
          type: integer
          example: 3
    createBookingRoomResponse:
      type: object
      description: Create booking room respone
      properties:
        meetingid:
          description: Meeting Id
          type: string
          example: 1234
        organizer:
          description: Organizer Email
          type: string
          example: xxx@maxis.com
        roomId:
          description: Room Id
          type: string
          example: mm-8-1 
        imageUrl:
          description: Image Url
          type: string
          example: https://prod-int-chatbot.maxis.com.my/chatbot_images/roomImg/8-1.JPG
        roomName:
          description: Room Name
          type: string
          example: RES_MM_L8_1_Formal_12pax_TV
        start:
          description: Start time
          type: string
          example: 30/08/2019 13:15
        end:
          description: End time
          type: string
          example: 30/08/2019 16:15
    cancelBookingRoomResponse:
      type: object
      description: Create booking room respone
      properties:
        meetingid:
          description: Meeting Id
          type: string
          example: 1234
        organizer:
          description: Organizer Email
          type: string
          example: xxx@maxis.com
        roomId:
          description: Room Id
          type: string
          example: mm-8-1 
        imageUrl:
          description: Image Url
          type: string
          example: https://prod-int-chatbot.maxis.com.my/chatbot_images/roomImg/8-1.JPG
        roomName:
          description: Room Name
          type: string
          example: RES_MM_L8_1_Formal_12pax_TV
        start:
          description: Start time
          type: string
          example: 30/08/2019 13:15
        end:
          description: End time
          type: string
          example: 30/08/2019 16:15
        status:
          description: Status
          type: string
          example: cancel  
    listBookingRoomResponse:
      type: object
      description: List booking room respone
      properties:
        room:
          description: Room
          type: array
          items:
             $ref: '#/components/schemas/room'
    room:
      type: object
      description: Room
      properties:
        id:
          description: Id
          type: string
          example: mm-8-1
        imageUrl:
          description: Image Url
          type: string
          example: https://prod-int-chatbot.maxis.com.my/chatbot_images/roomImg/8-1.JPG
  examples:
    listBookingRoom:
      value: 
        bookDate: '30/08/2019'
        bookTime: '13:15'
        buildingName: 'mm'
        roomSize: 'small'
        duration: 
          unit: 'hr'
          amount: 3
    createBookingRoom:
      value: 
        organizer: 'xxx@maxis.com'
        roomId: 'mm-8-1'
        bookDate: '30/08/2019'
        bookTime: '13:15'
        duration: 
          unit: 'hr'
          amount: 3
    cancelBookingRoom:
      value:
        organizer: 'xxx@maxis.com'
        meetingId: '1234'
    createBookingRoomResponse:
      value:
        meetingid: '1234'
        organizer: 'xxx@maxis.com'
        roomId: 'mm-8-1'
        imageUrl : 'https://prod-int-chatbot.maxis.com.my/chatbot_images/roomImg/8-1.JPG'
        roomName: 'RES_MM_L8_1_Formal_12pax_TV'
        start: '30/08/2019 13:15'
        end: '30/08/2019 16:15'
    cancelBookingRoomResponse:
      value:
        meetingid: '1234'
        organizer: 'xxx@maxis.com'
        roomId: 'mm-8-1'
        imageUrl : 'https://prod-int-chatbot.maxis.com.my/chatbot_images/roomImg/8-1.JPG'
        roomName: 'RES_MM_L8_1_Formal_12pax_TV'
        start: '30/08/2019 13:15'
        end: '30/08/2019 16:15'
        status: 'cancel'
    listBookingRoomResponse:
      value:
        room: 
          - id: 'mm-8-1'
            imageUrl: 'https://prod-int-chatbot.maxis.com.my/chatbot_images/roomImg/8-1.JPG'
          - id: 'mm-8-2'
            imageUrl: 'https://prod-int-chatbot.maxis.com.my/chatbot_images/roomImg/8-2.JPG'
