openapi: 3.0.0
info:
  version: "1.0.0-oas3"
  title: CommonAPI
paths:
  /smsmessaging:
    get:
      tags:
        - Submit MT
      summary: Submit MT
      description: Submit MT operation
      operationId: smsmessaging get
      parameters:
        - in: header
          name: X-Authorize-Salt
          schema:
            type: string
            format: uuid
          required: true
        - in: query
          name: user
          required: true
          schema:
            type: string
            example: divakar.g@imimobile.com:imi@123
        - in: query
          name: senderid
          required: true
          schema:
            type: string
            example: IMIMOB
        - in: query
          name: msgtxt
          required: true
          schema:
            type: string
            example: message content
        - in: query
          name: corelationid
          required: true
          schema:
            type: string
            example: 123
        - in: query
          name: dcs
          required: true
          schema:
            type: string
            example: "0"
        - in: query
          name: rtype
          required: true
          schema:
            type: string
            example: "0"
        - in: query
          name: receipientno
          required: true
          schema:
            type: string
            example: 9999999999  
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
                example: successful operation
        '201':
          description: IP Not whitelisted
          content:
            text/plain:
              schema:
                type: string
                example: IP Not whitelisted
        '202':
          description: Invalid Username
          content:
            text/plain:
              schema:
                type: string
                example: Invalid Username
        '203':
          description: Invalid Password
          content:
            text/plain:
              schema:
                type: string
                example: Invalid Password
        '204':
          description: Invalid Msisdn
          content:
            text/plain:
              schema:
                type: string
                example: Invalid Msisdn
        '205':
          description: Invalid Country Code
          content:
            text/plain:
              schema:
                type: string
                example: Invalid Country Code
        '206':
          description: Invalid Sender ID
          content:
            text/plain:
              schema:
                type: string
                example: Invalid Sender ID
        '207':
          description: Invalid DCS
          content:
            text/plain:
              schema:
                type: string
                example: Invalid DCS
        '208':
          description: Invalid Corelation ID
          content:
            text/plain:
              schema:
                type: string
                example: Invalid Corelation ID
        '209':
          description: Dnd User
          content:
            text/plain:
              schema:
                type: string
                example: Dnd User
        '210':
          description: Parameter Mismatch
          content:
            text/plain:
              schema:
                type: string
                example: Parameter Mismatch
        '211':
          description: Sender ID not configured
          content:
            text/plain:
              schema:
                type: string
                example: Sender ID not configured
        '212':
          description: No Request found
          content:
            text/plain:
              schema:
                type: string
                example: No Request found
        '213':
          description: Sending Request Fail
          content:
            text/plain:
              schema:
                type: string
                example: Sending Request Fail
        '214':
          description: Application Error
          content:
            text/plain:
              schema:
                type: string
                example: Application Error
        '215':
          description: Message Sending Fail
          content:
            text/plain:
              schema:
                type: string
                example: Message Sending Fail
        '216':
          description: Invalid apicode
          content:
            text/plain:
              schema:
                type: string
                example: Invalid apicode
        '217':
          description: Invalid Message
          content:
            text/plain:
              schema:
                type: string
                example: Invalid Message
    post:
      tags:
        - Submit MT
      summary: Submit MT
      operationId: smsmessaging post
      parameters:
        - in: header
          name: X-Authorize-Salt
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SMSMessageRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/SMSMessageRequestXML'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '201':
          description: IP Not whitelisted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '202':
          description: Invalid Username
        '203':
          description: Invalid Password
        '204':
          description: Invalid Msisdn
        '205':
          description: Invalid Country Code
        '206':
          description: Invalid Sender ID
        '207':
          description: Invalid DCS
        '208':
          description: Invalid Corelation ID
        '209':
          description: Dnd User
        '210':
          description: Parameter Mismatch
        '211':
          description: Sender ID not configured
        '212':
          description: No Request found
        '213':
          description: Sending Request Fail
        '214':
          description: Application Error
        '215':
          description: Message Sending Fail
        '216':
          description: Invalid apicode
        '217':
          description: Invalid Message

  /clicheck:
    get: 
      tags:
        - Sender ID check
      summary: Sender ID check
      description: Sender ID check
      operationId: Sender ID check
      parameters:
        - in: query
          name: user
          required: true
          schema:
            type: string
            example: divakar.g@imimobile.com:imi@123
        - in: query
          name: senderid
          required: true
          schema:
            type: string
            example: IMIMOB
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
                example: successful operation
        '206':
          description: Invalid Sender ID
          content:
            text/plain:
              schema:
                type: string
                example: Invalid Sender ID

  /ipcheck:
    get: 
      tags:
        - White-listing IP Check
      summary: Validate white-listing IP
      description: Validate white-listing IP
      operationId: whitelist-ip_validate
      parameters:
        - in: query
          name: user
          required: true
          schema:
            type: string
            example: divakar.g@imimobile.com:imi@123
        - in: query
          name: ip
          required: true
          schema:
            type: string
            example: 10.0.10.223
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
                example: successful operation 
        '201':
          description: IP Not whitelisted
          content:
            text/plain:
              schema:
                type: string
                example: IP Not whitelisted 

components:
  schemas:
    SMSMessageRequest:
      type: object
      required: 
        - user
        - password
        - senderid
        - msgtxt
        - dcs
        - receipientno
        - rtype
      properties:
        user:
          type: string
          example: divakar.g@imimobile.com
        password:
          type: string
          example: imi@123
        senderid:
          type: string
          example: IMIMOB
        msgtxt:
          type: string
          example: message content
        corelationid:
          type: string
          example: 123
        dcs:
          type: string
          example: 0
        receipientno:
          type: string
          example: 9491386089
        rtype:
          type: string
          example: 0
    SMSMessageRequestXML:
      type: object
      required: 
        - user
        - password
        - senderid
        - msgtxt
        - dcs
        - MobileNumber
        - receipientno
        - rtype
      properties:
        user:
          type: string
          example: divakar.g@imimobile.com
        password:
          type: string
          example: imi@123
        senderid:
          type: string
          example: IMIMOB
        msgtxt:
          type: string
          example: message content
        corelationid:
          type: string
          example: 123
        dcs:
          type: string
          example: 0
        MobileNumber:
          properties:
            receipientno:
              type: string
              example: 9491386089
        rtype:
          type: string
          example: 0
      xml:
        name: SMSMessageRequest
    ApiResponse:
      type: object
      properties:
        responsecode:
          type: string
          example: 200
        transid:
          type: string
          example: 0123456789
        message:
          type: string
          example: successful operation
      required:
        - responsecode
        - transid
        - message
      xml:
        name: SMSMessageResponse
    ApiErrorResponse:
      type: object
      properties:
        responsecode:
          type: string
          example: 201
        transid:
          type: string
          example: ""
        message:
          type: string
          example: IP Not whitelisted
      required:
        - responsecode
        - transid
        - message
      xml:
        name: SMSMessageResponse
