openapi: 3.0.0
info:
  version: "1.0.0"
  title: 'FairPay API'
  description: |
    # __Bevezetés__
    Jelen dokumentáció célja, hogy bemutassa a FairPay fizetési platformot, annak használatát és a kereskedő által implementálandó végpontokat. 
    
    ### Milyen előnnyel jár a FairPay fizetési platform használata?
    * __Biztonságosabb__: bankkártyás fizetéssel szemben nem kerül kényes pénzügyi adat kiadásra
    * __Kényelmesebb__: átutalással és nem rögzitett kártyás adatokkal történő kártyás vásárlással szemben akár 3 kattintással jóváhagyható
    * __Kontrollálható__: teljes mértékben a fogyasztó által inicializált és jóváhagyott

    Fizetési megoldásunk alapja, hogy az átutalással történő online fizetést egy pár kattintásos fizetési folyamattá alakítjuk függetlenül attól, hogy a fogyasztó hol bankol. Erre az új, összes EUs országban kiterjesztésre kerülő, PSD2 rendelet teremt lehetőséget. 

    # __Biztonság__
    A tranzakcióban érintett felek közötti kommunikáció hitelességének és megmásíthatatlanságának biztosítása érdekében a FairPay fizetési platform a JSON Web Token (JWT) technológiát használja a HMAC SHA256 aláírási algoritmussal. Az interfész minden pontján, ahol HTTP kérés vagy válasz törzsrészében utazik adat, azok a JWT szabványnak megfelelően kerülnek elkódolásra és aláírásra.

    A JWT szabvány egy bevált mód a végpontok közötti hiteles adattovábbításra. Egy JSON Web Token három fő részből áll, ezek a fejrész, a törzs és az aláírás. A fejrész a tokenre vonatkozó metainformációkat tartalmazza, mint a használt aláírási algoritmus, a token kibocsátásának időpontja vagy a kiállító neve. A token törzse egy tetszőleges JSON objektum, amelynek formátumát az alábbi OpenAPI leíró határozza meg. Az aláírás rész az fejrész és a törzs base64 kódolt tartalmának az aláírását tartalmazza SHA256 algoritmus szerint.

    A JWT tokenek kezeléséhez minden elterjedt programozási nyelven elérhető könnyen használható programkönyvtár, amelyek segítségével a tokenek előállítása, aláírása, hitelességének ellenőrzése egyszerűen megoldható.
    
    ### __PHP mintakód JWT token generálására__
    ```
    <?php
      require __DIR__ . '/vendor/autoload.php';
      use Firebase\JWT\JWT;
      $key = "FairPay Example API key";
      $startPaymentRequest = array(
        "successURL" => "https://mywebshop.hu/paymentSuccess.php",
        "errorURL" => "https://mywebshop.hu/paymentError.php",
        "ipnCallbackURL" => "https://mywebshop.hu/api/payments/ipn",
        "locale" => "hu_HU",
        "transactionID" => "MYWEBSHOP-2019/01",
        "description" => "MyWebshop rendelés",
        "currency" => "HUF",
        "totalAmount" => 661440,
        "merchantID" => "M00001",
        "paymentItems" => array(
          array(
            "name" => "Dell P2411h",
            "quantity" => 12,
            "unitPrice" => 55120,
            "code" => "DISPLAY01"
          )
        )
      );
      $jwt = JWT::encode($startPaymentRequest, $key);
      echo $jwt;
    ?>
    ```

    # Platform működése
    Az alábbi szekvencia diagram szemlélteti a platform működését, annak szereplőit, életciklusait és a közöttük végbemenő üzenetváltásokat.
    
    <img src="http://gbsolutions.io/wp-content/uploads/2019/09/fairpay-seq.png" />
    
    ### __Fizetés kezdeményezése__
    1. A vásárló a kiválasztja a kereskedő oldalán a FairPay fizetési módot
    2. A kereskedő háttérrendszere összeállítja a StartPaymentRequest-et és elküldi a FairPay háttérrendszerének
    3. A StartPaymentResponse-ban kapott tranzakció azonosítót a kereskedő hozzárendeli a saját tranzakciójához és eltárolja azt
    4. A kereskedő átirányítja a vásárlót a FairPay platform felületére
   
    ### __Fizetés megszakítása a FairPay platform felületén__
    5. A vásárló a FairPay platform felületén megszakítja a fizetési folyamatot
    6. FairPay átirányítja a vásárlót a sikertelen fizetést jelző oldalra
    7. Kereskedő tájékoztatja a vásárlót a fizetés sikertelenségéről
    
    ### __Sikertelen fizetés__
    8. A vásárló kiválasztja a számlavezető bankját a FairPay platform felületén
    9. A FairPay átirányítja a vásárlót a számlavezető bankjának felületére azonosítás és tranzakció engedélyezés céljából
    10. A vásárló megszakítja a folyamatot vagy nem ad engedélyt a tranzakcióra vagy egyéb tranzakciós hiba történik
    11. A számlavezető bank jelzi a sikertelen tranzakciót a FairPay platformnak
    12. FairPay átirányítja a vásárlót a sikertelen fizetést jelző oldalra
    13. Kereskedő tájékoztatja a vásárlót a fizetés sikertelenségéről
    
    ### __Sikeres fizetés__
    14. A vásárló kiválasztja a számlavezető bankját a FairPay platform felületén
    15. A FairPay átirányítja a vásárlót a számlavezető bankjának felületére azonosítás és tranzakció engedélyezés céljából
    16. A vásárló sikeresen azonosítja magát és engedélyezi a fizetést
    17. A számlavezető bank jelzi a sikeres tranzakciót a FairPay platformnak
    18. FairPay átirányítja a vásárlót a sikeres fizetést jelző oldalra
    19. Kereskedő tájékoztatja a vásárlót a fizetés sikerességéről
    
    ### __Fizetés állapotának változása__
    20. A FairPay platform folyamatosan ellenőrzi a fizetés állapotát, mindaddig amíg végállapotba nem kerül
    21. A FairPay platform eltárolja a számlavezető bank által közölt állapotot és ellenőrzi, hogy történt-e változás az előző állapothoz képest
    22. A fizetés állapotának változása esetén a FairPay platform meghívja a kereskedő által kötelezően implementálandó ipn végpontot és átadja a fizetéshez és tranzakcióhoz tartozó egyedi azonosítókat, valamint az új állapotot
    23. Opcionálisan a kereskedő tájékoztatja a vásárlót a fizetés állapotának változásáról
    
    ### __Fizetés állapotának lekérdezése__ (opcionális)
    24. A kereskedő háttérrendszere a FairPay platform által osztott egyedi azonosítóval meghívja a /payments/{paymentID}/status végpontot
    25. A FairPay platform ellenőrzi a fizetés állapotát a számlavezető banknál
    26. A FairPay platform válaszban megküldi a kereskedőnek a fizetés aktuális állapotát
    27. A kereskedő feldolgozza a válaszban visszaadott állapotot és eltárolja azt
    28. Opcionálisan a kereskedő tájékoztatja a vásárlót a fizetés állapotának változásáról
    
    # __Végpontok__ részletes leírása
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/GB-Solutions-Zrt/FairPay-API/1.0.0
paths:
  /payments:
    post:
      summary: Fizetési folyamat indítása
      description: 'Fizetés indítására szolgáló végpont. Válaszként a fizetéshez tartozó azonosító és a FairPay felületére mutató URL kerül megküldésre. A fizetéshez tartozó azonosítóval lehetséges a fizetés státuszának lekérdezése. A válasz feldolgozása után a FairPay felületére mutató URL-re szükséges a vásárlót átirányítani.'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartPaymentRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartPaymentResponse'
      parameters: []
      operationId: startPayment
      tags:
        - FairPay által implementált
  
  /payments/{paymentID}/status:
    get:
      summary: Fizetési állapot lekérdezése (opcionális)
      tags:
        - FairPay által implementált
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IPNUpdate'
      parameters:
        - schema:
            type: string
          in: path
          name: paymentID
          required: true
      description: 'Fizetési állapot lekérdezése szolgáló végpont. Válaszként a fizetéshez tartozó utolsó IPN állapot kerül elküldésre. Implementálása kereskedői oldalon opcionális, a rendszer minden státuszváltozásról IPN üzenetet küld a kereskedő által kötelezően implementálandó IPN végpontra.'
  /success:
    get:
      summary: Sikeres fizetés oldal
      tags:
        - Kereskedő által implementálandó
      responses:
        '200':
          description: Sikeres fizetést jelző oldal jelenik meg
      parameters:
        - schema:
            type: string
          in: query
          name: transactionID
          description: Kereskedő oldali tranzakció azonosító
          required: true
        - schema:
            type: string
          in: query
          name: statusCode
          required: true
          description: Fizetési művelet státuszkód
        - schema:
            type: string
          in: query
          name: statusMessage
          required: true
          description: Fizetés státuszát leíró lokalizált üzenet
        - schema:
            type: string
          in: query
          name: paymentID
          required: true
          description: A fizetés FairPay oldali azonosítója
      description: 'A FairPay fizetési oldalán sikeresen befejezett művelet után a böngésző átirányít erre az oldalra, amely az ügyfél számára a sikeres fizetést jelzi. Fontos, hogy a visszairányítás még nem jelzi hitelesen a tranzakció sikeres lezárultát, nem kezdődhet meg a teljesítés. A sikeres fizetést az IPN üzenet megérkezése jelzi.'
      
  /error:
    get:
      summary: Sikertelen fizetés oldal
      tags:
        - Kereskedő által implementálandó
      responses:
        '200':
          description: OK
      description: 'A FairPay fizetési oldalán sikertelenül befejezett művelet után a böngésző átirányít erre az oldalra, amely az ügyfél számára a sikertelen fizetést jelzi.'
      parameters:
        - schema:
            type: string
          in: query
          name: transactionID
          description: Kereskedő oldali tranzakció azonosító
          required: true
        - schema:
            type: string
          in: query
          name: statusCode
          required: true
          description: Fizetési művelet státuszkód
        - schema:
            type: string
          in: query
          name: statusMessage
          required: true
          description: Fizetés státuszát leíró lokalizált üzenet
        - schema:
            type: string
          in: query
          name: paymentID
          description: A fizetés FairPay oldali azonosítója
          required: true
          
  /ipn:
    post:
      summary: Instant Payment Notification (IPN) üzenetek fogadására szolgáló kereskedői végpont
      tags:
        - Kereskedő által implementálandó
      responses:
        '200':
          description: OK
      description: Instant Payment Notification (IPN) üzenetek fogadására szolgáló kereskedői végpont.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IPNUpdate'
              
components:
  schemas:
    StartPaymentRequest:
      title: StartPaymentRequest
      type: object
      properties:
        errorURL:
          type: string
          format: uri
          description: >
            A FairPay fizetési oldalán sikertelenül lezárult művelet után a böngésző
            átirányít az itt megadott URL-re. Az URL a kereskedői oldalon a sikertelen
            fizetést jelző oldalra kell irányítson.
          example: 'https://mywebshop.hu/paymentError.php'
        successURL:
          type: string
          format: uri
          description: 'A FairPay fizetési oldalán sikeresen befejezett művelet után a böngésző átirányít az itt megadott URL-re. Az URL a kereskedői oldalon a sikeres fizetést jelző oldalra kell irányítson. Fontos, hogy a visszairányítás még nem jelzi hitelesen a tranzakció sikeres lezárultát, nem kezdődhet meg a teljesítés. A sikeres fizetést az IPN üzenet megérkezése jelzi.'
          example: 'https://mywebshop.hu/paymentSuccess.php'
        ipnCallbackURL:
          type: string
          format: uri
          description: 'IPN (Instant Payment Notification) információk átadása számára megadott végpont. A FairPay fizetési szervere a kereskedői oldal szerverén ezt a végpontot fogja meghívni, amikor a tranzakció státusza módosul. A fizetés csak akkor tekinthető befejezettnek, ha ez a végpont meghívásra került.'
          example: 'https://mywebshop.hu/api/payments/ipn'
        locale:
          type: string
          enum:
            - hu_HU
            - en_EN
          description: A fizetőoldal nyelvi beállításai
        transactionID:
          type: string
          description: Kereskedő oldali tranzakció azonosító
          example: 'MYWEBSHOP-2019/01'
        description:
          type: string
          description: 'Vásárlási tranzakcióhoz tartozó leírás, amely megjelenik a fizetőoldalon'
          example: 'MyWebshop rendelés'
        currency:
          type: string
          enum:
            - HUF
            - USD
            - EUR
          description: A vásárlás pénzneme
        totalAmount:
          type: number
          description: "A vásárlás végösszege. Maximum 2 tizedesjegyet tartalmazhat, tizedeselválasztó karakter: '.'"
          format: double
          example: 55312
        merchantID:
          type: string
          description: 'Kereskedő azonosító kód, melyet a FairPay regisztráció során generál a FairPay'
          example: 'M00001'
        paymentItems:
          type: array
          items:
            $ref: '#/components/schemas/PaymentItem'
      required:
        - errorURL
        - successURL
        - ipnCallbackURL
        - transactionID
        - currency
        - totalAmount
        - merchantID
    
    PaymentItem:
      title: PaymentItem
      type: object
      properties:
        name:
          type: string
          description: Terméknév
          example: 'Dell P2411h'
        quantity:
          type: number
          format: int
          description: Vásárolt mennyiség
          example: 12
        unitPrice:
          type: string
          description: 'A tétel egységára'
          example: 55120
        code:
          type: string
          description: Termékkód
          example: 'DISPLAY01'
      required:
        - name
        - quantity
        - unitPrice
        - code
    
    StartPaymentResponse:
      title: StartPaymentResponse
      type: object
      properties:
        redirectTo:
          type: string
          description: A fizetési művelethez tartozó fizetőoldal, a vásárlót ide szükséges átirányítani
          example: 'https://fairpay.io/paymentPage?paymentID=FP000001'
        paymentID:
          type: string
          example: FP000001
          description: A fizetés FairPay oldali azonosítója  
    IPNUpdate:
      title: IPNUpdate
      type: object
      properties:
        paymentID:
          type: string
          description: A fizetés FairPay oldali azonosítója
          example: FP000001
        transactionID:
          type: string
          description: A tranzakció kereskedő oldali azonosítója
          example: 'MYWEBSHOP-2019/01'
        statusCode:
          type: string
          description: Fizetési művelet státuszkód
          example: 'SUCCESS'
        statusMessage:
          type: string
          description: Fizetés státuszát leíró lokalizált üzenet
          example: 'Sikeres fizetés'
