openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Client Portal API'
  description: 'This is the API for the Client Portal'
  
servers: 
  - url: https://api.b4tportal.com/v1
    description: Production server
  
  - url: https://api.clientportal.development.corp.bill4time.com/v1
    description: Sandbox Server
    

paths: 
  /users/{userID}:
    get:
      summary: Returns a user by ID.
      
      parameters:
        - name: userID
          in: path
          required: true
          description: The ID of the user to return.
          schema:
            type: integer
        
    
      responses: 
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
        '400':
          description: The specified user ID is invalid.
        '404':
          description: A user with the specified ID was not found.
