openapi: 3.0.0
info:
  title: STEMdroid course API
  version: 1.0.0
paths:
  /course/{courseId}:
    get:
      parameters: 
        - in: path
          name: courseId
          required: true
          schema:
            type: integer
            example: 12345
        - in: header
          name: customer-security-header
          required: false
          schema:
            type: integer
            example: 12312-323423-2323
      responses:
        200:
          description: This is a list of the courses in the catalog
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/course'
        500:
          $ref: '#/components/responses/500ApiError'
  /course:
    post:
      description: Add a course to the catalog
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/course'
      responses:
        200:
          description: The course has been created.
        500:
          $ref: '#/components/responses/500ApiError'
    get:
      parameters: 
        - $ref: '#/components/parameters/PageNumber'
        - $ref: '#/components/parameters/PageSize'
      responses:
        200:
          description: This is a list of the courses in the catalog
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/course'
        500:
          $ref: '#/components/responses/500ApiError'
components:
  parameters:
    PageNumber:
      in: query
      name: pageNumber
      description: Page number to return
      required: false
      schema:
        type: integer
        example: 1
    PageSize:
      in: query
      name: pageSize
      description: Number of results in the page
      required: false
      schema:
        type: integer
        example: 10
        maximum: 100    
  schemas:
    course:
      type: object
      required: 
        - name
      properties:
        id:
          type: integer
          example: 400
        name:
          type: string
          example: Lemon Water
        description:
          type: string
          example: Lemon Water
        image_title:
          type: string
          example: mineral-water-lemon-lime
        image:
          type: string
          example: https://hplussport.com/images/1234
  responses:
    500ApiError:
      description: This is an unexpected error
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: string
                example: 500
              message:
                type: string
                example: This is an error
