openapi: 3.0.0
info:
  version: '0.1.0'
  title: ''
  description: ''
paths: {}
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/DanielaKirschPatch/mypatch_celeste/0.1.0
