openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/benedict35/api-config/1.0.0
info:
  description: This is a configuration store API
  version: "1.0.0"
  title: Config API
tags:
  - name: menu
    description: menu items
  - name: project
    description: third-party project info
paths:
  /project-menu:
    get:
      tags:
        - menu
      summary: all project menus
      operationId: allMenus
      description: |
        Get all project menus
      responses:
        '200':
          description: all project menu items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectMenu'
  /project:
    get:
      tags:
        - project
      summary: all projects
      operationId: allProjects
      description: |
        Get all projects
      responses:
        '200':
          description: all projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
components:
  schemas:
    ProjectMenu:
      type: object
      required:
        - id
        - name
        - position
        - projectLink
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Ghana
        countryCode:
          type: string
          example: Ghana
        position:
          type: integer
          example: 2
        projectLink:
          type: string
          example: https://infogram.com/project/1
    Project:
      type: object
      required:
        - id
        - link
        - numberOfPages
      properties:
        id:
          type: integer
          example: 1
        tag:
          type: string
          example: country
        countryCode:
          type: string
          example: South Africa
        link:
          type: string
          example: https://infogram.com/project/hghgj
        numberOfPages:
          type: integer
          example: 4
