openapi: 3.0.0
info:
  contact:
    email: helkyn@accounttech.com

  license:
    name: AccountTECH 1.0
    url: http://www.accounttech.com
 
  version: '1.0'
  title: 'Darwin API'
  description: 'RESTFul API to pull and push AccountTECH Darwin data'
servers:
# Added by API Auto Mocking Plugins
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/AccountTECH.com/Darwin/1.0
  - url: 'https://darwin.api.transactionplan.com'
components:
  securitySchemes:
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic  
paths:
  /api/ledgerreport/{type}:
    get:
      security:
        - basicAuth: []
      tags:
      - developers,ledger,accounting
      summary: searches the general ledger
      operationId: ledgerreportPL      
      description: searched the profit and lost ledger for a given company, office and date range
      parameters:
        - name: type
          in: path
          description: the type of ledger
          required: true
          schema:
            type: string
          example: 'PL'
        - name: companyID
          in: query
          description: used to filter result for a given company
          required: false
          schema:
            type: string
          example: '1'
        - name: pageIndex
          in: query
          description: the page number to use for the data retrieval
          required: true
          schema:
            type: string
          example: '0'
        - name: dateStart
          in: query
          description: start date for filtering
          required: true
          schema:
            type: string
          example: '2000-01-01'
        - name: officeID
          in: query
          schema:
            type: string
          example: '1'
        - name: pageSize
          in: query
          schema:
            type: string
          example: '100'
        - name: dateEnd
          in: query
          description: end date for filtering data
          required: true
          schema:
            type: string
          example: '2020-12-31'
      responses:
        '200':
          description: Auto generated using Swagger Inspector
      servers:
        - url: 'https://darwin.api.transactionplan.com'
    servers:
      - url: 'https://darwin.api.transactionplan.com'
