openapi: 3.0.1
info:
  title: Retail Inventory MDC Process
  version: '1.0'
servers:
  - url: 'https://devapigw.ashleyfurniture.com/inventory/retail'
paths:
  /:
    get:
      summary: wildcard-get
      description: wildcard-get
      operationId: 5e32e5665d774148f4d433e7
      responses:
        '200':
          description: ''
  /multiple:
    get:
      summary: Multiple DC
      operationId: multiple-dc
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: apikey
      in: header
    apiKeyQuery:
      type: apiKey
      name: apikey
      in: query
security:
  - apiKeyHeader: []
  - apiKeyQuery: []
