openapi: "3.0.2"
info:
  title: "RSS API"
  description: "Reader for scientific journals"
  version: "2.5"
  termsOfService: "https://scient.org/terms"
  contact:
    name: "Scient API"
    url: "https://scient.com/api"
    email: "some_email@gmail.com"
  license:
    name: "CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)"
    url: "https://openweathermap.org/price"
servers:
 - url: http://103.125.217.63:8900
   description: feed server
 - url: http://103.125.217.63:8700
   description: journal server
 - url: http://103.125.217.63:8800
   description: user server
paths:
## journal mcs
  /category:
    get:
      tags:
        - getCategory
      summary: "get all categories"
      description: "http GET 103.125.217.63:8700/category"
      operationId: getCategory
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
        404:
          description: Not found response
          content:
            text/plain:
              schema:
                title: Weather not found
                type: string
                example: Not found
  /subcategory:
    get:
      tags:
        - getSubcategory
      summary: "get subcategory by category id"
      description: "http GET :8000/subcategory category_id==1"
      operationId: getSubategory
      parameters:
      - name: category_id
        in: query
        description: "http GET 103.125.217.63:8700/subcategory category_id==1"
        schema:
          type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
        404:
          description: Not found response
          content:
            text/plain:
              schema:
                title: Weather not found
                type: string
                example: Not found
  /journal:
    get:
      tags:
        - getJournals
      summary: "get journals.get all journals by subcategory_id"
      description: "http GET 103.125.217.63:8700/journal subcategory_id==1"
      operationId: "getJournals"
      parameters:
      - name: user_id
        in: query
        description: "1,2,3,4"
        schema:
          type: integer
      - name: subcategory_id
        in: query
        description: "1,2,3,4"
        schema:
          type: integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
        404:
          description: Not found response
          content:
            text/plain:
              schema:
                title: Weather not found
                type: string
                example: Not found
  /get_user_journals:
    get:
      tags:
        - getUserJournals
      summary: "get all user journals by user_id and page. One page include 15 feeds"
      description: "http GET 103.125.217.63:8700/get_user_journals user_id=1 page=1"
      operationId: "getUserJournals"
      parameters:
      - name: user_id
        in: query
        description: "1,2,3,4"
        schema:
          type: integer
      - name: page
        in: query
        description: "1,2,3,4"
        schema:
          type: integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
## user mcs
  /add_bookmark:
    get:
      tags:
        - addBookmark
      summary: "add bookmark to users bookmarks list"
      description: "http GET 103.125.217.63:8800/add_bookmark user_id==1 feed_id==1"
      operationId: "addBookmark"
      parameters:
      - name: user_id
        in: query
        description: "user_id==1"
        schema:
          type: integer
      - name: feed_id
        in: query
        description: "feed_id==1"
        schema:
          type: integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
  /remove_bookmark:
    get:
      tags:
        - removeBookmark
      summary: "remove bookmark from user bookmarks list"
      description: "http GET 103.125.217.63:8800/remove_bookmark user_id==1 feed_id==1"
      operationId: "removeBookmark"
      parameters:
      - name: user_id
        in: query
        description: "user_id==1"
        schema:
          type: integer
      - name: feed_id
        in: query
        description: "feed_id==1"
        schema:
          type: integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
  /add_read_feed:
    get:
      tags:
        - addFeedID
      summary: "add read feed id to users feed read list"
      description: "http GET 103.125.217.63:8800/add_read_feed user_id==1 feed_id==1"
      operationId: "addFeedID"
      parameters:
      - name: user_id
        in: query
        description: "user_id==1"
        schema:
          type: integer
      - name: feed_id
        in: query
        description: "feed_id==1"
        schema:
          type: integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
  /add_journal_id_list:
    get:
      tags:
        - addJournalID
      summary: "add journal id to users journal list"
      description: "http GET 103.125.217.63:8800/add_journal_id_list user_id==1 journal_id==1"
      operationId: "addJournalID"
      parameters:
      - name: user_id
        in: query
        description: "user_id==1"
        schema:
          type: integer
      - name: journal_id
        in: query
        description: "journal_id==1"
        schema:
          type: integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
  /remove_journal_id_list:
    get:
      tags:
        - removeJournalID
      summary: "remove journal id from users journal list"
      description: "http GET 103.125.217.63:8800/remove_journal_id_list user_id==1 journal_id==1"
      operationId: "removeJournalID"
      parameters:
      - name: user_id
        in: query
        description: "1,2,3,4"
        schema:
          type: integer
      - name: journal_id
        in: query
        description: "1,2,3,4"
        schema:
          type: integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
  /get_user_params:
    get:
      tags:
        - getUserParams
      summary: "get user data: user_id, token, statistics by user_email"
      description: "http GET 103.125.217.63:8800/get_user_params user_email=='k.valov@mail.ru'"
      operationId: "getUserParams"
      parameters:
      - name: user_email
        in: query
        description: "email k.valov@mail.ru"
        schema:
          type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
## feed mcs
  /help:
    get:
      tags:
        - help
      summary: "return API description in docstring. Only for functions in feed microservice"
      description: "http GET 103.125.217.63:8900/help f==<function_name>"
      operationId: "help"
      parameters:
      - name: f
        in: query
        description: "function_name"
        schema:
          type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
  /get_feed:
    get:
      tags:
        - getFeed
      summary: "get feed data. return journal_name, feed_id, feed_name, ga_path, abstract, authors, pub_date, link"
      description: "http GET 103.125.217.63:8900/get_feed feed_id==1"
      operationId: "getFeed"
      parameters:
      - name: feed_id
        in: query
        description: "1,2,3,4"
        schema:
          type: integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
  /get_users_feeds:
    get:
      tags:
        - getUserFeeds
      summary: "For feed based view. Return random feeds from all user journals"
      description: "http GET 103.125.217.63:8900/get_users_feeds user_id==1 page==1"
      operationId: "getUserFeeds"
      parameters:
      - name: user_id
        in: query
        description: "1,2,3,4"
        schema:
          type: integer
      - name: page
        in: query
        description: "1,2,3,4"
        schema:
          type: integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
  /get_random_feeds:
    get:
      tags:
        - getRandomFeeds
      summary: "get feed data. return journal_name, feed_id, feed_name, ga_path, abstract, authors, pub_date, link"
      description: "http GET 103.125.217.63:8900/get_random_feeds feed_id==1 page==1"
      operationId: "getRandomFeeds"
      parameters:
      - name: feed_id
        in: query
        description: "1,2,3,4"
        schema:
          type: integer
      - name: page
        in: query
        description: "1,2,3,4"
        schema:
          type: integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
  /get_journal_feeds:
    get:
      tags:
        - getJournalFeeds
      summary: "For journal based view. Get journal feeds. Page include 15 feeds"
      description: "http GET 103.125.217.63:8900/get_random_feeds feed_id==1 page==1"
      operationId: "getJournalFeeds"
      parameters:
      - name: journal_id
        in: query
        description: "1,2,3,4"
        schema:
          type: integer
      - name: page
        in: query
        description: "1,2,3,4"
        schema:
          type: integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
  /get_users_bookmarks:
    get:
      tags:
        - getUserBookamrks
      summary: "get user bookmarks"
      description: "http GET 103.125.217.63:8900/get_users_bookmarks user_id==1"
      operationId: "getUserBookamrks"
      parameters:
      - name: user_id
        in: query
        description: "1,2,3,4"
        schema:
          type: integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'

## mcs ads
  # /get_ads_by_id

components:
  schemas:
    200:
      title: Successful response
      type: object
      properties:
        placeholder:
          type: string
          description: Placeholder description
# tags:
#   - name: getFeeds
#   - name: getJournals
#   - name: getPublishers
#   - name: getCategory
#   - name: getUser
#   - name: addUser
#   - name: updateUser
