openapi: 3.0.0
info:
  version: "1.0.1-oas3"
  title: Employees Data
  description: This is the API that has the data of all Pro=mech employees.
  termsOfService: https:promech/termsofservice.com
  contact:
    name: promec
    url: promech.com
    email: promech@gmail.com
  license:
    name: Promech license
    url: https://promech/licence.com
  
paths:
  /employee:
    get:
      description: Obtain information
      parameters:
        - name: bodylimit
          in: query
          description: The amount of employes returned
          schema:
            type: integer
            minimum: 10
            maximum: 20
            example: 15
        - name: pagelimit
          in: query
          description: The pages amount of employes info
          schema:
            type: integer
            minimum: 1
            maximum: 5
            example: 2
      responses:
        '200':
          description: Successfull
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Employee'
                 
            application/xml:
              schema:
                type: object
                $ref: '#/components/schemas/Employee'
              
    post:
      description: Create a new database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  example: 4
                employee name:
                  type: string
                  example: Messi
                employee title:
                  type: string
                  example: Forward
      responses:
       200:
        description: Succesfully created a new wmployee
        
  
components:
    schemas:
      
      Employee:
          description: model of employee
          properties:
                    id:
                      type: integer
                      example: 4
                    employee name:
                      type: string
                      example: Messi
                    employee title:
                      type: string
                      example: Forwawrd
