openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
  - description: Demo server
    url: https://virtserver.swaggerhub.com/phantomID/enroll
info:
  description: This API is used to enroll user
  version: "1.0.0"
  title: Enroll
  contact:
    email: phantom@no-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: developers
    description: Operations available to regular developers
paths:
  /enroll:
    post:
      tags:
        - developers
      summary: enrolls a user's fingerprint
      operationId: enrollUser
      description: |
        By passing in appropriate images, a user's fingerprint can be enrolled
      parameters:
        - in: header
          name: version
          required: true
          schema:
            type: string
            example: 
              1.0.0:
                value: 1.0.0
                summary: version 1.0.0 of the API
              
        - in: query
          name: type
          description: the type of enrollment
          required: true
          schema:
            type: string
          examples:       
            fingerprint:         
              value: fingerprint    
              summary: enroll using finger
            # face:         
            #   value: face    
            #   summary: enroll using face
            # voice:         
            #   value: voice    
            #   summary: enroll using voice
      
      requestBody:
        content: 
          multipart/form-data:
            schema: 
              $ref: '#/components/schemas/requestBody'
              
          
      responses:
        '200':
          description: successfully enrolled/queued
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseBody'
        '400':
          description: bad input parameter

components:
  schemas:
    requestBody:
      type: object
      properties:      # Request parts
        userID:            # Part 1 (string value)
          type: string
          format: uuid
          
        referenceID:            # Part 1 (string value)
          type: string

        subType:
          type: string
          example: leftThumb || leftIndexFinger || leftMiddleFinger || rightThumb || rightIndexFinger || rightMiddleFinger

        deviceDetails:
          type: string
          example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
            

        fingerprintImages:  # Part 3 (an image)
          type: array
          items:
            type: string
            format: binary
            example: [file1,file2,file3]
                    
                    
    ResponseBody:
      type: object
      properties:
        responseCode:
          type: string
          example: 200
        responseMessage:
          type: string
          example: Enrollment Success
