openapi: 3.0.0
info:
  version: "1.0.5"
  title: 'FLS Dropsoft API'
  description: |
    With this api you are able to read the assortment for your store and post order products.
  contact:
    email: contact@tappcreative.nl
servers:
  - url: https://fls.dropsoft.nl/api/
tags:
- name: Order
  description: Send your order
- name: Assortment
  description: Get retailer assortment
paths:
  /order/{bearer}/{dryrun}:
    post: 
      tags:
      - Order
      summary: Send order
      parameters: 
        - name: bearer
          in: path
          required: true
          description: Personal retailer Bearer
          schema:
            type: string
        - name: dryrun
          in: path
          required: true
          description: Add dryrun to make a test order. If set to false the order will be processed
          schema:
            type: boolean
      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                orderlines:
                  type: array
                  items:
                    type: object
                    properties:
                      productCode:
                        type: integer
                      amount:
                        type: integer
                customer:
                    type: object
                    properties:
                      firstName:
                        type: string
                      lastName:
                        type: string
                      company:
                        type: string
                      street:
                        type: string
                      housenumber:
                        type: string
                      housenumberAdditional:
                        type: string
                      zipcode:
                        type: string
                      city:
                        type: string
                      emailaddress:
                        type: string
                      phone:
                        type: string
                delivery:
                    type: object
                    properties:
                      firstName:
                        type: string
                      lastName:
                        type: string
                      company:
                        type: string
                      street:
                        type: string
                      housenumber:
                        type: integer
                      housenumberAdditional:
                        type: string
                      zipcode:
                        type: string
                      city:
                        type: string
                      delivery_date:
                        type: string
                      delivery_note:
                        type: string
                card:
                    type: object
                    properties:
                      productCode:
                        type: string
                      message:
                        type: string
              example:   # Sample object
                  orderlines:
                    - productCode: string
                      amount: 1
                  customer:
                    firstName: string
                    lastName: string
                    company: string
                    street: string
                    housenumber: string
                    housenumberAdditional: string
                    zipcode: string
                    city: string
                    emailaddress: string
                    phone: string
                  delivery:
                    firstName: string
                    lastName: string
                    company: string
                    street: string
                    housenumber: 1
                    housenumberAdditional: string
                    zipcode: 1234AB
                    city: string
                    delivery_date: 01-01-2020
                    delivery_note: string
                  card:
                    productCode: string
                    message: string
                  
                  
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: 
                    type: string
                  order_reference: 
                    type: string
                  feedback_message: 
                    type: string
  /assortment/{bearer}:
    get:
      tags:
      - Assortment
      summary: Returns retailers assortment
      parameters: 
        - name: bearer
          in: path
          required: true
          description: Personal retailer Bearer
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  assortment: 
                    type: array
                    items:
                      type: object
                      properties:
                        product_id:
                          type: integer
                        product_name:
                          type: string
                        latin_name:
                          type: string
                        product_description:
                          type: string
                        amount_available:
                          type: integer
                        price_information:
                          type: object
                          properties:
                            currency:
                              type: string
                            price:
                              type: integer
                        extra_information:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              description:
                                type: string
                        images:
                          type: array
                          items:
                            type: object
                            properties:
                              uri:
                                type: string
                        videos:
                          type: array
                          items:
                            type: object
                            properties:
                              youtube_id:
                                type: string
