openapi: 3.0.1
info:
  title: RPM Public API
  description: API for quoting and booking orders
  version: "v2"
paths:
  /api/Order:
    get:
      tags:
        - Order
      summary: Get information about the order.
      parameters:
        - name: orderId
          in: query
          description: Order id.
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TurvoOrderInfoResponseModel'
    post:
      tags:
        - Order
      summary: >-
        Accept the quote and create a new order or create a new order without a
        quote if you have no quote id.
      requestBody:
        description: Order creation model.
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/OrderDetailsSaveRequestModel'
          application/json:
            schema:
              $ref: '#/components/schemas/OrderDetailsSaveRequestModel'
          text/json:
            schema:
              $ref: '#/components/schemas/OrderDetailsSaveRequestModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/OrderDetailsSaveRequestModel'
      responses:
        '200':
          description: The order was generated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDetailsSaveRequestModel'
    delete:
      tags:
        - Order
      summary: Cancel the order.
      parameters:
        - name: orderId
          in: query
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: The order was canceled successfully.
  /api/Quote:
    post:
      tags:
        - Quote
      summary: Generate a new quote.
      requestBody:
        description: Quote generation model.
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/QuoteGenerateRequestModel'
          application/json:
            schema:
              $ref: '#/components/schemas/QuoteGenerateRequestModel'
          text/json:
            schema:
              $ref: '#/components/schemas/QuoteGenerateRequestModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/QuoteGenerateRequestModel'
      responses:
        '200':
          description: The quote was generated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuoteGenerateResponseModel'
  /api/Quote/reject:
    put:
      tags:
        - Quote
      summary: Reject the quote.
      requestBody:
        description: The quote Id for rejection.
        content:
          application/json-patch+json:
            schema:
              type: string
              format: uuid
          application/json:
            schema:
              type: string
              format: uuid
          text/json:
            schema:
              type: string
              format: uuid
          application/*+json:
            schema:
              type: string
              format: uuid
      responses:
        '201':
          description: The quote was rejected successfully.
components:
  schemas:
    TurvoOrderInfoResponseModel:
      type: object
      properties:
        OrderId:
          type: string
          format: uuid
        ShipmentId:
          type: integer
          format: int32
        ShipmentURL:
          type: string
          nullable: true
        ShipmnetStatus:
          type: string
          nullable: true
        Pickedup:
          type: string
          format: date-time
          nullable: true
        PickedupETA:
          type: string
          format: date-time
          nullable: true
        Delivered:
          type: string
          format: date-time
          nullable: true
        DeliveryETA:
          type: string
          format: date-time
          nullable: true
      additionalProperties: false
    OrderDetailsSaveRequestModel:
      type: object
      properties:
        QuoteId:
          type: string
          format: uuid
        OriginBusinessName:
          type: string
          nullable: true
        OriginAddress:
          type: string
          nullable: true
        OriginCity:
          type: string
          nullable: true
        OriginState:
          type: string
          nullable: true
        OriginAppointmentStart:
          type: string
          format: date-time
          nullable: true
        OriginAppointmentEnd:
          type: string
          format: date-time
          nullable: true
        DestinationBusinessName:
          type: string
          nullable: true
        DestinationAddress:
          type: string
          nullable: true
        DestinationCity:
          type: string
          nullable: true
        DestinationState:
          type: string
          nullable: true
        DestinationAppointmentStart:
          type: string
          format: date-time
          nullable: true
        DestinationAppointmentEnd:
          type: string
          format: date-time
          nullable: true
        DestinationResidence:
          type: boolean
        OriginResidence:
          type: boolean
        ContactName:
          type: string
          nullable: true
        ContactPhone:
          type: string
          nullable: true
        ContactEmail:
          type: string
          nullable: true
        SpecialNotes:
          type: string
          nullable: true
        Vin:
          type: string
          nullable: true
        ExpirationDate:
          type: string
          format: date-time
        OriginZip:
          type: string
          nullable: true
        DestinationZip:
          type: string
          nullable: true
        Reference:
          type: object
          additionalProperties:
            type: string
          nullable: true
      additionalProperties: false
    QuoteGenerateRequestModel:
      required:
        - DestinationZip
        - OriginZip
        - VehicleIsDrivable
        - VehicleVin
      type: object
      properties:
        OriginZip:
          type: string
        DestinationZip:
          type: string
        DestinationCountry:
          type: integer
          format: int32
          nullable: true
        VehicleVin:
          type: string
        VehicleIsDrivable:
          type: boolean
        OriginBusinessName:
          type: string
          nullable: true
        OriginAddress:
          type: string
          nullable: true
        OriginCity:
          type: string
          nullable: true
        OriginState:
          type: string
          nullable: true
        OriginAppointmentStart:
          type: string
          format: date-time
          nullable: true
        OriginAppointmentEnd:
          type: string
          format: date-time
          nullable: true
        DestinationBusinessName:
          type: string
          nullable: true
        DestinationAddress:
          type: string
          nullable: true
        DestinationCity:
          type: string
          nullable: true
        DestinationState:
          type: string
          nullable: true
        DestinationAppointmentStart:
          type: string
          format: date-time
          nullable: true
        DestinationAppointmentEnd:
          type: string
          format: date-time
          nullable: true
        DestinationResidence:
          type: boolean
        OriginResidence:
          type: boolean
        ContactName:
          type: string
          nullable: true
        ContactPhone:
          type: string
          nullable: true
        ContactEmail:
          type: string
          nullable: true
        SpecialNotes:
          type: string
          nullable: true
      additionalProperties: false
    ShippingResponseModel:
      type: object
      properties:
        Id:
          type: integer
          format: int32
        Description:
          type: string
          nullable: true
        TransitTime:
          type: string
          nullable: true
        DaysTillPickupFromLot:
          type: integer
          format: int32
        Cost:
          type: number
          format: double
      additionalProperties: false
    QuoteGenerateResponseModel:
      type: object
      properties:
        QuoteReferenceKey:
          type: string
          format: uuid
        CheckoutURL:
          type: string
          nullable: true
        Rating:
          type: string
          nullable: true
        Shipping:
          type: array
          items:
            $ref: '#/components/schemas/ShippingResponseModel'
          nullable: true
        CurrencyAbbreviation:
          type: integer
          format: int32
        ExpirationUTC:
          type: string
          format: date-time
        QuoteGenerationRequest:
          allOf:
            - $ref: '#/components/schemas/QuoteGenerateRequestModel'
          nullable: true
      additionalProperties: false
