openapi: 3.0.0
info:
  description: |
    API for receiving information about returned devices in 
    FPC upgrade programmes
  version: "1.0.1"
  title: Grading 
  contact:
    email: devops@trueconnectivity.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: grading
    description: Operations related to grading of returned devices
paths:
  /fpc/grading:
    post:
      tags:
        - grading
      summary: Informatiom about the upgrade device
      security:
        - api_key: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Upgrade'
      responses:
        200:
          description: Sucessfully processed update
        404:
          description: The orderId not found
            
components:
  schemas:
    Upgrade:
      type: object
      required:
        - orderId
        - merchant
        - timestamp
        - status
      properties:
        orderId:
          type: string
          description: Customer order reference used for Enrollment of the device to the system used for upgrade (HITS)
        merchant:
          type: string
          description: Reference of the overall account for given teritory where the devices are being processed - for multi tenancy purposes 
        serialNumber:
          type: string
          description: Serial Number / IMEI for the product, IMEI for phone
        sku:
          type: string
          description: The identifier of the product
        grade:
          type: string
          description: The quality of the returned device
          example: "A"
        redemptionDate:
          type: string
          description: timestamp when the device has been graded
          format: date-time
        returnDate:
          type: string
          description: timestamp when the device has been graded
          format: date-time  
        timestamp:
          type: string
          description: timestamp when the device has been graded
          format: date-time
        description:
          type: string
          description: Additional information about the upgrade state
        residualValue:
          type: number
          format: double
          description: Residual for the returned device
        status:
          type: string
          description: Status of the upgrade process
          enum:
            - GRADED
            - NOT_RECEIVED
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/TrustaGo/Upgrade/1.0.0
