openapi: 3.0.0
info:
  description: ALIOTH MOCK API
  version: "1.0.0-oas3"
  title: ALIOTH MOCK API
  contact:
    email: markortal@ibayad.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:


  # SavePhoneNumberForDevice
  /SavePhoneNumberForDevice/{deviceSerialNumber}/{phoneNumber}:
    post:
      parameters:
        - in: path
          name: deviceSerialNumber
          schema:
            type: string
          required: true
        - in: path
          name: phoneNumber
          schema:
            type: string
          required: true
      responses:
        '200':
          description: item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultStringResponse'
  /DeletePhoneNumberForDevice/{deviceSerialNumber}/{phoneNumber}:
    delete:
      parameters:
        - in: path
          name: deviceSerialNumber
          schema:
            type: string
          required: true
        - in: path
          name: phoneNumber
          schema:
            type: string
          required: true
      responses:
        '200':
          description: item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultStringResponse'
  /GetDevicesSerialNumbers/{deviceKind}/{phoneNumber}:
    get:
      parameters:
        - in: path
          name: deviceKind
          schema:
            type: string
          required: true
        - in: path
          name: phoneNumber
          schema:
            type: string
          required: true
      responses:
        '200':
          description: item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultJSONResponse'
  /ConfirmReload:
    post:
      responses:
        '200':
          description: item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfirmReloadResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmReloadReuest'
        description: Inventory item to add
  /ActivateDevice:
    put:
      responses:
        '200':
          description: item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultStringResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActivateDeviceRequest'
  /CheckDeviceStatusForReload/{deviceSerialNumber}:
    get:
      parameters:
        - in: path
          name: deviceSerialNumber
          schema:
            type: string
          required: true
      responses:
        '200':
          description: item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultBooleanResponse'
  /ComputeReloadAmountForDevice:
    post:
      responses:
        '200':
          description: item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComputeReloadAmountForDeviceResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComputeReloadAmountRequest'
  /GetDeviceKindFromSerial/{deviceSerialNumber}:
    get:
      parameters:
        - in: path
          name: deviceSerialNumber
          schema:
            type: string
          required: true
      responses:
        '200':
          description: item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDeviceKindFromSerialResponse'
  /GetActivationFees/{activationMode}/{deviceSerialNumber}:
    get:
      parameters:
        - in: path
          name: activationMode
          schema:
            type: string
            enum: [CASH, DELAYED]
          required: true
        - in: path
          name: deviceSerialNumber
          schema:
            type: string
          required: true
      responses:
        '200':
          description: item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultDoubleResponse'
servers:
  - url: 'https://virtserver.swaggerhub.com/heph4estus/ALIOTH/1.0.0'
components:
  schemas:
    ComputeReloadAmountForDeviceResponse:
      type: object
      required:
        - returnStatus
        - returnDetail
        - data
      properties:
        returnStatus:
          type: string
          enum: [OK, NOK, EXCEPTION]
        returnDetail:
          type: string
          example: 'Success'
        data:
          type: object
          required:
            - reloadUnitCount
            - reloadUnitType
            - reloadAmount
          properties:
            reloadUnitCount:
              type: integer
              example: 100
            reloadUnitType:
              type: string
              enum: [DAY, WEEK, MONTH, MONEY, KWH]
            reloadAmount:
              type: number
              example: 50000
    ConfirmReloadResponse:
      type: object
      required:
        - returnStatus
        - returnDetail
        - data
      properties:
        returnStatus:
          type: string
          enum: [OK, NOK, EXCEPTION]
        returnDetail:
          type: string
          example: 'Success'
        data:
          type: object
          required:
            - reloadUnitCount
            - reloadUnitType
            - reloadAmount
            - transactionId
            - creditExpiryDate
          properties:
            reloadUnitCount:
              type: integer
              example: 100
            reloadUnitType:
              type: string
              enum: [DAY, WEEK, MONTH, MONEY, KWH]
            reloadAmount:
              type: number
              example: 10.50
            transactionId:
              type: number
              example: 1234567890
            creditExpiryDate:
              type: string
              example: '08/08/2020 12:24:00 PM'
    ConfirmReloadReuest:
      type: object
      required:
        - deviceSerialNumber
        - reloadUnitCount
        - reloadUnitType
        - customerPhoneNumber
      properties:
        deviceSerialNumber:
          type: string
          example: 'ASE-09001211100B'
        reloadUnitCount:
          type: number
          example: 200.00
        reloadUnitType:
          type: string
          enum: [DAY, WEEK, MONTH, MONEY, KWH]
        customerPhoneNumber:
          type: string
          example: '09664677367'
    ActivateDeviceRequest:
      type: object
      required:
        - activationMode
        - deviceSerialNumber
        - customerPhoneNumber
        - activatorPhoneNumber
        - activationFees
      properties:
        activationMode:
          type: string
          enum: [CASH, DELAYED]
        deviceSerialNumber:
          type: string
          example: 'ASE-09001211100B'
        activatorPhoneNumber:
          type: string
          example: '09664677367'
        activationFees:
          type: number
          example: 100.00
        customerPhoneNumber:
          type: string
          example: '09664677367'
    ComputeReloadAmountRequest:
      type: object
      required:
        - deviceSerialNumber
        - reloadUnitCount
        - reloadUnitType
      properties:
        deviceSerialNumber:
          type: string
          example: 'ASE-09001211100B'
        reloadUnitCount:
          type: number
          example: 200.00
        reloadUnitType:
          type: string
          enum: [DAY, WEEK, MONTH, MONEY, KWH]
    DefaultStringResponse:
      type: object
      required:
        - returnStatus
        - returnDetail
        - data
      properties:
        returnStatus:
          type: string
          enum: [OK, NOK, EXCEPTION]
        returnDetail:
          type: string
          example: 'Success'
        data:
          type: string
          example: 'Operation is OK'
    GetDeviceKindFromSerialResponse:
      type: object
      required:
        - returnStatus
        - returnDetail
        - data
      properties:
        returnStatus:
          type: string
          enum: [OK, NOK, EXCEPTION]
        returnDetail:
          type: string
          example: 'Success'
        data:
          type: string
          enum: [SOLAR_KIT, ENERGY_METER, UNKNOWN]
    DefaultJSONResponse:
      type: object
      required:
        - returnStatus
        - returnDetail
        - data
      properties:
        returnStatus:
          type: string
          enum: [OK, NOK, EXCEPTION]
        returnDetail:
          type: string
          example: 'Success'
        data:
          type: object
          required:
            - kind
          properties:
            kind:
              type: string
              example: "test10101"
    DefaultBooleanResponse:
      type: object
      required:
        - returnStatus
        - returnDetail
        - data
      properties:
        returnStatus:
          type: string
          enum: [OK, NOK, EXCEPTION]
        returnDetail:
          type: string
          example: 'Success'
        data:
          type: boolean
          example: true
    DefaultDoubleResponse:
      type: object
      required:
        - returnStatus
        - returnDetail
        - data
      properties:
        returnStatus:
          type: string
          enum: [OK, NOK, EXCEPTION]
        returnDetail:
          type: string
          example: 'Success'
        data:
          type: number
          example: 1000.50
