openapi: 3.0.0
info:
  version: "2.1.0"
  title: 'incadea APIs - Basic Package'
  description: 'Encloses the APIs, which cover the basic needs, such as login, master data, etc.'
tags:
  - name: Basic 
  
paths: 
  /api/login:   
    post:
      operationId: "Login"
      summary: "The initial authentication request"
      description: "The initial authentication, which is performed in two steps. First the credentials are checked against the Active Directory of the DMS system. Only if successful, the credentials are verified against the requested DMS."
      tags: 
      - Basic
      parameters:
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/AcceptLanguage"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                  - UserName
                  - Password
                  - BackendCode
              properties:
                UserName:
                  description: "The name of the Active Directory user without the domain name"
                  type: string
                  example: "salesperson"
                Password:
                  description: "The password of the provided Active Directory user"
                  type: string
                  format: password
                  example: "MyPassword1"
                BackendCode:
                  description: "The unique identifier of the DMS instance, to which the authentication is required"
                  type: string
                  example: "INC001"    
      responses:
        "200":
          description: "The token has returned successfully"
          headers:
            Content-Language:
              $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/headers/ContentLanguage"   
          content:
            application/json:
              schema:
                type: object
                required:
                  - SessionToken
                  - ExpiresOn
                properties:
                  SessionToken:
                    description: "The session token"                           
                    type: string
                    example: "BTZej7W4/stndwNStdUC/EI32tvX8gIrsfMfFvMXQp4YHPfz56itnjD3dHLwZRMSi0vJzJCvMoEgYjXr2/8YiR/bS2J/sLNhxYJSR7ht3MFJ8kDyJ6tsx0/xvcZlkzAuOpI1RjxkTePyWH5UCzP8iIEV4oc3N/9MyjxXo6ADxY6kGuCzMrtZQLdS/+jrylGTwhBux4aExcvxupmDx5R4ZIIIIBEZx5pHuGstb5uiMe93rGMFbltOmEhtEOXP1QHUqzDtkVe0YX0TdW/Msi/mlhOgfrpIx58A1Oy0L9/ibJurx5zeI0ds5y0buIaYdm3t21BPQUl+iP9iGOR89g4ZqDKSu3jcH7JViCwrw1U2nifQal0CltUGMbBlrgnHzmt3"
                  ExpiresOn:
                    description: "A date and time, when the provided token will be expired"
                    type: string
                    format: datetime
                    example: "2019-06-10T08:00:00+0200"
        "400":
          description: |
            The client error, which can have the following Error Codes: 
            *   101 Invalid request parameters
          content:
            application/json:
              schema:
                $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/Error" 
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/Error"
        "500":
          description: |
            The server error, which can have the following Error Codes: 
            *  110 Backend service is not found or unavailable. 
            *  111 Backend platform unexpected error
            *  112 No endpoint found with the requested URL
            *  113 Invalid SOAP action name configured
            *  114 Unexpected error
          content:
            application/json:
              schema:
                $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/Error"

  /api/companies:   
    get:
      operationId: "GetCompanies"
      summary: "Get the companies and its locations, which are accessible for the logged in user."
      tags:
        - Basic
      parameters:
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/Authorization"
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/AcceptLanguage"
      responses:
        "200":
          description: "A collection of the companies along with the locations"
          headers:
            Content-Language:
              $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/headers/ContentLanguage"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/Company"
        "400":
          description: |
            The client error, which can have the following Error Codes: 
            *   101 Invalid request parameters
          content:
            application/json:
              schema:
                $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/Error"
        "500":
          description: |
            The server error, which can have the following Error Codes: 
            *  110 Backend service is not found or unavailable. 
            *  111 Backend platform unexpected error
            *  112 No endpoint found with the requested URL
            *  113 Invalid SOAP action name configured
            *  114 Unexpected error
            * 1056 Runtime error (see Details to get more information)
          content:
            application/json:
              schema:
                $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/Error"     

  /api/companies/{CompanyName}/users/me:
    get:
      operationId: "GetCurrentUser"
      summary: "Get information about the current user"
      description: "Get infomration about the user, which was used to acquire the session token via api/login"
      tags: 
      - Basic
      parameters:
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/Authorization"
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/AcceptLanguage"
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/CompanyName"    
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/LocationIdOptional"  
      responses:
        200:
          description: "The information about the user"
          headers:
            Content-Language:
              $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/headers/ContentLanguage"   
          content:
            application/json:
              schema:   
                 $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/User"
        "400":
          description: |
            The client error, which can have the following Error Codes: 
            *   101 Invalid request parameters
          content:
            application/json:
              schema:
                $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/Error" 
        "500":
          description: |
            The server error, which can have the following Error Codes: 
            *  110 Backend service is not found or unavailable. 
            *  111 Backend platform unexpected error
            *  112 No endpoint found with the requested URL
            *  113 Invalid SOAP action name configured
            *  114 Unexpected error
          content:
            application/json:
              schema:
                $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/Error"

  /api/companies/{CompanyName}/settings:    
    get:
      operationId: "GetCompanySettings"
      summary: "Get the settings related to the company"
      description: "Get the settings related to the company, such as storage type"
      tags: 
      - Basic
      parameters:
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/Authorization"
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/AcceptLanguage"
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/CompanyName"    
      responses:
        200:
          description: "The company settings"
          headers:
            Content-Language:
              $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/headers/ContentLanguage"   
          content:
            application/json:
              schema:   
                  $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/CompanySettings"
        "400":
          description: |
            The client error, which can have the following Error Codes: 
            *   101 Invalid request parameters
          content:
            application/json:
              schema:
                $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/Error"
        "500":
          description: |
            The server error, which can have the following Error Codes: 
            *  110 Backend service is not found or unavailable. 
            *  111 Backend platform unexpected error
            *  112 No endpoint found with the requested URL
            *  113 Invalid SOAP action name configured
            *  114 Unexpected error
          content:
            application/json:
              schema:
                $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/Error"
          
  /api/companies/{CompanyName}/paymentmethods:   
    get:
      operationId: "GetPaymentMethods"
      summary: "Get the payment methods available for the online requested services"
      tags:
        - Basic
      parameters:
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/Authorization"
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/AcceptLanguage"
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/CompanyName"
      responses:
          "200":
            description: "A collection of the payment methods, which are available for the online requested services"
            headers:
              Content-Language:
                $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/headers/ContentLanguage"
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/Object"  
          "400":
            description: |
              The client error, which can have the following Error Codes: 
              *   101 Invalid request parameters
            content:
              application/json:
                schema:
                  $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/Error" 
                  
          "500":
            description: |
              The server error, which can have the following Error Codes: 
              *  110 Backend service is not found or unavailable. 
              *  111 Backend platform unexpected error
              *  112 No endpoint found with the requested URL
              *  113 Invalid SOAP action name configured
              *  114 Unexpected error
              * 1055 Online Payment Method has not been setup in FastFit Setup Application
              * 1056 Runtime error (see Details to get more information)
              * 1062 Company does not exist
            content:
              application/json:
                schema:
                  $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/Error"   
         
  /api/companies/{CompanyName}/makes:   
    get:
      operationId: "GetMakes"
      summary: "Get the makes available for the online requested services"
      tags:
        - Basic
      parameters:
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/Authorization"
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/AcceptLanguage"
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/CompanyName"
      responses:
          "200":
            description: "A collection of the makes, which are available for the online requested services"
            headers:
              Content-Language:
                $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/headers/ContentLanguage"
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/Object"
          "400":
            description: |
              The client error, which can have the following Error Codes: 
              *   101 Invalid request parameters
            content:
              application/json:
                schema:
                  $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/Error" 
          "500":
            description: |
              The server error, which can have the following Error Codes: 
              *  110 Backend service is not found or unavailable. 
              *  111 Backend platform unexpected error
              *  112 No endpoint found with the requested URL
              *  113 Invalid SOAP action name configured
              *  114 Unexpected error
              * 1056 Runtime error (see Details to get more information)
              * 1059 The Method is not implemented
              * 1062 Company does not exist
            content:
              application/json:
                schema:
                  $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/Error"    

  /api/companies/{CompanyName}/files/{FileId}:   
    get:
      operationId: "GetFile"
      summary: "Get the file based on its unique identifier"
      tags:
        - Basic
      parameters:
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/Authorization"
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/AcceptLanguage"
        - $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/parameters/CompanyName"
        - name: FileId
          description: "The unique identifier of the file."
          in: path
          required: true
          schema:
            type: string
            example: "3056bedb-5962-4de5-9bbb-641be0300034"   
      responses:
        "200":
          description: "A file content"
          headers:
            Content-Language:
              $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/headers/ContentLanguage"
          content:            
            application/json:
              schema:
                type: object
                properties:
                  Content:
                    description: "An image sent as Base64 string"
                    type: string
                    format: byte
                  MIMEType:
                    description: "The type of the file"
                    type: string
                    enum: [application/pdf, image/jpeg, image/png]
                    example: "image/jpeg"  
        "400":
          description: |
            The client error, which can have the following Error Codes: 
            *   101 Invalid request parameters
          content:
            application/json:
              schema:
                $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/Error"   
        "500":
          description: |
            The server error, which can have the following Error Codes: 
            *  110 Backend service is not found or unavailable. 
            *  111 Backend platform unexpected error
            *  112 No endpoint found with the requested URL
            *  113 Invalid SOAP action name configured
            *  114 Unexpected error
          content:
            application/json:
              schema:
                $ref: "https://api.swaggerhub.com/domains/incadea/Generic/2.1.0#/components/schemas/Error" 

servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/incadea/Basic/2.0.0
