openapi: 3.0.0

servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/AlexeyBille/bitrix24_k7/1.0.0
info:
  description: Описание апи со стороны к7
  version: "1.0.0"
  title: Интеграция битрикс24 с К7
  contact:
    email: ASBille@1cbit.ru
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Контрагенты
    description: Компании в б24, контрагенты в К7
  - name: Контакты
    description: Контакты в б24, контакты в К7
  - name: Счет
    description: Сделка в б24, счет в К7
paths:
  '/contragent/{code}':
    get:
      tags:
        - Контрагенты
      summary: Получение контрагента по его коду
      operationId: getContragent
      description: |
        Получение контрагента по его коду
      parameters:
        - in: path
          name: code
          description: Код контрагента из К7
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Результат получение контрагента по коду из К7
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contragent'
        '404':
          description: Контрагент не найден
        '500':
          description: Ошибка на стороне К7
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/contact/':
    post:
      tags:
        - Контакты
      summary: Создание контакта
      operationId: postContacts
      description: |
        Создание контакта
      requestBody:
        $ref: '#/components/requestBodies/Contact'
      responses:
        '200':
          description: Контакт успешно добавлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        '500':
          description: Ошибка на стороне К7
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/bill/':
    post:
      tags:
        - Счет
      summary: Создание счета
      operationId: postBill
      description: |
        Создание счета
      requestBody:
        $ref: '#/components/requestBodies/Bill'
      responses:
        '200':
          description: Счет успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillCreateResponse'
        '500':
          description: Ошибка на стороне К7
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/bill/{code}':
    put:
      tags:
        - Счет
      summary: Изменение счета
      operationId: putBill
      description: |
        Изменение счета
      parameters:
        - in: path
          name: code
          description: Код счета из К7
          required: true
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/Bill'
      responses:
        '200':
          description: Счет успешно изменен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillCreateResponse'
        '500':
          description: Ошибка на стороне К7
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Contragent:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 'Код контрагента в к7'
          example: '022/0000000016226'
        name:
          type: string
          example: 'ООО «Студия Пинкман» pink-man.ru'
          description: 'Наименование'
        full_name:
          type: string
          example: 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТУДИЯ ПИНКМАН"'
          description: 'Полное наименование'
        legal_address:
          type: string
          example: '109444, Москва ГОРОД, Самаркандский Квартал 137А БУЛЬВАР, корпус 11, кв.116'
          description: 'Юридический адрес'
        actual_address:
          type: string
          example: '109444, Москва ГОРОД, Самаркандский Квартал 137А БУЛЬВАР, корпус 11, кв.116'
          description: 'Фактический адрес'
        inn:
          type: string
          example: '9721052900'
          description: 'ИНН'
        kpp:
          type: string
          example: '972101001'
          description: 'КПП'
        phone:
          type: string
          example: '+7 (999) 999 99-99'
          description: 'Телефон'
        email:
          type: string
          example: 'example@mail.com'
          description: 'Email'
        office: 
          type: string
          example: 'Красноярск'
          description: 'Офис'
        manager:
          type: string
          example: 'Зубова Екатерина'
          description: 'Главный менеджер'
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
    Contact:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 'Код контакта в к7'
        contragent_id:
          type: string
          format: uuid
          example: '022/0000000016226'
          description: 'Ид контрагента к которому привязан контакт'
        full_name:
          type: string
          example: 'Иванов Иван Иванович'
          description: 'ФИО'
        position:
          type: string
          example: 'Генеральный директор'
          description: 'Должность'
        email:
          type: string
          example: 'example@mail.com'
          description: 'Email'
        phones:
          type: array
          description: 'Телефоны'
          items:
            type: string
            example: '+7 (999) 999 99 99'
    Bill:
      type: object
      properties:
        contragent_id:
          type: string
          format: uuid
          example: '022/0000000016226'
          description: 'Код контрагента в к7'
        direction:
          type: string
          example: 'Веб'
          description: 'Направление'
        manager:
          type: string
          example: 'Екатерина Зубова'
          description: 'Менеджер'
        organization:
          type: string
          example: 'ООО "Развитие бизенса"'
          description: 'Организация'
        nds:
          type: string
          example: 'Без НДС'
          description: 'Ставка НДС'
        price:
          type: number
          example: 2000.0
          description: 'Сумма счета'
        items:
          type: array
          description: 'Номенклатура'
          items:
            $ref: '#/components/schemas/Nomenclature'
    Nomenclature:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 'Ид номенклатуры в К7'
        quantity:
          type: integer
          example: 2
          description: 'Rоличество'
        price:
          type: number
          example: 1000.0
          description: 'Цена'
        sum:
          type: number
          example: 2000.0
          description: 'Сумма'
    BillCreateResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 'Код счета в К7'
        date:
          type: string
          format: date-time
          description: 'Дата'
        pdf:
          type: string
          example: '0L3QvtC80LXQvdC6....C0YPRgNCw'
          description: 'Файл pdf в формате base64'
    Error:
      type: object
      properties:
        status:
          type: string
          example: 'ERROR'
          description: 'Статус ошибки'
        message:
          type: string
          example: 'Недостаточно прав доступа'
          description: 'Описание ошибки'
    Success:
      type: object
      properties:
        status:
          type: string
          example: 'SUCCESS'
          description: 'Статус'
        message:
          type: string
          example: 'Операция выполнена успешно'
          description: 'Описание'
  requestBodies:
    Contact:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Contact'
      description: Контакт который нужно сохранить
      required: true
    Bill:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Bill'
      description: Счет который нужно создать
      required: true
