openapi: 3.0.0

info:
  version: "1.2.1"
  title: API de Cobrança do Sicred Internetbanking MEI

paths:
  /bff/cobranca/v1/cobrancas:
    post:
      tags:
        - cadastrar-cobranca
      summary: >-
        Cadastro de novas cobranças do associado (ex. boleto, cartão de cŕedito,
        QR Code)
      operationId: cadastrarCobranca
      parameters:
        - name: Content-Type
          in: header
          description: Content-Type
          required: true
          schema:
            type: string
            default: application/json;charset=UTF-8
        - name: Authorization
          in: header
          description: authorization
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CobrancaDTO'
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProtocoloDTO'
        '400':
          description: Requisição inválida
        '401':
          description: Erro de autenticação
        '403':
          description: Erro de autorização
        '404':
          description: Path inexistente
        '415':
          description: Media Type não suportado
        '422':
          description: Entidade não processável
  /bff/cobranca/v1/cobrancas/{tipoProduto}/{convenioAssociado}:
    get:
      tags:
        - consultar-cobranca-por-tipo-produto
      summary: Consulta de cobranças emitidas pelo associado por tipo de produto
      operationId: consultarCobrancasPorTipoProduto
      parameters:
        - name: Content-Type
          in: header
          description: Content-Type
          required: true
          schema:
            type: string
            default: application/json;charset=UTF-8
        - name: Authorization
          in: header
          description: authorization
          required: true
          schema:
            type: string
        - name: tipoProduto
          in: path
          description: Tipo do produto de cobrança
          required: true
          schema:
            type: string
            enum: 
            - BOLETO
        - name: convenioAssociado
          in: path
          description: Identificador do convênio de adesão do associado ao produto
          required: true
          schema:
            type: string
        - name: situacaoCobranca
          in: query
          description: Situação da cobrança
          required: true
          schema:
            type: string
            enum:
            - EM_ABERTO
            - VENCIDA
            - LIQUIDADA
        - name: periodo
          in: query
          description: Período a ser consultado
          required: true
          schema:
            type: string
            enum:
            - SETE_DIAS
            - QUINZE_DIAS
            - TRINTA_DIAS
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: '#/components/schemas/BoletoCobrancaDTO'
                    - $ref: '#/components/schemas/AdquirenciaCobrancaDTO'
        '204':
          description: Recurso não localizado
        '400':
          description: Requisição inválida
        '401':
          description: Erro de autenticação
        '403':
          description: Erro de autorização
        '404':
          description: Path inexistente
        '415':
          description: Media Type não suportado
        '422':
          description: Entidade não processável
  /bff/cobranca/v1/cobrancas/{tipoProduto}/{convenioAssociado}/{idCobranca}:
    get:
      tags:
        - detalhar-cobranca
      summary: Consulta de informações detalhadas da cobrança emitida pelo associado
      operationId: detalharCobranca
      parameters:
        - name: Content-Type
          in: header
          description: Content-Type
          required: true
          schema:
            type: string
            default: application/json;charset=UTF-8
        - name: Authorization
          in: header
          description: authorization
          required: true
          schema:
            type: string
        - name: tipoProduto
          in: path
          description: Tipo do produto de cobrança
          required: true
          schema:
            type: string
            enum: 
            - BOLETO
        - name: convenioAssociado
          in: path
          description: Identificador do convênio de adesão do associado ao produto
          required: true
          schema:
            type: string
        - name: idCobranca
          in: path
          description: Identificador da cobrança a ser detalhada
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                    - $ref: '#/components/schemas/BoletoCobrancaDTO'
                    - $ref: '#/components/schemas/AdquirenciaCobrancaDTO'
        '204':
          description: Recurso não localizado
        '400':
          description: Requisição inválida
        '401':
          description: Erro de autenticação
        '403':
          description: Erro de autorização
        '404':
          description: Path inexistente
        '415':
          description: Media Type não suportado
        '422':
          description: Entidade não processável
  /bff/cobranca/v1/pagadores:
    get:
      tags:
        - consultar-pagadores
      summary: Consulta lista de pagadores de cobrança cadastrados pelo associado
      operationId: consultarPagadores
      parameters:
        - name: Content-Type
          in: header
          description: Content-Type
          required: true
          schema:
            type: string
            default: application/json;charset=UTF-8
        - name: Authorization
          in: header
          description: authorization
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PagadorCobrancaDTO'
        '204':
          description: Recurso não localizado
        '400':
          description: Requisição inválida
        '401':
          description: Erro de autenticação
        '403':
          description: Erro de autorização
        '404':
          description: Path inexistente
        '415':
          description: Media Type não suportado
        '422':
          description: Entidade não processável
  /bff/cobranca/v1/pagadores/{oidPagador}:
    get:
      tags:
        - consultar-pagador
      summary: Consulta pagador cadastrado pelo associado
      operationId: consultarPagador
      parameters:
        - name: Content-Type
          in: header
          description: Content-Type
          required: true
          schema:
            type: string
            default: application/json;charset=UTF-8
        - name: Authorization
          in: header
          description: authorization
          required: true
          schema:
            type: string
        - name: oidPagador
          in: path
          description: Identificador único do pagador
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagadorCobrancaDTO'
        '204':
          description: Recurso não localizado
        '400':
          description: Requisição inválida
        '401':
          description: Erro de autenticação
        '403':
          description: Erro de autorização
        '404':
          description: Path inexistente
        '415':
          description: Media Type não suportado
        '422':
          description: Entidade não processável
    delete:
      tags:
        - excluir-pagador
      summary: Exclusão de pagadores (sacados) cadastrados pelo associado
      operationId: excluirPagador
      parameters:
        - name: Content-Type
          in: header
          description: Content-Type
          required: true
          schema:
            type: string
            default: application/json;charset=UTF-8
        - name: Authorization
          in: header
          description: authorization
          required: true
          schema:
            type: string
        - name: oidPagador
          in: path
          description: Identificador único do pagador
          required: true
          schema:
            type: string
      responses:
        '204':
          description: OK
        '400':
          description: Requisição inválida
        '401':
          description: Erro de autenticação
        '403':
          description: Erro de autorização
        '404':
          description: Path inexistente
        '415':
          description: Media Type não suportado
        '422':
          description: Entidade não processável
  /bff/cobranca/v1/pagadores/{oidPagador}/configuracao:
    put:
      tags:
        - configurar-pagador
      summary: Configura parâmetros de cobrança utilizados para o pagador (sacado)
      operationId: configurarPagador
      parameters:
        - name: Content-Type
          in: header
          description: Content-Type
          required: true
          schema:
            type: string
            default: application/json;charset=UTF-8
        - name: Authorization
          in: header
          description: authorization
          required: true
          schema:
            type: string
        - name: oidPagador
          in: path
          description: Identificador único do pagador
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametrosPagadorCobrancaDTO'
      responses:
        '204':
          description: OK
        '400':
          description: Requisição inválida
        '401':
          description: Erro de autenticação
        '403':
          description: Erro de autorização
        '404':
          description: Path inexistente
        '415':
          description: Media Type não suportado
        '422':
          description: Entidade não processável
  /bff/cobranca/v1/adesao-produtos:
    get:
      tags:
        - consultar-adesao-produtos
      summary: Consulta produtos de cobrança contratados pelo associado
      operationId: consultarProdutosAssociado
      parameters:
        - name: Content-Type
          in: header
          description: Content-Type
          required: true
          schema:
            type: string
            default: application/json;charset=UTF-8
        - name: Authorization
          in: header
          description: authorization
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AdesaoProdutoCobrancaDTO'
        '204':
          description: Recurso não localizado
        '400':
          description: Requisição inválida
        '401':
          description: Erro de autenticação
        '403':
          description: Erro de autorização
        '404':
          description: Path inexistente
        '415':
          description: Media Type não suportado
        '422':
          description: Entidade não processável
  /bff/cobranca/v1/adesao-produtos/{tipoProduto}/adesao-vigente:
    get:
      tags:
        - consultar-adesao-vigente
      summary: Consulta detalhes da adesão vigente (adesão principal / ativa) do associado a um tipo específico de produto de cobrança
      operationId: consultarAdesaoVigente
      parameters:
        - name: Content-Type
          in: header
          description: Content-Type
          required: true
          schema:
            type: string
            default: application/json;charset=UTF-8
        - name: Authorization
          in: header
          description: authorization
          required: true
          schema:
            type: string
        - name: tipoProduto
          in: path
          description: Tipo do produto de cobrança
          required: true
          schema:
            type: string
            enum: 
            - BOLETO
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/AdesaoProdutoCobrancaDTO'
        '204':
          description: Recurso não localizado
        '400':
          description: Requisição inválida
        '401':
          description: Erro de autenticação
        '403':
          description: Erro de autorização
        '404':
          description: Path inexistente
        '415':
          description: Media Type não suportado
        '422':
          description: Entidade não processável

servers:
  - url: 'https://virtserver.swaggerhub.com/bgbauer/Cobranca/1.2.0'
components:
  schemas:
    CobrancaDTO:
      type: object
      required:
        - convenio
        - pagador
        - tipoCobranca
        - identificador
        - dataVencimento
        - valor
        - tipoProduto
      properties:
        convenio:
          type: string
          description: identificador do convênio de cobrança
        pagador:
          $ref: '#/components/schemas/PagadorCobrancaDTO'
        salvarPagador:
          type: boolean
        tipoCobranca:
          type: string
          enum:
            - VENDA_PRODUTO
            - PRESTACAO_SERVICO
            - OUTRO
        identificador:
          type: string
          description: identificador da cobrança definido pelo associado (ex. número da NF origem da cobrança)
        dataVencimento:
          type: string
          format: date
        valor:
          type: number
          format: double
        juros:
          type: number
          format: double
        multa:
          type: number
          format: double
        mensagem:
          type: string
        tipoProduto:
          type: string
          description: tipo do produto de cobrança a ser utilizado
          enum:
          - BOLETO
          - ADQUIRENCIA
        dataPagamento:
          type: string
          format: date
        valorPago:
          type: number
          format: double
    AdquirenciaCobrancaDTO:
      allOf:
        - $ref: '#/components/schemas/CobrancaDTO'
        - type: object
    BoletoCobrancaDTO:
      allOf:
        - $ref: '#/components/schemas/CobrancaDTO'
        - type: object
          properties:
            nossoNumero:
              type: string
            codigoBarras:
              type: string
            linhaDigitavel:
              type: string
    ProtocoloDTO:
      type: object
      properties:
        idProtocolo:
          type: integer
        statusProtocolo:
          type: string
        retorno:
          type: string
    PagadorCobrancaDTO:
      type: object
      required:
        - nome
        - cpfCnpj
      properties:
        oidPagador:
          type: string
          description: identificador único do pagador (gerado automaticamente)
        cooperativa:
          type: string
        conta:
          type: string
        nome:
          type: string
          description: nome do pagador (requerido se identificador não informado)
        cpfCnpj:
          type: string
          description: CPF/CNPJ do pagador (requerido se identificador não informado)
    ParametrosPagadorCobrancaDTO:
      type: object
      required:
        - pagador
        - tipoCobrancaPadrao
        - informaIdentificador
        - informaMensagem
        - prazoVencimento
        - jurosPadrao
        - multaPadrao
      properties:
        pagador:
          $ref: '#/components/schemas/PagadorCobrancaDTO'
        tipoCobrancaPadrao:
          type: string
          enum:
            - VENDA_PRODUTO
            - PRESTACAO_SERVICO
            - OUTRO
        informaIdentificador:
          type: boolean
        informaMensagem:
          type: boolean
        prazoVencimento:
          type: integer
        jurosPadrao:
          type: number
          format: double
        multaPadrao:
          type: number
          format: double
    AdesaoProdutoCobrancaDTO:
      type: object
      required:
        - identificador
        - tipoProduto
        - tipoConvenio
        - dataAdesao
        - situacaoConvenio
      properties:
        identificador:
          type: string
          description: identificador do convênio de cobrança (contrato de adesão)
        tipoProduto:
          type: string
          enum:
          - BOLETO
        tipoConvenio:
          type: string
          enum:
          - EMISSAO_OPERACAO
          - OPERACAO
          - CONSULTA
          description: ações admitidas com este convênio no canal
        dataAdesao:
          type: string
          format: date
        situacaoConvenio:
          type: string
          enum:
          - ATIVO
          - PENDENTE
          - INATIVO
