openapi: 3.0.1
info:
  title: ProjectRepositoryService Web API
  description: ProjectRepositoryService Web API
  termsOfService: ConduentInternal
  contact:
    name: CAP Support
    url: https://www.Conduent.com
    email: CAP-Support@conduent.com
  license:
    name: Conduent Internal only
    url: https://www.Conduent.com
  version: "1.0.0"
servers:
# Added by API Auto Mocking Plugin
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/Conduent-DP/ProjectRepositoryService/1.0.0
- url: http://localhost:5000/
paths:
  /ProjectRepositoryService/{id}/{etag}:
    get:
      tags:
      - ProjectRepositoryService
      summary: Get Project File Stream for a specific Blob Id/Name
      description: This API list all the resources for the resource id passed
      operationId: ProjectRepositoryService_GetById
      parameters:
      - name: id
        in: path
        description: Blob Id or Name
        required: true
        schema:
          type: string
          nullable: true
      - name: etag
        in: path
        description: Optional Parameter - Etag for the blob resource
        required: true
        schema:
          type: string
          nullable: true
      responses:
        200:
          description: Resources
          content:
            '*/*':
              schema:
                type: string
                format: binary
components: {}
x-generator: NSwag v13.3.0.0 (NJsonSchema v10.1.11.0 (Newtonsoft.Json v12.0.0.0))
