openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/arunjose/Kiosk-Analytics-API/1.0.0
info:
  description: This is a simple API
  version: "1.0.0"
  title: Analytics API for Kiosk
  contact:
    email: info@dcx.no
  license:
    name: Licensed by Digital Cloud Xperience AS
paths:
  /click:
    post:
      tags:
        - Application clicks
      summary: The endpoint used to post the click on an object in the app
      operationId: postClick
      description: Use this endpoint to record a click on the object of kiosk application
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClickPostRequest'
      responses:
        '204':
          description: No Content
        '400':
          description: bad input parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    
components:
  schemas:
    ErrorResponse:
      type: object
      description: Error model
      required: 
      - code
      - message
      properties:
        code:
          type: number
          format: int
          example: 1002
          description: Error code for the error
        message:
          type: string
          example: Missing required fields
          description: The detailed error message
    ClickPostRequest:
      type: object
      required:
        - appId
        - objectId
      properties:
        appId:
          type: string
          format: uuid
          description: Id of the application
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        objectId:
          type: string
          description: Id of the object
          example: JAAJH512763AGB
