openapi: 3.0.0
info:
  description: |
    API to fetch non-transmitted entries to API calling application
    Entries can be fetched in both XML or JSON format.
    
    The Link is https://beta.onyxone.com/restapi/siport_api_call.xml?changeStatus=1
    The apikey will be provided by OnyxOne for external system
    
    You can replace xml with JSON to get the response in JSON format
  version: "1.0.0"
  title: Api Access Entries
  contact:
    email: lennert@onyx.be
servers: 
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Lennert-Onyx/ApiAccessEntries/1.0.0
  - url: 'https://beta.onyxone.com/restapi/'
    description: OnyxOne beta server
paths:
  /siport_api_call.xml:
    get:
      summary: Fetch non-transmitted entries in XML format
      operationId: getEntriesXML
      parameters:
        - name: changeStatus
          in: query
          description: changeStatus 1 will flag the entries as submitted
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: 'Note that the entry id will not be its own element, but will be the value of the entry element, there is currently no way to describe this in our API documentation editor. <br> Example: <entry ...>123 </ entry>'
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Response'
  /siport_api_call.json:
    get:
      summary: Fetch non-transmitted entries in JSON format
      operationId: getEntriesJSON
      parameters:
        - name: changeStatus
          in: query
          description: changeStatus 1 will flag the entries as submitted
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
components:
  securitySchemes:
    sessionKey:
      type: apiKey
      name: apikey
      in: header
  schemas:
    Response:
      type: array
      items:
        $ref: '#/components/schemas/SiportResponse'
      xml:
        name: 'response'
        wrapped: true
    SiportResponse:
      type: object
      properties:
        user_id:
          type: integer
          example: 99798
        onyxone_id:
          type: integer
          example: 9979882
        firstname:
          type: string
          example: 'Lennert'
        lastname:
          type: string
          example: 'Hofman'
        uin:
          type: string
          example: '96121012345'
        phone:
          type: string
          example: '0471234567'
        blacklisted:
          type: integer
          example: 0
        entries:
          type: array
          items:
            $ref: '#/components/schemas/entry'
        limosa_number:
          type: integer
          example: 123123123
        limosa_date:
          type: string
          example: '2021-03-17'
        photo:
          type: string
          description: 'Avatar in binary format'
          example: 'RDs29cfSua+KMBuoHgycSNtz7E16fpWnRaZYw20ChY4l29OvvS9o3oCgnqPLuzcIcUpZscrirIGPejaDUyXMrGiiUvn/umiru0elFYey82Vyn86dzcfNycGpbKYKdwb8KxtekaC4cHIwah0u8L55Nctro9y+tjvLDVpbcgo+3ByK7DS/iLeWO0'
        Company:
          type: string
          example: 'OnyxOnlineLearning'
        country_payrol:
          type: string
          example: 'BE'
      xml:
        name: 'siport_response'
    entry:
      description: 'Note that the id will not be its own element, but will be the value of the entry element, there is currently no way to describe this in our API documentation editor. Example: <entry ...>123</ entry>'
      type: object
      properties:
        id:
          type: integer
          example: 456
        entry_start_date:
          type: string
          example: '2020-03-16'
          xml:
            attribute: true
        entry_end_date:
          type: string
          example: '2020-04-16'
          xml:
            attribute: true
        max_access_till_date:
          type: string
          example: '2020-04-16'
          xml:
            attribute: true
        min_expiration_date:
          type: string
          example: '2020-06-20'
          xml:
            attribute: true
        job_type:
          type: integer
          example: 2
          xml:
            attribute: true
        active_entry:
          type: string
          example: 'Active'
          enum: [Active,Future]
          xml:
            attribute: true
        contractor_company_id:
          type: integer
          example: 789
          xml:
            attribute: true
        contractor_company_name:
          type: string
          example: 'OnyxOnlineLearning'
          xml:
            attribute: true
        contractor_company_cq_id:
          type: integer
          example: 987
          xml:
            attribute: true
        main_contractor_company_id:
          type: integer
          example: 789
          xml:
            attribute: true
        main_contractor_company_name:
          type: string
          example: 'OnyxOnlineLearning'
          xml:
            attribute: true
        main_contractor_company_cq_id:
          type: integer
          example: 987
          xml:
            attribute: true
        status:
          type: string
          example: 'Updated'
          enum: [New,Updated,Cancelled,Deleted]
          xml:
            attribute: true
        approved_by_email:
          type: string
          example: 'test@example.be'
          xml:
            attribute: true
