openapi: 3.0.0
info:
  version: "10.0.7"
  title: ProvidersList
  description: Common ProvidersList API
paths:
  /providers/:
    get:
      operationId: providers_list
      description: 'search Providers '
      parameters:
      - $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/PaginationQueryParameters/10.1#/components/parameters/orderingParam
      - $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/PaginationQueryParameters/10.1#/components/parameters/pageParam
      - $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/PaginationQueryParameters/10.1#/components/parameters/pageSizeParam
      - name: name
        in: query
        description: Provider name
        required: false
        schema:
          type: string
      - name: gender
        in: query
        description: Provider gender
        required: false
        schema:
          type: string
      - name: is_accepting_new_patients
        in: query
        description: 'is provider accepting new patients at any of their locations'
        required: false
        schema:
          type: boolean
      - name: plan_id
        in: query
        description: Plan ID
        required: false
        schema:
          type: string
      - name: plan_name
        in: query
        description: Plan name
        required: false
        schema:
          type: string
      - name: is_pcp
        in: query
        description: 'Boolean: is provider a pcp'
        required: false
        schema:
          type: string
      - name: language
        in: query
        description: Provider language
        required: false
        schema:
          type: string
      - name: npi
        in: query
        description: provider npi
        required: false
        schema:
          type: string
      - name: tax_id
        in: query
        description: provider tax id
        required: false
        schema:
          type: string
      - name: primary_specialty
        in: query
        description: Provider primary specialty
        required: false
        schema:
          type: string
      - name: latitude
        in: query
        required: false
        schema:
          type: string
      - name: longitude
        in: query
        required: false
        schema:
          type: string
      - name: distance
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                required:
                - count
                - results
                type: object
                properties:
                  count:
                    type: integer
                  next:
                    type: string
                  previous:
                    type: string
                  results:
                    type: array
                    items:
                      $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/ProviderModel/10.0.10#/components/schemas/Provider
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/ErrorModel/10.0.2#/components/schemas/Error'
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/ErrorModel/10.0.2#/components/schemas/Error'
      tags:
      - providers
