openapi: 3.0.0
info:
  version: "10.2.2"
  title: FAQsList
  description: Common FAQsList API
paths:
  /faqs/:
    get:
      operationId: faqs_list
      description: 'gets list of faqs'
      tags:
      - faq
      parameters:
        - in: query
          name: filter_metadata
          description: '
            the filter metadata as json to filter the faq list
            e.g. /faqs/?filter_metadata={"product_coverage_type":"dental"}
            '
          required: false
          style: form
          explode: true
          schema:
            type: string
        - $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/PaginationQueryParameters/10.1#/components/parameters/orderingParam
        - $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/PaginationQueryParameters/10.1#/components/parameters/pageParam
        - $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/PaginationQueryParameters/10.1#/components/parameters/pageSizeParam
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                required:
                - count
                - results
                type: object
                properties:
                  count:
                    type: integer
                  next:
                    type: integer
                  previous:
                    type: integer
                  results:
                    type: array
                    items:
                      $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/FAQModel/10.1.1#/components/schemas/FAQ'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/ErrorModel/10.0.2#/components/schemas/Error'
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/ErrorModel/10.0.2#/components/schemas/Error'
