openapi: 3.0.0
servers: 
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://stage.iquatic.io/stage/marine-plugin-service
  - url: https://z7du11w0h9.execute-api.us-west-2.amazonaws.com/stage/marine-plugin-service
info:
  description: Endpoints for Marine Instruments integration
  version: "1.0.0"
  title: iQuatic Marine Plugin

externalDocs:
  description: Generate Bearer Token
  url: https://app.swaggerhub.com/apis/iquatic/iQuatic_BearerToken/1.0.0

tags:
  - name: Endpoints
    
paths:
  /companies/{companyId}:
    get:
      tags:
      - Endpoints
      summary: Get a company, farms and ponds
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCompanyResponse'
      parameters: 
        - name: companyId
          in: path
          required: true
          description: The id of the company (cargill)
          schema:
            type: string
  /companies/{companyId}/farms/{farmId}:
    get:
      tags:
      - Endpoints
      summary: Get the farm info and ponds
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFarmResponse'
      parameters: 
        - name: companyId
          in: path
          required: true
          description: The id of the company (cargill)
          schema:
            type: string
        - name: farmId
          in: path
          required: true
          description: The id of the farm (test)
          schema:
            type: string
  /companies/{companyId}/metrics:
    post:
      tags:
      - Endpoints
      summary: Send metrics to iQuatic
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'
      parameters: 
        - name: companyId
          in: path
          required: true
          description: The id of the company
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                metrics:
                  type: array
                  items:
                    type: object
                    properties:
                      companyId:
                        type: string
                        description: the id of the company
                      farmId:
                        type: string
                        description: the id of the farm
                      pondId:
                        type: string
                        description: the id of the pond
                      masterId:
                        type: string
                        description: Serial id of the master 
                      ts:
                        type: integer
                        description: The timestamp of when that metric was created
                      metricId:
                        type: string
                        description: the id of the metric
                        enum: 
                          - activity-index
                          - water-temperature
                          - feed
                          - feeding-mode
                          - scheduled-feed-amount
       
                      value:
                        type: object
                        description: The corresponding value defined in Schemas section
  /companies/{companyId}/devices:
    post:
      tags:
      - Endpoints
      summary: Send devices to iQuatic
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MasterDevice'
      parameters: 
        - name: companyId
          in: path
          required: true
          description: The id of the company
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/FeederDevice'
                - $ref: '#/components/schemas/MasterDevice'
            example:
              {
                devices: [
                  {
                    type: mas,
                    model: CU-model,
                    manufacturer: CU-manufacturer,
                    gpsCoordinates: {
                      lat: 43.25,
                      long: 13.44
                    },
                    assignment: {
                      farmId: "central",
                      pondId: "1"
                    },
                    id: CU1000,
                    version: "1.0",
                    slaveFeeder: "madan",
                    slaves: [ "CC100" ],
                  },
                  {
                    type: madan,
                    id: A1,
                    model: feeder-model,
                    manufacturer: feeder-manufacturer,
                    gpsCoordinates: {
                      lat: 43.25,
                      long: 13.44
                    },
                    assignment: {
                      farmId: "central",
                      pondId: "1"
                    },
                    comm: {
                      masterId: CU1000,
                      version: "1.0",
                      id: "CC100",
                      model: CC-model
                    }
                  }
                ]
              }
              
  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    MasterDevice:
      type: object
      properties:
        devices:
          type: array
          items:
            type: object
            properties:
              devices:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Serial id for master
                    version:
                      type: string
                      description: CU version
                    slaves:
                      type: array
                      items:
                        type: string
                        description: CC id of slaves
                    slaveFeeder:
                      type: string
                      description: feeder type of slaves
                    type:
                      type: string
                      enum:
                        - mas
                    model:
                      type: string
                      description: Model of the device
                    manufacturer:
                      type: string
                      description: Device manufacturer
                    gpsCoordinates:
                      type: object
                      properties:
                        lat:
                          type: number
                        long:
                          type: number
                    assignment:
                      type: object
                      properties:
                        farmId:
                          type: string
                          description: iQuatic farm id
                        pondId:
                          type: string
                          description: iQuatic pond id
                  required: [id, version, slaves, slaveFeeder, type, model, manufacturer]
    FeederDevice:
      type: object
      properties:
        devices:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: Manufacturer id for feeder
              type:
                type: string
                enum:
                  - madan
              model:
                type: string
                description: Model of the device
              manufacturer:
                type: string
                description: Device manufacturer
              gpsCoordinates:
                type: object
                properties:
                  lat:
                    type: number
                  long:
                    type: number
              assignment:
                type: object
                properties:
                  farmId:
                    type: string
                    description: iQuatic farm id
                  pondId:
                    type: string
                    description: iQuatic pond id
              comm:
                type: object
                properties:
                  masterId:
                    type: string
                    description: Serial id of the master that controls this slave
                  version:
                    type: string
                    description: CC version
                  id:
                    type: string
                    description: CC id
                  model:
                    type: string
                    description: CC model
                required: [version, id, model]
            required: [id, type, model, manufacturer, comm]
    GetCompanyResponse:
      type: object
      properties:
        companyId:
          type: string
          description: The id of the company
        name:
          type: string
          description: The name of the company
        properties:
          type: object
          properties:
            marineId:
              type: string
        farms:
          type: array
          items:
            $ref: '#/components/schemas/GetFarmResponse'
    GetFarmResponse:
      type: object
      properties:
        companyId:
          type: string
          description: The id of the company
        farmId:
          type: string
          description: The id of the farm
        name:
          type: string
          description: The name of the farm
        ponds:
          type: array
          items:
            $ref: '#/components/schemas/GetPondResponse'
    GetPondResponse:
      type: object
      properties:
        companyId:
          type: string
          description: The id of the company
        farmId:
          type: string
          description: The id of the farm
        pondId:
          type: string
          description: The id of the company
        name:
          type: string
          description: The name of the company 
        properties:
          type: object
          properties:
            type:
              type: string
              description: The type of the pond
            status:
              type: string
              description: indicates if it is active or not
            location:
              type: object
              properties:
                polygonPaths:
                  type: array
                  items:
                    type: object
                    properties:
                      lat: 
                        type: number
                      long: 
                        type: number
                center:
                  type: object
                  properties:
                    lat: 
                      type: number
                    long: 
                      type: number
                    
    DefaultResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Indicates if was successfully informed if the schedule was applied
    activity-index:
      type: object
      properties:
        activityIndex:
          type: number
          minimum: 0
          maximum: 100
          description: 'the percentage activity, 0-100'
    feeding-mode:
      type: object
      properties:
        mode:
          type: string
          enum: [scheduled, acoustic, stopped]
    scheduled-feed-amount:
      type: object
      properties:
        scheduledFeedAmount:
          type: number
          minimum: 0
          description: 'feed amount in Kg'
    feed:
      type: object
      properties:
        feedId:
          type: string
          minLength: 1
        feederType:
          type: string
          enum: [madan]
        amount:
          type: number
          minimum: 0
    water-temperature:
      type: object
      properties:
        waterTemperature:
          type: number
          description: 'unit is in C'

security: 
  - bearerAuth: []
