openapi: 3.0.0
info:
  version: "1.0.1"
  title: 'APP Test'
  description: ''

servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/jzorro/FirstAPI/1.0.0
    
paths:
  /users/{userID}:
    get:
      summary: Returns a user by ID
      parameters:
        - name: userID
          in: path
          required: true
          description: The ID of the user to return
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
        '400':
          description: The specified user ID is invalid
        '404':
          description: A user with the specified ID was not found
  
  /users/{userName}:
    get:
      summary: Return a user by name
      parameters: 
        - name: userName
          in: path
          required: true
          description: The name of the user to retunr
          schema:
            type: string
      responses:
        '202':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
        '402':
          description: The specified user name is invalid
        '406':
          description: A user with the specified name was not found
