openapi: 3.0.1
info:
  title: taringa-api-definition
  description: Definition of Taringa-API
  version: '0.1'
servers:
  - url: 'http://34.102.229.1'
paths:
  /sendAllTokens:
    post:
      description: |
        **POST body parms**
        ```
        param    type                   description

        symbol   {String}               token symbol eg: T!
        type     {String}               chain type eg: Testnet, Mainnet
        sender   {String}               token sender address
        receiver {String}               token receiver address
        ```
      parameters:
        - name: Taringa-API-Key
          in: header
          schema:
            type: string
          example: <Your-Taringa-API-Key>
        - name: X-Parse-Application-Id
          in: header
          schema:
            type: string
          example: taringa
        - name: X-Parse-REST-API-KEY
          in: header
          allowEmptyValue: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                receiver:
                  type: string
                sender:
                  type: string
                type:
                  type: string
            examples:
              '0':
                value: "{\n\t\"type\": \"Testnet\",\n\t\"symbol\": \"T!\",\n\t\"sender\": \"0x55B80C386F2b1c81Cfe6914a5C8d3aE9D533C4Fc\",\n\t\"receiver\": \"0xE2Bb6AE7741F9C975e676c1bd26F7503CDb36377\"\n}"
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: 
                '0':
                  value: |-
                    {
                        "result": {
                          "hash": "0x574404c5d23323626235f90ab44c08e9bf982020e48b177215fe58c71486d3bc"
                          }
                    }
      servers:
        - url: 'http://34.102.229.1'
    servers:
      - url: 'http://34.102.229.1'
  /sendTokens:
    post:
      description: |
        **POST body parms**
        ```
        param    type                   description

        symbol   {String}               token symbol eg: T!
        type     {String}               chain type eg: Testnet, Mainnet
        sender   {String}               token sender address
        receiver {String}               token receiver address
        value    {String}               transfer value (decimal base, unit: T!)
        ```
      parameters:
        - name: Taringa-API-Key
          in: header
          schema:
            type: string
          example: <Your-Taringa-API-Key>
        - name: X-Parse-Application-Id
          in: header
          schema:
            type: string
          example: taringa
        - name: X-Parse-REST-API-KEY
          in: header
          allowEmptyValue: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                receiver:
                  type: string
                sender:
                  type: string
                type:
                  type: string
                value:
                  type: string
            examples:
              '0':
                value: "{\n\t\"type\": \"Testnet\",\n\t\"symbol\": \"T!\",\n\t\"sender\": \"0x55B80C386F2b1c81Cfe6914a5C8d3aE9D533C4Fc\",\n\t\"receiver\": \"0xE2Bb6AE7741F9C975e676c1bd26F7503CDb36377\",\n\t\"value\": \"1\"\n}"
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: 
                '0':
                  value: |-
                    {
                        "result": {
                          "hash": "0x574404c5d23323626235f90ab44c08e9bf982020e48b177215fe58c71486d3bc"
                          }
                    }
      servers:
        - url: 'http://34.102.229.1'
    servers:
      - url: 'http://34.102.229.1'
  /addAddress:
    post:
      description: |
        **POST body parms**
        ```
        param    type                   description

        chain    {String}               chain name eg: Rootstock
        symbol   {String}               token symbol eg: T!
        type     {String}               chain type eg: Testnet, Mainnet
        address  {String}               address you want to add
        ```
      parameters:
        - name: Taringa-API-Key
          in: header
          schema:
            type: string
          example: <Your-Taringa-API-Key>
        - name: X-Parse-Application-Id
          in: header
          schema:
            type: string
          example: taringa
        - name: X-Parse-REST-API-KEY
          in: header
          allowEmptyValue: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                chain:
                  type: string
                address:
                  type: string
                type:
                  type: string
            examples:
              '0':
                value: "{\n\t\"chain\": \"Rootstock\",\n\t\"type\": \"Testnet\",\n\t\"symbol\": \"T!\",\n\t\"address\": \"0x732cB8e029Cec47873289F70ca16EFd60CC31B9B\"\n}"
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: 
                '0':
                  value: |-
                    {
                        "result": true
                    }
      servers:
        - url: 'http://34.102.229.1'
    servers:
      - url: 'http://34.102.229.1'
  /generateAddresses:
    post:
      description: |
        **POST body parms**
        ```
        param    type                   description

        chain    {String}               chain name eg: Rootstock
        symbol   {String}               token symbol eg: T!
        type     {String}               chain type eg: Testnet, Mainnet
        amount   {String}               generate address amount
        ```
      parameters:
        - name: Taringa-API-Key
          in: header
          schema:
            type: string
          example: <Your-Taringa-API-Key>
        - name: X-Parse-Application-Id
          in: header
          schema:
            type: string
          example: taringa
        - name: X-Parse-REST-API-KEY
          in: header
          allowEmptyValue: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                chain:
                  type: string
                amount:
                  type: integer
                type:
                  type: string
            examples:
              '0':
                value: "{\n\t\"chain\": \"Rootstock\",\n\t\"type\": \"Testnet\",\n\t\"symbol\": \"T!\",\n\t\"amount\": 1\n}"
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://34.102.229.1'
    servers:
      - url: 'http://34.102.229.1'
  /formatRawTransaction:
    post:
      description: |
        **POST body parms**
        ```
        param    type                   description

        symbol   {String}               token symbol eg: T!
        type     {String}               chain type eg: Testnet, Mainnet
        sender   {String}               public key for sender
        receiver {String}               public key for receiver
        value    {String}               transfer value (decimal base, unit: T!)
        ```
      parameters:
        - name: Taringa-API-Key
          in: header
          schema:
            type: string
          example: <Your-Taringa-API-Key>
        - name: X-Parse-Application-Id
          in: header
          schema:
            type: string
          example: taringa
        - name: X-Parse-REST-API-KEY
          in: header
          allowEmptyValue: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                receiver:
                  type: string
                sender:
                  type: string
                type:
                  type: string
                value:
                  type: string
            examples:
              '0':
                value: |-
                  {
                      "symbol": "T!",
                      "type": "Testnet",
                      "sender": "0xE2Bb6AE7741F9C975e676c1bd26F7503CDb36377",
                      "receiver": "0x55B80C386F2b1c81Cfe6914a5C8d3aE9D533C4Fc",
                      "value": "3"
                  }
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://34.102.229.1'
    servers:
      - url: 'http://34.102.229.1'
  /getBalance:
    post:
      description: |
        **POST body parms**
        ```
        param    type                   description

        symbol   {String}               token symbol eg: T!
        type     {String}               chain type eg: Testnet, Mainnet
        address  {String}               address you want to add
        ```
      parameters:
        - name: Taringa-API-Key
          in: header
          schema:
            type: string
          example: <Your-Taringa-API-Key>
        - name: X-Parse-Application-Id
          in: header
          schema:
            type: string
          example: taringa
        - name: X-Parse-REST-API-KEY
          in: header
          allowEmptyValue: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                address:
                  type: string
                type:
                  type: string
            examples:
              '0':
                value: "{\n\t\"address\": \"0x55B80C386F2b1c81Cfe6914a5C8d3aE9D533C4Fc\",\n\t\"type\": \"Testnet\",\n\t\"symbol\": \"T!\"\n}"
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://34.102.229.1'
    servers:
      - url: 'http://34.102.229.1'
  /getTransactions:
    post:
      description: |
        **POST body parms**
        ```
        param    type                   description

        address  {String}               address you want to add
        chain    {String}               chain name eg: Rootstock
        type     {String}               chain type eg: Testnet, Mainnet
        symbol   {String}               token symbol eg: T!
        page     {Number}               
        pageSize {Number}               
        ```
      parameters:
        - name: Taringa-API-Key
          in: header
          schema:
            type: string
          example: <Your-Taringa-API-Key>
        - name: X-Parse-Application-Id
          in: header
          schema:
            type: string
          example: taringa
        - name: X-Parse-REST-API-KEY
          in: header
          allowEmptyValue: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                symbol:
                  type: string
                chain:
                  type: string
                address:
                  type: string
                pageSize:
                  type: integer
                page:
                  type: integer
                type:
                  type: string
            examples:
              '0':
                value: "{\n\t\"address\": \"0xE2Bb6AE7741F9C975e676c1bd26F7503CDb36377\",\n\t\"chain\": \"Rootstock\",\n\t\"type\": \"Testnet\",\n\t\"symbol\": \"T!\",\n\t\"page\": 1,\n\t\"pageSize\": 2\n}"
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://34.102.229.1'
    servers:
      - url: 'http://34.102.229.1'
  /sendSignedTransaction:
    post:
      parameters:
        - name: Taringa-API-Key
          in: header
          schema:
            type: string
          example: <Your-Taringa-API-Key>
        - name: X-Parse-Application-Id
          in: header
          schema:
            type: string
          example: taringa
        - name: X-Parse-REST-API-KEY
          in: header
          allowEmptyValue: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                type:
                  type: string
                hash:
                  type: string
            examples:
              '0':
                value: |-
                  {
                      "name": "Rootstock",
                      "hash": "0xf86b82017f840387ee4082520894f08f6c2eac2183dfc0a5910c58c186496f32498d8609184e72a0008062a09abbee1b8a3498b006bc0439aca458014a5648a68694fb1171ff16d71686a8cba01220e60ca04dfbc3fd15b52b96e82c356570120466a245a973a69b6758d29bec",
                      "type": "Testnet"
                  }
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: 
                '0':
                  value: |-
                    {
                        "result": {
                          "hash": "0x4c09f65c74ce07279976a4b2638178854fa146d14f4c50e8fab5c83c8c118ee8"
                          }
                    }
      servers:
        - url: 'http://34.102.229.1'
      description: |
        **POST body parms**
        ```
        param    type                   description

        name   {String}               chain name eg: Rootstock
        type   {String}               chain type eg: Testnet, Mainnet
        hash   {String}               signed transaction
        ```
    servers:
      - url: 'http://34.102.229.1'
