openapi: 3.0.0
info:
  version: 'V01'
  title: 'CMS Page API'
  description: 'Hybris provides an api which exposes the template layout and internal components mapped to the given template'

paths: 
  /cchcmswebservices/{baseSiteId}/cms/pages:
    get:
      tags:
      - "CMSPages"
      description: This API provides details about the page layout and components mapped in slots
      parameters:
        - in: path
          name: baseSiteId 
          required: true
          schema:
            type: string
        - in: query
          name: fields
          schema:
            type: string
            default: DEFAULT
          required: true  
          description: Field set required from API
        - in: query
          name: pageId
          schema:
            type: string
            default: /login
          required: true  
          description: Hybris page id
        
        - in: query
          name: lang
          schema:
            type: string
            default: en
          required: true  
          description: Language of selected site

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page'
                
components:
  schemas:
    Page:
      type: object
      properties:
        uid:
          type: string
          example: 'login'
        title:
          type: string
          example: 'login'
        template:
          type: string
          example: 'LoginPageTemplate'
        typeCode:
          type: string
          example: 'ContentPage'
        name:
          type: string
          example: 'Login Page'
        contentSlots:
          type: object
          properties:
            contentSlot:
              type: array
              items:
                type: object
                properties:
                  slotId:
                    type: string
                    example: 'LeftContentSlot-login'
                  position:
                    type: string
                    example: 'LeftContentSlot'
                  name:
                    type: string
                    example: 'Left Content Slot for Customer Login'
                  slotShared:
                    type: string
                    example: 'true'
                  components:
                    type: object
                    properties:
                      component:
                        type: array
                        items:
                          type: object
                          properties:
                            uid:
                              type: string
                              example: ''
                            typeCode:
                              type: string
                              example: ''
                            modifiedTime:
                              type: string
                              example: ''
                            name:
                              type: string
                              example: ''
                            shownProductCount:
                              type: string
                              example: ''
                            container:
                              type: string
                              example: ''
                            totalDisplay:
                              type: string
                              example: ''
                            flexType:
                              type: string
                              example: ''
                            external:
                              type: string
                              example: ''
                            urlLink:
                              type: string
                              example: ''
                            target:
                              type: string
                              example: ''
                            wrapAfter:
                              type: string
                              example: ''
                            copyright:
                              type: string
                              example: ''
                            showLanguageCurrency:
                              type: string
                              example: ''
                            navigationNode:
                              type: object
                              properties:
                                uid:
                                  type: string
                                  example: ''
                                entries:
                                  type: array
                                  items:
                                    type: object
                                    properties:  
                                      children:
                                        type: array
                                        items:
                                           type: object
                                           properties:
                                            uid:
                                              type: string
                                              example: ''
                                            entries:
                                              type: array
                                              items:
                                                type: object
                                                properties:
                                                  itemId:
                                                    type: string
                                                    example: ''
                                                  itemSuperType:
                                                    type: string
                                                    example: ''
                                                  itemType:
                                                    type: string
                                                    example: ''
                                                  title:
                                                    type: string 
                                                    example: ''
        label:
          type: string
          example: '/login'

# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/anjaneyuluk/CMSPageAPI/V01
