openapi: 3.0.0
info:
  description: Donor Advantage REST API
  version: "1.0.0-oas3"
  title: Donor Advantage REST API
  contact:
    email: matt.noble@fmgtucson.com
  license:
    name: Proprietary
paths:
  /member.jsp:
    get:
      summary: Return contact info for all members in database
      description: |
        Get a list of all members and their contact info
      parameters:
        - in: query
          name: offset
          description: number of records to skip for pagination
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: limit
          description: maximum number of records to return
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: member contact info
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MemberItem'
        '400':
          description: bad input parameter
components:
  schemas:
    MemberItem:
      type: object
      required:
        - id
        - full_name
        - first_name
        - last_name
        - init_date
        - grad_date
      properties:
        id:
          type: integer
          example: 35
        full_name:
          type: string
          example: John Doe
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: Doe
        init_date:
          type: string
          example: '2016-08-29T00:00:00.000Z'
        grad_date:
          type: string
          example: 2016
        status:
          type: string
          example: A
        code:
          type: string
          example: A
        address:
          $ref: '#/components/schemas/Address'
        phone:
          type: array
          items:
            $ref: '#/components/schemas/Phone'
        email:
          type: string
          example: john.doe@university.edu
    Address:
      required:
        - street1
        - city
        - state
        - zip
      properties:
        street1:
          type: string
        street2:
          type: string
        city:
          type: string
        state:
          type: string
        zip:
          type: string
    Phone:
      required:
        - type
        - number
      properties:
        type:
          type: string
          example: Home
        number:
          type: string
          example: 408-867-5309
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
servers:
  - url: 'https://gms.fmgtucson.com/donor_advantage/api'
