openapi: 3.0.0
info:
  title: MemberPoliciesList
  description: Common MemberPoliciesList API
  version: "10.1.4"
paths:
  /member-policies/:
    get:
      tags:
      - member policies
      summary: Get the list of member-policy association list associated with member's search criteria
      description: "Returns a list of member_policy object. \n\nSearch can be performed using\n
          Member First Name, Last Name, Member ID, Address fields, email, Member Birth date etc. \nAdditional search\
          fields can be included as needed by the configuration of the applications.\n"
      operationId: member-policies-list
      parameters:
      - $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/PaginationQueryParameters/10.1#/components/parameters/orderingParam
      - $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/PaginationQueryParameters/10.1#/components/parameters/pageParam
      - $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/PaginationQueryParameters/10.1#/components/parameters/pageSizeParam
      - name: first_name
        in: query
        description: Member's first name to be used for search by first name. Partial
          searches can be implemented by Payer.
        required: false
        style: form
        explode: false
        schema:
          type: string
          minLength: 2
      - name: last_name
        in: query
        description: Member's last name to be used for search by last name. Partial
          searches can be implemented by Payer.
        required: false
        style: form
        explode: false
        schema:
          type: string
          minLength: 2
      - name: member_id
        in: query
        description: Unique member identifier associated with the member.This is same as member_number.
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: birth_date
        in: query
        description: Members date of birth in YYYY-MM-DD format.
        required: false
        style: form
        explode: false
        schema:
          type: string
          format: date
      - name: phone_number
        in: query
        description: Members phone number in xxx-xxx-xxxx format.
        required: false
        style: form
        explode: false
        schema:
          type: string
          format: 999-999-9999
      - name: line_of_business
        in: query
        description: Line of business based search e.g. Small Group, Large Group, Individual, Medicare etc.
        required: false
        style: form
        explode: false
        schema:
          type: string
      - name: member_display_identifier
        in: query
        description: returns member_policies based on member_display identifier.
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: member_name
        in: query
        description: name searches against name fields including first, middle, last,
          and all name fields.
        required: false
        style: form
        explode: false
        schema:
          type: string
          minLength: 2
      - name: ssn
        in: query
        description: member's ssn.
        required: false
        style: form
        explode: false
        schema:
          type: string
      - name: email
        in: query
        description: member's email.
        required: false
        style: form
        explode: false
        schema:
          type: string
          format: xyz@xyz.xxx
      - name: address_city
        in: query
        description: member's physical address's city.
        required: false
        style: form
        explode: false
        schema:
          type: string
      - name: address_state
        in: query
        description: member's physical address's state.
        required: false
        style: form
        explode: false
        schema:
          type: string
      - name: address_zip
        in: query
        description: member's physical address's zipcode.
        required: false
        style: form
        explode: false
        schema:
          type: string
          minLength: 5
      - name: policy_id
        in: query
        description: Unique policy identifier associated with the policy.
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: effective_date_before
        in: query
        description: |
                      Filters for entries with effective_date before the specified date.
                      Member Policies with an effective_date before the date passed in this parameter will be listed in the response.
        required: false
        style: form
        explode: false
        schema:
          type: string
          format: date
      - name: effective_date_after
        in: query
        description: |
                      Filters for entries with effective_date after the specified date.
                      Member Policies with an effective_date after the date passed in this parameter will be listed in the response.
        required: false
        style: form
        explode: false
        schema:
          type: string
          format: date
      - name: termination_date_before
        in: query
        description: |
                      Filters for entries with termination_date before the specified date.
                      Member Policies with a termination date before the date passed in this parameter will be listed in the response.
        required: false
        style: form
        explode: false
        schema:
          type: string
          format: date
      - name: termination_date_after
        in: query
        description: |
                      Filters for entries with termination_date after the specified date.
                      Member Policies with a termination_date after the date passed in this parameter will be listed in the response.
        required: false
        style: form
        explode: false
        schema:
          type: string
          format: date
      - name: should_all_filters_exact_match
        in: query
        description: "This flag is used for exact/partial matches. All the fields configured to do partial v/s exact searches will be operated with this flag."
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: An array of member_policies objects
          content:
            application/json:
              schema:
                required:
                - count
                - results
                type: object
                properties:
                  count:
                    type: integer
                    description: Count representing the total number of objects available
                      to be returned in the results array
                  next:
                    type: integer
                    description: query identifier defined by the api developer for
                      getting the next set of records
                  previous:
                    type: integer
                    description: query identifier defined by the api developer for
                      getting the previous set of records
                  results:
                    type: array
                    items:
                      $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/MemberPolicyModel/10.1.3#/components/schemas/MemberPolicy
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/ErrorModel/10.0.2#/components/schemas/Error'
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/ErrorModel/10.0.2#/components/schemas/Error'
