openapi: 3.0.0
info:
  version: '2.0'
  title: 'PurchasePlus API - Goods Module'
  description: 'Product and service description management, including bulk import and export'

# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/marketboomer/PurchasePlusAPI-Goods/2.0
  - description: PurchasePlus Production
    url: https://api.purchaseplus.com
  - description: PurchasePlus Staging 
    url: https://staging.api.purchaseplus.com
  - description: PurchasePlus Demo
    url: https://demo.api.purchaseplus.com

tags:
  - name: Master Catalogue Export
    description: An export of the products on the P+ master catalogue
    
paths:
  "/goods/api/master_catalogue_exports":
    post:
      tags:
        - Master Catalogue Export
      summary: Create a master catalogue export
      description: |
        This will create a new master catalogue export _unless_ there is another master catalogue export that was created less than one day ago. Generating the master catalogue export is an expensive process due to the large number of products. If there is an export that is less than one day old then it will be returned instead if you try to create a new one.
        
        When a new export does get created it will initially be in the `open` state. Once our background exporting task has picked it up its state will change to `processing`. And finally, when it is `complete` there will be a value in the `export_download_url` field that you may use to retrieve the content of the export. Note that this URL will expire after a certain period of time. If you need to get a new valid `export_download_url` call the `GET` endpoint using the ID of the export as the parameter. 
      operationId: postMasterCatalogueExport
      responses:
        200:
          $ref: "#/components/responses/MasterCatalogueExportSuccessResponse"
        400:
          $ref: "https://api.swaggerhub.com/domains/marketboomer/PurchasePlusAPI/2.0#/components/responses/BadRequestError"
        401:
          $ref: "https://api.swaggerhub.com/domains/marketboomer/PurchasePlusAPI/2.0#/components/responses/UnauthorisedError"
        403:
          $ref: "https://api.swaggerhub.com/domains/marketboomer/PurchasePlusAPI/2.0#/components/responses/ForbiddenError"
        406:
          $ref: "https://api.swaggerhub.com/domains/marketboomer/PurchasePlusAPI/2.0#/components/responses/NotAcceptableError"
        500:
          $ref: "https://api.swaggerhub.com/domains/marketboomer/PurchasePlusAPI/2.0#/components/responses/ServerError"
  "/goods/api/master_catalogue_exports/{masterCatalogueExportId}":
    get:
      tags:
        - Master Catalogue Export
      summary: Finds master catalogue export by ID
      operationId: getMasterCatalogueExportById
      parameters:
        - $ref: "#/components/parameters/masterCatalogueExportId"
      responses:
        200:
          $ref: "#/components/responses/MasterCatalogueExportSuccessResponse"
        401:
          $ref: "https://api.swaggerhub.com/domains/marketboomer/PurchasePlusAPI/2.0#/components/responses/UnauthorisedError"
        403:
          $ref: "https://api.swaggerhub.com/domains/marketboomer/PurchasePlusAPI/2.0#/components/responses/ForbiddenError"
        404:
          $ref: "https://api.swaggerhub.com/domains/marketboomer/PurchasePlusAPI/2.0#/components/responses/NotFoundError"
        500:
          $ref: "https://api.swaggerhub.com/domains/marketboomer/PurchasePlusAPI/2.0#/components/responses/ServerError"
  
components:
  schemas:
    MasterCatalogueExport:
      type: object
      properties:
        id:
          type: string
          description: JSONAPI ID of the master catalogue export
          example: "1000"
        type:
          type: string
          description: JSONAPI Type
          example: master_catalogue_exports
        attributes:
          type: object
          properties:
            id:
              type: integer
              format: int64
              readOnly: true
              description: Unique identifier for the master catalogue export.
              example: 1000
            completed_at:
              type: string
              format: date-time
              readOnly: true
              description: Timestamp when the export process was completed.
              example: "2020-03-06T04:47:01.592+11:00"
            created_at:
              type: string
              format: date-time
              readOnly: true
              description: Timestamp when the master catalogue export was created.
              example: "2020-03-06T03:24:12.170+11:00"
            creator_id:
              type: integer
              format: int64
              readOnly: true
              description: ID of the user that created this master catalogue export.
              example: 1000
            export_download_url:
              type: string
              readOnly: true
              description: URL to retrieve the content of the export.
              example: "https://marketboomer.s3.ap-southeast-1.amazonaws.com/exports/master_catalogue_export/p_catalogue_connect_106511_05_mar_2020_4_24pm.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200311T151926Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&"
            started_at:
              type: string
              format: date-time
              readOnly: true
              description: Timestamp when the export process was initiated.
              example: "2020-03-06T04:33:19.997+11:00"
            state:
              type: string
              maxLength: 255
              default: open
              readOnly: true
              description: |
                The current state of the master catalogue export. The valid values are
                state | description
                ------|------------
                `open` | The initial state for the master catalogue. The export will be placed on a queue awaiting processing (this is automatic).
                `processing` | Indicates the export is currently being generated. The state may change to either complete or failed from here.
                `complete` | The export has successfully completed. No further state changes are possible.
                `failed` | The export process has failed. Contact marketboomer to discover why.
              enum:
                - open
                - processing
                - complete
                - failed
            updated_at:
              type: string
              format: date-time
              readOnly: true
              description: Timestamp when the master catalogue export was last updated.
              example: "2015-05-18T06:18:49.051Z"  
        links:
          type: object
          properties:
            self:
              type: string
              readOnly: true
              description: Endpoint for the master catalogue export itself
              example: "https://api.purchaseplus.com/goods/api/master_catalogue_exports/1000" 
              
  parameters:
    masterCatalogueExportId:
      name: masterCatalogueExportId
      in: path
      description: "ID of masterCatalogueExport"
      required: true
      schema:
        type: integer
        format: int64
        example: 1000
        
  responses:
    MasterCatalogueExportSuccessResponse:
      description: Master Catalogue Export operation was successful.
      content:
        application/vnd.mbapi.v2+json:
          schema:
            type: object
            properties:
              data:
                $ref: "#/components/schemas/MasterCatalogueExport"
              
  securitySchemes:
    access_token:
      type: apiKey
      name: Access-token
      in: header
    client:
      type: apiKey
      name: Client
      in: header
    uid:
      type: apiKey
      name: Uid
      in: header
security:
  - access_token: []
  - client: []
  - uid: []
