openapi: 3.0.0
servers: []
info:
  description: This is a simple API
  version: "1.0.0"
  title: Get Orders
  contact:
    email: oleg.letyanin@columbusglobal.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /orders:
    get:
      summary: get Orders
      operationId: getOrders
      description: get orders
      security:
        - basicAuth: []
      responses:
        '200':
          description: get all orders
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
                xml:
                  name: response
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
components:
  securitySchemes:
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic 
  schemas:
    Order:
      type: object
      properties:
        HDR:
          type: object
          properties:
              MTYPE:
                type: string
                xml:
                  attribute: true
                example:
                  DELORD
              MVER:
                type: string
                xml:
                  attribute: true      
                example:
                  004                
              MFUNC:
                type: string
                xml:
                  attribute: true 
                example:
                  D                   
              SND:
                type: integer
                xml:
                  attribute: true
                example:
                  4820086639880                     
              RECP:
                type: integer  
                xml:
                  attribute: true  
                example:
                  9991027012248                   
              DDATE:
                type: integer
                xml:
                  attribute: true    
                example:
                  20200429                    
              DTIME:
                type: integer
                xml:
                  attribute: true   
                example:
                  200006                    
              TESTF:
                type: integer 
                xml:
                  attribute: true 
                example:
                  1                  
        HDO:
          type: object
          properties:
              ONBR:
                type: string
                xml:
                  attribute: true   
                example:
                  ORD-01031-G5C1D7
              ODATE:
                type: integer
                xml:
                  attribute: true
                example:
                  20200429
              DLDATE:
                type: integer
                xml:
                  attribute: true  
                example:
                  20200429
              DLTIME:
                type: string
                xml:
                  attribute: true  
                example:
                 ''
              IPMT:
                type: string
                xml:
                  attribute: true  
                example:
                 C
              IPMD:
                type: string
                xml:
                  attribute: true                
                example:
                  0
              IBIL:
                type: string 
                xml:
                  attribute: true
                example:
                  I
              TXT:
                type: string
                xml:
                  attribute: true                
              SAN:
                type: string
                xml:
                  attribute: true 
                
              SAFN:
                type: string 
                xml:
                  attribute: true                
              SAT:
                type: integer  
                xml:
                  attribute: true
                example:
                  7926382722
              REM:
                type: string
                xml:
                  attribute: true                
        NAD:
          type: object
          properties:
              GLN:
                type: integer
                xml:
                  attribute: true 
                example:
                  9991027012248
              LOCID:
                type: string
                xml:
                  attribute: true                
              SNAME:
                type: string
                xml:
                  attribute: true 
                example:
                  Евро-Аква - Щасливе
              DESC:
                type: string
                xml:
                  attribute: true
                example:
                  Евро-Аква - Щасливе
              CITY:
                type: string 
                xml:
                  attribute: true  
                example:
                  Киев
              PCODE:
                type: string 
                xml:
                  attribute: true   
                example:
                  01001
              STR:
                type: string  
                xml:
                  attribute: true 
                example:
                  Лесі Українки
              NO:
                type: integer
                xml:
                  attribute: true 
                example:
                  28
              TAX:
                type: integer
                xml:
                  attribute: true 
                example:
                  368005526599
              REM:
                type: string
                xml:
                  attribute: true                
        PAY:
          type: object
          properties:
              LOCID:
                type: string
                xml:
                  attribute: true 
                example: 
                  СЧЛ8765
              SNAME:
                type: string
                xml:
                  attribute: true   
                example:
                  Ещенко В. О.
              DESC:
                type: string
                xml:
                  attribute: true
                example:
                  Ещенко В. О.                  
              CITY:
                type: string
                xml:
                  attribute: true                
                example:
                  Бровари
              PCODE:
                type: string  
                xml:
                  attribute: true   
                nullable: true                  
              STR:
                type: string 
                xml:
                  attribute: true                
              NO:
                type: string  
                xml:
                  attribute: true                
              TAX:
                type: string
                xml:
                  attribute: true                
        DEL:
          type: object
          properties:
              LOCID:
                type: string
                xml:
                  attribute: true 
                example: 
                  СЧЛ8765
              SNAME:
                type: string
                xml:
                  attribute: true   
                example:
                  Ещенко В. О.
              DESC:
                type: string
                xml:
                  attribute: true
                example:
                  Ещенко В. О.                  
              CITY:
                type: string
                xml:
                  attribute: true                
                example:
                  Бровари               
              PCODE:
                type: string  
                xml:
                  attribute: true                
              STR:
                type: string 
                xml:
                  attribute: true                
              NO:
                type: string
                xml:
                  attribute: true                
        LIN:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/LIN'
          xml:
            name: 'LIN'
            wrapped: false
      xml:
        name: 'EC-DIST.XML.DELORD'
        wrapped: true
    LIN:
      type: object
      properties:
        NBR:
          type: integer
          xml:
            attribute: true    
          example:
            1
        EAN:
          type: integer
          xml:
            attribute: true 
          example:
            4860019002190
        SKU:
          type: integer
          xml:
            attribute: true  
          example:
            7001311401
        SNAME:
          type: string
          xml:
            attribute: true   
          example:
            Борж0,15x12ж/б
        PSUID:
          type: integer 
          xml:
            attribute: true 
          example:
            7001311401
        DESC:
          type: string 
          xml:
            attribute: true
          example:
            Боржомі 0,15 л (ж/б) газована мін. вода х 12 пл.
        PRCODE:
          type: string
          xml:
            attribute: true                
        PRNAME:
          type: string
          xml:
            attribute: true                
        UOM:
          type: string
          xml:
            attribute: true  
          example:
            Штука
        DSCT:
          type: integer
          xml:
            attribute: true  
          example:
            0
        TXT:
          type: string
          xml:
            attribute: true                
        CURR:
          type: string  
          xml:
            attribute: true 
          example:
            UAH
        REM:
          type: string
          xml:
            attribute: true                
        QTY:
          type: integer
          format: format
          xml:
            attribute: true     
          example:
            100.0000000000
        DGPRI:
          type: integer
          format: format
          xml:
            attribute: true 
          example:
            8.7500
security:
  - basicAuth: []
