openapi: 3.0.0
info:
  version: "1.0.0-oas3"
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
  
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/MyDummyOrg3/Clientes_ex/1.0.0-oas3
  

# Basic authentication
components:
  schemas:
    arrayOfcontactos:
      type: object 
      properties:
        telefone:
          type: integer
        tipo:
          type: string
          enum: ['telemovel', 'emprego', 'casa']
      example:
        - telefone: 961111111
          tipo: 'telemovel'
        - telefone: 931111111
          tipo: 'emprego'
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []

paths:
  /clientes:
    get:
      description: Returns a list of clientes
      #  ----- Added lines ----------------------------------------
      parameters:
        - name: regiao
          in: query
          description: Limits the number of items on a page
          schema:
            type: integer
      responses:
        '200':
          description: Successful response,
          content:
            application/json:
             schema:
                type: array
                items:
                  type: object
                  required:
                    - cliente_id
                  properties:
                    cliente_id:
                      type: number
                      example: 123
                    nome:
                      type: string
                      example: Hugo
                    genero:
                      type: string
                      example: M
                    regioes:
                      type: string
                      example: Alentejo
                    contactos:
                      $ref: '#/components/schemas/arrayOfcontactos'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object 
              required:
                - username
              properties:
                artist_name:
                  type: string
                artist_genre:
                  type: string
                albums_recorded:
                  type: integer
                username:
                  type: string

      responses:
        '200':
          description: Successfully created a new artist

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
#  ---- /Added lines  ----------------------------------------
  /outros:
    get:
      description: Returns a list of outros
      #  ----- Added lines ----------------------------------------
      responses:
        '200':
          description: Successfully created a new artist
