openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/gpmetals/orosoft/1.1.0
info:
  description: API to query information from Orosoft to be processed into vtiger. this update accounts for changes in the neo API
  version: "1.1.0"
  title: Client Information Query API
  contact:
    email: admin@global-precious-metals.com
  license:
    name: Proprietary, all rights reserved


  
tags:
  - name: Authenticated Calls
    description: Server to Server calls secured by token
  
paths:
  '/transactions/{clientId}':
    get:
      tags:
        - Authenticated Calls
      summary: returns transaction list for and account, and date if need be
      operationId: list transactions
      description: |
        clientId is necessary 
      parameters:
        - in: path
          name: clientId
          description: client id number in orosoft
          required: true
          schema:
            type: string
            minLength: 4
            maxLength: 4
      responses:
        '200':
          description: list of transactions since the beginning of times
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionId'
              examples:
                example1:
                  $ref: '#/components/examples/transListExample1'
                    
        '400':
          description: bad input parameter
        
  '/transactions/{clientId}/{startDate}':
    get:
      tags:
        - Authenticated Calls
      summary: returns transaction list for and account
      operationId: list transactions since a given date
      description: |
        clientId is necessary while date is optional, and default to the 2019-01-01 (as per [standard](https://tools.ietf.org/html/rfc3339#section-5.6)
      parameters:
        - in: path
          name: clientId
          description: client id number in orosoft
          required: true
          schema:
            type: string
            minLength: 4
            maxLength: 4
        - in: path
          name: startDate
          description: start date for records
          required: true
          schema:
            type: string
            format: date
            
     
      responses:
        '200':
          description: list of transactions since the start date
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionId'
              examples:
                example1:
                  $ref: '#/components/examples/transListExample1'
                  
        '400':
          description: bad input parameter
          
  '/details':
    get:
      tags:
        - Authenticated Calls
      summary: returns transaction details, for all types 
      operationId: transaction details
      description: behind the scene there might be a few different database calls, but hey should be harmonized for consumption purposes
      parameters:
      - in: query
        name: docNo
        description: document reference
        required: true
        schema:
          type: string
          example: "SAL/2019/000012"
      
      
      responses:
        '200':
          description: return details of transaction
          content:
            application/json:
              schema:
                # type: object
                # items:
                  $ref: '#/components/schemas/TransactionDetails'
              examples:
                SAL:
                #basic example
                  value:
                    transtype: SAL
                    clientId: 2345
                    documentDate: "2019-05-12"
                    deliveryDate: "2019-05-16"
                    barItems: 
                     
                      - sku: G_1KG_CB_P49_PA
                        longDesc: Gold 99.99 PAMP 1000g Cast Bar
                        quantity: 2
                        pureOz: 64.269
                        otherCharge: 501.2
                        metal: gold
                        serials: A1234-A1235
                        location: 
                      #metalItem2: 
                      - sku: G_1KG_CB_P49_MK
                        longDesc: Gold 99.99 MKS 1000g Cast Bar
                        quantity: 1
                        pureOz: 32.14
                        otherCharge: 249.5
                        metal: gold
                        serials: B3456
                        location:
                    xauPrice: 1346.4
                    xagPrice: 15.1
                    xptPrice: 750.33
                    xpdPrice: 1500.24
                    xrhoPrice: 6200.86
                    mbtcPrice: 8.1
                    totalusdVal: 130555.8
                
                SWD:
                #example with "miscalleneous charges"
                  value:
                    transtype: SWD
                    clientId: 2345
                    documentDate: "2019-05-12"
                    deliveryDate: "2019-05-16"
                    barItems: 
                     
                      - sku: G_1KG_CB_P49_PA
                        longDesc: Gold 99.99 PAMP 1000g Cast Bar
                        quantity: 7
                        pureOz: 224.98
                        otherCharge: 6299.44
                        metal: gold
                        serials: A1234-A1240
                        location: 
                      #metalItem2: 
                      - sku: G_1OZ_CO_P49_KR
                        longDesc: Gold 99.99 Krugerrand 1.09oz Coin
                        quantity: 49
                        pureOz: 53.41
                        otherCharge: 2990.96
                        metal: gold
                        serials: 
                        location:
                        # this item is for unmatched "other charge" (roundup)
                      - sku: 
                        longDesc: 
                        quantity: 
                        pureOz: 
                        otherCharge: 104.56
                        metal: 
                        serials: 
                        location:
                    xauPrice: 1400
                    xagPrice: 15.1
                    xptPrice: 750.33
                    xpdPrice: 1500.24
                    xrhoPrice: 6200.86
                    mbtcPrice: 8.1
                    totalusdVal: 400000
                    
                PUR:
                #exmaple of purchase details output
                  value:
                    transtype: PWD
                    clientId: 2345
                    documentDate: "2019-07-12"
                    deliveryDate: "2019-07-19"
                    barItems: 
                     
                      - sku: G_1KG_CB_P49_PA
                        longDesc: Gold 99.99 PAMP 1000g Cast Bar
                        quantity: 2
                        pureOz: 64.269
                        otherCharge: 501.2
                        metal: gold
                        serials: A1234-A1235
                        location: 
                     
                    xauPrice: 1346.4
                    xagPrice: 15.1
                    xptPrice: 750.33
                    xpdPrice: 1500.24
                    xrhoPrice: 6200.86
                    totalusdVal: 87032.98
                
                FOC:
                #exmaple of foward output
                  value:
                    transtype: FOC
                    clientId: 2747
                    documentDate: "2019-01-01"
                    deliveryDate: "2019-01-01"
                    barItems: 
                     
                      - sku: 
                        longDesc: 
                        quantity: 
                        pureOz: 7586.928 #this field is NEGATIVE for SELL direction
                        otherCharge: 
                        metal: gold
                        serials: 
                        location: 
                     
                    xauPrice: 1250.45
                    xagPrice: #values not relevant to the FWD are irrelevant
                    xptPrice: #values not relevant to the FWD are irrelevant
                    xpdPrice: #values not relevant to the FWD are irrelevant
                    xrhoPrice: #values not relevant to the FWD are irrelevant
                    totalusdVal: # nulled too

                STI:
                #exmaple of storage invoice output
                  value:
                    transtype: STI
                    clientId: 2747
                    documentDate: "2019-01-01"
                    deliveryDate: 
                    barItems: 
                     
                      - sku: 
                        longDesc: "from:2019-01-01 to:2019-03-31 xau:1520 xag:15.1 mbtc:6.1 xauQty:7586.928 xagQty: 1500 mbtcQty: 1000.0"
                        quantity: 
                        pureOz: 
                        otherCharge: 
                        metal: 
                        serials: 
                        location: 
                      
                     
                    xauPrice: #values for the gold fix need to be PARSED from the JRV/STI record
                    xagPrice: #values for the silver fix need to be PARSED from the JRV/STI record
                    xptPrice: #values for the platinum fix need to be PARSED from the JRV/STI record
                    xpdPrice: #values for the palladium fix need to be PARSED from the JRV/STI record
                    xrhoPrice: #values for the rhodium fix need to be PARSED from the JRV/STI record
                    mbtcPrice: 
                    totalusdVal: 501.25
            
        '400':
          description: bad input parameter
  '/holdings/{clientId}':
    get:
      tags:
        - Authenticated Calls
      summary: return array of holdings for a given client
      operationId: list holdings
      description: |
        clientId is necessary 
      parameters:
        - in: path
          name: clientId
          description: client id number in orosoft
          required: true
          schema:
            type: string
            pattern: '[1-9][1-9]{3}'
            
      
      responses:
        '200':
          description: list of holdings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MetalItem'
              example:
                - sku: G_1KG_CB_P49_PA
                  longDesc: Gold 99.99 PAMP 1000g Cast Bar
                  quantity: 2
                  pureOz: 64.296
                  otherCharge:
                  metal: gold
                  serials: ['A1224','A1225']
                  location: Geneva
                - sku: G_1KG_CB_P49_MK
                  longDesc: Gold 99.99 MKS 1000g Cast Bar
                  quantity: 1
                  pureOz: 32.14
                  otherCharge:
                  metal: gold
                  serials: ['C4321','A1225']
                  location: Singapore
              
        '400':
          description: bad input parameter

#Schema descriptions for types and others
components:
  schemas:
    TransType:
      type: string
      enum:
        - SAL
        - SWD
        - PUR
        - PWD
        - JRV
        - STI
        - REC
        - PAY
        - OPB
    TransactionId:
      type: object
      required:
        - docNo
        #- transyear
        #- transNumb
        #- transDate
        #- usdVal
      properties:
        docNo:
          type: string
        # transyear:
        #   type: string
        #   example: 2019
        # transNumb:
        #   type: string
        #   pattern: '[0-9]{6}'
        #   example: '000001'
        transDate:
          type: string
          format: date
          example: '2019-09-20'
        usdVal:
          type: number
          example: 10000.25
    # TransactionList:
    #   type: array
    #   items: 
    #     $ref: '#/components/schemas/TransactionId'
    
    TransactionDetails:
      type: object
      required:
        - transtype
        - clientId
        - documentDate
        - deliveryDate #value date in oro, can be null ?
        - barItems #should be an array
        - totalusdVal
        - xauPrice
        - xagPrice
        - xptPrice
        - xpdPrice
        - xrhoPrice
        - mbtcPrice
        
      properties:
        transtype:
          $ref: '#/components/schemas/TransType'
        clientId:
          type: string
          pattern: '[1-9][0-9]{3}'
        documentDate:
          type: string
          format: date
          example: '2019-06-13'
        deliveryDate:
          type: string
          format: date
          example: '2019-06-16'
          nullable: true #no delivery for types FOC, PAY or JRV e.g.
        barItems:
          type: array
          items:
            $ref: '#/components/schemas/MetalItem'
          nullable: true
        totalusdVal:
          type: number
          example: 86149.5
        xauPrice:
          type: number
          minimum: 600
          maximum: 5000
          example: 1346.3
          nullable: true #some transactions don't need spot
        xagPrice:
          type: number
          minimum: 5
          maximum: 150
          example: 15.1
          nullable: true #some transactions don't need spot
        mbtcPrice:
          type: number
          minimum: 0.1
          maximum: 100
          example: 8.123
          nullable: true #some transactions don't need spot
        xptPrice:
          type: number
          minimum: 100
          maximum: 5000
          example: 760.32
          nullable: true #some transactions don't need spot
        xpdPrice:
          type: number
          minimum: 100
          maximum: 5000
          example: 1116.3
          nullable: true #some transactions don't need spot
        xrhoPrice:
          type: number
          minimum: 100
          maximum: 20000
          example: 6452.31
          nullable: true #some transactions don't need spot
    MetalItem:
      type: object
      required:
        - sku
        - longDesc
        - quantity
        - pureOz
        - otherCharge #value of premium in USD
        - metal
        - serials
        - location
      properties:
        sku:
          type: string
          example: 'G_1KG_CB_P49_PA'
          nullable: true
        longDesc:
          type: string
          example: 'Gold 99.99 PAMP 1000g Cast Bar'
          nullable: true
        quantity:
          type: integer
          example: 2
          nullable: true
        pureOz:
          type: number
          example: 64.296
          nullable: true
        otherCharge:
          type: number
          example: 500.0
          nullable: true #we re-use the definition between holding and charge
        metal:
          type: string
          enum:
            - gold
            - silver
            - platinum
            - palladium
            - rhodium
            - btc
          nullable: true
        serials:
          type: array
          items:
            type: string
          example: ['A1224,A1225']
          nullable: true #coins or unmatched "other charge" don't need it
        location:
          type: string
          example: 'Geneva' #this is the long description of the location
            
  examples:
    MetalExampleHOL:
      value:
        sku: 'G_1KG_CB_P49_PA'
        longDesc: 'Gold 99.99 PAMP 1000g Cast Bar'
        quantity: 2
        pureOz: 64.296
        otherCharge: 
        metal: 'gold'
        serials: ['A1224','A1225']
        location: 'Geneva'
    
    transListExample1:
      value:
        - transtype: OPB
          # transyear: 2019
          # transnumb: 999999
          docNo: "OPB/2019/999999"
          transDate: "2019-01-01"
          usdVal: 25723.2
        - transtype: PAY
          # transyear: 2019
          # transnumber: 000018
          docNo: "PAY/2019/000018"
          transDate: "2019-03-12"
          usdVal: 54000
        - transtype: SWD
          # transyear: 2019
          # transnumber: 001234
          docNo: "SWD/2019/001234"
          transDate: "2019-04-02"
          usdVal: 49156
        - transtype: FOC
          # transyear: 2019
          # transnumber: 003454
          docNo: "FOC/2019/003454"
          transDate: "2019-06-13"
          usdVal: -758588
        - transtype: STI
          # transyear: 2019
          # transnumb: 002222
          docNo: "STI/2019/002222"
          transDate: "2019-07-13"
  
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      
security:
  - bearerAuth: []
