openapi: 3.0.0
servers:
  - url: '{domain}'
info:
  version: "1.0.2"
  title: Yell API
  description: |
    - Request limit: 10 per day.
    - Throttle:  
      - Burst limit: 200 requests. 
      - Rate limit: 100 requests per second.
    - Account Creation Frequency: Every hour, Mon-Fri - 8am-5pm.
    - Change Log: 
      - Change merchant_data to merchantData
      - Updated abc fields to support accountType POI creation for Apple Business Chat
      - Updated values in Example JSON to variables
    - Release Date: 05/05/2020
    

paths:
  /merchant:
    post: 
      summary: Create merchant Account
      parameters: 
      - name: x-api-key
        in: header
        schema:
          type: string
      - name: version
        in: path
        required: true
        schema:
          type: string
        example:
          'v=1.0'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/merchant'
            examples:
              merchant:
                $ref: '#/components/examples/merchantExample'
      
      responses:
        '200':
          description: Successful Response 
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
              example:
                  message: 'success'
                  

      callbacks:
        merchantCallback:
          '{{Yell_API}}':
            post:
              responses:
                '200':
                  description: Successful Response
                  content:
                    application/json:
                      examples:
                        Response:
                          $ref: '#/components/examples/merchantResponseExample'
        
        
        
        natAbcCallback:
          '{{Yell_API}}':
            post:
              responses:
                '200':
                  description: Successful Response
                  content:  
                    application/json:
                      examples:
                        Response:
                          $ref: '#/components/examples/natAbcResponseExample'
      
                        
        natSkillCallback:
          '{{Yell_API}}':
            post:
              responses:
                '200':
                  description: Successful Response
                  content:  
                    application/json:
                      examples:
                        Response:
                          $ref: '#/components/examples/natSkillResponseExample'
                        
        completedCallback:
          '{{Yell_API}}':
            post:
              responses:
                '200':
                  description: Successful Response
                  content:  
                    application/json:
                      examples:
                        Response:
                          $ref: '#/components/examples/completedResponseExample'
                          
        
                          
        
                      
 
components:
  schemas:
    merchant:
      properties:
        branches: 
          type: array
          items:
            type: object
            properties:
              natId:  
                type: string
              businessFunction: 
                type: string
              companyName: 
                type: string
              postcode:
                type: string
              lpChannels:
                type: object
                properties:
                  abc: 
                    type: object
                    properties:
                      cspId:
                        type: string
                      orgInfo:
                        type: object
                        properties:
                          vendorOrgId:
                            type: string
                          vendorId:
                            type: string
                          name:
                            type: string
                          countryCode: 
                            type: string
                          contact:
                            type: object
                            properties:
                              name:
                                type: object
                                properties:
                                  firstName:
                                    type: string
                                  lastName:
                                    type: string
                              phone:
                                type: string
                              email:
                                type: string
                          termsOfUse:
                            type: object
                            properties:
                              version:
                                type: string
                              accepted:
                                type: string
                          applePayMerchantId:
                            type: string
                      businessCard:
                        type: object
                        properties:
                          accountType:
                            type: string
                          supportHours:
                            type: string
                          intentID:
                            type: string
                          groupID:
                            type: string
                          timeZoneId:
                            type: string
                          estimatedResponseTime:
                            type: number
        merchantData:
          type: object
          properties:
            id: 
              type: string
            appId:
              type: string
            email:
              type: string
            nickname:
              type: string
    
  examples:
    merchantExample:
      value:
        branches:
        - natId: "{{natId1}}"
          businessFunction: "{{businessFunctionA}}"
          companyName: "{{companyName}}"
          postcode: "{{postCode}}"
          lpChannels:
            abc:
              cspId: "{{cspId}}"
              orgInfo:
                vendorOrgId: "{{vendorOrgId}}"
                vendorId: "{{natId1}}"
                name: "{{businessName}}"
                countryCode: GB
                contact:
                  name:
                    firstName: "{{firstName}}"
                    lastName: "{{lastName}}"
                  phone: "{{phoneNumber}}"
                  email: "{{email}}"
                termsOfUse:
                  version: 3cf5d20e-3d9f-4ca3-845b-aa423dce71a5
                  accepted: '2020-01-01T19:20:30+01:00'
                applePayMerchantId: com.apple.store
              businessCard:
                accountType: POI
                supportHours: Mo-Fr 09:00-13:00,14:00-18:00; Sa 10:00-13:00
                intentID: applePOI
                groupID: "{{natId1}}"
                timeZoneId: Europe/London
                estimatedResponseTime: 1440
        - natId: "{{natId2}}"
          businessFunction: "{{businessFunctionB}}"
          companyName: "{{companyName}}"
          postcode: "{{postCode}}"
          lpChannels:
            abc:
              cspId: "{{cspId}}"
              orgInfo:
                vendorOrgId: "{{vendorOrgId}}"
                vendorId: "{{natId2}}"
                name: "{{businessName}}"
                countryCode: GB
                contact:
                  name:
                    firstName: "{{firstName}}"
                    lastName: "{{lastName}}"
                  phone: "{{phoneNumber}}"
                  email: "{{email}}"
                termsOfUse:
                  version: 3cf5d20e-3d9f-4ca3-845b-aa423dce71a5
                  accepted: '2020-01-01T19:20:30+01:00'
                applePayMerchantId: com.apple.store
              businessCard:
                accountType: POI
                supportHours: Mo-Fr 09:00-13:00,14:00-18:00; Sa 10:00-13:00
                intentID: applePOI
                groupID: "{{natId2}}"
                timeZoneId: Europe/London
                estimatedResponseTime: 1440
        merchantData:
          id: "{{merchantId}}"
          appId: "{{merchantAppId}}"
          email: "{{merchantEmail}}"
          nickname: "{{merchantNickname}}"

      
    merchantResponseExample:
      value: {
        id: '39412de7-b157-45b2-8781-b76f7f8e1c02',
        lpAccount: '1234555986',
        lpBlacklistSkill: {
          id: '8388830',
          name: 'Blacklist'
        },
        users: [
          {
            userId: '1111111',
            userName: 'oaoa',
            userPwd: 'haidhekf'
          }
        ]
      }
    natAbcResponseExample:
      value: 
        id: '39412de7-b157-45b2-8781-b76f7f8e1c02'
        natId: 'ccc'
        lpChannel:
          abc:
            code: 0
            comment: ''
            data:
              businessId: '6e050031-3f30-4971-bcc9-74b8'
              status: 'pending'
              reviewStatus: 'pending'
              errorCode: 0
              
    natSkillResponseExample:
      value: 
        id: '39412de7-b157-45b2-8781-b76f7f8e1c02'
        natId: 'ccc'
        lpAccount: '1234555986'
        lpSkill: 
          id: '8388830'
          name: 'ccc'
        
      
    completedResponseExample:
      value:
        id: '39412de7-b157-45b2-8781-b76f7f8e1c02'
        natsTotal: 27
        natsCompleted: 25
        natsFailed: 2
