openapi: 3.0.1
info:
  title: PartnerInfo API
  version: v1
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/leandroom/partner-info_api/v1
  - url: https://wdcsis99.westcon.com.br/v1
    description: Development server
paths:
  /api/PartnerInfo/{taxID}:
    get:
      tags:
        - PartnerInfo
      summary: Return the partner information from governmental data sources
      description: Query SintegraAWS services for fetching company information
      parameters:
        - name: taxID
          in: path
          description: company identifier to be queried on SintegraAWS services
          required: true
          schema: 
            type: string
            format: string
      responses:
        '200':
          description: expected response containing a JSON object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartnerDetails'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    PartnerDetails:
      type: object
      properties:
        ReceitaFederal:
          $ref: '#/components/schemas/ReceitaFederal'
        Sintegra:
          $ref: '#/components/schemas/Sintegra'
        Simples:
          $ref: '#/components/schemas/Simples'
        Suframa:
          $ref: '#/components/schemas/Suframa'
    ReceitaFederal:
      type: object
      properties:
        code: 
          type: string 
          description: Código de retorno utilizado para informar o status da requisição.
        status: 
          type: string 
          description: Indica a situação da requisição. (Valores possíveis- OK,ERROR)
        message: 
            type: string 
            description: Mensagem explicativa indicando o campo status.
        cnpj: 
          type: string 
          description: CNPJ no formato '00.000.000/0000-00'
        tipo: 
          type: string 
          description: Valores possíveis -MATRIZ, FILIAL.
        abertura: 
          type: string 
          description: Data de abertura no formato 'dd/mm/aaaa'
        nome: 
          type: string 
          description: Razão social.
        fantasia: 
          type: string 
          description: Nome fantasia.
        atividade_principal: 
          type: array 
          items: 
            $ref: '#/components/schemas/AtividadePrincipal'
          description: Atividade principal. Um array com um elemento.
        atividades_secundarias: 
          type: array
          items: 
            $ref: '#/components/schemas/AtividadeSecundaria'
          description: Atividades secundárias.
        natureza_juridica: 
          type: string 
          description: Natureza jurídica.
        logradouro: 
          type: string 
          description: Logradouro.
        numero: 
          type: string 
          description: Número.
        complemento: 
          type: string 
          description: Complemento.
        cep: 
          type: string 
          description: CEP no formato '00.000-000'
        bairro: 
          type: string 
          description: Bairro.
        municipio: 
          type: string 
          description: Município.
        uf: 
          type: string 
          description: Sigla da Unidade da Federação.
        email: 
          type: string 
          description: Email.
        telefone: 
          type: string 
          description: Telefone.
        efr: 
          type: string 
          description: Ente Federativo Responsável, disponibilizado apenas para CNPJs da administração pública.
        situacao: 
          type: string 
          description: Situação.
        data_situacao: 
          type: string 
          description: Data da situação no formato 'dd/mm/aaaa'
        motivo_situacao: 
          type: string 
          description: Motivo da situação.
        situacao_especial: 
          type: string 
          description: Situação especial.
        data_situacao_especial: 
          type: string 
          description: Data da situação especial no formato 'dd/mm/aaaa'
        capital_social: 
          type: string 
          description: Valor do capital social no formato '0.00'
        qsa: 
          type: array
          items: 
            $ref: '#/components/schemas/QSA'
          description: Quadro de Sócios e Administradores.
        extra: 
          type: object 
          description: Campo reservado para uso futuro
        ibge: 
          $ref: '#/components/schemas/IBGE'
    Sintegra:
      type: object
      properties:
        status: 
          type: string 
          description: Indica a situação da requisição. Valores possíveis - OK, ERROR
        code: 
          type: string 
          description: Código de retorno utilizado para informar o status da requisição.
        message: 
          type: string 
          description: Mensagem explicativa indicando o campo status.
        cnpj: 
          type: string 
          description: CNPJ no formato '00000000000000'
        nome_empresarial: 
          type: string 
          description: Razão social.
        nome_fantasia: 
          type: string 
          description: Nome fantasia.
        inscricao_estadual: 
          type: string 
          description: Inscrição Estadual.
        tipo_inscricao: 
          type: string 
          description: Tipo de Inscrição Estadual.
        data_situacao_cadastral: 
          type: string 
          description: Data da situação cadastral no formato 'dd-MM-yyyy'.
        situacao_cnpj: 
          type: string 
          description: Situação cadastral do CNPJ.
        situacao_ie: 
          type: string 
          description: Situação Cadastral da Inscrição Estadual (IE).
        data_inicio_atividade: 
          type: string 
          description: Data do início da atividade no formato 'dd-MM-yyyy'.
        regime_tributacao: 
          type: string 
          description: Regime de tributação.
        informacao_ie_como_destinatario: 
          type: string 
          description: Informação da Inscrição Estadual como destinatário.
        porte_empresa: 
          type: string 
          description: Porte da empresa.
        cnae_principal: 
          $ref: '#/components/schemas/CNAEPrincipal'
        data_fim_atividade: 
          type: string 
          description: Data na qual a empresa foi cancelada no formato dd-MM-yyyy. Apenas para empresas com o status diferente de Ativo.
        uf: 
          type: string 
          description: Sigla da Unidade da Federação
        cep: 
          type: string 
          description: CEP no formato '00000000'
        municipio: 
          type: string 
          description: Município.
        bairro: 
          type: string 
          description: Bairro.
        logradouro: 
          type: string 
          description: Logradouro.
        complemento: 
          type: string 
          description: Complemento.
        numero: 
          type: string 
          description: Número.
        ibge: 
          $ref: '#/components/schemas/IBGE'
    Simples:
      type: object
      properties:
        status: 
          type: string 
          description: Indica a situação da requisição. Valores possíveis - OK, ERROR.
        code: 
          type: string 
          description: Código de retorno utilizado para informar o status da requisição.
        message: 
          type: string 
          description: Mensagem explicativa indicando o campo status.
        cnpj: 
          type: string 
          description: CNPJ no formato '00000000000000'
        cnpj_matriz: 
          type: string 
          description: CNPJ no formato '00.000.000/0000-00'
        nome_empresarial: 
          type: string 
          description: Razão social.
        situacao_simples_nacional: 
          type: string 
          description: Situação no Simples Nacional
        situacao_simei: 
          type: string 
          description: Situação no SIMEI
        situacao_simples_nacional_anterior: 
          type: string 
          description: Opções pelo Simples Nacional em Períodos Anteriores
        situacao_simei_anterior: 
          type: string 
          description: Opções pelo SIMEI em Períodos Anteriores
        agendamentos: 
          type: string 
          description: Agendamentos no Simples Nacional
        eventos_futuros_simples_nacional: 
          type: string 
          description: Eventos Futuros no Simples Nacional
        eventos_futuros_simples_simei: 
          type: string 
          description: Eventos Futuros no SIMEI
    Suframa:
      type: object
      properties:
        status: 
          type: string 
          description: Indica a situação da requisição. Valores possíveis - OK, ERROR.
        code: 
          type: string 
          description: Código de retorno utilizado para informar o status da requisição.
        message: 
          type: string 
          description: Mensagem explicativa indicando o campo status.
        cnpj: 
          type: string 
          description: CNPJ no formato '00000000000000'.
        nome_empresarial: 
          type: string 
          description: Razão social.
        inscricao_suframa: 
          type: string 
          description: Inscrição Estadual.
        data_validade_cadastral: 
          type: string 
          description: Data da situação cadastral no formato dd-MM-yyyy.
        situacao_cadastral: 
          type: string 
          description: Situação Cadastral da Inscrição Suframa.
        uf: 
          type: string 
          description: Sigla da Unidade da Federação.
        cep: 
          type: string 
          description: CEP no formato '00000000'
        municipio: 
          type: string 
          description: Município.
        bairro: 
          type: string 
          description: Bairro.
        logradouro: 
          type: string 
          description: Logradouro.
        complemento: 
          type: string 
          description: Complemento.
        numero: 
          type: string 
          description: Número.
        endereco_eletronico: 
          type: string 
          description: e-mail do CNPJ.
        telefone: 
          type: string 
          description: Telefone de contato do CNPJ.
        tipo_incentivo: 
          type: string 
          description: Tipo de Incentivo do CNPJ.
        observacao: 
          type: string 
          description: Observacao do CNPJ.
    CNAEPrincipal:
      type: object
      description: Atividade econômica principal
      properties:
        cnae_principal.code: 
          type: string 
          description: Código do CNAE principal
        cnae_principal.text: 
          type: string 
          description: Descrição da atividade econômica principal
    AtividadePrincipal:
      type: object
      properties:
        atividade_principal.code: 
          type: string 
          description: Código CNAE da atividade no formato '00.00-0-00'
        atividade_principal.text: 
          type: string 
          description: Descrição da atividade
    AtividadeSecundaria:
      type: object
      properties:
        atividades_secundarias.code: 
          type: string 
          description: Código CNAE da atividade no formato '00.00-0-00'.
        atividades_secundarias.text: 
          type: string 
          description: Descrição da atividade.
    QSA:
      type: object
      properties:
        qsa.nome: 
          type: string 
          description: Nome do sócio.
        qsa.qual: 
          type: string 
          description: Qualificação do sócio.
        qsa.pais_origem: 
          type: string 
          description: País de origem do sócio. Disponível apenas para sócios estrangeiros.
        qsa.nome_rep_legal: 
          type: string 
          description: Nome do representante legal. Disponível apenas para sócios com representantes.
        qsa.qual_rep_legal: 
          type: string 
          description: Qualificação do representante legal. Disponível apenas para sócios com representantes.
    IBGE:
      type: object
      properties:
        ibge.codigo_municipio: 
          type: string 
          description: Código IBGE do municipio.
        ibge.codigo_uf: 
          type: string 
          description: Código IBGE da UF.
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
          description: Chave da exceção gerada
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
          description: Código do erro gerado
        detail:
          type: string
          nullable: true
          description: Mensagem da exceção gerada
        instance:
          type: string
          nullable: true
          description: Descrição sobre origem do erro
      nullable: true
