penapi: 3.0.0
info:
  version: "2.0"
  title: "OAuth"
  description: "Microsoft identity platform allows developers to build applications that sign in all Microsoft identities and get tokens to call Microsoft APIs like Microsoft Graph, or APIs you've built. This full-featured platform consists of an OAuth 2.0."

servers: 
- description: MSFT login server 
  url: https://login.microsoftonline.com/
 
tags:
  - name: ROPC #Resource Owner Password Client Credentials
  - name: Client Credentials

paths:
  /organizations/oauth2/v2.0/token:
    #parameters:
    #    - name: tenant
    #      in: path
    #      required: true
    #      description: "The directory tenant that you want to log the user into. This can be in GUID or friendly name format. This parameter can't be set to common or consumers, but may be set to organizations."
    #      schema:
    #        type: string
    post:
      tags:
        - ROPC
      summary: "The ROPC flow is a single request: it sends the client identification and user's credentials to the IDP, and then receives tokens in return."
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required: [client_id, scope, client_secret, username, password, grant_type]
              properties:
                client_id:
                  type: string
                  example: 00000000-0000-0000-0000-000000000000
                  description: "The Application (client) ID that the Azure portal - App registrations page assigned to your app."
                scope:
                  type: string
                  example: https://analysis.windows.net/powerbi/api/.default
                  description: "A space-separated list of scopes, or permissions, that the app requires. In an interactive flow, the admin or the user must consent to these scopes ahead of time."
                client_secret:
                  type: string
                  example: LZrfMtS1Y+G23xWnzrN+Gau8rB32BL7O6VHSY2oCrBC0=
                  description: "If your app is a public client, then the client_secret or client_assertion cannot be included. If the app is a confidential client, then it must be included."
                username:
                  type: string
                  example: john.smith@example.onmicrosoft.com
                  description: "The user's email address."
                password:
                  type: string
                  format: password
                  example: 'P$1èCabo9'
                  description: "The user's password."
                grant_type:
                  type: string
                  example: password
                  description: "The grant type; Must be set to password."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponseBody'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
                    
  /{tenant}/oauth2/v2.0/token:
      parameters:
        - name: tenant
          in: path
          required: true
          description: "The directory tenant that you want to request permission from. This can be in GUID or friendly name format. If you don't know which tenant the user belongs to and you want to let them sign in with any tenant, use common."
          schema:
            type: string
      post:
        tags:
          - Client Credentials
        summary: "Use the OAuth 2.0 client credentials grant specified in RFC 6749, sometimes called two-legged OAuth, to access web-hosted resources by using the identity of an application."
        requestBody:
          content:
            application/x-www.form.urlencoded:
              schema: 
                type: object
                required: [client_id, scope, client_secret, grant_type]
                properties:
                  client_id:
                    type: string
                    example: 00000000-0000-0000-0000-000000000000
                    description: "The Application (client) ID that the Azure portal - App registrations page assigned to your app."
                  scope:
                    type: string
                    example: https://analysis.windows.net/powerbi/api/.default
                    description: "A space-separated list of scopes, or permissions, that the app requires. In an interactive flow, the admin or the user must consent to these scopes ahead of time."
                  client_secret:
                    type: string
                    example: LZrfMtS1Y+G23xWnzrN+Gau8rB32BL7O6VHSY2oCrBC0=
                    description: "The client secret that you generated for your app in the app registration portal. The client secret must be URL-encoded before being sent."
                  grant_type:
                    type: string
                    example: password
                    description: "The grant type; Must be set to client_credentials."
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/TokenResponseBody'      
          400:
            description: Bad Request
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponseBody'        
                  
components:
  schemas:
    TokenResponseBody:
      type: object
      properties:
        token_type:
          type: string
          description: "The token type; Always set to Bearer."
        scope: 
          type: string
          description: "If an access token was returned, this parameter lists the scopes the access token is valid for in space separated string format."
        expires_in:
          type: string
          description: "Number of seconds that the included access token is valid for."
        ext_expires_in:
          type: string
          description: "Number of extended lifetime in seconds that the included access token is valid for."
        access_token:
          type: string
          description: "Issued for the scopes that were requested in opaque string format."
    ErrorResponseBody:
      type: object
      properties:
        error:
          type: string
          description: "An error code string that you can use to classify types of errors that occur, and to react to errors."
        error_description:
          type: string
          description: "A specific error message that might help you identify the root cause of an authentication error."
        error_codes:
          type: string
          description: "A list of STS-specific error codes that might help with diagnostics."
        timestamp:
          type: string
          description: "The time when the error occurred."
        trace_id:
          type: string 
          description: "A unique identifier for the request to help with diagnostics."
        correlation_id:
          type: string
          description: "A unique identifier for the request to help with diagnostics across components."