openapi: 3.0.0
info:
  version: '0.1.0'
  title: 'Testing Swagger at Inb'
  description: 'First test'

# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/serafin.agoiz/test_inb/0.1.0

paths:
  /users/{userId}:
    get:
      summary: Return the Profile needed by UI
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the profile to be returned to UI
          schema:
            type: integer
      responses:
        '200':
          description: all is good
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
        '400':
          description: Id has wrong format
        '404':
          description: Id not found
