openapi: 3.0.0
info:
  version: "10.2.1"
  title: MembersPatch
  description: Common MembersPatch API
paths:
  /members/{member_number}/:
    patch:
      tags:
      - member
      summary: Updates attributes of a Member
      parameters:
      - name: member_number
        in: path
        description: unique member number.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: policy_id
        in: query
        description: unique policy id.
        required: false
        style: form
        explode: false
        schema:
          type: string
      description: "Updates attributes of a Member e.g. address, phone, email. This\
        \ API is allowed for members with privacy_flag set to false. \n"
      operationId: members_update
      requestBody:
        description: Updates attributes of a Member e.g. address, phone, email.
        content:
          application/json:
            schema:
              $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/MemberModel/10.2.1#/components/schemas/Member
      responses:
        '200':
          description: Successfully updated the Member attributes to the payer system.
        '202':
          description: Member update received and will be processed asynchronously
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/ConfirmationResponseModel/10.0.1#/components/schemas/ConfirmationResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/ErrorModel/10.0.2#/components/schemas/Error'
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/ErrorModel/10.0.2#/components/schemas/Error'
