openapi: 3.0.0
info:
  description: |
    Professional yozuvchilikdan tortib kundalik yozishmalargacha… 

    “Matn.uz” nomli kundalik yordamchingiz bilan birgalikda, savodxon inson sifatida taassurot qoldiradigan, aniq va xatosiz yozing! ✏️ 

    Facebook, Twitter, Instagram va boshqa barcha ommabop ijtimoiy tarmoqlarda “post” yozayotganingizda, katta bir maqola ustida ish olib borgan vaqtingizda, u yoki bu so‘zning izohiga qiziqqaningizda, bizning tizimdan maslahatlar oling. 💻

  version: "v1"
  title: Matn.uz
  contact:
    email: matn@akhmatovich.uz
tags:
  - name: imlo
    description: So‘zlarni imloviy xatolarili tekshirish
  - name: dictionary
    description: Lug‘at
  - name: about
    description: Loyiha haqida
paths:

  #  _           _       
  # (_)_ __ ___ | | ___  
  # | | '_ ` _ \| |/ _ \ 
  # | | | | | | | | (_) |
  # |_|_| |_| |_|_|\___/ 

  /correct:
    post:
      tags:
        - imlo
      summary: Berilgan so‘zlarni imloviy xatolarini tekshirish
      requestBody:
        required: true
        content:
          application/json:
            examples:
              Bitta so‘z:
                value:
                  - olma
              Bir nechta so‘z:
                value:
                  - assalomu
                  - alaykum
                  - ishlariz
                  - yaxshimi
            schema:
              type: object
              properties:
                text:
                  type: array
                  items:
                    $ref: '#/components/schemas/Word'
      responses:
        200:
          description: To‘g‘ri bajarildi
          content:
            application/json:
              examples:
                Xatolik yo‘q:
                  value:
                    errors: false
                    data: []
                Xatolik bor:
                  value:
                    errors: true
                    data:
                      - oma
                      - sallom
                      - yahshi
              schema:
                type: object
                properties:
                  errors:
                    type: boolean
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Word'
        400:
          description: Kiritilgan ma‘lumot to‘liq emas
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      text:
                        type: string
                        example: text maydoni to‘ldirilishi shart.
        500:
          description: Serverda xatolik yuz berdi
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Serverda xatolik yuz berdi.
  /suggestions:
    post:
      tags:
        - imlo
      summary: Berilgan so‘zlarni imloviy xatolarini tekshirish va taklif olish
      requestBody:
        required: true
        content:
          application/json:
            examples:
              Bitta so‘z:
                value:
                  - olma
              Bir nechta so‘z:
                value:
                  - assalomu
                  - alaykum
                  - ishlariz
                  - yaxshimi
            schema:
              type: object
              properties:
                text:
                  type: array
                  items:
                    $ref: '#/components/schemas/Word'
      responses:
        200:
          description: To‘g‘ri bajarildi
          content:
            application/json:
              examples:
                Xatolik yo‘q:
                  value:
                    errors: false
                    data: []
                Xatolik bor:
                  value:
                    errors: true
                    data:
                      - word: salm
                        suggestions:
                          - sal
                          - salom
                          - salim
              schema:
                type: object
                properties:
                  errors:
                    type: boolean
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        word:
                          $ref: '#/components/schemas/Word'
                        suggestions:
                          type: array
                          items:
                            $ref: '#/components/schemas/Suggestion'
        400:
          description: Kiritilgan ma‘lumot to‘liq emas
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      text:
                        type: string
                        example: text maydoni to‘ldirilishi shart.
        500:
          description: Serverda xatolik yuz berdi
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Serverda xatolik yuz berdi.

# _                       _ _ _                 _       _             
#| |_ _ __ __ _ _ __  ___| (_) |_ ___ _ __ __ _| |_ ___(_)_   _  __ _ 
#| __| '__/ _` | '_ \/ __| | | __/ _ \ '__/ _` | __/ __| | | | |/ _` |
#| |_| | | (_| | | | \__ \ | | ||  __/ | | (_| | |_\__ \ | |_| | (_| |
# \__|_|  \__,_|_| |_|___/_|_|\__\___|_|  \__,_|\__|___/_|\__, |\__,_|
#                        |___/       

  /latin:
    post:
      tags:
        - transliteratsiya
      summary: Berilgan matnni lotinchaga o‘girish
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        200:
          description: To‘g‘ri bajarildi
          content:
            application/json:
              example:
                assalomu alaykum
              schema:
                type: string
        400:
          description: Kiritilgan ma‘lumot to‘liq emas
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      text:
                        type: string
                        example: text maydoni to‘ldirilishi shart.
        500:
          description: Serverda xatolik yuz berdi
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Serverda xatolik yuz berdi.

  /cyrillic:
    post:
      tags:
        - transliteratsiya
      summary: Berilgan matnni kirillchaga o‘girish
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        200:
          description: To‘g‘ri bajarildi
          content:
            application/json:
              example:
                ассалому алайкум
              schema:
                type: string
        400:
          description: Kiritilgan ma‘lumot to‘liq emas
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      text:
                        type: string
                        example: text maydoni to‘ldirilishi shart.
        500:
          description: Serverda xatolik yuz berdi
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Serverda xatolik yuz berdi.

#        _                 _   
#   __ _| |__   ___  _   _| |_ 
#  / _` | '_ \ / _ \| | | | __|
# | (_| | |_) | (_) | |_| | |_ 
#  \__,_|_.__/ \___/ \__,_|\__|

  /collaborators:
    get:
      tags:
        - about
      summary: Barcha loyiha ishtirokchilari
      responses:
        200:
          description: To‘g‘ri bajarildi
          content:
            application/json:
              example:
                id: 1
                first_name: Abdullajon
                last_name: Abdullayev
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Collaborator'

#      _ _      _   _                              
#   __| (_) ___| |_(_) ___  _ __   __ _ _ __ _   _ 
#  / _` | |/ __| __| |/ _ \| '_ \ / _` | '__| | | |
# | (_| | | (__| |_| | (_) | | | | (_| | |  | |_| |
#  \__,_|_|\___|\__|_|\___/|_| |_|\__,_|_|   \__, |
#                                            |___/ 
  /dictionary:
    get:
      tags:
        - dictionary
      parameters:
        - name: search
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: To‘g‘ri bajarildi
          content:
            application/json:
              examples:
                Qidiruv natijasi:
                  value:
                    - id: 1
                      latin: abad
                    - id: 2
                      latin: abadiy
                    - id: 3
                      latin: abadiylash
                Lug‘at omborida topilmadi:
                  value: []
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    latin: 
                      type: string
        400:
          description: Kiritilgan ma‘lumot to‘liq emas
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      search:
                        type: string
                        example: search maydoni to‘ldirilishi shart.
  /words/{id}:
    get:
      tags: 
        - dictionary
      parameters: 
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: To‘g‘ri bajarildi
          content:
            application/json:
              example:
                id: 1
                latin: abad
                cyrillic: абад
                syllable: a-bad
              schema:
                $ref: '#/components/schemas/Dictionary'
    
servers:
  - url: 'https://matn.uz/api/v1'
security: 
  - apiKey: []
components:
  securitySchemes:
    apiKey:
      type: http
      scheme: bearer
  schemas:
    Collaborator:
      description: Loyiha ishtirokchisi
      type: object
      properties:
        id:
          description: Unikal raqami
          example: 1
          type: integer
        first_name:
          description: Ismi
          example: Abdullajon
          type: string
        last_name:
          description: Familiyasi
          example: Abdullayev
          type: string
    Word:
      description: So‘z
      type: string
      example: salom
    Dictionary:
      description: Lug‘at
      type: object
    
      properties:
        id:
          type: integer
        latin:
          type: string
        cyrillic:
          type: string
        syllable:
          type: string
      example:
        id: 1
        latin: abad
        cyrillic: абад
        syllable: a-bad
    Suggestion:
      description: Taklif
      type: string
      example: to‘g‘ri
