openapi: 3.0.1
info:
  title: Sedera REST API
  description: This API provides easy readability and examples for accessing the API endpoints offered by Sedera
  version: '0.6'
servers:
  - url: ' https://staging.my.salesforce.com'
paths:
  /services/data/v46.0/query/q:
    get:
      tags:
        - Search
      summary: Query for field values on accounts and contacts
      parameters:
        - in: query
          name: q
          required: true
          schema:
            type: string
          description: SOQL query of the format '?q = SOQL query'
          examples:
            Account Query:
              summary: Query subscription status of account
              value: '?q=SLECT+id,name,Subscription_Status__c+FROM+Account+WHERE+id+ =+''012i00000AzCiMAAV'''
            Contact Query:
              summary: Query if contact exists on account
              value: '?q=SELECT+Id,AccountId,Relationship_to_Member__c,FirstName,MiddleName,LastName,DOB__c,Gender__c,Mobile_Phone__c,App_Signature_Signs__c,X5_Year_Pre_ex__c,Dependent_Health_Completed_On__c,Dependent_Health_History__c,SSAN__c,Active__c+FROM+Contact+WHERE+AccountId+%3D+''0011N00001khhq3QAA''+AND+RecordTypeId+%3D+''012o0000000GpWD''+AND+Active__c+%3D+TRUE'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: object
                properties:
                  totalSize:
                    type: integer
                  done:
                    type: boolean
                  records:
                    type: object
                    properties:
                      attributes:
                        type: object
                        properties:
                          type:
                            type: string
                          url:
                            type: string
                      field 1:
                        type: string
                      field 2:
                        type: string
                      field ...:
                        type: string
                      field n:
                        type: string
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errorCode:
                    type: string
  /services/data/v46.0/sobjects/Account/:
    post:
      tags:
        - Accounts
      summary: Creates a new member account
      requestBody:
        content:
          application/json:
            schema:
              required:
                - Account_Employer_Name__c
                - Name
                - First_Name__c
                - Last_Name__c
                - Gender__c
                - Relationship_to_Member__c
                - Dependent_Status__c
                - IUA_Chosen__C
                - Primary_Email_Address__c
                - Date_of_Birth
                - Primary_Phone_Number__c
                - Tobacco_Use__c
                - Principals_Signed_On__c
                - Primary_Member_Principles__c
                - Enrollment_date__c
              type: object
              properties:
                Account_Employer_Name__c:
                  type: string
                Name:
                  type: string
                First_Name__c:
                  type: string
                Middle_initial__c:
                  type: string
                Last_Name__c:
                  type: string
                Gender__c:
                  type: string
                  enum:
                    - M
                    - F
                Dependent_Status__c:
                  type: string
                  enum:
                    - EO
                    - ES
                    - EF
                    - EC
                Enrollment_Date__c:
                  type: string
                  format: date
                IUA_Chosen__c:
                  type: integer
                  enum:
                    - 500
                    - 1000
                    - 1500
                    - 2500
                    - 5000
                BillingStreet:
                  type: string
                BillingCity:
                  type: string
                BillingState:
                  type: string
                BillingPostalCode:
                  type: string
                Primary_Email_Address__c:
                  type: string
                  format: email
                Date_of_Birth__c:
                  type: string
                  format: date
                Primary_Phone_Number__c:
                  type: string
                  format: phone
                Tobacco_Use__c:
                  type: boolean
                Principles_Signed_On__c:
                  type: string
                  format: date
                Demographics_Completed_On__c:
                  type: string
                  format: date
                Primary_Health_Completed_On__c:
                  type: string
                  format: date
                Dependents_Added_On__c:
                  type: string
                  format: date
                Dependent_Health_Completed_On:
                  type: string
                  format: date
                Ancillary_Flow_Completed_On__c:
                  type: string
                  format: date
                MCS_Completed_On__c:
                  type: string
                  format: date
                Primary_Member_Principles__c:
                  type: string
                  enum:
                    - INCOMPLETE
                    - COMPLETED
                Primary_Demographics__c:
                  type: string
                  enum:
                    - INCOMPLETE
                    - COMPLETED
                Primary_Health_History__c:
                  type: string
                  enum:
                    - INCOMPLETE
                    - COMPLETED
                Ancillary_Flow__c:
                  type: string
                  enum:
                    - INCOMPLETE
                    - COMPLETED
                MCS_Summary_Flow__c:
                  type: string
                  enum:
                    - INCOMPLETE
                    - COMPLETED
                Membership_Stage__c:
                  type: string
                  enum:
                    - New Enrollment - Incomplete
                    - New Enrollment - Complete
                Unique_Partner_ID__c:
                  type: string
                Contact_Partner_ID__c:
                  type: string
                Liberty_RX__c:
                  type: boolean
                Member_MEC_Prduct__c:
                  type: string
                Member_Discount_Tier_Manual__c:
                  type: string
                  enum:
                    - T1
                    - T2
                    - T3
                Subscription_Status__c:
                  type: string
                  enum:
                    - Application in Process
                    - Pending Start Date
                    - Active
                    - Incomplete
                Unique_Partner_id__c:
                  type: string
                Referral_Affiliate__c:
                  type: string
            examples:
              partial enrollment:
                summary: partial enrollment
                value: |-
                  {
                  "Account_Employer_Name__c" : "0012i000008vQAm",
                  "Name" : "John Test",
                  "First_Name__c" : "John",
                  "Middle_Initial__c" : "T",
                  "Last_Name__c" : "Test1",
                  "Gender__c" : "M",
                  "Dependent_Status__c" : "EO",
                  "Enrollment_Date__c" : "2020-02-01",
                  "IUA_Chosen__c" : "500.00",
                  "Primary_Email_Address__c" : "example@email.com",
                  "Date_of_Birth__c" : "2000-01-01",
                  "Primary_Phone_Number__c" : "1234567890",
                  "Tobacco_Use__c" : "true",
                  "Subscription_Status__c" : "Application in Process",
                  "Referral_Affiliate__c" : '0083i000008fTuM'
                  }
              completed enrollment:
                summary: completed enrollment
                value: |-
                  {
                     "Account_Employer_Name__c" : "0012i000008vQAm",
                     "Name" : "John Test",
                     "First_Name__c" : "John",
                     "Middle_Initial__c" : "T",
                     "Last_Name__c" : "Test1",
                     "Gender__c" : "M",
                     "Dependent_Status__c" : "EO",
                     "Enrollment_Date__c" : "2020-02-01",
                     "IUA_Chosen__c" : "500.00",
                     "BillingStreet" : "123 Sedera Ave",
                     "BillingCity" : "Austin",
                     "BillingState" : "Texas",
                     "BillingPostalCode" : "12345",
                     "Primary_Email_Address__c" : "example@email.com",
                     "Date_of_Birth__c" : "2000-01-01",
                     "Primary_Phone_Number__c" : "1234567890",
                     "Tobacco_Use__c" : "true",
                     "Principles_Signed_On__c" : "2020-01-01",
                     "Demographics_Completed_On__c" : "2020-01-01",
                     "Primary_Health_Completed_on__c" : "2020-01-01",
                     "Dependents_Added_On__c" : "2020-01-01",
                     "Dependent_Health_Completed_On__c" : "2020-01-01",
                     "Ancillary_Flow_Completed_On__c" : "2020-01-01",
                     "MCS_Completed_On__c" : "2020-01-01",
                     "Primary_Member_Principles__c" : "INCOMPLETE",
                     "Primary_Demographics__c" : "INCOMPLETE",
                     "Primary_Health_History__c" : "INCOMPLETE",
                     "Ancillary_Flow__c" : "INCOMPLETE",
                     "MCS_Summary_Flow__c" : "INCOMPLETE",
                     "Membership_Stage__c" : "New Enrollment - Incomplete",
                     "Subscription_Status__c" : "Pending Start Date"
                     "Referral_Affiliate__c" : '0083i000008fTuM'
                   }
      responses:
        '201':
          description: Created
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/services/data/v46.0/sobjects/Account/Id/{accountId}':
    patch:
      tags:
        - Accounts
      summary: Edit existing member account
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              required:
                - AccountNumber
              type: object
              properties:
                AccountNumber:
                  type: string
                Member_Discount_Tier_Manual__c:
                  type: string
                Member_MEC_Prduct__c:
                  type: string
            examples:
              '0':
                value: |-
                  {
                      "AccountNumber" : "0011N00001hpugwQAA",
                      "Member_Discount_Tier_Manual__c" : "T1",
                      "Member_MEC_Product__c" : "SHA Preventative"
                  }
      responses:
        '200':
          description: Created
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PatchResponse'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /services/data/v46.0/sobjects/Contact/:
    post:
      tags:
        - Contacts
      summary: Creates a new contact object
      requestBody:
        content:
          application/json:
            schema:
              required:
                - FirstName
                - LastName
                - Gender__c
                - Relationship_to_Member__c
                - DOB__c
                - AccountId
              type: object
              properties:
                FirstName:
                  type: string
                LastName:
                  type: string
                Gender__c:
                  type: string
                  enum:
                    - M
                    - F
                Relationship_to_Member__c:
                  type: string
                  enum:
                    - Self
                    - Spouse
                    - Child
                DOB__c:
                  type: string
                  format: date
                AccountId:
                  type: string
            examples:
              '0':
                value: |-
                  {
                      "FirstName" : "Jane1",
                      "LastName" : "Doe1",
                      "Gender__c" : "M",
                      "Relationship_to_Member__c" : "Spouse",
                      "DOB__c" : "mm/dd/yyyy",
                      "AccountId": "001D000000IqhSL" # this is the 15 digit ID returned when you POST a new member account
                  }
      responses:
        '200':
          description: Ok
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/services/data/v46.0/sobjects/Contact/Id/{contactId}':
    patch:
      tags:
        - Contacts
      summary: Edit existing contact object
      parameters:
        - name: contactId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                AccountNumber:
                  type: string
                Member_Discount_Tier_Manual__c:
                  type: string
                Member_MEC_Prduct__c:
                  type: string
            examples:
              '0':
                value: |-
                  {
                      "AccountNumber" : "0011N00001hpugwQAA",
                      "Member_Discount_Tier_Manual__c" : "T1",
                      "Member_MEC_Product__c" : "SHA Preventative"
                  }
      responses:
        '200':
          description: Created
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PatchResponse'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /services/data/v46.0/sobjects/Condition__c:
    post:
      tags:
        - Conditions
      summary: Creates a new condition for a contact object
      requestBody:
        content:
          application/json:
            schema:
              required:
                - Account__c
                - Contact__c
                - Description__c
                - Is_Cured__c
              type: object
              properties:
                Account__c:
                  type: string
                  description: this is the 15 digit ID returned when you POST a new member account
                Contact__c:
                  type: string
                  description: this is the 15 digit ID returned when you POST a new contact to the member account
                Description__c:
                  type: string
                Is_Cured__c:
                  type: boolean
                Is_Ongoing__c:
                  type: boolean
            examples:
              '0':
                value: |-
                  {
                    "Account__c" : "001D000000IqhSL",  
                    "Contact__c" : "0032i0000085U8s", 
                    "Description__c" : "Description of medical condition. ie: Heart Attack",
                    "Is_Cured__c" : "true",
                    "Is_Ongoing__c" : "false",
                    "Treatment_End_Date__c" : "2015-12-21" 
                    "Locked__c" : true
                  }
      responses:
        '201':
          description: Created
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      servers:
        - url: 'https://CS37.salesforce.com'
    servers:
      - url: 'https://CS37.salesforce.com'
components:
  schemas:
    PatchResponse:
      type: object
      properties:
        id:
          type: string
          nullable: true
        success:
          type: boolean
          nullable: true
        errors:
          type: array
          items:
            type: string
          nullable: true
        created:
          type: boolean
          default: false
          nullable: true
    AccountResponse:
      type: object
      properties:
        id:
          type: string
          nullable: true
        status:
          type: boolean
          nullable: true
        errors:
          type: array
          items:
            type: string
          nullable: true
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          nullable: true
        errorCode:
          type: string
          nullable: true
        fields:
          type: array
          items:
            type: string
          nullable: true
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        password:
          tokenUrl: 'https://test.salesforce.com/services/oauth2/token'
