openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/SirPole/sberbank/1.0.0
info:
  description: Sberbank fair loan mock api
  version: "1.0.0"
  title: Sberbank fair loan mock api
  contact:
    email: martin.brychta@superkoders.com
  license:
    name: MIT
paths:
  /success:
    post:
      summary: Sends successful response
      responses:
       '200':
        description: Success
        content:
          application/json:
            example: 
              statusCode: '200'
              statusText: 'Odeslání dat proběhlo úspěšně, děkujeme.'
              
  /error:
    post:
      summary: Sends failure response
      responses:
        '200':
          description: Error
          content:
            application/json:
              example:
                statusCode: '500'
                statusText: 'Během odesílání dat nastala chyba, litujeme.'
