openapi: 3.0.0
tags:
  - name: Call-API
    description: Call API
  - name: Token-API
    description: Sonetel Token API
paths:
  /call/call-back:
    post:
      summary: Request a call-back call
      requestBody:
        description: >-
          You can request a [Callback call](https://sonetel.com/en/help/help-topics/using-the-service/make-calls/) by specifying your mobile number, the
          destination number being called, the Caller Id to be shown to your
          mobile and the Caller Id to be show to the destination. You must provide
          a valid Caller Id that you are [allowed to use](https://sonetel.com/en/help/help-topics/my-settings/my-call-settings/), such as a [Sonetel number](https://sonetel.com/en/help/help-topics/getting-started/get-a-phone-number/)
          that you have in your account, or a verified mobile number. The
          request must be authorized using a [Sonetel user access token](#/components/schemas/AccessTokenResponse) passed in the authorization header.
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - app_id
                - call1
                - call2
                - show_1
                - show_2
              properties:
                app_id:
                  type: string
                  description: Name of the app from where you call this request
                app_version:
                  type: string
                  description: Your app version
                call1:
                  type: string
                  description: >-
                    Your mobile number in [E164
                    format](https://en.wikipedia.org/wiki/E.164) where you want
                    to receive the call-back call
                call2:
                  type: string
                  description: >-
                    The destination number [E164
                    format](https://en.wikipedia.org/wiki/E.164) being called
                device:
                  type: string
                  description: This field is not in use
                show_1:
                  type: string
                  description: >-
                    The callerId shown in your mobile when Sonetel calls you.
                    This must be a number you own at Sonetel or one of your
                    verified mobile numbers. You can also set this to
                    *automatic* in case you want to have Sonetel select one for
                    you
                show_2:
                  type: string
                  description: >-
                    The callerId shown to the destination number. This must be a
                    number you own at Sonetel or one of your verified mobile
                    numbers. You can also set this to *automatic* in case you
                    want to have Sonetel select one for you
                userid:
                  type: string
                  description: >-
                    The userId of the admin user in your account on behalf of
                    which the call is made. Optional
              example:
                app_id: My call app
                app_version: 1.1.3
                call1: '+12345672345'
                call2: '+19875439876'
                device: null
                show_2: '+12232323232'
                userid: null
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallbackResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
      security:
        - oauth2schema:
            - user.read
            - user.write
      tags:
        - Call-API
  /oauth/token:
    post:
      summary: Request a Sonetel user access token
      requestBody:
        description: >-
          Request a Sonetel user access token in exchange for an email address and password of a user. The access token is a [JWT token](https://en.wikipedia.org/wiki/JSON_Web_Token).
          
          You also need to send an Authorization header in the request carrying Basic authorization credentials with with username and password both set as "any-app".
          
          
          The JWT token contains the iat (issued at time) and the exp(expiry time). A refresh token is also returned in the response which can be used to refresh the access token before expiry.
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - grant_type
                - username
                - password
                - response_type
              properties:
                grant_type:
                  type: string
                  description: This must be set as *password*
                username:
                  type: string
                  description: The user's email address
                password:
                  type: string
                  description: The user's password
                response_type:
                  type: string
                  description: This must be set as *token*
              example:
                grant_type: password
                username: someone@somecompany.com
                password: mypassword
                response_type: token
      responses:
        '200':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
      security:
        - oauth2schema:
            - user.read
            - user.write
      tags:
        - Token-API
components:
  securitySchemes:
    oauth2schema:
      type: oauth2
      flows:
        password:
          tokenUrl: 'https://api.sonetel.com/SonetelAuth/1.3/oauth/token'
          scopes:
            account.read: Account read
            account.write: Account write
            conversation.read: Conversation read
            conversation.write: Conversation write
            user.read: User read
            user.write: User write
  schemas:
    CallbackResponse:
      type: object
      properties:
        response:
          type: string
        statusCode:
          type: integer
          format: int32
      title: Callback response
    AccessTokenResponse:
      type: object
      properties:
        access_token:
          type: string
          description: The JWT access token
        refresh_token:
          type: string
          description: A refresh token to generate a new access token before expiry
        token_type:
          type: string
          description: The token type. Usually set to "bearer"
      example:
        access_token: eyJ0eXAiOiJKV1…
        refresh_token: h2jcn26.jejf
        token_type: bearer
      title: Access token response
info:
  title: Sonetel REST API
  termsOfService: 'https://sonetel.com/en/help/help-topics/terms-conditions/terms-conditions/'
  version: "1.2-oas3"
  contact:
    email: support@sonetel.com
