openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/SpeelYaalHub/example-leave-service/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/SpeelYaalHub/Allsec-Leave-Service/1.0.0
info:
  description: API to manage Leave Requests
  version: "1.0.0"
  title: API to manage Leave Requests
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /leaverequests:
    get:
      summary: lists all Leave requests
      description: |
        Lists all Leave requests
      responses:
        '200':
          description: Lists all leave requests
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LeaveRequest'
        '400':
          description: error
    post:
      summary: submits a leave request
      description: submits a leave request
      responses:
        '201':
          description: leave request created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LeaveRequest'
        description: LeaveRequest  to submit
    patch:
      summary: Updates the existing leave request (for example status to APPROVED)
      description: Updates the existing leave request (for example status to APPROVED)
      responses:
        '201':
          description: leave request updated
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LeaveRequest'
        description: LeaveRequest  to update
      
components:
  schemas:
    LeaveRequest:
      type: object
      required:
        - employeeId
        - name
        - fromDate
        - toDate
        - numberOfDays
      properties:
        id:
          type: integer
          description: "A unique record id for internal technical system use"
        employeeId:
          type: string
          format: "EMP[Number]"
          description: "An employee number used by departments in the organization"
          example: "EMP001"
        name:
          type: string
          description: "Full Name"
        fromDate:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
          description: "Leave starting Date"
        toDate:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
          description: "Leave starting Date"
        numberOfDays:
          type: integer
        status:
          type: string
          enum: ["APPLIED", "APPROVED", "REJECTED", "SENTFORDETAILS"]
