openapi: 3.0.0
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/lucasfilippi/kontiki_hash2email/1.0.0
  - description: You must provide an url matching the following pattern
    url: https://your-domain.tld/hash2subscriber/1.0.0
info:
  description: Hash to subscriber conversion API to implement
  version: "1.0.0"
  title: Hash2Subscriber API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /sha256/{hash}:
    get:
      summary: Return optin subscriber by sha256 hashed email
      operationId: sha256
      description: |
        You need to return the Subsriber according to the sha256 hash 
      parameters:
        - in: path
          name: hash
          description: lowercase email encoded with sha256 algorithm
          required: true
          schema:
            type: string
            maxLength: 64
            minLength: 64
      responses:
        '200':
          $ref: '#/components/responses/Found'
        '400':
          $ref: '#/components/responses/Malformed'
        '404':
          $ref: '#/components/responses/NotFound'
        '410':
          $ref: '#/components/responses/Gone'
  /md5/{hash}:
    get:
      summary: Return optin subscriber by md5 hashed email
      operationId: md5
      description: |
        You need to return the Subsriber according to the md5 hash 
      parameters:
        - in: path
          name: hash
          description: lowercase email encoded with md5 algorithm
          required: true
          schema:
            type: string
            maxLength: 32
            minLength: 32
      responses:
        '200':
          $ref: '#/components/responses/Found'
        '400':
          $ref: '#/components/responses/Malformed'
        '404':
          $ref: '#/components/responses/NotFound'
        '410':
          $ref: '#/components/responses/Gone'
components:
  schemas:
    Subscriber:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: email
          example: subscriber@domain.tld
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        gender: 
          type: string
          enum:
          - M
          - F
  responses:
    Found:
      description: Subscriber matching hash 
      content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Subscriber'
    Malformed:
      description: bad input parameter
    NotFound:
      description: A Subscriber with the specified sha256 was not found
    Gone:
      description: The Subscriber with the specified sha256 is not optin anymore.
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
security:
  - ApiKeyAuth: []
