openapi: 3.0.0
info:
  description: |
    API para integrar el chat de 1doc3 dentro de apps
  version: "1.1.7"
  title: 1DOC3 In-App WebView
  termsOfService: 'https://cdn.1doc3.com/terminos-y-condiciones.pdf'
  contact:
    email: contacto@1doc3.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Autenticación
    description: Autenticación a nivel de servidores
  - name: Usuarios
    description: Operaciones con el los usuarios
  - name: Chat
    description: Operaciones con los chats
paths:
  /token:
    post:
      servers:
      - url: https://auth.1doc3.com
        description: Servidor de autenticación
      tags:
        - Autenticación
      summary: Intercambia credenciales por un token
      operationId: authenticate
      requestBody:
        description: Parámetros para intercambiar por un token
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '403':
          description: Parámetros incorrectos
  /chat/status:
    get:
      tags:
        - Chat
      summary: Verificación del estado del chat
      operationId: getChatStatus
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  available:
                    type: boolean
                    example: true
        '400':
          description: Parámetros incorrectos
  /user:
    post:
      tags:
        - Usuarios
      summary: Crea un usuario
      description: Crea un usuario y devuelve un identificador único
      operationId: createUser
      requestBody:
        description: Datos básicos del usuario
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: a1b2c3-x7y8z9
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
      security:
        - bearerAuth: [] 
  /user/chat-available:
    get:
      tags:
        - Usuarios
      summary: Consulta si un usuario tiene un chat disponible o sin terminar
      description: >-
        Cuando un usuario tiene un chat que no ha utilizado o que no llegó a
        terminar con un médico, la respuesta será `true`, de lo contrario, si el
        usuario nunca ha comprado un chat, o ha finalizado todos los chat
        anteriores que compró, la respuesta será `false`.
      operationId: getUserChatAvailable
      parameters:
        - in: query
          name: id
          description: Identificador del usuario
          required: true
          schema:
            type: string
            example: 0ab3d8f4-881c-4f1e-9fa6-17bfe1acaedcap
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  available:
                    type: boolean
                    example: true
        '400':
          description: Parámetros incorrectos
      security:
        - bearerAuth: []
  /chat:
    post:
      tags:
        - Chat
      summary: Servicio para cargar un chat a un usuario.
      operationId: addChat
      requestBody:
        description: Datos básicos del usuario
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: a1b2c3-x7y8z9
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
      security:
        - bearerAuth: []
    get:
      tags:
        - Chat
      summary: Web que le permite al usuario iniciar el chat con un médico.
      operationId: startChat
      parameters:
        - in: query
          name: id
          description: Identificador del usuario
          required: true
          schema:
            type: string
            example: 0ab3d8f4-881c-4f1e-9fa6-17bfe1acaedcap
      responses:
        '200':
          description: Operación exitosa
        '400':
          description: Parámetros incorrectos
        '403':
          description: No autorizado
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: string
          example: 0ab3d8f4-881c-4f1e-9fa6-17bfe1acaedc
    Credentials:
      type: object
      properties:
        grant_type:
          type: string
          example: client_credentials
        client_id:
          type: string
          example: PE13784B77F2DD9145933E04F35165BD6PP5D07A711EFD4249B0F7CEA982P
        client_secret:
          type: string
          example: PE13784B77F2DD7A711EFD4249B0F7CEA982P
    Token:
      type: object
      properties:
        access_token:
          type: string
          example: >-
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3d3dy4xZG9jMy5jb20iLCJpYXQiOiIxNTE4MDIyNTcwIiwiZXhwIjoiMTUxODEwODk3MCIsInN1YiI6ImNsaWVudHxzYWx1ZHRvdGFsIiwiYXVkIjoiMWRvYzMtYXBpIn0.kq4YZCW01YHcUWwvQHnfTxVm1KCOW23YaP03yRrAujg
        expires_in:
          type: integer
          example: 28800
        token_type:
          type: string
          example: Bearer
servers:
  - url: https://auth.1doc3.com
    description: Servidor de autenticación (producción)
  - url: https://staging.auth.1doc3.com
    description: Servidor de autenticación (pruebas)
  - url: https://apiv3.1doc3.com
    description: API principal (producción)
  - url: http://staging.apiv3.1doc3.com
    description: API principal (pruebas)
  - url: https://1doc3.com
    description: Servidor de aplicación (producción)
  - url: http://dev.1doc3.com
    description: Servidor de aplicación (pruebas)
