openapi: 3.0.0
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/mission-one/MuellerApi/1.0.1
  - description: Live
    url: http://news.mueller.de/api/
  - description: Test
    url: http://news.mueller.de/api-test/
info:
  description: Draft
  version: "1.0.2"
  title: mission-one dialog+ / helloAgain Anbindung
tags:
  - name: Subscribers
paths:
  /subscribers:
    post:
      tags:
        - Subscribers
      summary: adds subscriber
      operationId: addSubscriber
      description: |
        Adds a subscriber and sends a double-opt-in (doi) mail, if no subscriber with the given email exists. If a subscriber already exists, no doi mail is sent.
      responses:
        '204':
          description: 'item created, deliberately no content'
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscriber'
        description: Subscriber to add
components:
  schemas:
    Subscriber:
      type: object
      required:
        - email
        - country
      properties:
        email:
          type: string
          example: max@mustermann.info
        salutation:
          type: string
          example: m
          description: one of [m = male | f = female] or empty value
        firstname:
          type: string
          example: Max
        lastname:
          type: string
          example: Mustermann
        country:
          type: string
          example: AT
          description: 'two-letter country-code, available countries: DE, AT, CH, HU, HR, SI'
        external_id:
          type: string
          example: xxxxx-xxxxxx-xxxxx
          description: 'third-party unique id'
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: X-API-KEY  # name of the header, query parameter or cookie
# 2) Apply the API key globally to all operations
security:
  - ApiKeyAuth: []     # use the same name as under securitySchemes
