openapi: 3.0.0
info:
  title: urlasimg
  version: 1.0.0
  description: The url as img api documentation . For user registration, check the website at https://urlasimg.com/pricing
  contact:
    name: urlasimg
    email: contact@urlasimg.com
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/padjis/urlasimg/1.0.0
  - url: 'https://api.urlasimg.com/v1'
    description: urlasimg
paths:
  /auth:
    post:
      operationId: post-auth
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      description: Authenticates a user and returns an access token if the authentication is successful. The token shall be used for every call to private endpoints. The token is valid for 15 minutes.
      parameters:
        - schema:
            type: string
          in: query
          name: email
          description: The email of the user
          required: true
        - schema:
            type: string
          in: query
          name: password
          description: The password of the user
          required: true
      tags:
        - authentication
  /request:
    post:
      operationId: post-request
      tags:
        - api usage
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
        '403':
          description: Forbidden
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: 'This error is not handled yet, please contact us with the details of your API call details ...'
      parameters:
        - schema:
            type: string
          in: query
          name: url
          description: The url of the page you want to get the image from
          required: true
      description: Returns the main image from an url.
      security:
        - Token-1: []
    parameters: []
components:
  schemas:
    Response:
      title: Response
      type: object
      properties:
        id:
          type: string
        timestamp: 
          type: string
          format: date
        status: 
          type: string
        error:
          type: string
        message:
          type: string
        path:
          type: string
  securitySchemes:
    Token-1:
      type: http
      scheme: bearer
tags:
  - name: authentication
    description: Authenticate to the api
  - name: api usage
    description: Endpoint to use the api
