openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Sample API'
  description: 'This is a sample API.'
  
servers: 
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/MyTeam617/sample/1.0.0
  - url: https://api.example.com/v1.

paths:
  /users/{userId}:
    get:
      summary: Return a user by Id.
      parameters: 
        - name: userId
          in: path
          required: true
          description: The ID of the user to return.
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
