openapi: 3.0.0
info:
  title: Public
  version: '1.0'
  description: Public API
servers:
  - url: 'http://localhost:3000/public'
    description: public url (no auth)
paths:
  /qrcodes:
    post:
      summary: generate qrcodes
      tags: []
      responses:
        '201':
          description: Created
          content:
            image/png:
              schema:
                type: object
              examples: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorcode:
                    type: string
                  message:
                    type: string
              examples:
                exemple:
                  value:
                    errorcode: '1000'
                    message: le doctype ne respecte pas le format attendu
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                doctype:
                  type: string
                  minLength: 5
                  maxLength: 5
                  description: 'FDTNW : valeur fixe désignant la fiche de transmission « New »'
                gendate:
                  type: string
                  pattern: '[0-9]'
                  description: 'AAAAMMJJ : date de génération'
                source:
                  type: string
                  minLength: 10
                  maxLength: 10
                  description: 'SSSSSSSSSS : si bordereau de transmission d''un éditeur/bailleur : source =  BAIL complété par des 0 à gauche '
                counter:
                  type: string
                  minLength: 5
                  maxLength: 5
                  description: 'GGGGG : code guichet'
                territory:
                  type: string
                  minLength: 3
                  maxLength: 3
                  description: 'TTT : code territoire'
                siret:
                  type: string
                  description: 'Ssss : Code SIRET'
                refnum:
                  type: string
                  minLength: 18
                  maxLength: 18
                  description: 'uuu : numéro unique de référence'
                nbfiles:
                  type: string
                  pattern: '[0-9]'
                  description: 'DDD : nombre de dossiers'
                ctrlkey:
                  type: string
                  pattern: '[0-9]'
                  description: modulo 97
              required:
                - doctype
                - gendate
                - source
                - counter
                - territory
                - siret
                - refnum
                - nbfiles
                - ctrlkey
        description: Fiche de Transmission
    parameters: []
components:
  securitySchemes: {}
