penapi: "3.0.1"
info:
  title: "geotab-data-access-layer"
  version: "1.0"
servers:
  - url: "https://uih4cvwmri.execute-api.us-east-1.amazonaws.com/Prod"
tags:
  - name: Geotab Data Access Layer
paths:
  '/{entity}/{env_type}':
    get:
      tags:
        - Geotab Data Access Layer
      parameters:
        - name: entity
          in: path
          description: >-
            defines the type of entity(trip or exception-event) user is
            requesting for
          required: true
          schema:
            type: string
            example: trip
        - name: env_type
          in: path
          description: defines what environment's data user want to access.
          required: true
          schema:
            type: string
            example: dev
          
        - name: start-date
          in: query
          description: "" 
          required: true
          schema:
            type: string
            example: "2018-01-01 12:28:56.062"
            format: date-time
        - name: end-date
          in: query
          description: ""
          required: true
          schema:
            type: string
            example: "2020-03-18 12:29:22.062"
            format: date-time
        
        - name: OptionalQueryStringParams
          in: query
          schema:
            $ref: '#/components/schemas/QueryStringParamsModel'
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataAccessResponse200'
        '400':
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataAccessResponse400'
        '500':
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataAccessResponse500'
          
          
components:
  schemas:
    QueryStringParamsModel:
      type: "object"
      properties:
        offset:
          type: "string"
          example: "2020-03-20 13:16:39.768846"
        limit:
          type: "integer"
          example: 500
          description: "The numbers of items to return."
        is_raw:
          type: "boolean"
          example: false
        filter[afterhoursstart]:
          type: "string"
          example: "eqTrue"
    
    
    GeotabRawTripDataModel:
      type: "object"
      description: "Raw Trip data"
      properties:
        _id: 
          type: "string"
          example: "2020-03-20 13:16:39.508571"
        account_id: 
          type: "string"
          example: "Verisk"
        afterhoursdistance: 
          type: "string"
          example: "0"
        afterhoursdrivingduration:
          type: "string"
          example: "00:00:00"
        afterhoursend: 
          type: "string"
          example: "False"
        afterhoursstart: 
          type: "string"
          example: "False"
        afterhoursstopduration: 
          type: "string"
          example: "00:00:00"
        averagespeed: 
          type: "string"
          example: "16.3415"
        distance: 
          type: "string"
          example: "2.859477"
        drivingduration: 
          type: "string"
          example: "00:10:29.9370000"
        idlingduration: 
          type: "string"
          example: "00:00:03"
        isseatbeltoff:
          type: "string"
          example: "False"
        maximumspeed:
          type: "string"
          example: "53"
        nexttripstart: 
          type: "string"
          example: "2019-10-14 18:46:05.062"
        speedrange1: 
          type: "string"
          example: "0"
        speedrange1duration: 
          type: "string"
          example: "00:00:00"
        speedrange2: 
          type: "string"
          example: "0"
        speedrange2duration: 
          type: "string"
          example: "00:00:00"
        speedrange3: 
          type: "string"
          example: "0"
        speedrange3duration: 
          type: "string"
          example: "00:00:00"
        trip_start: 
          type: "string"
          example: "2019-10-14 12:08:26.063"
        trip_stop: 
          type: "string"
          example: "2019-10-14 12:18:56.000"
        stopduration:
          type: "string"
          example: "06:27:09.0629999"
        stoppoint: 
          type: "string"
          example: "X:-80.5691375732422; Y:37.1259918212891"
        workdistance: 
          type: "string"
          example: "2.859477"
        workdrivingduration: 
          type: "string"
          example: "00:10:29.9370000"
        workstopduration: 
          type: "string"
          example: "06:27:09.0629999"
        datetime: 
          type: "string"
          example: "2019-10-14 12:18:56.000"
        deviceid:
          type: "string" 
          example: "b1"
        driver: 
          type: "string"
          example: "**UnknownDriver"
        id: 
          type: "string"
          example: "b9C64"
        version: 
          type: "string"
          example: ""
        last_updated_dt_utc: 
          type: "string"
          example: "2020-03-20 13:16:39.515"
        device: 
          type: "string"
          example: "b1"
        year: 
          type: "string"
          example: "2020"
        month: 
          type: "string"
          example: "3"
        day:
          type: "string"
          example: "20"
    GeotabRawExceptionEventDataModel:
      type: "object"
      description: " Raw exception-event data"
      properties:
        _id: 
          type: "string"
          example: "2020-03-20 13:24:52.551109"
        account_id: 
          type: "string"
          example: "Verisk"
        activefrom: 
          type: "string"
          example:  "2019-10-23 18:57:18.592"
        activeto: 
          type: "string"
          example: "2019-10-23 18:57:19.676"
        distance: 
          type: "string"
          example: "0.00417686176785238"
        duration: 
          type: "string"
          example: "00:00:01.084000"
        exceptions: 
          type: "string"
          example: ""
        rule: 
          type: "string"
          example: "aMJtmxj0qh0-xGH0estsvUQ"
        deviceid: 
          type: "string"
          example: "b2"
        diagnostic: 
          type: "string"
          example: "DiagnosticAccelerationForwardBrakingId"
        driver:
          type: "string"
          example: "**Unknown Driver"
        version: 
          type: "string"
          example: ""
        id:
          type: "string"
          example: ""
        last_updated_dt_utc:
          type: "string"
          example: "2020-03-20 13:24:52.551"
        device: 
          type: "string"
          example: "b2"
        year:
          type: "string"
          example: "2020"
        month:
          type: "string"
          example: "3"
        day:
          type: "string"
          example: "20"
    GeotabCleansedExceptionEventDataModel:
      type: "object"
      description: " Cleansed exception-event data"
      properties:
        _id: 
          type: "string"
          example: "2020-03-20 13:24:52.551109"
        account_id: 
          type: "string"
          example: "Verisk"
        activefrom: 
          type: "string"
          format: "date-time"
          example:  "2019-10-23 18:57:18.592"
        activeto: 
          type: "string"
          format: "date-time"
          example: "2019-10-23 18:57:19.676"
        distance: 
          type: "integer"
          format: "double"
          example: "0.00417686176785238"
        duration: 
          type: "string"
          example: "00:00:01.084000"
        exceptions: 
          type: "string"
          example: ""
        rule: 
          type: "string"
          example: "aMJtmxj0qh0-xGH0estsvUQ"
        deviceid: 
          type: "string"
          example: "b2"
        diagnostic: 
          type: "string"
          example: "DiagnosticAccelerationForwardBrakingId"
        driver:
          type: "string"
          example: "**Unknown Driver"
        version: 
          type: "string"
          example: ""
        id:
          type: "string"
          example: ""
        last_updated_dt_utc:
          type: "string"
          example: "2020-03-20 13:24:52.551"
        device: 
          type: "string"
          example: "b2"
        year:
          type: "string"
          example: "2020"
        month:
          type: "string"
          example: "3"
        day:
          type: "string"
          example: "20"
    GeotabCleansedTripDataModel:
      type: "object"
      description: "Cleansed Trip data"
      properties:
        _id: 
          type: "string"
          example: "2020-03-20 13:16:39.508571"
        account_id: 
          type: "string"
          example: "Verisk"
        afterhoursdistance: 
          type: "integer"
          format: "double" 
          example: "0"
        afterhoursdrivingduration:
          type: "string"
          example: "00:00:00"
        afterhoursend: 
          type: "string"
          example: "False"
        afterhoursstart: 
          type: "string"
          example: "False"
        afterhoursstopduration: 
          type: "string"
          example: "00:00:00"
        averagespeed: 
          type: "integer"
          format: "double"
          example: "16.3415"
        distance: 
          type: "integer"
          format: "double"
          example: "2.859477"
        drivingduration: 
          type: "string"
          example: "00:10:29.9370000"
        idlingduration: 
          type: "string"
          example: "00:00:03"
        isseatbeltoff:
          type: "string"
          example: "False"
        maximumspeed:
          type: "integer"
          example: "53"
        nexttripstart: 
          type: "string"
          format: "date-time"
          example: "2019-10-14 18:46:05.062"
        speedrange1: 
          type: "integer"
          format: "double"
          example: "0"
        speedrange1duration: 
          type: "string"
          example: "00:00:00"
        speedrange2: 
          type: "integer"
          format: "double"
          example: "0"
        speedrange2duration: 
          type: "string"
          example: "00:00:00"
        speedrange3: 
          type: "integer"
          format: "double"
          example: "0"
        speedrange3duration: 
          type: "string"
          example: "00:00:00"
        trip_start: 
          type: "string"
          format: "date-time"
          example: "2019-10-14 12:08:26.063"
        trip_stop: 
          type: "string"
          format: "date-time"
          example: "2019-10-14 12:18:56.000"
        stopduration:
          type: "string"
          example: "06:27:09.0629999"
        stoppoint: 
          type: "string"
          example: "X:-80.5691375732422; Y:37.1259918212891"
        workdistance: 
          type: "string"
          example: "2.859477"
        workdrivingduration: 
          type: "string"
          example: "00:10:29.9370000"
        workstopduration: 
          type: "string"
          example: "06:27:09.0629999"
        datetime: 
          type: "string"
          format: "date-time"
          example: "2019-10-14 12:18:56.000"
        deviceid:
          type: "string" 
          example: "b1"
        driver: 
          type: "string"
          example: "**UnknownDriver"
        id: 
          type: "string"
          example: "b9C64"
        version: 
          type: "string"
          example: ""
        last_updated_dt_utc: 
          type: "string"
          format: "date-time"
          example: "2020-03-20 13:16:39.515"
        device: 
          type: "string"
          example: "b1"
        year: 
          type: "string"
          example: "2020"
        month: 
          type: "string"
          example: "3"
        day:
          type: "string"
          example: "20"
    DataAccessResponse200:
      type: "object"
      properties:
        Body:
          type: "object"
          properties:
            links:
              type: "object"
              properties:
                offset:
                  type: "string"
                base:
                  type: "string"
                  format: "url"
            results:
              type: "array"
              items:
                type: "object"
    DataAccessResponse400:
      type: "object"
      description: "Bad Request"
      properties:
        Body:
          type: "string"
          example: "Unknown environment type <wrong_env>, valid environment types are dev,test,uat,prod (Case insensitive) or Unknown entity <wrong_entity>, valid entities are trip,exception-event or Required query parameters: start-date, end-date or Invalid value for pathParameter is_raw <wrong_value>, Valid values are true,false or Invalid start-date or end-date for entity type:<trip or exception-event>, please pass start-date and end-date in YYYY-MM-DD HH:mm:ss.SSS format."
    DataAccessResponse500:
      type: "object"
      description: "Internal Server Error"
      properties:
        Body:
          type: "string"
          example: "interval server error"