openapi: 3.0.0
info:
  description: |
    API Adapter for SportsBiz Cognito Integration
    [https://sportsbiz.com](https://sportsbiz.com).
  version: "1.0.0"
  title: Cognito Adapter
  termsOfService: 'https://sportsbiz.com'
  contact:
    email: info@sportsbiz.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/SportsBiz/CognitoAdapter/1.0.0
tags:
  - name: users
    description: manage user registration, authentication, and authorization
  - name: data
    description: Access to User Profile and Preferences
paths:
  /users:
    get:
      tags:
        - users
      summary: get a listing of all  Cognito users
      operationId: getUsers
      responses:
        '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: 'https://api.swaggerhub.com/domains/SportsBiz/common-components/1.0.0#/components/schemas/CognitoUser'
        '500':
          description: internal error

    post:
      tags:
        - users
      summary: register a new user
      operationId: addUser
      responses:
        '405':
          description: Invalid input
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'https://api.swaggerhub.com/domains/SportsBiz/common-components/1.0.0#/components/schemas/CognitoUser'
  /users/{email}:
    get:
      tags:
        - users
      summary:  Find a user by their email address
      description: return a single user
      operationId: getUserByEmail
      parameters:
        - name: email
          in: path
          description: email of user to return
          required: true
          schema:
            type: string
            pattern: '^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$;'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/SportsBiz/common-components/1.0.0#/components/schemas/CognitoUser'
    put:
      tags:
        - users
      summary: update a Cognito User
      operationId: updateCognitoUser
      parameters:
        - name: email
          in: path
          description: email of user to update
          required: true
          schema:
            type: string
            pattern: '^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$;'
      responses:
        '405':
          description: Invalid input
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'https://api.swaggerhub.com/domains/SportsBiz/common-components/1.0.0#/components/schemas/CognitoUser'
    delete:
      tags:
        - users
      summary: disable a Cognito user
      operationId: deleteCognitoUser
      parameters:
        - name: email
          in: path
          description: email of user to disable
          required: true
          schema:
            type: string
            pattern: '^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$;'
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid email supplied
        '404':
          description: user not found
  /users/confirm:
    post:
      tags:
        - users
      summary: confirm a users email or phone
      operationId: confirmUserCommunication
      parameters:
        - name: code
          in: query
          description: verification code sent to user
          required: true
          style: form
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '500':
          description: error
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/SportsBiz/common-components/1.0.0#/components/schemas/ErrorModel'
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'https://api.swaggerhub.com/domains/SportsBiz/common-components/1.0.0#/components/schemas/CognitoLogin'
  /users/signin:
    post:
      tags:
        - users
      summary: authenticate a user
      operationId: signInUser
      responses:
        '202':
          description: additional information required
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/SportsBiz/common-components/1.0.0#/components/schemas/CognitoLogin'
        '200':
          description: operation succesful
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/SportsBiz/common-components/1.0.0#/components/schemas/AppUser'
        '500':
          description: error
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/SportsBiz/common-components/1.0.0#/components/schemas/ErrorModel'
  /users/reset/{email}:
    post:
      tags:
        - users
      summary: reset a users password
      operationId: resetPassword
      parameters:
        - name: email
          in: path
          description: email of user to resetPassword
          required: true
          schema:
            type: string
            pattern: '^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$;'
      responses:
        '200':
          description: succesful operation
        '500':
          description: error
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/SportsBiz/common-components/1.0.0#/components/schemas/ErrorModel'
  /users/respond:
    post:
      tags:
        - users
      summary: response of users challenge code during registration
      operationId: respondToChallenge
      responses:
        '202':
          description: additional information required
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/SportsBiz/common-components/1.0.0#/components/schemas/CognitoLogin'
        '200':
          description: operation succesful
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/SportsBiz/common-components/1.0.0#/components/schemas/AppUser'
        '500':
          description: error
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/SportsBiz/common-components/1.0.0#/components/schemas/ErrorModel'
