openapi: 3.0.0
servers:
  - description: Lastmile Rider Mobile App API
    url:  https://lastmileapp-tx-dev.all-delivery.net
info:
  description: Lastmile Rider Mobile App API <BR> Ver 1.0.3 <br><li> เพิ่ม API POST /transportation/{transportationId}/confirmTrue </li>
  version: "1.0.3"
  title: Lastmile Rider Mobile App API
security: 
  - ApiKeyAuth: []
paths:
  /transportation/waiting/:
    get:
      tags:
        - Transportation Processing
      summary: transportation information for rider
      operationId: getWaitingTransportations
      description: ค้นข้อมูล transportations ของ rider ตามสถานะ [WaitingForRider]
      parameters:
        - in: query
          name: riderId
          description: riderId
          required: true
          schema:
            type: string
          example: 'RD001'
        - in: query
          name: startdate
          description: เวลาเริ่มต้นที่อัพเดตสถานะล่าสุด ไม่ระบุใช้เวลาปัจุบัน -24 hr
          schema:
            type: string
            format: date-time
          example: '2020-05-13T08:30:00+7:00'
        - in: query
          name: enddate
          description: เวลาสิ้นสุดที่อัพเดตสถานะล่าสุด ไม่ระบุใช้เวลาปัจจุบัน
          schema:
            type: string
            format: date-time
          example: '2020-05-13T18:30:00+7:00'
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransportationsResponse'
  /transportation/processing/:
    get:
      tags:
        - Transportation Processing
      summary: transportation information for rider
      operationId: getProcessingTransportations
      description: ค้นข้อมูล transportations ของ rider ตามสถานะ [InTransit, OutForDelivery]
      parameters:
        - in: query
          name: riderId
          description: riderId
          required: true
          schema:
            type: string
          example: 'RD001'
        - in: query
          name: startdate
          description: เวลาเริ่มต้นที่อัพเดตสถานะล่าสุด ไม่ระบุใช้เวลาปัจุบัน -24 hr
          schema:
            type: string
            format: date-time
          example: '2020-05-13T08:30:00+7:00'
        - in: query
          name: enddate
          description: เวลาสิ้นสุดที่อัพเดตสถานะล่าสุด ไม่ระบุใช้เวลาปัจจุบัน
          schema:
            type: string
            format: date-time
          example: '2020-05-13T18:30:00+7:00'
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransportationsResponse'
  /transportation/finished/:
    get:
      tags:
        - Transportation Processing
      summary: transportation information for rider
      operationId: getFinishedTransportations
      description: ค้นข้อมูล transportations ของ rider ตามสถานะ [FailedAttempt, Delivered, Cancel, Exception, Closed]
      parameters:
        - in: query
          name: riderId
          description: riderId
          required: true
          schema:
            type: string
          example: 'RD001'
        - in: query
          name: startdate
          description: เวลาเริ่มต้นที่อัพเดตสถานะล่าสุด ไม่ระบุใช้เวลาปัจุบัน -24 hr
          schema:
            type: string
            format: date-time
          example: '2020-05-13T08:30:00+7:00'
        - in: query
          name: enddate
          description: เวลาสิ้นสุดที่อัพเดตสถานะล่าสุด ไม่ระบุใช้เวลาปัจจุบัน
          schema:
            type: string
            format: date-time
          example: '2020-05-13T18:30:00+7:00'
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransportationsResponse'  
  /transportation/{transportationId}/status:
    post:
      tags:
        - Transportation Processing
      summary: update transporation status
      operationId: updateTransportationStatus
      description: อัพเดตสถานะของ transportation
      parameters:
        - in: path
          name: transportationId
          description: transportationId
          required: true
          schema:
            type: string
          example: 'LM202005015000001'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - status
              properties:
                status:
                  type: string
                  enum: [InTransit, OutForDelivery, FailedAttempt, Delivered, Cancel, Exception, Closed]
                  example: Closed
                riderId:
                  type: string
                  example: 'RD0001'
                deliveryTypeId:
                  type: number
                  enum: [1,2,3]
                  example: 1
                  description: 1=เดิน, 2=จักรยาน, 3=จักรยานยนต์
                signatureImage:
                  type: string
                  format: byte
                  example: iVBORw0KGgoAAAANSUhEUgAABLAAAASwCAIAAABkQySYAAABc2lDQ1BpY2MAACiRdZHPK0RRFMc
                  description: image in base64
      responses:
        '200':
          description: update transportation status success
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: string
                    example: '0000'
                  statusMessage:
                    type: string
                    example: 'Success'
  /transportation/{transportationId}/confirmTrue:
    post:
      tags:
        - Transportation Processing
      summary: confirmTrue
      operationId: confirmTrue
      description: ตรวจสอบสิทธิขายสินค้า TRUE <BR> เรียก QUEUE '7-delivery-confirm-true-sqs' trigger Lambda '7-delivery-confirm-true-sqs-lambda'
      parameters:
        - in: path
          name: transportationId
          description: transportationId
          required: true
          schema:
            type: string
          example: 'LM202005015000001'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - trueTranId
              - orderNo
              - idenId
              - storeId
              properties:
                trueTranId:
                  type: string
                  example: 1234
                orderNo:
                  type: string
                  example: '10001'
                idenId:
                  type: string
                  example: '18205000389654'
                storeId:
                  type: string
                  example: 1234
      responses:
        '200':
          description: TRUE return status success
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: string
                    example: '0000'
                  statusMessage:
                    type: string
                    example: 'Success'
        '400':
          description: TRUE return status fail
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: string
                    example: '1000'
                  statusMessage:
                    type: string
                    example: 'ไม่สามารถใช้สิทธิได้ แจ้งลูกค้า กรุณาติดต่อทรู 1242'
  
components:
  securitySchemes:
      ApiKeyAuth:
        type: apiKey
        in: header
        name: x-api-key
  schemas:
    TransportationsResponse:
      type: object
      properties:
        statusCode:
          type: string
          example: '0000'
        statusMessage:
          type: string
          example: 'Success'
        result:
          type: array
          items:
            $ref: '#/components/schemas/Transportation'
    Transportation:
      type: object
      required:
        - transportationId
        - status
        - companyCode
        - serviceCode
        - orderNo
        - requestType
        - requestDateTime
        - customer
        - payment
        - order
        - store
      properties:
        transportationId:
          type: string
          example: 'LM202005140000001'
        status:
          type: string
          enum: [WaitingForRider, InTransit, OutForDelivery, FailedAttempt, Delivered, Cancel, Exception, Closed]
          example: OutforDelivery
        companyCode:
          type: string
          example: 'CPALL'
        serviceCode:
          type: string
          example: 'CPA001'
        orderNo:
          type: string
          example: '1561898749875419'
        requestType:
          type: string
          enum: [now,booking]
          example: 'now'
        requestDateTime:
          type: string
          format: date-time
          example: '2020-05-13T08:30:00+7:00'
        package:
          type: array
          items:
            type: object
            properties:
              weight:
                type: string
                format: kg
                example: 0.5
              size:
                type: string
                format: cm
                example: 20x30x11
        customer: 
          $ref: '#/components/schemas/Customer'
        payment:
          $ref: '#/components/schemas/Payment'
        order:
          $ref: '#/components/schemas/Order'
        store:
          $ref: '#/components/schemas/Store'
 
    Customer:
      type: object
      properties:
        customerName:
          type: string
          example: 'ธนพล จิตนุพงศ์'
        customerTel:
          type: string
          example: '0920123096'
        customerAddress:
          type: string
          example: '334/12 ซอยธรรมสโรช ถนนพญาไท แขวงถนนเพชรบุรี เขตราชเทวี กรุงเทพฯ 10400'
        remark:
          type: string
          example: 'เชิงสะพานหัวช้าง'
        lat:
          type: string
          example: '13.8638352937558'
        long:
          type: string
          example: '100.4923581794014'
    Payment:
      type: object
      properties:
        paymentType:
          type: string
          example: cod
          enum: [no, cod]
        userPreferred:
          type: string
          example: cash
          enum: [cash, tmw]
    Order:
      type: object
      properties:
        orderNo:
          type: string
          example: '1561898749875419'
        orderDateTime:
          type: string
          example: '2020-05-13T18:30:00+7:00'
        totalPrice:
          type: number
          example: 138
        discount:
          type: number
          example: 0
        netprice:
          type: number
          example: 158
        totalItem:
          type: integer
          example: 4
        label:
          type: array
          items:
            type: string
            example: ['เป็นสมาชิก All Member','สะสม M-Stamp','ข้อความถึงร้าน: ขอหลอดเพิ่ม']
        orderItems:
          type: array
          items:
            type: object
            properties:
              itemName:
                type: string
                example: 'มัคคิอาโตเย็น size L'
              amount:
                type: integer
                example: 1
              price:
                type: number
                example: 50
              unitPrice:
                type: number
                example: 50
              remark:
                type: string
                example: หวานน้อย
              productImage:
                type: string
                example: 'https://alldelivery.cpcall.co.th/product/12491293.png'
    Store:
      type: object
      properties:
        storeId:
          type: string
          example: '00151'
        storeName:
          type: string
          example: 'พระรามสี่-2(บ่อนไก่)'
        storeTel:
          type: string
          example: 0910020151
        storeAddress:
          type: string
          example: 'ถ.พระราม-4 แขวงลุมพินี เขตปทุมวัน กรุงเทพมหานคร'
        remark:
          type: string
          example: 'Other telephone: 022514573'
        lat:
          type: string
          example: 13.7240250167412
        long:
          type: string
          example: 100.5501075073560
