openapi: 3.0.0
servers:
  - url: https://staging-apps.i2iex.ph/api-apic
    description: Sandbox server (Staging)
info:
  description: |
    # Introduction
    Welcome to i2i REST API Portal.

  version: "0.2.2"
  title: i2i API Portal
  termsOfService: 'https://ubx.ph'
  contact:
    name: API Support
    email: keihertz@ubx.ph
    
paths:
  /auth/token:
    post:
      tags: 
        - Authentication
      summary: Getting the access token to authenticate request
      description: Getting the access token
      requestBody:
        $ref: "#/components/requestBodies/authToken"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessToken'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServer'
                
  /remittance:
    get:
      tags:
        - Remittance
      summary: Get remittance status via senderReference
      description: Get remittance status
      security:
        - Bearer: []
      parameters:
        - name: senderReference
          in: query
          description: 'Remittance senderReference to be checked'
          required: true
          schema:
            type: string
            example: 'UB123456'
            description: 'This is the sender reference id from the requester.'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  i2iReference:
                    type: string
                    example: 'SC123456789012345'
                    description: "This i2i's tracking reference for the transaction."
                  status:
                    type: string
                    example: 'ENCASHED'
                    description: 'List of possible status: PENDING, FOR ENCASHMENT, ENCASHED, REFUNDED'
        400:
          description: Illegal Access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServer'
  
  /remittance/fees:
    get:
      tags: 
        - Remittance
      summary: Fetch fees for a specific amount
      description: Fetch fees
      security:
        - Bearer: []
      parameters:
        - name: amount
          in: query
          description: 'amount'
          required: true
          schema:
            type: number
            example: '100.00'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  i2iFee:
                    type: number
                    example: 10
                    description: "This i2i's base fee for all remittance transactions."
                  serviceFee:
                    type: number
                    example: 5
                    description: "This is the addon fee which is subject to the entity's pricing model."
        400:
          description: Illegal Access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServer'
  
  /remittance/feesMatrix:
    get:
      tags: 
        - Remittance
      summary: Fetch remittance fees matrix
      description: Fetch remittance fees matrix
      security:
        - Bearer: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      example: 1
                      description: 'Reference id of the pricing range.'
                    minAmount:
                      type: number
                      example: 1.00
                      description: 'Start amount of pricing range.'
                    maxAmount:
                      type: number
                      example: 100.99
                      description: 'End amount of pricing range.'
                    value:
                      type: number
                      example: 2.00
                      description: 'i2i pricing for the amount range.'
        400:
          description: Illegal Access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServer'
                
  /remittance/validate:
    post:
      tags: 
        - Remittance
      summary: Validate remittance fields
      description: Validate fields
      security:
        - Bearer: []
      requestBody:
        $ref: "#/components/requestBodies/remittance"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'Failed'
                  reasons:
                    type: array
                    items:
                      type: object
                      properties:
                        fieldName:
                          type: string
                          example: 'amount'
                          description: 'The key of the field with error.'
                        error:
                          type: string
                          example: 'The error message for the field.'
        400:
          description: Illegal Access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServer'
  
  /remittance/process:
    post:
      tags: 
        - Remittance
      summary: Process the remittance transaction
      description:  Process remittance
      security:
        - Bearer: []
      requestBody:
        $ref: "#/components/requestBodies/remittance"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  i2iReference:
                    type: string
                    example: "SC123456789012345"
                    description: "This i2i's tracking reference for the transaction."
                  senderReference:
                    type: string
                    example: "UB123456"
                    description: 'This is the sender reference id from the requester.'
                  transactionCode:
                    type: string
                    example: "123abc"
                    description: 'This is the transaction code to be used by the receiver to redeem the remittance. Sent to the receiver via SMS.'
                  status:
                    type: string
                    example: "PENDING"
                    description: 'List of possible status: PENDING, FOR ENCASHMENT, ENCASHED, REFUNDED'
        400:
          description: Illegal Access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServer'
                
  /remittance/cancel:
    post:
      tags:
        - Remittance
      summary: Cancels a remittance given that it is still unclaimed
      description: Cancel remittance
      security:
        - Bearer: []
      requestBody:
        $ref: '#/components/requestBodies/remittanceCancel'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  senderReference:
                    type: string
                    example: 'UB123456'
                    description: 'This is the sender reference id from the requester.'
                  status:
                    type: string
                    example: "PENDING"
                    description: 'List of possible status: PENDING, FOR ENCASHMENT, ENCASHED, REFUNDED'
        400:
          description: Illegal Access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServer'

  /remittance/report:
    get:
      tags: 
        - Remittance
      x-swagger-router-controller: RemittanceController
      operationId: generateRemittanceReport
      summary: Generate remittance report
      description: Generate remittance report
      security:
        - Bearer: []
      parameters:
        - in: query
          name: startDate
          description: 'Start date (Optional)'
          schema:
            type: string
        - in: query
          name: endDate
          description: 'End date (Optional)'
          schema:
            type: string
        - in: query
          name: search
          description: 'Search keyword/s (Optional)'
          schema:
            type: string
      responses:
        200:
          description: Success
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
        400:
          description: Illegal Access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServer'

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  requestBodies:
    authToken:
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                type: string
                description: 'Username provided by i2i.'
                example: 'unionbankph'
              password:
                type: string
                description: 'Password provided by i2i.'
                example: 'P@ssw0rd123!'
            required:
              - username
              - password
    remittance:
      content:
        application/json:
          schema:
            type: object
            properties:
              senderReference:
                type: string
                description: 'This is the sender reference id from the requester.'
                example: 'UB123456'
              amount:
                type: number
                description: 'Amount of the requested remittance.'
                example: 100.00
              senderName:
                type: string
                description: 'Full name of the sender client.'
                example: 'Juan Dela Cruz'
              senderMobileNumber:
                type: string
                description: "Sender client's mobile number."
                example: '+639123456789'
              receiverName:
                type: string
                description: 'Full name of the receiver client.'
                example: 'Juana Reyes'
              receiverMobileNumber:
                type: string
                description: "Receiver client's mobile number."
                example: '+639987654321'
    remittanceCancel:
      content:
        application/json:
          schema:
            type: object
            properties:
              i2iReference:
                type: string
                description: "This i2i's tracking reference for the transaction."
                example: 'SC123456789012345'
            required:
              - i2iReference

  schemas:
    Forbidden:
      type: object
      properties:
        error:
          type: string
          example: 'IllegalAccessError'
        message:
          type: string
          example: 'Authentication header not set'
        eventCode:
          type: string
          example: '102'
    InternalServer:
      type: object
      properties:
        error:
          type: string
          example: 'AppError'
        message:
          type: string
          example: 'Something wrong happened. Please contact i2i at support@ubx.ph'
        eventCode:
          type: string
          example: 'eb887931c2fe9502'
    SuccessToken:
      type: object
      properties:
        accessToken:
          type: string
        expiresIn:
          type: string
          example: '15m'
          description: "Token's expiration in m (mins), h (hours), or d (days)."
    Report:
      type: object
      properties:
        requestDate:
          type: string
          description: 'This is the date the transaction was requested.'
          example: '2020-01-01 03:30:05 PM'
        i2iReference:
          type: string
          description: "This i2i's tracking reference for the transaction."
          example: 'SC1234567890'
        senderName:
          type: string
          description: 'This is the name of the transaction sender'
          example: 'Cruz, Juan Dela'
        receiverName:
          type: string
          description: 'This is the name of the transaction receiver'
          example: 'Doe, John'
        amount:
          type: number
          description: 'This is the amount to be transferred'
          example: '100.00'
        txFee:
          type: string
          description: 'This is the transaction fee'
          example: '10.00'
        serviceCharge:
          type: string
          description: 'This is the service charge'
          example: '0.00'
        totalAmount:
          type: string
          description: 'This is the total amount'
          example: '110.00'
        status:
          type: string
          description: 'List of possible status: PENDING, FOR ENCASHMENT, ENCASHED, REFUNDED'
          example: 'ENCASHED'
        encashedDate:
          type: string
          description: 'This is the date when the transaction was encashed'
          example: '2020-01-02 02:30:05 PM'
