openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/shivek/automation-rgm-buslane-demo/1.0.0
info:
  description: Automation - Ramat Gan Municipal - BusLane - Demo
  version: "1.0.0"
  title: Automation Api
  contact:
    email: yair@shivek.co.il
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: Operations
    description: Operations available for calls comming from the workflow API Managment or
      authenticated testers
paths:
   /getVehicleOwnerContactInfo:
    get:
      tags:
        - Operations
      summary: Get vehicle owner contact information
      operationId: getVehicleOwnerContactInfo
      description: >
        By passing the vehicleRegistrationID and OwnerID we get back a full
        contac information for the owner
      parameters:
        - in: query
          name: ownerId
          description: pass in an ID to receive current address
          required: true
          schema:
            type: string
      responses:
        '200':
          description: vehicle owner address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vehicleOwnerAddress'
        '400':
          description: Bad ownerId or Can not find address for this ownerId
    post:
      tags:
        - Operations
      summary: Get vehicle owner contact information
      operationId: getVehicleOwnerContactInfo2
      description: >
        By passing the vehicleRegistrationID and OwnerID we get back a full
        contac information for the owner
      responses:
        '200':
          description: vehicle owner address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vehicleOwnerAddress'
        '400':
          description: Bad ownerId or Can not find address for this ownerId
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ownerId:
                  description: pass in an ID to receive current address
                  type: string
                  example: 058015521
components:
  schemas:
    vehicleOwnerAddress:
      type: object
      required:
        - id
        - vehicleRegId
        - name
        - address
      properties:
        id:
          type: string
          example: 058015521
        vehicleRegId:
          type: string
          example: 830-40-301
        name:
          $ref: '#/components/schemas/fullName'
        address:
          $ref: '#/components/schemas/address'
    fullName:
      type: object
      required:
        - firstName
        - lastName
      properties:
        firstName:
          type: string
          example: Yosef
        lastName:
          type: string
          example: Cohen
        middleInitials:
          type: string
          example: Jr.
    address:
      type: object
      required:
        - street
        - city
        - zipCode
      properties:
        street:
          type: string
          example: 123 Herzel Street
        city:
          type: string
          example: Haifa
        zipCode:
          type: string
          example: 33670
