openapi: 3.0.0
info:
  version: "v1-oas3"
  title: Converter API
  description: API to convert any format into pdf format and pdf format to tiff.
servers:
  - url: https://jhconverterapi-test.apps.cac.preview.pcf.manulife.com/
    description: Test
  - url: https://jhconverterapi-uat.apps.cac.pcf.manulife.com/
    description: UAT
  - url: https://jhconverterapi-prod.apps.cac.pcf.manulife.com/
    description: Prodution
paths:
  /convertfile:
    post:
      tags:
        - ConverterApi
      operationId: ConverterApi_documentConvert
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/CustomResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/CustomResponse'
            text/xml:
              schema:
                $ref: '#/components/schemas/CustomResponse'
      deprecated: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/DocumentRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/DocumentRequest'
          text/xml:
            schema:
              $ref: '#/components/schemas/DocumentRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/DocumentRequest'
        required: true
  /combinePDFs:
    post:
      tags:
        - ConverterApi
      operationId: ConverterApi_combinePDFs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/CustomResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/CustomResponse'
            text/xml:
              schema:
                $ref: '#/components/schemas/CustomResponse'
      deprecated: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PDFMergeRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/PDFMergeRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/PDFMergeRequest'
          text/xml:
            schema:
              $ref: '#/components/schemas/PDFMergeRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PDFMergeRequest'
        required: true
components:
  schemas:
    DocumentRequest:
      type: object
      properties:
        Base64EncodedData:
          type: string
        DocumentType:
          type: string
        ConvertType:
          type: string
    CustomResponse:
      type: object
      properties:
        Code:
          type: string
        Message:
          type: string
        detail:
          $ref: '#/components/schemas/Object'
    Object:
      type: object
      properties: {}
    PDFMergeRequest:
      type: object
      properties:
        PDFOneBase64EncodedData:
          type: string
        PDFTwoBase64EncodedData:
          type: string
