openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/calplug/SimHome/v1
  - description: Pluto API
    url: https://pluto.calit2.uci.edu:8481/v1
info:
  version: "v1"
  title: SimHome API
  description: >-
    The SimHome API for accessing energy data and interacting with bots.
  contact:
    email: simhomecalplug@gmail.com
paths:
  /ping:
    get:
      summary: Server heartbeat operation
      description: >-
        Ensure API is listening for requests.
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
      tags:
        - test
  /energy:
    get:
      summary: Get energy usage
      description: >-
        Retrieve energy usage over specified time period.
      parameters:
        - in: query
          name: start
          schema:
            type: string
            format: date-time
          required: false
          description: Start date of range to retrieve energy data.
        - in: query
          name: end
          schema:
            type: string
            format: date-time
          required: false
          description: End date of range to retrieve energy data.
      responses:
        '200':
          description: OK
      tags: 
        - simhome
  /energy/devices:
    get:
      summary: Get list of all device information
      description: >-
        Retrieve list of devices in the SimHome.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Devices'
      tags: 
        - simhome
  /energy/total:
    get:
      summary: Get energy usage
      description: >-
        Retrieve energy usage over specified time period.
      parameters:
        - in: query
          name: StartDate
          schema:
            type: string
            format: date
            example: 01/01/2019
          required: true
          description: Start date of range to retrieve energy data.
        - in: query
          name: EndDate
          schema:
            type: string
            format: date
            example: 05/01/2019
          required: true
          description: End date of range to retrieve energy data.
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: number
      tags: 
        - simhome
  /energy/usage:
    get:
      summary: Get energy usage
      description: >-
        Retrieve energy usage over specified time period.
      parameters:
        - in: query
          name: DeviceID
          schema:
            type: integer
            example: 48
          required: true
          description: SimHome device ID to compute energy usage for.
        - in: query
          name: StartDate
          schema:
            type: string
            format: date
            example: 01/01/2019
          required: true
          description: Start date of range to retrieve energy data.
        - in: query
          name: EndDate
          schema:
            type: string
            format: date
            example: 05/01/2019
          required: true
          description: End date of range to retrieve energy data.
      responses:
        '200':
          description: OK
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/EnergyUsage'
      tags: 
        - simhome
  /energy/usagerange:
    get:
      summary: Get energy usage
      description: >-
        Retrieve energy usage over specified time period.
      parameters:
        - in: query
          name: idType
          schema:
            type: string
            enum: ["", name, UID]
            default: ""
          required: false
          description: Retrieve energy usage by device name, UID, or id (defaults to id).
        - in: query
          name: DeviceID
          schema:
            type: integer
          required: true
          description: SimHome device ID to compute energy usage for.
        - in: query
          name: Increment
          schema:
            type: integer
          required: false
          description: Currently does nothing, may be used in the future to specify days or hours or custom increment.
        - in: query
          name: StartDate
          schema:
            type: string
            format: date
          required: true
          description: Start date of range to retrieve energy data.
        - in: query
          name: EndDate
          schema:
            type: string
            format: date
          required: true
          description: End date of range to retrieve energy data.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnergyUsageRange'
      tags: 
        - simhome
  /energy/totaldistribution:
    get:
      summary: Get energy usage by device
      description: >-
        Retrieve energy usage by device over specified period.
      parameters:
        - in: query
          name: StartDate
          schema:
            type: string
            format: date
          required: true
          description: Start date of range to retrieve energy data.
        - in: query
          name: EndDate
          schema:
            type: string
            format: date
          required: true
          description: End date of range to retrieve energy data.
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: number
      tags: 
        - simhome
  /energy/editdevice:
    get:
      summary: Edit device
      parameters:
        - in: query
          name: idType
          schema:
            type: string
          required: false
          description: \"name\" or \"UID\",  to select which type of specifier to use (device_name, or device_uid), other values will use normal id (device_id); not used in add
        - in: query
          name: id
          schema:
            type: string
          required: false
          description: name, uid, or id; depends on idType, not used in add
        - in: query
          name: func
          schema:
            type: integer
            enum: [0, 1, 2]
          required: true
          description: 0=add, 1=delete, 2=edit
        - in: query
          name: device_id
          schema:
            type: integer
        - in: query
          name: device_uid
          schema:
            type: string
        - in: query
          name: device_name
          schema:
            type: string
        - in: query
          name: device_type
          schema:
            type: string
        - in: query
          name: SCE_rebate_id
          schema:
            type: integer
      responses:
        '202':
          description: OK
      tags:
        - simhome
  /rebates:
    get:
      summary: Get all rebates
      description: >-
        Retrieve all device rebates.
      parameters:
        - in: query
          name: provider
          schema:
            type: string
          required: false
          description: ID of rebate provider to filter rebates by.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rebates'
      tags: 
        - simhome
  /smartenit/devices:
    get:
      summary: Get all devices from smartenit.
      description: >-
        Route to Smartenit API for all devices.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmartenitDevices'
      tags:
        - smartenit
  /smartenit/on:
    post:
      summary: Turn on device.
      parameters:
        - in: query
          name: id
          schema:
            type: string
        - in: query
          name: compid
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: "{\"message\":\"Device method executed\",\"data\":{}}"
      tags:
        - smartenit
  /smartenit/off:
    post:
      summary: Turn off device.
      parameters:
        - in: query
          name: id
          schema:
            type: string
        - in: query
          name: compid
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: "{\"message\":\"Device method executed\",\"data\":{}}"
      tags:
        - smartenit
components:
  schemas:
    Devices:
      type: array
      items:
        type: object
        properties:
          device_id:
            type: string
            description: Device ID assigned by SimHome.
          device_uid:
            type: string
            description: Device ID assigned by Smartenit.
          device_name:
            type: string
            description: Name of device.
          device_type:
            type: string
            description: Type of device.
          SCE_suggested_device_id:
            type: string
            description: SCE suggested device.
    EnergyUsage:
      type: object
      properties:
        kWh:
          type: number
        data:
          type: array
          items:
            type: object
            properties:
              energy_id:
                type: integer
              device_id:
                type: string
              energy_topic:
                type: string
              energy_value:
                type: integer
              energy_timestamp:
                type: string
                format: date-time
    EnergyUsageRange:
      type: object
      properties:
        total:
          type: number
        usageData:
          type: array
          items:
            type: object
            properties:
              start:
                type: string
                format: date-time
              end:
                type: string
                format: date-time
              kwh:
                type: number
    Rebates:
      type: object
      properties:
        rebates:
          type: array
          items:
            $ref: '#/components/schemas/Rebate'
    Rebate:
      type: object
      properties:
        id:
          type: integer
          description: ID of rebate.
        type:
          type: integer
          description: type of rebate.
        name:
          type: string
          description: Name of rebate.
        description:
          type: string
          description: Rebate description.
        url:
          type: string
          description: url.
        provider:
          type: string
          description: provider.
        createdAt:
          type: string
          format: date-time
          description: datetime of rebate info created.
    SmartenitDevices:
      type: object
      properties:
        device_name:
          type: object
          properties:
            name:
              type: string
            type:
              type: string
            id:
              type: string
            hasMetering:
              type: boolean
            hasOnOff:
              type: boolean
            meteringComp:
              type: string
            onOffComp:
              type: string
tags:
  - name: New Tag 1
