openapi: 3.0.2
info:
  title: Vidado Read API
  description: The Vidado READ API - Provides a simple API to allow potential clients and partners to use Vidado’s READ engine text field digitization capability.
  version: 0.1.0
servers:
  - url: 'https://api.vidado.ai'
paths:
  /read/text:
    post:
      tags:
        - read-text
      summary: Digitize Image Text.
      description: This method takes an image snippet and attempts to extract and machine or human entered data on the snippet.
      parameters: 
        - in: query
          name: autoscale
          schema:
            type: boolean
          description: This parameter is optional and allow the image to be scaled automatically to 100,000 pixels. 
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DigitizeImageRequestBody'
      responses:
        '200':
          description: Successful Response
          headers:
            X-Ratelimit-Limit:
              description: The rate limit ceiling for the request
              style: simple
              explode: false
              schema:
                type: integer
            X-Ratelimit-Remaining:
              description: The number of requests left
              style: simple
              explode: false
              schema:
                type: integer
            X-Ratelimit-Reset:
              description: The remaining window before the rate limit resets in UTC epoch seconds
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigitizeImageResponseBody'
              examples:
                Success Response Example:
                  $ref: '#/components/examples/Success'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigitizerError'
              examples:
                Image missing:
                  $ref: '#/components/examples/ImageMissing'
                Tracking info missing:
                  $ref: '#/components/examples/NoTrackingInfo'
                Content type missing:
                  $ref: '#/components/examples/ContentTypeMissing'
                Image dimensions too big:
                  $ref: '#/components/examples/ImageDimensionsTooBig'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
              examples:
                API token missing:
                  $ref: '#/components/examples/APITokenMissing'
        '403':
          description: Permission denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
              examples:
                Authentication not valid:
                  $ref: '#/components/examples/AuthenticationNotValid'
        '411':
          description: Missing content-length
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigitizerError'
        '413':
          description: Image size exceeded the memory limit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigitizerError'
              examples:
                Image size too big:
                  $ref: '#/components/examples/ImageTooBig'
        '415':
          description: Unsupported media
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigitizerError'
              examples:
                Bad File:
                  $ref: '#/components/examples/BadFile'
                Bad Content Type:
                  $ref: '#/components/examples/BadContentType'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
              examples:
                Rate limit exceeded:
                  $ref: '#/components/examples/RateLimitExceeded'
        default:
          description: Unexpected error
      security:
        - ApiKeyAuth: []
components:
  schemas:
    DigitizeImageRequestBody:
      title: Digitizer Request Body
      required:
        - image
      type: object
      properties:
        image:
          title: Image
          type: string
          format: binary
    DigitizeImageResponseBody:
      title: Digitizer Response Body
      required:
        - confidence
        - filename
        - request_id
        - value
      type: object
      properties:
        value:
          title: DigitizedText
          type: string
        confidence:
          title: Confidence
          type: number
          format: float
        filename:
          title: FileName
          type: string
        request_id:
          title: RequestId
          type: string
    DigitizerError:
      title: Vidado Digitizer Error
      required:
        - detail
      type: object
      properties:
        detail:
          title: Message Details
          type: string
    APIError:
      title: API Error
      required:
        - error
      type: object
      properties:
        error:
          title: API Error Details
          type: string
  examples:
    NoTrackingInfo:
      value:
        detail: No api-management-tracking-info provided in header
    ContentTypeMissing:
      value:
        detail: No content-type provided in header
    ImageMissing:
      value:
        detail: No image provided
    APITokenMissing:
      value:
        error: Authorization field missing
    ImageDimensionsTooBig:
      value:
        detail: Image dimensions too large (100,000 sq pixels)
    ImageTooBig:
      value:
        error: Image size too big
    AuthenticationNotValid:
      value:
        error: Access to this API has been disallowed
    BadFile:
      value:
        detail: Unable to open file
    BadContentType:
      value:
        detail: Content-type must be multipart/form-data
    RateLimitExceeded:
      value:
        error: Rate limit exceeded
    Success:
      value:
        confidence: 0.98
        filename: name.png
        request_id: 1da98ae1-9686-44ce-81f7-2a7b01c45745
        value: joseph
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
