openapi: 3.0.0
info:
    description: Order api for Fachman
    version: '3.0.0'
    title: Fachman sign-app
tags:
    - name: user
      description: 'Actions regarding user management, login, logout, user rights'
    - name: order
      description: Actions working with orders
servers:
    - url: https://virtserver.swaggerhub.com/SirPole/fachman-sign_app/3.0.0
      description: SwaggerHub API Auto Mocking
    - url: 'http://localhost:8080'
      description: Local mock server
    - url: 'https://shop:fachman1@fachman-stage.www4.superkoderi.cz/api'
      description: Staging server
paths:
    /login:
        post:
            operationId: login
            tags:
                - user
            summary: Login to application
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Credentials'
            responses:
                '200':
                    description: Logged in
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UserData'
                '403':
                    description: Invalid credentials
    /orders:
        get:
            operationId: getOrders
            tags:
                - order
            summary: Get all orders
            responses:
                '200':
                    description: List of orders
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Order'
                            example:
                                - id: 1
                                  company: Test company 1
                                  address: Location 1
                                  number: 111
                                  boxNumber: 111
                                  signee: null
                                  signature: null
                                - id: 2
                                  company: Test company 1
                                  address: Location 1
                                  number: 222
                                  boxNumber: 222
                                  signee: signee
                                  signature: >-
                                      data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAALOklEQVR4Xu2dWchuVRmAH3OIQi3tVKCWVhIZolCKTVLRRASRgRANlEEF5k2QUlRkUdRF4U1dNEBGIwRZN0WmNE84QCF5CisttUHT0kgszXhtbdhtvv+cb9jTu9ezYfOfo99e77ued52H
                                - id: 3
                                  company: Test company 1
                                  address: Location 2
                                  number: 333
                                  boxNumber: 333
                                  signee: null
                                  signature: null
                                - id: 4
                                  company: Test company 2
                                  address: Location 1
                                  number: 444
                                  boxNumber: 444
                                  signee: null
                                  signature: null
                                - id: 5
                                  company: Test company 2
                                  address: Location 1
                                  number: 555
                                  boxNumber: 555
                                  signee: null
                                  signature: null
                '401':
                    $ref: '#/components/responses/UnauthorizedError'
            security:
                - bearerAuth: []
    '/order/{orderid}':
        get:
            operationId: getOrderById
            tags:
                - order
            summary: Find order by ID
            parameters:
                - name: orderid
                  in: path
                  description: ID of order to return
                  required: true
                  schema:
                      type: integer
                      format: int32
                      minimum: 1
                  example: 1
            responses:
                '200':
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Order'
                            example:
                                id: 1
                                number: 111
                                boxNumber: 111
                                company: Test company 1
                                address: Location 1
                                signee: null
                                signature: null
                '400':
                    description: Invalid ID supplied
                '401':
                    $ref: '#/components/responses/UnauthorizedError'
                '404':
                    description: Order not found
            security:
                - bearerAuth: []
        put:
            operationId: updateOrderById
            tags:
                - order
            summary: Update existing order
            parameters:
                - name: orderid
                  in: path
                  description: ID of order to update
                  required: true
                  schema:
                      type: integer
                      format: int32
                      minimum: 1
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Order'
            responses:
                '200':
                    description: Successfully updated order
                '400':
                    description: Invalid ID supplied
                '401':
                    $ref: '#/components/responses/UnauthorizedError'
            security:
                - bearerAuth: []
components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
    schemas:
        UserData:
            type: object
            properties:
                login:
                    type: string
                apiKey:
                    type: string
            required:
                - login
                - apiKkey
            example:
                login: user
                apikey: sample
        Order:
            type: object
            required:
                - id
                - company
                - address
                - number
                - boxNumber
            properties:
                id:
                    type: integer
                company:
                    type: string
                address:
                    type: string
                signee:
                    type: string
                    description: Name of the person who signed for the order
                signature:
                    type: string
                    description: Base64 representation of signee signature
                number:
                    type: integer
                boxNumber:
                    type: integer
            example:
                id: 1
                company: Test company 1
                address: Location 1
                signee: signee
                signature: >-
                    data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAALOklEQVR4Xu2dWchuVRmAH3OIQi3tVKCWVhIZolCKTVLRRASRgRANlEEF5k2QUlRkUdRF4U1dNEBGIwRZN0WmNE84QCF5CisttUHT0kgszXhtbdhtvv+cb9jTu9ezYfOfo99e77ued52H/e1/7bUOwUMCEpBAEgKHJMnTNCUgAQmgsBwEEpBAGgIKK02pTFQCElBYjgEJSCANAYWVplQmKgEJKCzHgAQkkIaAwkpTKhOVgAQUlmNAAhJIQ0BhpSmViUpAAgrLMSABCaQhoLDSlMpEJSABheUYkIAE0hBQWGlKZaISkIDCcgxIQAJpCCisNKUyUQlIQGE5BiQggTQEFFaaUpmoBCSgsBwDEpBAGgIKK02pTFQCElBYjgEJSCANAYWVplQmKgEJKCzHgAQkkIaAwkpTKhOVgAQUlmNAAhJIQ0BhpSmViUpAAgrLMSABCaQhoLDSlMpEJSABheUYkIAE0hBQWGlKZaISkIDCcgxIQAJpCCisNKUyUQlIQGE5BiQggTQEFFaaUpmoBCSgsBwDEpBAGgIKK02pTFQCElBYjgEJSCANAYWVplQmKgEJKCzHgAQkkIaAwkpTKhOVgAQUlmNAAhJIQ0BhpSmViUpAAgrLMSABCaQhoLDSlMpEZ0TgJcAzgYtnlFMVqSisKspsJ7ckcALw1HI+Ejir/Hk/8GLAfz9bgt32MoFvS87rlkSgLaZGUPHzmNLJvwCPWdFh//2MPAoEPjJww01G4CjgCcATgRcBh7funhoxrZPc5cBTgF8CL13nAj/THwGF1R9LW5qewOOLkBoxhZzijL8/tpXe34D4inew484ippDTEcCNwE+Abx3sQv//MAQU1jBcbXU4AocBZwKvBB7WEVRIZd3jdmBf+XBbTCGn5rx53cb83DgEFNY4nI2yPYFTgTOKpJqfMW5vAY7foNl/Ab8Ffld+3lvulEJOimkDkFN+VGFNSd/YXQInrpDT0QfA1P1q9+eOlNqC+r248xNQWPlrmLUHx66Q07p3TDGt4CrgfuDrLUndnRWGea9HQGGtx8lP7U7gUcCHgYeWr3fxm7Z1jvjqF3K6uvXzjnUu9DPLI6CwllfTufUoHo6/CjgX+AVw2gESvGuFnG6aW4fMZzoCCms69kuOHK+thKTi7E64jOdMMcXggRVyum7JUOzb7gQU1u4MbeF/BE5qSer0PaD8EPgjcEmR1X3Ck8AmBBTWJrT8bJdAzHtq7qT2mvX9G+DL5fQOyjG0EwGFtRO+ai+OV1saUT18BYV/tiT17Wop2fHeCSis3pEutsGYwNlI6kl79PKbLVHFRE0PCfRKQGH1inNxjT0C+CRwHPCcPXr38yKpLwH+Rm9xQ2BeHVJY86rHXLJ5IfDacl4PxN1V+4jlVprnUvEysIcERiGgsEbBnCJIrAn1uiKpWAuqfYS0TgG+UkT11RQ9MsnFEVBYiyvpxh06p0gqJniuOn5WvuqdD/x149a9QAI9ElBYPcJM1FTcLTV3U49bkXe8VPz5coawPCQwCwIKaxZlGCWJh7SeS8W0hFVHTEFoRPWfUbIyiAQ2IKCwNoCV9KOxcULzAH3VKpt/KJL6HBDPqjwkMFsCCmu2pdk5sY8Czy47vaxqLB6cx93UZTtHsgEJjERAYY0EesQwbwDeCcTUg+7cqVhdMyQVd1OusjliUQzVDwGF1Q/HObTy8iKqZ7SS+RVwcuu51BVzSNQcJLAtAYW1Lbn5XHd2EVX35ePbgB8AbwT+Pp90zUQC2xNQWNuzm/rKmH0eX/1e3Ukklmz5UDnvmTpJ40ugTwIKq0+a47QV7/WFqC5YEe5jRVS3jpOKUSQwLgGFNS7vXaLFHnwhqjhjb7728cUiKteb2oWw186egMKafYkeTPAi4O3AozvpxnIu8fUvnlV5SGDxBBTWvEscv+GLr3kxS709O/2nZQea2OLKQwLVEFBY8y3164usjiwpxrpT8bUw7qgunW/aZiaB4QgorOHYbttyrJMed1Vv6jTw6RX/bdsYXieBlAQU1rzK9nzg42XtqSazeL/vrcB35pWq2UhgfAIKa3zme0V8D/D+zv/8VJm+4Pro86mTmUxIQGFNCL+EPrS8OrMPiKWJ4/hHEdVnp0/PDCQwHwIKa9paNO/5xRIwccRiebF4XkwKvWHa1IwugfkRUFjT1SSmKcTKCe2t3D8CXDhdSkaWwLwJKKxp6vNm4BOd0G8pW2pNk5FRJZCAgMIav0gxj+odrbCxblWsCOoOyePXwojJCCiscQsW7wHGFlohqOaZVfzZ51Xj1sFoSQkorPEK9zTgmhJuf1k//Vzg/vFSMJIEchNQWOPV77vAc0u47wHPGy+0kSSwDAIKa5w6fqAIKjaFiOPpwLXjhDaKBJZDQGENX8v2V8EfAXGn9e7hwxpBAssjoLCGr6lfBYdnbIRKCCisYQv9GSDusE4rYc5oPXgfNrKtS2CBBBTWsEW9GHhv2az0qrKW1bARbV0CCyagsIYrbiOriHA1cOZwoWxZAnUQUFjD1bktrPcB8XcPCUhgBwIKawd4B7lUYQ3H1pYrJaCwhiu8whqOrS1XSkBhDVd4hTUcW1uulIDCGq7wbWF9A3jZcKFsWQJ1EFBYw9X5fCDWvToduKKzr+BwUW1ZAgsmoLCGK+5xwC2t5o8Hbh0unC1LYPkEFNawNY5F+WJjiduBm4GzywYTw0a1dQkslIDCGrawsZ/gCa0VRq8DzisTSYeNbOsSWCABhTV8UWNpmXe1wtxXpBUbUHhIQAIbEFBYG8Da4aOxDHK8CH1Yq40PuszMDkS9tEoCCmu8ssdKDSGtU0vIWHbmT2V9d5dJHq8ORkpMQGGNW7wjgUvLXoTxAD6O2DzVjSjGrYPRkhJQWNMUzq2+puFu1OQEFNZ0BXQz1enYGzkpAYU1beFWbVd/efktopNMp62N0WdIQGFNX5STgZjicFZJJWbHx6z4eJ3nMuBrzpCfvkhmMA8CCmsedTi0SCt+W/iaFSmFvO4A3qa85lEws5iGgMKahvteUWNm/CvK6zzdz/waeLJ3Xg+u3Brr5MfhSq7zGr+DZ6OwBke8VYB4cfqclrwaWXUbq+Vr4ynAC4B9ZUPaZgdthbXV8Mp7kcKaf+1CXpcAx+5x59X0YEnyir6GoJoznvOtkrbCmv/47TVDhdUrzsEb69557RUw5HU38AXgRuCmsmLE4AnuECDumhpBPWuNdhy7a0Ba2kcset6KHkxedwFHt7oXfw9xhcDiPKK8GtQXgQeATcdTvK707yKqow6QSMj3SuDw1koX7kLUV+UStbPpAEvUtapSDXnFw/p47hXrb8UyNs07i1lB/LhIKu4Wv5+1E+bdLwGF1S/PObQW8roAiPcWTyrniZ27rTuBY+aQbOvZ1A1FUHEnFWdM4/CQwP8RUFj1DIj4DVuIq5HYgb6CjUnltiKo/WMGNVZOAgorZ93MWgJVElBYVZbdTksgJwGFlbNuZi2BKgkorCrLbqclkJOAwspZN7OWQJUEFFaVZbfTEshJQGHlrJtZS6BKAgqryrLbaQnkJKCwctbNrCVQJQGFVWXZ7bQEchJQWDnrZtYSqJKAwqqy7HZaAjkJKKycdTNrCVRJQGFVWXY7LYGcBBRWzrqZtQSqJKCwqiy7nZZATgIKK2fdzFoCVRJQWFWW3U5LICcBhZWzbmYtgSoJKKwqy26nJZCTgMLKWTezlkCVBBRWlWW30xLISUBh5aybWUugSgIKq8qy22kJ5CSgsHLWzawlUCUBhVVl2e20BHISUFg562bWEqiSgMKqsux2WgI5CSisnHUzawlUSUBhVVl2Oy2BnAQUVs66mbUEqiTwX7MLLKYWb1pcAAAAAElFTkSuQmCC
                number: 111
                boxNumber: 111
        Credentials:
            type: object
            properties:
                login:
                    type: string
                    description: User name or e-mail
                password:
                    type: string
                    description: User's password
            required:
                - login
                - password
            example:
                login: test
                password: test
    responses:
        UnauthorizedError:
            description: Access token is missing or invalid
