openapi: 3.0.0
servers: 
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Concentra_Dev/BVCI/1.0.0
info:
  description: API for Trust Business
  version: "1.0.0"
  title: Concentra BVCI API
  contact:
    email: lawrence.lee@concentra.ca
tags:
  - name: public
    description: Operations available to external parties
  - name: private
    description: Operations available for internal use
paths:
  /transfers:
    post:
      tags:
        - public
      summary: Initiate a fund transfer into the escrow account
      operationId: fundTransfer
      description: Initiate a fund transfer from or to the escrow account
      responses:
        '201':
          description: Tranfer accepted. Return the screening ID.
        '400':
          description: Invalid request.
        '409':
          description: A transfer with the same reference number already exists.
        '500':
          description: Server error.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
        description: The information required for the transfer request
    get:
      tags:
        - public
      summary: Get a list of transfers
      operationId: getTransactions
      description: Initiate a fund transfer from or to the escrow account
      parameters:
        - in: query
          name: referenceNum
          description: Original reference number generated by BVCI.
          required: false
          schema:
            type: string
            example: '201908081918512122'
        - in: query
          name: status
          description: Status of the transfer.
          required: false
          schema:
            type: string
            example: 'Completed'
        - in: query
          name: startDate
          description: The oldest transfer request date to include in the result.
          required: false
          schema:
            type: string
            format: date-time
            example: '2020-01-01'
        - in: query
          name: endDate
          description: The latest transfer request date to include in the result.
          required: false
          schema:
            type: string
            format: date-time
            example: '2020-01-31'
        - in: query
          name: limit
          description: Number of records returned. Maximum is 1000.
          required: false
          schema:
            type: number
            example: 50
      responses:
        '200':
          description: Transactions found.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransferDetails'
        '204':
          description: No result for the specified criteria.
        '400':
          description: Invalid request.
        '500':
          description: Server error.
  /transfers/screenings/{id}:
    put:
      tags:
        - private
      summary: Updating the transfer status
      operationId: updateTransferStatusReview
      description: A callback API for update the screening status of the transfer.
      parameters:
        - in: path
          name: id
          description: Screening ID
          required: true
          schema:
            type: number
            example: 1
      responses:
        '200':
          description: Transfer status updated
        '204':
          description: No result for the specified criteria.
        '400':
          description: Invalid request.
        '500':
          description: Server error.
      requestBody:
        content:
          application/json:
            schema:
             $ref: '#/components/schemas/ScreeningStatus'
        description: The latest transfer status
components:
  schemas:
    Client:
      required:
        - clientType
        - clientNum
        - firstName
        - lastName
        - dateOfBirth
        - address
        - city
        - province
        - postalCode
        - country
      properties:
        clientType:
          type: string
          example: 'Individual'
        clientNum:
          type: string
          example: '2470008'
        firstName:
          type: string
          example: 'Joe'
        lastName:
          type: string
          example: 'Doe'
        dateOfBirth:
          type: string
          format: date-time
          example: '1999-12-31'
        address:
          type: string
          example: 376 Highway 7 east unit 1005
        city:
          type: string
          example: Richmond Hill
        province:
          type: string
          example: 'ON'
        postalCode:
          type: string
          example: L4B 0C7
        country:
          type: string
          example: CA
    TransferRequest:
      type: object
      required:
        - transferType
        - referenceNum
        - routeNum
        - transitNum
        - accountNum
        - amount
        - currency
      properties:
        transferType:
          type: string
          example: contribution
        referenceNum:
          type: string
          example: '201908081918512122'
        routeNum:
          type: string
          example: '853'
        transitNum:
          type: string
          example: '64378'
        accountNum:
          type: string
          example: '12345'
        swiftCode:
          type: string
          example: TCACCAT1
        bankName:
          type: string
          example: Concentra Bank
        amount:
          type: number
          example: 100
        currency:
          type: string
          example: CAD
        client:
          $ref: '#/components/schemas/Client'
    TransferDetails:
      type: object
      required:
        - transferType
        - referenceNum
        - amount
        - currency
        - status
        - statusUpdatedOn
        - requestedOn
      properties:
        transferType:
          type: string
          example: contribution
        referenceNum:
          type: string
          example: '201908081918512122'
        amount:
          type: number
          example: 100
        currency:
          type: string
          example: CAD
        status:
          type: string
          example: "AFT in process"
        statusUpdatedOn:
          type: string
          format: date-time
          example: '2020-02-14T09:12:33.001Z'
        requestedOn:
          type: string
          format: date-time
          example: '2020-02-14T09:12:33.001Z'
        completedOn:
          type: string
          format: date-time
          example: '2020-02-16T10:15:28.006Z'
    ScreeningStatus:
      required:
        - status
        - statusDate
      properties:
        status:
          type: string
          example: 'Accepted'
        statusDate:
          type: string
          format: date-time
          example: '2020-02-13T10:15:28.006Z'
        reviewer:
          type: string
          example: 'John Smith'
        message:
          type: string
          example: 'Manually verified the client is okay.'
