openapi: 3.0.1
info:
  version: "0.1"
  title: Based on "Basic Auth Example"
  description: >
    An example for how to use Auth with Swagger.
host: basic-auth-server.herokuapp.com
schemes:
  - http
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /:
    get:
      security:
        - Bearer: []
      responses:
        "200":
          description: "Will send `Authenticated`"
        "403":
          description: "You do not have necessary permissions for the resource"
