openapi: 3.0.0
info:
  description: ""
  version: "1.0.0"
  title: "EZfix recognize"
# host: "ezfix.com"
# basePath: "/api"
tags:
- name: "receipts"
- name: "results"
- name: "manufacturers"
- name: "tyres"
schemes:
- "https"
paths:
  /receipts:
    get:
      tags:
      - "receipts"
      summary: "Get list of receipts"
      description: ""
      operationId: "receipts.list"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/ReceiptsResponse"
  /receipts/{id}:
    get:
      tags:
      - "receipts"
      summary: "Get receipt by id"
      description: ""
      operationId: "receipts.get"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Id of receipt"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/ReceiptResponse"
        400:
          description: "Invalid Id"
        404:
          description: "Receipt not found"
  /results:
    post:
      tags:
      - "results"
      summary: "Create a recognition result based on receipt"
      description: ""
      operationId: "results.add"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: body
        name: result
        description: "Recognition result"
        schema:
          $ref: '#/definitions/Result'
      responses:
        201:
          description: "Successfully added result"
        400:
          description: "Invalid result"     
  /manufacturers:
    get:
      tags:
      - "manufacturers"
      summary: "Get dictionary of manufacturers"
      description: ""
      operationId: "manufacturers.list"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/ManufacturersResponse"
  /manufacturers/{id}/tyres:
    get:
      tags:
      - "manufacturers"
      - "tyres"
      summary: "Get dictionary of tyre models by manufacturer"
      description: ""
      operationId: "manufacturers.tyres.list"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Id of manufacturer"
        required: true
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/TyresResponse"
    post:
      tags:
      - "manufacturers"
      - "tyres"
      summary: "Add tyre model by manufacturer"
      description: ""
      operationId: "manufacturers.tyres.add"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Id of manufacturer"
        required: true
        type: "string"
      - in: body
        name: tyre
        description: "Tyre"
        schema:
          $ref: '#/definitions/Tyre'
      responses:
        201:
          description: "Successfully added tyre"
        400:
          description: "Invalid tyre data" 
definitions:
  Receipt:
    type: "object"
    required:
    - "id"
    - "status"
    properties:
      certificate_id: 
        type: integer
      itemsraw:
        type: object
        properties:
          name:
            type: string
          quantity:
            type: integer
          price:
            type: integer
          sum:
            type: integer
  ReceiptResponse:
    type: object
    required:
      - receipt
      - status
    properties:
      status:
        type: "string"
        example: "success"
      receipt:
        $ref: "#/definitions/Receipt"
  ReceiptsResponse:
    type: "object"
    required: 
      - receipts
      - status
    properties:
      status:
        type: "string"
        example: "success"
      receipts: 
        type: "array"
        items:
          $ref: "#/definitions/Receipt"
  Result: 
    type: "object"
    required:
      - receipt_id
      - manufacturer_id
      - width
      - ratio
      - diameter
    properties:
      receipt_id:
        type: "string"
        example: "1234567890"
      manufacturer_id: 
        type: "string"
        example: "MANU123"
      tire_id: 
        type: "string"
        example: "A123"
      tire_name:
        type: "string"
        example: "new_tyre_name"
      width: 
        type: "string"
        example: "205"
      ratio: 
        type: "string"
        example: "55"
      diameter:
        type: "string"
        example: "16"
  Manufacturer: 
    type: "object"
    required:
    - "id"
    - "name"
    properties:
      id:
        type: "string"
        example: "MANU123"
      name:
        type: "string"
        example: "Toyo"
  ManufacturersResponse:
    type: "object"
    required: 
      - manufacturers
      - status
    properties:
      status:
        type: "string"
        example: "success"
      manufacturers: 
        type: "array"
        items:
          $ref: "#/definitions/Manufacturer"
  Tyre:
    type: "object"
    required:
    - "id"
    - "name"
    properties:
      id:
        type: "string"
        example: "A123"
      name:
        type: "string"
        example: "Sigura Stud"
  TyresResponse:
    type: "object"
    required: 
      - manufacturer
      - models
      - status
    properties:
      status:
        type: "string"
        example: "success"
      manufacturer:
        $ref: "#/definitions/Manufacturer"
      models: 
        type: "array"
        items:
          $ref: "#/definitions/Tyre"
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /smolnikov/EZfix_receipts/1.0.0
