openapi: 3.0.0
info:
  version: "1.0.1"
  title: Google API
  description: >-
    endpoints of `Google API` are private and protected by an Account service Authentication 
    `contact the developer` or refer to the [Documentation](https://docs.google.com/document/d/1CWxXTqgFkXggkeDypYyIx_po7kfxrHSygNHuR2JDOAM/edit?usp=sharing)
  contact:
    email: gianni.prata@soitec.com
paths:
  /fileCreate:
    post:
      tags:
        - Google Drive API
      summary: Create a file (or folder)
      parameters:
        - in: header
          name: X-Soitec-Message
          schema:
            type: string
            example: X-Soitec-Message
          description: store in keepass
          required: true
        - in: header
          name: X-Soitec-Hash
          schema:
            type: string
            example: X-Soitec-Hash
          description: store in keepass
          required: true
          
      requestBody:
        description: Parameters to pass in body request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/folderCreate'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
        '404': 
          description: Not found
        '500':
          description: Internal error
      security:
        - ApiKeyAuth: []

  
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/SOITEC/GAPI/1.0.0
  - url: 'https://us-central1-gapi-b17f8.cloudfunctions.net/googleapi'
components:
  schemas:
    folderCreate:
       type: object
       required:
        - requests
       properties:
        requests:
          type: object
          required:
            - parents
            - name
            - mimeType
          properties:
            parents:
              type: array
              items:
               type: string
               example: 1FhWjYi4Qaè6PFvqok0wyaZY0pStluKxkf
            name:
              type: string
              example: file Or Folder name
            mimeType:
              type: string
              example: application/vnd.google-apps.folder
  responses:
    NotFound:
      description: The specified resource was not found
    NoContent:
      description: No content to return
    BadRequest:
      description: Bad request
    Unauthorized:
      description: Unauthorized
    InternalError:
      description: Internal Server Error
