openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Weva API'
  description: 'api'

# Added by API Auto Mocking Plugin
servers:

  - description: SwaggerHub API Auto Mocking
    url: https://api.weva.com/v1
    
paths:
  /users/:
    get:
      summary: Returns a user by ID
      responses:
        '200':
          description: OK
