openapi: 3.0.0
info:
  description: API documentation for integration
  version: "1.0.0-oas3"
  title: Techainer JP api
  contact:
    email: admin@techainer.com
tags:
  - name: JP general document
    description: General japanese documents
  - name: JP driver licence
    description: Japanese driver licence
paths:
  /poc-jp-dl/call/predict:
    post:
      tags:
        - JP driver licence
      summary: Japanese driver licence
      operationId: jpDlExtraction
      description: Information extraction from Japanese driver licence
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Result data
          # content:
          #   application/json:
          #     example: 
                
        '422':
          description: Invalid input
        '500':
          description: Internal Server Error
  /ocr/call/predict:
    post:
      tags:
        - JP general document
      summary: Japanese general document extraction
      operationId: jpGeneralExtraction
      description: Information extraction from Japanese document
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                input:
                  type: string
                  format: binary
                kv_model:
                  type: string
                  enum: [""]
                ocr_model:
                  type: string
                  enum: ["jp"]
                linecut_model:
                  type: string
                  enum: ["craft_tiny"]
                alignment:
                  type: boolean
                  enum: [True, False]
      responses:
        '200':
          description: Result data
        '422':
          description: Invalid input
        '500':
          description: Internal Server Error
servers:
  - description: API endpoint
    url: 'http://app.gotai.ml'
