openapi: 3.0.0
info:
  title: 'Dyzio Campaign Integration API'
  version: "1.0.1"
  description: API for creation of campaigns and retrieval of campaign data
  contact:
    name: API Contact
    email: support@dyzio.co
    url: 'http://dyzio.co'
paths:
  /campaigns:
    post:
      tags:
        - campaigns
      description: Create a new instance of campaigns
      responses:
        '201':
          description: campaigns create response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/campaigns'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      requestBody:
        $ref: '#/components/requestBodies/Body'
  '/campaigns/{id}':
    get:
      tags:
        - campaigns
      description: Get a specific instance of campaigns
      parameters:
        - name: id
          in: path
          description: id of specific instance to lookup
          required: true
          schema:
            type: string
      responses:
        '200':
          description: campaigns find response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/campaigns'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    patch:
      tags:
        - campaigns
      description: Update an instance of campaigns
      parameters:
        - name: id
          in: path
          description: id of specific instance to lookup
          required: true
          schema:
            type: string
      responses:
        '200':
          description: campaigns update response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/campaigns'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      requestBody:
        $ref: '#/components/requestBodies/Body'
security:
  - apiKey: []
    appId:  []
servers:
  - url: 'https://virtserver.swaggerhub.com/dyzio/dyzio-public-api/1.0.0'
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-KEY
    appId:
      type: apiKey
      in: header
      name: X-APP-ID
  requestBodies:
    Body:
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: '#/components/schemas/campaigns'
      description: New or partial resource
      required: true
  schemas:
    influencers:
      type: object
      description: The influencer. Must have at least one social handle!
      properties:
        id:
          description: The influencer UUID in the dyzio system (Generated by dyzio)
          type: string
        name:
          description: >-
            The influencer's real name (will be used in email correspondence
            etc)
          type: string
          example: Zoe Sugg
        email:
          description: The influencer's email. Do NOT use agent emails.
          type: string
          example: 'zoe@zoella.com'
        instagram:
          description: The influencer's instagram handle. Do not include @ sign.
          type: string
          example: zoella
        youtubeChannelId:
          description: The influencer's youtube channel ID. Do not use their username.
          type: string
          example: UCWRV5AVOlKJR1Flvgt310Cw
        twitter:
          description: The influencer's twitter handle. Do not include @ sign.
          type: string
          example: zoella
        facebook:
          description: The influencer's facebook handle. Do not include @ sign.
          type: string
          example: zoella
        platformId:
          description: The influencer's ID from YOUR system. Used to avoid duplicates.
          type: string
          example: xyz-123
      required:
        - name
        - email
        - instagram
        - platformId
    campaigns:
      description: The main interface with the API
      type: object
      properties:
        id:
          description: The campaign UUID in the dyzio system (Generated by dyzio)
          type: string
        name:
          type: string
          example: Nike Summer Running
        currency:
          $ref: '#/components/schemas/currency'
        budget:
          type: number
          example: 10000
        liveDate:
          description: >-
            The date the campaign starts. The system will not add posts from
            before this date.
          type: string
          format: date
          example: '2020-01-01'
        endDate:
          description: >-
            The date the campaign starts. The system will not add posts from
            after this date.
          type: string
          format: date
          example: '2020-02-29'
        hashtags:
          description: >-
            The hashtags or @mentions to search for. The sytem uses basic
            regular expressions to search post captions.
          type: string
          example: '#nike,#summer,@nikeuk'
        loginURL:
          description: >-
            The login URL you should render in your app to open a logged in dyzio window. (expires after a few hours)
          type: string
        influencers:
          description: Array of influencers to add to the campaign.
          type: array
          items:
            $ref: '#/components/schemas/influencers'
          example: [
            { name: 'Zoe Sugg', instagram: 'zoella', email: 'zoe@zoella.com', platformId: 'xyz-123' },
            { name: 'Lily Pebbles', instagram: 'lilypebbles', email: 'lily@lilypebbles.com', platformId: 'wef-345' }
          ]
      required:
        - name
        - liveDate
        - endDate
        - hashtags
    currency:
      type: string
      enum:
        - GBP
        - USD
    error:
      type: object
      required:
        - jsonapi
        - meta
        - links
        - errors
      properties:
        jsonapi:
          type: object
          required:
            - version
          properties:
            version:
              type: string
        meta:
          type: object
        links:
          type: object
          properties:
            self:
              type: string
        errors:
          type: array
          items:
            type: object
            required:
              - status
              - code
              - title
              - detail
            properties:
              status:
                type: string
              code:
                type: string
              title:
                type: string
              detail:
                type: object
