openapi: 3.0.2
info:
    title: G-Plans Grocery List
    version: "1.0.0"
paths:
    /grocery-list/items:
        summary: Get list
        description: ''
        get:
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Item'
                    description: Successful response - returns an array of `Item` entities.
            operationId: getitems
            summary: List all items (including extra food)
            description: Gets a list of all `Item` entities.
    '/grocery-list/items/{foodName}/uncheck':
        post:
            parameters:
                -
                    name: foodName
                    description: Food name.
                    schema:
                        type: string
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Item'
            summary: Uncheck a list item
    '/grocery-list/items/{foodName}/check':
        summary: Path used to manage a single Item.
        description: >-
            The REST endpoint/path used to get, update, and delete single instances of an `Item`.  This path
            contains `GET`, `PUT`, and `DELETE` operations used to perform the get, update, and delete tasks,
            respectively.
        post:
            requestBody: {}
            parameters:
                -
                    name: foodName
                    description: Food name.
                    schema:
                        type: string
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Item'
            summary: Check a list item
        parameters:
            -
                name: foodName
                description: Food name.
                schema:
                    type: string
                in: path
                required: true
    /grocery-list/items/extra/:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ItemWriteOnly'
                required: true
            responses:
                '201':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Item'
                    description: List item for extra food
            summary: Create a list item for extra food
    '/grocery-list/items/extra/{foodName}':
        put:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ItemWriteOnly'
                required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Item'
            summary: Update a list item for extra food
        delete:
            parameters:
                -
                    name: foodName
                    description: Food name.
                    in: path
                    required: true
            responses:
                '204': {}
            summary: Delete a list item for extra food
        patch:
            summary: Update a list item for extra food partially
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ItemWriteOnly'
                required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Item'
            parameters:
                -
                    name: foodName
                    description: Food name.
                    schema:
                        type: string
                    in: path
                    required: true
components:
    schemas:
        Item:
            title: Root Type for Item
            description: Grocery list item
            required:
                - name
                - amount
                - calories
                - carbohydrates
                - checked
                - fats
                - is_extra
                - proteins
                - unit
                - category
            type: object
            properties:
                name:
                    description: Food name.
                    type: string
                category:
                    enum:
                        - meat
                        - bread
                        - vegetables
                        - extra
                    type: string
                    readOnly: true
                amount:
                    description: Food amount
                    type: number
                unit:
                    description: ''
                    type: string
                calories:
                    description: For whole amount
                    type: number
                proteins:
                    description: For whole amount
                    type: number
                carbohydrates:
                    description: For whole amount
                    type: number
                fats:
                    description: For whole amount
                    type: number
                checked:
                    description: ''
                    type: boolean
                checkin:
                    description: Checkin ID
                    type: number
                    readOnly: true
                is_extra:
                    description: ''
                    type: boolean
                    readOnly: true
            example:
                name: beef
                category: meat
                amount: 8.03
                unit: some text
                calories: 19.7
                proteins: 62.5
                carbohydrates: 19.43
                fats: 24.08
                checked: true
                checkin: 69.91
                is_extra: true
        ItemWriteOnly:
            title: Item to write
            description: Grocery list item
            required:
                - name
                - amount
                - calories
                - carbohydrates
                - fats
                - proteins
                - unit
                - checkin
            type: object
            properties:
                name:
                    description: Food name.
                    type: string
                amount:
                    description: Food amount
                    type: number
                unit:
                    description: ''
                    type: string
                calories:
                    description: For whole amount
                    type: number
                proteins:
                    description: For whole amount
                    type: number
                carbohydrates:
                    description: For whole amount
                    type: number
                fats:
                    description: For whole amount
                    type: number
                checked:
                    description: ''
                    type: boolean
                checkin:
                    description: Checkin ID
                    type: number
                    readOnly: true
                is_extra:
                    description: ''
                    type: boolean
                    readOnly: true
            example:
                name: beef extra
                amount: 8.03
                unit: g
                calories: 19.7
                proteins: 62.5
                carbohydrates: 19.43
                fats: 24.08
                checkin: 69.91
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/pauk-slon/grocery-list/1
