openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/glee_mes/WEB-COMM-BUILDER/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/glee314/WEB-COMM-BUILDER/1.0.0
info:
  description: Web Commerce Builder Merchant Onboarding API
  version: "1.0.0"
  title: Web Commerce Builder Merchant Onboarding API
  contact:
    email: glee@merchante-solutions.com

paths:

  /webcommapi/v1/onboard/stores:
    get:
      responses:
        200:
          description: Merchant OnBoard API - Return all Merchant Store
          content:
            application/json:
              schema:
                type: object
                properties:
                  stores: 
                    type: array
                    items: 
                      type: object
                      properties: 
                        merchantId:
                          type: number
                          description: MES Merchant Id
                          example: 1111111111111
                        email:
                          type: string
                          description: Store Owner Email 
                          example: glee@merchante-solutions.com
                        ownerName:
                          type: string
                          description: Merchant Owner Name
                          example: John Doe
                        storeId:
                          type: number
                          description: store Id returned from ECWID API
                          example: 12345
                        profileId:
                          type: string
                          description: Profile Id stored in App Storage as profile:value pair.
                          example:  "1111111111111000001"  
                        plan: 
                          type: string
                          description: plan in the request
                          example: basic_plan
                        storeStatus:
                          type: string
                          description: Store Status - Active, Deleted
                          example: Active
                     
                  status:
                    type: string
                    description: API Status
                    example: Success
                  errorMessage:
                    type: string
                    description: API Status Error Message
                    example: No Error
        
  /webcommapi/v1/onboard/{merchantId}:
     get:
      summary: Merchant OnBoard API - Get Merchant Store Info
      parameters:
        - in: path
          name: merchantId
          schema:
            type: number
          required: true
          description: Merchant Id to Deactivate
      responses:
        200:
          description: Merchant OnBoard API Response - Deactivate
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    description: Store Owner Email 
                    example: glee@merchante-solutions.com
                  ownerName:
                    type: string
                    description: Merchant Owner Name
                    example: John Doe
                  storeId:
                    type: number
                    description: store Id returned from ECWID API
                    example: 12345
                  profileId:
                    type: string
                    description: Profile Id stored in App Storage as profile:value pair.
                    example:  "1111111111111000001"  
                  plan: 
                    type: string
                    description: plan in the request
                    example: basic_plan
                  storeStatus:
                    type: string
                    description: Store Status - Active, Deleted
                    example: Active  
                  status:
                    type: string
                    description: API Status
                    example: Success
                  errorMessage:
                    type: string
                    description: API Status Error Message
                    example: No Error
        400:
          description: bad input parameter
          
          
  /webcommapi/v1/onboard/{modifiedBy}/{merchantId}:       
     delete:
      summary: Merchant OnBoard API - Delete Merchant Store
      parameters:
        - in: path
          name: modifiedBy
          schema:
            type: string
          required: true
          description: User Id or App id that initiates the request
        - in: path
          name: merchantId
          schema:
            type: number
          required: true
          description: Merchant Id to Delete
      responses:
        200:
          description: Merchant OnBoard API Response - Delete
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    description: Store Owner Email 
                    example: glee@merchante-solutions.com
                  ownerName:
                    type: string
                    description: Merchant Owner Name
                    example: John Doe
                  storeId:
                    type: number
                    description: store Id returned from ECWID API
                    example: 12345
                  profileId:
                    type: string
                    description: Profile Id stored in App Storage as profile:value pair.
                    example:  "1111111111111000001"  
                  status:
                    type: string
                    description: API Status
                    example: Success
                  errorMessage:
                    type: string
                    description: API Status Error Message
                    example: No Error
        400:
          description: bad input parameter
            
  /webcommapi/v1/onboard:
    post:
      summary: Merchant OnBoard API - Create Merchant Store
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchantId:
                  type: number
                  description: MES Merchant Id
                  example: 1111111111111
                email:
                  type: string
                  description: Unique Id Used to Identify the Request
                  example: glee@merchante-solutions.com
                ownerName:
                  type: string
                  description: Merchant Owner name
                  example: John Doe
                plan:
                  type: string
                  description: plan
                  example: basic_plan
                modifiedBy:
                  type: string
                  description: User Id or app Id that initiates the request.
                  example:  salesforceuser
      responses:
        200:
          description: Merchant OnBoard API Response - Create
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    description: Store Owner Email 
                    example: glee@merchante-solutions.com
                  ownerName:
                    type: string
                    description: Merchant Owner Name
                    example: John Doe
                  storeId:
                    type: number
                    description: store Id returned from ECWID API
                    example: 12345
                  profileId:
                    type: string
                    description: Profile Id stored in App Storage as profile:value pair.
                    example:  "1111111111111000001"
                  plan: 
                    type: string
                    description: plan in the request
                    example: basic_plan
                  status:
                    type: string
                    description: API Status
                    example: Success
                  errorMessage:
                    type: string
                    description: API Status Error Message
                    example: No Error
        400:
          description: bad input parameter
      
    put:
      summary: Merchant OnBoard API - Update Merchant Store
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchantId:
                  type: number
                  description: MES Merchant Id
                  example: 1111111111111
                plan:
                  type: string
                  description: plan
                  example: business_plan
                modifiedBy:
                  type: string
                  description: User Id or app Id that initiates the request.
                  example:  salesforceuser
      responses:
        200:
          description: Merchant OnBoard API Response - Update
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    description: Store Owner Email 
                    example: glee@merchante-solutions.com
                  ownerName:
                    type: string
                    description: Merchant Owner Name
                    example: John Doe
                  storeId:
                    type: number
                    description: store Id returned from ECWID API
                    example: 12345
                  profileId:
                    type: string
                    description: Profile Id stored in App Storage as profile:value pair.
                    example:  "1111111111111000001"  
                  plan: 
                    type: string
                    description: plan in the request
                    example: basic_plan
                  status:
                    type: string
                    description: API Status
                    example: Success
                  errorMessage:
                    type: string
                    description: API Status Error Message
                    example: No Error
        400:
          description: bad input parameter
