openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/scrb04138/BananaFunction/1.0.0
info:
  description: This is a simple API
  version: "1.0.0"
  title: Simple Inventory API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /inventory:
    get:
      tags:
        - developers
      summary: searches inventory
      operationId: searchInventory
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
    
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/InventoryItem'
        '400':
          description: bad input parameter
    post:
      tags:
        - developers
      summary: Find pet by ID
      description: Returns a single pet
      operationId: getPetById
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/InventoryItem'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
components:
 schemas:
    InventoryItem:
      type: object
      required:
        - urlString
        - changeA
        - changeB
        - changeC
        - changeD
        - changeE
        
      properties:
        urlString: 
          type: string
          example: "https://www.iconfont.cn/?spm=a313x.7781069.1998910419.d4d0a486a"
        changeA: 
          type: string
          example: "typety"
        changeB: 
          type: string
          example: "test"
        changeC: 
          type: string
          example: "tespe"
        changeD: 
          type: string
          example: "dsype"
        changeE: 
          type: string
          example: "dsaye"
