openapi: 3.0.0
info:
  version: "V1.0"
  title: 'Datenkraft Test'
  description: 'Erster Test für Beispiel'
  contact:
    name: Florian Martinetz
    email: dev.florianmartinetz@gmail.com
servers: 
  - url: 192.168.100.10:8081
    description: Server Address with IP
  - url: localhost:81
    description: Server Address locally 
  - url: https://{environment}.example.com
    variables:
      environment:
        default: api    # Production server
        enum:
          - api         # Production server
          - api.dev     # Development server
          - api.staging # Staging server
components:
  
  schemas:
    #Customer: 
    #  description: Datastructure Customer
    #  type: object
    #  properties:
    #    id: 
    #      type: integer
    #    name:
    #      type: string
    #    address: 
    #      type: object  
    #      properties:
    #        street: 
    #          type: string
    #        city: 
    #          type: string 
    #        postal_code: 
    #          type: integer
    #        country: 
    #          type: string 
    #          default: "Austria"
    Order:
      description: Datastructure Customer
      type: object
      properties:
        id: 
          type: integer
        costumer_id: 
          type: integer
        shop_id: 
          description: Sent by this shop
          type: integer
        created: 
          type: string
          format: date
        products_id: 
          description: ID's of the products
          type: array 
          items: 
            type: integer
    #Product: 
    #  description: Datastructure Product 
    #  type: object 
    #  properties:
    #    id: 
    #      type: integer
    #    shop_id:
    #      description: In which shop is the product stored
    #      type: integer
    #    name: 
    #      type: string 
    #      description: Name of the Product
    ArrayOfOrders:
      description: Datastructure for an array of orders
      type: array
      items:
         $ref: '#/components/schemas/Order'
tags: 
  - name: order
    description: order operations
  - name: shop
    description: shop infos 
  - name: customer 
    description: Everything about the costumer
paths:
  /order:
    get: 
      tags:
        - order
      summary: Get all orders from all shops
      description: >
        A detailed description of the operation.
        Use markdown for rich text representation,
        such as **bold**, *italic*, and [links](https://swagger.io).
      responses:
        '200':
          description: List all orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfOrders'
