openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/tojawojtek/Mirrors/1.0.0
info:
  description: This is a simple API
  version: "1.0.1"
  title: Simple Inventory API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:

  - name: face recognition
    description: face
  - name: customers
    description: api for customer data
  - name: data
    description: required data for mobile app
paths:
  /face:
    post:
      tags:
      - face recognition
      parameters:
      - in: header
        name: geo-latitude
        required: true
        schema:
          type: string
      - in: header
        name: geo-longitude
        required: true
        schema:
          type: string
      - in: header
        name: shop-department
        required: true
        schema:
          type: string
      - in: header
        name: timestamp
        required: true
        schema:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
      - in: header
        name: shop-id
        required: true
        schema:
          type: string
      - in: header
        name: region
        required: true
        schema:
          type: array
          items:
            type: string
          example: "Mazowieckie,Warszawa"

      requestBody:
        content:
          image/png:
            schema:
              type: string
              format: binary
      responses:
        500:
          description: internal server error
        200:
          description: OK
  /customer/hour:
    get:
      tags:
      - customers
      parameters:
      - in: header
        name: start-date
        required: false
        schema:
          type: string
          format: date
      - in: header
        name: end-date
        required: false
        schema:
          type: string
          format: date
      - in: header
        name: weekday
        schema:
          type: array
          items:
            type: string
      - in: header
        name: min-hour
        required: false
        schema:
          type: number
          format: integer
      - in: header
        name: max-hour
        required: false
        schema:
          type: number
          format: integer
      - in: header
        name: male
        schema:
          type: boolean
      - in: header
        name: female
        schema:
          type: boolean
      - in: header
        name: moods
        schema:
          type: array
          items:
            type: string
      - in: header
        name: minAge
        schema:
          type: number
          format: integer
      - in: header
        name: maxAge
        schema:
          type: number
          format: integer
      - in: header
        name: location
        schema:
          type: string
      responses:
        200:
          description: ok

          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/Line'
                example:
                  - nameLine: Customers by selected time span
                    points:
                      - hour: 13
                        customers: 145
                      - hour: 14
                        customers: 120
                      - hour: 15
                        customers: 200
                  - nameLine: Customers this month
                    points:
                      - hour: 10
                        customers: 100
                      - hour: 12
                        customers: 150
                  - nameLine: Customers on black friday
                    points:
                      - hour: 6
                        customers: 400
                      - hour: 9
                        customers: 300
        500:
          description: internal server error

  /customer/age:
    get:
      tags:
        - customers
      parameters:
      - in: header
        name: start-date
        required: false
        schema:
          type: string
          format: date
      - in: header
        name: end-date
        required: false
        schema:
          type: string
          format: date
      - in: header
        name: weekday
        schema:
          type: array
          items:
            type: string
      - in: header
        name: min-hour
        required: false
        schema:
          type: number
          format: integer
      - in: header
        name: max-hour
        required: false
        schema:
          type: number
          format: integer
      - in: header
        name: male
        schema:
          type: boolean
      - in: header
        name: female
        schema:
          type: boolean
      - in: header
        name: moods
        schema:
          type: array
          items:
            type: string
      - in: header
        name: minAge
        schema:
          type: number
          format: integer
      - in: header
        name: maxAge
        schema:
          type: number
          format: integer
      - in: header
        name: location
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Age'

                example:
                  - ageGroup: "1-15"
                    customers: 250
                  - ageGroup: "16-25"
                    customers: 130
                  - ageGroup: "26-35"
                    customers: 290
                  - ageGroup: "36-45"
                    customers: 100
        500:
          description: internal server error
  /customer/mood:
    get:
      tags:
       - customers
      parameters:
      - in: header
        name: start-date
        required: false
        schema:
          type: string
          format: date
      - in: header
        name: end-date
        required: false
        schema:
          type: string
          format: date
      - in: header
        name: weekday
        schema:
          type: array
          items:
            type: string
      - in: header
        name: min-hour
        required: false
        schema:
          type: number
          format: integer
      - in: header
        name: max-hour
        required: false
        schema:
          type: number
          format: integer
      - in: header
        name: male
        schema:
          type: boolean
      - in: header
        name: female
        schema:
          type: boolean
      - in: header
        name: moods
        schema:
          type: array
          items:
            type: string
      - in: header
        name: minAge
        schema:
          type: number
          format: integer
      - in: header
        name: maxAge
        schema:
          type: number
          format: integer
      - in: header
        name: location
        schema:
          type: string

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mood'

                example:
                  - mood: happiness
                    customers: 130
                  - mood: sadness
                    customers: 200
                  - mood: surprised
                    customers: 100
        500:
          description: internal server error




  /data/locations:
    get:
      tags:
      - data
      parameters:
      - in: header
        name: region
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
           application/json:
            schema:
              type: array
              items:
                type: string
              example: ["Ochota","Bielay","Piaseczno"]
components:
  schemas:
    Line:
      description: data for one line in linechart
      type: object
      required:
        - nameLine
      properties:
        nameLine:
          type: string
        points:
          type: array
          items:
            $ref: '#/components/schemas/HourPoint'

    HourPoint:
      description: each point in line
      type: object
      properties:
        hour:
          type: number
          format: integer
        customers:
          type: number
          format: float
      required:
        - hour
        - customers


    Age:
      type: object
      properties:
        ageGroup:
          type: string
        customers:
          type: number
          format: integer
      required:
        - ageGroup
        - customers
    Mood:
      type: object
      properties:
        mood:
          type: string
        customers:
          type: number
          format: integer
      required:
        - mood
        - customers
