openapi: 3.0.0
info:
  description: |
    Borneo API : interfacing by API between integrated peripherals & http
  version: "1.0.1"
  title: Borneo
tags:
  - name: tpa
    description: Routes regarding the payment automat
  - name: scanneur
    description: Routes regarding scanner
  - name: imprimante
    description: Routes regarding printer
  - name: paiement
    description: Routes regarding payment itself
  - name: impression
    description: Routes regarding printing
  - name: lecture
    description: Routes regarding reading from peripherals
  - name: maintenance
    description: Routes regarding maintenance
paths:
  /v1/tpa/solvency:
    post:
      tags:
        - paiement
        - tpa
      summary: Solvency request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  description: Transaction amount, in cents
                  type: integer
                  example: 200
                currency:
                  description: ISO 4217's currency code
                  type: string
                  default: '978'
                  example: '978'
                mock:
                  description: (optional) Mocks (fakes the answer of) a call , contains the wanted return code (e.g. 200 for succes)
                  type: integer
                  example: 200
              required:
                - amount
      responses:
        '200':
          description: Authorized payment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SolvencyResponse'
        '401':
          description: Refused payment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SolvencyResponse'
        '402':
          description: Cancelled payment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SolvencyResponse'
        '403':
          description: Invalid licence
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error50X'
    delete:
      tags:
        - paiement
        - tpa
      summary: Cancel solvency request
      responses:
        '200':
          description: Cancellation accepted
        '403':
          description: Invalid licence
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error50X'
  /v1/tpa/payment:
    post:
      tags:
        - paiement
        - tpa
      summary: Validation of payment request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  description: Real transaction amount, in cents
                  type: integer
                  example: 200
                currency:
                  description: ISO 4217's currency code
                  type: string
                  default: '978'
                  example: '978'
                mock:
                  description: (optional) Mocks (fakes the answer of) a call , contains the wanted return code (e.g. 200 for succes)
                  type: integer
                  example: 200
              required:
                - amount
      responses:
        '200':
          description: Payment validated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '401':
          description: Payment amount request greater than the solvency request
        '403':
          description: Invalid licence
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error50X'
  /v1/printer/print:
    post:
      tags:
        - impression
        - imprimante
      summary: Printing request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                base64:
                  description: File content (Base64) to print
                  type: string
                  format: byte
                type:
                  description:  >
                       Sent type
                        * 0 => RAW
                        * 1 => PDF
                  type: integer
      responses:
        '200':
          description: Printing request succeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  near_end_paper:
                    type: boolean
                    description: End of paper indicator
                    default: false
        '403':
          description: Invalid licence
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error50X'
  /v1/scanner/read:
    get:
      tags:
        - lecture
        - scanneur
      summary: Scanner reading request
      responses:
        '200':
          description: Reading succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    description: Scanned string
                    type: string
        '403':
          description: Invalid licence
        '404':
          description: No data emitted by scanner
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error50X'
    delete:
      tags:
        - lecture
        - scanneur
      summary: Cancellation of the scan request
      responses:
        '200':
          description: Cancellation succeded
        '403':
          description: Invalid licence
  /v1/tpa/status:
    get:
      tags:
        - maintenance
        - tpa
      summary: State of the banking hardware
      responses:
        '200':
          description: Request succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  cr:
                    description: >
                      Payment hardware status
                        * '0' => Hardware is available for requests
                        * '1' => Hardware already processing a request
                        * '2' => Hardware in maintenance mode
                    type: string
                    enum:
                      - '0'
                      - '1'
                      - '2'
                  carte:
                    description: >
                      Card insertion status
                        * '0' => No card in the reader
                        * '1' => Card in the reader
                    type: string
                    enum:
                      - '0'
                      - '1'
                  etat:
                    description: >
                      State of communications
                        * '0' => No ongoing calls
                        * '1' => Bank collection on-going
                        * '2' => Parameters download on-going
                    type: string
                    enum:
                      - '0'
                      - '1'
                      - '2'
                  periph:
                    description: >
                      Other devices status
                        * '0' => Running OK
                        * '1' => PinPad KO
                        * '2' => Reader KO
                        * '3' => PinPad and Reader KO
                    type: string
                    enum:
                      - '0'
                      - '1'
                      - '2'
                      - '3'
        '403':
          description: Invalid licence
  /v1/printer/status:
    get:
      tags:
        - maintenance
        - imprimante
      summary: Printer status request
      responses:
        '200':
          description: Printer status request succeeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  offline:
                    type: boolean
                    description: Offline printer ?
                    default: false
                  no_paper:
                    type: boolean
                    description: Lacking paper ?
                    default: false
                  near_end_paper:
                    type: boolean
                    description: Next to lack paper ?
                    default: false
                  ticket_out:
                    type: boolean
                    description: Ticket out ?
                    default: false
                  no_cover:
                    type: boolean
                    description: Printer cover opened ?
                    default: false
                  spooling:
                    type: boolean
                    description: Printer currently printing ?
                    default: false
                  over_temp:
                    type: boolean
                    description: Overheating of the printer ?
                    default: false
                  hl_volt:
                    type: boolean
                    description: Power supply problem ?
                    default: false
                  paper_jam:
                    type: boolean
                    description: Paper jam ?
                    default: false
                  cut_error:
                    type: boolean
                    description: Cutting issue ?
                    default: false
                  ram_error:
                    type: boolean
                    description: Enough memory ?
                    default: false
        '403':
          description: Invalid licence
  /v1/activate:
    post:
      tags:
        - maintenance
      summary: Borneo activation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                licence:
                  description: Your activation licence
                  type: integer
      responses:
        '200':
          description: Borneo is activated (open the 443 ports to communicated IPs)
        '404':
          description: Invalid licence
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error50X'
components:
  schemas:
    SolvencyResponse:
      type: object
      properties:
        receipt:
          description: Ticket sent back by bank automaton (can be void if no ticket sent by automaton)
          type: string
    PaymentResponse:
      type: object
      properties:
        receipt:
          description: Ticket sent back by bank automaton (can be void if no ticket sent by automaton)
          type: string
    Error50X:
      type: object
      properties:
        code:
          type: string
          description: Error code
        msg:
          type: string
          description: Error message
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/CISS9/Borneo/1.0.1
