openapi: 3.0.0 #openapi version
info: #info section - contact info, license and other details
  version: '1.0.0'
  title: 'Sample API'
  description: 'This is a sample API'
servers:
  - url: https://api.example.com/v1
  
  
paths: #define api operations
  /users/{userId}:
    get:
      summary: Returns a user by ID.
      parameters: 
        - name: userId #specifies name as the one in the path
          in: path #name specified in path as e.g /users/15
          required: true #it is required
          description: The ID of the user to return
          schema: #value type
            type: integer
      responses:
        '200':
          description: successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: integer
                  name:
                    type: string
      responses:
        '400':
          description: The specified user ID is invalid (e.g. not a number)
        '404':
          description: A user with the specified ID was not found
