openapi: 3.0.0
info:
  description: CoreX API
  version: 1.0.0
  title: CoreX main APIs
  contact:
    email: devops@prophius.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: /api/v1/
tags:
  - name: CoreX
    description: CoreX APIs
paths:
  /authenticate/login:
    post:
      tags:
        - Generate access token for subsequent requests
      summary: Returns token to be used for subsequent airtime and data requests
      requestBody:
        description: Authentication Request Post Object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/authenticationRequestPostBody'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/components/schemas/authenticationRequestPostBody'
  '/airtime/{msisdn}':
    parameters:
      - name: msisdn
        in: path
        required: true
        description: MSISDN for which airtime is to be bought
        type: string
    get:
      tags:
        - Get Specific MSISDN airtime information
      summary: Returns MSISDN airtime information for provided MSISDN
      parameters:
        - in: path
          name: msisdn
          required: true
          description: MSISDN for which airtime information is being requested
          schema:
            $ref: '#/components/schemas/id'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/components/schemas/airtimeRequest'
        '400':
          description: invalid MSISDN
          schema:
            $ref: '#/components/schemas/airtimeRequest'
    post:
      tags:
        - Provide airtime value for MSISDN
      summary: Returns status of airtime purchase request
      parameters:
        - in: path
          name: msisdn
          required: true
          description: MSISDN for which airtime is being purchased
          schema:
            $ref: '#/components/schemas/id'
      requestBody:
        description: Airtime Purchase Request Post Object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/airtimeRequestPostBody'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/components/schemas/airtimeRequestPostBody'
  '/data/{msisdn}':
    parameters:
      - name: msisdn
        in: path
        required: true
        description: MSISDN for which data is to be bought
        type: string
    get:
      tags:
        - Get Specific MSISDN data information
      summary: Returns MSISDN data information for provided MSISDN
      parameters:
        - in: path
          name: msisdn
          required: true
          description: MSISDN for which data information is requested
          schema:
            $ref: '#/components/schemas/id'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/components/schemas/dataRequest'
        '400':
          description: invalid MSISDN
          schema:
            $ref: '#/components/schemas/dataRequest'
    post:
      tags:
        - Provide data value for MSISDN
      summary: Returns status of data purchase request
      parameters:
        - in: path
          name: msisdn
          required: true
          description: MSISDN for which data is being purchased
          schema:
            $ref: '#/components/schemas/id'
      requestBody:
        description: Data Purchase Request Post Object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dataRequestPostBody'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/components/schemas/dataRequestPostBody'
components:
  schemas:
    id:
      properties:
        msisdn:
          type: string
    authenticationRequestPostBody:
      type: object
      properties:
        username:
          type: string
          format: string
          description: username provided for API access. Test username is 'bank'
        password:
          type: string
          format: string
          description: password provided for API access. Test password is 'bank'
    airtimeRequestGet:
      type: object
      properties:
        airtimeRequest:
          type: object
    airtimeRequestPostBody:
      type: object
      properties:
        product_id:
          type: string
          format: string
          description: >-
            product id of the airtime product to be purchased (retrived from GET
            airtime/{msisdn})
        denomination:
          type: int
          format: int
          description: >-
            denomination of the airtime product to be purchased (retrived from
            GET airtime/{msisdn})
        send_sms:
          type: boolean
          format: boolean
          description: 'True to send SMS to MSISDN, false to not send SMS to MSISDN'
        sms_text:
          type: string
          format: string
          description: >-
            Empty if send_sms is false. Provide SMS text to be sent if send_sms
            is true
        customer_reference:
          type: string
          format: string
          description: Reference to uniquely identify this transaction
    dataRequestGet:
      type: object
      properties:
        dataRequest:
          type: object
    dataRequestPostBody:
      type: object
      properties:
        product_id:
          type: string
          format: string
          description: >-
            product id of the data product to be purchased (retrived from GET
            airtime/{msisdn})
        denomination:
          type: int
          format: int
          description: >-
            denomination of the data product to be purchased (retrived from GET
            airtime/{msisdn})
        send_sms:
          type: boolean
          format: boolean
          description: 'True to send SMS to MSISDN, false to not send SMS to MSISDN'
        sms_text:
          type: string
          format: string
          description: >-
            Empty if send_sms is false. Provide SMS text to be sent if send_sms
            is true
        customer_reference:
          type: string
          format: string
          description: Reference to uniquely identify this transaction
