openapi: 3.0.0
info:
  description: Gestion des actions du WSS
  version: "1.0.0"
  title: WindevSoftwareService
servers:
  - url: http://127.0.0.1:38001/WSS_ACTIONS/rest/api/v1
tags:
  - name: ACTIONS
    description: >-
      Gestion des actions
paths:
  '/Notifier/{Logiciel}/{Dossier}/{PID}/{Handle}':
    post:
      tags:
        - ACTIONS
      summary: Notification de l'activité
      operationId: Notifier
      description: |
        Notifie de l'activité d'un logiciel pour un dossier
      parameters:
        - in: path
          name: Logiciel
          description: pass an optional search string for looking up inventory
          required: true
          schema:
            type: string
        - in: path
          name: Dossier
          description: pass an optional search string for looking up inventory
          required: true
          schema:
            type: string
            minimum: 0
        - in: path
          name: PID
          description: pass an optional search string for looking up inventory
          required: true
          schema:
            type: integer
            format: int32
        - in: path
          name: Handle
          description: pass an optional search string for looking up inventory
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
        '500':
          description: EXCEPTION
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
  '/Notifier/{Logiciel}/{Dossier}':
    get:
      tags:
        - ACTIONS
      summary: Dossier actif ?
      operationId: ANotifier
      description: |
        Logiciel/Dossier actif dans les 60 derniéres secondes ?
      parameters:
        - in: path
          name: Logiciel
          description: nom du logiciel
          required: true
          schema:
            type: string
            maxLength: 18
        - in: path
          name: Dossier
          description: nom du dossier
          required: true
          schema:
            type: string
            maxLength: 30
      responses:
        '200':
          description: Logiciel/Dossier actif
        '404':
          description: Logiciel/Dossier non trouvé ou inactif
        '500':
          description: EXCEPTION
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
  '/{Logiciel}/{Dossier}/{Nom}':
    post:
      tags:
        - ACTIONS
      operationId: AjouterAction
      description: Création d'une action
      requestBody:
        description: Données internes de l'action
        required: true
        content:
          application/json:
            schema:
              type: object
          application/txt:
            schema:
              type: string
      parameters:
        - in: path
          name: Logiciel
          description: nom du logiciel
          required: true
          schema:
            type: string
            maxLength: 18
        - in: path
          name: Dossier
          description: nom du dossier
          required: true
          schema:
            type: string
            maxLength: 30
        - in: path
          name: Nom
          description: nom de l'action
          required: true
          schema:
            type: string
            maxLength: 50
        - in: query
          name: synchrone
          description: 0 = action asynchrone, 1 = action synchrone
          required: false
          schema:
            type: integer
        - in: query
          name: timeout
          description: temps max en secondes d'attente en mode synchrone
          required: false
          schema:
            type: integer
        - in: query
          name: code_user
          description: code utilisateur
          required: false
          schema:
            type: string
            maxLength: 5
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Action'
        '404':
          description: Action non trouvée
        '500':
          description: EXCEPTION
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
  '/{ActionId}':
    get:
      tags:
        - ACTIONS
      operationId: DonnerAction
      description: Récupération des données de l'action
      parameters:
        - in: path
          name: ActionId
          description: identifiant de l'action
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Action'
        '404':
          description: Action non trouvée
        '500':
          description: EXCEPTION
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
    put:
      tags:
        - ACTIONS
      operationId: ModifierAction
      description: Mise à jour de l'action
      parameters:
        - in: path
          name: ActionId
          description: identifiant de l'action
          required: true
          schema:
            type: integer
        - in: query
          name: action_resultat
          description: flag (à 1) pour intégrer les données passées en requête (body) en tant que résultat
          required: false
          schema:
            type: integer
        - in: query
          name: action_etat
          description: etat de l'action (0 à 5)
          required: false
          schema:
            type: integer
        - in: query
          name: code_user
          description: code utilisateur
          required: false
          schema:
            type: string
            maxLength: 5
      requestBody:
        description: Optionel, intégré si action_resultat=1
        required: false
        content:
          application/json:
            schema:
              type: object
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: OK
        '404':
          description: Action non trouvée
        '500':
          description: EXCEPTION
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
    delete:
      tags:
        - ACTIONS
      operationId: SupprimerAction
      description: |
        Mise à jour de l'action
      parameters:
        - in: path
          name: ActionId
          description: identifiant de l'action
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '404':
          description: Action non trouvée
        '500':
          description: EXCEPTION
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
  '/Liste/{Logiciel}/{Dossier}':
    get:
      tags:
        - ACTIONS
      operationId: LstActions
      description: Liste des actions d'un logiciel/dossier
      parameters:
        - in: path
          name: Logiciel
          description: nom du logiciel
          required: true
          schema:
            type: string
            maxLength: 18
        - in: path
          name: Dossier
          description: nom du dossier
          required: true
          schema:
            type: string
            maxLength: 30
        - in: query
          name: filtre_nom
          description: filtrage sur le nom d'une action
          required: false
          schema:
            type: string
            maxLength: 50
        - in: query
          name: filtre_date
          description: 'filtrage sur les actions > à une date (AAAAMMJJHHMMSSCCC)'
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LstActions'
        '500':
          description: EXCEPTION
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
  '/infos/version':
    get:
      operationId: VersionServeur
      description: Version du serveur
      responses:
        '200':
          description: OK -> version du serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  serveur:
                    type: string
                    example: "24.01.012"
components:
  schemas:
    Action:
      type: object
      required: 
      - "id"
      - "nom"
      - "etat"
      - "dateCreation"
      - "dateModification"
      - "synchro"
      - "userCode"
      - "logicielDossier"
      - "donnees"
      - "resultat"
      properties: 
        id: 
          type: "number"
          example: 149
        nom: 
          type: "string"
          example: "PRESTATION_AJOUTER"
        etat: 
          type: "number"
          example: 2
        dateCreation: 
          type: "string"
          example: "20200406104639665"
        dateModification: 
          type: "string"
          example: "20200406104639715"
        synchro: 
          type: "number"
        userCode: 
          type: "string"
          example: "APOLO"
        logicielDossier: 
          type: "string"
          example: "PERCEVAL\tDOSSTEST"
        donnees: 
          type: "string"
          example: "--données d'entrée de l'action - format json ou txt--"
        resultat: 
          type: "string"
          example: "--données de sortie de l'action - format json ou txt--"
    Erreur:
      type: object
      required: 
      - "erreur"
      properties: 
        erreur: 
          required: 
          - "libelle"
          - "detail"
          properties: 
            libelle: 
              type: "string"
              example: "Erreur interne"
            detail: 
              type: "string"
              example: "Le variant n'est pas un objet."
    LstActions:
      type: array
      items:
        type: object
        required: 
        - "id"
        - "nom"
        - "etat"
        - "dateCreation"
        - "dateModification"
        - "userCode"
        - "synchro"
        properties: 
          id: 
            type: "number"
            example: 149
          nom: 
            type: "string"
            example: "SYNCHRO DOME"
          etat: 
            type: "number"
            example: 2
          dateCreation: 
            type: "string"
            example: "20200406104639665"
          dateModification: 
            type: "string"
            example: "20200406104639715"
          userCode: 
            type: "string"
            maxLength: 5
            example: "APOLO"
          synchro: 
            type: "number"
            example: 1
