openapi: 3.0.0
info:
  description: Gestion des tâches du WSS
  version: "1.0.0"
  title: WindevSoftwareService
servers:
  - url:  http://127.0.0.1:38001/WSS_TACHES/rest/api/v1
tags:
  - name: TACHES
    description: 'Gestion des tâches'
paths:
  '/':
    post:
      tags:
        - TACHES
      operationId: AjouterTache
      description: Création d'une tâche
      requestBody:
        description: Données internes de la tâche
        required: true
        content:
          application/json:
            schema:
              type: object
      parameters:
        - in: query
          name: Nom
          description: nom de la tâche
          required: true
          schema:
            type: string
            maxLength: 50
        - in: query
          name: code_user
          description: code utilisateur
          required: false
          schema:
            type: string
            maxLength: 5
        - in: query
          name: type
          description: NomLogiciel_NomDossier créant la tâche
          required: false
          schema:
            type: string
            maxLength: 50
      responses:
        '200':
          description: OK -> renvoie le numéro (id) de la tâche créée
          content:
            application/txt:
              schema:
                type: integer
                example: 127
        '404':
          description: Tâche non trouvée
        '500':
          description: EXCEPTION
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
  '/{TacheId}':
    get:
      tags:
        - TACHES
      operationId: DonnerTache
      description: Récupération des données de la tâche
      parameters:
        - in: path
          name: TacheId
          description: identifiant de la tâche
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UneTache'
        '404':
          description: Tâche non trouvée
        '500':
          description: EXCEPTION
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
    put:
      tags:
        - TACHES
      operationId: ModifierTache
      description: Mise à jour de la tâche
      parameters:
        - in: path
          name: TacheId
          description: identifiant de la tâche
          required: true
          schema:
            type: integer
        - in: query
          name: tache_resultat
          description: flag (à 1) pour intégrer les données passées en requête (body) en tant que résultat
          required: false
          schema:
            type: integer
        - in: query
          name: tache_etat
          description: etat de la tâche (0 à 5)
          required: false
          schema:
            type: integer
        - in: query
          name: code_user
          description: code utilisateur
          required: false
          schema:
            type: string
            maxLength: 5
      requestBody:
        description: Optionel, intégré si tache_resultat=1
        required: false
        content:
          application/json:
            schema:
              type: object
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: OK
        '404':
          description: Tâche non trouvée
        '500':
          description: EXCEPTION
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
    delete:
      tags:
        - TACHES
      operationId: SupprimerTache
      description: |
        Mise à jour de la tâche
      parameters:
        - in: path
          name: TacheId
          description: identifiant de la tâche
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '404':
          description: Tâche non trouvée
        '500':
          description: EXCEPTION
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
  '/Liste':
    get:
      tags:
        - TACHES
      operationId: LstTaches
      description: Liste des tâches
      parameters:
        - in: query
          name: type
          description: filtre sur nom du logiciel_dossier
          example: "PERCEVAL_DOSSTEST"
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LstTaches'
        '500':
          description: EXCEPTION
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erreur'
  '/infos/version':
    get:
      operationId: VersionServeur
      description: Version du serveur
      responses:
        '200':
          description: OK -> version du serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  serveur:
                    type: string
                    example: "24.01.012"
components:
  schemas:
    UneTache:
      type: object
      required: 
      - "id"
      - "nom"
      - "etat"
      - "dateCreation"
      - "dateModification"
      - "userCode"
      - "logicielDossier"
      - "donnees"
      - "resultat"
      - "dateLancement"
      properties: 
        id: 
          type: "number"
          example: 149
        nom: 
          type: "string"
          maxLength: 50
          example: "SYNCHRO DOME"
        etat: 
          type: "number"
          example: 2
        dateCreation: 
          type: "string"
          example: "20200406104639665"
        dateModification: 
          type: "string"
          example: "20200406104639715"
        userCode: 
          type: "string"
          maxLength: 5
          example: "APOLO"
        logicielDossier: 
          type: "string"
          maxLength: 50
          example: "PERCEVAL\tDOSSTEST"
        donnees: 
          type: "string"
          example: "--données json supprimées--"
        resultat: 
          type: "string"
          example: "7499228"
        dateLancement: 
          type: "string"
          example: "20200406104639715"
    Erreur:
      type: object
      required: 
      - "erreur"
      properties: 
        erreur: 
          required: 
          - "libelle"
          - "detail"
          properties: 
            libelle: 
              type: "string"
              example: "Erreur interne"
            detail: 
              type: "string"
              example: "Le variant n'est pas un objet."
    LstTaches:
      type: array
      items:
        type: object
        required: 
        - "id"
        - "nom"
        - "etat"
        - "dateCreation"
        - "dateModification"
        - "userCode"
        - "dateLancement"
        - "donnees"
        - "logicielDossier"
        properties: 
          id: 
            type: "number"
            example: 149
          nom: 
            type: "string"
            example: "SYNCHRO DOME"
          etat: 
            type: "number"
            example: 2
          dateCreation: 
            type: "string"
            example: "20200406104639665"
          dateModification: 
            type: "string"
            example: "20200406104639715"
          userCode: 
            type: "string"
            maxLength: 5
            example: "APOLO"
          dateLancement: 
            type: "string"
            example: "20200406104639715"
          donnees: 
            type: "string"
            example: "JSON des donées internes de la tâches"
          logicielDossier: 
            type: "string"
            example: "PERCEVAL\tDOSSTEST"
