openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/dolearning/school/1.0.0
  - description: 测试服务
    url: http://dolearning.test/school/api/v1
info:
  description: 学校API
  version: "1.0.0"
  title: 学校API
  contact:
    email: cong.liu@dolearning.net
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: managers
    description: 管理员
  - name: teachers
    description: 老师
  - name: students
    description: 学生
paths:
  /apps:
    get:
      tags:
        - managers
        - teachers
        - students
      summary: 获取应用
      operationId: getApps
      responses:
        '200':
          description: 应用列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/AppList'
components:
  schemas:
    AppList:
      type: array
      items:
        $ref: '#/components/schemas/App'
    App:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          example: question
          description: 应用名称
        display_name:
          type: string
          example: 同步练习
          description: 应用的显示名称
        icon:
          type: string
          format: url
          example: https://dolearning.test/images/question.png
          description: 图标
        beta:
          type: boolean
          description: 内测版本
