openapi: 3.0.0
servers:
  - description: Ringgold ISNI API
    url: https://isni.ringgold.com/api/stable
  - description: Ringgold ISNI API release candidate
    url: https://isni.ringgold.com/api/rc
info:
  description: Simple Ringgold ISNI lookup API
  version: "1.0.0"
  title: Ringgold ISNI API
  contact:
    name: API Support
    url: 'https://support.ringgold.com/identify-database-api-services'
    email: support@ringgold.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
produces:
  - application/json
paths:
  '/institution/{id}':
    get:
      description: Lookup a record by ISNI id
      tags:
        - institution
      parameters:
        - name: id
          in: path
          description: ISNI ID
          schema:
            type: string
          required: true
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Institution'
  '/search':
    get:
      description: |
        Search isni records
      tags:
        - institution
      parameters:
        - name: q
          in: query
          description: search query
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: limits used for pagination
          required: false
          schema:
            type: number
            format: integer
        - name: offset
          in: query
          description: offset used for pagination
          required: false
          schema:
            type: number
            format: integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'

components:
  schemas:
    SearchResponse:
      properties:
        total:
          type: number
          format: integer
        limit:
          type: number
          format: integer
        offset:
          type: number
          format: integer
        institutions:
          type: array
          items:
            $ref: '#/components/schemas/Institution'
              
    Institution:
      properties:
        isni:
          type: string
        name:
          type: string
        alt_names:
          type: array
          items:
            properties:
              name:
                type: string
            type: object
        locality:
          type: string
        admin_area_level_1_short:
          type: string
        post_code:
          type: string
        country_code:
          type: string
        urls:
          type: array
          items:
            properties:
              url:
                type: string
            type: object
