openapi: 3.0.0
info:
  description:
    This is an API for an Interface Defination
  version: 1.0.0
  title: CVS Invoice Postings
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
  - name: DVSA CVS SAP Interface
    description: Data Defination Contract for DVSA SAP interface
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: crm
    description: Invoice Postings from Dynamics CRM
  - name: cpms
    description: Payments Postings from CPMS to SAP
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
servers:
  - url: https://localhost
paths:
  /v1/crm:
    post:
      parameters:
        - $ref: '#/components/parameters/correlationId'
      tags:
        - Posts an Invoice Line to SAP
      summary: Add new Invoice Line Item or Invoice Correction
      operationId: addCRMInvoiceLine
      requestBody:
        description: Invoice Line to be posted to SAP
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invoice'
        required: true
      responses:
        200:
          description: OK
        405:
          description: Invalid input
      security:
        - Lambda-Auth: []
      x-amazon-apigateway-integration:
        credentials: 'arn:aws:iam::${account_number}:role/$${stageVariables.sqs_role_name}'
        uri: 'arn:aws:apigateway:eu-west-1:sqs:path/${account_number}/$${stageVariables.queue_name}'
        responses:
          default:
            statusCode: '200'
        passthroughBehavior: 'when_no_match'
        httpMethod: 'POST'
        type: 'aws'
  /v1/cpms:
    post:
      parameters:
        - $ref: '#/components/parameters/correlationId'
      tags:
        - Posts an Invoice Line to SAP
      summary: Add new Invoice Line Item or Invoice Correction
      operationId: addCPMSInvoiceLine
      requestBody:
        description: Invoice Line to be posted to SAP
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payments'
        required: true
      responses:
        200:
          description: OK
        405:
          description: Invalid input
      security:
        - Lambda-Auth: []
      x-amazon-apigateway-integration:
        credentials: 'arn:aws:iam::${account_number}:role/$${stageVariables.sqs_role_name}'
        uri: 'arn:aws:apigateway:eu-west-1:sqs:path/${account_number}/$${stageVariables.queue_name}'
        responses:
          default:
            statusCode: '200'
        passthroughBehavior: 'when_no_match'
        httpMethod: 'POST'
        type: 'aws'
components:
  parameters:
    correlationId:
      in: header
      name: X-Amzn-Trace-Id
      required: true
      schema:
        type: string
      description: is a unique identifier value that is attached to requests and messages that allow reference to a particular transaction or event chain

  schemas:
    Invoice:
      type: array
      items:
        $ref: '#/components/schemas/InvoiceLine'
    InvoiceLine:
      type: object
      required:
        - scheme
        - country
        - activity
        - invoiceNumber
        - invoiceDate
        - invoicePostingDate
        - customerNumber
        - line
        - product
        - testReference
        - invoiceItemAmount
        - OABTransferValue
        - testDate
        - salesPerson
        - invCustomerName
        - invAddressLine1
        - invCity
        - invPostalCode
        - longText
      properties:
        scheme:
          type: string
          maxLength: 4
          enum:
            - "CVS"
        country:
          type: string
          maxLength: 2
          enum:
            - "GB"
        activity:
          type: string
          maxLength: 15
          enum:
            - "INVOICE"
            - "ATFMATCH"
            - "DEBT"
            - "TESTMATCH"
            - "AMEND"
        invoiceNumber:
          type: string
          maxLength: 25
          minLength: 18
          example: 'INV-20200301-000001'
          pattern: '(INV|PAY|CRE|REF)-\d{4}(((0)[0-9])|((1)[0-2]))([0-2][0-9]|(3)[0-1])-\d{6}'
        invoiceDate:
          type: string
          maxLength: 8
          format:  date-mday "/" date-month "/" date-fullyear
        invoicePostingDate:
          type: string
          maxLength: 8
          format:  date-mday "/" date-month "/" date-fullyear
        customerNumber:
          type: string
          maxLength: 15
          minLength: 7
          example: '0000100'
          pattern: '\d{7}'
        paymentReference:
          type: string
          example: 'CVS00220200305155307BA10291C'
          pattern: 'CVS[A-Z0-9]{25}'
        line:
          type: integer
          maxLength: 8
          minLength: 2
          multipleOf: 10
        product:
          type: string
          maxLength: 50
          enum:
            - "IO - Admin MOT Service-No VAT - Non ATF"
            - "IO - Admin MOT Service-No VAT -  ATF"
            - "IO-Cust Initiative (CK)-VAT - Non ATF"
            - "IO-Cust Initiative (CK)-VAT -  ATF"
            - "IO-HGV Vehicle Testing-VAT - Non ATF"
            - "IO-HGV Vehicle Testing-VAT -  ATF"
            - "IO-HGV Vehicle Testing-No VAT - Non ATF"
            - "IO-HGV Vehicle Testing-No VAT -  ATF"
            - "IO-Int Car DG Road(ADR)-No VAT - Non ATF"
            - "IO-Int Car DG Road(ADR)-No VAT -  ATF"
            - "IO - LGV Vehicle Testing-VAT - Non ATF"
            - "IO - LGV Vehicle Testing-VAT -  ATF"
            - "IO - MSVA APPROVAL-No VAT - Non ATF"
            - "IO - MSVA APPROVAL-No VAT -  ATF"
            - "IO - CVS Other-No VAT - Non ATF"
            - "IO - CVS Other-No VAT -  ATF"
            - "IO - PSV Vehicle Test-VAT - Non ATF"
            - "IO - PSV Vehicle Test-VAT -  ATF"
            - "IO - PSV Vehicle Test-No VAT - Non ATF"
            - "IO - PSV Vehicle Test-No VAT -  ATF"
            - "IS - Admin MOT Service-No VAT - Non ATF"
            - "IS - Admin MOT Service-No VAT -  ATF"
            - "IS - Approval Centres-No VAT - Non ATF"
            - "IS - Approval Centres-No VAT -  ATF"
            - "IS - COIF-No VAT - Non ATF"
            - "IS - COIF-No VAT -  ATF"
            - "IS - HGV Vehicle Test-VAT - Non ATF"
            - "IS - HGV Vehicle Test-VAT -  ATF"
            - "IS - HGV Vehicle Test-No VAT - Non ATF"
            - "IS - HGV Vehicle Test-No VAT -  ATF"
            - "IS - IVA-VAT - Non ATF"
            - "IS - IVA-VAT -  ATF"
            - "IS - IVA-No VAT - Non ATF"
            - "IS - IVA-No VAT -  ATF"
            - "IS-Int Trans Perish-ATP-No VAT - Non ATF"
            - "IS-Int Trans Perish-ATP-No VAT -  ATF"
            - "IS-Int Car DG Road(ADR)-No VAT - Non ATF"
            - "IS-Int Car DG Road(ADR)-No VAT -  ATF"
            - "IS - LGV Testing-VAT - Non ATF"
            - "IS - LGV Testing-VAT -  ATF"
            - "IS - LGV Testing-No VAT - Non ATF"
            - "IS - LGV Testing-No VAT -  ATF"
            - "IS - MSVA APPROVAL-No VAT - Non ATF"
            - "IS - MSVA APPROVAL-No VAT -  ATF"
            - "IS - PSV Testing-VAT - Non ATF"
            - "IS - PSV Testing-VAT -  ATF"
            - "IS - PSV Testing-No VAT - Non ATF"
            - "IS - PSV Testing-No VAT -  ATF"
            - "IV   - HGV Testing-VAT - Non ATF"
            - "IV   - HGV Testing-VAT -  ATF"
            - "IV   - IVA Approval-VAT - Non ATF"
            - "IV   - IVA Approval-VAT -  ATF"
            - "IV   - MSVA APPROVAL-VAT - Non ATF"
            - "IV   - MSVA APPROVAL-VAT -  ATF"
            - "IV   - PSV Vehicle Testing-VAT - Non ATF"
            - "IV   - PSV Vehicle Testing-VAT -  ATF"
        testReference:
          type: string
          maxLength: 50
          example: 'HGV_AN_S_NH_AT_TIV_24-INV-20200301-000001-010'
          pattern: '(HGV|PSV|TRA)_[A-Z]{2}_[A-Z]_[A-Z]{2}_[A-Z]{2}_[A-Z]{3}_[0-9]{2}-(INV|PAY|CRE|REF)-[0-9]{8}-[0-9]{6}-[0-9]{3}'
        invoiceItemAmount:
          type: integer
          maxLength: 11
          minimum: 0
        OABTransferValue:
          type: integer
          maxLength: 13
          minimum: 0
        testDate:
          type: string
          maxLength: 8
          format:  date-mday "/" date-month "/" date-fullyear
        salesPerson:
          type: string
          enum:
            - "TNM 1 Area 2"
            - "TNM 2 Area 3"
            - "TNM 3 Area 5"
            - "TNM 4 Area 6"
            - "TNM 5 Area 9"
            - "TNM 6 Area 10"
            - "TNM 7 Area 11"
            - "TNM 8 Area 12"
            - "TNM 9 Area 15"
            - "TNM 10 Area 17"
            - "TNM 11 Area 18"
            - "TNM 12 Area 13"
        invCustomerName:
          type: string
          maxLength: 35
        invAddressLine1:
          type: string
          maxLength: 35
        invAddressLine2:
          type: string
          maxLength: 35
        invAddressLine3:
          type: string
          maxLength: 35
        invAddressLine4:
          type: string
          maxLength: 35
        invCity:
          type: string
          maxLength: 35
        invPostalCode:
          type: string
          maxLength: 10
        longText:
          type: string
          maxLength: 132
    Payments:
      type: array
      items:
        $ref: '#/components/schemas/Payment'
    Payment:
      type: object
      required:
        - scheme
        - country
        - activity
        - taxcode
        - taxAmount
        - line
        - lineDescription
        - lineAmount
        - receiptAmount
        - receiptNumber
        - receiptDate
        - receiptGLDate
        - receiptMethod
        - recCustomerNumber
        - recCustomerName
        - recAddressLine1
        - recCity
        - recPostalCode
        - recReference
        - salesPerson
        - orderReference
      properties:
        scheme:
          type: string
          maxLength: 4
          enum:
            - "CVS"
        country:
          type: string
          maxLength: 2
          enum:
            - "GB"
        activity:
          type: string
          maxLength: 15
          enum:
            - "TOPUP"
            - "REFUND"
            - "FAILEDP"
            - "PAYMENT"
            - "COMP"
            - "ADJUST"
        invoiceNumber:
          type: string
          maxLength: 25
          nullable: true
        invoiceDate:
          type: string
          maxLength: 8
        ruleStartDate:
          type: string
          maxLength: 8
          format:  date-mday "/" date-month "/" date-fullyear
        taxcode:
          type: string
          maxLength: 1
          enum:
            - "Z"
        taxAmount:
          type: integer
          maxLength: 13
          enum:
            - 0
        invoiceAmount:
          type: string
          maxLength: 13
        line:
          type: integer
          maxLength: 8
          minLength: 1
        lineDescription:
          type: string
          maxLength: 80
          enum:
            - "PFA Top Up"
            - "Refund"
            - "Failed Payment"
            - "Comp"
            - "Adjust"
        lineAmount:
          type: integer
          maxLength: 11
          minLength: 1
          minimum: 0
        receiptAmount:
          type: integer
          maxLength: 13
          minLength: 1
          minimum: 0
        receiptNumber:
          type: string
          maxLength: 28
          example: 'CVS00220200305155307BA10291C'
          pattern: 'CVS[A-Z0-9]{25}'
        receiptDate:
          type: string
          maxLength: 8
          format:  date-mday "/" date-month "/" date-fullyear
        receiptGLDate:
          type: string
          maxLength: 8
          format:  date-mday "/" date-month "/" date-fullyear
        receiptMethod:
          type: string
          maxLength: 15
          enum:
            - "CARD"
            - "CHEQUE"
            - "COMP"
            - "POSTAL_ORDER"
            - "CASH"
            - "DIRECT_DEBIT"
        receiptMatchAmount:
          type: string
          maxLength: 13
        ccReference:
          type: string
          maxLength: 10
          minimum: 0
        refundAmount:
          type: integer
          maxLength: 13
          minimum: 0
        invCustomerNumber:
          type: string
          maxLength: 15
          minLength: 7
        invCustomerName:
          type: string
          maxLength: 35
        invAddressLine1:
          type: string
          maxLength: 35
        invAddressLine2:
          type: string
          maxLength: 35
        invAddressLine3:
          type: string
          maxLength: 35
        invAddressLine4:
          type: string
          maxLength: 35
        invCity:
          type: string
          maxLength: 35
        invPostalCode:
          type: string
          maxLength: 10
        invReference:
          type: string
          maxLength: 16
        recCustomerNumber:
          type: string
          maxLength: 10
          minLength: 7
          example: '0000100'
          pattern: '\d{7}'
        recCustomerName:
          type: string
          maxLength: 35
        recAddressLine1:
          type: string
          maxLength: 35
        recAddressLine2:
          type: string
          maxLength: 35
        recAddressLine3:
          type: string
          maxLength: 35
        recAddressLine4:
          type: string
          maxLength: 35
        recCity:
          type: string
          maxLength: 35
        recPostalCode:
          type: string
          maxLength: 10
        recReference:
          type: string
          maxLength: 16
        salesPerson:
          type: string
          maxLength: 40
          enum:
            - "TNM 1 Area 2"
            - "TNM 2 Area 3"
            - "TNM 3 Area 5"
            - "TNM 4 Area 6"
            - "TNM 5 Area 9"
            - "TNM 6 Area 10"
            - "TNM 7 Area 11"
            - "TNM 8 Area 12"
            - "TNM 9 Area 15"
            - "TNM 10 Area 17"
            - "TNM 11 Area 18"
            - "TNM 12 Area 13"
        orderReference:
          type: string
          maxLength: 25
          minimum: 0
          pattern: '[+]?\d+(\d+)?'
        payingInBatchReference:
          type: string
          maxLength: 40
          minimum: 0
          pattern: '[+]?\d+(\d+)?'
  securitySchemes:
    Lambda-Auth:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "custom"
      x-amazon-apigateway-authorizer:
        authorizerUri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:${account_number}:function:$${stageVariables.auth_lambda}/invocations"
        authorizerCredentials: "${auth_cred}"
        authorizerResultTtlInSeconds: 300
        type: "token"
