openapi: 3.0.0
info:
  version: '1'
  title: 'Remessas Aplicativo'
  description: 'Api para envio de Remessas para Contas em Moeda Estrangeira'
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/BTCorretora/Remessas/1
paths:
  /obterConfiguracao:
    get: 
      summary: Obtém a configuração atual para remessas
      operationId: obterConfiguracao
      description: Retorna a configuração de moedas e motivos suportadas para envio de remessas
      responses:
        '200':
          description: detalhes da configuração
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnvelopeConfiguracao'
  /obterCotacao:
    post: 
      summary: Obtém cotação em andamento
      operationId: obterCotacao
      description: Retorna a informações sobre uma cotação em andamento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametrosIdentificadorCotacao'
      responses:
        '200':
          description: detalhes da cotação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnvelopeCotacao'
  /iniciarCotacao:
    post:
      summary: Iniciar uma cotação de remessa
      operationId: iniciarCotacao
      description: Inicia o processo de cotação para envio de remessa de forma assíncrona
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametrosCotacao'
      responses:
        '200':
          description: retorna o identificador da ação para acompanhamento
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/EnvelopeGuid'
  /aceitarCotacao:
    post:
      summary: Iniciar um processo de aceite de cotação de remessa
      operationId: aceitarCotacao
      description: Inicia o processo de aceite de uma cotação em andamento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametrosAceiteCotacao'
      responses:
        '200':
          description: retorna o identificador da ação para acompanhamento
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/EnvelopeGuid'
  /cancelarCotacao:
    post:
      summary: Inicia um processo de cancelamento de cotação de remessa
      operationId: cancelarCotacao
      description: Inicia o processo de cancelamento de uma cotação em andamento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametrosIdentificadorCotacao'
      responses:
        '200':
          description: retorna o identificador da ação para acompanhamento
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Resultado'
  /cadastrarBeneficiario:
    post:
      summary: Cadastra um beneficiário para remessa
      operationId: cadastrarBeneficiario
      description: Cadastra um beneficiário para utilização em remessas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametrosCadastroBeneficiario'
      responses:
        '200':
          description: retorna o identificador do beneficiário
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/EnvelopeInteger'
  /alterarBeneficiario:
    post:
      summary: Altera um beneficiário de remessa existente
      operationId: alterarBeneficiario
      description: Altera um beneficiário para utilização em remessas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametrosAlteracaoBeneficiario'
      responses:
        '200':
          description: retorna o identificador do beneficiário
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/EnvelopeInteger'
  /cadastrarContaBeneficiario:
    post:
      summary: Cadastra uma conta de um beneficiário de remessa
      operationId: cadastrarContaBeneficiario
      description: Cadastra uma conta de beneficiário para utilização em remessas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametrosContaBeneficiario'
      responses:
        '200':
          description: retorna o identificador da conta do beneficiário
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/EnvelopeInteger'
  /removerBeneficiario:
    post:
      summary: Remove um beneficiário de remessa
      operationId: removerBeneficiario
      description: Remove beneficiário de remessas
      requestBody:
        description: identificador do beneficiário
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametroId'
      responses:
        '200':
          description: Retorna resultado da ação
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Resultado'
  /removerContaBeneficiario:
    post:
      summary: Remove uma conta de beneficiário de remessa
      operationId: removerContaBeneficiario
      description: Remove conta de beneficiário de remessas
      requestBody:
        description: identificador da conta do beneficiário
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametroId'
      responses:
        '200':
          description: Retorna resultado da ação
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Resultado'
  /obterBeneficiarios:
    post:
      summary: Retorna a relação de beneficiários de remessa do cliente
      operationId: obterBeneficiarios
      description: Retorna a relação de beneficiários de remessa do cliente e suas contas
      requestBody:
        description: identificador do cliente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametroId'
      responses:
        '200':
          description: Relação de beneficiários
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/EnvelopeBeneficiarios'
components:
  schemas:
    Resultado:
      type: object
      properties:
        Sucesso:
          type: boolean
          nullable: false
        Mensagem:
          type: string
          nullable: true
        CodigoErro:
          type: integer
          format: int32
          nullable: true
    EnvelopeConfiguracao:
      allOf:
        - $ref: '#/components/schemas/Resultado'
        - type: object
          properties:
            Dados:
              $ref: '#/components/schemas/Configuracao'
    EnvelopeCotacao:
      allOf:
        - $ref: '#/components/schemas/Resultado'
        - type: object
          properties:
            Dados:
              $ref: '#/components/schemas/Cotacao'
    EnvelopeGuid:
      allOf:
        - $ref: '#/components/schemas/Resultado'
        - type: object
          properties:
            Dados:
              type: string
              format: Guid
              nullable: true
    EnvelopeInteger:
      allOf:
        - $ref: '#/components/schemas/Resultado'
        - type: object
          properties:
            Dados:
              type: integer
              format: int32
              nullable: true
    EnvelopeBeneficiarios:
      allOf:
        - $ref: '#/components/schemas/Resultado'
        - type: object
          properties:
            Dados:
              type: array
              items:
                $ref: '#/components/schemas/Beneficiario'
              nullable: true
    Cotacao:
      type: object
      required:
        - Id
        - Expiracao
        - ValorEmReais
        - ValorDestino
        - Moeda
        - Iof
        - Taxa
        - Despesa
        - TaxaVet
      properties:
        Id:
          type: integer
          format: int32
          nullable: false
        Expiracao:
          type: string
          format: DateTime
          nullable: false
        ValorEmReais:
          type: number
          format: Decimal
          nullable: false
        ValorDestino:
          type: number
          format: Decimal
          nullable: false
        Moeda:
          type: string
          description: Código ISO
          nullable: false
        Iof:
          type: number
          format: Decimal
          nullable: false
        Taxa:
          type: number
          format: Decimal
          nullable: false
        Despesa:
          type: number
          format: Decimal
          nullable: false
        TaxaVet:
          type: number
          format: Decimal
          nullable: false
    Moeda:
      type: object
      properties:
        Nome:
          type: string
          nullable: false
        CodigoMoeda:
          type: string
          nullable: false
          description: Código ISO
    IdNome:
      type: object
      required:
        - Id
        - Nome
      properties:
        Id:
          type: integer
          format: int32
          nullable: false
        Nome:
          type: string
          nullable: false
    Configuracao:
      type: object
      properties:
        Moedas:
          type: array
          nullable: false
          items:
            $ref: '#/components/schemas/Moeda'
        Motivos:
          type: array
          nullable: false
          items:
            $ref: '#/components/schemas/IdNome'
    Beneficiario:
      type: object
      properties:
        BeneficiarioId:
          type: integer
          format: inte32
          nullable: false
        Nome:
          type: string
          nullable: false
        Remetente:
          type: boolean
          nullable: false
          description: indica se o beneficiário é o próprio remetente
        Telefone:
          type: string
          nullable: false
        Contas:
          type: array
          nullable: false
          items:
            $ref: '#/components/schemas/Conta'
    ParametrosCotacao:
      type: object
      required:
        - idMotivo
        - codigoMoeda
        - valor
        - emReais
      properties:
        idMotivo:
          type: integer
          format: int32
          nullable: false
        codigoMoeda:
          type: string
          nullable: false
        valor:
          type: number
          format: decimal
          nullable: false
        emReais:
          type: boolean
          nullable: false
          description: informa se o valor é o de destino, em moeda estrangeira, ou o valor em reais a ser enviado.
    ParametrosAceiteCotacao:
      type: object
      required:
        - idCotacao
        - idCliente
        - idContaBeneficiario
      properties:
        idCotacao:
          type: string
          format: Guid
          nullable: false
        idCliente:
          type: integer
          format: int32
          nullable: false
        idContaBeneficiario:
          type: integer
          format: int32
          nullable: false
    Conta:
      type: object
      required:
        - Nome
        - InformacaoConta1
        - CodigoMoeda
        - CodigoPais
      properties:
        Nome:
          type: string
          nullable: false
        InformacaoConta1:
          type: string
          nullable: false
          description: para EUA, Routing Number. Para Europa, IBAN
        InformacaoConta2:
          type: string
          nullable: true
          description: para EUA, Accounting Number
        Id:
          type: integer
          format: int32
          nullable: true
        CodigoMoeda:
          type: string
          nullable: false
          description: Código ISO
        CodigoPais:
          type: string
          nullable: false
          description: Código ISO-2 do país
    ParametrosCadastroBeneficiario:
      type: object
      required:
        - idCliente
        - Nome
        - Remetente
        - Telefone
        - Contas
      properties:
        idCliente:
          type: integer
          format: inte32
          nullable: false
        Nome:
          type: string
          nullable: false
        Remetente:
          type: boolean
          nullable: false
          description: indica se o beneficiário é o próprio remetente
        Telefone:
          type: string
          nullable: false
        Contas:
          type: array
          nullable: false
          items:
            $ref: '#/components/schemas/Conta'
    ParametrosAlteracaoBeneficiario:
      type: object
      required:
        - idBeneficiario
        - Nome
        - Remetente
        - Telefone
      properties:
        idBeneficiario:
          type: integer
          format: inte32
          nullable: false
        Nome:
          type: string
          nullable: false
        Remetente:
          type: boolean
          nullable: false
          description: indica se o beneficiário é o próprio remetente
        Telefone:
          type: string
          nullable: false
    ParametrosContaBeneficiario:
      type: object
      required:
        - idBeneficiario
        - Conta
      properties:
        idBeneficiario:
          type: integer
          format: inte32
          nullable: false
        Conta:
          $ref: '#/components/schemas/Conta'
    ParametrosIdentificadorCotacao:
      type: object
      required:
        - idCotacao
      properties:
        idCotacao:
          type: string
          format: Guid
          nullable: false
    ParametroId:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          format: int32
          nullable: false
