openapi: 3.0.0
info:
  description: |
    Chatbot app calls SAP PO 7.5 Integration
  version: "1.0.0"
  title: 'DPSP PO7.5 ChatBot Integration'
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Partner evt/IT
    email: contato@evtit.com
    url: http://www.evtit.com/
#  license:
#    name: Apache 2.0
#    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: chatbot
    description: Everything about Chatbot integration for DPSP
paths:
  /ChatbotAPI/:
    post:
      tags:
        - chatbot
      summary: API
      operationId: chatbot
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ZEVOIT_CHATBOT_API_T'
      security:
        - po75_auth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ZEVOIT_CHATBOT_API'
        required: true
servers:
# Added by API Auto Mocking Plugin
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/evt-nathan-ferreira/DPSP_ChatBot/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/evt-nathan-ferreira/DPSP_RFC/1.0.0
  - url: 'http://vhdsppodci.hec.dpsp.int:50000/RESTAdapter'
    description: SAP PO Development server (DP1) - External URL
components:
  securitySchemes:
    po75_auth:
      type: http
      scheme: basic
    api_key:
      type: apiKey
      name: api_key
      in: header
  schemas:
    ZEVOIT_CHATBOT_API:
      type: object
      properties:
        I_ACTION:
          type: string
          description: I_ACTION
        I_CODE:
          type: string
          description: I_CODE
        I_EBELN:
          type: string
          description: I_EBELN 
        I_UNAME:
          type: string
          description: I_UNAME 
      title: ZEVOIT_CHATBOT_API
      xml:
        name: ZEVOIT_CHATBOT_API
      description: ''
    ZEVOIT_CHATBOT_API_T:
      type: object
      properties:
        T_RETURN:
          $ref: '#/components/schemas/Item_POS'
        T_POS:
          $ref: '#/components/schemas/Item_RETURN'
      title: ZEVOIT_CHATBOT_API_T
      xml:
        name: ZEVOIT_CHATBOT_API_T
    Item_POS:
      type: object
      properties:
        item:
          type: array
          items:
            $ref: '#/components/schemas/T_POS'
    Item_RETURN:
      type: object
      properties:
        item:
          type: array
          items:
            $ref: '#/components/schemas/T_RETURN'
    T_POS:
      type: object
      properties:
        UNAME:
          type: string
          description: UNAME
        WI_ID:
          type: string
          description: WI_ID
        EBELN:
          type: string
          description: EBELN
        FRGCO:
          type: string
          description: FRGCO
        RLWRT:
          type: string
          description: RLWRT
        WI_TEXT:
          type: string
          description: WI_TEXT
        ANEXOS:
          type: string
          description: ANEXOS
    T_RETURN:
      type: object
      properties:
        TYPE:
          type: string
          description: TYPE
        ID:
          type: string
          description: ID
        NUMBER:
          type: string
          description: NUMBER
        MESSAGE:
          type: string
          description: MESSAGE
        LOG_NO:
          type: string
          format: date
          description: LOG_NO
        LOG_MSG_NO:
          type: string
          description: LOG_MSG_NO
        MESSAGE_V1:
          type: string
          description: MESSAGE_V1
        MESSAGE_V2:
          type: string
          description:  MESSAGE_V2
        MESSAGE_V3:
          type: string
          description: MESSAGE_V3
        MESSAGE_V4:
          type: string
          description: MESSAGE_V4
        PARAMETER:
          type: string
          description: PARAMETER
        ROW:
          type: string
          description: ROW
        FIELD:
          type: string
          description: FIELD
        SYSTEM:
          type: string
          description: SYSTEM
