openapi: 3.0.0
info:
  description: Bolti vásárlásokhoz használt kupon API.
  version: "1.0.1"
  title: Konzolvilág kuponbeváltás API MSKiskerhez
  contact:
    email: zoltan.piri@konzolvilag.hu
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /coupon_api/validate:
    post:
      summary: VALIDATE_COUPON
      description: 'Ellenőrzi, hogy felhasználható-e a kupon'
      responses:
        '200':
          description: 'MSKisker válasz'
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/MskkResponseValidate'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                operation:
                  type: string
                  description: 'fix érték: VALIDATE_COUPON'
                param1:
                  type: string
                  description: 'Kuponkód'
                  
  /coupon_api/redeem:
    post:
      summary: REDEEM_COUPON
      description: 'Beváltja a kupont'
      responses:
        '200':
          description: 'MSKisker válasz'
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/MskkResponseRedeem'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                operation:
                  type: string
                  description: 'fix érték: REDEEM_COUPON'
                param1:
                  type: string
                  description: 'Kuponkód'
                param2:
                  type: string
                  description: 'Bizonylatszám amihez a beváltást csatoljuk'
                  
components:
  schemas:
    MskkResponseValidate:
      type: object
      properties:
        response:
          type: object
          properties:
            success:
              type: boolean
              description: 'API hívás sikeressége'
            message:
              type: string
              description: 'Válasz üzenet'
            data:
              type: object
              properties:
                kupon:
                  type: object
                  description: 'A kuponkód részletes adatai'
                  properties:
                    azon:
                      type: string
                      description: 'Kupon típusa'
                    kod:
                      type: string
                      description: 'Kuponkód'
                    pont:
                      type: integer
                      description: 'Kupon törzsvásárlói fix pont értéke'
                    pontszorzo:
                      type: integer
                      description: 'Kupon törzsvásárlói pont szorzó értéke'
                    kedvezmeny:
                      type: integer
                      description: 'Kupon fix árkedvezmény értéke'
                    kedvezmenyszazalek:
                      type: integer
                      description: 'Kupon százalékos árkedvezmény értéke'
                      
    MskkResponseRedeem:
      type: object
      properties:
        response:
          type: object
          properties:
            success:
              type: boolean
              description: 'API hívás sikeressége'
            message:
              type: string
              description: 'Hibaüzenet ha nem volt sikeres a beváltás'
