openapi: 3.0.2
info:
  title: 'Profile Address Book API'
  version: "1.0.0"
  description: >
     This API provides a set of methods to allow a customer to maintain a list of addresses in an address book
     
     
    
     That then makes it easier for the customer to order and enjoy delicious wines whether that be:-
     
     
     *  Using the address in the website express checkout
     
     
     *  Managing the way they use the address for thie regular wineplan
     
     
     *  Any other service that the custome uses or subscribes to.
     
     
  contact:
    email: apisupport@directwines.com
tags:
  - name: Profile Address Book API
servers:
# Added by API Auto Mocking Plugin
# Added by API Auto Mocking Plugin
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Direct_Wines/ProfileAddressBookAPISuite/1.0.0
  - url: /api
    description: This website

# =========================================================================================
#  API methods start here
# =========================================================================================  
paths:
  /user/shipping/addresses:
   post:
    tags:
    - Profile Address Book API 
    summary: Add New Address
    description: ''
    operationId: addNewAddress
    requestBody:
      description: 'Input parameter which holds shipping address to be added profile '
      required: true
      content:
        application/json:
          schema:
            "$ref": '#/components/schemas/AddShippingAddressRequest'
          example:
            shippingNewAddress:
              address:
                address1: "Hurricane Road"  
                address2: "Unit 5, The I O Centre"
                city: "Gloucester"
                houseNumber: 23
                houseName: "Williams Villa"
                postalCode: 'GL3 4AQ'
                type: UK
                county: 'Gloucestershire'
                country: UK
                deliveryInstructions:
                  deliveryInstruction: No Safe Place Signature Required
              contactInfo:
                companyName: df
                deliveryPhoneNumber: '01111111111'
                email: 'tejashree@nviz.com'
              personalInfo:
                salutation: Miss
                firstName: 'Tejashree'
                lastName: 'Patil'
            createBillingAddrflag: false
    responses:
      '200':
        description: successful operation
        content: 
          application/json:
            schema:
              $ref: 'https://api.swaggerhub.com/apis/Direct_Wines/CommonAPIModelsSuite/1.0.0#/components/schemas/ApiResponse'
        
      '422':
          description: A validation error occured when calling this method.  For example it may be that the supplied account Id was invalid or was unauthorized for this user. 
          content: 
            application/json:
              schema:
                 $ref: 'https://api.swaggerhub.com/apis/Direct_Wines/CommonAPIModelsSuite/1.0.0#/components/schemas/CommonResponseHeader'
                 
      

# --------------------------------------------------------------------------------------                 
  /user/shipping/address/{addressId}/options:
    post:
      tags:
        - Profile Address Book API
      summary: Apply an option to an existing address in the address book
      description: |
         This API allows a customer to specify how a address in their address book should be used.  The full list of options is described below,  but the most common options that can be selected are:-
         * It can be set as the default address to be used on future sales orders.
         
         Multiple options can be selected.  Where that is the case the union of all the selected options will be applied. SAVE_TO_ADDRESS_BOOK option is not applicable for this API
      operationId: applyOptionToAddressInAddressWallet
      parameters:
        - name: addressId
          in: path
          description: The id of a valid address entry which this method is to act upon. 
          required: true
          schema:
            type: string
            pattern: .*
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShippingAddressOptions'            
        description: >-
          A list of options whch specify how this card may be used
        
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShippingAddressOptions'
        '422':
          description: An unexpected validation or processing error occured whilse calling this method. 
          content: 
            application/json:
              schema:
                 $ref: 'https://api.swaggerhub.com/apis/Direct_Wines/CommonAPIModelsSuite/1.2.0#/components/schemas/CommonResponseHeader'

# --------------------------------------------------------------------------------------                 
  /user/shipping/address/{addressId}:
    delete:
      tags:
        - Profile Address Book API
      summary: Remove an address from the customers address book
      description: ''
      operationId: removeAddressFromAddressBook
      parameters:
        - name: addressId
          in: path
          description: The id of the entry in the customer's address book which is to be deleted 
          required: true
          schema:
            type: string
            pattern: .*
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: >-
                  https://api.swaggerhub.com/apis/Direct_Wines/CommonAPIModelsSuite/1.0.0#/components/schemas/ApiResponse
        '422':
          description: An unexpected validation or processing error occured whilse calling this method. 
          content: 
            application/json:
              schema:
                 $ref: 'https://api.swaggerhub.com/apis/Direct_Wines/CommonAPIModelsSuite/1.2.0#/components/schemas/CommonResponseHeader'
  
  /user/shipping/address:
    put:
      tags: 
        - Profile Address Book API
      summary: Edit a shipping address in customers address book
      operationId: editShippingAddress
      parameters:
        - name: addressId
          in: path
          description: The id of the entry in the customer's address book which is to be edited 
          required: true
          schema:
            type: string
            pattern: .*
      requestBody:
        description: 'Input parameter which holds shipping address to be edited in a profile '
        required: true
        content:
          application/json:
            schema:
              "$ref": '#/components/schemas/EditShippingAddressRequest'
      responses:
        '200':
          description: successful operation
          content: 
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/apis/Direct_Wines/CommonAPIModelsSuite/1.0.0#/components/schemas/ApiResponse'
          
        '422':
            description: A validation error occured when calling this method.  For example it may be that the supplied account Id was invalid or was unauthorized for this user. 
            content: 
              application/json:
                schema:
                   $ref: 'https://api.swaggerhub.com/apis/Direct_Wines/CommonAPIModelsSuite/1.0.0#/components/schemas/CommonResponseHeader'
                  
components:
  schemas:
#
#  REQUEST Objects
#  ========================================================================  
    AddShippingAddressRequest:
      type: object
      properties:
        shippingNewAddress:
          $ref: "#/components/schemas/Contact"
        createBillingAddrflag:
          type: boolean
          default: false
          description: This flag is used to define if shipping address passed in the input should be saved in the billing address as well.
        options:
          $ref: '#/components/schemas/ShippingAddressOptions'
    
    EditShippingAddressRequest:
      type: object
      properties:
        shippingNewAddress:
          $ref: "#/components/schemas/Contact"
        createBillingAddrflag:
          type: boolean
          default: false
          description: This flag is used to define if shipping address passed in the input should be saved in the billing address as well.
        addressId:
          type: string
          description: This property is not used for add address API however this is used in edit address api to identify the address to be edited.
          example: "e09832332"
        options:
          $ref: '#/components/schemas/ShippingAddressOptions'
    
    Contact:
      description: This is used to define the contact details of the user which includes address , contact information and personal information.
      type: object
      required:
        - address
        - contactInfo
        - personalInfo
      properties:
        address:
          oneOf:
            - $ref: "#/components/schemas/USAddress"
            - $ref: "#/components/schemas/NZAddress"
            - $ref: "#/components/schemas/UKAddress"
            - $ref: "#/components/schemas/AUAddress"
            - $ref: "#/components/schemas/OtherAddress"
        personalInfo:
          $ref: "#/components/schemas/PersonalInformation"
        contactInfo:
          $ref: "#/components/schemas/ContactInformation"

    ContactInformation:
      type: object
      
      description: This is used to define the contact information of the user.
      properties:
        deliveryPhoneNumber:
          description: The contact phone number for a delivery.
          type: string
          example: 0934567899
        email:
          description: This is used to define the email address of the user.
          type: string
        companyName:
          description: This is used to define companyName in the address contact information.
          type: string
        dayPhoneNumber:
          description: This is used to define the day phone number of the user and is used in LWM and INTL market.
            
          type: string
          
        phoneNumberExtension:
          description: This is used to define the phone number extension in contact information.
          type: string
        eveningPhoneNumber:
          description: This is used to define the evening phone number in contact information.
          type: string
        alternatePhoneNumber:
          description: This is used to define the alternate phone number in contact information.
          type: string
        localPhoneNumber:
          description: This is used to define the local phone number in contact information.
          type: string
        phoneNotes:
          description: This is used to define the phone notes in contact information.
          type: string
      
      example:
        email: jahsasd@gmail.com
        companyName: Infusion
        dayPhoneNumber: '9812345670'
    
    OtherAddress:
      allOf:
        - $ref: "#/components/schemas/PostalAddress"
        - type: object
          properties:
            name:
              type: string
            state:
              type: string
            postalCode:
              type: string


    NZAddress:
      description: This is used to define the address object for NZ which inherits postal address object and has its own properties postal code and delivery instruction. 
      allOf:
        - $ref: "#/components/schemas/PostalAddress"
        - type: object
          properties:
            name:
              type: string
            postalCode:
              type: string
            deliveryInstructions:
              "$ref": "#/components/schemas/DeliveryInstructions"
 
    AUAddress:
      description: This is used to define the address object for AU which inherits postal address object and has its own properties specific to AU country.
      allOf:
        - $ref: "#/components/schemas/PostalAddress"
        - type: object
          properties:
            name:
              type: string
            state:
              type: string
            stateCode:
              type: string
            street:
              type: string
            postalCode:
              type: string
            suburb:
              type: string

 
    USAddress:
      description: This is used to define the address object for US which inherits postal address object and has its own properties specific to US country.
      allOf:
        - $ref: "#/components/schemas/PostalAddress"
        - type: object
          properties:
            name:
              type: string
            state:
              description: This is used to define state in the US postal address.
              type: string
              example:  MA
            stateCode:
              type: string
              description: This is used to define stateCode in the postal address.
              example: MA
            zipCode:
              type: string
          required: 
            - state
            - zipCode
            - address2
            - city
            - country
            - type
          example:
            type: US
            zipCode: '85255'
            state: MA
            address1: Hurricane Road
            address2: Unit 5, The I O Centre
            city: monson
            country: US
    
    UKAddress:
      description: This is used to define the address object for US which inherits postal address object and has its own properties specific to UK country.
      allOf:
        - $ref: "#/components/schemas/PostalAddress"
        - type: object
          properties:
            name:
              type: string
            postalCode:
              description: This is used to define postal code for UK address.
              type: string
            county:
              type: string
            flatNumber:
              type: string
            houseName:
              type: string
            street:
              type: string
            street2:
              type: string
            street3:
              type: string
            town:
              type: string
            pod:
              type: boolean
              default: false
            deliveryName:
              type: string
            test:
              type: string
            deliveryInstructions:
              $ref: "#/components/schemas/DeliveryInstructions"
          example:
            type: UK
            deliveryName: xcxcxxc
            postalCode: GL3 4AQ
            houseNumber: '22'
            flatNumber: ''
            address1: Hurricane Road
            address2: Unit 5, The I O Centre
            city: Gloucester
            town: sdf
            county: Gloucestershire
            country: GB
            deliveryInstructions:
              deliveryInstruction: At back door
              deliveryInstructionTxtLine1: ''
              deliveryInstructionTxtLine2: ''
              deliveryInstructionTxtLine3: ''
              deliveryInstructionTxtLine4: ''
    
    DeliveryInstructions:
      description: This is used to define delivery instructions for the order.
      type: object
      properties:
        deliveryInstruction:
          description: This is used to define delivery instructions for the order.
  
          type: string
          example: At back door
        deliveryInstructionTxt:
          type: string
          description: This is used to define delivery instructions text for the order if there is sepcial delivery instruction which is not listed in the application.
  
        deliveryInstructionTxtLine1:
          description: This is used to define delivery instructions text line 1 if delivery instruction is too long.
          type: string
        deliveryInstructionTxtLine2:
          description: This is used to define delivery instructions text line 2 if delivery instruction is too long.
          type: string
        deliveryInstructionTxtLine3:
          description: This is used to define delivery instructions text line 3 if delivery instruction is too long.
          type: string
        deliveryInstructionTxtLine4:
          description: This is used to define delivery instructions text line 4 if delivery instruction is too long.
          type: string
      required:
        - deliveryInstruction
        - deliveryInstructionTxt

  
    PostalAddress:
      description: This is used to define postal address of the user.
      type: object
      discriminator:
        propertyName: type
      required:
        - address1
        - city
        - country
        - addressType
  
      properties:
        address1:
          description: This is used to define street in the postal address.
          type: string
        address2:
          description: This is used to define address2 in the postal address.
          type: string
        address3:
          description: This is used to define address3 in the postal address.
          type: string
        city:
          description: This is used to define city in the postal address.
           
          type: string
        country:
          description: This is used to define country in the postal address.
          type: string
        addressType:
          description: This is used to define addressType in the postal address.
          type: string
          enum: [Residential , Commercial]
          example: Residential
        houseNumber:
          description: This is used to define house number in the postal address.
          type: string
        type:
          description: This is used to define type the postal address.
          type: string
          enum: [US,UK, AU ,NZ]
          example: US
      example:
        type: UK
        postalCode: 'GL3 4AQ'
        houseNumber: 22
        flatNumber: ""
        address1: 'Hurricane Road'
        address2: 'Unit 5, The I O Centre'
        city: Gloucester
        county: Gloucestershire
        country: GB
        
    PersonalInformation:
      type: object
      description: This is used to define personal information of the user.
  
      properties:
        firstName:
          description: This is used to define first name of the user.
          type: string
        lastName:
          description: This is used to define last name of the user. 
          type: string
        middleName:
          description: This is used to define middle name of the user.
          type: string
        salutation:
          description: This is used to define salution of the user.
          type: string
          example: Mr., Mrs., Ms.,Dr 
      required:
        - firstName
        - lastName
        - salutation

    ShippingAddressOptions:
      type: object
      properties:
        addressOptions:
          type: array
          items:
            $ref: '#/components/schemas/AddressOption'   
          example: [DEFAULT_ADDRESS,SAVE_TO_ADDRESS_BOOK]
    
    AddressOption:
      type: string
      enum:
       - DEFAULT_ADDRESS, SAVE_TO_ADDRESS_BOOK
      description: |
       * 'DEFAULT_ADDRESS'  - This option states that the address should be set as the default address in the address book.  The default address is used in the express checkout on the website to make it quicker for a customer to process an order.
       * 'SAVE_TO_ADDRESS_BOOK'  - This option states that the address should be saved to the address book. Both this option and "DEFAULT_ADDRESS' are not needed in case the customer wish to make the address as a default address.
