openapi: 3.0.0
info:
  title: API Pryvatex Exchange
  description: >-
    This is an example of using OAuth2 Access Code Flow in a specification to
    describe security to your API.
  version: 1.0.0
servers:
  - url: 'https://virtserver.swaggerhub.com/Demo/1.0.0'
    description: SwaggerHub API Auto Mocking
  - url: 'https://pryvatex.com/api'
    description: API of Pryvatex exchange
security:
  - accessCode:
      - read
      - write
paths:
  /order/markets/pairs:
    get:
      summary: Get all pairs
      description: Call to get all pairs suppored trade
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
              example:
                status: success
                data:
                  - pair: ETH-BTC
                    baseCurrency: BTC
                    quoteCurrency: ETH
  /order/markets/tickers:
    get:
      summary: Get all tickers
      description: Call to get all tickers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
              example:
                status: success
                data:
                  - instrument: ETH-BTC
                    price: '40'
                    best_ask: '40'
                    best_bid: '40'
                    high_24h: '40'
                    low_24h: '40'
                    open_24h: '40'
                    price_24h: '40'
                    product_id: abcabcabc
                    sequence: '0'
                    volume_24h: '0.6'
                    volume: '20'
                    precision: '8'
  '/order/trading/{instrument}':
    get:
      summary: Get all orders
      description: 'Call to get all '
      parameters:
        - name: instrument
          in: path
          description: instrument
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: ETHBTC
        - name: limit
          in: query
          description: the max length of data response
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 10
        - name: type
          in: query
          description: type of order
          required: false
          style: form
          explode: true
          schema:
            type: string
            enum:
              - limit
              - market
              - stop
        - name: side
          in: query
          description: side of order
          required: false
          style: form
          explode: true
          schema:
            type: string
            enum:
              - buy
              - sell
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
              example:
                status: success
                data:
                  - id: 5d8207be6bd9ad5b497d8791
                    instrument: ETH-BTC
                    status: open
                    type: limit
                    side: buy
                    price: 5005000000
                    size: 1000000
                    remainingSize: 1000000
                    precision: 8
                    time: 1569384084518
  '/order/tradeHistory/{instrument}':
    get:
      summary: Get all history trades
      description: 'Call to get all '
      parameters:
        - name: instrument
          in: path
          description: instrument
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: ETHBTC
        - name: limit
          in: query
          description: the max length of data response
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
              example:
                status: success
                data:
                  - id: 5d8207be6bd9ad5b497d8791
                    instrument: ETH-BTC
                    price: 5005000000
                    size: 1000000
                    precision: 8
                    time: 1569384084518
  /user/info:
    get:
      summary: Get user's info
      description: 'Get user''s info '
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
              example:
                status: success
                data:
                  - id: 5ddbb600f874fd65143b0cd8
                    email: conan_doyle@gmail.com
                    firstName: Conan
                    lastName: Doyle
                    userType: Individual
                    kycLevel: 0
                    kycStatus: complete
  /user/balances:
    get:
      summary: Get user's balances
      description: 'Get user''s balances '
      parameters:
        - name: asset
          in: query
          description: symbol of asset
          required: false
          style: form
          explode: true
          schema:
            type: string
            enum:
              - BTC
              - ETH
              - PVC
              - GBP
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_5'
              example:
                status: success
                data:
                  - name: Bitcoin
                    symbol: BTC
                    address: 1KwtpkoMtVHGM25gG5kbGrpbakLyq8KRXU
                    balance: 0
                    lockedBalance: 0
  /user/orders:
    get:
      summary: Get all user's orders
      description: 'Call to get all user''s orders '
      parameters:
        - name: instrument
          in: query
          description: instrument
          required: false
          style: form
          explode: true
          schema:
            type: string
            example: ETHBTC
        - name: limit
          in: query
          description: the max length of data response
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 10
        - name: type
          in: query
          description: type of order
          required: false
          style: form
          explode: true
          schema:
            type: string
            enum:
              - limit
              - market
              - stop
        - name: side
          in: query
          description: side of order
          required: false
          style: form
          explode: true
          schema:
            type: string
            enum:
              - buy
              - sell
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
              example:
                status: success
                data:
                  - id: 5d8207be6bd9ad5b497d8791
                    instrument: ETH-BTC
                    status: open
                    type: limit
                    side: buy
                    price: 5005000000
                    size: 1000000
                    remainingSize: 1000000
                    precision: 8
                    time: 1569384084518
  /user/trades:
    get:
      summary: Get all user's trades
      description: Call to get all user's trades
      parameters:
        - name: instrument
          in: query
          description: instrument
          required: false
          style: form
          explode: true
          schema:
            type: string
            example: ETHBTC
        - name: limit
          in: query
          description: the max length of data response
          required: false
          style: form
          explode: true
          schema:
            type: number
            default: 10
        - name: side
          in: query
          description: the side of user's order which matching
          required: false
          style: form
          explode: true
          schema:
            type: string
            enum:
              - buy
              - sell
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_6'
              example:
                status: success
                data:
                  - id: 5d8207be6bd9ad5b497d8791
                    instrument: ETH-BTC
                    makerOrderId: 5d8207be6bd9ad5b497d8792
                    takerOrderId: 5d8207be6bd9ad5b497d8793
                    price: 5005000000
                    size: 1000000
                    precision: 8
                    time: 1569384084518
  /order/create:
    post:
      summary: Create an order
      description: Call to create an order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_7'
              example:
                status: 5d8207be6bd9ad5b497d8791
  /order/cancel:
    post:
      summary: Cancel an order
      description: Call to Cancel an order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_1'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_8'
              example:
                status:
                  cancelSize: 100000
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        status:
          type: string
          description: response status
        data:
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_data'
    inline_response_200_1:
      type: object
      properties:
        status:
          type: string
          description: response status
        data:
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_1_data'
    inline_response_200_2:
      type: object
      properties:
        status:
          type: string
          description: response status
        data:
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_2_data'
    inline_response_200_3:
      type: object
      properties:
        status:
          type: string
          description: response status
        data:
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_3_data'
    inline_response_200_4:
      type: object
      properties:
        status:
          type: string
          description: response status
        data:
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_4_data'
    inline_response_200_5:
      type: object
      properties:
        status:
          type: string
          description: response status
        data:
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_5_data'
    inline_response_200_6:
      type: object
      properties:
        status:
          type: string
          description: response status
        data:
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_6_data'
    body:
      properties:
        instrument:
          type: string
          description: instrument of order
        type:
          type: string
          description: type of order
          enum:
            - market
            - limit
            - stop
        side:
          type: string
          description: side of order
          enum:
            - buy
            - sell
        size:
          type: number
          description: size of order
        price:
          type: number
          description: price of order
        stopPrice:
          type: number
          description: stop price of stop order
      example:
        instrument: ETH-BTC
        type: limit
        side: buy
        size: 0.01
        price: 46.03
    inline_response_200_7:
      type: object
      properties:
        success:
          type: string
          description: id of order
    body_1:
      properties:
        id:
          type: string
          description: id of order
      example:
        id: 5d8207be6bd9ad5b497d8791
    inline_response_200_8:
      type: object
      properties:
        success:
          type: object
          description: cancel response
    inline_response_200_data:
      type: object
      properties:
        pair:
          type: string
          description: currency pair
        baseCurrency:
          type: string
          description: base currency of pair
        quoteCurrency:
          type: string
          description: quote currency of pair
    inline_response_200_1_data:
      type: object
      properties:
        instrument:
          type: string
          description: market pair
        price:
          type: string
          description: price
        best_ask:
          type: string
          description: best ask
        best_bid:
          type: string
          description: best bid
        high_24h:
          type: string
          description: high 24h
        low_24h:
          type: string
          description: low 24h
        open_24h:
          type: string
          description: open 24h
        price_24h:
          type: string
          description: price 24h
        volume_24h:
          type: string
          description: volume 24h
        volume:
          type: string
          description: volume
        precision:
          type: string
          description: precision
        product_id:
          type: string
          description: product id
        sequence:
          type: string
          description: sequence
    inline_response_200_2_data:
      type: object
      properties:
        id:
          type: string
          description: id of order
        instrument:
          type: string
          description: instrument of order
        status:
          type: string
          description: status of order
          enum:
            - open
            - filed
            - partial_filled
            - pending
        type:
          type: string
          description: type of order
          enum:
            - limit
            - market
            - stop
        side:
          type: string
          description: side of order
          enum:
            - buy
            - sell
        price:
          type: number
          description: price of order
        size:
          type: number
          description: size of order
        remainingSize:
          type: number
          description: remaining size of order
        precision:
          type: number
          description: precision
        time:
          type: number
          description: 'unixtime order created, unit: milisecond'
    inline_response_200_3_data:
      type: object
      properties:
        id:
          type: string
          description: id of trade
        instrument:
          type: string
          description: instrument of trade
        price:
          type: number
          description: price of trade
        size:
          type: number
          description: size of trade
        precision:
          type: number
          description: precision
        time:
          type: number
          description: 'unixtime order traded, unit: milisecond'
    inline_response_200_4_data:
      type: object
      properties:
        id:
          type: string
          description: id of user
        email:
          type: string
          description: email of user using signup
        firstName:
          type: string
          description: first name of user
        lastName:
          type: string
          description: last name of user
        userType:
          type: string
          description: user type
          enum:
            - Individual
            - Institutional
        kycLevel:
          type: number
          description: kyc level of user
        kycStatus:
          type: string
          description: kyc status of user
          enum:
            - null
            - pending
            - processing
            - complete
            - error
    inline_response_200_5_data:
      type: object
      properties:
        name:
          type: string
          description: name of asset
        symbol:
          type: string
          description: symbol of asset
          enum:
            - BTC
            - ETH
            - PVC
            - GBP
        address:
          type: string
          description: address of asset
        balance:
          type: number
          description: total coin of asset
        lockedBalance:
          type: number
          description: total lock coin of asset
    inline_response_200_6_data:
      type: object
      properties:
        id:
          type: string
          description: id of trade
        instrument:
          type: string
          description: instrument of trade
        makerOrderId:
          type: string
          description: marker order id
        takerOrderId:
          type: string
          description: taker order id
        price:
          type: number
          description: price of trade
        size:
          type: number
          description: size of trade
        precision:
          type: number
          description: precision
        time:
          type: number
          description: 'unixtime order traded, unit: milisecond'
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: x-api-key
      in: header
    DigitalSignatureAuth:
      type: apiKey
      name: x-digital-signature
      in: header
