openapi: 3.0.0
info:
  version: '1.0.0-oas3'
  title: 'Ambev PO7.5 CIG Integration'
  description: |
    App da Celula de Informações GerenciaisIG calls SAP PO 7.5 Integration
    <br>
    Methods:
      <br>» GET&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Read Pre-Sale Results from SAP
      
      1.0.0-oas3 (05/04/2020): Creation
      <br>&nbsp;&nbsp;&nbsp;&nbsp;• Method GET Released
      
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Partner evt/IT
    email: contato@evtit.com
    url: http://www.evtit.com/
#  license:
#    name: Apache 2.0
#    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: 'Developer: Daniel G. Alexandre'
  url: 'mailto:daniel.dgatech@gmail.com'
servers:
- url: https://sappodev.ambevdevs.com.br/RESTAdapter
  description: SAP PO Development server (DP1) - External URL
- url: https://sappoqas.ambevdevs.com.br/RESTAdapter
  description: SAP PO Quality server (QP1) - External URL
- url: https://sappoprd.ambevdevs.com.br/RESTAdapter
  description: SAP PO Production server (PP1) - External URL
tags:
  - name: CIG
    description: Management Information Cell
paths:
  /v1/CIG/getPreSaleResults:
    get:
      tags:
      - CIG
      summary: Read CIG information from SAP
      operationId: getPreSaleResults
      description: Returns several rows with data of pre-Sales
      parameters:
        - name: dataPuxada
          in: query
          description: Date of Expedition
          required: true
          schema:
            type: string
            format: date
        - name: queryType
          in: query
          description: Type of process to be done, 1 or 2
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getPreSaleResults_res'
      security:
      - po75_auth: []
components:
  schemas:
    getPreSaleResults_res:
      type: object
      properties:
        queryResult:
          type: object
          properties:
            row:
              type: array
              items:
                type: object
                properties:
                  codCliente:
                    type: string
                  codUnbOrigem:
                    type: string
                  codProduto:
                    type: string
                  qtdeSku:
                    type: integer
                  vlrTtv2w:
                    type: number
                  dataInclusao:
                    type: string
                    format: date
                  dataPuxada:
                    type: string
                    format: date
  securitySchemes:
    po75_auth:
      type: http
      scheme: basic
    api_key:
      type: apiKey
      name: api_key
      in: header
