openapi: 3.0.2
info:
  description: | 
     # This API suite has a set operations to provide information about **Item Lists**.
     
     An **Item List** comprises a set of product items with a set of associated meta-data.
     
     The most typical use of an item-list is to allow a 'shop front' page to be constructed in a website application
     For example:-  A web-page advertising 'Christmas Hampers',  might be associated with an item-list 'christmas-hampers'
     The Item Lists would contain a list of item codes to be advertised for sale,  together with meta-data that helps with the 
     display of the list.

     *For example:-*  An Item List with the name *gifts-over-80* might define a set of
     gifts products with a value of 80 GBP _(or the appropriate local currency)_.
  version: "1.0.0"
  title: Item List API
  contact:
    email: apisupport@laithwaiteswine.com
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Direct_Wines/ItemList/1.0.0
  - description: This website  
    url: /api
paths:
  '/itemlist/{name}/{locale}/{companyCode}':
    get:
      tags:
        - Item List API Suite
      summary: Return an Item List object
      description: |
        This method returns an item list object.
      operationId: getItemlistByName
      parameters:
        - name: name
          in: path
          required: true
          example: gifts-over-80
          schema:
            type: string
            pattern: .*
        - name: locale
          in: path
          required: true
          example: en_GB_UKLAIT
          schema:
            type: string
            pattern: .*
        - name: companyCode
          in: path
          required: true
          example: UK
          schema:
            type: string
            pattern: .*
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemListResponse'
        '403':
           description: This will be returned if a points scheme is not in operation on the current site
           content: 
            application/json:
              schema:
                 $ref: 'https://api.swaggerhub.com/apis/Direct_Wines/CommonAPIModelsSuite/1.2.0#/components/schemas/CommonResponseHeader'  
        '422':
           description: A validation error occured when calling this method.  For example it may be that the supplied account Id was invalid or was unauthorized for this user. 
           content: 
            application/json:
              schema:
                 $ref: 'https://api.swaggerhub.com/apis/Direct_Wines/CommonAPIModelsSuite/1.2.0#/components/schemas/CommonResponseHeader'  
components:
  schemas:
# ==============================================================================  
#   Response Objects
# ==============================================================================  
    ItemListResponse:
      allOf:
        - $ref: 'https://api.swaggerhub.com/apis/Direct_Wines/CommonAPIModelsSuite/1.2.0#/components/schemas/ApiResponse'
        - type: object
          properties:
            response:
                $ref: '#/components/schemas/ItemList'

# ==============================================================================  
#   Data Objects/Beans
# ==============================================================================  
    ItemList:
      type: object
      description: This object defines the list of pending subscriptions that will be created by processing this cart as an order.
      properties:
        name:
          type: string
          description: |
             This name of the item list.
             
             This also doubles as the *id* of the list.
          
          example: gifts-over-80
        displayName:
          type: string
          description: | 
            A description of the item list.
            
            This normally equates to a more meaningful literal description of the list that could be used in website headline tag.
            
          example: "Gifts over £80"
        templateStyle:
          type: string
          deprecated: true
          description: | 
            An internal style that is used by the website when displaying this list.
            
            This property is deprecated and should not be used as it may be removed in a future version of the API.
            
            All meta-properties associated with an item list are now defined in the presentationMap property
            
          example: "OnePerRow-Default"
        bannerURL:
          type: string
          deprecated: true
          description: | 
            An internal html banner that is used by the website when displaying this list.
            
            This property is deprecated and should not be used as it may be removed in a future version of the API.
            
            All meta-properties associated with an item list are now defined in the presentationMap property
            
          example: "gifts2019-20/peak/listbanner.html"
        itemList:
          type: array
          description: |
             A list of product item codes that comprise the list.
             
             For each item is the list,  [the Product getItem API method](/api/product/item/{itemCode})  may be used to retrieve individual product details
             
          items: 
            type: string
          example:
          - J00092
          - M11113
          - M11114
          - 39403SI
        presentationMap:
          type: object
          description: |
             A map of key-value pairs containing meta-data associated with the item list
             
             An example might be:-
             "itemlist.title":"Gifts over £80"
             
             However the exact data dictionary of keys and values may vary from list to list as they
             defined by the item list creator.   
             
          additionalProperties:
            type: string
          example:
             itemlist.title : "Gifts over £80"
             
      required: 
      - name
      - displayName
      - itemList
