openapi: "3.0.1"
info:
  title: "wiit-7340-degrees-at-cscc-api"
  version: "2.0.0"
  description:
    Specification for the Degrees restaurant at Columbus State menu
    Application Programming Interface (API)
paths:
  /api/menu/categories:
    get:
      summary: Get a list of menu categories
      responses:
        '200':
          description: A list of zero or more menu categories
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuCategoryList'
    post:
      summary: Create a new menu category
      requestBody:
        description: a representation of the menu category to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewMenuCategory'
      responses:
        '201':
          description:
            The server created the menu category and the new menu
            category instance, represented in the response body is
            available the specified location
          headers:
            Location:
              description:
                The location of the newly created category
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SavedMenuCategory'
        '400':
          description: One or more fields, as noted in the response body, failed validation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryValidationErrors'
  /api/menu/categories/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        required: true
        description: Numeric ID of the desired menu category
    get:
      summary: Lookup a menu category by ID
      description: Get a singleton list with the specificied menu category
      responses:
        '200':
          description: The rsponse contains a singleton list containing the specificied menu category
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuCategoryList'
        '404':
          description: No menu category exists with that ID
          content: {}
        '400':
          description: The ID path parameter provided is not a valid number
          content: {}
    put:
      summary: Update a menu category by ID
      description: Update the menu category to match the representation provided in the request body
      responses:
        '204':
          description: The server successfully updated the menu category
          content: {}
        '400':
          description:
            Either the ID path parameter provided is not a valid number
            or one or more fields, as noted in the response body,
            failed validation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/CategoryValidationErrors'
                  - $ref: '#/components/schemas/EmptyObject'
        '404':
          description: No menu category exists with that ID
          content: {}
        '409':
          description: The ID in the request body does not match the ID in path parameter
          content: {}
    delete:
      summary: Remove a menu category by ID
      description: Delete the specified menu category
      responses:
        '204':
          description: The server successfully deleted the menu category
          content: {}
        '404':
          description: No menu category exists with that ID
          content: {}
        '400':
          description: The ID path parameter provided is not a valid number
          content: {}

  /api/menu/items:
    get:
      summary: Get a list of menu items
      responses:
        '200':
          description: A list of zero or more menu items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItemList'
    post:
      summary: Create a new menu item
      requestBody:
        description: a representation of the menu item to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewMenuItem'
      responses:
        '201':
          description:
            The server created the menu item and the new
            instance, represented in the response body is
            available the specified location
          headers:
            Location:
              description:
                The location of the newly created item
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SavedMenuItem'
        '400':
          description: One or more fields, as noted in the response body, failed validation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItemValidationErrors'
  /api/menu/items/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        required: true
        description: Numeric ID of the desired menu item
    get:
      summary: Lookup a menu item by ID
      description: Get a singleton list with the specificied menu item
      responses:
        '200':
          description:
            The response contains a singleton list containing
            the specificied menu item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItemList'
        '400':
          description: The ID path parameter provided is not a valid number
          content: {}
        '404':
          description: No menu item exists with that ID
          content: {}
    put:
      summary: Update a menu item by ID
      description: Update the menu item to match the representation provided in the request body
      responses:
        '204':
          description: The server successfully updated the menu item
          content: {}
        '400':
          description:
            Either the ID path parameter provided is not a valid number
            or one or more fields, as noted in the response body,
            failed validation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/MenuItemValidationErrors'
                  - $ref: '#/components/schemas/EmptyObject'
        '404':
          description: No menu item exists with that ID
          content: {}
        '409':
          description: The ID in the request body does not match the ID in path parameter
          content: {}
    delete:
      summary: Remove a menu item by ID
      description: Delete the specified menu item
      responses:
        '204':
          description: The server successfully deleted the menu item
          content: {}
        '400':
          description: The ID path parameter provided is not a valid number
          content: {}
        '404':
          description: No menu item exists with that ID
          content: {}

components:
  schemas:
    EmptyObject:
      type: object
      description: Empty {} object
    MenuCategoryList:
      type: array
      description:
        List of menu categories
      items:
        type: object
        properties:
          id:
            type: integer
            format: int64
            description: The menu category ID
          categoryTitle:
            type: string
            description: The title of this menu category
            nullable: false
            minLength: 1
            maxLength: 80
          categoryNotes:
            type: string
            description: Notes about this menu category
          sortOrder:
            type: integer
            format: int32
            description: values used to order items for display purposes
    SavedMenuCategory:
      type: object
      description: Representation of a previously saved menu category
      properties:
        id:
          type: integer
          format: int64
          description: The menu category ID
        categoryTitle:
          type: string
          description: The title of this menu category
          nullable: false
          minLength: 1
          maxLength: 80
        categoryNotes:
          type: string
          description: Notes about this menu category
        sortOrder:
          type: integer
          format: int32
          description: values used to order items for display purposes
          default: 0
    NewMenuCategory:
      type: object
      description: Shows set of fields needed to create a new menu category
      properties:
        categoryTitle:
          type: string
          description: The title of this menu category
          nullable: false
          minLength: 1
          maxLength: 80
        categoryNotes:
          type: string
          description: Notes about this menu category
        sortOrder:
          type: integer
          format: int32
          description: values used to order items for display purposes
          default: 0

    MenuItemList:
      type: array
      description:
        List of menu items
      items:
        type: object
        properties:
          id:
            type: integer
            format: int64
            description: the ID of this menu item
          menuCategory:
            type: object
            description: The category to which this menu item belongs
            nullable: false
            properties:
              id:
                type: integer
                format: int64
                description: The menu category ID
              categoryTitle:
                type: string
                description: The title of this menu category
              categoryNotes:
                type: string
                description: Notes about this menu category
              sortOrder:
                type: integer
                format: int32
                description: Values used to order items for display purposes
                default: 0
          name:
            type: string
            description: The name of this menu item
            nullable: false
            minLength: 1
            maxLength: 80
          description:
            type: string
            description: A description about this menu item
          price:
            type: string
            description: The price (or prices) of this menu item
            nullable: false
            minLength: 1
            maxLength: 20
          sortOrder:
            type: integer
            format: int32
            description: Values used to order items for display purposes
    NewMenuItem:
      type: object
      description: Shows set of fields needed to create a new menu item
      properties:
        menuCategory:
          type: object
          description: The category to which this menu item belongs
          nullable: false
          properties:
            id:
              type: integer
              format: int64
              description: The menu category ID
        name:
          type: string
          description: The name of this menu item
          nullable: false
          minLength: 1
          maxLength: 80
        description:
          type: string
          description: A description about this menu item
        price:
          type: string
          description: The price (or prices) of this menu item
          nullable: false
          minLength: 1
          maxLength: 20
        sortOrder:
          type: integer
          format: int32
          description: Values used to order items for display purposes
    SavedMenuItem:
      type: object
      description: Representation of a previously saved menu item
      properties:
        id:
          type: integer
          format: int64
          description: the ID of this menu item
        menuCategory:
          type: object
          description: The category to which this menu item belongs
          nullable: false
          properties:
            id:
              type: integer
              format: int64
              description: The menu category ID
            categoryTitle:
              type: string
              description: The title of this menu category
            categoryNotes:
              type: string
              description: Notes about this menu category
            sortOrder:
              type: integer
              format: int32
              description: Values used to order items for display purposes
              default: 0
        name:
          type: string
          description: The name of this menu item
          nullable: false
          minLength: 1
          maxLength: 80
        description:
          type: string
          description: A description about this menu item
        price:
          type: string
          description: The price (or prices) of this menu item
          nullable: false
          minLength: 1
          maxLength: 20
    CategoryValidationErrors:
      type: object
      description: Provides a list of fields with validation errors
      properties:
        fieldErrors:
          type: object
          properties:
            categoryTitle:
              type: string
              description: Validation error message for the categoryTitle field
    MenuItemValidationErrors:
      type: object
      description: Provides a list of fields with validation errors
      properties:
        fieldErrors:
          type: object
          properties:
            menuCategory:
              type: string
              description: Validation error message for the menuCategory field
            name:
              type: string
              description: Validation error message for the name field
            price:
              type: string
              description: Validation error message for the price field
