openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'MetriXFreight Data Interface'
  description: 'This is a interface that is able to consume MetriXFreight measurement posts.'
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Metrilus/MetriXFreight/1.0.0
  - description: Localhost Test Server  
    url: 'http://localhost:8080/1.0.0'

paths:
  /measurement:
    post:
      summary: Endpoint that receives MetriX measurements
      operationId: placeOrder
      responses:
        '200':
          description: Successful Operation
        '400':
          description: Invalid Request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Measurement'
        description: A JSON object which contains the measurement data
        required: true

components:
  schemas:
    Measurement:
      type: object
      properties:
        Id:
          type: string
          description: 'The unique identifier for the MetriX Measurement.'
        GateId:
          type: string
          description: 'The identifier for the MetriX Gate that produced the Measurement.'
        Timestamp:
          type: string
          format: date-time
          description: 'The timestamp (UTC) associated with the Measurement.'
        DimensioningState:
          enum:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
          type: integer
          description: "An indication of the system's stability at the time that the Measurement was produced."
        LegalForTradeHash:
          type: string
          description: 'For Legal-for-Trade measurements, an internal hash with which the             veracity of the Measurement may be verified.'
        Length:
          type: number
          format: double
          description: 'The measured length.'
        Width:
          type: number
          format: double
          description: 'The measured width.'
        Height:
          type: number
          format: double
          description: 'The measured height.'
        Weight:
          type: number
          format: double
          description: 'The measured weight, if available.'
        WeightState:
          enum:
            - 0
            - 1
            - 2
            - 3
            - 4
          type: integer
          description: 'A flag from the Weighing Scale indicating the stability of Weight data at the time that the Measurement was produced.'
        WeightReference:
          type: string
          description: 'For Legal-for-Trade measurements that include Legal-for-Trade Weight values, a reference from the Weighing Scale with which the veracity of the Weight value may be verified.'
        
        Image:
          type: string
          format: byte
          description: 'Base-64 encoded image data.'
        
        UserData:
          type: object
          properties:
            UserId:
              type: string
              description: 'The users identity (or SKU) for the measurement, typically captured                   via a barcode scanner.'
            UserLength:
              type: number
              format: double
              description: 'A length entered by a user or operator, if available.'
            UserWidth:
              type: number
              format: double
              description: 'A width entered by a user or operator, if available.'
            UserHeight:
              type: number
              format: double
              description: 'A height entered by a user or operator, if available.'
            UserWeight:
              type: number
              format: double
              description: 'A weight entered by a user or operator, if available.'
            ExtraBarcodes:
              type: array
              description: 'A collection of additionally scanned barcodes'
              items:
                type: string
            CustomFields:
              type: object
              description: 'A custom object.'
