openapi: 3.0.1
info:
  title: UBWApi
  description: Catalogue for Web API Methods
  version: "1.0"
servers:
  - url: 'https://wspubwintapi.azurewebsites.net'
paths:
  /Catalogue/CostCategoryDefaults:
    get:
      description: Get Cost Category Defaults
      responses:
        '200':
          description: '{
            "LegalEntityCode": "ALL",
            "CostCentreCode": "C10000",
            "WorkOrderCode": "AD100001-101",
            "Project": "AD100001",
            "CostCentreAttributeID": "C1",
            "ProjectAttributeID": "B0",
            "WorkOrderAttributeID": "BF",
            "LegalEntityAttributeID": "A28"
        }'
      servers:
        - url: 'https://wspubwintapi.azurewebsites.net'
    servers:
      - url: 'https://wspubwintapi.azurewebsites.net'
  /Catalogue/Employees:
    get:
      description: Get all employees from UBW
      responses:
        '200':
          description: '{"FirstName": "Jeremy",
            "Surname": "Blackwell",
            "EmployeeNumber": "210746",
            "Status": "C"
        }'
      servers:
        - url: 'https://wspubwintapi.azurewebsites.net'
    servers:
      - url: 'https://wspubwintapi.azurewebsites.net'
  /Catalogue/GLCodes:
    get:
      description: Gets all GL Codes
      responses:
        '200':
          description: '{"Account": "105060",
            "AccountDescription": "Prepaid Workers Compensation Insurance",
            "Status": "N"}'
      servers:
        - url: 'https://wspubwintapi.azurewebsites.net'
    servers:
      - url: 'https://wspubwintapi.azurewebsites.net'
  /Catalogue/InvoicesAll:
    get:
      description: Gets all Invoice(s) from method(s) /InvoicesPaid, /InvoicesPosted & /InvoicesRegistered. <br><br> <u>URL</u><br>http://wspubwintapi.azurewebsites.net/Catalogue/InvoicesAll?$filter=InvoiceNo eq '1920' and SupplierNo eq 'ADS101670'&$orderby=InvoiceNo, SupplierNo
      parameters:
        - name: $filter
          in: query
          schema:
            type: string
          example: InvoiceNo eq '1920'      
      responses:
        '200':
          description: '    {
          "Type": "PostedInvoices",
          "ID": "4286",
          "InvoiceNo": "1920",
          "SupplierNo": "ADS101670",
          "Currency": "AUD",
          "TransactionCurrencyAmount": "-5574.800",
          "TransactionCompanyAmount": "-5574.800",
          "TransactionNo": "22000016",
          "SequenceNo": "3",
          "EmployeeResponsibleOnInvoice": "",
          "TransactionType": "PI"
        },
        {
          "Type": "PaidInvocies",
          "ID": "286",
          "InvoiceNo": "1920",
          "SupplierNo": "ADS101670",
          "Currency": "AUD",
          "TransactionCurrencyAmount": "-5574.800",
          "TransactionCompanyAmount": "-5574.800",
          "TransactionNo": "22000004",
          "SequenceNo": "3",
          "EmployeeResponsibleOnInvoice": "",
          "TransactionType": "PI"
        }'
      servers:
        - url: 'https://wspubwintapi.azurewebsites.net'
    servers:
      - url: 'https://wspubwintapi.azurewebsites.net'    
  /Catalogue/InvoicesPaid:
    get:
      description: Gets all Invoice Paid
      responses:
        '200':
          description: '{"InvoiceNo": "307",
            "SupplierNo": "AIC100008",
            "Currency": "AUD",
            "TransactionCurrencyAmount": "-0.780",
            "TransactionCompanyAmount": "-0.780",
            "TransactionNo": "22000000",
            "SequenceNo": "3",
            "EmployeeResponsibleOnInvoice": "",
            "TransactionType": "PI"}'
      servers:
        - url: 'https://wspubwintapi.azurewebsites.net'
    servers:
      - url: 'https://wspubwintapi.azurewebsites.net'
  /Catalogue/InvoicesPosted:
    get:
      description: Gets all Posted Invoices
      responses:
        '200':
          description: '{"InvoiceNo": "1.77VICTORIA10JAN17",
            "SupplierNo": "ADS101382",
            "Currency": "AUD",
            "TransactionCurrencyAmount": "-22659.980",
            "TransactionCompanyAmount": "-22659.980",
            "TransactionNo": "22000017",
            "SequenceNo": "0",
            "EmployeeResponsibleOnInvoice": "",
            "TransactionType": "PI"}'
      servers:
        - url: 'https://wspubwintapi.azurewebsites.net'
    servers:
      - url: 'https://wspubwintapi.azurewebsites.net'
  /Catalogue/InvoicesRegistered:
    get:
      tags: []
      description: Gets all registered invoices
      responses:
        '200':
          description: '{"InvoiceNo": "L870761",
            "SupplierNo": "ADS100045",
            "Currency": "AUD",
            "TransactionCurrencyAmount": "-1766.160",
            "TransactionCompanyAmount": "-1766.160",
            "TransactionNo": "21044016",
            "SequenceNo": "0",
            "EmployeeResponsibleOnInvoice": "218187",
            "AccountType": "AP"
        }'
      servers:
        - url: 'https://wspubwintapi.azurewebsites.net'
    servers:
      - url: 'https://wspubwintapi.azurewebsites.net'
  /Catalogue/LegalEntity:
    get:
      description: Gets all Legal Entity
      responses:
        '200':
          description: '{"LegalEntityCode": "101",
      "LegalEntity": "WSP Australia",
      "ABN": "80 078 004 798",
      "AddressNoStreet": "Level 27, Ernst & Young Centre          680 George Street",
      "AddressCountryCode": "AU",
      "City": "Sydney",
      "State": "NSW",
      "PostCode": "2001           ",
      "OCRLegalEntityKeyword": "WSP"
       }'
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'https://wspubwintapi.azurewebsites.net'
    servers:
      - url: 'https://wspubwintapi.azurewebsites.net'
  /Catalogue/POHeaders:
    get:
      description: Gets all Purchase Order Headers
      responses:
        '200':
          description: '{"PurchaseOrder": "30000000",
            "PrintStatus": 1,
            "Status": "F",
            "WorkFlowState": "T",
            "SupplierNo": "ADS100624"}'
      servers:
        - url: 'https://wspubwintapi.azurewebsites.net'
    servers:
      - url: 'https://wspubwintapi.azurewebsites.net'
  /Catalogue/POLineItems:
    get:
      description: Gets all Purchase Order Line Items
      responses:
        '200':
          description: '{
          "Company": "AU",
          "PurchaseOrder": "30000027",
          "PurchaseOrderLineNo": 2,
          "Status": "C",
          "PurchaseOrderQuantity": "1.000",
          "PurchaseOrderPrice": "13.640",
          "TransactionCurrencyAmount": "13.640",
          "TaxTransactionCurrencyAmount": "1.360",
          "TaxCode": "A1",
          "ProductCode": "0035",
          "POLineDescription": "Freight",
          "POAmountAUD": "13.640",
          "Currency": "AUD",
          "MatchedTotalPerLine": null,
          "MatchedQuantityPerLine": null
    }'
      servers:
        - url: 'https://wspubwintapi.azurewebsites.net'
    servers:
      - url: 'https://wspubwintapi.azurewebsites.net'
  /Catalogue/ReceiptDetailsList:
    get:
      description: Gets all Receipt Details
      responses:
        '200':
          description: '{
          "Company": "AU",
          "PurchaseOrder": "30000006",
          "PurchaseOrderLineNo": 1,
          "ReceiptNumber": "60000002",
          "QuantityReceipted": "720.00000000",
          "PurchaseOrderPrice": "45.00000000",
          "TransactionCurrencyAmount": "32400.000",
          "MatchedTotalPerLine": "32400.000",
          "MatchedQuantityPerReceipt": "720.00000000"
        }'
      servers:
        - url: 'http://wspubwintapi.azurewebsites.net'
    servers:
      - url: 'http://wspubwintapi.azurewebsites.net'      
  /Catalogue/Suppliers:
    get:
      description: Gets all the suppliers <br><br> <u>URL</u><br>http://wspubwintapi.azurewebsites.net/Catalogue/Suppliers?$select=SupplierNo,SupplierName ,SupplierGroupCode ,SupplierGroupText ,SupplierStatus ,ABN ,PurchaseOrderRequiredText ,CountryCode ,OCRInvoiceLine ,PR_BankAccount ,PayRecipient ,PR_ABN ,PR_BSB ,PR_Status
      responses:
        '200':
          description: '{
          "SupplierNo": "ADS100173",
          "SupplierName": "Orix Australia Corporation Ltd",
          "SupplierGroupCode": "DS",
          "SupplierGroupText": "Domestic Suppliers",
          "BSB": "033000      ",
          "BankAccount": "216443         ",
          "SupplierStatus": "Active",
          "ABN": "79002992681",
          "PurchaseOrderRequiredText": "Yes",
          "CountryCode": "AU",
          "OCRInvoiceLine": null,
          "PR_BankAccount": null,
          "PayRecipient": null,
          "PR_ABN": null,
          "PR_BSB": null,
          "PR_Status": null
        }'
      servers:
        - url: 'https://wspubwintapi.azurewebsites.net'
    servers:
      - url: 'https://wspubwintapi.azurewebsites.net'
  /Catalogue/Suppliers_FilterbySupplierNo_NONCRITICAL:
    get:
      description: Gets non-crticial supplier information  <br><br> <u>URL</u><br>http://wspubwintapi.azurewebsites.net/Catalogue/Suppliers?$select=SupplierNo,SupplierName
                  ,SupplierGroupCode
                  ,SupplierGroupText
                  ,SupplierStatus
                  ,ABN
                  ,PurchaseOrderRequiredText
                  ,CountryCode
                  ,OCRInvoiceLine
                  ,PR_BankAccount
                  ,PayRecipient
                  ,PR_ABN
                  ,PR_BSB
                  ,PR_Status&$filter=SupplierNo eq 'ADS100173'
      responses:
        '200':
          description: '{
          "SupplierNo": "ADS100173",
          "SupplierName": "Orix Australia Corporation Ltd",
          "SupplierGroupCode": "DS",
          "SupplierGroupText": "Domestic Suppliers",
          "SupplierStatus": "Active",
          "ABN": "79002992681",
          "PurchaseOrderRequiredText": "Yes",
          "CountryCode": "AU",
          "OCRInvoiceLine": null,
          "PR_BankAccount": null,
          "PayRecipient": null,
          "PR_ABN": null,
          "PR_BSB": null,
          "PR_Status": null
        }'
      servers:
        - url: 'https://wspubwintapi.azurewebsites.net'
    servers:
      - url: 'https://wspubwintapi.azurewebsites.net'
  /Catalogue/Suppliers_FilterbySupplierNo_CRITICAL:
    get:
      description: Gets crticial supplier information <br><br> <u>URL</u><br>http://wspubwintapi.azurewebsites.net/Catalogue/Suppliers?$select=SupplierNo,SupplierName,BSB,BankAccount&$filter=SupplierNo eq 'ADS100173'
      responses:
        '200':
          description: '{
            "SupplierNo": "ADS100173",
            "SupplierName": "Orix Australia Corporation Ltd",
            "BSB": "033000",
            "BankAccount": "216443"
          }'
      servers:
        - url: 'https://wspubwintapi.azurewebsites.net'
    servers:
      - url: 'https://wspubwintapi.azurewebsites.net'      
  /Catalogue/SupplierInvoices:
    get:
      description: Gets last top 10 posted Suppler Invoices ingested by ABBYY, ordred by [CreatedDate] Descending
      responses:
        '200':
          description: '{
                "InvoiceNo": "854063",
                "InvoiceDate": "2019-06-04T00:00:00",
                "PONumber": null,
                "SupplierID": "ADS100058",
                "SupplierName": "Air-Met Scientific Pty Ltd",
                "SupplierPayRecipient": null,
                "ABN": "73006849949",
                "Bank_BSB": "033112",
                "Bank_AccountNumber": "189283",
                "EmployeeID": "214669",
                "ResponsiblePerson": "Allan Richardson",
                "ReceiptNumber": null,
                "LegalEntityCode": "101",
                "LegalEntityName": "WSP Australia",
                "Currency": "AUD",
                "TotalExGST": "99.3800",
                "TotalIncGST": "109.3200",
                "GST": "9.9400",
                "InvoiceFileName": "Invoice 854063.pdf",
                "InvoiceFile": <<BINARY DATA>>,
                "ABBYBatchID": "5",
                "ABBYOperatorComment": null,
                "ABBYValidationDate": "2019-07-16T03:03:40",
                "CreatedBy": "svcabbyyservice"
          }'
      servers:
        - url: 'https://wspubwintapi.azurewebsites.net'
    servers:
      - url: 'https://wspubwintapi.azurewebsites.net'
  /Catalogue/SupplierInvoices_FilterBySupplierIdInvoiceNo| :
    get:
      description: Gets Supplier Invoices based on SupplierID and Invoice No.<br><br> <u>URL</u><br> http://wspubwintapi.azurewebsites.net/Catalogue/SupplierInvoices?$expand=SupplierInvoiceDetails&$filter=InvoiceNo eq '00180861' and SupplierID eq 'ADS100242'
      parameters:
        - name: $filter
          in: query
          schema:
            type: string
          example: InvoiceNo eq '00180861' and SupplierID eq 'ADS100242'
      responses:
        '200':
          description: '{
        "SupplierInvoiceDetails": [
        {
          "LineItemNumber": "1",
          "Product": null,
          "Description": "Supply of cleaned and evacuated canister with soil gas 200ml/min sampling train  Supply of cleaned and certified duplicate sampling “T” Piece",
          "TaxCode": "A1",
          "Price": "0",
          "Amount": "560.0000",
          "GST": "56.0000",
          "NetAmount": "616.0000",
          "WorkOrder": "AD100001-101",
          "ProjectNo": "AD100001",
          "CostCentre": "C10000",
          "GLAccount": "200022"
        },
        {
          "LineItemNumber": "2",
          "Product": null,
          "Description": "Supply of carbon tube",
          "TaxCode": "A1",
          "Price": "0",
          "Amount": "10.0000",
          "GST": "1.0000",
          "NetAmount": "11.0000",
          "WorkOrder": "AD100001-101",
          "ProjectNo": "AD100001",
          "CostCentre": "C10000",
          "GLAccount": "200022"
        },
        {
          "LineItemNumber": "3",
          "Product": null,
          "Description": "Supply of teflon tubing @ $20m Supply of 10m tygon tubing",
          "TaxCode": "A1",
          "Price": "0",
          "Amount": "10.0000",
          "GST": "1.0000",
          "NetAmount": "11.0000",
          "WorkOrder": "AD100001-101",
          "ProjectNo": "AD100001",
          "CostCentre": "C10000",
          "GLAccount": "200022"
        }
      ],
      "InvoiceNo": "00180861",
      "InvoiceDate": "2019-01-30T00:00:00",
      "PONumber": "",
      "SupplierID": "ADS100242",
      "SupplierName": "SGS Australia Pty Ltd",
      "SupplierPayRecipient": "SUPPAYREC",
      "ABN": "44000964278",
      "Bank_BSB": "242000",
      "Bank_AccountNumber": "233413011",
      "EmployeeID": "218672",
      "ResponsiblePerson": "Adam Gray",
      "ReceiptNumber": null,
      "LegalEntityCode": "101",
      "LegalEntityName": "WSP Australia",
      "Currency": "AUD",
      "TotalExGST": "580.0000",
      "TotalIncGST": "638.0000",
      "GST": "58.0000",
      "InvoiceFileName": "INV-LC00180861.pdf",
      "InvoiceFile": <<BINARY DATA>>,
      "ABBYBatchID": "6",
      "ABBYOperatorComment": null,
      "ABBYValidationDate": "2019-07-16T03:58:44",
      "CreatedBy": "svcabbyyservice"
    }'
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'https://wspubwintapi.azurewebsites.net'
    servers:
      - url: 'https://wspubwintapi.azurewebsites.net'
  /Catalogue/SupplierInvoices_POST :
    post:
      description: URL - https://wspubwintapi.azurewebsites.net/Catalogue/SupplierInvoices
      responses:
        '200':
          description: '<b><u>Mandatory Fields</u></b>
          <p>SupplierInvoice.LegalEntityCode, SupplierInvoice.LegalEntityName, SupplierInvoice.EmployeeID, SupplierInvoice.ResponsiblePerson, SupplierInvoice.SupplierID, SupplierInvoice.InvoiceDate, SupplierInvoice.InvoiceNo, SupplierInvoice.Currency, SupplierInvoice.TotalExGST, SupplierInvoice.TotalIncGST, SupplierInvoice.GST, SupplierInvoice.InvoiceFileName, SupplierInvoice.InvoiceFile, SupplierInvoiceDetails.LineItemNumber, SupplierInvoiceDetails.Description, SupplierInvoiceDetails.Amount, SupplierInvoiceDetails.NetAmount, SupplierInvoiceDetails.GST,
            SupplierInvoiceDetails.TaxCode</p>
            
            <p><b><u>Conditionally Mandatory Fields</u></b>
            <p><u>For Non-PO invoices:</u>
            <ul>
              <li>SupplierInvoiceDetails.WorkOrder</li>
              <li>SupplierInvoiceDetails.ProjectNo</li>
              <li>SupplierInvoiceDetails.CostCentre</li>
              <li>SupplierInvoiceDetails.GLAccount</li>
            </ul>
            </p>
        
        JSON Object: <br>
        {
      "SupplierInvoiceDetails": [
        {
          "LineItemNumber": "1",
          "Product": null,
          "Description": "Supply of cleaned and evacuated canister with soil gas 200ml/min sampling train  Supply of cleaned and certified duplicate sampling “T” Piece",
          "TaxCode": "A1",
          "Price": "0",
          "Amount": "560.0000",
          "GST": "56.0000",
          "NetAmount": "616.0000",
          "WorkOrder": "AD100001-101",
          "ProjectNo": "AD100001",
          "CostCentre": "C10000",
          "GLAccount": "200022"
        },
        {
          "LineItemNumber": "2",
          "Product": null,
          "Description": "Supply of carbon tube",
          "TaxCode": "A1",
          "Price": "0",
          "Amount": "10.0000",
          "GST": "1.0000",
          "NetAmount": "11.0000",
          "WorkOrder": "AD100001-101",
          "ProjectNo": "AD100001",
          "CostCentre": "C10000",
          "GLAccount": "200022"
        }
      ],
      "InvoiceNo": "NM20190801",
      "InvoiceDate": "2019-07-12T00:00:00",
      "PONumber": "PONUM123",
      "SupplierID": "ADS100268",
      "SupplierName": "Sydney Water Corporation",
      "SupplierPayRecipient": "SUP001PayRecipient",
      "ABN": null,
      "Bank_BSB": null,
      "Bank_AccountNumber": "061-02020",
      "EmployeeID": "123456",
      "ResponsiblePerson": "Nice Person",
      "ReceiptNumber": null,
      "LegalEntityCode": "LECode",
      "LegalEntityName": "WSP - Australia",
      "Currency": "AUD",
      "TotalExGST": "100.0000",
      "TotalIncGST": "100.0000",
      "GST": "10.0000",
      "InvoiceFileName": "Testing.pdf",
      "InvoiceFile": "<<BINARY DATA>>",
      "ABBYBatchID": "D74BD22D-A847-4E38-A9D3-95E328041C3B",
      "ABBYOperatorComment": "Testing",
      "ABBYValidationDate": "2019-01-01T00:00:00",
      "CreatedBy": "NM"
    }'
      servers:
        - url: 'https://wspubwintapi.azurewebsites.net'
    servers:
      - url: 'https://wspubwintapi.azurewebsites.net'
components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
