openapi: 3.0.1
info:
  title: TaggingAPI
  description: API for tagging system management
  version: '1.0.0-oas3'
servers:
  - url: 'https://apim-analytics-dev-northeurope.azure-api.net'
paths:
  /Inference:
    put:
      tags:
        - Classification
      summary: Inference.
      description: Sets tags for given product and modelId
      operationId: inference
      parameters:
        - name: modelId
          in: query
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Successfully tagged given product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
        '400':
          description: Invalid Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
components:
  schemas:
    Tag:
      type: object
      properties:
        name:
          type: string
        certainity:
          type: integer
        attributes:
          type: array
          items:
            type: string
      example:
        name: string
        certainity: 0
        attributes:
          - string
    Result:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        tag:
          type: object
          properties:
            name:
              type: string
            certainity:
              type: integer
            attributes:
              type: array
              items:
                type: string
      example:
        code: 1
        message: OK
        tag:
          name: Spodnie
          certainity: 100
          attributes:
            - first
            - second
            - last
    ErrorResult:
      type: object
      properties:
        code:
          type: integer
        description:
          type: string
    Product:
      type: object
      properties:
        guid:
          type: string
        paths:
          type: array
          items:
            type: string
        urls:
          type: array
          items:
            type: string
        image:
          type: object
