openapi: 3.0.0
info:
  description: >-
    REST API para la obtencion de datos de ubicacion actual de unidades de
    Boltrack SRL.
  version: "0.5.1-oas3"
  title: API de Ubicacion en Tiempo Real - Boltrack SRL
  contact:
    email: lcarrasco@boltrack.com.bo
tags:
  - name: integraciones
    description: Endpoints para obtener datos de unidades en tiempo real
paths:
  '/ultimaubicacion/{id_unidad}':
    get:
      tags:
        - integraciones
      summary: Endpoint para obtener datos por unidad
      operationId: ultimaubicacion
      description: >
        El retraso de la información que devuelve este endpoint es dependiente
        de la conexion GPRS del equipo de rastreo satelital instalado en la
        unidad. 
      parameters:
        - in: path
          name: id_unidad
          description: Identificador de la unidad que se desea encontrar su ubicacion
          required: true
          schema:
            type: string
        - in: header
          name: token
          description: >-
            Token provisto por Boltrack SRL para permitir acceso a datos de la
            unidad.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Datos de la unidad correspondiente
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/datosUbicacion'
                example:
                  id: SCZ01-1465XKT
                  fecha: '2020-02-04T20:48:36.331Z'
                  latitud: -17.653254
                  longitud: -65.871814
        '400':
          description: Parametros erroneos o faltantes.
  /unidades:
    get:
      tags:
        - integraciones
      summary: Endpoint para obtener la lista de unidades habilitadas al Token
      operationId: unidades
      description: |
        Se retorna la lista de unidades habilitadas para el Token provisto.. 
      parameters:
        - in: header
          name: token
          description: >-
            Token provisto por Boltrack SRL para permitir acceso a datos de las
            unidades.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Listado de unidades correspondientes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                  - SCZ01-1465XKT
                  - SCZ02-756ERF
        '400':
          description: Parametros erroneos o faltantes.
servers:
  - url: 'https://gestiondeflota.boltrack.net/integracionapi/'
components:
  schemas:
    datosUbicacion:
      type: object
      required:
        - id_unidad
        - fecha
        - latitud
        - longitud
      properties:
        id_unidad:
          type: string
          example: SCZ01-1465XKT
        fecha:
          type: string
          format: date-time
          example: '2020-02-04T20:48:36.331Z'
        latitud:
          type: number
          format: double
          example: -17.653254
        longitud:
          type: number
          format: double
          example: -65.871814
