openapi: 3.0.1
info:
  title: FS Happy Go Pay API - APP
  description: |
    1. 呼叫任何API時，都需於Header:Authorization帶入Token. 
    2. 當第一次呼叫API或Token效期結束時，需呼叫apiLoginPost取得Token。
  contact:
    name: Foya3600(交易處理部)
    url: 'http://www.foyatech.com/'
    email: foya3600@foyatech.com
  license:
    name: Powered By Foyatech(豐揚科技)
    url: 'http://www.foyatech.com/'
  version: "0.0.9"
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://uat.foyatech.com/FS.HGP
  - url: /FS.HGP

paths:
  /api/Login:
    post:
      tags:
        - System
      summary: 登入認證
      description: '使用帳號密碼登入認證以取得交易Token'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginReq'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginRsp'
        '400':
          description: 檢核錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
        '401':
          description: 未登入或無權限
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
        '550':
          description: 550 系統錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
  /api/MemberApply:
    post:
      tags:
        - Member
      summary: '認證發卡及綁定 OtherCard 卡服務'
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemberApplyReq'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberApplyRsp'
        '400':
          description: 檢核錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
        '401':
          description: 未登入或無權限
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
        '550':
          description: 550 系統錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'             
                
  /api/MemberRenew:
    post:
      tags:
        - Member
      summary: 停用取得新HGP ID
      description: '取得新 HGPID(停用後重啟情境)'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemberRenewReq'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberRenewRsp'
        '400':
          description: 檢核錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
        '401':
          description: 未登入或無權限
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
        '550':
          description: 550 系統錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
                
  /api/Point:
    get:
      tags:
        - Member
      summary: '查詢限時點數餘額'
      description: ''
      parameters:
        - name: LoyaltyId
          in: query
          description: HAPPY GO 卡號
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HGPointRsp'
        '400':
          description: 檢核錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
        '401':
          description: 未登入或無權限
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
        '550':
          description: 550 系統錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'                    
                
  /api/AccumPoint:
    post:
      tags:
        - Accumulated
      summary: 'Happy Go Point累點'
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccumPointReq'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccumPointRsp'
        '400':
          description: 檢核錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
        '401':
          description: 未登入或無權限
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
        '550':
          description: 550 系統錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
                
  /api/AccumPoint/{TransactionId}:
    put:
      tags:
        - Accumulated
      summary: 'Happy Go Point累點返還'
      description: '返還點數不可大於原始交易贈予之點數'
      parameters:
        - name: TransactionId
          in: path
          description: 交易編號
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefundPointReq'            
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/void'
        '400':
          description: 檢核錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
        '401':
          description: 未登入或無權限
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
        '550':
          description: 550 系統錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'               

  /api/GetHomePageUrl:
    post:
      tags:
        - AppAdaptor
      summary: '取得Happy Go Pay首頁URL'
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HomePageUrlReq'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HomePageUrlRsp'
        '400':
          description: 檢核錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
        '401':
          description: 未登入或無權限
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
        '550':
          description: 550 系統錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
  /api/GetTransPageUrl:
    post:
      tags:
        - AppAdaptor
      summary: '取得Happy Go Pay交易頁URL'
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransPageUrlReq'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransPageUrlRsp'
        '400':
          description: 檢核錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
        '401':
          description: 未登入或無權限
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
        '550':
          description: 550 系統錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'             
                
  /api/GetAuthenticatePageUrl:
    post:
      tags:
        - AppAdaptor
      summary: '取得支付密碼驗證頁面'
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticatePageUrlReq'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticatePageUrlRsp'
        '400':
          description: 檢核錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
        '401':
          description: 未登入或無權限
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
        '550':
          description: 550 系統錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusCode'
components:
  schemas:
    void:
      type: object
    statusCode:
      type: object
      properties:
        ErrCode:
          type: string
          description: 錯誤代碼
        ErrMsg:
          type: string
          description: 錯誤訊息說明

    LoginReq:
      required:
        - UserId
        - Password
      type: object
      properties:
        UserId:
          type: string
          description: 登入者
          maxLength: 20
        Password:
          type: string
          description: 密碼
          maxLength: 64
    LoginRsp:
      type: object
      properties:
        Token:
          type: string
          description: 金鑰
          maxLength: 2000
        ExpireTime:
          type: string
          description: Token到期時間
          format: 'yyyyMMddHHmmss'
          maxLength: 14
          
          
    MemberApplyReq:
      required:
        - Mobile
        - Idno
        - Name
        - Birthday
        - Email
      type: object
      properties:
        Idno:
          type: string
          description: 身份證號
          maxLength: 10
        Name:
          type: string
          description: 姓名
          maxLength: 50
        Birthday:
          type: string
          description: 生日
          maxLength: 10
          format: yyyy-MM-dd
          example: '1980-01-23'
        Mobile:
          type: string
          description: 行動電話
          maxLength: 64
          example: '0912345678'
        Email:
          type: string
          description: 電子信箱
          maxLength: 128
          example: 'abc@ddim.com.tw'
        Address:
          type: string
          description: 地址
          maxLength: 128
          example: '新北市板橋區新站路 16 號'
          
    MemberApplyRsp:
      type: object
      properties:
        LoyaltyId:
          type: string
          description: HAPPY GO 卡號
        HgpId:
          type: string
          description: HAPPY GO PAY 會員代號

    MemberRenewReq:
      required:
        - Idno
        - Birthday
        - Mobile        
      type: object
      properties:
        Idno:
          type: string
          description: 身份證號
          maxLength: 10
        Birthday:
          type: string
          description: 生日
          maxLength: 10
          format: yyyy-MM-dd
          example: '1980-01-23'
        Mobile:
          type: string
          description: 行動電話
          maxLength: 64
          example: '0912345678'
          
    MemberRenewRsp:
      type: object
      properties:
        LoyaltyId:
          type: string
          description: HAPPY GO 卡號
        HgpId:
          type: string
          description: HAPPY GO PAY 會員代號
          
    HGPointRsp:
      type: object
      properties:
        Name:
          type: string
          description: 姓名(主卡人姓名)(隱碼)
          maxLength: 20
        BalanceAmount:
          type: integer
          description: 累計目前總點數
          maxLength: 11
        BalanceBefore:
          type: integer
          description: 前一年度累積餘額
          maxLength: 11
        BalanceExpire:
          type: string
          description: 前一年累積點數之有效日期
          maxLength: 20
          example: '20181231'
        BalanceBefore30:
          type: integer
          description: 最近 30 日內到期之點數餘額
          maxLength: 11                  
          
    AccumPointReq:
      required:
        - OrderId
        - LoyaltyId
        - Point
      type: object
      properties:
        OrderId:
          type: string
          description: 累點訂單編號。
          maxLength: 64
          example: '20200123143023-001'      
        HgpId:
          type: string
          description: HAPPY GO PAY 會員代號
          maxLength: 64
        Point:
          type: integer
          description: 回饋點數(正整數)
          maxLength: 10
          
    RefundPointReq:
      required:
        - LoyaltyId
        - Point
      type: object
      properties:
        HgpId:
          type: string
          description: HAPPY GO PAY 會員代號
          maxLength: 64
        Point:
          type: integer
          description: 返還點數(正整數)
          maxLength: 10                   
          
    AccumPointRsp:
      type: object
      properties:
        TransactionId:
          type: string
          description: 系統產生之交易編號
          maxLength: 64  
        OrderId:
          type: string
          description: 累點訂單編號
          maxLength: 64
          example: '20200123143023-001'      

    HomePageUrlReq:
      required:
        - HgpId
        - AppUdid
        - AppVersion
        - Timestamp
      type: object
      properties:
        HgpId:
          type: string
          description: HAPPY GO PAY 會員代號
          maxLength: 64
        AppUdid:
          type: string
          description: 手機識別碼
          maxLength: 40
          example: 'testUdid'
        AppVersion:
          type: string
          description: APP版本
          maxLength: 50
          example: 'v1'
        AuthenticateKey:
          type: string
          description: |
            '支付密碼識別值(若有開啟生物辨識，則此欄位為必要欄位)'
          maxLength: 1024          
        IsSupBiometric:
          type: string
          description: |
            '是否支援生物辨識(1支援、 0:不支援)'
          maxLength: 1
        Timestamp:
          type: string
          description: 交易時間
          format: 'yyyyMMddHHmmss'
          maxLength: 14
          example: '20200210170504'
          
    HomePageUrlRsp:
      type: object
      properties:
        WebviewUrl:
          type: string
          description: WebView Page URL
          maxLength: 1024
        ExpiredTime:
          type: string
          description: URL有效期限
          maxLength: 14
          format: 'yyyyMMddHHmmss'
          example: '20200210170504'
        Timestamp:
          type: string
          description: 交易時間
          format: 'yyyyMMddHHmmss'
          maxLength: 14
          example: '20200210170504'          
          
    TransPageUrlReq:
      required:
        - HgpId
        - AppUdid
        - AppVersion
        - DataInfo
        - Timestamp
      type: object
      properties:
        HgpId:
          type: string
          description: HAPPY GO PAY 會員代號
          maxLength: 64
        AppUdid:
          type: string
          description: 手機識別碼
          maxLength: 40
          example: 'testUdid'
        AppVersion:
          type: string
          description: APP版本
          maxLength: 50
          example: 'v1'
        DataInfo:
          type: string
          description: 特店交易資料
          maxLength: 4096
          example: '{"Amt":"100"}'
        AuthenticateKey:
          type: string
          description: |
            '支付密碼識別值(若有開啟生物辨識，則此欄位為必要欄位)'
          maxLength: 1024          
        IsSupBiometric:
          type: string
          description: |
            '是否支援生物辨識(1支援、 0:不支援)'
          maxLength: 1
        Timestamp:
          type: string
          description: 交易時間
          format: 'yyyyMMddHHmmss'
          maxLength: 14
          example: '20200210170504'
          
    TransPageUrlRsp:
      type: object
      properties:
        WebviewUrl:
          type: string
          description: WebView Page URL
          maxLength: 1024
        ExpiredTime:
          type: string
          description: URL有效期限
          maxLength: 14
          format: 'yyyyMMddHHmmss'
          example: '20200210170504'
        Timestamp:
          type: string
          description: 交易時間
          format: 'yyyyMMddHHmmss'
          maxLength: 14
          example: '20200210170504'                 
          
    AuthenticatePageUrlReq:
      required:
        - HgpId
        - AppUdid
        - AppVersion
        - Timestamp
      type: object
      properties:
        HgpId:
          type: string
          description: HAPPY GO PAY 會員代號
          maxLength: 64
        AppUdid:
          type: string
          description: 手機識別碼
          maxLength: 40
          example: 'testUdid'
        AppVersion:
          type: string
          description: APP版本
          maxLength: 50
          example: 'v1'
        Timestamp:
          type: string
          description: 交易時間
          format: 'yyyyMMddHHmmss'
          maxLength: 14
          example: '20200210170504'
          
    AuthenticatePageUrlRsp:
      type: object
      properties:
        WebviewUrl:
          type: string
          description: WebView Page URL
          maxLength: 1024
        Timestamp:
          type: string
          description: 交易時間
          format: 'yyyyMMddHHmmss'
          maxLength: 14
          example: '20200210170504'               
        ExpiredTime:
          type: string
          description: URL有效期限
          maxLength: 14
          format: 'yyyyMMddHHmmss'
          example: '20200210170504'          
          
    
tags:
  - name: System
    description: 系統服務
  - name: Member
    description: Happy Go Pay 會員申裝異動服務
  - name: Accumulated
    description: Happy Go Point服務
  - name: AppAdaptor
    description: Happy Go Pay App介接服務
