openapi: "3.0.1"
info:
  title: "api.goldenscent.com"
  version: "private"
servers:
- url: "https://api.goldenscent.com/prod"
paths:
  /shipment/track:
    get:
      tags: 
      - Shipment
      parameters:
      - name: "mobile_number"
        in: "query"
        required: true
        example: "+966530212011"
        schema:
          type: "string"
      - name: "order_number"
        in: "query"
        required: true
        example: "201196151"
        schema:
          type: "string"
      responses:
        200:
          description: "200 response"
  /callcenter/get-order-id-by-telephone:
    get:
      tags: 
      - Order
      parameters:
      - name: "telephone"
        in: "query"
        required: true
        example: "+966530212011"
        schema:
          type: "string"
      responses:
        200:
          description: "200 response"

          
  /callcenter/verify-order:
    post:
      tags: 
      - Order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Verify'
      responses:
        200:
          description: "200 response"

  /stockbroker/qty:
    get:
      tags: 
      - Stock
      parameters:
      - name: "sku"
        in: "query"
        required: true
        example: "3700839900119,3614272050358"
        schema:
          type: "string"
      - name: "storeGroupId"
        in: "query"
        required: true
        example: "1"
        schema:
          type: "string"
      responses:
        200:
          description: "200 response"
          
components:
  schemas:
    Verify:
      title: "Order verification"
      type: "object"
      properties:
        order_id:
          type: "string"
          example: "201196151"
        verify:
          type: "boolean"
          enum:
           - 1
           - 0
          example: "1"
  securitySchemes:
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"
