openapi: 3.0.1
info:
  title: Inovyo
  description: Plataforma de Customer Experience
  termsOfService: https://www.inovyo.com/termos-de-uso-e-condicoes-gerais/
  contact:
    email: admin@inovyo.com
  version: 1.0.0
servers:
- url: https://api.inovyo.com/{nome-do-cliente}/v1
  variables:
    "nome-do-cliente":
      default: demo
paths:
  /contact:
    get:
      tags:
      - contact
      summary: Consumir dados dos contatos baseado em um status
      operationId: getContactsBasedOnStatus
      parameters:
      - name: status
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
            default: new
            enum:
            - new
            - scheduled
            - sent
      - name: surveyid
        in: query
        description: ID da pesquisa
        schema:
          type: integer
      - name: page
        in: query
        description: Número da página
        schema:
          type: integer
      - name: limit
        in: query
        description: Número de resultados
        schema:
          type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllContacts'
        "400":
          description: invalid status value
          content: {}
        "404":
          description: nothing found
          content: {}
        "500":
          description: internal server error
          content: {}
      security:
      - ApiToken: []
        ApiSecret: []
    post:
      tags:
      - contact
      summary: Enviar um contato
      operationId: postContact
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
        required: true
      responses:
        "201":
          description: successful operation
          content: {}
        "400":
          description: invalid body
          content: {}
        "404":
          description: nothing found
          content: {}
        "500":
          description: internal server error
          content: {}
      security:
      - ApiToken: []
        ApiSecret: []
  /contact/batch:
    post:
      tags:
      - contact
      summary: Enviar uma lista de contatos
      operationId: postBatchOfContacts
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Contact'
        required: true
      responses:
        "201":
          description: successful operation
          content: {}
        "400":
          description: invalid body
          content: {}
        "404":
          description: nothing found
          content: {}
        "500":
          description: internal server error
          content: {}
      security:
      - ApiToken: []
        ApiSecret: []
  /contact/{id}:
    get:
      tags:
      - contact
      summary: Consumir dados de contato
      operationId: getContact
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpecificContact'
        "400":
          description: invalid id
          content: {}
        "404":
          description: nothing found
          content: {}
        "500":
          description: internal server error
          content: {}
      security:
      - ApiToken: []
        ApiSecret: []
  /survey:
    get:
      tags:
      - survey
      summary: Consumir ID das pesquisas
      operationId: getSurveys
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Survey'
        "404":
          description: nothing found
          content: {}
        "500":
          description: internal server error
          content: {}
      security:
      - ApiToken: []
        ApiSecret: []
components:
  schemas:
    AllContacts:
      type: object
      properties:
        status:
          type: string
        contacts:
          type: integer
        total_contacts:
          type: integer
        page:
          type: integer
        total_pages:
          type: integer
        data:
          type: object
          required:
            - email
            - survey
          properties:
            id:
              type: string
              format: uuid
              uniqueItems: true
              readOnly: true
            createdat:
              type: string
              format: date-time
            name:
              type: string
            email:
              type: string
              format: email
            phone:
              type: string
            survey:
              type: integer
            extra:
              type: object
              minProperties: 1
              maxProperties: 6
    SpecificContact:
      type: object
      properties:
        status:
          type: string
        data:
          type: object
          required:
            - email
            - survey
          properties:
            id:
              type: string
              format: uuid
              uniqueItems: true
              readOnly: true
            createdat:
              type: string
              format: date-time
            name:
              type: string
            email:
              type: string
              format: email
            phone:
              type: string
            survey:
              type: integer
            extra:
              type: object
              minProperties: 1
              maxProperties: 6
    Contact:
      type: object
      required:
        - email
        - survey
      properties:
        id:
          type: string
          format: uuid
          uniqueItems: true
          readOnly: true
        createdat:
          type: string
          format: date-time
        name:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        survey:
          type: integer
          format: int64
        extra:
          type: object
          minProperties: 1
          maxProperties: 6
    Survey:
      type: object
      properties:
        count:
          type: integer
        data:
          type: object
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
  securitySchemes:
    ApiToken:
      type: apiKey
      in: query
      name: api_token
    ApiSecret:
      type: apiKey
      in: query
      name: api_secret
