openapi: 3.0.0
info:
  description: An API describing how to integrate with the HeadBox instant meeting room booking platform.
  version: "1.0.0-oas3"
  title: Simple Bookable meeting room API
  contact:
    email: gavin@headbox.com

paths:
  /createBooking:
    post:
      summary: Should create a confirmed booking
      description: Calling this end-point should create a confirmed booking in your platform. 
      operationId: createBooking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingRequest'
          
      responses:
        '200':
          description: Confirmation that the booking has been successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingConfirmation'
        '409':
          description: Returned if the slots are no longer available. This could happen if someone has made a booking in parallel
        '500':
          description: An unknown error has occured and the booking was not confirmed
                
  /availability:
    get:
      summary: Returns the availability information for the provided meeting rooms
      description: Based on the passed room IDs and date, this should return the availability of those rooms. HeadBox will have already selected the most appropriate rooms based on location, number of attendees
      parameters:
        - in: query
          name: rooms
          description: A comma seperated list of the room IDs that we want to check availability for. These IDs will correspond to your internal reference for that room.
          required: true
          schema:
            type: string
        - in: query
          name: date
          required: true
          description: The date to check availability for. This is in the format YYYY-MM-DD
          schema:
            type: string
            format: date
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
        '400':
          description: bad input parameter

components:
  schemas:
    BookingRequest:
      type: object
      required:
        - date
        - roomID
        - headboxUUID
        - totalPrice
      properties:
        roomId:
          description: Your unique identifier for that room
          type: string
          example: "RM1"
        notes:
          description: Any additional notes provided by the Guest at the time of booking
          type: string
        date:
          description: The date the booking is for in the format YYYY-MM-DD
          type: string
          example: "2020-07-23"
        totalPrice:
          description: The total price calculated for the booking
          type: number
          example: 235.50
        headboxUUID:
          description: Our unique reference for the booking
          type: string
          example: "0255e848-4681-11ea-b77f-2e728ce88125"
        guest:
          $ref: '#/components/schemas/Guest'
        bookingSlot:
          $ref: '#/components/schemas/Slot'
    
    Guest:
      type: object
      required:
        - email
        - name
      properties:
        email:
          type: string
          example: bookings@headbox.com
          description: The Guests email address
        name:
          type: string
          example: Tori Bell
          description: The Guests full name
        telephone:
          type: string
          example: 07777 123456
          description: The contact number we have for the Guest
        company:
          type: string
          example: HeadBox
          description: The Guests company if known
    Room:
      type: object
      required:
        - id
        - availableTo
        - availableFrom
        - bookedSlots
        - slotType
        - pricePerSlot
      properties:
        id:
          type: string
          example: RM1 
          description: This should be the unique ID for the room in your system. HeadBox will have already matched this to the corresponding room in our platform
        pricePerSlot:
          type: number
          
        availableFrom:
          type: string
          format:  partial-time
          description: The earliest time the room is available to accept bookings from
          example: "08:00:00"
        availableTo:
          type: string
          format:  partial-time
          description: The latest the time the room is available to. This should correspond with the end of the last timeslot available. 
          example: "18:00:00"
        slotType:
          type: string
          enum: [hourly, half_or_full_day]
          description: The type of booking slots the room allows.
          example: hourly
        morningSlot:
           $ref: '#/components/schemas/Slot'
        afternoonSlot:
          $ref: '#/components/schemas/Slot'
        bookedSlots:
          type: array
          description: An array of the slots that have already been booked
          items:
            $ref: '#/components/schemas/Slot'
            
    BookingConfirmation:
      required:
        - bookingReference
      properties:
        bookingReference:
          description: Your internal reference for the booking. This can be used for reporting and to reconcile bookings with HeadBox
          type: string
          example: "BOOKING_3583"
    Slot:
      required:
        - startTime
        - endTime
      properties:
        startTime:
          type: string
          format: partial-time
          example: "09:00:00"
        endTime:
          type: string
          format: partial-time
          example: "12:00:00"
