openapi: 3.0.0
info:
  version: "10.3.1"
  title: UsersPreferencesList
  description: Common UsersPreferencesList API
paths:
  /user/preferences/:
    get:
      tags:
      - user preferences
      summary: Get the list of User Preferences
      description: "Returns a list of Preference object. \n\nSearch can be filtered\
        \ using Preference Group \n\nUser identifiers are passed as the header identities\
        \ object. API developers should use the header to get the user identifier\
        \ to get the preferences for the user."
      operationId: preferences_list
      parameters:
      - $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/PaginationQueryParameters/10.1#/components/parameters/orderingParam
      - $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/PaginationQueryParameters/10.1#/components/parameters/pageParam
      - $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/PaginationQueryParameters/10.1#/components/parameters/pageSizeParam
      - name: preference_group
        in: query
        description: Preference Group to filter the response specific to the group.
          Preference Group string is an enum which is defined as part of configuration.
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: policy_id
        in: query
        description: unique policy id.
        required: false
        style: form
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: An array of preference objects
          content:
            application/json:
              schema:
                required:
                - count
                - results
                type: object
                properties:
                  count:
                    type: integer
                    description: Count representing the total number of objects available
                      to be returned in the results array
                  next:
                    type: integer
                    description: query identifier defined by the api developer for
                      getting the next set of records
                  previous:
                    type: integer
                    description: query identifier defined by the api developer for
                      getting the previous set of records
                  results:
                    type: array
                    items:
                      $ref: https://api.swaggerhub.com/domains/Zipari-Core-Services/PreferenceModel/10.3.1#/components/schemas/Preference
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/ErrorModel/10.0.2#/components/schemas/Error'
        '403':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Zipari-Core-Services/ErrorModel/10.0.2#/components/schemas/Error'
