openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Fleet Tracker API"
  description: "Fleet Tracker API Documentation"
servers:
  - url: https://devportal.thinair.co/api/v1
security:
  - bearerAuth: []
paths:
  /getLatestPosition:
    post:
      tags:
        - Live View
      summary: Get The Latest Postions Of Devices
      requestBody:
        description: Get The Latest Postions Of Devices.
        content:
          application/json:
            schema:
              type: object
              properties:
                deviceIDs:
                  type: array
                  items:
                    type: integer
                offset:
                  type: integer
                limit:
                  type: integer
        required: false
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  positionsData:
                    type: array
                    items:
                      $ref: "#/components/schemas/PositionsData"
      x-codegen-request-body-name: position
components:
  schemas:
    PositionsData:
      type: object
      properties:
        DeviceID:
          type: integer
        Name:
          type: string
        CurrentLatitude:
          type: string
        CurrentLongitude:
          type: string
        CurrentAltitude:
          type: string
        CurrentSpeed:
          type: integer
        CurrentHeading:
          type: integer
        LastRecv:
          type: string
  securitySchemes:
    bearerAuth:
      type: apiKey
      name: Authorization
      in: header
