openapi: 3.0.0
info:
  version: '1.0.1'
  title: 'eCl@ss Dictionary API v 1.0'
  description: '<strong>Retrieval of classes and properties as eCl@ss XML 3.0.</strong>
  <p>Please install the swagger inspector extension and activate it for this page before runnig <i>try out</i> in swaggerhub:</p>
  <ul>
  <li><a href="https://chrome.google.com/webstore/detail/swagger-inspector-extensi/biemppheiopfggogojnfpkngdkchelik">Extension for Chrome browser</a></li>
  <li><a href="https://addons.mozilla.org/en-US/firefox/addon/swagger-inspector-ff-extension/">Extension for Firefox browser</a></li> 
  </ul>
  <p>Please authorize with the supplied user / password before making calls.</p>
  <p>Settings at bottom right of page should be: SSL certificates are validated, Routing requests via browser.</p>
  <p>When using the services with curl you may need to pass curl the <tt>-k</tt> option or install the SSL certificate for curl (<a href="https://curl.haxx.se/docs/sslcerts.html">See details</a>).</p>'

servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/eClass-Sub-Account/eClass-dictionary-API/1.0.0
  - description: ecl@ss beta
    url: https://beta.eclass-cdp.com/api/v1
    
paths:
    /classes/{irdi}:
      parameters:
        - name: irdi
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/irdi'
          example: '0173-1#01-AGI149#001'
      get:
        summary: "Retrieve a class as eCl@ss XML 3.0"
        description: "Please note: Retrieving a classification class at fourth level will pull also the advanced and basic application class as well as the classification classes at levels 1-3. Retrieving an application class will not pull any classification classes.<br>Example results are not included because they would be too big."
        responses:
          '200': 
            description: OK
            links:
              XML_Schema:
                description: '<a href="https://www.eclass.eu/static/eClassXML/3.0/eCl@ssXML/dictionary.xsd">eCl@ss XML 3.0</a>'
              Classification_Class:
                description: '<a href="http://wiki.eclass.eu/wiki/Classification_Class_(XML_Mapping)">Wiki Page</a>'
              Application_Class:
                description: '<a href="http://wiki.eclass.eu/wiki/Application_Class_(XML_Mapping)">Wiki Page</a>'
            content:
              application/x.eclass.v3+xml:
                schema:
                  type: string
                  description: https://www.eclass.eu/static/eClassXML/3.0/eCl@ssXML/dictionary.xsd
          '401':
            description: "Unauthorized"
          '404':
            description: "Not Found"
    /properties/{irdi}:
      parameters:
        - name: irdi
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/irdi'
          example: '0173-1#02-AAY070#001'
      get:
        summary: "retrieve a property as eCl@ss XML 3.0"
        description: "Example results are not included because they would be too big."
        responses:
          '200': 
            description: OK
            links:
              XML_Schema:
                description: '<a href="https://www.eclass.eu/static/eClassXML/3.0/eCl@ssXML/dictionary.xsd">eCl@ss XML 3.0</a>'
              Property:
                description: '<a href="http://wiki.eclass.eu/wiki/Property_(XML_Mapping)">Wiki Page</a>'
            content:
              application/x.eclass.v3+xml:
                schema:
                  type: string
                  description: https://www.eclass.eu/static/eClassXML/3.0/eCl@ssXML/dictionary.xsd
          '401':
            description: "Unauthorized"
          '404':
            description: "Not Found"
    /units/{irdi}:
      parameters:
        - in: path
          name: irdi
          required: true
          description: IRDI of unit of measure to retrieve
          example: '0173-1#05-AAA101#002'
          schema:
            $ref: '#/components/schemas/irdi'
        - in: query
          name: release
          required: false
          description: filter to target release
          example: '0173-1#11-ECLASS11.0#001'
          schema:
            $ref: '#/components/schemas/irdi'
      get:
        summary: "Retrieve a unit as eCl@ss XML 3.0"
        description: "Example results are not included because they would be too big."
        responses:
          200:
            links:
              XML_Schema:
                description: '<a href="https://www.eclass.eu/static/eClassXML/3.0/eCl@ssXML/units.xsd">eCl@ss XML 3.0</a>'
            content:
              application/x.eclass.v3+xml:
                schema:
                  type: string
                  description: 'https://www.eclass.eu/static/eClassXML/3.0/eCl@ssXML/units.xsd'
            description: OK    
    /mappings/{sourceRelease}/{targetRelease}/{sourceAC}:
      parameters:
        - name: sourceAC
          description: IRDI of the application class for which mapping is requested
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/irdi'
          example: '0173-1---ADVANCED_1_1#01-AFW243#005'
        - name: sourceRelease
          description: 'IRDI of the source release from which mapping is requested, e.g. 0173-1#11-ECLASS10.1#001, 0173-1#11-ECLASS11#001'
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/irdi'
          example: '0173-1#11-ECLASS11#001'
        - name: targetRelease
          description: 'IRDI of the target release to which mapping is requested, e.g. 0173-1#11-ECLASS11#001, 0173-1#11-ETIM7.0_1.0#001'
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/irdi'
          example: '0173-1#11-ETIM7.0_1.0#001'
      get:
        summary: "Retrieve mapping for an Application Class"
        responses:
          '200':
            description: OK
            links:
              XML_Schema:
                description: '<a href="https://www.eclass.eu/static/eClassXML/3.0/eCl@ssXML/mapping.xsd">eCl@ss XML 3.0</a>'
              Mapping:
                description: '<a href="http://wiki.eclass.eu/wiki/Transaction_Update_File">Wiki Page</a>'
            content:
              application/e.eclass.v3+xml:
                schema:
                  type: string
                  description: https://www.eclass.eu/static/eClassXML/3.0/eCl@ssXML/mapping.xsd
          '401':
            description: "Unauthorized"
          '404':
            description: "Not found"
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    irdi:
      type: string
      pattern: '^[0-9]{4}-[A-Z0-9:_.]{1,35}((-[A-Z0-9:_.]{1,35}(-[A-Z0-9]{1}(-[A-Z0-9:_.]{1,70})?)?)?|-([A-Z0-9:_.]{1,35})?--[A-Z0-9:_.]{1,70}|---[A-Z0-9:_.]{1,70})#[0-9A-Z]{2}-[A-Z0-9:_.]{1,131}#[0-9]{1,10}$'
security:
    - basicAuth: []
