openapi: 3.0.0
info:
  version: 'v1'
  title: 'Beycelik Integration Service'
  description: 'Integration with Beycelik production data'
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/inavitas/business-beycelik-integration/v1

paths: 
  /production-data:
    post:
      tags:
        - Production
      description: User can add new data 
      operationId: addProductionData
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Data'
      responses:
        200:
         description: Returns successful message
         content:
          application/json:
           schema:
              $ref: "#/components/schemas/SuccessModel"
components:
  schemas:
    Data:
      type: object
      properties:
        line:
          type: string
          example: 'Hat1'
        reference: 
          type: string
          example: 'Referans1'
        number:
          type: integer
          example: 50
        weight:
          type: number
          example: 115.6
        startDate:
          type: string
          example: "2019-12-01 13:45"
        endDate:
          type: string
          example: "2019-12-01 18:17"
    SuccessModel:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example : 200
        message:
          type: string
          example: "Successful operation"
