openapi: 3.0.0
info:
  description: |
    Demo Assessment API
  version: "1.0.0"
  title: Assessment API
  termsOfService: 'https://rakbank.ae'
  contact:
    email: sharabdheen.aboobacker@rakbank.ae
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
# Added by API Auto Mocking Plugin
# Added by API Auto Mocking Plugin
  - description: Mock API Endpoint
    url: http://rakbank-test.mocklab.io
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/rakmobility/assessment/1.0.0
tags:
  - name: activation
    description: Activation API
security:
  - apiKeyAuth: [] 
paths:
  /activation:
    post:
      tags:
        - activation
      summary: Activate a product
      operationId: activateProduct
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
            example: "Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZW1vdXNlcjEiLCJuYW1lIjoiUkFLQkFOSyBEZW1vIiwiaWF0IjoxNTE2MjM5MDIyfQ.hD2So1Jms00c7XB_bxNIrTgvSqMesmrlc0FkBAdY6rM"
          required: true
      responses:
        '400':
          description: Invalid ID supplied
        '200':
          description: Successfully activate the product
        '405':
          description: Validation exception
      requestBody:
        $ref: '#/components/requestBodies/ActivationRequest'
components:
  securitySchemes:
    apiKeyAuth:            # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: Authorization
  schemas:
    ActivationRequest:
      type: object
      required:
        - productId
        - emirate
      properties:
        productId:
          type: string
          example: "82jqp008d2l00"
        emirate:
          type: string
          example: "Abu Dhabi"
      xml:
        name: ActivationRequest    
  requestBodies:
    ActivationRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ActivationRequest'
        application/xml:
          schema:
            $ref: '#/components/schemas/ActivationRequest'
      description: Product Id that needs to be activated to an Emirate
      required: true
