openapi: 3.0.1
info:
  title: Eventos de ordenes de servicio - Restaurantes Integraciones
  description: Especificación de eventos relacionados con ordenes de servicio
  version: "1.0"
paths:
  /orderEvent:
    post:
      summary: Nuevo evento en la orden
      operationId: orderEvent
      requestBody:
        description: Notifica acerca de un nuevo evento en la orden 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderEventInfo'
        required: true
      responses:
        200:
          description: Operación exitosa
          content: {}
components:
  schemas:
    OrderEventInfo:
      type: object
      properties:
        orderId:
          type: string
          description: El id de la orden
          format: int32
        eventType:
          type: string
          description: |
            El tipo de evento en la orden.
            * `assigned_to_domiciliary` - Indica cuando la orden ha sido asignada a un domiciliario
            * `domiciliary_in_store` - Indica cuando el domiciliario ha llegado a la tienda
            * `hand_to_domiciliary` - Indica cuando el domiciliario se le ha entregado el pedido
            * `cancelled` - Indica que la orden ha sido cancelada
            * `finished` - Indica que la orden ha finalizado
          enum:
          - assigned_to_domiciliary
          - domiciliary_in_store
          - hand_to_domiciliary
          - cancelled
          - finished
