openapi: 3.0.0
info:
  description: |
    API for syncing agencies AON + CW
  version: "1.2.0"
  title: Agencies AON sync w/ CW
components:
  schemas:
    Agency:
      type: object
      required:
        - agency_code
        - agency_legal_name
        - agency_email
        - account_current
        - new_comm_rate
        - renew_comm_rate
        - stp_eligible
        - phone
      properties:
        agency_code:
          type: integer
        agency_legal_name:
          type: string
        agency_dba_name:
          type: string
        agency_email:
          type: string
        new_business_uw:
          type: string
        renewal_business_uw:
          type: string
        account_current:
          type: boolean
        new_comm_rate:
          type: number
        renew_comm_rate:
          type: number
        stp_eligible:
          type: boolean
        phone:
          type: string
        address_info:
          type: array
          items:
            $ref: '#/components/schemas/AddressInfo'
      xml:
        name: Agency
    
    ArrayOfAgencies:
      type: object
      properties:
        agency_info:
          type: array
          items:
            $ref: '#/components/schemas/Agency'
    
    AgencyInfo:
      type: object
      properties:
        agency_info:
          $ref: '#/components/schemas/Agency'
      xml:
        name: AgencyInfo
        
    AddressInfo:
      type: object
      required:
        - street_line_1
        - city
        - state
        - zip_code
      properties:
        street_line_1:
          type: string
        street_line_2:
          type: string
        city:
          type: string
        state:
          type: string
        zip_code:
          type: string
      xml:
        name: AddressInfo
    
    Program:
      type: string
      enum:
        - dentistsadvantage      # For Dentists Advantage
        - attorneysadvantage     # For Attorneys Advantage
        
    LOB:
      type: string
      enum:
        - healthcare             # For Dentists Advantage
        - specialty              # For Attorneys Advantage
        
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
paths:
  /agency:
    get:
      tags:
        - Agency
      summary: Get BOTH new and updated agencies since two dates
      security:
        - basicAuth: []
      parameters:
        - name: line_of_business
          in: query
          description: Identifies Affinity business unit/lob 
          required: true
          schema:
            $ref: '#/components/schemas/LOB'
        - name: program
          in: query
          description: Identifies insurance program being rated 
          required: true
          schema:
            $ref: '#/components/schemas/Program'
        - name: date_from
          in: query
          description: Start date
          required: true
          schema:
            type: string
        - name: date_to
          in: query
          description: End date
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Agencies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfAgencies'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '405':
          description: Invalid input
          
  /updateagency:
    post:
      tags:
        - Agency
      summary: Insert or update an agency (in case of insert id must be null)
      description: >-
        It returns an agency identification. This id will be stored in CW
        database and will be use to match this agency
      security:
        - basicAuth: []
      parameters:
        - name: line_of_business
          in: query
          description: Identifies Affinity business unit/lob 
          required: true
          schema:
            $ref: '#/components/schemas/LOB'
        - name: program
          in: query
          description: Identifies insurance program being rated 
          required: true
          schema:
            $ref: '#/components/schemas/Program'
      responses:
        '200':
          description: Agency successful created or updated (Broker Number)
          content:
            '*/*':
              schema:
                type: integer
                format: int32
                example: 9999
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '405':
          description: Invalid input
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgencyInfo'
        description: Agency object that needs to be inserted (id must be null)
        required: true
