openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/BZCompany/api.porovnejsito.cz/1.0.0
  - description: API Auto Mocking
    url: http://api.porovnejsito.bzcompany.cz/
info:
  description: .
  version: "1.0.0"
  title: PorovnejsiTo.cz API
  contact:
    email: skrebsky@bzcompany.cz
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: public
    description: Veřejný přístup, omezeno na IP
paths:
  /provider:
    get:
      tags:
        - public
      summary: dostupné balíčky na adrese
      operationId: searchProvider
      description: |
        Vyhledávání balíčku služeb dle adresy nebo GPS souřadnic. Výsledek obsahuje max. 3 nalezená adresní místa(pouze v případě hledání dle adresy, parametr {q}) a seznam dostupných balíčků pro každé adresní místo.
      parameters:
        - in: query
          name: x
          description: zeměpisná délka ve formátu WGS-84
          required: false
          schema:
            type: number
            format: float
          example: 14.4000936
        - in: query
          name: y
          description: zemepisná šířka ve formátu WGS-84
          required: false
          schema:
            type: number
            format: float
          example: 49.7037853865
        - in: query
          name: q
          description: hledaná adresa
          schema:
            type: string
          example: ulice č.p., město
        - in: query
          name: service
          description: typ sluzby
          schema:
            type: string
            enum:
              - internet
              - tv
              - call
          example: internet,tv
      responses:
        '200':
          description: výsledky vyhledávání
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: bad input parameter
  /order:
    post:
      tags:
        - public
      summary: objednávka
      operationId: createOrder
      description: nová objednávka
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        '201':
          description: data objednávky
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: bad input parameter
        '500':
          description: server error
  /order/{id}/status:
    get:
      tags:
        - public
      summary: objednávka
      operationId: orderStatus
      description: stav objednávky
      parameters:
        - in: path
          name: id
          description: id objednávky
          required: true
          schema:
            type: number
            format: int32
      responses:
        '200':
          description: data objednávky
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: bad input parameter
  /lists/servicepackagetags:
    get:
      tags:
        - public
      summary: štítky
      operationId: lstServicePackageTags
      description: seznam štítků pro balíčky
      responses:
        '200':
          description: seznam položek
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
  /lists/servicetvprogs:
    get:
      tags:
        - public
      summary: tv programy
      operationId: lstServiceProgs
      description: seznam tv programů
      responses:
        '200':
          description: seznam položek
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
  /lists/servicetvapps:
    get:
      tags:
        - public
      summary: tv aplikace
      operationId: lstServiceApps
      description: seznam tv aplikací
      responses:
        '200':
          description: seznam položek
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
  /lists/tvproggenres:
    get:
      tags:
        - public
      summary: tv žánry
      operationId: lstServiceTVProgGenres
      description: seznam tv žánrů
      responses:
        '200':
          description: seznam položek
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
  /lists/tvprogqualities:
    get:
      tags:
        - public
      summary: tv žánry
      operationId: lstServiceTVProgQualities
      description: seznam tv kvality
      responses:
        '200':
          description: seznam položek
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
components:
  schemas:
    Response:
      type: object
      properties:
        status:
          type: integer
          format: int32
          description: stav provedené akce
        data:
          anyOf:
            - $ref: '#/components/schemas/ProviderData'
            - $ref: '#/components/schemas/ServiceTVApp'
            - $ref: '#/components/schemas/ServiceTVProg'
            - $ref: '#/components/schemas/LstServicePackageTag'
            - $ref: '#/components/schemas/LstTVProgGenre'
            - $ref: '#/components/schemas/LstTVProgQuality'
            - $ref: '#/components/schemas/OrderResponse'
          description: data odpovědi
        id:
          type: string
          description: unikátní ID chyby
        code:
          type: integer
          format: int32
          description: kód chyby
        title:
          type: string
          description: popis chyby
    ProviderData:
      type: object
      properties:
        lat:
          type: number
          format: float
          description: zeměpisná šířka
        long:
          type: number
          format: float
          description: zeměpisná délka
        query:
          type: string
          description: hledaná adresa
        packages:
          type: array
          items:
            $ref: '#/components/schemas/ServicePackage'
          description: nalezené balíčky
        providers:
          type: array
          items:
            $ref: '#/components/schemas/Provider'
          description: seznam poskytovatelů(pouze nalezené balíčky)
    ServicePackage:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/IdentId'
        title:
          type: string
          description: název balíčku
        price_per_month:
          type: number
          format: double
          description: cena službu/měsíc
        price_setup:
          type: number
          format: double
          description: zřizovací poplatek
        note1:
          type: string
          description: poznámka
        note2:
          type: string
          description: poznámka ke zřizovacímu poplatku
        is_commitment:
          type: boolean
        services:
          type: object
          properties:
            internet:
              $ref: '#/components/schemas/ServiceInternet'
            tv:
              $ref: '#/components/schemas/ServiceTV'
            call:
              $ref: '#/components/schemas/ServiceCall'
        provider_id:
          $ref: '#/components/schemas/IdentId'
        brand_id:
          $ref: '#/components/schemas/IdentId'
    ServiceInternet:
      type: object
      properties:
        technology_code:
          type: string
          description: kód technologie připojení
        speed_down_mb:
          type: number
          format: double
          description: rychlost stahování dat v MB
        speed_up_mb:
          type: number
          format: double
          description: rychlost uploadování dat v MB
        fup_down_limit_gb:
          type: number
          format: double
          description: omezení stahování dat v GB
        fup_up_limit_gb:
          type: number
          format: double
          description: omezení uploadu dat v GB
        is_business:
          type: boolean
          description: firemní internet
    ServiceTV:
      type: object
      properties:
        technology_code:
          type: string
          description: kód technologie připojení
        max_devices:
          type: integer
          format: int32
          description: max. počet zařízení
        history:
          type: boolean
          description: zpětné shlédnutí
        history_note:
          type: string
          description: popis funkce zpětného shlédnutí
        record:
          type: boolean
          description: nahrávání pořadů
        record_note:
          type: string
          description: popis funkce nahrávání pořadů
        pause:
          type: boolean
          description: funkce pauza
        video:
          type: boolean
          description: funkce videotéka
        tag_ids:
          type: array
          items:
            $ref: '#/components/schemas/IdentIds'
        app_id:
          type: array
          items:
            $ref: '#/components/schemas/IdentId'
        prog_id:
          type: array
          items:
            $ref: '#/components/schemas/IdentId'
    ServiceTVApp:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/IdentId'
        title:
          type: string
          description: název aplikace
        note1:
          type: string
          description: poznámka 1
        note2:
          type: string
          description: poznámka 2
    ServiceTVProg:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/IdentId'
        title:
          type: string
          description: název programu
        note1:
          type: string
          description: poznámka 1
        note2:
          type: string
          description: poznámka 2
        quality_ids:
          $ref: '#/components/schemas/IdentIds'
        genre_ids:
          type: array
          items:
            $ref: '#/components/schemas/IdentIds'
    ServiceCall:
      type: object
      properties:
        technology_code:
          type: string
          description: kód technologie připojení
        fup_down_limit_gb:
          type: number
          format: double
          description: omezení stahování dat v GB
        free_min_own:
          type: integer
          format: int32
          description: volné minuty ve vlastní síti
        free_min_other:
          type: integer
          format: int32
          description: volné minuty do ostatních síti
        free_sms_own:
          type: integer
          format: int32
          description: volné sms ve vlastní síti
        free_sms_other:
          type: integer
          format: int32
          description: volné sms do ostatních síti
        free_mms_own:
          type: integer
          format: int32
          description: volné mms ve vlastní síti
        free_mms_other:
          type: number
          format: double
          description: volné mms do ostatních síti
        price_min_own:
          type: number
          format: double
          description: cena volání za minutu ve vlastní síti
        price_min_other:
          type: number
          format: double
          description: cena volání za minutu do ostatních síti
        price_sms_own:
          type: number
          format: double
          description: cena za sms ve vlastní síti
        price_sms_other:
          type: number
          format: double
          description: cena za sms do ostatních síti
        price_mms_own:
          type: number
          format: double
          description: cena za mms ve vlastní síti
        price_mms_other:
          type: number
          format: double
          description: cena za mms do ostatních síti
        benefit1:
          type: boolean
          description: zvýhodnění pro studenty
        benefit2:
          type: boolean
          description: zvýhodnění pro seniory
        benefit3:
          type: boolean
          description: zvýhodnění pro ZTP
    Provider:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/IdentId'
        name:
          type: string
          description: název poskytovatele
    LstServicePackageTag:
      type: object
      properties:
        ids:
          $ref: '#/components/schemas/IdentIds'
        title:
          type: string
          description: název štítku
    LstTVProgGenre:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/IdentId'
        title:
          type: string
          description: název žánru
    LstTVProgQuality:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/IdentId'
        title:
          type: string
          description: název kvality
    IdentId:
      type: integer
      format: int32
      description: unikátní identifikátor položky
    IdentIds:
      type: string
      description: unikátní identifikátor položky
    OrderRequest:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/OrderData'
        items:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/OrderItem'
        partner:
          $ref: '#/components/schemas/IdentIds'
      required:
        - data
        - items
        - partner
    OrderResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/OrderData'
        items:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/OrderItem'
    OrderData:
      type: object
      properties:
        provider_id:
          type: integer
          format: int32
          description: unikátní identifikátor poskytovatele
        first_name:
          type: string
          maxLength: 32
          description: jméno objednavatele
        last_name:
          type: string
          maxLength: 32
          description: příjmení objednavatele
        email:
          type: string
          maxLength: 255
          description: emailový kontakt
        phone:
          type: string
          maxLength: 32
          description: telefonní kontakt
        birth_num:
          type: string
          maxLength: 12
          description: rodné číslo nebo ič
        person_id_num:
          type: string
          maxLength: 12
          description: číslo dokladu (OP/pas)
        person_id_valid_year:
          type: integer
          format: int32
          minimum: 2000
          maximum: 2100
          description: platnost dokladu (rok)
        person_id_valid_month:
          type: integer
          format: int32
          minimum: 1
          maximum: 12
          description: platnost dokladu (měsíc)
        address1_contact_name:
          type: string
          maxLength: 64
          description: kontaktní osoba (adresa instalace)
        address1_street:
          type: string
          maxLength: 128
          description: ulice č.p. (adresa instalace)
        address1_city:
          type: string
          maxLength: 64
          description: město (adresa instalace)
        address1_zip_code:
          type: string
          maxLength: 5
          description: psč (adresa instalace)
        address1_country_code:
          type: string
          maxLength: 6
          description: kód země dle ISO 3166-1
        address1_country_region_code:
          type: string
          maxLength: 5
          description: kód kraje dle CZ-NUTS územního dělení v ČR
          default: null
        address1_country_township_code:
          type: string
          maxLength: 6
          description: kód okresu dle LAU1 územního dělení v ČR
          default: null
        address2_contact_name:
          type: string
          maxLength: 64
          description: společnost / jméno (fakturační adresa)
          default: null
        address2_street:
          type: string
          maxLength: 128
          description: ulice č.p. (fakturační adresa)
          default: null
        address2_city:
          type: string
          maxLength: 64
          description: město (fakturační adresa)
          default: null
        address2_zip_code:
          type: string
          maxLength: 5
          description: psč (fakturační adresa)
          default: null
        address2_country_code:
          type: string
          maxLength: 6
          description: kód země dle ISO 3166-1
          default: null
        address2_country_region_code:
          type: string
          maxLength: 5
          description: kód kraje dle CZ-NUTS územního dělení v ČR
          default: null
        address2_country_township_code:
          type: string
          maxLength: 6
          description: kód okresu dle LAU1 územního dělení v ČR
          default: null
        time_call:
          type: string
          pattern: '(0?[0-9]|1[0-9]|2[0-3]):[0-5]?[0-9]'
          description: kdy volat (čas, HH:MM)
          default: null
        note1:
          type: string
          description: poznámka k instalaci
          default: null
        id:
          type: number
          format: int32
          readOnly: true
          description: unikátní identifikátor objednávky
        status_ids:
          type: string
          maxLength: 4
          readOnly: true
          description: kód stavu
        status_note:
          type: string
          readOnly: true
          description: poznámka ke stavu
          default: null
        time_created:
          type: string
          format: date-time
          readOnly: true
          description: datum vytvoření objednávky
        time_changed:
          type: string
          format: date-time
          readOnly: true
          description: datum poslední změny objednávky
      required:
        - provider_id
        - first_name
        - last_name
        - email
    OrderItem:
      type: object
      properties:
        service_package_id:
          type: integer
          format: int32
          description: unikátní identifikátor balíčku
        ext_id:
          type: string
          maxLength: 32
          description: vlastní označení
          default: null
        note1:
          type: string
          readOnly: true
          description: poznámka
          default: null
        id:
          type: number
          format: int32
          readOnly: true
          description: unikátní identifikátor položky objednávky
        status_ids:
          type: string
          maxLength: 4
          readOnly: true
          description: kód stavu
        status_note:
          type: string
          readOnly: true
          description: poznámka ke stavu
          default: null
      required:
        - service_package_id
