openapi: 3.0.1
info:
  title: Refunder notifications
  description: Refunder notifications API
  version: 0.0.7
servers:
- url: http://109.202.21.168:59000
tags: []
paths:
  /get-notification:
    get:
      tags:
      - get-notification
      summary: notifications
      description: notifications
      operationId: get-notification
      parameters:
      - name: last_notification_id
        in: query
        description: |-
          Last receiver notification id.
          Used as filter parameter to include notifications only after that id.
          Can be used as header value.
        required: false
        schema:
          type: string
      - name: extension_version
        in: query
        description: |-
          Filter for specific extension version.
          Should be specified concrete version or `all`.
          If value is empty then value `all` will be used.
          Can be used as header value.
          Case insensitive.
        required: false
        schema:
          type: string
      - name: browser_name
        in: query
        description: |-
          Filter for browser version.
          Should be specified concrete version or `all`.
          If value is empty then value `all` will be used.
          Can be used as header value.
          Case insensitive.
        required: false
        schema:
          type: string
      - name: user_email
        in: query
        description: |-
          Filter for notification to concrete user.
          Should be specified concrete user email or `unregistered`.
          When specified concrete user email then result will be for that specific email and `registered`.
          Other wise if value is not specified then result will be only for `unregistered`.
          Possible value: `unregistered`, `registered`, some email - `some.email@mail.com`.
          Can be used as header value.
          Case insensitive.
        required: false
        schema:
          type: string
      - name: notification_type
        in: query
        description: |-
          Filter for notification types.
          Can accept many values.
          Example values is `cashback`, `general`, `personalized`
          Result will return only notification witch contains any of specified type.
          Case insensitive.
        required: false
        schema:
          type: string
      - name: language
        in: query
        description: |-
          Filter for language.
          Accept single value.
          Should be `pl` or `se`.
          Can be used as header value.
          Case insensitive.
        required: true
        schema:
          type: string
      responses:
        200:
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get-notification54133929'
              examples:
                get-notification:
                  value: '[{"datime":"2020-01-21T14:21:20.039369Z","id":1579616480039,"where":{"popup":false,"blocked_popup":false,"slider":false},"html":{"headline":"<div>headline</div>"},"target":{"versions":["all"],"browsers":["all"],"users":["all"],"type":"test","language":"se"},"expiredAt":null},{"datime":"2020-01-21T14:21:17.366526Z","id":1579616477366,"where":{"popup":false,"blocked_popup":false,"slider":false},"html":{"headline":"<div>headline</div>"},"target":{"versions":["all"],"browsers":["all"],"users":["all"],"type":"test","language":"se"},"expiredAt":null}]'
  /set-notification:
    post:
      tags:
      - set-notification
      summary: notifications
      description: notifications
      operationId: set-notification
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/set-notification791956856'
            examples:
              set-notification:
                value: |-
                  {
                      "where": {
                          "popup": true,
                          "blocked_popup": false,
                          "slider": true
                      },
                      "html": {
                          "headline": "<img src=\"https://image.refunder.se/stores/23-s-cdon_com1.png\"><br>",
                          "body": "<b>Hej!</b> - CDON kör en Megakampanj på elektronik hela helgen. Passa på att fynda! <a href=\"http://www.cdon.com\" target=\"blank\">Klicka här</a>.<br><br>"
                      },
                      "target": {
                          "versions": [
                              "all"
                          ],
                          "browsers": [
                              "all"
                          ],
                          "users": [
                              "kungadler@gmail.com"
                          ],
                          "type": "cashback",
                          "language": "se"
                      },
                      "expiredAt": "2019-11-06T22:10:39Z"
                  }
      responses:
        200:
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/set-notification486549215'
              examples:
                set-notification:
                  value: '{"datime":"2020-01-21T14:21:17.588083Z","id":1579616477588,"where":{"popup":true,"blocked_popup":false,"slider":true},"html":{"headline":"<img
                    src=\"https://image.refunder.se/stores/23-s-cdon_com1.png\"><br>","body":"<b>Hej!</b>
                    - CDON kör en Megakampanj på elektronik hela helgen. Passa på
                    att fynda! <a href=\"http://www.cdon.com\" target=\"blank\">Klicka
                    här</a>.<br><br>"},"target":{"versions":["all"],"browsers":["all"],"users":["kungadler@gmail.com"],"type":"cashback","language":"se"},"expiredAt":"2019-11-06T22:10:39Z"}'
components:
  schemas:
    get-notification54133929:
      type: array
      items:
        type: object
        properties:
          expiredAt:
            type: string
            description: expired at datetime
          html:
            type: object
            properties:
              body:
                type: string
                description: body content
              headline:
                type: string
                description: headline content
            description: notification html content
          where:
            type: object
            properties:
              slider:
                type: boolean
                description: condition for slider
              popup:
                type: boolean
                description: condition for popup
              blocked_popup:
                type: boolean
                description: condition for blocked popup
          id:
            type: number
            description: notification id
          datime:
            type: string
            description: creation date time
          target:
            type: object
            properties:
              versions:
                type: array
                description: target versions
                items:
                  oneOf:
                  - type: object
                  - type: boolean
                  - type: string
                  - type: number
              language:
                type: string
                description: notification language
              type:
                type: string
                description: notification type
              browsers:
                type: array
                description: target browsers
                items:
                  oneOf:
                  - type: object
                  - type: boolean
                  - type: string
                  - type: number
              users:
                type: array
                description: target users
                items:
                  oneOf:
                  - type: object
                  - type: boolean
                  - type: string
                  - type: number
    set-notification791956856:
      type: object
      properties:
        expiredAt:
          type: string
          description: |-
            Notification expired date. `ISO 8601` format without timezone.
            Example value: `2019-11-06T22:10:39Z`.
            Treats as UTC+0 offset.
            Optional.
            Default values is null.
        html:
          type: object
          properties:
            body:
              type: string
              description: body content
            headline:
              type: string
              description: headline content
          description: notification html content
        where:
          type: object
          properties:
            slider:
              type: boolean
              description: condition for slider
            popup:
              type: boolean
              description: condition for popup
            blocked_popup:
              type: boolean
              description: condition for blocked popup
        target:
          type: object
          properties:
            versions:
              type: array
              description: target versions
              items:
                oneOf:
                - type: object
                - type: boolean
                - type: string
                - type: number
            language:
              type: string
              description: notification language
            type:
              type: string
              description: notification type. Recommended values `cashback`, `general`,
                `personalized`
            browsers:
              type: array
              description: target browsers
              items:
                oneOf:
                - type: object
                - type: boolean
                - type: string
                - type: number
            users:
              type: array
              description: target users
              items:
                oneOf:
                - type: object
                - type: boolean
                - type: string
                - type: number
    set-notification486549215:
      type: object
