openapi: 3.0.0

info:
  version: "1.0.1"
  title: 'IONITY Ticketing API'
  description: ''

servers:
  - url: https://{environment}.ionity.eu/rest/ionity-ticketing
    variables:
      environment:
        default: jira  # Production environment
        enum:
          - jira       # Production environment
          - jira-test  # Test environment

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

security:
  - basicAuth: []

paths:

  /api:
    get:
      summary: Get Open API 3.0 specification (this file).
      responses:
        200:
          description: Text response

  /tickets:

    post:
      summary: Create a new ticket
      description: |
        Ionity operates a centralized ticketing system. This api allows partners to ...
        - create new tickets and hand over them to a service partner
        - [to be extended]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                chargepoint_id:
                  type: string
                  description: id of chargepoint
                serial_number:
                  type: string
                  description: serial number of affected device
                description:
                  type: string
                  description: further description of ticket
                assignee:
                  type: string
                  description: eMail address of assigned service partner
                priority:
                  type: string
                  description: priority of ticket
                error_code:
                  type: string
                  description: error-code, e.q. "Other Error"
                error_info:
                  type: string
                  description: optional additional information concerning the error
                vendor_code:
                  type: string
                  description: vendor specific error code
                firmware_version:
                  type: string
                  description: firmware version if availiable
                evse_id:
                  type: string
                  description: evse id of affected connector
                address:
                  type: string
                  description: location of affected device
              required:
                - chargepoint-id
                - serial-number
                - description
                - assignee
            example: 
                {
                  "chargepoint_id" : "hpc-120879",
                  "serial_number" : "120879",
                  "description" : "Problem at charging station needs an escalation.",
                  "assignee" : "serivce@service-partner.com",
                  "priority" : "S1",
                  "error_code" : "OtherError",
                  "vendor_code" : "282",
                  "firmware_version" : "pkx.4.0.4_ionity",
                  "evse_id" : "DE*ION*E100101",
                  "address" : "Autobahn A61, Rasthof Brohltal West 56651 Niederzissen"
                }
      responses:
        201:
          description: ticket created
          headers:
            Location:
              description: URL of new issues
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  issue:
                    type: string
                    description: "created ticket ID, for example: OPSDESK-1234"
              example: 
                {
                  "issue" : "OPSDESK-1234"
                }
        400:
          description: |
            ticket cration failed, possible reasons:
            - [to be defined]

    get:
      summary: Returns a list of all relevant tickets present on the server
      responses:
        200:
          description: JSON Array
          content:
            application/json:
              example:
                [OPSDESK-1234, OPSDESK-1235]
  
  /tickets/{issue}:
    put:
      summary: Update Ticket
      parameters: 
        - in: path
          name: issue
          schema:
            type: string
          required: true
          example: "OPSDESK-1234"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                chargepoint_id:
                  type: string
                  description: id of chargepoint
                serial_number:
                  type: string
                  description: serial number of affected device
                description:
                  type: string
                  description: further description of ticket  
                assignee:
                  type: string
                  description: eMail address of assigned service partner
                priority:
                  type: string
                  description: priority of ticket
                error_code:
                  type: string
                  description: error-code, e.q. "Other Error"
                error_info:
                  type: string
                  description: optional additional information concerning the error
                vendor_code:
                  type: string
                  description: vendor specific error code
                firmware_version:
                  type: string
                  description: firmware version if availiable
                evse_id:
                  type: string
                  description: evse id of affected connector
                address:
                  type: string
                  description: location of affected device
            example: 
                {
                  "chargepoint_id" : "hpc-120879",
                  "serial_number" : "120879",
                  "description" : "Problem at charging station needs an escalation.",
                  "assignee" : "serivce@service-partner.com",
                  "priority" : "S1",
                  "error_code" : "OtherError",
                  "vendor_code" : "282",
                  "firmware_version" : "pkx.4.0.4_ionity",
                  "evse_id" : "DE*ION*E100101",
                  "address" : "Autobahn A61, Rasthof Brohltal West 56651 Niederzissen"
                }
      responses:
        204:
          description: ticket updated
          headers:
            Location:
              description: URL of issues
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  issue:
                    type: string
                    description: "updated ticket ID, for example: OPSDESK-1234"
              example: 
                {
                  "issue" : "OPSDESK-1234"
                }
        400:
          description: |
            ticket update failed, possible reasons:
            - [to be defined]

  /tickets/{issue}/attachments:
    post:
      summary: Upload an Attachment file to the ticket.
      parameters: 
        - in: path
          name: issue
          schema:
            type: string
          required: true
          example: "OPSDESK-1234"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: array
                  description: |
                    - Multiple files may be uploaded at once
                  items:
                    type: string
                    format: binary
              required:
                - file
            encoding:
              file:
                contentType: application/xml; charset=utf-8
      responses:
        201:
          description: File upload successful
        400:
          description: |
            File upload is invalid, possible reasons:
            - File could not be uploaded
