openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Error Template for APIs'
  description: 'Error Template for APIs'
paths: {}
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/herzcthu/ErrorTemplate/1.0.0
components:
  schemas:
    badRequestService:
      type: object
      properties:
        code: 
          type: string
          enum: 
          - "YB10001"
        message: 
          type: string
          enum:
          - "Bad Request"
        details:
          type: string
    serverErrorService:
      type: object
      properties:
        code: 
          type: string
          enum:
          - "YB14003"
        message: 
          type: string
          enum:
          - "System Error"
        details:
          type: string
    badRequestCore:
      type: object
      properties:
        code: 
          type: string
          enum:
          - "YB90001"
        message: 
          type: string
          enum:
          - "Bad Request"
        details:
          type: string
    serverErrorCore:
      type: object
      properties:
        code: 
          type: string
          enum:
          - "YB94003"
        message: 
          type: string
          enum:
          - "System Error"
        details:
          type: string
