openapi: 3.0.0
info:
  description: |
    Security Multifactor Authentication
  version: "1.0.0"
  title: Security Multifactor Authentication
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: rubiyanisha@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
# Added by API Auto Mocking Plugin
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/RubiyaKadarBasha/sample/1.0.0


tags:
  - name: nextgen/api/v1/rest/
    description: Everything about Security Multifactor Authentication


paths:

  '/scb/userDetails/{userId}/authentication':
    get:
      tags:
        - nextgen/api/v1/rest
      summary: Security Mutlifactor Authentication
      operationId: overall
      parameters:
        - name: userId
          in: path
          description: get the userID
          required: true
          schema:
            type: integer
            format: int64

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationSummary'


components:
  schemas:
  
    AuthenticationSummary:
      type: object
      properties:
        multifactorResponse:
          $ref: '#/components/schemas/Success'
        
  

    Success:
      type: object
      properties:
        rescode:
          type: number
          example: 200
        message:
          type: string
          example: authenticaion success
