openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/POLIEDRO/Inscricoes-SAEP/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/POLIEDRO/SAEPInscricoes/1.0.0
info:
  description: Api para inscrições do SAEP
  version: "1.0.0"
  title: Inscricoes-SAEP
paths:
  /mapa:
    post:
      summary: obtém o mapa de inscrições para uma determinada unidade e período letivo
      operationId: mapa
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametrosMapa'
      responses:
        '200':
          description: detalhes do mapa de inscrições
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultadoMapa'
  /inscrever:
    post:
      summary: inscreve os agrupamentos de cursos informados, removendo os que não forem fornecidos
      operationId: inscrever
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametrosInscricao'
      responses:
        '200':
          description: detalhes do mapa de inscrições
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultadoMapa'
  /filtros:
    post:
      summary: obtém os filtros para tipos e classes para inscrição de turmas
      operationId: filtros
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametrosFiltros'
      responses:
        '200':
          description: detalhes do mapa de inscrições
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultadoFiltros'
  /inscreverTurmas:
    post:
      summary: inscreve os turmas informadas do curso, removendo as que não forem fornecidos
      operationId: inscreverTurmas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametrosInscricaoTurmas'
      responses:
        '200':
          description: relação de turmas inscritas para o simulado, do curso informado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultadoTurmasInscritas'
  /inscreverAlunos:
    post:
      summary: inscreve os alunos informados da turma, removendo os que não forem fornecidos
      operationId: inscreverAlunos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametrosInscricaoAlunos'
      responses:
        '200':
          description: relação de alunos inscritas para o simulado e curso informado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultadoAlunosInscritos'
  /turmas:
    post:
      summary: obtém a lista de turmas inscritas em um simulado
      operationId: turmasInscritas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametrosTurmasInscritas'
      responses:
        '200':
          description: relação de turmas inscritas para o simulado e curso informado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultadoTurmasInscritas' 
  /alunosTurma:
    post:
      summary: obtém a lista de alunos de uma turma inscritas em um simulado
      operationId: alunosInscritas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParametrosAlunosInscritos'
      responses:
        '200':
          description: relação de alunos de uma turma inscritas para o smulado e curso informado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultadoAlunosInscritos' 
components:
  schemas:
    Resultado:
      type: object
      properties:
        Sucesso:
          type: boolean
          description: se a chamada teve sucesso
        FalhaAutenticacao:
          type: boolean
          description: se a autenticacao está válida
        SemEscolaDefinida:
          type: boolean
          description: se o usuário está sem escola definida na sessão
        DeveTrocarSenha:
          type: boolean
          description: se o usuário está com senha expirada
        FalhaValidacao:
          type: boolean
          description: se ocorreu uma falha de validação
        Excecao:
          type: boolean
          description: se ocorreu uma exceção
        SomenteLeitura:
          type: boolean
          description: se a sessão é somente leitura
        Mensagem:
          type: string
          description: mensagem de erro ou validação
        Redirecionar:
          type: boolean
          description: se o site deve redirecionar
        CodigoFalhaAcesso:
          type: integer
          description: código de erro de falha de acesso
          format: int32
    ResultadoMapa:
      allOf: 
        - $ref: "#/components/schemas/Resultado"
        - type: object
          required:
           - Dados
          properties:
            Dados:
              $ref: '#/components/schemas/Mapa'
    ResultadoAlunosInscritos:
      allOf: 
        - $ref: "#/components/schemas/Resultado"
        - type: object
          required:
           - Dados
          properties:
            Dados:
              type: array
              items:
                $ref: '#/components/schemas/Aluno'
    Aluno:
      type: object
      required: 
        - id
        - matricula
        - nome
        - recebeCartao
        - marcado
      properties:
        id: 
          type: integer
          format: int32
        matricula:
          type: integer
          format: int32
        nome:
          type: string
        recebeCartao:
          type: boolean
        selecionado: 
          type: boolean
    Turma:
      type: object
      required: 
        - id
        - nome
        - total
        - inscritos
        - inscritosCartao
        - marcada
      properties:
        id: 
          type: integer
          format: int32
        nome:
          type: string
        inscritos:
          type: integer
          format: int32
        total:
          type: integer
          format: int32
        inscritosCartao:
          type: integer
          format: int32
        marcada:
          type: boolean
    ResultadoTurmasInscritas:
      allOf: 
        - $ref: "#/components/schemas/Resultado"
        - type: object
          required:
           - Dados
          properties:
            Dados:
              type: array
              items:
                $ref: '#/components/schemas/Turma'
    ResultadoFiltros:
      allOf: 
        - $ref: "#/components/schemas/Resultado"
        - type: object
          required:
           - Dados
          properties:
            Dados:
              type: array
              items:
                $ref: '#/components/schemas/TipoSimuladoFiltro'
    InscricoesAgrupamento:
      type: object
      required: 
        - agrupamentoCursoId
      properties:
        agrupamentoCursoId:
          type: integer
          format: int32
        simuladoId: 
          type: integer
          format: int32
          nullable: true
        dataInicial:
          type: string
          format: DateTime
          nullable: true
        dataFinal:
          type: string
          format: DateTime
          nullable: true
        inscrito:
          type: boolean
          nullable: true
    DadosInscricao:
      type: object
      required: 
        - simuladoId
        - agrupamentoCursoId
      properties:
        simuladoId: 
          type: integer
          format: int32
        agrupamentoCursoId:
          description: ids do AgrupamentosCurso inscrito
          type: integer
          format: int32
    TipoSimulado:
      type: object
      required:
        - nome
        - id
        - classes
      properties:
        id: 
          type: integer
          format: int32
        nome:
          type: string
        classes:
          type: array
          items:
            $ref: '#/components/schemas/Classe'
    Simulado:
      type: object
      required: 
        - nome
        - id
      properties:
        id: 
          type: integer
          format: int32
        nome:
          type: string
    TipoSimuladoFiltro:
      type: object
      required:
        - nome
        - id
        - simulados
      properties:
        id: 
          type: integer
          format: int32
        nome:
          type: string
        simulados:
          type: array
          items:
            $ref: '#/components/schemas/Simulado'
    Classe:
      type: object
      required:
        - nome
        - inscricoes
      properties:
        nome:
          type: string
        inscricoes:
          type: array
          items:
            $ref: '#/components/schemas/InscricoesAgrupamento'
    AgrupamentoAcademico:
      type: object
      required:
        - nome
        - tiposSimulado
        - mostraTipoSimulado
      properties:
        nome:
          type: string
        mostraTipoSimulado:
          type: boolean
        tiposSimulado: 
          type: array
          items:
            $ref: '#/components/schemas/TipoSimulado'
    AgrupamentoCurso:
      type: object
      required:
        - id
        - nome
      properties:
        id: 
          type: integer
          format: int32
        nome:
          type: string
    Mapa:
      type: object
      required:
        - agrupamentosAcademicos
        - agrupamentosCursos
      properties:
        agrupamentosAcademicos:
          type: array
          items:
            $ref: '#/components/schemas/AgrupamentoAcademico'
        agrupamentosCursos:
          type: array
          items:
            $ref: '#/components/schemas/AgrupamentoCurso'
    ParametrosMapa:
      type: object
      required: 
        - unidadeId
        - periodoLetivoId
      properties:
        unidadeId: 
          type: integer
          format: int32
        periodoLetivoId:
          type: integer
          format: int32
    ParametrosFiltros:
      type: object
      required: 
        - cursoId
      properties:
        cursoId: 
          type: integer
          format: int32
    ParametrosInscricao:
      allOf:
        - $ref: "#/components/schemas/ParametrosMapa"
        - type: object
          required: 
            - inscricoes
          properties:
            inscricoes:
              type: array
              items:
                $ref: "#/components/schemas/DadosInscricao"
    ParametrosInscricaoTurmas:
      type: object
      required: 
        - simuladoId
        - cursoId
        - turmas
      properties:
        simuladoId:
          type: integer
          format: int32
        cursoId:
          type: integer
          format: int32
        turmas:
          type: array
          items:
            type: integer
            format: int32
    ParametrosInscricaoAlunos:
      type: object
      required: 
        - simuladoId
        - turmaId
        - alunos
      properties:
        simuladoId:
          type: integer
          format: int32
        turmaId:
          type: integer
          format: int32
        alunos:
          type: array
          items:
            type: integer
            format: int32
    ParametrosTurmasInscritas:
      type: object
      required: 
        - cursoId
        - simuladoId
      properties:
        cursoId:
          type: integer
          format: int32
        classeId:
          type: integer
          format: int32
    ParametrosAlunosInscritos:
      type: object
      required: 
        - simuladoId
        - turmaId
      properties:
        simuladoId:
          type: integer
          format: int32
        turmaId:
          type: integer
          format: int32
