openapi: 3.0.1
info:
  title: FlashMobile API Documentación
  description: REST API para la aplicación de FlashMobile
  contact:
    name: Billy Larru
    email: billy.larru@insolutions.pe
  version: v1
paths:
  /api/v1/auth:
    post:
      tags:
        - Auth
      summary: Obtener token
      description: "El token obtenido debe ser utilizado durante todo el siguiente flujo:\r\n\r\n1.- Verificar DNI\r\n\r\n2.- Validación iccid\r\n\r\n3.- Consulta de las mejores huellas\r\n\r\n4.- Validación biométrica\r\n\r\n5.- Registro de datos del cliente\r\n\r\n\r\n\r\n\r\n\r\nObtenga el token por cada usuario que inicie el flujo, el token tiene un tiempo de vida de una hora, tiempo necesario para completar el proceso descrito.\r\n\r\n\r\n\r\n\r\n\r\n**Posibles códigos de respuesta:**\r\n\r\n0000000000 - OK (successful HTTP Status 200)\r\n\r\n1111111111 - Error en el servidor (error del servidor HTTP estado 500)\r\n\r\n2222222222 - Operación Fallida ( error del cliente y/o servidor estado 500)\r\n\r\n4040001001 - La petición es invalida (error del cliente HTTP estado 400)\r\n\r\n4040001002 - Credenciales invalidas (error del cliente HTTP estado 400)\r\n\r\n4040001003 - Error de validación de datos de entrada.\r\n\r\n4050001001 - Error interno (error del servidor HTTP estado 500)\r\n\r\n4050001002 - Error en la BD (error del servidor HTTP estado 500)"
      requestBody:
        description: ''
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /api/v1/biometrics/best:
    post:
      tags:
        - Biometric
      summary: Consulta de las mejores huellas
      description: "**Posibles códigos de respuesta:**\r\n\r\n 0000000000 - OK (successful HTTP Status 200)\r\n \r\n 1111111111 - Error en el servidor (error del servidor HTTP estado 500)\r\n \r\n 2222222222 - Operación Fallida ( error del cliente y/o servidor estado 500)\r\n \r\n 0040400000 - Token no encontrado ( error del cliente HTTP estado 400)\r\n \r\n 0044000000 - Token expirado ( error del cliente HTTP estado 400)\r\n \r\n 0040100000 - Token inválido ( error del cliente HTTP estado 400)\r\n \r\n 3020001001 - Es probable que se detecte la huella de los dedos indices.(succesful HTTP status 200)\r\n \r\n 3040001001 - La petición es inválida. ( error del cliente HTTP estado 400)\r\n \r\n 3040001002 - Sin registro de huellas de mejor calidad.(error del cliente HTTP estado 400)\r\n \r\n 3040001003 - Error de validación de datos de entrada.\r\n \r\n 3050001001 - Error interno ( error del servidor HTTP estado 500)\r\n \r\n 3050001002 - Error en la BD( error del servidor HTTP estado 500)\r\n \r\n 3050001003 - Error de configuración del servidor. (error del servidor HTTP estado 500)\r\n \r\n 3050001004 - Error del servicio de RENIEC (error del servidor HTTP estado 500)"
      parameters:
        - name: token
          in: header
          description: ''
          required: true
          schema:
            type: string
      requestBody:
        description: ''
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/BiometricBestRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/BiometricBestRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/BiometricBestRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/BiometricBestRequest'
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiometricBestResponse'
  /api/v1/biometrics/validation:
    post:
      tags:
        - Biometric
      summary: Validación biométrica
      description: "**Posibles códigos de respuesta:**\r\n\r\n 0000000000 - OK (successful HTTP Status 200)\r\n \r\n 1111111111 - Error en el servidor (error del servidor HTTP estado 500)\r\n \r\n 2222222222 - Operación Fallida ( error del cliente y/o servidor estado 500)\r\n \r\n 0040400000 - Token no encontrado ( error del cliente HTTP estado 400)\r\n \r\n 0044000000 - Token expirado ( error del cliente HTTP estado 400)\r\n \r\n 0040100000 - Token inválido ( error del cliente HTTP estado 400)\r\n \r\n 3040002001 - La petición es inválida. ( error del cliente HTTP estado 400)\r\n \r\n 3040002002 - La huella recibida no coincide con la huella del dni ingresado. ( error del cliente HTTP estado 400)\r\n \r\n 3040002003 - Error de validación de datos de entrada. ( error del cliente)\r\n \r\n 3050002001 - Error interno. ( error del servidor HTTP estado 500)\r\n \r\n 3050002002 - Error en la BD( error del servidor HTTP estado 500)\r\n \r\n 3050002003 - Error de configuración del servidor. (error del servidor HTTP estado 500)\r\n \r\n 3050002004 - Error del servicio de RENIEC (error del servidor HTTP estado 500)\r\n \r\n 3050002006 - El dni ingresado no existe en la base de datos del RENIEC."
      parameters:
        - name: token
          in: header
          description: ''
          required: true
          schema:
            type: string
      requestBody:
        description: ''
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/BiometricValidationRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/BiometricValidationRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/BiometricValidationRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/BiometricValidationRequest'
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BiometricValidationResponse'
  '/api/v1/simcards/{iccid}':
    get:
      tags:
        - SimCard
      summary: ICCID a validar por parte de FlashMobile
      description: "**Posibles códigos de respuesta:**\r\n\r\n0000000000 - OK (successful HTTP Status 200)\r\n\r\n1111111111 - Error en el servidor (error del servidor HTTP estado 500)\r\n\r\n2222222222 - Operación Fallida ( error del cliente y/o servidor estado 500)\r\n\r\n0040400000 - Token no encontrado ( error del cliente HTTP estado 400)\r\n\r\n0044000000 - Token expirado ( error del cliente HTTP estado 400)\r\n\r\n0040100000 - Token inválido ( error del cliente HTTP estado 400)\r\n\r\n1040001001 - La petición es invalida (error del cliente HTTP estado 400)\r\n\r\n1040001002 - ICCID invalido (error del cliente HTTP estado 400)\r\n\r\n1040001003 - Iccid no activado.\r\n\r\n1040001004 - Error de validación de datos de entrada. (error del cliente)\r\n\r\n1040401001 - ICCID no existe en la BD (error del cliente HTTP estado 400)\r\n\r\n1050001001 - Error interno (error del servidor HTTP estado 500)\r\n\r\n1050001002 - Error en la BD (error del servidor HTTP estado 500)"
      parameters:
        - name: token
          in: header
          description: Token de acceso a la API
          required: true
          schema:
            type: string
        - name: iccid
          in: path
          description: Número ICCID del SIM Card
          required: true
          schema:
            pattern: '^[0-9-]*$'
            type: string
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyIccidResponse'
  '/api/v1/users/{dni}':
    get:
      tags:
        - User
      summary: Se valida que el DNI se encuentre registrado en la BD de FlashMobile
      description: "**Posibles códigos de respuesta:**\r\n\r\n0000000000 - OK (successful HTTP Status 200)\r\n\r\n1111111111 - Error en el servidor (error del servidor HTTP estado 500)\r\n\r\n2222222222 - Operación Fallida ( error del cliente y/o servidor estado 500)\r\n\r\n0040400000 - Token no encontrado ( error del cliente HTTP estado 400)\r\n\r\n0044000000 - Token expirado ( error del cliente HTTP estado 400)\r\n\r\n0040100000 - Token inválido ( error del cliente HTTP estado 400)\r\n\r\n2040001001 - La petición es invalida (error del cliente HTTP estado 400)\r\n\r\n2040001002 - DNI invalido (error del cliente HTTP estado 400)\r\n\r\n2040001003 - Error de validación de datos de entrada.\r\n            \r\n2040401001 - DNI no existe en la BD (error del cliente HTTP estado 400)\r\n\r\n2050001001 - Error interno (error del servidor HTTP estado 500)\r\n\r\n2050001002 - Error en la BD (error del servidor HTTP estado 500)"
      parameters:
        - name: token
          in: header
          description: Token de acceso a la API
          required: true
          schema:
            type: string
        - name: dni
          in: path
          description: Número de DNI
          required: true
          schema:
            maxLength: 8
            minLength: 8
            pattern: '^[0-9-]*$'
            type: string
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyDniResponse'
  /api/v1/users:
    post:
      tags:
        - User
      summary: "Se registra datos personales, datos de portabilidad(si lo solicita el usuario),\r\nvalidación biometrica y validación ICCID"
      description: "**Posibles códigos de respuesta:**\r\n\r\n0000000000 - OK (successful HTTP Status 200)\r\n\r\n1111111111 - Error en el servidor (error del servidor HTTP estado 500)\r\n\r\n2222222222 - Operación Fallida ( error del cliente y/o servidor estado 500)\r\n\r\n0040400000 - Token no encontrado ( error del cliente HTTP estado 400)\r\n\r\n0044000000 - Token expirado ( error del cliente HTTP estado 400)\r\n\r\n0040100000 - Token inválido ( error del cliente HTTP estado 400)\r\n\r\n2040002001 - La petición es invalida (error del cliente HTTP estado 400)\r\n\r\n2040002002 - El máximo de solicitudes de activación con este dni ya se ha alcanzado.( Máximo se puede tener 5 solicitudes de activación)\r\n\r\n2040002003 - Error de validación de datos de entrada.\r\n\r\n2050002001 - Error interno (error del servidor HTTP estado 500)\r\n\r\n2050002002 - Error en la BD (error del servidor HTTP estado 500)"
      parameters:
        - name: token
          in: header
          description: Token de acceso a la API
          required: true
          schema:
            type: string
      requestBody:
        description: ''
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/ConsolidatedDataRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/ConsolidatedDataRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/ConsolidatedDataRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ConsolidatedDataRequest'
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsolidatedDataResponse'
components:
  schemas:
    AuthRequest:
      required:
        - password
        - username
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      additionalProperties: false
    AuthResponse:
      type: object
      properties:
        message:
          type: string
          nullable: true
          readOnly: true
        code:
          type: string
          description: Código de respuesta
          nullable: true
        status:
          type: integer
          description: "Estado del proceso\r\n\r\n0 - Proceso exitoso\r\n\r\n1 - Error\r\n\r\n2 - Falló"
          format: int32
        data:
          type: object
          additionalProperties: false
          description: Información que el servicio retornará en el caso que sea necesario
          nullable: true
      additionalProperties: false
    BiometricBestRequest:
      required:
        - dni
      type: object
      properties:
        dni:
          maxLength: 8
          minLength: 8
          pattern: '^[0-9-]*$'
          type: string
      additionalProperties: false
    BiometricBestResponse:
      type: object
      properties:
        message:
          type: string
          nullable: true
          readOnly: true
        code:
          type: string
          description: Código de respuesta
          nullable: true
        status:
          type: integer
          description: "Estado del proceso\r\n\r\n0 - Proceso exitoso\r\n\r\n1 - Error\r\n\r\n2 - Falló"
          format: int32
        data:
          type: object
          additionalProperties: false
          description: Información que el servicio retornará en el caso que sea necesario
          nullable: true
      additionalProperties: false
    BiometricValidationRequest:
      required:
        - dniCliente
        - rawBase64
        - rawHeight
        - rawWidth
      type: object
      properties:
        dniCliente:
          maxLength: 8
          minLength: 8
          pattern: '^[0-9-]*$'
          type: string
        rawBase64:
          type: string
        rawHeight:
          type: string
        rawWidth:
          type: string
      additionalProperties: false
    BiometricValidationResponse:
      type: object
      properties:
        message:
          type: string
          nullable: true
          readOnly: true
        code:
          type: string
          description: Código de respuesta
          nullable: true
        status:
          type: integer
          description: "Estado del proceso\r\n\r\n0 - Proceso exitoso\r\n\r\n1 - Error\r\n\r\n2 - Falló"
          format: int32
        data:
          type: object
          additionalProperties: false
          description: Información que el servicio retornará en el caso que sea necesario
          nullable: true
      additionalProperties: false
    VerifyIccidResponse:
      type: object
      properties:
        message:
          type: string
          nullable: true
          readOnly: true
        code:
          type: string
          description: Código de respuesta
          nullable: true
        status:
          type: integer
          description: "Estado del proceso\r\n\r\n0 - Proceso exitoso\r\n\r\n1 - Error\r\n\r\n2 - Falló"
          format: int32
        data:
          type: object
          additionalProperties: false
          description: Información que el servicio retornará en el caso que sea necesario
          nullable: true
      additionalProperties: false
    VerifyDniResponse:
      type: object
      properties:
        message:
          type: string
          nullable: true
          readOnly: true
        code:
          type: string
          description: Código de respuesta
          nullable: true
        status:
          type: integer
          description: "Estado del proceso\r\n\r\n0 - Proceso exitoso\r\n\r\n1 - Error\r\n\r\n2 - Falló"
          format: int32
        data:
          type: object
          additionalProperties: false
          description: Información que el servicio retornará en el caso que sea necesario
          nullable: true
      additionalProperties: false
    ConsolidatedDataRequest:
      required:
        - birthDate
        - dni
        - email
        - formStatus
        - iccid
        - lastName
        - name
        - validationBiometric
        - validationBiometricDate
        - wantPortability
      type: object
      properties:
        formId:
          type: string
          description: "Id del Formulario\r\n            \r\n- Id obtenido del resultado del servicio de validación de DNI( /users/{dni} )\r\n            \r\n- Es nulo(null) en caso de que el usuario no se haya pre-registrado por la web de FlashMobile"
          nullable: true
        dni:
          maxLength: 8
          minLength: 8
          pattern: '^[0-9-]*$'
          type: string
          description: Número de DNI del cliente(8 dígitos)
        formStatus:
          pattern: ^(completed|rejected bio|rejected iccid)*$
          type: string
          description: "Estado de la solicitud del cliente:\r\n\r\n-completed (Completado, cuando la biometría es OK y la validación del icc es OK)\r\n\r\n-rejected bio (Falló al validar biometria)\r\n\r\n-rejected iccid (Falló en los escaneos o en  el ingreso de iccid)"
        iccid:
          pattern: '^[0-9-]*$'
          type: string
          description: Número ICCID(19 dígitos)
        name:
          type: string
          description: Nombres del cliente
        lastName:
          type: string
          description: Apellidos del cliente
        birthDate:
          pattern: '^([0-9]{4})-([0-9]{2})-([0-9]{2})$'
          type: string
          description: Fecha de nacimiento en formato yyyy-MM-dd
        email:
          type: string
          description: email del cliente
          format: email
        sponsorTeamId:
          type: string
          description: Id del sponsor que recomienda a este cliente(campo opcional)
          nullable: true
        wantPortability:
          type: boolean
          description: booleano que indica si el cliente quiere portabilidad
        phoneNumber:
          pattern: '^(|[0-9]{9})$'
          type: string
          description: Número de telefono que quiere mantener el cliente en caso de portabilidad
          nullable: true
        currentCompany:
          pattern: ^(|Bitel|Claro|Cuy|Movistar|Entel)$
          type: string
          description: "La operadora actual del cliente en caso de portabilidad (Bitel, Claro, Cuy, Movistar o Entel)\r\nEn caso de no portabilidad enviar una cadena vacía."
          nullable: true
        planType:
          pattern: ^(|Prepaid|Postpaid)$
          type: string
          description: Tipo de plan(Prepaid o Postpaid)
          nullable: true
          example: Prepaid (prepago)
        validationBiometric:
          type: boolean
          description: booleano que indica el resultado de la validación biométrica
        validationBiometricDate:
          pattern: '^([0-9]{4})-([0-9]{2})-([0-9]{2}) ([0-9]{2}):([0-9]{2}):([0-9]{2})$'
          type: string
          description: 'Fecha en que se completó la validación biométrica, en formato yyyy-MM-dd HH:mm:ss'
      additionalProperties: false
    ConsolidatedDataResponse:
      type: object
      properties:
        message:
          type: string
          nullable: true
          readOnly: true
        code:
          type: string
          description: Código de respuesta
          nullable: true
        status:
          type: integer
          description: "Estado del proceso\r\n\r\n0 - Proceso exitoso\r\n\r\n1 - Error\r\n\r\n2 - Falló"
          format: int32
        data:
          type: object
          additionalProperties: false
          description: Información que el servicio retornará en el caso que sea necesario
          nullable: true
      additionalProperties: false
