openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
# Added by API Auto Mocking Plugin
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/SwaggerTest5/CreateTemplateSchedule/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/SwaggerTest5/CreateTemplateSchedule
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/SwaggerTest5/CreateTemplateSchedule
info:
  description: This is a simple API
  version: "1.0.0"
  title: Template Schedule API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: POST_PUT_DELETE
    description: Other than Get
  - name: GET_METHODS
    description: Operations available to get and search
paths:
  /v3/offers/scheduledTemplate/:
    get:
      tags:
        - GET_METHODS
      summary: searches scheduled templates
      operationId: searchTemplateSchedule
      description: |
        By passing in the appropriate options, you can search for
        available scheduled template in the system
      parameters:
        - in: query
          name: scheduleName
          description: pass an optional search name string for looking up schedule template
          required: false
          schema:
            type: string
        - in: query
          name: scheduleStartDate
          description: pass an optional date for looking up schedule template within a period
          required: false
          schema:
            type: string            
            format: datetime
        - in: query
          name: skip
          description: number of records to skip for pagination
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: limit
          description: maximum number of records to return
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScheduleTemplate'
        '400':
          description: bad input parameter
        '503':
          description: internal server error        
    post:
      tags:
        - POST_PUT_DELETE
      summary: adds an template schedule item
      operationId: addTemplate Schedule
      description: Adds an item to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleTemplate'
        description: Template Schedule item to add
  /v3/offers/scheduledTemplate/{scheduleId}:
    put:
      tags:
        - POST_PUT_DELETE
      summary: update scheduled template
      operationId: updateTemplateScheduleById
      description: |
        this will update the given template schedule
      parameters:
        - in: path
          name: scheduleId
          description: pass an optional search string for looking up schedule template
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateScheduleTemplate'            
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/ScheduleTemplate'
        '400':
          description: bad input parameter
        '503':
          description: internal server error    
    delete:
      tags:
        - POST_PUT_DELETE
      summary: delete scheduled template
      operationId: deleteTemplateScheduleById
      description: |
        this will delete the given template schedule
      parameters:
        - in: path
          name: scheduleId
          description: pass an optional search string for looking up schedule template
          required: true
          schema:
            type: string
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/ScheduleTemplate'
        '400':
          description: bad input parameter
        '503':
          description: internal server error      
    get:
      tags:
        - GET_METHODS
      summary: searches scheduled templates
      operationId: getTemplateScheduleById
      description: |
        By passing in the scheduleId the specific schedule with will returned.
      parameters:
        - in: path
          name: scheduleId
          description: pass an optional search string for looking up schedule template
          required: true
          schema:
            type: string
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/ScheduleTemplate'
        '400':
          description: bad input parameter
        '503':
          description: internal server error           
components:
  schemas:
    UpdateScheduleTemplate:
      type: object
      required:
        - name
        - description
        - scheduleDateTime
        - offers
      properties:
        name:
          type: string
          example: MyOfferSchedule
        description:
          type: string
          example: My Offer Schedule Description
        scheduleDateTime:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        templateOffers:
          type: array
          items:
            $ref: '#/components/schemas/OfferTemplate'  
    ScheduleTemplate:
      type: object
      required:
        - name
        - description
        - scheduleId
        - scheduleDateTime
        - offers
      properties:
        name:
          type: string
          example: MyOfferSchedule
        description:
          type: string
          example: My Offer Schedule Description
        scheduleid:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        scheduleDateTime:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        templateOffers:
          type: array
          items:
            $ref: '#/components/schemas/OfferTemplate'
    OfferTemplate:
      required:
        - campaignId
        - catalogueId
        - templateId
        - venueIds
        - startDateTime
        - endDateTime
      properties:
        campaignId:
          type: integer
          example: 15326
        scheduleid:
          type: string
          format: uuid
          example: c45c1f04-8fa2-4428-aa05-2cdc82c4dd49 
        templateId:
          type: integer
          example: 13239 
        venueIds:          
          type: array
          items:
            type: integer
          example: [3101, 6924, 6925]          
      type: object
